Alaris: Alaris.Test.Unit.TSUN022A Class Reference
Alaris.Test.Unit.TSUN022A Class Reference sealed
Unit tests for the NYSE trading calendar (STCL001A).
Public Member Functions
void IsBusinessDay_Weekend_ReturnsFalse ()
Verifies weekends are not business days.
void IsBusinessDay_Weekday_ReturnsTrue ()
Verifies weekdays are business days (when not holidays).
void IsBusinessDay_NyseHoliday_ReturnsFalse (int year, int month, int day, string holiday)
Verifies NYSE holidays are not business days.
void GetBusinessDaysBetween_OneWeek_ReturnsFiveDays ()
Verifies business days calculation excludes weekends.
void GetBusinessDaysBetween_SameDay_ReturnsZero ()
Verifies business days calculation handles same day correctly.
void GetBusinessDaysBetween_ReversedDates_ReturnsZero ()
Verifies business days calculation handles reversed dates.
void GetTimeToExpiryInYears_VsApproximation_DiffersNearHolidays ()
Verifies time-to-expiry calculation with calendar is more accurate than approximation.
void GetTimeToExpiryInYears_TwoWeeks_IsApproximatelyTenDays ()
Verifies typical 2-week expiry calculation.
Private Attributes
readonly STCL001A _calendar = new()
Detailed Description
Unit tests for the NYSE trading calendar (STCL001A).
Tests validate that the calendar correctly excludes weekends and holidays.
Definition at line 15 of file TSUN022A.cs.
Member Function Documentation
GetBusinessDaysBetween_OneWeek_ReturnsFiveDays()
void Alaris.Test.Unit.TSUN022A.GetBusinessDaysBetween_OneWeek_ReturnsFiveDays () inline
Verifies business days calculation excludes weekends.
Definition at line 69 of file TSUN022A.cs.
References Alaris.Test.Unit.TSUN022A._calendar, and Alaris.Strategy.Calendar.STCL001A.GetBusinessDaysBetween().
GetBusinessDaysBetween_ReversedDates_ReturnsZero()
void Alaris.Test.Unit.TSUN022A.GetBusinessDaysBetween_ReversedDates_ReturnsZero () inline
Verifies business days calculation handles reversed dates.
Definition at line 94 of file TSUN022A.cs.
References Alaris.Test.Unit.TSUN022A._calendar, and Alaris.Strategy.Calendar.STCL001A.GetBusinessDaysBetween().
GetBusinessDaysBetween_SameDay_ReturnsZero()
void Alaris.Test.Unit.TSUN022A.GetBusinessDaysBetween_SameDay_ReturnsZero () inline
Verifies business days calculation handles same day correctly.
Definition at line 83 of file TSUN022A.cs.
References Alaris.Test.Unit.TSUN022A._calendar, and Alaris.Strategy.Calendar.STCL001A.GetBusinessDaysBetween().
GetTimeToExpiryInYears_TwoWeeks_IsApproximatelyTenDays()
void Alaris.Test.Unit.TSUN022A.GetTimeToExpiryInYears_TwoWeeks_IsApproximatelyTenDays () inline
Verifies typical 2-week expiry calculation.
Definition at line 130 of file TSUN022A.cs.
References Alaris.Test.Unit.TSUN022A._calendar, and Alaris.Strategy.Calendar.STCL001A.GetTimeToExpiryInYears().
GetTimeToExpiryInYears_VsApproximation_DiffersNearHolidays()
void Alaris.Test.Unit.TSUN022A.GetTimeToExpiryInYears_VsApproximation_DiffersNearHolidays () inline
Verifies time-to-expiry calculation with calendar is more accurate than approximation.
Definition at line 109 of file TSUN022A.cs.
References Alaris.Test.Unit.TSUN022A._calendar, and Alaris.Strategy.Calendar.STCL001A.GetTimeToExpiryInYears().
IsBusinessDay_NyseHoliday_ReturnsFalse()
void Alaris.Test.Unit.TSUN022A.IsBusinessDay_NyseHoliday_ReturnsFalse (int year, int month, int day, string holiday) inline
Verifies NYSE holidays are not business days.
Definition at line 57 of file TSUN022A.cs.
References Alaris.Test.Unit.TSUN022A._calendar, and Alaris.Strategy.Calendar.STCL001A.IsBusinessDay().
IsBusinessDay_Weekday_ReturnsTrue()
void Alaris.Test.Unit.TSUN022A.IsBusinessDay_Weekday_ReturnsTrue () inline
Verifies weekdays are business days (when not holidays).
Definition at line 38 of file TSUN022A.cs.
References Alaris.Test.Unit.TSUN022A._calendar, and Alaris.Strategy.Calendar.STCL001A.IsBusinessDay().
IsBusinessDay_Weekend_ReturnsFalse()
void Alaris.Test.Unit.TSUN022A.IsBusinessDay_Weekend_ReturnsFalse () inline
Verifies weekends are not business days.
Definition at line 23 of file TSUN022A.cs.
References Alaris.Test.Unit.TSUN022A._calendar, and Alaris.Strategy.Calendar.STCL001A.IsBusinessDay().
Member Data Documentation
_calendar
readonly STCL001A Alaris.Test.Unit.TSUN022A._calendar = new() private
Definition at line 17 of file TSUN022A.cs.
Referenced by Alaris.Test.Unit.TSUN022A.GetBusinessDaysBetween_OneWeek_ReturnsFiveDays(), Alaris.Test.Unit.TSUN022A.GetBusinessDaysBetween_ReversedDates_ReturnsZero(), Alaris.Test.Unit.TSUN022A.GetBusinessDaysBetween_SameDay_ReturnsZero(), Alaris.Test.Unit.TSUN022A.GetTimeToExpiryInYears_TwoWeeks_IsApproximatelyTenDays(), Alaris.Test.Unit.TSUN022A.GetTimeToExpiryInYears_VsApproximation_DiffersNearHolidays(), Alaris.Test.Unit.TSUN022A.IsBusinessDay_NyseHoliday_ReturnsFalse(), Alaris.Test.Unit.TSUN022A.IsBusinessDay_Weekday_ReturnsTrue(), and Alaris.Test.Unit.TSUN022A.IsBusinessDay_Weekend_ReturnsFalse().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN022A.cs