Alaris: Alaris.Test.Unit.Core.Time.CRTM005ATests Class Reference
Alaris.Test.Unit.Core.Time.CRTM005ATests Class Reference
Public Member Functions
void Constructor_ValidDate_CreatesCorrectSerialNumber ()
void Constructor_LeapYear_Feb29Valid ()
void FromDateTime_RoundTrips ()
void Subtraction_TwoDates_ReturnsDaysBetween ()
void AddDays_30Days_ReturnsCorrectDate ()
void AddDays_CrossingYearBoundary_Works ()
void AddDays_Negative_SubtractsDays ()
void Comparison_EarlierDate_IsLess ()
void Equality_SameDate_AreEqual ()
void DayOfWeek_KnownDate_ReturnsCorrect ()
void DayOfWeek_Saturday_IsWeekend ()
void DayOfWeek_Wednesday_IsNotWeekend ()
Detailed Description
Definition at line 9 of file CRTM005ATests.cs.
Member Function Documentation
AddDays_30Days_ReturnsCorrectDate()
void Alaris.Test.Unit.Core.Time.CRTM005ATests.AddDays_30Days_ReturnsCorrectDate () inline
Definition at line 60 of file CRTM005ATests.cs.
References Alaris.Core.Time.CRTM005A.AddDays(), Alaris.Core.Time.CRTM005A.Day, and Alaris.Core.Time.CRTM005A.Month.
AddDays_CrossingYearBoundary_Works()
void Alaris.Test.Unit.Core.Time.CRTM005ATests.AddDays_CrossingYearBoundary_Works () inline
Definition at line 70 of file CRTM005ATests.cs.
References Alaris.Core.Time.CRTM005A.AddDays(), Alaris.Core.Time.CRTM005A.Month, and Alaris.Core.Time.CRTM005A.Year.
AddDays_Negative_SubtractsDays()
void Alaris.Test.Unit.Core.Time.CRTM005ATests.AddDays_Negative_SubtractsDays () inline
Definition at line 80 of file CRTM005ATests.cs.
References Alaris.Core.Time.CRTM005A.AddDays(), and Alaris.Core.Time.CRTM005A.Month.
Comparison_EarlierDate_IsLess()
void Alaris.Test.Unit.Core.Time.CRTM005ATests.Comparison_EarlierDate_IsLess () inline
Definition at line 93 of file CRTM005ATests.cs.
Constructor_LeapYear_Feb29Valid()
void Alaris.Test.Unit.Core.Time.CRTM005ATests.Constructor_LeapYear_Feb29Valid () inline
Definition at line 25 of file CRTM005ATests.cs.
Constructor_ValidDate_CreatesCorrectSerialNumber()
void Alaris.Test.Unit.Core.Time.CRTM005ATests.Constructor_ValidDate_CreatesCorrectSerialNumber () inline
Definition at line 14 of file CRTM005ATests.cs.
DayOfWeek_KnownDate_ReturnsCorrect()
void Alaris.Test.Unit.Core.Time.CRTM005ATests.DayOfWeek_KnownDate_ReturnsCorrect () inline
Definition at line 121 of file CRTM005ATests.cs.
DayOfWeek_Saturday_IsWeekend()
void Alaris.Test.Unit.Core.Time.CRTM005ATests.DayOfWeek_Saturday_IsWeekend () inline
Definition at line 130 of file CRTM005ATests.cs.
DayOfWeek_Wednesday_IsNotWeekend()
void Alaris.Test.Unit.Core.Time.CRTM005ATests.DayOfWeek_Wednesday_IsNotWeekend () inline
Definition at line 139 of file CRTM005ATests.cs.
Equality_SameDate_AreEqual()
void Alaris.Test.Unit.Core.Time.CRTM005ATests.Equality_SameDate_AreEqual () inline
Definition at line 106 of file CRTM005ATests.cs.
FromDateTime_RoundTrips()
void Alaris.Test.Unit.Core.Time.CRTM005ATests.FromDateTime_RoundTrips () inline
Definition at line 35 of file CRTM005ATests.cs.
References Alaris.Core.Time.CRTM005A.FromDateTime(), and Alaris.Core.Time.CRTM005A.ToDateTime().
Subtraction_TwoDates_ReturnsDaysBetween()
void Alaris.Test.Unit.Core.Time.CRTM005ATests.Subtraction_TwoDates_ReturnsDaysBetween () inline
Definition at line 49 of file CRTM005ATests.cs.
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/Core/Time/CRTM005ATests.cs