Alaris: Alaris.Strategy.Core.Numerical.STPR007A Class Reference
Alaris.Strategy.Core.Numerical.STPR007A Class Reference
Brent's method root-finding algorithm. Combines bisection, secant, and inverse quadratic interpolation.
Public Member Functions
readonly record struct RootResult (double Root, double FunctionValue, int Iterations, bool Converged)
Result of root-finding operation.
Static Public Member Functions
static double FindRoot (Func< double, double > f, double a, double b, double tolerance=DefaultTolerance, int maxIterations=DefaultMaxIterations)
Finds a root of f(x) = 0 in the interval [a, b] using Brent's method.
static RootResult FindRootWithInfo (Func< double, double > f, double a, double b, double tolerance=DefaultTolerance, int maxIterations=DefaultMaxIterations)
Finds root with detailed result including convergence info.
static double SolveImpliedVolatility (Func< double, double > priceFunction, double targetPrice, double minVol=0.001, double maxVol=5.0, double tolerance=1e-8)
Solves for implied volatility given a pricing function. Specialized convenience method for IV solving.
Static Private Attributes
const int DefaultMaxIterations = 100
const double DefaultTolerance = 1e-10
const double MachineEpsilon = 2.220446049250313e-16
Detailed Description
Brent's method root-finding algorithm. Combines bisection, secant, and inverse quadratic interpolation.
Definition at line 13 of file STPR007A.cs.
Member Function Documentation
FindRoot()
static double Alaris.Strategy.Core.Numerical.STPR007A.FindRoot (Func< double, double > f, double a, double b, double tolerance = DefaultTolerance, int maxIterations = DefaultMaxIterations) inline static
Finds a root of f(x) = 0 in the interval [a, b] using Brent's method.
Parameters
f Function whose root is sought.
a Lower bound of bracket.
b Upper bound of bracket.
tolerance Convergence tolerance.
maxIterations Maximum iterations.
Returns
Root x such that f(x) ≈ 0.
Exceptions
ArgumentException If f(a) and f(b) have same sign.
Definition at line 29 of file STPR007A.cs.
References Alaris.Strategy.Core.Numerical.STPR007A.MachineEpsilon.
Referenced by Alaris.Strategy.Core.Numerical.STPR007A.SolveImpliedVolatility().
FindRootWithInfo()
static RootResult Alaris.Strategy.Core.Numerical.STPR007A.FindRootWithInfo (Func< double, double > f, double a, double b, double tolerance = DefaultTolerance, int maxIterations = DefaultMaxIterations) inline static
Finds root with detailed result including convergence info.
Definition at line 142 of file STPR007A.cs.
References Alaris.Strategy.Core.Numerical.STPR007A.MachineEpsilon, and Alaris.Strategy.Core.Numerical.STPR007A.RootResult().
RootResult()
readonly record struct Alaris.Strategy.Core.Numerical.STPR007A.RootResult (double Root, double FunctionValue, int Iterations, bool Converged)
Result of root-finding operation.
Referenced by Alaris.Strategy.Core.Numerical.STPR007A.FindRootWithInfo().
SolveImpliedVolatility()
static double Alaris.Strategy.Core.Numerical.STPR007A.SolveImpliedVolatility (Func< double, double > priceFunction, double targetPrice, double minVol = 0::001, double maxVol = 5::0, double tolerance = 1e-8) inline static
Solves for implied volatility given a pricing function. Specialized convenience method for IV solving.
Parameters
priceFunction BS price as function of volatility.
targetPrice Target option price.
minVol Minimum volatility bound.
maxVol Maximum volatility bound.
tolerance Convergence tolerance.
Returns
Implied volatility.
Definition at line 243 of file STPR007A.cs.
References Alaris.Strategy.Core.Numerical.STPR007A.FindRoot().
Referenced by Alaris.Strategy.Core.STPR003A.ComputeImpliedVolatility(), and Alaris.Strategy.Core.STPR006A.ComputeImpliedVolatility().
Member Data Documentation
DefaultMaxIterations
const int Alaris.Strategy.Core.Numerical.STPR007A.DefaultMaxIterations = 100 static private
Definition at line 15 of file STPR007A.cs.
DefaultTolerance
const double Alaris.Strategy.Core.Numerical.STPR007A.DefaultTolerance = 1e-10 static private
Definition at line 16 of file STPR007A.cs.
MachineEpsilon
const double Alaris.Strategy.Core.Numerical.STPR007A.MachineEpsilon = 2.220446049250313e-16 static private
Definition at line 17 of file STPR007A.cs.
Referenced by Alaris.Strategy.Core.Numerical.STPR007A.FindRoot(), and Alaris.Strategy.Core.Numerical.STPR007A.FindRootWithInfo().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Core/Numerical/STPR007A.cs