Alaris: Alaris.Strategy.Hedge.STHD001A Class Reference
Alaris.Strategy.Hedge.STHD001A Class Reference sealed
Analyses the correlation between front-month and back-month implied volatility changes to assess calendar spread vega independence.
Public Member Functions
STHD001A (double maxAcceptableCorrelation=DefaultMaxCorrelation, int minimumObservations=DefaultMinimumObservations, ILogger< STHD001A >? logger=null)
Initialises a new instance of the vega correlation analyser.
STHD002A Analyse (string symbol, IReadOnlyList< double > frontIVChanges, IReadOnlyList< double > backIVChanges)
Analyses the correlation between front-month and back-month IV changes.
STHD002A AnalyseFromLevels (string symbol, IReadOnlyList< double > frontIVHistory, IReadOnlyList< double > backIVHistory)
Analyses correlation from historical IV time series.
Static Public Member Functions
static double GetConditionalCorrelationThreshold (double currentVIX)
Gets a VIX-conditional correlation threshold for regime-dependent filtering.
Static Public Attributes
const double DefaultMaxCorrelation = 0.70
Default maximum acceptable correlation coefficient.
const int DefaultMinimumObservations = 20
Default minimum number of observations required.
Private Member Functions
void SafeLog (Action logAction)
Safely executes logging operation with fault isolation (Rule 15).
Static Private Member Functions
static double[] ComputeChanges (IReadOnlyList< double > levels)
Computes daily changes (first differences) from a time series.
static string DetermineInterpretation (double correlation)
Determines a human-readable interpretation of the correlation.
Private Attributes
readonly? ILogger< STHD001A > _logger
readonly double _maxAcceptableCorrelation
readonly int _minimumObservations
Static Private Attributes
static readonly Action< ILogger, string, double, string, Exception?> LogCorrelationResult
static readonly Action< ILogger, string, int, int, Exception?> LogInsufficientData
Detailed Description
Analyses the correlation between front-month and back-month implied volatility changes to assess calendar spread vega independence.
Definition at line 13 of file STHD001A.cs.
Constructor & Destructor Documentation
STHD001A()
Alaris.Strategy.Hedge.STHD001A.STHD001A (double maxAcceptableCorrelation = DefaultMaxCorrelation, int minimumObservations = DefaultMinimumObservations, ILogger< STHD001A >? logger = null) inline
Initialises a new instance of the vega correlation analyser.
Parameters
maxAcceptableCorrelation Maximum acceptable correlation. Default: 0.70.
minimumObservations Minimum observations required. Default: 20.
logger Optional logger instance.
Exceptions
ArgumentOutOfRangeException Thrown when correlation threshold is not in [-1, 1] or observations < 3.
Definition at line 57 of file STHD001A.cs.
References Alaris.Strategy.Hedge.STHD001A._logger, Alaris.Strategy.Hedge.STHD001A._maxAcceptableCorrelation, and Alaris.Strategy.Hedge.STHD001A._minimumObservations.
Member Function Documentation
Analyse()
STHD002A Alaris.Strategy.Hedge.STHD001A.Analyse (string symbol, IReadOnlyList< double > frontIVChanges, IReadOnlyList< double > backIVChanges) inline
Analyses the correlation between front-month and back-month IV changes.
Parameters
symbol The underlying symbol.
frontIVChanges Daily changes in front-month IV.
backIVChanges Daily changes in back-month IV.
Returns
Vega correlation analysis result.
Exceptions
ArgumentNullException Thrown when either IV change array is null.
ArgumentException Thrown when arrays have different lengths.
Definition at line 111 of file STHD001A.cs.
References Alaris.Strategy.Hedge.STHD001A._logger, Alaris.Strategy.Hedge.STHD001A._maxAcceptableCorrelation, Alaris.Strategy.Hedge.STHD001A._minimumObservations, Alaris.Strategy.Hedge.STHD001A.DetermineInterpretation(), Alaris.Strategy.Hedge.STHD001A.LogCorrelationResult, Alaris.Strategy.Hedge.STHD001A.LogInsufficientData, Alaris.Strategy.Hedge.STHD001A.SafeLog(), and Alaris.Strategy.Hedge.STHD002A.
Referenced by Alaris.Strategy.Hedge.STHD001A.AnalyseFromLevels().
AnalyseFromLevels()
STHD002A Alaris.Strategy.Hedge.STHD001A.AnalyseFromLevels (string symbol, IReadOnlyList< double > frontIVHistory, IReadOnlyList< double > backIVHistory) inline
Analyses correlation from historical IV time series.
Parameters
symbol The underlying symbol.
frontIVHistory Front-month IV time series (levels, not changes).
backIVHistory Back-month IV time series (levels, not changes).
Returns
Vega correlation analysis result.
Definition at line 202 of file STHD001A.cs.
References Alaris.Strategy.Hedge.STHD001A.Analyse(), and Alaris.Strategy.Hedge.STHD001A.ComputeChanges().
Referenced by Alaris.Strategy.Hedge.STHD005A.Validate().
ComputeChanges()
static double[] Alaris.Strategy.Hedge.STHD001A.ComputeChanges (IReadOnlyList< double > levels) inline static private
Computes daily changes (first differences) from a time series.
Parameters
levels Time series of levels.
Returns
Array of daily changes.
Definition at line 223 of file STHD001A.cs.
Referenced by Alaris.Strategy.Hedge.STHD001A.AnalyseFromLevels().
DetermineInterpretation()
static string Alaris.Strategy.Hedge.STHD001A.DetermineInterpretation (double correlation) inline static private
Determines a human-readable interpretation of the correlation.
Parameters
correlation The Pearson correlation coefficient.
Returns
Interpretation string.
Definition at line 244 of file STHD001A.cs.
Referenced by Alaris.Strategy.Hedge.STHD001A.Analyse().
GetConditionalCorrelationThreshold()
static double Alaris.Strategy.Hedge.STHD001A.GetConditionalCorrelationThreshold (double currentVIX) inline static
Gets a VIX-conditional correlation threshold for regime-dependent filtering.
Parameters
currentVIX Current VIX level.
Returns
Conditional correlation threshold.
Definition at line 89 of file STHD001A.cs.
Referenced by Alaris.Test.Unit.Phase2MediumPriorityTests.STHD001A_GetConditionalCorrelationThreshold_HighVIX_ReturnsHigher(), and Alaris.Test.Unit.Phase2MediumPriorityTests.STHD001A_GetConditionalCorrelationThreshold_LowVIX_ReturnsBase().
SafeLog()
void Alaris.Strategy.Hedge.STHD001A.SafeLog (Action logAction) inline private
Safely executes logging operation with fault isolation (Rule 15).
Definition at line 261 of file STHD001A.cs.
References Alaris.Strategy.Hedge.STHD001A._logger.
Referenced by Alaris.Strategy.Hedge.STHD001A.Analyse().
Member Data Documentation
_logger
readonly? ILogger<STHD001A> Alaris.Strategy.Hedge.STHD001A._logger private
Definition at line 15 of file STHD001A.cs.
Referenced by Alaris.Strategy.Hedge.STHD001A.STHD001A(), Alaris.Strategy.Hedge.STHD001A.Analyse(), and Alaris.Strategy.Hedge.STHD001A.SafeLog().
_maxAcceptableCorrelation
readonly double Alaris.Strategy.Hedge.STHD001A._maxAcceptableCorrelation private
Definition at line 16 of file STHD001A.cs.
Referenced by Alaris.Strategy.Hedge.STHD001A.STHD001A(), and Alaris.Strategy.Hedge.STHD001A.Analyse().
_minimumObservations
readonly int Alaris.Strategy.Hedge.STHD001A._minimumObservations private
Definition at line 17 of file STHD001A.cs.
Referenced by Alaris.Strategy.Hedge.STHD001A.STHD001A(), and Alaris.Strategy.Hedge.STHD001A.Analyse().
DefaultMaxCorrelation
const double Alaris.Strategy.Hedge.STHD001A.DefaultMaxCorrelation = 0.70 static
Default maximum acceptable correlation coefficient.
Definition at line 36 of file STHD001A.cs.
DefaultMinimumObservations
const int Alaris.Strategy.Hedge.STHD001A.DefaultMinimumObservations = 20 static
Default minimum number of observations required.
Definition at line 42 of file STHD001A.cs.
LogCorrelationResult
readonly Action<ILogger, string, double, string, Exception?> Alaris.Strategy.Hedge.STHD001A.LogCorrelationResult static private
Initial value:
=
        LoggerMessage.Define<string, double, string>(
            LogLevel.Information,
            new EventId(1, nameof(LogCorrelationResult)),
            "Vega correlation for {Symbol}: {Correlation:F4} - {Interpretation}")
Definition at line 20 of file STHD001A.cs.
Referenced by Alaris.Strategy.Hedge.STHD001A.Analyse().
LogInsufficientData
readonly Action<ILogger, string, int, int, Exception?> Alaris.Strategy.Hedge.STHD001A.LogInsufficientData static private
Initial value:
=
        LoggerMessage.Define<string, int, int>(
            LogLevel.Warning,
            new EventId(2, nameof(LogInsufficientData)),
            "Insufficient IV history for {Symbol}: {Actual} observations, required {Required}")
Definition at line 26 of file STHD001A.cs.
Referenced by Alaris.Strategy.Hedge.STHD001A.Analyse().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Hedge/STHD001A.cs