Alaris: Alaris.Infrastructure.Protocol.Buffers.PLBF001A Class Reference
Alaris.Infrastructure.Protocol.Buffers.PLBF001A Class Reference
Thread-safe buffer pool manager for zero-allocation binary serialization. Component ID: PLBF001A.
Static Public Member Functions
static PooledBuffer RentBuffer (int minimumLength=DefaultBufferSize)
Rents a buffer from the shared ArrayPool.
static PooledBuffer RentLargeBuffer ()
Rents a large buffer suitable for option chain snapshots.
Static Public Attributes
const int DefaultBufferSize = 4096
Default buffer size for most market data messages (4KB). Sufficient for individual OptionContract, PriceBar, EarningsEvent.
const int LargeBufferSize = 65536
Large buffer size for option chain snapshots (64KB). Accommodates chains with ~500+ contracts.
const int MaxBufferSize = 1024 * 1024
Maximum buffer size to prevent excessive memory usage (1MB).
Detailed Description
Thread-safe buffer pool manager for zero-allocation binary serialization. Component ID: PLBF001A.
Rule 5 (Zero-Allocation Hot Paths): This class provides reusable byte buffers to avoid heap allocations during message encoding/decoding. All hot path serialization operations should rent buffers from this pool.
Usage:
using var buffer = PLBF001A.RentBuffer(4096);
int bytesWritten = encoder.Encode(message, buffer.Span);
// buffer is automatically returned to pool on dispose
Definition at line 23 of file PLBF001A.cs.
Member Function Documentation
RentBuffer()
static PooledBuffer Alaris.Infrastructure.Protocol.Buffers.PLBF001A.RentBuffer (int minimumLength = DefaultBufferSize) inline static
Rents a buffer from the shared ArrayPool.
Parameters
minimumLength Minimum required buffer size.
Returns
A disposable buffer handle that returns the buffer to the pool on dispose.
Exceptions
ArgumentOutOfRangeException If minimumLength exceeds MaxBufferSize.
Definition at line 48 of file PLBF001A.cs.
References Alaris.Infrastructure.Protocol.Buffers.PLBF001A.MaxBufferSize.
Referenced by Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.LoadBinaryCacheAsync(), Alaris.Test.Unit.TSUN030A.OptionChainSnapshot_RoundTrip_PreservesAllContracts(), Alaris.Test.Unit.TSUN030A.RentBuffer_ReturnsBufferOfAtLeastRequestedSize(), Alaris.Test.Unit.TSUN030A.RentBuffer_WithInvalidSize_Throws(), and Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.SaveOptionChainCacheAsync().
RentLargeBuffer()
static PooledBuffer Alaris.Infrastructure.Protocol.Buffers.PLBF001A.RentLargeBuffer () static
Rents a large buffer suitable for option chain snapshots.
Returns
A disposable buffer handle.
Referenced by Alaris.Test.Unit.TSUN030A.RentLargeBuffer_ReturnsLargeBuffer().
Member Data Documentation
DefaultBufferSize
const int Alaris.Infrastructure.Protocol.Buffers.PLBF001A.DefaultBufferSize = 4096 static
Default buffer size for most market data messages (4KB). Sufficient for individual OptionContract, PriceBar, EarningsEvent.
Definition at line 29 of file PLBF001A.cs.
LargeBufferSize
const int Alaris.Infrastructure.Protocol.Buffers.PLBF001A.LargeBufferSize = 65536 static
Large buffer size for option chain snapshots (64KB). Accommodates chains with ~500+ contracts.
Definition at line 35 of file PLBF001A.cs.
Referenced by Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.LoadBinaryCacheAsync(), Alaris.Test.Unit.TSUN030A.OptionChainSnapshot_RoundTrip_PreservesAllContracts(), Alaris.Test.Unit.TSUN030A.RentLargeBuffer_ReturnsLargeBuffer(), and Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.SaveOptionChainCacheAsync().
MaxBufferSize
const int Alaris.Infrastructure.Protocol.Buffers.PLBF001A.MaxBufferSize = 1024 * 1024 static
Maximum buffer size to prevent excessive memory usage (1MB).
Definition at line 40 of file PLBF001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Buffers.PLBF001A.RentBuffer().
The documentation for this class was generated from the following file:
src/Alaris.Infrastructure/Protocol/Buffers/PLBF001A.cs