Alaris: Alaris.Test.Unit.TSUN030A Class Reference
Alaris.Test.Unit.TSUN030A Class Reference sealed
Unit tests for FIX SBE binary serialization components. Component ID: TSUN030A.
Public Member Functions
void PriceBarData_RoundTrip_PreservesAllFields ()
void OptionContractData_RoundTrip_PreservesAllFields ()
void ToMantissa_FromMantissa_RoundTrip_IsAccurate (decimal value)
void PriceBar_RoundTrip_PreservesAllFields ()
void OptionContract_RoundTrip_PreservesAllFields ()
void OptionContract_WithNullGreeks_PreservesNulls ()
void OptionChainSnapshot_RoundTrip_PreservesAllContracts ()
void EventEnvelope_RoundTrip_PreservesAllFields ()
void GetEncodedSize_ReturnsCorrectSize ()
void SessionMetadata_RoundTrip_PreservesAllFields ()
void GetEncodedSize_ForSession_ReturnsCorrectSize ()
void RentBuffer_ReturnsBufferOfAtLeastRequestedSize ()
void RentLargeBuffer_ReturnsLargeBuffer ()
void RentBuffer_WithInvalidSize_Throws ()
Detailed Description
Unit tests for FIX SBE binary serialization components. Component ID: TSUN030A.
Definition at line 22 of file TSUN030A.cs.
Member Function Documentation
EventEnvelope_RoundTrip_PreservesAllFields()
void Alaris.Test.Unit.TSUN030A.EventEnvelope_RoundTrip_PreservesAllFields () inline
Definition at line 272 of file TSUN030A.cs.
References Alaris.Infrastructure.Events.Serialization.EVsr001A.DecodeEventEnvelope(), Alaris.Infrastructure.Events.Serialization.EVsr001A.EncodeEventEnvelope(), and Alaris.Infrastructure.Events.Core.EVCR003A.
GetEncodedSize_ForSession_ReturnsCorrectSize()
void Alaris.Test.Unit.TSUN030A.GetEncodedSize_ForSession_ReturnsCorrectSize () inline
Definition at line 360 of file TSUN030A.cs.
References Alaris.Host.Application.Model.APmd001A, Alaris.Host.Application.Serialization.APsr001A.EncodeSessionMetadata(), and Alaris.Host.Application.Serialization.APsr001A.GetEncodedSize().
GetEncodedSize_ReturnsCorrectSize()
void Alaris.Test.Unit.TSUN030A.GetEncodedSize_ReturnsCorrectSize () inline
Definition at line 305 of file TSUN030A.cs.
References Alaris.Infrastructure.Events.Serialization.EVsr001A.EncodeEventEnvelope(), Alaris.Infrastructure.Events.Core.EVCR003A, and Alaris.Infrastructure.Events.Serialization.EVsr001A.GetEncodedSize().
OptionChainSnapshot_RoundTrip_PreservesAllContracts()
void Alaris.Test.Unit.TSUN030A.OptionChainSnapshot_RoundTrip_PreservesAllContracts () inline
Definition at line 213 of file TSUN030A.cs.
References Alaris.Infrastructure.Data.Serialization.DTsr001A.DecodeOptionChainSnapshot(), Alaris.Infrastructure.Data.Serialization.DTsr001A.EncodeOptionChainSnapshot(), Alaris.Infrastructure.Protocol.Buffers.PLBF001A.LargeBufferSize, Alaris.Infrastructure.Protocol.Buffers.PLBF001A.RentBuffer(), and Alaris.Infrastructure.Data.Model.OptionChainSnapshot.Symbol.
OptionContract_RoundTrip_PreservesAllFields()
void Alaris.Test.Unit.TSUN030A.OptionContract_RoundTrip_PreservesAllFields () inline
Definition at line 137 of file TSUN030A.cs.
References Alaris.Infrastructure.Data.Serialization.DTsr001A.DecodeOptionContract(), Alaris.Infrastructure.Data.Serialization.DTsr001A.EncodeOptionContract(), and Alaris.Infrastructure.Data.Model.OptionContract.UnderlyingSymbol.
OptionContract_WithNullGreeks_PreservesNulls()
void Alaris.Test.Unit.TSUN030A.OptionContract_WithNullGreeks_PreservesNulls () inline
Definition at line 178 of file TSUN030A.cs.
References Alaris.Infrastructure.Data.Serialization.DTsr001A.DecodeOptionContract(), Alaris.Infrastructure.Data.Serialization.DTsr001A.EncodeOptionContract(), and Alaris.Infrastructure.Data.Model.OptionContract.Last.
OptionContractData_RoundTrip_PreservesAllFields()
void Alaris.Test.Unit.TSUN030A.OptionContractData_RoundTrip_PreservesAllFields () inline
Definition at line 54 of file TSUN030A.cs.
References Alaris.Infrastructure.Protocol.Serialization.PLSR001A.DecodeOptionContract(), Alaris.Infrastructure.Protocol.Serialization.PLSR001A.EncodeOptionContract(), Alaris.Infrastructure.Protocol.Serialization.OptionContractData.StrikeMantissa, and Alaris.Infrastructure.Protocol.Serialization.PLSR001A.ToMantissa().
PriceBar_RoundTrip_PreservesAllFields()
void Alaris.Test.Unit.TSUN030A.PriceBar_RoundTrip_PreservesAllFields () inline
Definition at line 107 of file TSUN030A.cs.
References Alaris.Infrastructure.Data.Serialization.DTsr001A.DecodePriceBar(), Alaris.Infrastructure.Data.Serialization.DTsr001A.EncodePriceBar(), and Alaris.Infrastructure.Data.Model.PriceBar.Symbol.
PriceBarData_RoundTrip_PreservesAllFields()
void Alaris.Test.Unit.TSUN030A.PriceBarData_RoundTrip_PreservesAllFields () inline
Definition at line 26 of file TSUN030A.cs.
References Alaris.Infrastructure.Protocol.Serialization.PLSR001A.DecodePriceBar(), Alaris.Infrastructure.Protocol.Serialization.PLSR001A.EncodePriceBar(), Alaris.Infrastructure.Protocol.Serialization.PriceBarData.TimestampEpochMs, and Alaris.Infrastructure.Protocol.Serialization.PLSR001A.ToMantissa().
RentBuffer_ReturnsBufferOfAtLeastRequestedSize()
void Alaris.Test.Unit.TSUN030A.RentBuffer_ReturnsBufferOfAtLeastRequestedSize () inline
Definition at line 387 of file TSUN030A.cs.
References Alaris.Infrastructure.Protocol.Buffers.PooledBuffer.Length, and Alaris.Infrastructure.Protocol.Buffers.PLBF001A.RentBuffer().
RentBuffer_WithInvalidSize_Throws()
void Alaris.Test.Unit.TSUN030A.RentBuffer_WithInvalidSize_Throws () inline
Definition at line 409 of file TSUN030A.cs.
References Alaris.Infrastructure.Protocol.Buffers.PLBF001A.RentBuffer().
RentLargeBuffer_ReturnsLargeBuffer()
void Alaris.Test.Unit.TSUN030A.RentLargeBuffer_ReturnsLargeBuffer () inline
Definition at line 399 of file TSUN030A.cs.
References Alaris.Infrastructure.Protocol.Buffers.PLBF001A.LargeBufferSize, Alaris.Infrastructure.Protocol.Buffers.PooledBuffer.Length, and Alaris.Infrastructure.Protocol.Buffers.PLBF001A.RentLargeBuffer().
SessionMetadata_RoundTrip_PreservesAllFields()
void Alaris.Test.Unit.TSUN030A.SessionMetadata_RoundTrip_PreservesAllFields () inline
Definition at line 330 of file TSUN030A.cs.
References Alaris.Host.Application.Model.APmd001A, Alaris.Host.Application.Serialization.APsr001A.DecodeSessionMetadata(), and Alaris.Host.Application.Serialization.APsr001A.EncodeSessionMetadata().
ToMantissa_FromMantissa_RoundTrip_IsAccurate()
void Alaris.Test.Unit.TSUN030A.ToMantissa_FromMantissa_RoundTrip_IsAccurate (decimal value) inline
Definition at line 94 of file TSUN030A.cs.
References Alaris.Infrastructure.Protocol.Serialization.PLSR001A.FromMantissa(), and Alaris.Infrastructure.Protocol.Serialization.PLSR001A.ToMantissa().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN030A.cs