Alaris: Alaris.Infrastructure.Data.Quality.PriceReasonablenessValidator Class Reference
Alaris.Infrastructure.Data.Quality.PriceReasonablenessValidator Class Reference sealed
Validates price reasonableness and data freshness. Component ID: DTqc001A.
Public Member Functions
PriceReasonablenessValidator (ILogger< PriceReasonablenessValidator > logger, ITimeProvider timeProvider)
Initializes a new instance of the PriceReasonablenessValidator class.
DataQualityResult Validate (MarketDataSnapshot snapshot)
Validates market data snapshot.
Parameters
snapshot The market data to validate.
Returns
Validation result.
Properties
string ComponentId [get]
Gets the validator component ID (e.g., "DTqc001A").
Properties inherited from Alaris.Infrastructure.Data.Quality.DTqc002A
Private Attributes
readonly ILogger< PriceReasonablenessValidator > _logger
readonly ITimeProvider _timeProvider
Detailed Description
Validates price reasonableness and data freshness. Component ID: DTqc001A.
Validation checks:
Spot price within ±10% of previous close
Option bid > 0 and bid < ask
Option ask < intrinsic value + $10
No stale timestamps (>1 hour old)
Definition at line 21 of file DTqc001A.cs.
Constructor & Destructor Documentation
PriceReasonablenessValidator()
Alaris.Infrastructure.Data.Quality.PriceReasonablenessValidator.PriceReasonablenessValidator (ILogger< PriceReasonablenessValidator > logger, ITimeProvider timeProvider) inline
Initializes a new instance of the PriceReasonablenessValidator class.
Parameters
logger The logger instance.
timeProvider The time provider for backtest-aware time operations.
Definition at line 34 of file DTqc001A.cs.
References Alaris.Infrastructure.Data.Quality.PriceReasonablenessValidator._logger, and Alaris.Infrastructure.Data.Quality.PriceReasonablenessValidator._timeProvider.
Member Function Documentation
Validate()
DataQualityResult Alaris.Infrastructure.Data.Quality.PriceReasonablenessValidator.Validate (MarketDataSnapshot snapshot) inline
Validates market data snapshot.
Parameters
snapshot The market data to validate.
Returns
Validation result.
Implements Alaris.Infrastructure.Data.Quality.DTqc002A.
Definition at line 43 of file DTqc001A.cs.
References Alaris.Infrastructure.Data.Quality.PriceReasonablenessValidator._logger, Alaris.Infrastructure.Data.Quality.PriceReasonablenessValidator._timeProvider, Alaris.Infrastructure.Data.Quality.PriceReasonablenessValidator.ComponentId, Alaris.Infrastructure.Data.Model.MarketDataSnapshot.HistoricalBars, Alaris.Core.Time.ITimeProvider.Now, Alaris.Infrastructure.Data.Model.MarketDataSnapshot.SpotPrice, and Alaris.Core.Time.ITimeProvider.ToInstant().
Referenced by Alaris.Test.Unit.DTqc001ATests.Validate_AskBelowIntrinsic_ShouldFail(), Alaris.Test.Unit.DTqc001ATests.Validate_BidGreaterThanAsk_ShouldFail(), Alaris.Test.Unit.DTqc001ATests.Validate_SpotPriceChanged_MoreThan10Percent_ShouldWarn(), Alaris.Test.Unit.DTqc001ATests.Validate_StaleData_ShouldFail(), Alaris.Test.Unit.DTqc001ATests.Validate_ValidSnapshot_ShouldPass(), and Alaris.Test.Unit.DTqc001ATests.Validate_ZeroBid_ShouldFail().
Member Data Documentation
_logger
readonly ILogger<PriceReasonablenessValidator> Alaris.Infrastructure.Data.Quality.PriceReasonablenessValidator._logger private
Definition at line 23 of file DTqc001A.cs.
Referenced by Alaris.Infrastructure.Data.Quality.PriceReasonablenessValidator.PriceReasonablenessValidator(), and Alaris.Infrastructure.Data.Quality.PriceReasonablenessValidator.Validate().
_timeProvider
readonly ITimeProvider Alaris.Infrastructure.Data.Quality.PriceReasonablenessValidator._timeProvider private
Definition at line 24 of file DTqc001A.cs.
Referenced by Alaris.Infrastructure.Data.Quality.PriceReasonablenessValidator.PriceReasonablenessValidator(), and Alaris.Infrastructure.Data.Quality.PriceReasonablenessValidator.Validate().
Property Documentation
ComponentId
string Alaris.Infrastructure.Data.Quality.PriceReasonablenessValidator.ComponentId get
Gets the validator component ID (e.g., "DTqc001A").
Implements Alaris.Infrastructure.Data.Quality.DTqc002A.
Definition at line 27 of file DTqc001A.cs.
Referenced by Alaris.Test.Unit.DTqc001ATests.ComponentId_ShouldBe_DTqc001A(), and Alaris.Infrastructure.Data.Quality.PriceReasonablenessValidator.Validate().
The documentation for this class was generated from the following file:
src/Alaris.Infrastructure/Data/Quality/DTqc001A.cs