Alaris: Alaris.Core.Pooling.CRPL001A Class Reference
Alaris.Core.Pooling.CRPL001A Class Reference
Object pool manager providing rent/return semantics for buffers.
Static Public Member Functions
static double[] RentDoubles (int minimumLength)
Rents a double array of at least the specified length.
static void ReturnDoubles (double[] array, bool clearArray=false)
Returns a double array to the pool.
static byte[] RentBytes (int minimumLength)
Rents a byte array for serialization buffers.
static void ReturnBytes (byte[] array, bool clearArray=false)
Returns a byte array to the pool.
static TResult WithDoubleBuffer< TResult > (int minimumLength, Func< double[], TResult > action)
Executes an action with a rented double buffer, automatically returning it.
static TResult WithByteBuffer< TResult > (int minimumLength, Func< byte[], TResult > action)
Executes an action with a rented byte buffer, automatically returning it.
static void WithDoubleBuffer (int minimumLength, Action< double[]> action)
Executes an action with a rented double buffer (void return).
Properties
static ArrayPool< double > DoublePool = ArrayPool<double>.Shared [get]
Shared pool for double arrays (Greeks, prices, etc.).
static ArrayPool< int > IntPool = ArrayPool<int>.Shared [get]
Shared pool for int arrays (indices, counts, etc.).
static ArrayPool< byte > BytePool = ArrayPool<byte>.Shared [get]
Shared pool for byte arrays (serialization buffers).
Detailed Description
Object pool manager providing rent/return semantics for buffers.
Definition at line 11 of file CRPL001A.cs.
Member Function Documentation
RentBytes()
static byte[] Alaris.Core.Pooling.CRPL001A.RentBytes (int minimumLength) inline static
Rents a byte array for serialization buffers.
Definition at line 57 of file CRPL001A.cs.
References Alaris.Core.Pooling.CRPL001A.BytePool.
Referenced by Alaris.Core.Pooling.CRPL001A.WithByteBuffer< TResult >().
RentDoubles()
static double[] Alaris.Core.Pooling.CRPL001A.RentDoubles (int minimumLength) inline static
Rents a double array of at least the specified length.
Parameters
minimumLength Minimum array length required.
Returns
Pooled array (may be larger than requested).
Definition at line 34 of file CRPL001A.cs.
References Alaris.Core.Pooling.CRPL001A.DoublePool.
Referenced by Alaris.Core.Pooling.CRPL001A.WithDoubleBuffer(), and Alaris.Core.Pooling.CRPL001A.WithDoubleBuffer< TResult >().
ReturnBytes()
static void Alaris.Core.Pooling.CRPL001A.ReturnBytes (byte[] array, bool clearArray = false) inline static
Returns a byte array to the pool.
Definition at line 66 of file CRPL001A.cs.
References Alaris.Core.Pooling.CRPL001A.BytePool.
Referenced by Alaris.Core.Pooling.CRPL001A.WithByteBuffer< TResult >().
ReturnDoubles()
static void Alaris.Core.Pooling.CRPL001A.ReturnDoubles (double[] array, bool clearArray = false) inline static
Returns a double array to the pool.
Parameters
array Array to return.
clearArray Whether to clear the array before returning.
Definition at line 45 of file CRPL001A.cs.
References Alaris.Core.Pooling.CRPL001A.DoublePool.
Referenced by Alaris.Core.Pooling.CRPL001A.WithDoubleBuffer(), and Alaris.Core.Pooling.CRPL001A.WithDoubleBuffer< TResult >().
WithByteBuffer< TResult >()
static TResult Alaris.Core.Pooling.CRPL001A.WithByteBuffer< TResult > (int minimumLength, Func< byte[], TResult > action) inline static
Executes an action with a rented byte buffer, automatically returning it.
Definition at line 103 of file CRPL001A.cs.
References Alaris.Core.Pooling.CRPL001A.RentBytes(), and Alaris.Core.Pooling.CRPL001A.ReturnBytes().
WithDoubleBuffer()
static void Alaris.Core.Pooling.CRPL001A.WithDoubleBuffer (int minimumLength, Action< double[]> action) inline static
Executes an action with a rented double buffer (void return).
Definition at line 124 of file CRPL001A.cs.
References Alaris.Core.Pooling.CRPL001A.RentDoubles(), and Alaris.Core.Pooling.CRPL001A.ReturnDoubles().
WithDoubleBuffer< TResult >()
static TResult Alaris.Core.Pooling.CRPL001A.WithDoubleBuffer< TResult > (int minimumLength, Func< double[], TResult > action) inline static
Executes an action with a rented double buffer, automatically returning it.
Template Parameters
TResult Return type of the action.
Parameters
minimumLength Minimum buffer length.
action Action to execute with the buffer.
Returns
Result of the action.
Definition at line 82 of file CRPL001A.cs.
References Alaris.Core.Pooling.CRPL001A.RentDoubles(), and Alaris.Core.Pooling.CRPL001A.ReturnDoubles().
Property Documentation
BytePool
ArrayPool<byte> Alaris.Core.Pooling.CRPL001A.BytePool = ArrayPool<byte>.Shared static get
Shared pool for byte arrays (serialization buffers).
Definition at line 26 of file CRPL001A.cs.
Referenced by Alaris.Core.Pooling.CRPL001A.RentBytes(), and Alaris.Core.Pooling.CRPL001A.ReturnBytes().
DoublePool
ArrayPool<double> Alaris.Core.Pooling.CRPL001A.DoublePool = ArrayPool<double>.Shared static get
Shared pool for double arrays (Greeks, prices, etc.).
Definition at line 16 of file CRPL001A.cs.
Referenced by Alaris.Core.Pooling.CRPL001A.RentDoubles(), and Alaris.Core.Pooling.CRPL001A.ReturnDoubles().
IntPool
ArrayPool<int> Alaris.Core.Pooling.CRPL001A.IntPool = ArrayPool<int>.Shared static get
Shared pool for int arrays (indices, counts, etc.).
Definition at line 21 of file CRPL001A.cs.
The documentation for this class was generated from the following file:
src/Alaris.Core/Pooling/CRPL001A.cs