Alaris: Alaris.Core.Options.DividendSchedule Class Reference
Alaris.Core.Options.DividendSchedule Class Reference sealed
Immutable schedule of discrete cash dividends for option pricing.
Public Member Functions
DividendSchedule ()
Creates an empty dividend schedule.
DividendSchedule (IEnumerable< CashDividend > dividends)
Creates a dividend schedule from a list of dividends.
IEnumerable< CashDividend > GetDividendsBetween (DateTime startDate, DateTime endDate)
Gets dividends between two dates (exclusive of start, inclusive of end).
double ComputePresentValue (DateTime valuationDate, DateTime expiryDate, double riskFreeRate)
Computes the present value of all dividends using the Spot model.
double AdjustSpotForDividends (double spot, DateTime valuationDate, DateTime expiryDate, double riskFreeRate)
Adjusts the spot price for the Spot dividend model.
double double Amount[] GetDividendTimesForGrid (DateTime valuationDate, DateTime expiryDate)
DividendSchedule Add (CashDividend dividend)
Creates a new schedule with an additional dividend.
Static Public Member Functions
static DividendSchedule FromContinuousYield (double spot, double continuousYield, DateTime startDate, DateTime endDate, int frequency=4)
Estimates dividends from a continuous yield over a period.
Public Attributes
double TimeYears
Gets dividend times relative to a valuation date, in years.
Static Public Attributes
static readonly DividendSchedule Empty = new()
Empty dividend schedule (no discrete dividends).
Properties
ImmutableArray< CashDividend > Dividends [get]
Gets all dividends in chronological order.
int Count [get]
Gets the number of dividends in the schedule.
bool HasDividends [get]
Gets whether the schedule has any dividends.
Private Attributes
readonly ImmutableArray< CashDividend > _dividends
Detailed Description
Immutable schedule of discrete cash dividends for option pricing.
Definition at line 61 of file CROP004A.cs.
Constructor & Destructor Documentation
DividendSchedule() [1/2]
Alaris.Core.Options.DividendSchedule.DividendSchedule () inline
Creates an empty dividend schedule.
Definition at line 73 of file CROP004A.cs.
References Alaris.Core.Options.DividendSchedule._dividends.
Referenced by Alaris.Core.Options.DividendSchedule.Add(), and Alaris.Core.Options.DividendSchedule.FromContinuousYield().
DividendSchedule() [2/2]
Alaris.Core.Options.DividendSchedule.DividendSchedule (IEnumerable< CashDividend > dividends) inline
Creates a dividend schedule from a list of dividends.
Parameters
dividends Dividends to include.
Definition at line 82 of file CROP004A.cs.
References Alaris.Core.Options.DividendSchedule._dividends, and Alaris.Core.Options.CashDividend().
Member Function Documentation
Add()
DividendSchedule Alaris.Core.Options.DividendSchedule.Add (CashDividend dividend) inline
Creates a new schedule with an additional dividend.
Parameters
dividend Dividend to add.
Returns
New schedule with dividend included.
Definition at line 231 of file CROP004A.cs.
References Alaris.Core.Options.DividendSchedule.DividendSchedule(), and Alaris.Core.Options.DividendSchedule._dividends.
AdjustSpotForDividends()
double Alaris.Core.Options.DividendSchedule.AdjustSpotForDividends (double spot, DateTime valuationDate, DateTime expiryDate, double riskFreeRate) inline
Adjusts the spot price for the Spot dividend model.
Parameters
spot Current spot price.
valuationDate Current valuation date.
expiryDate Option expiry date.
riskFreeRate Continuous risk-free rate.
Returns
Adjusted spot price (S - PV of dividends).
Definition at line 185 of file CROP004A.cs.
References Alaris.Core.Options.DividendSchedule.ComputePresentValue().
ComputePresentValue()
double Alaris.Core.Options.DividendSchedule.ComputePresentValue (DateTime valuationDate, DateTime expiryDate, double riskFreeRate) inline
Computes the present value of all dividends using the Spot model.
Parameters
valuationDate Current valuation date.
expiryDate Option expiry date.
riskFreeRate Continuous risk-free rate.
Returns
Total PV of dividends occurring before expiry.
PV = Σ [D_i × exp(-r × t_i)] for all dividends before expiry. Time t_i is measured in years from valuation date.
Definition at line 154 of file CROP004A.cs.
References Alaris.Core.Options.DividendSchedule._dividends, and Alaris.Core.Options.CashDividend().
Referenced by Alaris.Core.Options.DividendSchedule.AdjustSpotForDividends().
FromContinuousYield()
static DividendSchedule Alaris.Core.Options.DividendSchedule.FromContinuousYield (double spot, double continuousYield, DateTime startDate, DateTime endDate, int frequency = 4) inline static
Estimates dividends from a continuous yield over a period.
Parameters
spot Current spot price.
continuousYield Annual continuous dividend yield.
startDate Start date.
endDate End date.
frequency Dividend frequency (per year, e.g., 4 for quarterly).
Returns
DividendSchedule with estimated discrete dividends.
Each dividend = S × (exp(q/frequency) - 1) ≈ S × q / frequency for small q.
Definition at line 253 of file CROP004A.cs.
References Alaris.Core.Options.DividendSchedule.DividendSchedule(), Alaris.Core.Options.CashDividend(), and Alaris.Core.Options.DividendSchedule.Empty.
GetDividendsBetween()
IEnumerable< CashDividend > Alaris.Core.Options.DividendSchedule.GetDividendsBetween (DateTime startDate, DateTime endDate) inline
Gets dividends between two dates (exclusive of start, inclusive of end).
Parameters
startDate Start date (exclusive).
endDate End date (inclusive).
Returns
Dividends in the range.
Definition at line 126 of file CROP004A.cs.
References Alaris.Core.Options.DividendSchedule._dividends, and Alaris.Core.Options.CashDividend().
GetDividendTimesForGrid()
double double Amount[] Alaris.Core.Options.DividendSchedule.GetDividendTimesForGrid (DateTime valuationDate, DateTime expiryDate) inline
Definition at line 197 of file CROP004A.cs.
References Alaris.Core.Options.DividendSchedule._dividends, Alaris.Core.Options.CashDividend(), and Alaris.Core.Options.DividendSchedule.TimeYears.
Member Data Documentation
_dividends
readonly ImmutableArray<CashDividend> Alaris.Core.Options.DividendSchedule._dividends private
Definition at line 68 of file CROP004A.cs.
Referenced by Alaris.Core.Options.DividendSchedule.DividendSchedule(), Alaris.Core.Options.DividendSchedule.DividendSchedule(), Alaris.Core.Options.DividendSchedule.Add(), Alaris.Core.Options.DividendSchedule.ComputePresentValue(), Alaris.Core.Options.DividendSchedule.GetDividendsBetween(), and Alaris.Core.Options.DividendSchedule.GetDividendTimesForGrid().
Empty
readonly DividendSchedule Alaris.Core.Options.DividendSchedule.Empty = new() static
Empty dividend schedule (no discrete dividends).
Definition at line 66 of file CROP004A.cs.
Referenced by Alaris.Core.Options.DividendSchedule.FromContinuousYield().
TimeYears
double Alaris.Core.Options.DividendSchedule.TimeYears
Gets dividend times relative to a valuation date, in years.
Parameters
valuationDate Current valuation date.
expiryDate Option expiry date.
Returns
Array of (time in years, amount) pairs for FD grid integration.
Definition at line 197 of file CROP004A.cs.
Referenced by Alaris.Core.Options.DividendSchedule.GetDividendTimesForGrid().
Property Documentation
Count
int Alaris.Core.Options.DividendSchedule.Count get
Gets the number of dividends in the schedule.
Definition at line 113 of file CROP004A.cs.
Dividends
ImmutableArray<CashDividend> Alaris.Core.Options.DividendSchedule.Dividends get
Gets all dividends in chronological order.
Definition at line 108 of file CROP004A.cs.
HasDividends
bool Alaris.Core.Options.DividendSchedule.HasDividends get
Gets whether the schedule has any dividends.
Definition at line 118 of file CROP004A.cs.
The documentation for this class was generated from the following file:
src/Alaris.Core/Options/CROP004A.cs