Alaris: Alaris.Strategy.Model.OptionExpiry Class Reference
Alaris.Strategy.Model.OptionExpiry Class Reference sealed
Represents all option contracts for a specific expiration date.
Public Member Functions
int GetDaysToExpiry (DateTime fromDate)
Gets the number of days until expiration from a given date.
Properties
DateTime ExpiryDate [get]
Gets the expiration date for these options.
IList< OptionContract > Calls = new List<OptionContract>() [get]
Gets the list of call option contracts.
IList< OptionContract > Puts = new List<OptionContract>() [get]
Gets the list of put option contracts.
Detailed Description
Represents all option contracts for a specific expiration date.
Definition at line 32 of file STDT002A.cs.
Member Function Documentation
GetDaysToExpiry()
int Alaris.Strategy.Model.OptionExpiry.GetDaysToExpiry (DateTime fromDate)
Gets the number of days until expiration from a given date.
Referenced by Alaris.Strategy.Core.STCR001A.CalculateVolatilitySpread(), Alaris.Strategy.Core.STCR001A.ComputeTheoreticalMetrics(), and Alaris.Strategy.Core.STCR001A.ExtractSTTM001APoints().
Property Documentation
Calls
IList<OptionContract> Alaris.Strategy.Model.OptionExpiry.Calls = new List<OptionContract>() get
Gets the list of call option contracts.
Definition at line 42 of file STDT002A.cs.
Referenced by Alaris.Strategy.Core.STCR001A.CalculateExpectedMove(), Alaris.Strategy.Core.STCR001A.CalculateVolatilitySpread(), and Alaris.Strategy.Core.STCR001A.ExtractSTTM001APoints().
ExpiryDate
DateTime Alaris.Strategy.Model.OptionExpiry.ExpiryDate get
Gets the expiration date for these options.
Definition at line 37 of file STDT002A.cs.
Puts
IList<OptionContract> Alaris.Strategy.Model.OptionExpiry.Puts = new List<OptionContract>() get
Gets the list of put option contracts.
Definition at line 47 of file STDT002A.cs.
Referenced by Alaris.Strategy.Core.STCR001A.CalculateExpectedMove(), Alaris.Strategy.Core.STCR001A.CalculateVolatilitySpread(), and Alaris.Strategy.Core.STCR001A.ExtractSTTM001APoints().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Model/STDT002A.cs