Alaris: Alaris.Strategy.Risk.STQT001A Class Reference
Alaris.Strategy.Risk.STQT001A Class Reference sealed
Implements queue-theoretic analysis for position management.
Public Member Functions
STQT001A (QueueParameters? parameters=null, ILogger< STQT001A >? logger=null)
Initialises a new queue-theoretic position manager.
double ComputeBlockingProbability (int currentPositions, int maxCapacity, double? utilisation=null)
Computes blocking probability for M/M/1/K queue (exponential approximation).
int ComputeOptimalCapacity (double arrivalRate, double meanHoldingTime, double blockingCost, double holdingCost, int maxSearch=30)
Computes the optimal capacity given cost parameters.
double ComputeVirtualFinishTime (int signalStrength, double capitalRequired, double? arrivalTime=null)
Computes the virtual finish time for WFQ scheduling.
void AdvanceVirtualTime (double finishTime)
Advances the virtual time after processing a signal.
IEnumerable< SignalQueueEntry > RankByWFQ (IEnumerable< SignalQueueEntry > signals)
Ranks signals by WFQ virtual finish time (ascending = higher priority).
void UpdateArrivalRateEstimate (int newArrivalCount, double observationPeriod)
Updates arrival rate estimate using exponential smoothing.
void UpdateServiceRateEstimate (IReadOnlyList< double > holdingTimes)
Updates service rate estimate from observed holding times.
QueueEstimates GetCurrentEstimates ()
Gets current queue parameter estimates.
Static Public Member Functions
static double ComputeMeanQueueLength (double arrivalRate, double serviceRate, double serviceCV)
Computes the mean queue length using the Pollaczek-Khinchine formula.
static double ComputeMeanWaitingTime (double arrivalRate, double serviceRate, double serviceCV)
Computes the mean waiting time (Little's Law derived).
static double ComputeGittinsProxy (double expectedProfit, double remainingDays, double currentPnL=0)
Computes the Gittins-index proxy for a position.
static int SelectForEjection (IReadOnlyList< PositionPriority > positions, double newSignalPriority)
Selects the position to eject when at capacity and a new signal arrives.
Private Member Functions
void SafeLog (Action logAction)
Static Private Member Functions
static double ComputeMeanQueueLengthWithCapacity (double rho, int capacity)
Private Attributes
readonly? ILogger< STQT001A > _logger
readonly QueueParameters _params
double _estimatedArrivalRate
double _estimatedServiceRate
double _estimatedServiceCV
double _currentVirtualTime
Static Private Attributes
static readonly Action< ILogger, double, double, Exception?> LogBlockingProbability
static readonly Action< ILogger, int, int, Exception?> LogCapacityRecommendation
Detailed Description
Implements queue-theoretic analysis for position management.
Definition at line 11 of file STQT001A.cs.
Constructor & Destructor Documentation
STQT001A()
Alaris.Strategy.Risk.STQT001A.STQT001A (QueueParameters? parameters = null, ILogger< STQT001A >? logger = null) inline
Initialises a new queue-theoretic position manager.
Definition at line 38 of file STQT001A.cs.
References Alaris.Strategy.Risk.STQT001A._currentVirtualTime, Alaris.Strategy.Risk.STQT001A._estimatedArrivalRate, Alaris.Strategy.Risk.STQT001A._estimatedServiceCV, Alaris.Strategy.Risk.STQT001A._estimatedServiceRate, Alaris.Strategy.Risk.STQT001A._logger, Alaris.Strategy.Risk.STQT001A._params, and Alaris.Strategy.Risk.QueueParameters().
Member Function Documentation
AdvanceVirtualTime()
void Alaris.Strategy.Risk.STQT001A.AdvanceVirtualTime (double finishTime) inline
Advances the virtual time after processing a signal.
Parameters
finishTime Virtual finish time of processed signal.
Definition at line 257 of file STQT001A.cs.
References Alaris.Strategy.Risk.STQT001A._currentVirtualTime.
ComputeBlockingProbability()
double Alaris.Strategy.Risk.STQT001A.ComputeBlockingProbability (int currentPositions, int maxCapacity, double? utilisation = null) inline
Computes blocking probability for M/M/1/K queue (exponential approximation).
Parameters
currentPositions Current number of open positions.
maxCapacity Maximum capacity K.
utilisation System utilisation ρ = λ/μ.
Returns
Probability of blocking the next arrival.
Definition at line 93 of file STQT001A.cs.
References Alaris.Strategy.Risk.STQT001A._estimatedArrivalRate, Alaris.Strategy.Risk.STQT001A._estimatedServiceRate, Alaris.Strategy.Risk.STQT001A._logger, Alaris.Strategy.Risk.STQT001A.LogBlockingProbability, and Alaris.Strategy.Risk.STQT001A.SafeLog().
Referenced by Alaris.Test.Unit.QueueTheoryTests.BlockingProbability_AtCapacity_ReturnsOne(), and Alaris.Strategy.Risk.STQT001A.ComputeOptimalCapacity().
ComputeGittinsProxy()
static double Alaris.Strategy.Risk.STQT001A.ComputeGittinsProxy (double expectedProfit, double remainingDays, double currentPnL = 0) inline static
Computes the Gittins-index proxy for a position.
Parameters
expectedProfit Expected profit from position.
remainingDays Days remaining until expected exit.
currentPnL Current unrealised P&L.
Returns
Priority score for position (higher = more valuable to keep).
Definition at line 180 of file STQT001A.cs.
Referenced by Alaris.Test.Unit.QueueTheoryTests.GittinsProxy_HigherProfit_HigherPriority().
ComputeMeanQueueLength()
static double Alaris.Strategy.Risk.STQT001A.ComputeMeanQueueLength (double arrivalRate, double serviceRate, double serviceCV) inline static
Computes the mean queue length using the Pollaczek-Khinchine formula.
Parameters
arrivalRate Signal arrival rate λ (per day).
serviceRate Position service rate μ = 1/E[S].
serviceCV Coefficient of variation of service time.
Returns
Mean number of positions in system.
Definition at line 58 of file STQT001A.cs.
Referenced by Alaris.Strategy.Risk.STQT001A.ComputeMeanWaitingTime(), Alaris.Strategy.Risk.STQT001A.GetCurrentEstimates(), and Alaris.Test.Unit.QueueTheoryTests.MeanQueueLength_IncreasesWithUtilisation().
ComputeMeanQueueLengthWithCapacity()
static double Alaris.Strategy.Risk.STQT001A.ComputeMeanQueueLengthWithCapacity (double rho, int capacity) inline static private
Definition at line 328 of file STQT001A.cs.
Referenced by Alaris.Strategy.Risk.STQT001A.ComputeOptimalCapacity().
ComputeMeanWaitingTime()
static double Alaris.Strategy.Risk.STQT001A.ComputeMeanWaitingTime (double arrivalRate, double serviceRate, double serviceCV) inline static
Computes the mean waiting time (Little's Law derived).
Definition at line 79 of file STQT001A.cs.
References Alaris.Strategy.Risk.STQT001A.ComputeMeanQueueLength().
ComputeOptimalCapacity()
int Alaris.Strategy.Risk.STQT001A.ComputeOptimalCapacity (double arrivalRate, double meanHoldingTime, double blockingCost, double holdingCost, int maxSearch = 30) inline
Computes the optimal capacity given cost parameters.
Parameters
arrivalRate Expected signal arrival rate.
meanHoldingTime Mean position holding time.
blockingCost Cost per blocked signal.
holdingCost Cost per position-day (capital cost).
maxSearch Maximum capacity to consider.
Returns
Optimal capacity K*.
Definition at line 134 of file STQT001A.cs.
References Alaris.Strategy.Risk.STQT001A._logger, Alaris.Strategy.Risk.STQT001A.ComputeBlockingProbability(), Alaris.Strategy.Risk.STQT001A.ComputeMeanQueueLengthWithCapacity(), Alaris.Strategy.Risk.STQT001A.LogCapacityRecommendation, and Alaris.Strategy.Risk.STQT001A.SafeLog().
ComputeVirtualFinishTime()
double Alaris.Strategy.Risk.STQT001A.ComputeVirtualFinishTime (int signalStrength, double capitalRequired, double? arrivalTime = null) inline
Computes the virtual finish time for WFQ scheduling.
Parameters
signalStrength Signal strength (Recommended=3, Consider=1).
capitalRequired Capital requirement (size).
arrivalTime Signal arrival virtual time.
Returns
Virtual finish time for scheduling.
Definition at line 238 of file STQT001A.cs.
References Alaris.Strategy.Risk.STQT001A._currentVirtualTime.
Referenced by Alaris.Strategy.Risk.STQT001A.RankByWFQ().
GetCurrentEstimates()
QueueEstimates Alaris.Strategy.Risk.STQT001A.GetCurrentEstimates () inline
Gets current queue parameter estimates.
Definition at line 315 of file STQT001A.cs.
References Alaris.Strategy.Risk.STQT001A._estimatedArrivalRate, Alaris.Strategy.Risk.STQT001A._estimatedServiceCV, Alaris.Strategy.Risk.STQT001A._estimatedServiceRate, Alaris.Strategy.Risk.STQT001A.ComputeMeanQueueLength(), and Alaris.Strategy.Risk.QueueEstimates().
RankByWFQ()
IEnumerable< SignalQueueEntry > Alaris.Strategy.Risk.STQT001A.RankByWFQ (IEnumerable< SignalQueueEntry > signals) inline
Ranks signals by WFQ virtual finish time (ascending = higher priority).
Parameters
signals Signals to rank.
Returns
Signals ordered by virtual finish time.
Definition at line 267 of file STQT001A.cs.
References Alaris.Strategy.Risk.STQT001A.ComputeVirtualFinishTime().
SafeLog()
void Alaris.Strategy.Risk.STQT001A.SafeLog (Action logAction) inline private
Definition at line 343 of file STQT001A.cs.
References Alaris.Strategy.Risk.STQT001A._logger.
Referenced by Alaris.Strategy.Risk.STQT001A.ComputeBlockingProbability(), and Alaris.Strategy.Risk.STQT001A.ComputeOptimalCapacity().
SelectForEjection()
static int Alaris.Strategy.Risk.STQT001A.SelectForEjection (IReadOnlyList< PositionPriority > positions, double newSignalPriority) inline static
Selects the position to eject when at capacity and a new signal arrives.
Parameters
positions Current positions with their priorities.
newSignalPriority Priority of the incoming signal.
Returns
Index of position to eject, or -1 if new signal should be rejected.
Definition at line 199 of file STQT001A.cs.
Referenced by Alaris.Test.Unit.QueueTheoryTests.SelectForEjection_NewSignalHigherPriority_ReturnsMinIndex().
UpdateArrivalRateEstimate()
void Alaris.Strategy.Risk.STQT001A.UpdateArrivalRateEstimate (int newArrivalCount, double observationPeriod) inline
Updates arrival rate estimate using exponential smoothing.
Parameters
newArrivalCount Number of arrivals in the observation period.
observationPeriod Length of observation period in days.
Definition at line 279 of file STQT001A.cs.
References Alaris.Strategy.Risk.STQT001A._estimatedArrivalRate, and Alaris.Strategy.Risk.STQT001A._params.
UpdateServiceRateEstimate()
void Alaris.Strategy.Risk.STQT001A.UpdateServiceRateEstimate (IReadOnlyList< double > holdingTimes) inline
Updates service rate estimate from observed holding times.
Parameters
holdingTimes Observed holding durations in days.
Definition at line 290 of file STQT001A.cs.
References Alaris.Strategy.Risk.STQT001A._estimatedServiceCV, Alaris.Strategy.Risk.STQT001A._estimatedServiceRate, and Alaris.Strategy.Risk.STQT001A._params.
Member Data Documentation
_currentVirtualTime
double Alaris.Strategy.Risk.STQT001A._currentVirtualTime private
Definition at line 20 of file STQT001A.cs.
Referenced by Alaris.Strategy.Risk.STQT001A.STQT001A(), Alaris.Strategy.Risk.STQT001A.AdvanceVirtualTime(), and Alaris.Strategy.Risk.STQT001A.ComputeVirtualFinishTime().
_estimatedArrivalRate
double Alaris.Strategy.Risk.STQT001A._estimatedArrivalRate private
Definition at line 17 of file STQT001A.cs.
Referenced by Alaris.Strategy.Risk.STQT001A.STQT001A(), Alaris.Strategy.Risk.STQT001A.ComputeBlockingProbability(), Alaris.Strategy.Risk.STQT001A.GetCurrentEstimates(), and Alaris.Strategy.Risk.STQT001A.UpdateArrivalRateEstimate().
_estimatedServiceCV
double Alaris.Strategy.Risk.STQT001A._estimatedServiceCV private
Definition at line 19 of file STQT001A.cs.
Referenced by Alaris.Strategy.Risk.STQT001A.STQT001A(), Alaris.Strategy.Risk.STQT001A.GetCurrentEstimates(), and Alaris.Strategy.Risk.STQT001A.UpdateServiceRateEstimate().
_estimatedServiceRate
double Alaris.Strategy.Risk.STQT001A._estimatedServiceRate private
Definition at line 18 of file STQT001A.cs.
Referenced by Alaris.Strategy.Risk.STQT001A.STQT001A(), Alaris.Strategy.Risk.STQT001A.ComputeBlockingProbability(), Alaris.Strategy.Risk.STQT001A.GetCurrentEstimates(), and Alaris.Strategy.Risk.STQT001A.UpdateServiceRateEstimate().
_logger
readonly? ILogger<STQT001A> Alaris.Strategy.Risk.STQT001A._logger private
Definition at line 13 of file STQT001A.cs.
Referenced by Alaris.Strategy.Risk.STQT001A.STQT001A(), Alaris.Strategy.Risk.STQT001A.ComputeBlockingProbability(), Alaris.Strategy.Risk.STQT001A.ComputeOptimalCapacity(), and Alaris.Strategy.Risk.STQT001A.SafeLog().
_params
readonly QueueParameters Alaris.Strategy.Risk.STQT001A._params private
Definition at line 14 of file STQT001A.cs.
Referenced by Alaris.Strategy.Risk.STQT001A.STQT001A(), Alaris.Strategy.Risk.STQT001A.UpdateArrivalRateEstimate(), and Alaris.Strategy.Risk.STQT001A.UpdateServiceRateEstimate().
LogBlockingProbability
readonly Action<ILogger, double, double, Exception?> Alaris.Strategy.Risk.STQT001A.LogBlockingProbability static private
Initial value:
=
        LoggerMessage.Define<double, double>(
            LogLevel.Debug,
            new EventId(1, nameof(LogBlockingProbability)),
            "Blocking probability: P_K={Probability:P2} at utilisation ρ={Utilisation:F3}")
Definition at line 23 of file STQT001A.cs.
Referenced by Alaris.Strategy.Risk.STQT001A.ComputeBlockingProbability().
LogCapacityRecommendation
readonly Action<ILogger, int, int, Exception?> Alaris.Strategy.Risk.STQT001A.LogCapacityRecommendation static private
Initial value:
=
        LoggerMessage.Define<int, int>(
            LogLevel.Information,
            new EventId(2, nameof(LogCapacityRecommendation)),
            "Optimal capacity: K*={OptimalK} (current={CurrentK})")
Definition at line 29 of file STQT001A.cs.
Referenced by Alaris.Strategy.Risk.STQT001A.ComputeOptimalCapacity().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Risk/STQT001A.cs