Alaris: Alaris.Strategy.Core.STPR006A Class Reference
Alaris.Strategy.Core.STPR006A Class Reference
Production-grade Kou model pricing using characteristic function integration. Implements semi-analytical pricing for double-exponential jump-diffusion model. The Kou (2002) model extends Black-Scholes with asymmetric jumps:
Static Public Member Functions
static double ComputePrice (double spot, double strike, double timeToExpiry, KouParameters @params, bool isCall=true)
Computes call option price using Kou model characteristic function.
static double ComputeImpliedVolatility (double spot, double strike, double timeToExpiry, KouParameters @params)
Computes implied volatility from Kou model using Brent's method. Replaces Newton-Bisection cascade with unified Brent algorithm.
Static Private Member Functions
static Complex CharacteristicFunction (Complex u, double spot, double timeToExpiry, KouParameters @params)
Kou model characteristic function. This captures the jump-diffusion dynamics including asymmetric jumps.
static double BlackScholesPrice (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, bool isCall)
Black-Scholes option price for IV solving.
static double BlackScholesVega (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility)
Black-Scholes vega for gradient-based methods (retained for reference).
static double NormalCDF (double x)
static double NormalPDF (double x)
Static Private Attributes
const double MinIV = 0.001
const double MaxIV = 5.0
const double IVTolerance = 1e-6
Detailed Description
Production-grade Kou model pricing using characteristic function integration. Implements semi-analytical pricing for double-exponential jump-diffusion model. The Kou (2002) model extends Black-Scholes with asymmetric jumps:
Uses Fourier inversion for option pricing
Handles fat tails and skewness
Calibrates to market implied volatility smile
Definition at line 16 of file STPR006A.cs.
Member Function Documentation
BlackScholesPrice()
static double Alaris.Strategy.Core.STPR006A.BlackScholesPrice (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, bool isCall) inline static private
Black-Scholes option price for IV solving.
Definition at line 170 of file STPR006A.cs.
References Alaris.Strategy.Core.STPR006A.NormalCDF().
Referenced by Alaris.Strategy.Core.STPR006A.ComputeImpliedVolatility().
BlackScholesVega()
static double Alaris.Strategy.Core.STPR006A.BlackScholesVega (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility) inline static private
Black-Scholes vega for gradient-based methods (retained for reference).
Definition at line 200 of file STPR006A.cs.
References Alaris.Strategy.Core.STPR006A.NormalPDF().
CharacteristicFunction()
static Complex Alaris.Strategy.Core.STPR006A.CharacteristicFunction (Complex u, double spot, double timeToExpiry, KouParameters @ params) inline static private
Kou model characteristic function. This captures the jump-diffusion dynamics including asymmetric jumps.
Definition at line 124 of file STPR006A.cs.
References Alaris.Strategy.Core.KouParameters.DividendYield, Alaris.Strategy.Core.KouParameters.Eta1, Alaris.Strategy.Core.KouParameters.Eta2, Alaris.Strategy.Core.KouParameters.Lambda, Alaris.Strategy.Core.KouParameters.P, Alaris.Strategy.Core.KouParameters.RiskFreeRate, and Alaris.Strategy.Core.KouParameters.Sigma.
Referenced by Alaris.Strategy.Core.STPR006A.ComputePrice().
ComputeImpliedVolatility()
static double Alaris.Strategy.Core.STPR006A.ComputeImpliedVolatility (double spot, double strike, double timeToExpiry, KouParameters @ params) inline static
Computes implied volatility from Kou model using Brent's method. Replaces Newton-Bisection cascade with unified Brent algorithm.
Parameters
spot Current spot price.
strike Strike price.
timeToExpiry Time to expiry in years.
params Kou model parameters.
Returns
Implied volatility.
Definition at line 100 of file STPR006A.cs.
References Alaris.Strategy.Core.STPR006A.BlackScholesPrice(), Alaris.Strategy.Core.STPR006A.ComputePrice(), Alaris.Strategy.Core.KouParameters.DividendYield, Alaris.Strategy.Core.STPR006A.IVTolerance, Alaris.Strategy.Core.STPR006A.MaxIV, Alaris.Strategy.Core.STPR006A.MinIV, Alaris.Strategy.Core.KouParameters.RiskFreeRate, and Alaris.Strategy.Core.Numerical.STPR007A.SolveImpliedVolatility().
Referenced by Alaris.Strategy.Core.STIV002A.ComputeTheoreticalIV().
ComputePrice()
static double Alaris.Strategy.Core.STPR006A.ComputePrice (double spot, double strike, double timeToExpiry, KouParameters @ params, bool isCall = true) inline static
Computes call option price using Kou model characteristic function.
Parameters
spot Current spot price.
strike Strike price.
timeToExpiry Time to expiry in years.
params Kou model parameters.
isCall True for call, false for put.
Returns
Option price.
Definition at line 31 of file STPR006A.cs.
References Alaris.Strategy.Core.STPR006A.CharacteristicFunction(), Alaris.Strategy.Core.KouParameters.DividendYield, Alaris.Strategy.Core.Numerical.STPR002C.IntegrateToInfinity(), and Alaris.Strategy.Core.KouParameters.RiskFreeRate.
Referenced by Alaris.Strategy.Core.STPR006A.ComputeImpliedVolatility().
NormalCDF()
static double Alaris.Strategy.Core.STPR006A.NormalCDF (double x) static private
Referenced by Alaris.Strategy.Core.STPR006A.BlackScholesPrice().
NormalPDF()
static double Alaris.Strategy.Core.STPR006A.NormalPDF (double x) static private
Referenced by Alaris.Strategy.Core.STPR006A.BlackScholesVega().
Member Data Documentation
IVTolerance
const double Alaris.Strategy.Core.STPR006A.IVTolerance = 1e-6 static private
Definition at line 20 of file STPR006A.cs.
Referenced by Alaris.Strategy.Core.STPR006A.ComputeImpliedVolatility().
MaxIV
const double Alaris.Strategy.Core.STPR006A.MaxIV = 5.0 static private
Definition at line 19 of file STPR006A.cs.
Referenced by Alaris.Strategy.Core.STPR006A.ComputeImpliedVolatility().
MinIV
const double Alaris.Strategy.Core.STPR006A.MinIV = 0.001 static private
Definition at line 18 of file STPR006A.cs.
Referenced by Alaris.Strategy.Core.STPR006A.ComputeImpliedVolatility().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Core/STPR006A.cs