Alaris: Alaris.Core.Options.VanillaPayoff Struct Reference
Alaris.Core.Options.VanillaPayoff Struct Reference
Plain vanilla option payoff (European/American style). Replaces QuantLib PlainVanillaPayoff.
Public Member Functions
VanillaPayoff (OptionType optionType, double strike)
Initialises a new vanilla payoff.
double Payoff (double spot)
Calculates the intrinsic value (payoff at expiry).
double PayoffSigned (double spot)
Calculates the intrinsic value using the sign-based formula. Useful for unified call/put algorithms.
bool Equals (VanillaPayoff other)
override bool Equals (object? obj)
override int GetHashCode ()
override string ToString ()
Static Public Member Functions
static bool operator== (VanillaPayoff left, VanillaPayoff right)
Compares two payoffs for equality.
static bool operator!= (VanillaPayoff left, VanillaPayoff right)
Compares two payoffs for inequality.
Properties
OptionType Type [get]
Gets the option type (Call or Put).
double Strike [get]
Gets the strike price.
Detailed Description
Plain vanilla option payoff (European/American style). Replaces QuantLib PlainVanillaPayoff.
This is a value type for zero-allocation operations in hot paths.
Definition at line 24 of file CROP002A.cs.
Constructor & Destructor Documentation
VanillaPayoff()
Alaris.Core.Options.VanillaPayoff.VanillaPayoff (OptionType optionType, double strike) inline
Initialises a new vanilla payoff.
Parameters
optionType Call or Put.
strike Strike price.
Definition at line 31 of file CROP002A.cs.
References Alaris.Core.Options.VanillaPayoff.Strike, and Alaris.Core.Options.VanillaPayoff.Type.
Member Function Documentation
Equals() [1/2]
override bool Alaris.Core.Options.VanillaPayoff.Equals (object? obj) inline
Definition at line 88 of file CROP002A.cs.
References Alaris.Core.Options.VanillaPayoff.Equals().
Equals() [2/2]
bool Alaris.Core.Options.VanillaPayoff.Equals (VanillaPayoff other) inline
Definition at line 82 of file CROP002A.cs.
References Alaris.Core.Options.VanillaPayoff.Strike, and Alaris.Core.Options.VanillaPayoff.Type.
Referenced by Alaris.Core.Options.VanillaPayoff.Equals(), Alaris.Core.Options.VanillaPayoff.operator!=(), and Alaris.Core.Options.VanillaPayoff.operator==().
GetHashCode()
override int Alaris.Core.Options.VanillaPayoff.GetHashCode () inline
Definition at line 94 of file CROP002A.cs.
References Alaris.Core.Options.VanillaPayoff.Strike, and Alaris.Core.Options.VanillaPayoff.Type.
operator!=()
static bool Alaris.Core.Options.VanillaPayoff.operator!= (VanillaPayoff left, VanillaPayoff right) inline static
Compares two payoffs for inequality.
Definition at line 110 of file CROP002A.cs.
References Alaris.Core.Options.VanillaPayoff.Equals().
operator==()
static bool Alaris.Core.Options.VanillaPayoff.operator== (VanillaPayoff left, VanillaPayoff right) inline static
Compares two payoffs for equality.
Definition at line 102 of file CROP002A.cs.
References Alaris.Core.Options.VanillaPayoff.Equals().
Payoff()
double Alaris.Core.Options.VanillaPayoff.Payoff (double spot) inline
Calculates the intrinsic value (payoff at expiry).
Parameters
spot Spot price at expiry.
Returns
Payoff value (always non-negative).
Definition at line 59 of file CROP002A.cs.
References Alaris.Core.Options.VanillaPayoff.Strike, and Alaris.Core.Options.VanillaPayoff.Type.
PayoffSigned()
double Alaris.Core.Options.VanillaPayoff.PayoffSigned (double spot) inline
Calculates the intrinsic value using the sign-based formula. Useful for unified call/put algorithms.
Parameters
spot Spot price at expiry.
Returns
Payoff value (always non-negative).
Definition at line 75 of file CROP002A.cs.
References Alaris.Core.Options.VanillaPayoff.Strike, and Alaris.Core.Options.VanillaPayoff.Type.
ToString()
override string Alaris.Core.Options.VanillaPayoff.ToString () inline
Definition at line 116 of file CROP002A.cs.
Property Documentation
Strike
double Alaris.Core.Options.VanillaPayoff.Strike get
Gets the strike price.
Definition at line 52 of file CROP002A.cs.
Referenced by Alaris.Core.Options.VanillaPayoff.VanillaPayoff(), Alaris.Core.Options.VanillaPayoff.Equals(), Alaris.Core.Options.VanillaPayoff.GetHashCode(), Alaris.Core.Options.VanillaPayoff.Payoff(), and Alaris.Core.Options.VanillaPayoff.PayoffSigned().
Type
OptionType Alaris.Core.Options.VanillaPayoff.Type get
Gets the option type (Call or Put).
Definition at line 47 of file CROP002A.cs.
Referenced by Alaris.Core.Options.VanillaPayoff.VanillaPayoff(), Alaris.Core.Options.VanillaPayoff.Equals(), Alaris.Core.Options.VanillaPayoff.GetHashCode(), Alaris.Core.Options.VanillaPayoff.Payoff(), and Alaris.Core.Options.VanillaPayoff.PayoffSigned().
The documentation for this struct was generated from the following file:
src/Alaris.Core/Options/CROP002A.cs