Alaris: Alaris.Core.Pricing.CRSL002A Class Reference
Alaris.Core.Pricing.CRSL002A Class Reference sealed
Refines QD+ boundaries using Kim integral equation with stabilized FP-B' iteration.
Public Member Functions
CRSL002A (double spot, double strike, double maturity, double rate, double dividendYield, double volatility, bool isCall, int collocationPoints=50)
Initializes a new Kim solver for double boundaries.
double[] double[] double CrossingTime SolveBoundaries (double upperInitial, double lowerInitial)
Public Attributes
double[] Upper
Solves for refined boundaries using Kim's integral equation with FP-B' stabilized iteration.
double[] double[] Lower
Properties
int CollocationPoints [get]
Number of collocation points used for boundary refinement.
Private Member Functions
double[] double[] Lower RefineUsingFpbPrime (double[] upperInitial, double[] lowerInitial, double crossingTime)
bool ValidateInitialInputs (double[] upper, double[] lower)
double[] double[] Lower FallbackToQdPlusConstant (int m)
bool ValidateRefinementResult (double[] upper, double[] lower, double[] upperInit, double[] lowerInit)
double SolveUpperBoundaryPoint (double ti, double[] upper, double[] lower, double crossingTime)
double SolveLowerBoundaryPointStabilized (double ti, double[] lowerOld, double[] upperNew, double crossingTime)
double SanitizeBoundaryValue (double value, bool isUpper)
double CalculateNumerator (double ti, double[] upper, double[] lower, double crossingTime, bool isUpper)
double CalculateDenominator (double ti, double[] upper, double[] lower, double crossingTime, bool isUpper)
double CalculateNumeratorPrime (double ti, double[] lower, double[] upper, double crossingTime)
double CalculateDenominatorPrime (double ti, double[] lower)
double CalculateIntegralTerm (double ti, double Bi, double[] upper, double[] lower, double crossingTime, bool isNumerator)
Unified integral calculation for N (r-weighted) and D (q-weighted).
double FindCrossingTime (double[] upper, double[] lower)
double RefineCrossingTime (double[] upper, double[] lower, double initialCrossing)
void AdjustCrossingInitialGuess (double[] upper, double[] lower, double crossingTime)
double double Lower EnforceConstraints (double upper, double lower)
double InterpolateBoundary (double[] boundary, double t)
double CalculateD1 (double S, double K, double tau)
double CalculateD2 (double S, double K, double tau)
double[] EnforceMonotonicity (double[] boundary, int length, bool isIncreasing)
Static Private Member Functions
static bool CheckStagnation (int iter, double maxChange, ref double previousMaxChange, ref int stagnationCount)
static bool IsInvalidRatio (double numerator, double denominator)
static bool IsInvalidBoundary (double upper, double lower)
static double[] PoolAdjacentViolators (double[] values, bool increasing)
Pool Adjacent Violators algorithm for isotonic regression. Optimized to use stack-allocated spans for small arrays (Rule 5).
static double[] SmoothBoundary (double[] boundary)
Apply Savitzky-Golay-style smoothing to reduce second-order oscillations. Uses weighted 5-point moving average for quadratic smoothing.
static double NormalCDF (double x)
Private Attributes
readonly double _spot
readonly double _strike
readonly double _maturity
readonly double _rate
readonly double _dividendYield
readonly double _volatility
readonly bool _isCall
readonly int _collocationPoints
double Upper
Static Private Attributes
const double Tolerance = 1e-6
const int MaxIterations = 100
const int IntegrationPoints = 50
const double NumericalEpsilon = 1e-10
const double CrossingTimeThreshold = 1e-2
Detailed Description
Refines QD+ boundaries using Kim integral equation with stabilized FP-B' iteration.
Definition at line 16 of file CRSL002A.cs.
Constructor & Destructor Documentation
CRSL002A()
Alaris.Core.Pricing.CRSL002A.CRSL002A (double spot, double strike, double maturity, double rate, double dividendYield, double volatility, bool isCall, int collocationPoints = 50) inline
Initializes a new Kim solver for double boundaries.
Definition at line 41 of file CRSL002A.cs.
References Alaris.Core.Pricing.CRSL002A._collocationPoints, Alaris.Core.Pricing.CRSL002A._dividendYield, Alaris.Core.Pricing.CRSL002A._isCall, Alaris.Core.Pricing.CRSL002A._maturity, Alaris.Core.Pricing.CRSL002A._rate, Alaris.Core.Pricing.CRSL002A._spot, Alaris.Core.Pricing.CRSL002A._strike, Alaris.Core.Pricing.CRSL002A._volatility, and Alaris.Core.Validation.AlgorithmBounds.ValidateDoubleBoundaryInputs().
Member Function Documentation
AdjustCrossingInitialGuess()
void Alaris.Core.Pricing.CRSL002A.AdjustCrossingInitialGuess (double[] upper, double[] lower, double crossingTime) inline private
Definition at line 545 of file CRSL002A.cs.
References Alaris.Core.Pricing.CRSL002A._collocationPoints, and Alaris.Core.Pricing.CRSL002A._maturity.
CalculateD1()
double Alaris.Core.Pricing.CRSL002A.CalculateD1 (double S, double K, double tau) inline private
Definition at line 601 of file CRSL002A.cs.
References Alaris.Core.Pricing.CRSL002A._dividendYield, Alaris.Core.Pricing.CRSL002A._rate, Alaris.Core.Pricing.CRSL002A._volatility, and Alaris.Core.Pricing.CRSL002A.NumericalEpsilon.
Referenced by Alaris.Core.Pricing.CRSL002A.CalculateD2(), Alaris.Core.Pricing.CRSL002A.CalculateDenominator(), Alaris.Core.Pricing.CRSL002A.CalculateDenominatorPrime(), and Alaris.Core.Pricing.CRSL002A.CalculateIntegralTerm().
CalculateD2()
double Alaris.Core.Pricing.CRSL002A.CalculateD2 (double S, double K, double tau) inline private
Definition at line 611 of file CRSL002A.cs.
References Alaris.Core.Pricing.CRSL002A._volatility, Alaris.Core.Pricing.CRSL002A.CalculateD1(), and Alaris.Core.Pricing.CRSL002A.NumericalEpsilon.
Referenced by Alaris.Core.Pricing.CRSL002A.CalculateIntegralTerm(), and Alaris.Core.Pricing.CRSL002A.CalculateNumerator().
CalculateDenominator()
double Alaris.Core.Pricing.CRSL002A.CalculateDenominator (double ti, double[] upper, double[] lower, double crossingTime, bool isUpper) inline private
Definition at line 392 of file CRSL002A.cs.
References Alaris.Core.Pricing.CRSL002A._dividendYield, Alaris.Core.Pricing.CRSL002A._maturity, Alaris.Core.Pricing.CRSL002A._strike, Alaris.Core.Pricing.CRSL002A.CalculateD1(), Alaris.Core.Pricing.CRSL002A.CalculateIntegralTerm(), Alaris.Core.Pricing.CRSL002A.InterpolateBoundary(), Alaris.Core.Pricing.CRSL002A.NormalCDF(), and Alaris.Core.Pricing.CRSL002A.NumericalEpsilon.
Referenced by Alaris.Core.Pricing.CRSL002A.SolveUpperBoundaryPoint().
CalculateDenominatorPrime()
double Alaris.Core.Pricing.CRSL002A.CalculateDenominatorPrime (double ti, double[] lower) inline private
Definition at line 427 of file CRSL002A.cs.
References Alaris.Core.Pricing.CRSL002A._dividendYield, Alaris.Core.Pricing.CRSL002A._maturity, Alaris.Core.Pricing.CRSL002A._strike, Alaris.Core.Pricing.CRSL002A.CalculateD1(), Alaris.Core.Pricing.CRSL002A.InterpolateBoundary(), and Alaris.Core.Pricing.CRSL002A.NormalCDF().
Referenced by Alaris.Core.Pricing.CRSL002A.SolveLowerBoundaryPointStabilized().
CalculateIntegralTerm()
double Alaris.Core.Pricing.CRSL002A.CalculateIntegralTerm (double ti, double Bi, double[] upper, double[] lower, double crossingTime, bool isNumerator) inline private
Unified integral calculation for N (r-weighted) and D (q-weighted).
Definition at line 439 of file CRSL002A.cs.
References Alaris.Core.Pricing.CRSL002A._dividendYield, Alaris.Core.Pricing.CRSL002A._maturity, Alaris.Core.Pricing.CRSL002A._rate, Alaris.Core.Pricing.CRSL002A.CalculateD1(), Alaris.Core.Pricing.CRSL002A.CalculateD2(), Alaris.Core.Pricing.CRSL002A.IntegrationPoints, Alaris.Core.Pricing.CRSL002A.InterpolateBoundary(), Alaris.Core.Pricing.CRSL002A.IsInvalidBoundary(), Alaris.Core.Pricing.CRSL002A.NormalCDF(), and Alaris.Core.Pricing.CRSL002A.NumericalEpsilon.
Referenced by Alaris.Core.Pricing.CRSL002A.CalculateDenominator(), Alaris.Core.Pricing.CRSL002A.CalculateNumerator(), and Alaris.Core.Pricing.CRSL002A.CalculateNumeratorPrime().
CalculateNumerator()
double Alaris.Core.Pricing.CRSL002A.CalculateNumerator (double ti, double[] upper, double[] lower, double crossingTime, bool isUpper) inline private
Definition at line 367 of file CRSL002A.cs.
References Alaris.Core.Pricing.CRSL002A._maturity, Alaris.Core.Pricing.CRSL002A._rate, Alaris.Core.Pricing.CRSL002A._strike, Alaris.Core.Pricing.CRSL002A.CalculateD2(), Alaris.Core.Pricing.CRSL002A.CalculateIntegralTerm(), Alaris.Core.Pricing.CRSL002A.InterpolateBoundary(), Alaris.Core.Pricing.CRSL002A.NormalCDF(), and Alaris.Core.Pricing.CRSL002A.NumericalEpsilon.
Referenced by Alaris.Core.Pricing.CRSL002A.CalculateNumeratorPrime(), and Alaris.Core.Pricing.CRSL002A.SolveUpperBoundaryPoint().
CalculateNumeratorPrime()
double Alaris.Core.Pricing.CRSL002A.CalculateNumeratorPrime (double ti, double[] lower, double[] upper, double crossingTime) inline private
Definition at line 417 of file CRSL002A.cs.
References Alaris.Core.Pricing.CRSL002A._strike, Alaris.Core.Pricing.CRSL002A.CalculateIntegralTerm(), Alaris.Core.Pricing.CRSL002A.CalculateNumerator(), and Alaris.Core.Pricing.CRSL002A.InterpolateBoundary().
Referenced by Alaris.Core.Pricing.CRSL002A.SolveLowerBoundaryPointStabilized().
CheckStagnation()
static bool Alaris.Core.Pricing.CRSL002A.CheckStagnation (int iter, double maxChange, ref double previousMaxChange, ref int stagnationCount) inline static private
Definition at line 245 of file CRSL002A.cs.
References Alaris.Core.Pricing.CRSL002A.Tolerance.
Referenced by Alaris.Core.Pricing.CRSL002A.RefineUsingFpbPrime().
EnforceConstraints()
double double Lower Alaris.Core.Pricing.CRSL002A.EnforceConstraints (double upper, double lower) inline private
Definition at line 562 of file CRSL002A.cs.
References Alaris.Core.Pricing.CRSL002A._isCall, Alaris.Core.Pricing.CRSL002A._strike, and Alaris.Core.Pricing.CRSL002A.NumericalEpsilon.
Referenced by Alaris.Core.Pricing.CRSL002A.RefineUsingFpbPrime().
EnforceMonotonicity()
double[] Alaris.Core.Pricing.CRSL002A.EnforceMonotonicity (double[] boundary, int length, bool isIncreasing) inline private
Definition at line 620 of file CRSL002A.cs.
References Alaris.Core.Pricing.CRSL002A.PoolAdjacentViolators().
Referenced by Alaris.Core.Pricing.CRSL002A.RefineUsingFpbPrime().
FallbackToQdPlusConstant()
double[] double[] Lower Alaris.Core.Pricing.CRSL002A.FallbackToQdPlusConstant (int m) inline private
Definition at line 235 of file CRSL002A.cs.
References Alaris.Core.Pricing.CRSL002A._dividendYield, Alaris.Core.Pricing.CRSL002A._isCall, Alaris.Core.Pricing.CRSL002A._maturity, Alaris.Core.Pricing.CRSL002A._rate, Alaris.Core.Pricing.CRSL002A._spot, Alaris.Core.Pricing.CRSL002A._strike, Alaris.Core.Pricing.CRSL002A._volatility, and Alaris.Core.Pricing.CRAP001A.CalculateBoundaries().
Referenced by Alaris.Core.Pricing.CRSL002A.RefineUsingFpbPrime().
FindCrossingTime()
double Alaris.Core.Pricing.CRSL002A.FindCrossingTime (double[] upper, double[] lower) inline private
Definition at line 504 of file CRSL002A.cs.
References Alaris.Core.Pricing.CRSL002A._collocationPoints, and Alaris.Core.Pricing.CRSL002A._maturity.
InterpolateBoundary()
double Alaris.Core.Pricing.CRSL002A.InterpolateBoundary (double[] boundary, double t) inline private
Definition at line 586 of file CRSL002A.cs.
References Alaris.Core.Pricing.CRSL002A._maturity.
Referenced by Alaris.Core.Pricing.CRSL002A.CalculateDenominator(), Alaris.Core.Pricing.CRSL002A.CalculateDenominatorPrime(), Alaris.Core.Pricing.CRSL002A.CalculateIntegralTerm(), Alaris.Core.Pricing.CRSL002A.CalculateNumerator(), Alaris.Core.Pricing.CRSL002A.CalculateNumeratorPrime(), Alaris.Core.Pricing.CRSL002A.RefineCrossingTime(), Alaris.Core.Pricing.CRSL002A.SolveLowerBoundaryPointStabilized(), and Alaris.Core.Pricing.CRSL002A.SolveUpperBoundaryPoint().
IsInvalidBoundary()
static bool Alaris.Core.Pricing.CRSL002A.IsInvalidBoundary (double upper, double lower) inline static private
Definition at line 498 of file CRSL002A.cs.
Referenced by Alaris.Core.Pricing.CRSL002A.CalculateIntegralTerm().
IsInvalidRatio()
static bool Alaris.Core.Pricing.CRSL002A.IsInvalidRatio (double numerator, double denominator) inline static private
Definition at line 358 of file CRSL002A.cs.
References Alaris.Core.Pricing.CRSL002A.NumericalEpsilon.
Referenced by Alaris.Core.Pricing.CRSL002A.SolveLowerBoundaryPointStabilized(), and Alaris.Core.Pricing.CRSL002A.SolveUpperBoundaryPoint().
NormalCDF()
static double Alaris.Core.Pricing.CRSL002A.NormalCDF (double x) static private
Referenced by Alaris.Core.Pricing.CRSL002A.CalculateDenominator(), Alaris.Core.Pricing.CRSL002A.CalculateDenominatorPrime(), Alaris.Core.Pricing.CRSL002A.CalculateIntegralTerm(), and Alaris.Core.Pricing.CRSL002A.CalculateNumerator().
PoolAdjacentViolators()
static double[] Alaris.Core.Pricing.CRSL002A.PoolAdjacentViolators (double[] values, bool increasing) inline static private
Pool Adjacent Violators algorithm for isotonic regression. Optimized to use stack-allocated spans for small arrays (Rule 5).
Definition at line 632 of file CRSL002A.cs.
References Alaris.Core.Pricing.CRSL002A.PoolAdjacentViolators().
Referenced by Alaris.Core.Pricing.CRSL002A.EnforceMonotonicity(), and Alaris.Core.Pricing.CRSL002A.PoolAdjacentViolators().
RefineCrossingTime()
double Alaris.Core.Pricing.CRSL002A.RefineCrossingTime (double[] upper, double[] lower, double initialCrossing) inline private
Definition at line 516 of file CRSL002A.cs.
References Alaris.Core.Pricing.CRSL002A._maturity, Alaris.Core.Pricing.CRSL002A.CrossingTimeThreshold, and Alaris.Core.Pricing.CRSL002A.InterpolateBoundary().
RefineUsingFpbPrime()
double[] double[] Lower Alaris.Core.Pricing.CRSL002A.RefineUsingFpbPrime (double[] upperInitial, double[] lowerInitial, double crossingTime) inline private
Definition at line 109 of file CRSL002A.cs.
References Alaris.Core.Pricing.CRSL002A._collocationPoints, Alaris.Core.Pricing.CRSL002A._maturity, Alaris.Core.Pricing.CRSL002A.CheckStagnation(), Alaris.Core.Pricing.CRSL002A.EnforceConstraints(), Alaris.Core.Pricing.CRSL002A.EnforceMonotonicity(), Alaris.Core.Pricing.CRSL002A.FallbackToQdPlusConstant(), Alaris.Core.Pricing.CRSL002A.MaxIterations, Alaris.Core.Pricing.CRSL002A.NumericalEpsilon, Alaris.Core.Pricing.CRSL002A.SmoothBoundary(), Alaris.Core.Pricing.CRSL002A.SolveLowerBoundaryPointStabilized(), Alaris.Core.Pricing.CRSL002A.SolveUpperBoundaryPoint(), Alaris.Core.Pricing.CRSL002A.Tolerance, Alaris.Core.Pricing.CRSL002A.ValidateInitialInputs(), and Alaris.Core.Pricing.CRSL002A.ValidateRefinementResult().
SanitizeBoundaryValue()
double Alaris.Core.Pricing.CRSL002A.SanitizeBoundaryValue (double value, bool isUpper) inline private
Definition at line 329 of file CRSL002A.cs.
References Alaris.Core.Pricing.CRSL002A._isCall, Alaris.Core.Pricing.CRSL002A._strike, and Alaris.Core.Pricing.CRSL002A.NumericalEpsilon.
Referenced by Alaris.Core.Pricing.CRSL002A.SolveLowerBoundaryPointStabilized(), and Alaris.Core.Pricing.CRSL002A.SolveUpperBoundaryPoint().
SmoothBoundary()
static double[] Alaris.Core.Pricing.CRSL002A.SmoothBoundary (double[] boundary) inline static private
Apply Savitzky-Golay-style smoothing to reduce second-order oscillations. Uses weighted 5-point moving average for quadratic smoothing.
Definition at line 696 of file CRSL002A.cs.
Referenced by Alaris.Core.Pricing.CRSL002A.RefineUsingFpbPrime().
SolveBoundaries()
double[] double[] double CrossingTime Alaris.Core.Pricing.CRSL002A.SolveBoundaries (double upperInitial, double lowerInitial) inline
Definition at line 76 of file CRSL002A.cs.
Referenced by Alaris.Core.Pricing.CRSL001A.ApplyKimRefinement(), and Alaris.Core.Pricing.CREN004A.PriceDoubleBoundary().
SolveLowerBoundaryPointStabilized()
double Alaris.Core.Pricing.CRSL002A.SolveLowerBoundaryPointStabilized (double ti, double[] lowerOld, double[] upperNew, double crossingTime) inline private
Definition at line 304 of file CRSL002A.cs.
References Alaris.Core.Pricing.CRSL002A._isCall, Alaris.Core.Pricing.CRSL002A._strike, Alaris.Core.Pricing.CRSL002A.CalculateDenominatorPrime(), Alaris.Core.Pricing.CRSL002A.CalculateNumeratorPrime(), Alaris.Core.Pricing.CRSL002A.InterpolateBoundary(), Alaris.Core.Pricing.CRSL002A.IsInvalidRatio(), and Alaris.Core.Pricing.CRSL002A.SanitizeBoundaryValue().
Referenced by Alaris.Core.Pricing.CRSL002A.RefineUsingFpbPrime().
SolveUpperBoundaryPoint()
double Alaris.Core.Pricing.CRSL002A.SolveUpperBoundaryPoint (double ti, double[] upper, double[] lower, double crossingTime) inline private
Definition at line 282 of file CRSL002A.cs.
References Alaris.Core.Pricing.CRSL002A._isCall, Alaris.Core.Pricing.CRSL002A._strike, Alaris.Core.Pricing.CRSL002A.CalculateDenominator(), Alaris.Core.Pricing.CRSL002A.CalculateNumerator(), Alaris.Core.Pricing.CRSL002A.InterpolateBoundary(), Alaris.Core.Pricing.CRSL002A.IsInvalidRatio(), and Alaris.Core.Pricing.CRSL002A.SanitizeBoundaryValue().
Referenced by Alaris.Core.Pricing.CRSL002A.RefineUsingFpbPrime().
ValidateInitialInputs()
bool Alaris.Core.Pricing.CRSL002A.ValidateInitialInputs (double[] upper, double[] lower) inline private
Definition at line 222 of file CRSL002A.cs.
References Alaris.Core.Pricing.CRSL002A._collocationPoints, and Alaris.Core.Pricing.CRSL002A._strike.
Referenced by Alaris.Core.Pricing.CRSL002A.RefineUsingFpbPrime().
ValidateRefinementResult()
bool Alaris.Core.Pricing.CRSL002A.ValidateRefinementResult (double[] upper, double[] lower, double[] upperInit, double[] lowerInit) inline private
Definition at line 260 of file CRSL002A.cs.
References Alaris.Core.Pricing.CRSL002A._collocationPoints.
Referenced by Alaris.Core.Pricing.CRSL002A.RefineUsingFpbPrime().
Member Data Documentation
_collocationPoints
readonly int Alaris.Core.Pricing.CRSL002A._collocationPoints private
Definition at line 25 of file CRSL002A.cs.
Referenced by Alaris.Core.Pricing.CRSL002A.CRSL002A(), Alaris.Core.Pricing.CRSL002A.AdjustCrossingInitialGuess(), Alaris.Core.Pricing.CRSL002A.FindCrossingTime(), Alaris.Core.Pricing.CRSL002A.RefineUsingFpbPrime(), Alaris.Core.Pricing.CRSL002A.ValidateInitialInputs(), and Alaris.Core.Pricing.CRSL002A.ValidateRefinementResult().
_dividendYield
readonly double Alaris.Core.Pricing.CRSL002A._dividendYield private
Definition at line 22 of file CRSL002A.cs.
Referenced by Alaris.Core.Pricing.CRSL002A.CRSL002A(), Alaris.Core.Pricing.CRSL002A.CalculateD1(), Alaris.Core.Pricing.CRSL002A.CalculateDenominator(), Alaris.Core.Pricing.CRSL002A.CalculateDenominatorPrime(), Alaris.Core.Pricing.CRSL002A.CalculateIntegralTerm(), and Alaris.Core.Pricing.CRSL002A.FallbackToQdPlusConstant().
_isCall
readonly bool Alaris.Core.Pricing.CRSL002A._isCall private
Definition at line 24 of file CRSL002A.cs.
Referenced by Alaris.Core.Pricing.CRSL002A.CRSL002A(), Alaris.Core.Pricing.CRSL002A.EnforceConstraints(), Alaris.Core.Pricing.CRSL002A.FallbackToQdPlusConstant(), Alaris.Core.Pricing.CRSL002A.SanitizeBoundaryValue(), Alaris.Core.Pricing.CRSL002A.SolveLowerBoundaryPointStabilized(), and Alaris.Core.Pricing.CRSL002A.SolveUpperBoundaryPoint().
_maturity
readonly double Alaris.Core.Pricing.CRSL002A._maturity private
Definition at line 20 of file CRSL002A.cs.
Referenced by Alaris.Core.Pricing.CRSL002A.CRSL002A(), Alaris.Core.Pricing.CRSL002A.AdjustCrossingInitialGuess(), Alaris.Core.Pricing.CRSL002A.CalculateDenominator(), Alaris.Core.Pricing.CRSL002A.CalculateDenominatorPrime(), Alaris.Core.Pricing.CRSL002A.CalculateIntegralTerm(), Alaris.Core.Pricing.CRSL002A.CalculateNumerator(), Alaris.Core.Pricing.CRSL002A.FallbackToQdPlusConstant(), Alaris.Core.Pricing.CRSL002A.FindCrossingTime(), Alaris.Core.Pricing.CRSL002A.InterpolateBoundary(), Alaris.Core.Pricing.CRSL002A.RefineCrossingTime(), and Alaris.Core.Pricing.CRSL002A.RefineUsingFpbPrime().
_rate
readonly double Alaris.Core.Pricing.CRSL002A._rate private
Definition at line 21 of file CRSL002A.cs.
Referenced by Alaris.Core.Pricing.CRSL002A.CRSL002A(), Alaris.Core.Pricing.CRSL002A.CalculateD1(), Alaris.Core.Pricing.CRSL002A.CalculateIntegralTerm(), Alaris.Core.Pricing.CRSL002A.CalculateNumerator(), and Alaris.Core.Pricing.CRSL002A.FallbackToQdPlusConstant().
_spot
readonly double Alaris.Core.Pricing.CRSL002A._spot private
Definition at line 18 of file CRSL002A.cs.
Referenced by Alaris.Core.Pricing.CRSL002A.CRSL002A(), and Alaris.Core.Pricing.CRSL002A.FallbackToQdPlusConstant().
_strike
readonly double Alaris.Core.Pricing.CRSL002A._strike private
Definition at line 19 of file CRSL002A.cs.
Referenced by Alaris.Core.Pricing.CRSL002A.CRSL002A(), Alaris.Core.Pricing.CRSL002A.CalculateDenominator(), Alaris.Core.Pricing.CRSL002A.CalculateDenominatorPrime(), Alaris.Core.Pricing.CRSL002A.CalculateNumerator(), Alaris.Core.Pricing.CRSL002A.CalculateNumeratorPrime(), Alaris.Core.Pricing.CRSL002A.EnforceConstraints(), Alaris.Core.Pricing.CRSL002A.FallbackToQdPlusConstant(), Alaris.Core.Pricing.CRSL002A.SanitizeBoundaryValue(), Alaris.Core.Pricing.CRSL002A.SolveLowerBoundaryPointStabilized(), Alaris.Core.Pricing.CRSL002A.SolveUpperBoundaryPoint(), and Alaris.Core.Pricing.CRSL002A.ValidateInitialInputs().
_volatility
readonly double Alaris.Core.Pricing.CRSL002A._volatility private
Definition at line 23 of file CRSL002A.cs.
Referenced by Alaris.Core.Pricing.CRSL002A.CRSL002A(), Alaris.Core.Pricing.CRSL002A.CalculateD1(), Alaris.Core.Pricing.CRSL002A.CalculateD2(), and Alaris.Core.Pricing.CRSL002A.FallbackToQdPlusConstant().
CrossingTimeThreshold
const double Alaris.Core.Pricing.CRSL002A.CrossingTimeThreshold = 1e-2 static private
Definition at line 36 of file CRSL002A.cs.
Referenced by Alaris.Core.Pricing.CRSL002A.RefineCrossingTime().
IntegrationPoints
const int Alaris.Core.Pricing.CRSL002A.IntegrationPoints = 50 static private
Definition at line 34 of file CRSL002A.cs.
Referenced by Alaris.Core.Pricing.CRSL002A.CalculateIntegralTerm().
Lower
double [] double [] Alaris.Core.Pricing.CRSL002A.Lower
Definition at line 76 of file CRSL002A.cs.
MaxIterations
const int Alaris.Core.Pricing.CRSL002A.MaxIterations = 100 static private
Definition at line 33 of file CRSL002A.cs.
Referenced by Alaris.Core.Pricing.CRSL002A.RefineUsingFpbPrime().
NumericalEpsilon
const double Alaris.Core.Pricing.CRSL002A.NumericalEpsilon = 1e-10 static private
Definition at line 35 of file CRSL002A.cs.
Referenced by Alaris.Core.Pricing.CRSL002A.CalculateD1(), Alaris.Core.Pricing.CRSL002A.CalculateD2(), Alaris.Core.Pricing.CRSL002A.CalculateDenominator(), Alaris.Core.Pricing.CRSL002A.CalculateIntegralTerm(), Alaris.Core.Pricing.CRSL002A.CalculateNumerator(), Alaris.Core.Pricing.CRSL002A.EnforceConstraints(), Alaris.Core.Pricing.CRSL002A.IsInvalidRatio(), Alaris.Core.Pricing.CRSL002A.RefineUsingFpbPrime(), and Alaris.Core.Pricing.CRSL002A.SanitizeBoundaryValue().
Tolerance
const double Alaris.Core.Pricing.CRSL002A.Tolerance = 1e-6 static private
Definition at line 32 of file CRSL002A.cs.
Referenced by Alaris.Core.Pricing.CRSL002A.CheckStagnation(), and Alaris.Core.Pricing.CRSL002A.RefineUsingFpbPrime().
Upper [1/2]
double [] Alaris.Core.Pricing.CRSL002A.Upper
Solves for refined boundaries using Kim's integral equation with FP-B' stabilized iteration.
Refines boundaries using FP-B' stabilized fixed point iteration (Healy Equations 33-35). Uses ArrayPool for zero-allocation iteration buffers (Rule 5: Zero-Allocation Hot Paths).
Parameters
upperInitial Initial upper boundary from QD+.
lowerInitial Initial lower boundary from QD+.
Returns
Refined (upper, lower) boundaries and crossing time.
Definition at line 76 of file CRSL002A.cs.
Upper [2/2]
double Alaris.Core.Pricing.CRSL002A.Upper private
Definition at line 562 of file CRSL002A.cs.
Property Documentation
CollocationPoints
int Alaris.Core.Pricing.CRSL002A.CollocationPoints get
Number of collocation points used for boundary refinement.
Definition at line 30 of file CRSL002A.cs.
The documentation for this class was generated from the following file:
src/Alaris.Core/Pricing/CRSL002A.cs