Alaris: Alaris.Test.Unit.DTmd003ATests Class Reference
Alaris.Test.Unit.DTmd003ATests Class Reference sealed
Unit tests for DTmd003A corporate action model.
Public Member Functions
void GetPriceMultiplier_TwoForOneSplit_ReturnsHalf ()
void GetStrikeMultiplier_TwoForOneSplit_ReturnsHalf ()
void GetPriceMultiplier_FourForOneSplit_ReturnsQuarter ()
void GetPriceMultiplier_OneForTenReverseSplit_ReturnsTen ()
void GetStrikeMultiplier_OneForTenReverseSplit_ReturnsTen ()
void GetPriceMultiplier_FivePercentStockDividend_ReturnsAdjustedMultiplier ()
void GetPriceMultiplier_CashDividend_ReturnsOne ()
void GetStrikeMultiplier_CashDividend_ReturnsOne ()
void RequiresPriceAdjustment_VariousTypes_ReturnsExpected (CorporateActionType type, bool expected)
void RequiresStrikeAdjustment_VariousTypes_ReturnsExpected (CorporateActionType type, bool expected)
void Equals_SameValues_ReturnsTrue ()
void Equals_DifferentSymbol_ReturnsFalse ()
Detailed Description
Unit tests for DTmd003A corporate action model.
Definition at line 11 of file TSUN004A.cs.
Member Function Documentation
Equals_DifferentSymbol_ReturnsFalse()
void Alaris.Test.Unit.DTmd003ATests.Equals_DifferentSymbol_ReturnsFalse () inline
Definition at line 226 of file TSUN004A.cs.
References Alaris.Infrastructure.Data.Model.DTmd003A().
Equals_SameValues_ReturnsTrue()
void Alaris.Test.Unit.DTmd003ATests.Equals_SameValues_ReturnsTrue () inline
Definition at line 214 of file TSUN004A.cs.
References Alaris.Infrastructure.Data.Model.DTmd003A().
GetPriceMultiplier_CashDividend_ReturnsOne()
void Alaris.Test.Unit.DTmd003ATests.GetPriceMultiplier_CashDividend_ReturnsOne () inline
Definition at line 130 of file TSUN004A.cs.
References Alaris.Infrastructure.Data.Model.DTmd003A().
GetPriceMultiplier_FivePercentStockDividend_ReturnsAdjustedMultiplier()
void Alaris.Test.Unit.DTmd003ATests.GetPriceMultiplier_FivePercentStockDividend_ReturnsAdjustedMultiplier () inline
Definition at line 110 of file TSUN004A.cs.
References Alaris.Infrastructure.Data.Model.DTmd003A().
GetPriceMultiplier_FourForOneSplit_ReturnsQuarter()
void Alaris.Test.Unit.DTmd003ATests.GetPriceMultiplier_FourForOneSplit_ReturnsQuarter () inline
Definition at line 52 of file TSUN004A.cs.
References Alaris.Infrastructure.Data.Model.DTmd003A().
GetPriceMultiplier_OneForTenReverseSplit_ReturnsTen()
void Alaris.Test.Unit.DTmd003ATests.GetPriceMultiplier_OneForTenReverseSplit_ReturnsTen () inline
Definition at line 72 of file TSUN004A.cs.
References Alaris.Infrastructure.Data.Model.DTmd003A().
GetPriceMultiplier_TwoForOneSplit_ReturnsHalf()
void Alaris.Test.Unit.DTmd003ATests.GetPriceMultiplier_TwoForOneSplit_ReturnsHalf () inline
Definition at line 16 of file TSUN004A.cs.
References Alaris.Infrastructure.Data.Model.DTmd003A().
GetStrikeMultiplier_CashDividend_ReturnsOne()
void Alaris.Test.Unit.DTmd003ATests.GetStrikeMultiplier_CashDividend_ReturnsOne () inline
Definition at line 148 of file TSUN004A.cs.
References Alaris.Infrastructure.Data.Model.DTmd003A().
GetStrikeMultiplier_OneForTenReverseSplit_ReturnsTen()
void Alaris.Test.Unit.DTmd003ATests.GetStrikeMultiplier_OneForTenReverseSplit_ReturnsTen () inline
Definition at line 90 of file TSUN004A.cs.
References Alaris.Infrastructure.Data.Model.DTmd003A().
GetStrikeMultiplier_TwoForOneSplit_ReturnsHalf()
void Alaris.Test.Unit.DTmd003ATests.GetStrikeMultiplier_TwoForOneSplit_ReturnsHalf () inline
Definition at line 34 of file TSUN004A.cs.
References Alaris.Infrastructure.Data.Model.DTmd003A().
RequiresPriceAdjustment_VariousTypes_ReturnsExpected()
void Alaris.Test.Unit.DTmd003ATests.RequiresPriceAdjustment_VariousTypes_ReturnsExpected (CorporateActionType type, bool expected) inline
Definition at line 174 of file TSUN004A.cs.
References Alaris.Infrastructure.Data.Model.DTmd003A().
RequiresStrikeAdjustment_VariousTypes_ReturnsExpected()
void Alaris.Test.Unit.DTmd003ATests.RequiresStrikeAdjustment_VariousTypes_ReturnsExpected (CorporateActionType type, bool expected) inline
Definition at line 196 of file TSUN004A.cs.
References Alaris.Infrastructure.Data.Model.DTmd003A().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN004A.cs