//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ArithmeticAveragedOvernightIndexedCouponPricer : FloatingRateCouponPricer {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal ArithmeticAveragedOvernightIndexedCouponPricer(global::System.IntPtr cPtr, bool cMemoryOwn) : base(NQuantLibcPINVOKE.ArithmeticAveragedOvernightIndexedCouponPricer_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ArithmeticAveragedOvernightIndexedCouponPricer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          NQuantLibcPINVOKE.delete_ArithmeticAveragedOvernightIndexedCouponPricer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public ArithmeticAveragedOvernightIndexedCouponPricer(double meanReversion, double volatility, bool byApprox) : this(NQuantLibcPINVOKE.new_ArithmeticAveragedOvernightIndexedCouponPricer__SWIG_0(meanReversion, volatility, byApprox), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public ArithmeticAveragedOvernightIndexedCouponPricer(double meanReversion, double volatility) : this(NQuantLibcPINVOKE.new_ArithmeticAveragedOvernightIndexedCouponPricer__SWIG_1(meanReversion, volatility), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public ArithmeticAveragedOvernightIndexedCouponPricer(double meanReversion) : this(NQuantLibcPINVOKE.new_ArithmeticAveragedOvernightIndexedCouponPricer__SWIG_2(meanReversion), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public ArithmeticAveragedOvernightIndexedCouponPricer() : this(NQuantLibcPINVOKE.new_ArithmeticAveragedOvernightIndexedCouponPricer__SWIG_3(), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

}
