//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ExponentialSplinesFitting : FittingMethod {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal ExponentialSplinesFitting(global::System.IntPtr cPtr, bool cMemoryOwn) : base(NQuantLibcPINVOKE.ExponentialSplinesFitting_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ExponentialSplinesFitting obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          NQuantLibcPINVOKE.delete_ExponentialSplinesFitting(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public ExponentialSplinesFitting(bool constrainAtZero, QlArray weights, QlArray l2, double minCutoffTime, double maxCutoffTime, uint numCoeffs, double fixedKappa, Constraint constraint) : this(NQuantLibcPINVOKE.new_ExponentialSplinesFitting__SWIG_0(constrainAtZero, QlArray.getCPtr(weights), QlArray.getCPtr(l2), minCutoffTime, maxCutoffTime, numCoeffs, fixedKappa, Constraint.getCPtr(constraint)), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public ExponentialSplinesFitting(bool constrainAtZero, QlArray weights, QlArray l2, double minCutoffTime, double maxCutoffTime, uint numCoeffs, double fixedKappa) : this(NQuantLibcPINVOKE.new_ExponentialSplinesFitting__SWIG_1(constrainAtZero, QlArray.getCPtr(weights), QlArray.getCPtr(l2), minCutoffTime, maxCutoffTime, numCoeffs, fixedKappa), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public ExponentialSplinesFitting(bool constrainAtZero, QlArray weights, QlArray l2, double minCutoffTime, double maxCutoffTime, uint numCoeffs) : this(NQuantLibcPINVOKE.new_ExponentialSplinesFitting__SWIG_2(constrainAtZero, QlArray.getCPtr(weights), QlArray.getCPtr(l2), minCutoffTime, maxCutoffTime, numCoeffs), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public ExponentialSplinesFitting(bool constrainAtZero, QlArray weights, QlArray l2, double minCutoffTime, double maxCutoffTime) : this(NQuantLibcPINVOKE.new_ExponentialSplinesFitting__SWIG_3(constrainAtZero, QlArray.getCPtr(weights), QlArray.getCPtr(l2), minCutoffTime, maxCutoffTime), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public ExponentialSplinesFitting(bool constrainAtZero, QlArray weights, QlArray l2, double minCutoffTime) : this(NQuantLibcPINVOKE.new_ExponentialSplinesFitting__SWIG_4(constrainAtZero, QlArray.getCPtr(weights), QlArray.getCPtr(l2), minCutoffTime), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public ExponentialSplinesFitting(bool constrainAtZero, QlArray weights, QlArray l2) : this(NQuantLibcPINVOKE.new_ExponentialSplinesFitting__SWIG_5(constrainAtZero, QlArray.getCPtr(weights), QlArray.getCPtr(l2)), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public ExponentialSplinesFitting(bool constrainAtZero, QlArray weights) : this(NQuantLibcPINVOKE.new_ExponentialSplinesFitting__SWIG_6(constrainAtZero, QlArray.getCPtr(weights)), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public ExponentialSplinesFitting(bool constrainAtZero) : this(NQuantLibcPINVOKE.new_ExponentialSplinesFitting__SWIG_7(constrainAtZero), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public ExponentialSplinesFitting() : this(NQuantLibcPINVOKE.new_ExponentialSplinesFitting__SWIG_8(), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

}
