//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class FdCEVVanillaEngine : PricingEngine {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal FdCEVVanillaEngine(global::System.IntPtr cPtr, bool cMemoryOwn) : base(NQuantLibcPINVOKE.FdCEVVanillaEngine_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FdCEVVanillaEngine obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          NQuantLibcPINVOKE.delete_FdCEVVanillaEngine(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public FdCEVVanillaEngine(double f0, double alpha, double beta, YieldTermStructureHandle rTS, uint tGrid, uint xGrid, uint dampingSteps, double scalingFactor, double eps, FdmSchemeDesc schemeDesc) : this(NQuantLibcPINVOKE.new_FdCEVVanillaEngine__SWIG_0(f0, alpha, beta, YieldTermStructureHandle.getCPtr(rTS), tGrid, xGrid, dampingSteps, scalingFactor, eps, FdmSchemeDesc.getCPtr(schemeDesc)), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public FdCEVVanillaEngine(double f0, double alpha, double beta, YieldTermStructureHandle rTS, uint tGrid, uint xGrid, uint dampingSteps, double scalingFactor, double eps) : this(NQuantLibcPINVOKE.new_FdCEVVanillaEngine__SWIG_1(f0, alpha, beta, YieldTermStructureHandle.getCPtr(rTS), tGrid, xGrid, dampingSteps, scalingFactor, eps), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public FdCEVVanillaEngine(double f0, double alpha, double beta, YieldTermStructureHandle rTS, uint tGrid, uint xGrid, uint dampingSteps, double scalingFactor) : this(NQuantLibcPINVOKE.new_FdCEVVanillaEngine__SWIG_2(f0, alpha, beta, YieldTermStructureHandle.getCPtr(rTS), tGrid, xGrid, dampingSteps, scalingFactor), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public FdCEVVanillaEngine(double f0, double alpha, double beta, YieldTermStructureHandle rTS, uint tGrid, uint xGrid, uint dampingSteps) : this(NQuantLibcPINVOKE.new_FdCEVVanillaEngine__SWIG_3(f0, alpha, beta, YieldTermStructureHandle.getCPtr(rTS), tGrid, xGrid, dampingSteps), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public FdCEVVanillaEngine(double f0, double alpha, double beta, YieldTermStructureHandle rTS, uint tGrid, uint xGrid) : this(NQuantLibcPINVOKE.new_FdCEVVanillaEngine__SWIG_4(f0, alpha, beta, YieldTermStructureHandle.getCPtr(rTS), tGrid, xGrid), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public FdCEVVanillaEngine(double f0, double alpha, double beta, YieldTermStructureHandle rTS, uint tGrid) : this(NQuantLibcPINVOKE.new_FdCEVVanillaEngine__SWIG_5(f0, alpha, beta, YieldTermStructureHandle.getCPtr(rTS), tGrid), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public FdCEVVanillaEngine(double f0, double alpha, double beta, YieldTermStructureHandle rTS) : this(NQuantLibcPINVOKE.new_FdCEVVanillaEngine__SWIG_6(f0, alpha, beta, YieldTermStructureHandle.getCPtr(rTS)), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

}
