//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IborIborBasisSwapRateHelper : RateHelper {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal IborIborBasisSwapRateHelper(global::System.IntPtr cPtr, bool cMemoryOwn) : base(NQuantLibcPINVOKE.IborIborBasisSwapRateHelper_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IborIborBasisSwapRateHelper obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          NQuantLibcPINVOKE.delete_IborIborBasisSwapRateHelper(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public IborIborBasisSwapRateHelper(QuoteHandle basis, Period tenor, uint settlementDays, Calendar calendar, BusinessDayConvention convention, bool endOfMonth, IborIndex baseIndex, IborIndex otherIndex, YieldTermStructureHandle discountHandle, bool bootstrapBaseCurve) : this(NQuantLibcPINVOKE.new_IborIborBasisSwapRateHelper(QuoteHandle.getCPtr(basis), Period.getCPtr(tenor), settlementDays, Calendar.getCPtr(calendar), (int)convention, endOfMonth, IborIndex.getCPtr(baseIndex), IborIndex.getCPtr(otherIndex), YieldTermStructureHandle.getCPtr(discountHandle), bootstrapBaseCurve), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public Swap swap() {
    global::System.IntPtr cPtr = NQuantLibcPINVOKE.IborIborBasisSwapRateHelper_swap(swigCPtr);
    Swap ret = (cPtr == global::System.IntPtr.Zero) ? null : new Swap(cPtr, true);
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
