//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ModifiedCraigSneydScheme : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal ModifiedCraigSneydScheme(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ModifiedCraigSneydScheme obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ModifiedCraigSneydScheme() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          NQuantLibcPINVOKE.delete_ModifiedCraigSneydScheme(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ModifiedCraigSneydScheme(double theta, double mu, FdmLinearOpComposite map, FdmBoundaryConditionSet bcSet) : this(NQuantLibcPINVOKE.new_ModifiedCraigSneydScheme__SWIG_0(theta, mu, FdmLinearOpComposite.getCPtr(map), FdmBoundaryConditionSet.getCPtr(bcSet)), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public ModifiedCraigSneydScheme(double theta, double mu, FdmLinearOpComposite map) : this(NQuantLibcPINVOKE.new_ModifiedCraigSneydScheme__SWIG_1(theta, mu, FdmLinearOpComposite.getCPtr(map)), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public void step(QlArray a, double t) {
    NQuantLibcPINVOKE.ModifiedCraigSneydScheme_step(swigCPtr, QlArray.getCPtr(a), t);
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setStep(double dt) {
    NQuantLibcPINVOKE.ModifiedCraigSneydScheme_setStep(swigCPtr, dt);
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

}
