//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class MtMCrossCurrencyBasisSwapRateHelper : RateHelper {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal MtMCrossCurrencyBasisSwapRateHelper(global::System.IntPtr cPtr, bool cMemoryOwn) : base(NQuantLibcPINVOKE.MtMCrossCurrencyBasisSwapRateHelper_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MtMCrossCurrencyBasisSwapRateHelper obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          NQuantLibcPINVOKE.delete_MtMCrossCurrencyBasisSwapRateHelper(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public MtMCrossCurrencyBasisSwapRateHelper(QuoteHandle basis, Period tenor, uint fixingDays, Calendar calendar, BusinessDayConvention convention, bool endOfMonth, IborIndex baseCurrencyIndex, IborIndex quoteCurrencyIndex, YieldTermStructureHandle collateralCurve, bool isFxBaseCurrencyCollateralCurrency, bool isBasisOnFxBaseCurrencyLeg, bool isFxBaseCurrencyLegResettable, Frequency paymentFrequency, int paymentLag) : this(NQuantLibcPINVOKE.new_MtMCrossCurrencyBasisSwapRateHelper__SWIG_0(QuoteHandle.getCPtr(basis), Period.getCPtr(tenor), fixingDays, Calendar.getCPtr(calendar), (int)convention, endOfMonth, IborIndex.getCPtr(baseCurrencyIndex), IborIndex.getCPtr(quoteCurrencyIndex), YieldTermStructureHandle.getCPtr(collateralCurve), isFxBaseCurrencyCollateralCurrency, isBasisOnFxBaseCurrencyLeg, isFxBaseCurrencyLegResettable, (int)paymentFrequency, paymentLag), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public MtMCrossCurrencyBasisSwapRateHelper(QuoteHandle basis, Period tenor, uint fixingDays, Calendar calendar, BusinessDayConvention convention, bool endOfMonth, IborIndex baseCurrencyIndex, IborIndex quoteCurrencyIndex, YieldTermStructureHandle collateralCurve, bool isFxBaseCurrencyCollateralCurrency, bool isBasisOnFxBaseCurrencyLeg, bool isFxBaseCurrencyLegResettable, Frequency paymentFrequency) : this(NQuantLibcPINVOKE.new_MtMCrossCurrencyBasisSwapRateHelper__SWIG_1(QuoteHandle.getCPtr(basis), Period.getCPtr(tenor), fixingDays, Calendar.getCPtr(calendar), (int)convention, endOfMonth, IborIndex.getCPtr(baseCurrencyIndex), IborIndex.getCPtr(quoteCurrencyIndex), YieldTermStructureHandle.getCPtr(collateralCurve), isFxBaseCurrencyCollateralCurrency, isBasisOnFxBaseCurrencyLeg, isFxBaseCurrencyLegResettable, (int)paymentFrequency), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public MtMCrossCurrencyBasisSwapRateHelper(QuoteHandle basis, Period tenor, uint fixingDays, Calendar calendar, BusinessDayConvention convention, bool endOfMonth, IborIndex baseCurrencyIndex, IborIndex quoteCurrencyIndex, YieldTermStructureHandle collateralCurve, bool isFxBaseCurrencyCollateralCurrency, bool isBasisOnFxBaseCurrencyLeg, bool isFxBaseCurrencyLegResettable) : this(NQuantLibcPINVOKE.new_MtMCrossCurrencyBasisSwapRateHelper__SWIG_2(QuoteHandle.getCPtr(basis), Period.getCPtr(tenor), fixingDays, Calendar.getCPtr(calendar), (int)convention, endOfMonth, IborIndex.getCPtr(baseCurrencyIndex), IborIndex.getCPtr(quoteCurrencyIndex), YieldTermStructureHandle.getCPtr(collateralCurve), isFxBaseCurrencyCollateralCurrency, isBasisOnFxBaseCurrencyLeg, isFxBaseCurrencyLegResettable), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

}
