//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class RelinkableZeroInflationTermStructureHandle : ZeroInflationTermStructureHandle {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal RelinkableZeroInflationTermStructureHandle(global::System.IntPtr cPtr, bool cMemoryOwn) : base(NQuantLibcPINVOKE.RelinkableZeroInflationTermStructureHandle_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RelinkableZeroInflationTermStructureHandle obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(RelinkableZeroInflationTermStructureHandle obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NQuantLibcPINVOKE.delete_RelinkableZeroInflationTermStructureHandle(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public RelinkableZeroInflationTermStructureHandle() : this(NQuantLibcPINVOKE.new_RelinkableZeroInflationTermStructureHandle__SWIG_0(), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public RelinkableZeroInflationTermStructureHandle(ZeroInflationTermStructure p, bool registerAsObserver) : this(NQuantLibcPINVOKE.new_RelinkableZeroInflationTermStructureHandle__SWIG_1(ZeroInflationTermStructure.getCPtr(p), registerAsObserver), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public RelinkableZeroInflationTermStructureHandle(ZeroInflationTermStructure p) : this(NQuantLibcPINVOKE.new_RelinkableZeroInflationTermStructureHandle__SWIG_2(ZeroInflationTermStructure.getCPtr(p)), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public void linkTo(ZeroInflationTermStructure h, bool registerAsObserver) {
    NQuantLibcPINVOKE.RelinkableZeroInflationTermStructureHandle_linkTo__SWIG_0(swigCPtr, ZeroInflationTermStructure.getCPtr(h), registerAsObserver);
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public void linkTo(ZeroInflationTermStructure h) {
    NQuantLibcPINVOKE.RelinkableZeroInflationTermStructureHandle_linkTo__SWIG_1(swigCPtr, ZeroInflationTermStructure.getCPtr(h));
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public void reset() {
    NQuantLibcPINVOKE.RelinkableZeroInflationTermStructureHandle_reset(swigCPtr);
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

}
