//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class SquareRootProcessRNDCalculator : RiskNeutralDensityCalculator {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal SquareRootProcessRNDCalculator(global::System.IntPtr cPtr, bool cMemoryOwn) : base(NQuantLibcPINVOKE.SquareRootProcessRNDCalculator_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SquareRootProcessRNDCalculator obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          NQuantLibcPINVOKE.delete_SquareRootProcessRNDCalculator(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public SquareRootProcessRNDCalculator(double v0, double kappa, double theta, double sigma) : this(NQuantLibcPINVOKE.new_SquareRootProcessRNDCalculator(v0, kappa, theta, sigma), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public double stationary_pdf(double v) {
    double ret = NQuantLibcPINVOKE.SquareRootProcessRNDCalculator_stationary_pdf(swigCPtr, v);
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double stationary_cdf(double v) {
    double ret = NQuantLibcPINVOKE.SquareRootProcessRNDCalculator_stationary_cdf(swigCPtr, v);
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double stationary_invcdf(double q) {
    double ret = NQuantLibcPINVOKE.SquareRootProcessRNDCalculator_stationary_invcdf(swigCPtr, q);
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
