//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class SubPeriodsCoupon : FloatingRateCoupon {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal SubPeriodsCoupon(global::System.IntPtr cPtr, bool cMemoryOwn) : base(NQuantLibcPINVOKE.SubPeriodsCoupon_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SubPeriodsCoupon obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          NQuantLibcPINVOKE.delete_SubPeriodsCoupon(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public SubPeriodsCoupon(Date paymentDate, double nominal, Date startDate, Date endDate, uint fixingDays, IborIndex index, double gearing, double couponSpread, double rateSpread, Date refPeriodStart, Date refPeriodEnd, DayCounter dayCounter, Date exCouponDate) : this(NQuantLibcPINVOKE.new_SubPeriodsCoupon__SWIG_0(Date.getCPtr(paymentDate), nominal, Date.getCPtr(startDate), Date.getCPtr(endDate), fixingDays, IborIndex.getCPtr(index), gearing, couponSpread, rateSpread, Date.getCPtr(refPeriodStart), Date.getCPtr(refPeriodEnd), DayCounter.getCPtr(dayCounter), Date.getCPtr(exCouponDate)), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public SubPeriodsCoupon(Date paymentDate, double nominal, Date startDate, Date endDate, uint fixingDays, IborIndex index, double gearing, double couponSpread, double rateSpread, Date refPeriodStart, Date refPeriodEnd, DayCounter dayCounter) : this(NQuantLibcPINVOKE.new_SubPeriodsCoupon__SWIG_1(Date.getCPtr(paymentDate), nominal, Date.getCPtr(startDate), Date.getCPtr(endDate), fixingDays, IborIndex.getCPtr(index), gearing, couponSpread, rateSpread, Date.getCPtr(refPeriodStart), Date.getCPtr(refPeriodEnd), DayCounter.getCPtr(dayCounter)), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public SubPeriodsCoupon(Date paymentDate, double nominal, Date startDate, Date endDate, uint fixingDays, IborIndex index, double gearing, double couponSpread, double rateSpread, Date refPeriodStart, Date refPeriodEnd) : this(NQuantLibcPINVOKE.new_SubPeriodsCoupon__SWIG_2(Date.getCPtr(paymentDate), nominal, Date.getCPtr(startDate), Date.getCPtr(endDate), fixingDays, IborIndex.getCPtr(index), gearing, couponSpread, rateSpread, Date.getCPtr(refPeriodStart), Date.getCPtr(refPeriodEnd)), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public SubPeriodsCoupon(Date paymentDate, double nominal, Date startDate, Date endDate, uint fixingDays, IborIndex index, double gearing, double couponSpread, double rateSpread, Date refPeriodStart) : this(NQuantLibcPINVOKE.new_SubPeriodsCoupon__SWIG_3(Date.getCPtr(paymentDate), nominal, Date.getCPtr(startDate), Date.getCPtr(endDate), fixingDays, IborIndex.getCPtr(index), gearing, couponSpread, rateSpread, Date.getCPtr(refPeriodStart)), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public SubPeriodsCoupon(Date paymentDate, double nominal, Date startDate, Date endDate, uint fixingDays, IborIndex index, double gearing, double couponSpread, double rateSpread) : this(NQuantLibcPINVOKE.new_SubPeriodsCoupon__SWIG_4(Date.getCPtr(paymentDate), nominal, Date.getCPtr(startDate), Date.getCPtr(endDate), fixingDays, IborIndex.getCPtr(index), gearing, couponSpread, rateSpread), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public SubPeriodsCoupon(Date paymentDate, double nominal, Date startDate, Date endDate, uint fixingDays, IborIndex index, double gearing, double couponSpread) : this(NQuantLibcPINVOKE.new_SubPeriodsCoupon__SWIG_5(Date.getCPtr(paymentDate), nominal, Date.getCPtr(startDate), Date.getCPtr(endDate), fixingDays, IborIndex.getCPtr(index), gearing, couponSpread), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public SubPeriodsCoupon(Date paymentDate, double nominal, Date startDate, Date endDate, uint fixingDays, IborIndex index, double gearing) : this(NQuantLibcPINVOKE.new_SubPeriodsCoupon__SWIG_6(Date.getCPtr(paymentDate), nominal, Date.getCPtr(startDate), Date.getCPtr(endDate), fixingDays, IborIndex.getCPtr(index), gearing), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public SubPeriodsCoupon(Date paymentDate, double nominal, Date startDate, Date endDate, uint fixingDays, IborIndex index) : this(NQuantLibcPINVOKE.new_SubPeriodsCoupon__SWIG_7(Date.getCPtr(paymentDate), nominal, Date.getCPtr(startDate), Date.getCPtr(endDate), fixingDays, IborIndex.getCPtr(index)), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public DateVector fixingDates() {
    DateVector ret = new DateVector(NQuantLibcPINVOKE.SubPeriodsCoupon_fixingDates(swigCPtr), false);
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public DoubleVector dt() {
    DoubleVector ret = new DoubleVector(NQuantLibcPINVOKE.SubPeriodsCoupon_dt(swigCPtr), false);
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public DateVector valueDates() {
    DateVector ret = new DateVector(NQuantLibcPINVOKE.SubPeriodsCoupon_valueDates(swigCPtr), false);
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double rateSpread() {
    double ret = NQuantLibcPINVOKE.SubPeriodsCoupon_rateSpread(swigCPtr);
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
