Alaris: Alaris.Infrastructure.Data.Quality.VolumeOpenInterestValidator Class Reference
Alaris.Infrastructure.Data.Quality.VolumeOpenInterestValidator Class Reference sealed
Validates volume and open interest for liquidity requirements. Component ID: DTqc003A.
Public Member Functions
VolumeOpenInterestValidator (ILogger< VolumeOpenInterestValidator > logger)
Initializes a new instance of the VolumeOpenInterestValidator class.
DataQualityResult Validate (MarketDataSnapshot snapshot)
Validates market data snapshot.
Parameters
snapshot The market data to validate.
Returns
Validation result.
Properties
string ComponentId [get]
Gets the validator component ID (e.g., "DTqc001A").
Properties inherited from Alaris.Infrastructure.Data.Quality.DTqc002A
Private Attributes
readonly ILogger< VolumeOpenInterestValidator > _logger
Detailed Description
Validates volume and open interest for liquidity requirements. Component ID: DTqc003A.
Validation checks:
Volume > 0 for liquid options (OI > 100)
Volume within 10× of 30-day average
OI change consistent with volume
Definition at line 254 of file DTqc001A.cs.
Constructor & Destructor Documentation
VolumeOpenInterestValidator()
Alaris.Infrastructure.Data.Quality.VolumeOpenInterestValidator.VolumeOpenInterestValidator (ILogger< VolumeOpenInterestValidator > logger) inline
Initializes a new instance of the VolumeOpenInterestValidator class.
Definition at line 264 of file DTqc001A.cs.
References Alaris.Infrastructure.Data.Quality.VolumeOpenInterestValidator._logger.
Member Function Documentation
Validate()
DataQualityResult Alaris.Infrastructure.Data.Quality.VolumeOpenInterestValidator.Validate (MarketDataSnapshot snapshot) inline
Validates market data snapshot.
Parameters
snapshot The market data to validate.
Returns
Validation result.
Implements Alaris.Infrastructure.Data.Quality.DTqc002A.
Definition at line 270 of file DTqc001A.cs.
References Alaris.Infrastructure.Data.Quality.VolumeOpenInterestValidator.ComponentId.
Referenced by Alaris.Test.Unit.DTqc003ATests.Validate_HighVolumeToOiRatio_ShouldWarn(), Alaris.Test.Unit.DTqc003ATests.Validate_LiquidOptionWithNoVolume_ShouldWarn(), Alaris.Test.Unit.DTqc003ATests.Validate_ValidLiquidOption_ShouldPass(), Alaris.Test.Unit.DTqc003ATests.Validate_VolumeSpike_ShouldWarn(), and Alaris.Test.Unit.DTqc003ATests.Validate_ZeroAverageVolume_ShouldFail().
Member Data Documentation
_logger
readonly ILogger<VolumeOpenInterestValidator> Alaris.Infrastructure.Data.Quality.VolumeOpenInterestValidator._logger private
Definition at line 256 of file DTqc001A.cs.
Referenced by Alaris.Infrastructure.Data.Quality.VolumeOpenInterestValidator.VolumeOpenInterestValidator().
Property Documentation
ComponentId
string Alaris.Infrastructure.Data.Quality.VolumeOpenInterestValidator.ComponentId get
Gets the validator component ID (e.g., "DTqc001A").
Implements Alaris.Infrastructure.Data.Quality.DTqc002A.
Definition at line 259 of file DTqc001A.cs.
Referenced by Alaris.Test.Unit.DTqc003ATests.ComponentId_ShouldBe_DTqc003A(), and Alaris.Infrastructure.Data.Quality.VolumeOpenInterestValidator.Validate().
The documentation for this class was generated from the following file:
src/Alaris.Infrastructure/Data/Quality/DTqc001A.cs