Alaris: Alaris.Core.TermStructure.CRTS002AFlatVol Class Reference
Alaris.Core.TermStructure.CRTS002AFlatVol Class Reference sealed
Flat Black volatility surface with constant volatility. Replaces QuantLib BlackConstantVol.
Public Member Functions
CRTS002AFlatVol (CRTM005A referenceDate, double volatility, IDayCounter? dayCounter=null)
Initialises a flat Black volatility surface.
double BlackVol (double time, double strike)
Gets the Black volatility for a given time and strike.
Parameters
time Time to expiry in years.
strike Strike price.
Returns
Black volatility σ.
double BlackVariance (double time, double strike)
Gets the Black variance for a given time and strike.
Parameters
time Time to expiry in years.
strike Strike price.
Returns
Black variance σ²T.
double BlackVol (CRTM005A date, double strike)
Gets the Black volatility for a given date and strike.
Parameters
date Expiry date.
strike Strike price.
Returns
Black volatility σ.
Properties
CRTM005A ReferenceDate [get]
Gets the reference date (valuation date) for this surface.
IDayCounter DayCounter [get]
Gets the day count convention used by this surface.
double Volatility [get]
Gets the flat volatility of this surface.
Properties inherited from Alaris.Core.TermStructure.IVolatilitySurface
Private Attributes
readonly double _volatility
Detailed Description
Flat Black volatility surface with constant volatility. Replaces QuantLib BlackConstantVol.
For a flat volatility surface:
σ(T, K) = σ for all T and K
Variance = σ² * T
Definition at line 71 of file CRTS002A.cs.
Constructor & Destructor Documentation
CRTS002AFlatVol()
Alaris.Core.TermStructure.CRTS002AFlatVol.CRTS002AFlatVol (CRTM005A referenceDate, double volatility, IDayCounter? dayCounter = null) inline
Initialises a flat Black volatility surface.
Parameters
referenceDate The reference/valuation date.
volatility The flat volatility (annualised).
dayCounter Day count convention for time calculations.
Definition at line 81 of file CRTS002A.cs.
References Alaris.Core.TermStructure.CRTS002AFlatVol._volatility, Alaris.Core.Time.DayCounters.Actual365Fixed, Alaris.Core.TermStructure.CRTS002AFlatVol.DayCounter, and Alaris.Core.TermStructure.CRTS002AFlatVol.ReferenceDate.
Member Function Documentation
BlackVariance()
double Alaris.Core.TermStructure.CRTS002AFlatVol.BlackVariance (double time, double strike) inline
Gets the Black variance for a given time and strike.
Parameters
time Time to expiry in years.
strike Strike price.
Returns
Black variance σ²T.
Implements Alaris.Core.TermStructure.IVolatilitySurface.
Definition at line 108 of file CRTS002A.cs.
References Alaris.Core.TermStructure.CRTS002AFlatVol.BlackVol().
BlackVol() [1/2]
double Alaris.Core.TermStructure.CRTS002AFlatVol.BlackVol (CRTM005A date, double strike) inline
Gets the Black volatility for a given date and strike.
Parameters
date Expiry date.
strike Strike price.
Returns
Black volatility σ.
Implements Alaris.Core.TermStructure.IVolatilitySurface.
Definition at line 115 of file CRTS002A.cs.
References Alaris.Core.TermStructure.CRTS002AFlatVol.BlackVol(), Alaris.Core.TermStructure.CRTS002AFlatVol.DayCounter, Alaris.Core.TermStructure.CRTS002AFlatVol.ReferenceDate, and Alaris.Core.Time.IDayCounter.YearFraction().
BlackVol() [2/2]
double Alaris.Core.TermStructure.CRTS002AFlatVol.BlackVol (double time, double strike) inline
Gets the Black volatility for a given time and strike.
Parameters
time Time to expiry in years.
strike Strike price.
Returns
Black volatility σ.
Implements Alaris.Core.TermStructure.IVolatilitySurface.
Definition at line 100 of file CRTS002A.cs.
References Alaris.Core.TermStructure.CRTS002AFlatVol._volatility.
Referenced by Alaris.Core.TermStructure.CRTS002AFlatVol.BlackVariance(), and Alaris.Core.TermStructure.CRTS002AFlatVol.BlackVol().
Member Data Documentation
_volatility
readonly double Alaris.Core.TermStructure.CRTS002AFlatVol._volatility private
Definition at line 73 of file CRTS002A.cs.
Referenced by Alaris.Core.TermStructure.CRTS002AFlatVol.CRTS002AFlatVol(), and Alaris.Core.TermStructure.CRTS002AFlatVol.BlackVol().
Property Documentation
DayCounter
IDayCounter Alaris.Core.TermStructure.CRTS002AFlatVol.DayCounter get
Gets the day count convention used by this surface.
Implements Alaris.Core.TermStructure.IVolatilitySurface.
Definition at line 97 of file CRTS002A.cs.
Referenced by Alaris.Core.TermStructure.CRTS002AFlatVol.CRTS002AFlatVol(), and Alaris.Core.TermStructure.CRTS002AFlatVol.BlackVol().
ReferenceDate
CRTM005A Alaris.Core.TermStructure.CRTS002AFlatVol.ReferenceDate get
Gets the reference date (valuation date) for this surface.
Implements Alaris.Core.TermStructure.IVolatilitySurface.
Definition at line 94 of file CRTS002A.cs.
Referenced by Alaris.Core.TermStructure.CRTS002AFlatVol.CRTS002AFlatVol(), and Alaris.Core.TermStructure.CRTS002AFlatVol.BlackVol().
Volatility
double Alaris.Core.TermStructure.CRTS002AFlatVol.Volatility get
Gets the flat volatility of this surface.
Definition at line 124 of file CRTS002A.cs.
The documentation for this class was generated from the following file:
src/Alaris.Core/TermStructure/CRTS002A.cs