Alaris: Alaris.Algorithm.Universe.STUN001B Class Reference
Alaris.Algorithm.Universe.STUN001B Class Reference sealed
Polygon-based universe selection model that uses pre-generated universe files. Component ID: STUN001B (Alternative to STUN001A)
Classes
class UniverseEntry
Public Member Functions
STUN001B (DTpr004A earningsProvider, string dataPath, int daysBeforeEarningsMin=5, int daysBeforeEarningsMax=7, decimal minimumDollarVolume=1_500_000m, decimal minimumPrice=5.00m, int maxFinalSymbols=50, ILogger< STUN001B >? logger=null)
Initialises a new instance of the Polygon-based universe selection model.
string GetConfigurationSummary ()
Returns configuration summary for logging.
override IEnumerable< QuantConnect.Data.UniverseSelection.Universe > CreateUniverses (QCAlgorithm algorithm)
Creates universes for the algorithm.
Private Member Functions
IEnumerable< Symbol > SelectSymbols (QCAlgorithm algorithm, DateTime dateTime)
Selects symbols from the Polygon universe files.
void LoadUniverseForDate (QCAlgorithm algorithm, DateTime date)
Loads universe from pre-generated CSV file or ALARIS_SESSION_SYMBOLS.
void LoadEarningsSymbols (QCAlgorithm algorithm, DateTime date)
Loads earnings symbols by querying SEC EDGAR for top universe stocks. For backtesting, we use historical 8-K filings (which IS what happened). SEC EDGAR stores actual filing dates, not future predictions.
Private Attributes
readonly DTpr004A _earningsProvider
readonly? ILogger< STUN001B > _logger
readonly string _dataPath
readonly int _daysBeforeEarningsMin
readonly int _daysBeforeEarningsMax
readonly decimal _minimumDollarVolume
readonly decimal _minimumPrice
readonly int _maxSymbols
DateTime _lastUniverseDate
List< UniverseEntry > _cachedUniverse = new()
HashSet< string > _cachedEarningsSymbols = new(StringComparer.OrdinalIgnoreCase)
Static Private Attributes
static readonly char[] Separators = new[] { ',', ';' }
Loads universe from pre-generated CSV file.
Detailed Description
Polygon-based universe selection model that uses pre-generated universe files. Component ID: STUN001B (Alternative to STUN001A)
This selector reads from universe files generated by 'alaris universe generate':
Location: Alaris.Lean/Data/equity/usa/fundamental/coarse/{yyyyMMdd}.csv
Format: symbolId,ticker,close,volume,dollarVolume
Use this selector when LEAN fundamental data is not available. Run 'alaris universe generate' before backtesting to create the universe files.
Definition at line 33 of file STUN001B.cs.
Constructor & Destructor Documentation
STUN001B()
Alaris.Algorithm.Universe.STUN001B.STUN001B (DTpr004A earningsProvider, string dataPath, int daysBeforeEarningsMin = 5, int daysBeforeEarningsMax = 7, decimal minimumDollarVolume = 1_500_000m, decimal minimumPrice = 5::00m, int maxFinalSymbols = 50, ILogger< STUN001B >? logger = null) inline
Initialises a new instance of the Polygon-based universe selection model.
Definition at line 54 of file STUN001B.cs.
References Alaris.Algorithm.Universe.STUN001B._dataPath, Alaris.Algorithm.Universe.STUN001B._daysBeforeEarningsMax, Alaris.Algorithm.Universe.STUN001B._daysBeforeEarningsMin, Alaris.Algorithm.Universe.STUN001B._earningsProvider, Alaris.Algorithm.Universe.STUN001B._logger, Alaris.Algorithm.Universe.STUN001B._maxSymbols, Alaris.Algorithm.Universe.STUN001B._minimumDollarVolume, and Alaris.Algorithm.Universe.STUN001B._minimumPrice.
Member Function Documentation
CreateUniverses()
override IEnumerable< QuantConnect.Data.UniverseSelection.Universe > Alaris.Algorithm.Universe.STUN001B.CreateUniverses (QCAlgorithm algorithm) inline
Creates universes for the algorithm.
Definition at line 93 of file STUN001B.cs.
References Alaris.Algorithm.Universe.STUN001B.SelectSymbols().
GetConfigurationSummary()
string Alaris.Algorithm.Universe.STUN001B.GetConfigurationSummary () inline
Returns configuration summary for logging.
Definition at line 83 of file STUN001B.cs.
LoadEarningsSymbols()
void Alaris.Algorithm.Universe.STUN001B.LoadEarningsSymbols (QCAlgorithm algorithm, DateTime date) inline private
Loads earnings symbols by querying SEC EDGAR for top universe stocks. For backtesting, we use historical 8-K filings (which IS what happened). SEC EDGAR stores actual filing dates, not future predictions.
Definition at line 244 of file STUN001B.cs.
References Alaris.Algorithm.Universe.STUN001B._cachedEarningsSymbols, Alaris.Algorithm.Universe.STUN001B._cachedUniverse, Alaris.Algorithm.Universe.STUN001B._daysBeforeEarningsMax, Alaris.Algorithm.Universe.STUN001B._daysBeforeEarningsMin, Alaris.Algorithm.Universe.STUN001B._earningsProvider, and Alaris.Infrastructure.Data.Provider.DTpr004A.GetSymbolsWithEarningsAsync().
Referenced by Alaris.Algorithm.Universe.STUN001B.SelectSymbols().
LoadUniverseForDate()
void Alaris.Algorithm.Universe.STUN001B.LoadUniverseForDate (QCAlgorithm algorithm, DateTime date) inline private
Loads universe from pre-generated CSV file or ALARIS_SESSION_SYMBOLS.
Definition at line 147 of file STUN001B.cs.
References Alaris.Algorithm.Universe.STUN001B._cachedUniverse, Alaris.Algorithm.Universe.STUN001B._dataPath, Alaris.Algorithm.Universe.STUN001B._minimumDollarVolume, Alaris.Algorithm.Universe.STUN001B._minimumPrice, and Alaris.Algorithm.Universe.STUN001B.Separators.
Referenced by Alaris.Algorithm.Universe.STUN001B.SelectSymbols().
SelectSymbols()
IEnumerable< Symbol > Alaris.Algorithm.Universe.STUN001B.SelectSymbols (QCAlgorithm algorithm, DateTime dateTime) inline private
Selects symbols from the Polygon universe files.
Definition at line 104 of file STUN001B.cs.
References Alaris.Algorithm.Universe.STUN001B._cachedEarningsSymbols, Alaris.Algorithm.Universe.STUN001B._cachedUniverse, Alaris.Algorithm.Universe.STUN001B._lastUniverseDate, Alaris.Algorithm.Universe.STUN001B._logger, Alaris.Algorithm.Universe.STUN001B._maxSymbols, Alaris.Algorithm.Universe.STUN001B.LoadEarningsSymbols(), and Alaris.Algorithm.Universe.STUN001B.LoadUniverseForDate().
Referenced by Alaris.Algorithm.Universe.STUN001B.CreateUniverses().
Member Data Documentation
_cachedEarningsSymbols
HashSet<string> Alaris.Algorithm.Universe.STUN001B._cachedEarningsSymbols = new(StringComparer.OrdinalIgnoreCase) private
Definition at line 49 of file STUN001B.cs.
Referenced by Alaris.Algorithm.Universe.STUN001B.LoadEarningsSymbols(), and Alaris.Algorithm.Universe.STUN001B.SelectSymbols().
_cachedUniverse
List<UniverseEntry> Alaris.Algorithm.Universe.STUN001B._cachedUniverse = new() private
Definition at line 48 of file STUN001B.cs.
Referenced by Alaris.Algorithm.Universe.STUN001B.LoadEarningsSymbols(), Alaris.Algorithm.Universe.STUN001B.LoadUniverseForDate(), and Alaris.Algorithm.Universe.STUN001B.SelectSymbols().
_dataPath
readonly string Alaris.Algorithm.Universe.STUN001B._dataPath private
Definition at line 37 of file STUN001B.cs.
Referenced by Alaris.Algorithm.Universe.STUN001B.STUN001B(), and Alaris.Algorithm.Universe.STUN001B.LoadUniverseForDate().
_daysBeforeEarningsMax
readonly int Alaris.Algorithm.Universe.STUN001B._daysBeforeEarningsMax private
Definition at line 41 of file STUN001B.cs.
Referenced by Alaris.Algorithm.Universe.STUN001B.STUN001B(), and Alaris.Algorithm.Universe.STUN001B.LoadEarningsSymbols().
_daysBeforeEarningsMin
readonly int Alaris.Algorithm.Universe.STUN001B._daysBeforeEarningsMin private
Definition at line 40 of file STUN001B.cs.
Referenced by Alaris.Algorithm.Universe.STUN001B.STUN001B(), and Alaris.Algorithm.Universe.STUN001B.LoadEarningsSymbols().
_earningsProvider
readonly DTpr004A Alaris.Algorithm.Universe.STUN001B._earningsProvider private
Definition at line 35 of file STUN001B.cs.
Referenced by Alaris.Algorithm.Universe.STUN001B.STUN001B(), and Alaris.Algorithm.Universe.STUN001B.LoadEarningsSymbols().
_lastUniverseDate
DateTime Alaris.Algorithm.Universe.STUN001B._lastUniverseDate private
Definition at line 47 of file STUN001B.cs.
Referenced by Alaris.Algorithm.Universe.STUN001B.SelectSymbols().
_logger
readonly? ILogger<STUN001B> Alaris.Algorithm.Universe.STUN001B._logger private
Definition at line 36 of file STUN001B.cs.
Referenced by Alaris.Algorithm.Universe.STUN001B.STUN001B(), and Alaris.Algorithm.Universe.STUN001B.SelectSymbols().
_maxSymbols
readonly int Alaris.Algorithm.Universe.STUN001B._maxSymbols private
Definition at line 44 of file STUN001B.cs.
Referenced by Alaris.Algorithm.Universe.STUN001B.STUN001B(), and Alaris.Algorithm.Universe.STUN001B.SelectSymbols().
_minimumDollarVolume
readonly decimal Alaris.Algorithm.Universe.STUN001B._minimumDollarVolume private
Definition at line 42 of file STUN001B.cs.
Referenced by Alaris.Algorithm.Universe.STUN001B.STUN001B(), and Alaris.Algorithm.Universe.STUN001B.LoadUniverseForDate().
_minimumPrice
readonly decimal Alaris.Algorithm.Universe.STUN001B._minimumPrice private
Definition at line 43 of file STUN001B.cs.
Referenced by Alaris.Algorithm.Universe.STUN001B.STUN001B(), and Alaris.Algorithm.Universe.STUN001B.LoadUniverseForDate().
Separators
readonly char [] Alaris.Algorithm.Universe.STUN001B.Separators = new[] { ',', ';' } static private
Loads universe from pre-generated CSV file.
Definition at line 142 of file STUN001B.cs.
Referenced by Alaris.Algorithm.Universe.STUN001B.LoadUniverseForDate().
The documentation for this class was generated from the following file:
src/Alaris.Algorithm/STUN001B.cs