Alaris: Alaris.Host.Application.Service.APsv003A Class Reference
Alaris.Host.Application.Service.APsv003A Class Reference sealed
Verifies all required data exists before backtest execution. Implements fail-fast philosophy with actionable diagnostics. Component ID: APsv003A.
Public Member Functions
APsv003A (ILogger< APsv003A >? logger=null)
DataVerificationReport Verify (STDT010A requirements, string sessionDataPath)
Verifies all data requirements are met for a session.
Private Member Functions
void VerifyPriceData (STDT010A requirements, string sessionDataPath, DataVerificationReport report)
void VerifyMapAndFactorFiles (STDT010A requirements, string sessionDataPath, DataVerificationReport report)
void VerifyEarningsCalendar (STDT010A requirements, string sessionDataPath, DataVerificationReport report)
void VerifyOptionsData (STDT010A requirements, string sessionDataPath, DataVerificationReport report)
void VerifyBenchmarkData (STDT010A requirements, string sessionDataPath, DataVerificationReport report)
Private Attributes
readonly? ILogger< APsv003A > _logger
Detailed Description
Verifies all required data exists before backtest execution. Implements fail-fast philosophy with actionable diagnostics. Component ID: APsv003A.
Definition at line 18 of file APsv003A.cs.
Constructor & Destructor Documentation
APsv003A()
Alaris.Host.Application.Service.APsv003A.APsv003A (ILogger< APsv003A >? logger = null) inline
Definition at line 22 of file APsv003A.cs.
References Alaris.Host.Application.Service.APsv003A._logger.
Member Function Documentation
Verify()
DataVerificationReport Alaris.Host.Application.Service.APsv003A.Verify (STDT010A requirements, string sessionDataPath) inline
Verifies all data requirements are met for a session.
Parameters
requirements Session data requirements.
sessionDataPath Path to session data directory.
Returns
Detailed verification report.
Definition at line 33 of file APsv003A.cs.
References Alaris.Host.Application.Service.APsv003A._logger, Alaris.Host.Application.Service.APsv003A.VerifyBenchmarkData(), Alaris.Host.Application.Service.APsv003A.VerifyEarningsCalendar(), Alaris.Host.Application.Service.APsv003A.VerifyMapAndFactorFiles(), Alaris.Host.Application.Service.APsv003A.VerifyOptionsData(), and Alaris.Host.Application.Service.APsv003A.VerifyPriceData().
VerifyBenchmarkData()
void Alaris.Host.Application.Service.APsv003A.VerifyBenchmarkData (STDT010A requirements, string sessionDataPath, DataVerificationReport report) inline private
Definition at line 174 of file APsv003A.cs.
References Alaris.Host.Application.Service.APsv003A._logger, and Alaris.Host.Application.Service.DataVerificationReport.BenchmarkAvailable.
Referenced by Alaris.Host.Application.Service.APsv003A.Verify().
VerifyEarningsCalendar()
void Alaris.Host.Application.Service.APsv003A.VerifyEarningsCalendar (STDT010A requirements, string sessionDataPath, DataVerificationReport report) inline private
Definition at line 121 of file APsv003A.cs.
References Alaris.Host.Application.Service.APsv003A._logger, and Alaris.Host.Application.Service.DataVerificationReport.MissingEarningsDates.
Referenced by Alaris.Host.Application.Service.APsv003A.Verify().
VerifyMapAndFactorFiles()
void Alaris.Host.Application.Service.APsv003A.VerifyMapAndFactorFiles (STDT010A requirements, string sessionDataPath, DataVerificationReport report) inline private
Definition at line 96 of file APsv003A.cs.
References Alaris.Host.Application.Service.APsv003A._logger.
Referenced by Alaris.Host.Application.Service.APsv003A.Verify().
VerifyOptionsData()
void Alaris.Host.Application.Service.APsv003A.VerifyOptionsData (STDT010A requirements, string sessionDataPath, DataVerificationReport report) inline private
Definition at line 148 of file APsv003A.cs.
References Alaris.Host.Application.Service.APsv003A._logger.
Referenced by Alaris.Host.Application.Service.APsv003A.Verify().
VerifyPriceData()
void Alaris.Host.Application.Service.APsv003A.VerifyPriceData (STDT010A requirements, string sessionDataPath, DataVerificationReport report) inline private
Definition at line 81 of file APsv003A.cs.
References Alaris.Host.Application.Service.APsv003A._logger.
Referenced by Alaris.Host.Application.Service.APsv003A.Verify().
Member Data Documentation
_logger
readonly? ILogger<APsv003A> Alaris.Host.Application.Service.APsv003A._logger private
Definition at line 20 of file APsv003A.cs.
Referenced by Alaris.Host.Application.Service.APsv003A.APsv003A(), Alaris.Host.Application.Service.APsv003A.Verify(), Alaris.Host.Application.Service.APsv003A.VerifyBenchmarkData(), Alaris.Host.Application.Service.APsv003A.VerifyEarningsCalendar(), Alaris.Host.Application.Service.APsv003A.VerifyMapAndFactorFiles(), Alaris.Host.Application.Service.APsv003A.VerifyOptionsData(), and Alaris.Host.Application.Service.APsv003A.VerifyPriceData().
The documentation for this class was generated from the following file:
src/Alaris.Host/Application/Service/APsv003A.cs