Alaris: Alaris.Core.Pricing.CREX001A Class Reference
Alaris.Core.Pricing.CREX001A Class Reference sealed
Handles numerical stability as τ → 0 via blending to intrinsic. Threshold: τ < 1/252.
Public Member Functions
CREX001A (double minTimeToExpiry=DefaultMinTimeToExpiry, double blendingZoneWidth=DefaultBlendingZoneWidth)
Initialises a new instance of the near-expiry handler.
bool IsNearExpiry (double timeToExpiry)
Determines if the option is in the near-expiry regime.
bool IsIntrinsicOnly (double timeToExpiry)
Determines if the option is fully in intrinsic-value regime.
double CalculateBlendingWeight (double timeToExpiry)
Calculates the blending weight for smooth transition.
double BlendWithIntrinsic (double modelValue, double spot, double strike, bool isCall, double timeToExpiry)
Blends model value with intrinsic value for smooth near-expiry transition.
NearExpiryGreeks CalculateNearExpiryGreeks (double spot, double strike, bool isCall, double timeToExpiry)
Returns near-expiry Greeks with appropriate limiting behaviour.
NearExpiryValidation Validate (double timeToExpiry)
Validates that a time-to-expiry value is suitable for model pricing.
Static Public Member Functions
static double CalculateCallIntrinsic (double spot, double strike)
Calculates call option intrinsic value.
static double CalculatePutIntrinsic (double spot, double strike)
Calculates put option intrinsic value.
static double CalculateIntrinsic (double spot, double strike, bool isCall)
Calculates intrinsic value for either call or put.
Static Public Attributes
const double DefaultMinTimeToExpiry = 1.0 / 252.0
Minimum time-to-expiry threshold (in years) before near-expiry regime. Default: 1/252 ≈ 0.00397 (1 trading day).
const double DefaultBlendingZoneWidth = 2.0 / 252.0
Blending zone width (in years) for smooth transition. Default: 2/252 ≈ 0.00794 (2 trading days).
Private Attributes
readonly double _minTimeToExpiry
readonly double _blendingZoneWidth
Detailed Description
Handles numerical stability as τ → 0 via blending to intrinsic. Threshold: τ < 1/252.
Definition at line 12 of file CREX001A.cs.
Constructor & Destructor Documentation
CREX001A()
Alaris.Core.Pricing.CREX001A.CREX001A (double minTimeToExpiry = DefaultMinTimeToExpiry, double blendingZoneWidth = DefaultBlendingZoneWidth) inline
Initialises a new instance of the near-expiry handler.
Parameters
minTimeToExpiry Minimum time-to-expiry threshold (years).
blendingZoneWidth Width of blending zone (years).
Exceptions
ArgumentOutOfRangeException Thrown when thresholds are non-positive.
Definition at line 37 of file CREX001A.cs.
References Alaris.Core.Pricing.CREX001A._blendingZoneWidth, and Alaris.Core.Pricing.CREX001A._minTimeToExpiry.
Member Function Documentation
BlendWithIntrinsic()
double Alaris.Core.Pricing.CREX001A.BlendWithIntrinsic (double modelValue, double spot, double strike, bool isCall, double timeToExpiry) inline
Blends model value with intrinsic value for smooth near-expiry transition.
Parameters
modelValue Value from pricing model (Black-Scholes/spectral).
spot Current spot price.
strike Strike price.
isCall True for call, false for put.
timeToExpiry Time to expiration in years.
Returns
Blended option value.
Definition at line 157 of file CREX001A.cs.
References Alaris.Core.Pricing.CREX001A.CalculateBlendingWeight(), and Alaris.Core.Pricing.CREX001A.CalculateIntrinsic().
Referenced by Alaris.Core.Pricing.CREN003A.Price().
CalculateBlendingWeight()
double Alaris.Core.Pricing.CREX001A.CalculateBlendingWeight (double timeToExpiry) inline
Calculates the blending weight for smooth transition.
The weight function provides C⁰ continuity:
w(τ) = clamp((τ - ε_min) / zone_width, 0, 1)
At τ = ε_min: w = 0 (pure intrinsic) At τ = ε_min + zone: w = 1 (pure model)
Parameters
timeToExpiry Time to expiration in years.
Returns
Blending weight in [0, 1].
Definition at line 132 of file CREX001A.cs.
References Alaris.Core.Pricing.CREX001A._blendingZoneWidth, and Alaris.Core.Pricing.CREX001A._minTimeToExpiry.
Referenced by Alaris.Core.Pricing.CREX001A.BlendWithIntrinsic(), and Alaris.Core.Pricing.CREX001A.Validate().
CalculateCallIntrinsic()
static double Alaris.Core.Pricing.CREX001A.CalculateCallIntrinsic (double spot, double strike) inline static
Calculates call option intrinsic value.
Parameters
spot Current spot price.
strike Strike price.
Returns
Intrinsic value: max(S - K, 0).
Definition at line 83 of file CREX001A.cs.
Referenced by Alaris.Core.Pricing.CREX001A.CalculateIntrinsic().
CalculateIntrinsic()
static double Alaris.Core.Pricing.CREX001A.CalculateIntrinsic (double spot, double strike, bool isCall) inline static
Calculates intrinsic value for either call or put.
Parameters
spot Current spot price.
strike Strike price.
isCall True for call, false for put.
Returns
Intrinsic value.
Definition at line 112 of file CREX001A.cs.
References Alaris.Core.Pricing.CREX001A.CalculateCallIntrinsic(), and Alaris.Core.Pricing.CREX001A.CalculatePutIntrinsic().
Referenced by Alaris.Core.Pricing.CREX001A.BlendWithIntrinsic(), Alaris.Core.Pricing.CREX001A.CalculateNearExpiryGreeks(), and Alaris.Core.Pricing.CREN003A.Price().
CalculateNearExpiryGreeks()
NearExpiryGreeks Alaris.Core.Pricing.CREX001A.CalculateNearExpiryGreeks (double spot, double strike, bool isCall, double timeToExpiry) inline
Returns near-expiry Greeks with appropriate limiting behaviour.
Parameters
spot Current spot price.
strike Strike price.
isCall True for call, false for put.
timeToExpiry Time to expiration in years.
Returns
Near-expiry Greeks result.
Definition at line 192 of file CREX001A.cs.
References Alaris.Core.Pricing.CREX001A.CalculateIntrinsic(), Alaris.Core.Pricing.CREX001A.IsNearExpiry(), and Alaris.Core.Pricing.NearExpiryGreeks.
Referenced by Alaris.Core.Pricing.CREN003A.Delta(), Alaris.Core.Pricing.CREN003A.Gamma(), Alaris.Core.Pricing.CREN003A.Theta(), and Alaris.Core.Pricing.CREN003A.Vega().
CalculatePutIntrinsic()
static double Alaris.Core.Pricing.CREX001A.CalculatePutIntrinsic (double spot, double strike) inline static
Calculates put option intrinsic value.
Parameters
spot Current spot price.
strike Strike price.
Returns
Intrinsic value: max(K - S, 0).
Definition at line 97 of file CREX001A.cs.
Referenced by Alaris.Core.Pricing.CREX001A.CalculateIntrinsic().
IsIntrinsicOnly()
bool Alaris.Core.Pricing.CREX001A.IsIntrinsicOnly (double timeToExpiry) inline
Determines if the option is fully in intrinsic-value regime.
Parameters
timeToExpiry Time to expiration in years.
Returns
True if only intrinsic value should be used.
Definition at line 72 of file CREX001A.cs.
References Alaris.Core.Pricing.CREX001A._minTimeToExpiry.
Referenced by Alaris.Core.Pricing.CREN003A.Price().
IsNearExpiry()
bool Alaris.Core.Pricing.CREX001A.IsNearExpiry (double timeToExpiry) inline
Determines if the option is in the near-expiry regime.
Parameters
timeToExpiry Time to expiration in years.
Returns
True if near-expiry handling should be applied.
Definition at line 62 of file CREX001A.cs.
References Alaris.Core.Pricing.CREX001A._blendingZoneWidth, and Alaris.Core.Pricing.CREX001A._minTimeToExpiry.
Referenced by Alaris.Core.Pricing.CREX001A.CalculateNearExpiryGreeks(), Alaris.Core.Pricing.CREN003A.Delta(), Alaris.Core.Pricing.CREN003A.Gamma(), Alaris.Core.Pricing.CREN003A.Price(), Alaris.Core.Pricing.CREN003A.Theta(), and Alaris.Core.Pricing.CREN003A.Vega().
Validate()
NearExpiryValidation Alaris.Core.Pricing.CREX001A.Validate (double timeToExpiry) inline
Validates that a time-to-expiry value is suitable for model pricing.
Parameters
timeToExpiry Time to expiration in years.
Returns
Validation result with recommendation.
Definition at line 252 of file CREX001A.cs.
References Alaris.Core.Pricing.CREX001A._blendingZoneWidth, Alaris.Core.Pricing.CREX001A._minTimeToExpiry, Alaris.Core.Pricing.CREX001A.CalculateBlendingWeight(), and Alaris.Core.Pricing.NearExpiryValidation.
Referenced by Alaris.Core.Pricing.CRSL001A.Solve().
Member Data Documentation
_blendingZoneWidth
readonly double Alaris.Core.Pricing.CREX001A._blendingZoneWidth private
Definition at line 27 of file CREX001A.cs.
Referenced by Alaris.Core.Pricing.CREX001A.CREX001A(), Alaris.Core.Pricing.CREX001A.CalculateBlendingWeight(), Alaris.Core.Pricing.CREX001A.IsNearExpiry(), and Alaris.Core.Pricing.CREX001A.Validate().
_minTimeToExpiry
readonly double Alaris.Core.Pricing.CREX001A._minTimeToExpiry private
Definition at line 26 of file CREX001A.cs.
Referenced by Alaris.Core.Pricing.CREX001A.CREX001A(), Alaris.Core.Pricing.CREX001A.CalculateBlendingWeight(), Alaris.Core.Pricing.CREX001A.IsIntrinsicOnly(), Alaris.Core.Pricing.CREX001A.IsNearExpiry(), and Alaris.Core.Pricing.CREX001A.Validate().
DefaultBlendingZoneWidth
const double Alaris.Core.Pricing.CREX001A.DefaultBlendingZoneWidth = 2.0 / 252.0 static
Blending zone width (in years) for smooth transition. Default: 2/252 ≈ 0.00794 (2 trading days).
Definition at line 24 of file CREX001A.cs.
DefaultMinTimeToExpiry
const double Alaris.Core.Pricing.CREX001A.DefaultMinTimeToExpiry = 1.0 / 252.0 static
Minimum time-to-expiry threshold (in years) before near-expiry regime. Default: 1/252 ≈ 0.00397 (1 trading day).
Definition at line 18 of file CREX001A.cs.
The documentation for this class was generated from the following file:
src/Alaris.Core/Pricing/CREX001A.cs