Alaris: Alaris.Infrastructure.Data.Serialization.DTsr001A Class Reference
Alaris.Infrastructure.Data.Serialization.DTsr001A Class Reference
Bridges Alaris.Data.Model types to binary serialization format. Component ID: DTsr001A.
Static Public Member Functions
static int EncodePriceBar (PriceBar bar, Span< byte > buffer)
Encodes a PriceBar to binary format.
static PriceBar DecodePriceBar (ReadOnlySpan< byte > buffer, string symbol)
Decodes a PriceBar from binary format.
static int EncodePriceBars (IReadOnlyList< PriceBar > bars, Span< byte > buffer)
Encodes a list of PriceBars to binary format.
static ReadOnlyCollection< PriceBar > DecodePriceBars (ReadOnlySpan< byte > buffer)
Decodes a list of PriceBars from binary format.
static int EncodeOptionContract (OptionContract contract, Span< byte > buffer)
Encodes an OptionContract to binary format.
static OptionContract DecodeOptionContract (ReadOnlySpan< byte > buffer)
Decodes an OptionContract from binary format.
static int EncodeOptionChainSnapshot (OptionChainSnapshot snapshot, Span< byte > buffer)
Encodes an OptionChainSnapshot to binary format.
static OptionChainSnapshot DecodeOptionChainSnapshot (ReadOnlySpan< byte > buffer)
Decodes an OptionChainSnapshot from binary format.
Static Public Attributes
const int OptionContractEncodedSize = 152
Gets the fixed size of an encoded OptionContract. Layout: Strike(8) + Expiration(4) + Right+Pad(4) + 10*Greeks/Prices(80) + Timestamp(8) + Underlying(16) + Option(32) = 152 bytes.
Static Private Member Functions
static void WriteFixedString (Span< byte > buffer, string? value, int length)
static string ReadFixedString (ReadOnlySpan< byte > buffer, int length)
Static Private Attributes
const byte FormatVersion = 1
Detailed Description
Bridges Alaris.Data.Model types to binary serialization format. Component ID: DTsr001A.
This adapter converts between the domain model types (OptionContract, PriceBar, etc.) and the binary-optimized Protocol types for zero-allocation serialization.
Usage for cache operations:
using var buffer = PLBF001A.RentBuffer();
int length = DTsr001A.EncodePriceBar(bar, buffer.Span);
await stream.WriteAsync(buffer.Memory[..length]);
Definition at line 26 of file DTsr001A.cs.
Member Function Documentation
DecodeOptionChainSnapshot()
static OptionChainSnapshot Alaris.Infrastructure.Data.Serialization.DTsr001A.DecodeOptionChainSnapshot (ReadOnlySpan< byte > buffer) inline static
Decodes an OptionChainSnapshot from binary format.
Definition at line 306 of file DTsr001A.cs.
References Alaris.Infrastructure.Data.Serialization.DTsr001A.DecodeOptionContract(), Alaris.Infrastructure.Data.Serialization.DTsr001A.FormatVersion, Alaris.Infrastructure.Protocol.Serialization.PLSR001A.FromMantissa(), Alaris.Infrastructure.Data.Serialization.DTsr001A.OptionContractEncodedSize, and Alaris.Infrastructure.Data.Serialization.DTsr001A.ReadFixedString().
Referenced by Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.LoadBinaryCacheAsync(), and Alaris.Test.Unit.TSUN030A.OptionChainSnapshot_RoundTrip_PreservesAllContracts().
DecodeOptionContract()
static OptionContract Alaris.Infrastructure.Data.Serialization.DTsr001A.DecodeOptionContract (ReadOnlySpan< byte > buffer) inline static
Decodes an OptionContract from binary format.
Definition at line 198 of file DTsr001A.cs.
References Alaris.Infrastructure.Protocol.Serialization.PLSR001A.FromMantissa(), and Alaris.Infrastructure.Data.Serialization.DTsr001A.ReadFixedString().
Referenced by Alaris.Infrastructure.Data.Serialization.DTsr001A.DecodeOptionChainSnapshot(), Alaris.Test.Unit.TSUN030A.OptionContract_RoundTrip_PreservesAllFields(), and Alaris.Test.Unit.TSUN030A.OptionContract_WithNullGreeks_PreservesNulls().
DecodePriceBar()
static PriceBar Alaris.Infrastructure.Data.Serialization.DTsr001A.DecodePriceBar (ReadOnlySpan< byte > buffer, string symbol) inline static
Decodes a PriceBar from binary format.
Parameters
buffer Source buffer with encoded data.
symbol Symbol for the decoded bar.
Returns
Decoded domain model.
Definition at line 59 of file DTsr001A.cs.
References Alaris.Infrastructure.Protocol.Serialization.PLSR001A.DecodePriceBar().
Referenced by Alaris.Infrastructure.Data.Serialization.DTsr001A.DecodePriceBars(), and Alaris.Test.Unit.TSUN030A.PriceBar_RoundTrip_PreservesAllFields().
DecodePriceBars()
static ReadOnlyCollection< PriceBar > Alaris.Infrastructure.Data.Serialization.DTsr001A.DecodePriceBars (ReadOnlySpan< byte > buffer) inline static
Decodes a list of PriceBars from binary format.
Definition at line 110 of file DTsr001A.cs.
References Alaris.Infrastructure.Data.Serialization.DTsr001A.DecodePriceBar(), Alaris.Infrastructure.Data.Serialization.DTsr001A.FormatVersion, and Alaris.Infrastructure.Data.Serialization.DTsr001A.ReadFixedString().
EncodeOptionChainSnapshot()
static int Alaris.Infrastructure.Data.Serialization.DTsr001A.EncodeOptionChainSnapshot (OptionChainSnapshot snapshot, Span< byte > buffer) inline static
Encodes an OptionChainSnapshot to binary format.
Parameters
snapshot Source snapshot.
buffer Target buffer (use PLBF001A.LargeBufferSize for chains).
Returns
Number of bytes written.
Definition at line 264 of file DTsr001A.cs.
References Alaris.Infrastructure.Data.Model.OptionChainSnapshot.Contracts, Alaris.Infrastructure.Data.Serialization.DTsr001A.EncodeOptionContract(), Alaris.Infrastructure.Data.Serialization.DTsr001A.FormatVersion, Alaris.Infrastructure.Data.Model.OptionChainSnapshot.SpotPrice, Alaris.Infrastructure.Data.Model.OptionChainSnapshot.Symbol, Alaris.Infrastructure.Data.Model.OptionChainSnapshot.Timestamp, Alaris.Infrastructure.Protocol.Serialization.PLSR001A.ToMantissa(), and Alaris.Infrastructure.Data.Serialization.DTsr001A.WriteFixedString().
Referenced by Alaris.Test.Unit.TSUN030A.OptionChainSnapshot_RoundTrip_PreservesAllContracts(), and Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.SaveOptionChainCacheAsync().
EncodeOptionContract()
static int Alaris.Infrastructure.Data.Serialization.DTsr001A.EncodeOptionContract (OptionContract contract, Span< byte > buffer) inline static
Encodes an OptionContract to binary format.
Definition at line 143 of file DTsr001A.cs.
References Alaris.Infrastructure.Data.Model.OptionContract.Ask, Alaris.Infrastructure.Data.Model.OptionContract.Bid, Alaris.Infrastructure.Data.Model.OptionContract.Delta, Alaris.Infrastructure.Data.Model.OptionContract.Expiration, Alaris.Infrastructure.Data.Model.OptionContract.Gamma, Alaris.Infrastructure.Data.Model.OptionContract.ImpliedVolatility, Alaris.Infrastructure.Data.Model.OptionContract.Last, Alaris.Infrastructure.Data.Model.OptionContract.OpenInterest, Alaris.Infrastructure.Data.Model.OptionContract.OptionSymbol, Alaris.Infrastructure.Data.Model.OptionContract.Strike, Alaris.Infrastructure.Data.Model.OptionContract.Theta, Alaris.Infrastructure.Data.Model.OptionContract.Timestamp, Alaris.Infrastructure.Protocol.Serialization.PLSR001A.ToMantissa(), Alaris.Infrastructure.Data.Model.OptionContract.UnderlyingSymbol, Alaris.Infrastructure.Data.Model.OptionContract.Vega, Alaris.Infrastructure.Data.Model.OptionContract.Volume, and Alaris.Infrastructure.Data.Serialization.DTsr001A.WriteFixedString().
Referenced by Alaris.Infrastructure.Data.Serialization.DTsr001A.EncodeOptionChainSnapshot(), Alaris.Test.Unit.TSUN030A.OptionContract_RoundTrip_PreservesAllFields(), and Alaris.Test.Unit.TSUN030A.OptionContract_WithNullGreeks_PreservesNulls().
EncodePriceBar()
static int Alaris.Infrastructure.Data.Serialization.DTsr001A.EncodePriceBar (PriceBar bar, Span< byte > buffer) inline static
Encodes a PriceBar to binary format.
Parameters
bar Source domain model.
buffer Target buffer (minimum 80 bytes).
Returns
Number of bytes written.
Definition at line 38 of file DTsr001A.cs.
References Alaris.Infrastructure.Data.Model.PriceBar.Close, Alaris.Infrastructure.Protocol.Serialization.PLSR001A.EncodePriceBar(), Alaris.Infrastructure.Data.Model.PriceBar.High, Alaris.Infrastructure.Data.Model.PriceBar.Low, Alaris.Infrastructure.Data.Model.PriceBar.Open, Alaris.Infrastructure.Data.Model.PriceBar.Timestamp, and Alaris.Infrastructure.Protocol.Serialization.PLSR001A.ToMantissa().
Referenced by Alaris.Infrastructure.Data.Serialization.DTsr001A.EncodePriceBars(), and Alaris.Test.Unit.TSUN030A.PriceBar_RoundTrip_PreservesAllFields().
EncodePriceBars()
static int Alaris.Infrastructure.Data.Serialization.DTsr001A.EncodePriceBars (IReadOnlyList< PriceBar > bars, Span< byte > buffer) inline static
Encodes a list of PriceBars to binary format.
Parameters
bars Source bars.
buffer Target buffer (64 bytes per bar + header).
Returns
Number of bytes written.
Definition at line 81 of file DTsr001A.cs.
References Alaris.Infrastructure.Data.Serialization.DTsr001A.EncodePriceBar(), Alaris.Infrastructure.Data.Serialization.DTsr001A.FormatVersion, and Alaris.Infrastructure.Data.Serialization.DTsr001A.WriteFixedString().
ReadFixedString()
static string Alaris.Infrastructure.Data.Serialization.DTsr001A.ReadFixedString (ReadOnlySpan< byte > buffer, int length) inline static private
Definition at line 362 of file DTsr001A.cs.
Referenced by Alaris.Infrastructure.Data.Serialization.DTsr001A.DecodeOptionChainSnapshot(), Alaris.Infrastructure.Data.Serialization.DTsr001A.DecodeOptionContract(), and Alaris.Infrastructure.Data.Serialization.DTsr001A.DecodePriceBars().
WriteFixedString()
static void Alaris.Infrastructure.Data.Serialization.DTsr001A.WriteFixedString (Span< byte > buffer, string? value, int length) inline static private
Definition at line 352 of file DTsr001A.cs.
Referenced by Alaris.Infrastructure.Data.Serialization.DTsr001A.EncodeOptionChainSnapshot(), Alaris.Infrastructure.Data.Serialization.DTsr001A.EncodeOptionContract(), and Alaris.Infrastructure.Data.Serialization.DTsr001A.EncodePriceBars().
Member Data Documentation
FormatVersion
const byte Alaris.Infrastructure.Data.Serialization.DTsr001A.FormatVersion = 1 static private
Definition at line 29 of file DTsr001A.cs.
Referenced by Alaris.Infrastructure.Data.Serialization.DTsr001A.DecodeOptionChainSnapshot(), Alaris.Infrastructure.Data.Serialization.DTsr001A.DecodePriceBars(), Alaris.Infrastructure.Data.Serialization.DTsr001A.EncodeOptionChainSnapshot(), and Alaris.Infrastructure.Data.Serialization.DTsr001A.EncodePriceBars().
OptionContractEncodedSize
const int Alaris.Infrastructure.Data.Serialization.DTsr001A.OptionContractEncodedSize = 152 static
Gets the fixed size of an encoded OptionContract. Layout: Strike(8) + Expiration(4) + Right+Pad(4) + 10*Greeks/Prices(80) + Timestamp(8) + Underlying(16) + Option(32) = 152 bytes.
Definition at line 193 of file DTsr001A.cs.
Referenced by Alaris.Infrastructure.Data.Serialization.DTsr001A.DecodeOptionChainSnapshot().
The documentation for this class was generated from the following file:
src/Alaris.Infrastructure/Data/Serialization/DTsr001A.cs