Alaris: Alaris.Strategy.Core.STCR001A Class Reference
Alaris.Strategy.Core.STCR001A Class Reference sealed
Generates trading signals for earnings calendar spread opportunities. Implements the strategy from Atilgan (2014) and incorporates term structure analysis. Enhanced with Leung & Santoli (2014) model for theoretical IV and mispricing signals.
Public Member Functions
STCR001A (STDT001A marketData, STCR003A yangZhang, STTM001A termAnalyzer, STIV005A? earningsCalibrator=null, ILogger< STCR001A >? logger=null)
Initializes a new instance of the STCR001A class.
STCR004A Generate (string symbol, DateTime earningsDate, DateTime evaluationDate)
Generates a trading signal for a given symbol before an earnings announcement.
STCR004A Generate (string symbol, DateTime earningsDate, DateTime evaluationDate, IReadOnlyList< DateTime >? historicalEarningsDates)
Generates a trading signal with Leung & Santoli (2014) model calibration.
Private Member Functions
List< PriceBar > STDT002A optionChain FetchMarketData (string symbol, DateTime evaluationDate)
void CalculateSTCR004AMetrics (STCR004A signal, List< PriceBar > priceHistory, STDT002A optionChain, DateTime earningsDate, DateTime evaluationDate, IReadOnlyList< DateTime >? historicalEarningsDates)
Calculates all signal metrics including volatility, term structure, and criteria. Enhanced with Leung & Santoli (2014) model calculations.
void CalculateLeungSantoliMetrics (STCR004A signal, List< PriceBar > priceHistory, STDT002A optionChain, DateTime earningsDate, DateTime evaluationDate, IReadOnlyList< DateTime >? historicalEarningsDates)
Calculates Leung & Santoli (2014) model metrics including:
bool TryCalibrateFromHistory (STCR004A signal, List< PriceBar > priceHistory, IReadOnlyList< DateTime >? historicalEarningsDates)
bool TryCalibrateFromTermStructure (STCR004A signal, STDT002A optionChain, DateTime evaluationDate)
List< STTM001APoint > ExtractSTTM001APoints (STDT002A chain, DateTime evaluationDate)
Extracts term structure points from the option chain.
double CalculateExpectedMove (STDT002A chain, DateTime earningsDate, DateTime evaluationDate)
Calculates the expected move from the ATM straddle price.
double CalculateVolatilitySpread (STDT002A chain, DateTime evaluationDate)
Calculates the weighted volatility spread (put IV - call IV) as per Atilgan (2014).
void SafeLog (Action logAction)
Safely executes logging operation with fault isolation (Rule 15). Prevents logging failures from crashing critical paths.
Static Private Member Functions
static void ComputeTheoreticalMetrics (STCR004A signal, STDT002A optionChain, DateTime earningsDate, DateTime evaluationDate)
Computes theoretical IV, mispricing signal, and IV crush metrics.
static bool HasValidIVData (STDT002A optionChain)
Checks if the option chain has valid IV data for signal generation. Returns false if all IVs are zero or missing.
Private Attributes
readonly STDT001A _marketData
readonly STCR003A _yangZhang
readonly STTM001A _termAnalyzer
readonly STIV005A _earningsCalibrator
readonly? ILogger< STCR001A > _logger
List< PriceBar > priceHistory
Fetches market data required for signal generation.
Static Private Attributes
static readonly Action< ILogger, string, DateTime, Exception?> LogGeneratingSTCR004A
static readonly Action< ILogger, string, Exception?> LogInsufficientPriceHistory
static readonly Action< ILogger, string, Exception?> LogNoOptionData
static readonly Action< ILogger, string, Exception?> LogInsufficientSTTM001A
static readonly Action< ILogger, string, STCR004AStrength, double, double, long, Exception?> LogSTCR004AGenerated
static readonly Action< ILogger, string, Exception?> LogErrorGeneratingSTCR004A
static readonly Action< ILogger, string, double, double, double, Exception?> LogLeungSantoliMetrics
const double MinIvRvRatio = 1.25
const double MaxTermSlope = -0.00406
const long MinAverageVolume = 1_500_000
Detailed Description
Generates trading signals for earnings calendar spread opportunities. Implements the strategy from Atilgan (2014) and incorporates term structure analysis. Enhanced with Leung & Santoli (2014) model for theoretical IV and mispricing signals.
Definition at line 14 of file STCR001A.cs.
Constructor & Destructor Documentation
STCR001A()
Alaris.Strategy.Core.STCR001A.STCR001A (STDT001A marketData, STCR003A yangZhang, STTM001A termAnalyzer, STIV005A? earningsCalibrator = null, ILogger< STCR001A >? logger = null) inline
Initializes a new instance of the STCR001A class.
Parameters
marketData Market data provider for prices and options.
yangZhang Yang-Zhang volatility estimator.
termAnalyzer Term structure analyzer.
earningsCalibrator Optional L&S earnings jump calibrator.
logger Optional logger instance.
Definition at line 78 of file STCR001A.cs.
References Alaris.Strategy.Core.STCR001A._earningsCalibrator, Alaris.Strategy.Core.STCR001A._logger, Alaris.Strategy.Core.STCR001A._marketData, Alaris.Strategy.Core.STCR001A._termAnalyzer, and Alaris.Strategy.Core.STCR001A._yangZhang.
Member Function Documentation
CalculateExpectedMove()
double Alaris.Strategy.Core.STCR001A.CalculateExpectedMove (STDT002A chain, DateTime earningsDate, DateTime evaluationDate) inline private
Calculates the expected move from the ATM straddle price.
Definition at line 417 of file STCR001A.cs.
References Alaris.Strategy.Model.OptionExpiry.Calls, Alaris.Strategy.Model.STDT002A.Expiries, Alaris.Strategy.Model.OptionContract.MidPrice, Alaris.Strategy.Model.OptionExpiry.Puts, Alaris.Strategy.Model.OptionContract.Strike, and Alaris.Strategy.Model.STDT002A.UnderlyingPrice.
Referenced by Alaris.Strategy.Core.STCR001A.CalculateSTCR004AMetrics().
CalculateLeungSantoliMetrics()
void Alaris.Strategy.Core.STCR001A.CalculateLeungSantoliMetrics (STCR004A signal, List< PriceBar > priceHistory, STDT002A optionChain, DateTime earningsDate, DateTime evaluationDate, IReadOnlyList< DateTime >? historicalEarningsDates) inline private
Calculates Leung & Santoli (2014) model metrics including:
Earnings jump volatility (sigma_e) calibrated from historical EA moves
Theoretical pre-EA implied volatility: I(t) = sqrt(sigma^2 + sigma_e^2/(T-t))
IV mispricing signal (market IV vs theoretical)
Expected IV crush magnitude
Definition at line 246 of file STCR001A.cs.
References Alaris.Strategy.Core.STCR001A._logger, Alaris.Strategy.Core.STCR001A.ComputeTheoreticalMetrics(), Alaris.Strategy.Core.STCR004A.EarningsJumpVolatility, Alaris.Strategy.Core.STCR004A.IVMispricingSTCR004A, Alaris.Strategy.Core.STCR001A.LogLeungSantoliMetrics, Alaris.Strategy.Core.STCR001A.priceHistory, Alaris.Strategy.Core.STCR001A.SafeLog(), Alaris.Strategy.Core.STCR004A.Symbol, Alaris.Strategy.Core.STCR004A.TheoreticalIV, Alaris.Strategy.Core.STCR001A.TryCalibrateFromHistory(), and Alaris.Strategy.Core.STCR001A.TryCalibrateFromTermStructure().
Referenced by Alaris.Strategy.Core.STCR001A.CalculateSTCR004AMetrics().
CalculateSTCR004AMetrics()
void Alaris.Strategy.Core.STCR001A.CalculateSTCR004AMetrics (STCR004A signal, List< PriceBar > priceHistory, STDT002A optionChain, DateTime earningsDate, DateTime evaluationDate, IReadOnlyList< DateTime >? historicalEarningsDates) inline private
Calculates all signal metrics including volatility, term structure, and criteria. Enhanced with Leung & Santoli (2014) model calculations.
Definition at line 185 of file STCR001A.cs.
References Alaris.Strategy.Core.STCR001A._logger, Alaris.Strategy.Core.STCR001A._termAnalyzer, Alaris.Strategy.Core.STCR001A._yangZhang, Alaris.Strategy.Core.STTM001A.Analyze(), Alaris.Strategy.Core.STCR003A.Calculate(), Alaris.Strategy.Core.STCR001A.CalculateExpectedMove(), Alaris.Strategy.Core.STCR001A.CalculateLeungSantoliMetrics(), Alaris.Strategy.Core.STCR001A.CalculateVolatilitySpread(), Alaris.Strategy.Core.STCR004A.Criteria, Alaris.Strategy.Core.STCR004A.EvaluateStrength(), Alaris.Strategy.Core.STCR001A.ExtractSTTM001APoints(), Alaris.Strategy.Core.STTM001AAnalysis.GetIVAt(), Alaris.Strategy.Core.STCR004A.ImpliedVolatility30, Alaris.Strategy.Core.STCR001A.LogInsufficientSTTM001A, Alaris.Strategy.Core.STCR001A.MaxTermSlope, Alaris.Strategy.Core.STCR001A.MinAverageVolume, Alaris.Strategy.Core.STCR001A.MinIvRvRatio, Alaris.Strategy.Core.STCR001A.priceHistory, Alaris.Strategy.Core.STCR004A.RealizedVolatility30, Alaris.Strategy.Core.STCR001A.SafeLog(), Alaris.Strategy.Core.STTM001AAnalysis.Slope, and Alaris.Strategy.Core.STCR004A.Symbol.
Referenced by Alaris.Strategy.Core.STCR001A.Generate().
CalculateVolatilitySpread()
double Alaris.Strategy.Core.STCR001A.CalculateVolatilitySpread (STDT002A chain, DateTime evaluationDate) inline private
Calculates the weighted volatility spread (put IV - call IV) as per Atilgan (2014).
Definition at line 454 of file STCR001A.cs.
References Alaris.Strategy.Model.OptionExpiry.Calls, Alaris.Strategy.Model.OptionExpiry.GetDaysToExpiry(), Alaris.Strategy.Model.OptionExpiry.Puts, and Alaris.Strategy.Model.STDT002A.UnderlyingPrice.
Referenced by Alaris.Strategy.Core.STCR001A.CalculateSTCR004AMetrics().
ComputeTheoreticalMetrics()
static void Alaris.Strategy.Core.STCR001A.ComputeTheoreticalMetrics (STCR004A signal, STDT002A optionChain, DateTime earningsDate, DateTime evaluationDate) inline static private
Computes theoretical IV, mispricing signal, and IV crush metrics.
Definition at line 324 of file STCR001A.cs.
References Alaris.Strategy.Core.STCR004A.BaseVolatility, Alaris.Strategy.Core.STIV004A.ComputeExpectedIVCrush(), Alaris.Strategy.Core.STIV004A.ComputeIVCrushRatio(), Alaris.Strategy.Core.STIV004A.ComputeTheoreticalIV(), Alaris.Strategy.Calendar.TradingCalendarDefaults.DteToYears(), Alaris.Strategy.Core.STCR004A.EarningsJumpVolatility, Alaris.Strategy.Model.STDT002A.Expiries, Alaris.Strategy.Model.OptionExpiry.GetDaysToExpiry(), and Alaris.Strategy.Core.STCR004A.TheoreticalIV.
Referenced by Alaris.Strategy.Core.STCR001A.CalculateLeungSantoliMetrics().
ExtractSTTM001APoints()
List< STTM001APoint > Alaris.Strategy.Core.STCR001A.ExtractSTTM001APoints (STDT002A chain, DateTime evaluationDate) inline private
Extracts term structure points from the option chain.
Definition at line 373 of file STCR001A.cs.
References Alaris.Strategy.Model.OptionExpiry.Calls, Alaris.Strategy.Model.OptionExpiry.GetDaysToExpiry(), Alaris.Strategy.Model.OptionExpiry.Puts, and Alaris.Strategy.Model.STDT002A.UnderlyingPrice.
Referenced by Alaris.Strategy.Core.STCR001A.CalculateSTCR004AMetrics(), and Alaris.Strategy.Core.STCR001A.TryCalibrateFromTermStructure().
FetchMarketData()
List< PriceBar > STDT002A optionChain Alaris.Strategy.Core.STCR001A.FetchMarketData (string symbol, DateTime evaluationDate) inline private
Definition at line 174 of file STCR001A.cs.
References Alaris.Strategy.Core.STCR001A._marketData, Alaris.Strategy.Bridge.STDT001A.GetHistoricalPrices(), Alaris.Strategy.Bridge.STDT001A.GetSTDT002A(), and Alaris.Strategy.Core.STCR001A.priceHistory.
Referenced by Alaris.Strategy.Core.STCR001A.Generate().
Generate() [1/2]
STCR004A Alaris.Strategy.Core.STCR001A.Generate (string symbol, DateTime earningsDate, DateTime evaluationDate) inline
Generates a trading signal for a given symbol before an earnings announcement.
Definition at line 95 of file STCR001A.cs.
References Alaris.Strategy.Core.STCR001A.Generate().
Referenced by Alaris.Strategy.STCT001A.EvaluateOpportunity(), Alaris.Algorithm.STLN001A.EvaluateSnapshot(), and Alaris.Strategy.Core.STCR001A.Generate().
Generate() [2/2]
STCR004A Alaris.Strategy.Core.STCR001A.Generate (string symbol, DateTime earningsDate, DateTime evaluationDate, IReadOnlyList< DateTime >? historicalEarningsDates) inline
Generates a trading signal with Leung & Santoli (2014) model calibration.
Parameters
symbol The security symbol.
earningsDate Upcoming earnings announcement date.
evaluationDate Date when signal is being evaluated.
historicalEarningsDates Historical earnings dates for sigma_e calibration.
Returns
Trading signal with L&S model metrics if calibration data is provided.
Definition at line 108 of file STCR001A.cs.
References Alaris.Strategy.Core.STCR001A._logger, Alaris.Strategy.Core.STCR004A.AverageVolume, Alaris.Strategy.Core.STCR001A.CalculateSTCR004AMetrics(), Alaris.Strategy.Core.STCR001A.FetchMarketData(), Alaris.Strategy.Core.STCR001A.HasValidIVData(), Alaris.Strategy.Core.STCR004A.IVRVRatio, Alaris.Strategy.Core.STCR001A.LogErrorGeneratingSTCR004A, Alaris.Strategy.Core.STCR001A.LogGeneratingSTCR004A, Alaris.Strategy.Core.STCR001A.LogInsufficientPriceHistory, Alaris.Strategy.Core.STCR001A.LogNoOptionData, Alaris.Strategy.Core.STCR001A.LogSTCR004AGenerated, Alaris.Strategy.Core.STCR001A.priceHistory, Alaris.Strategy.Core.STCR001A.SafeLog(), Alaris.Strategy.Core.STCR004A.Strength, and Alaris.Strategy.Core.STCR004A.STTM001ASlope.
HasValidIVData()
static bool Alaris.Strategy.Core.STCR001A.HasValidIVData (STDT002A optionChain) inline static private
Checks if the option chain has valid IV data for signal generation. Returns false if all IVs are zero or missing.
Definition at line 493 of file STCR001A.cs.
Referenced by Alaris.Strategy.Core.STCR001A.Generate().
SafeLog()
void Alaris.Strategy.Core.STCR001A.SafeLog (Action logAction) inline private
Safely executes logging operation with fault isolation (Rule 15). Prevents logging failures from crashing critical paths.
Definition at line 519 of file STCR001A.cs.
References Alaris.Strategy.Core.STCR001A._logger.
Referenced by Alaris.Strategy.Core.STCR001A.CalculateLeungSantoliMetrics(), Alaris.Strategy.Core.STCR001A.CalculateSTCR004AMetrics(), and Alaris.Strategy.Core.STCR001A.Generate().
TryCalibrateFromHistory()
bool Alaris.Strategy.Core.STCR001A.TryCalibrateFromHistory (STCR004A signal, List< PriceBar > priceHistory, IReadOnlyList< DateTime >? historicalEarningsDates) inline private
Definition at line 268 of file STCR001A.cs.
References Alaris.Strategy.Core.STCR001A._earningsCalibrator, Alaris.Strategy.Core.STIV005A.Calibrate(), Alaris.Strategy.Core.EarningsJumpCalibration.IsValid, Alaris.Strategy.Core.STCR001A.priceHistory, Alaris.Strategy.Core.STCR004A.RealizedVolatility30, Alaris.Strategy.Core.EarningsJumpCalibration.SampleCount, Alaris.Strategy.Core.EarningsJumpCalibration.SigmaE, and Alaris.Strategy.Core.STCR004A.Symbol.
Referenced by Alaris.Strategy.Core.STCR001A.CalculateLeungSantoliMetrics().
TryCalibrateFromTermStructure()
bool Alaris.Strategy.Core.STCR001A.TryCalibrateFromTermStructure (STCR004A signal, STDT002A optionChain, DateTime evaluationDate) inline private
Definition at line 288 of file STCR001A.cs.
References Alaris.Strategy.Core.STIV005A.BaseVolatilityEstimator(), Alaris.Strategy.Core.STTM001APoint.DaysToExpiry, Alaris.Strategy.Core.STCR001A.ExtractSTTM001APoints(), Alaris.Strategy.Core.STTM001APoint.ImpliedVolatility, Alaris.Strategy.Core.STCR004A.RealizedVolatility30, and Alaris.Strategy.Core.STIV005A.STTM001AEstimator().
Referenced by Alaris.Strategy.Core.STCR001A.CalculateLeungSantoliMetrics().
Member Data Documentation
_earningsCalibrator
readonly STIV005A Alaris.Strategy.Core.STCR001A._earningsCalibrator private
Definition at line 19 of file STCR001A.cs.
Referenced by Alaris.Strategy.Core.STCR001A.STCR001A(), and Alaris.Strategy.Core.STCR001A.TryCalibrateFromHistory().
_logger
readonly? ILogger<STCR001A> Alaris.Strategy.Core.STCR001A._logger private
Definition at line 20 of file STCR001A.cs.
Referenced by Alaris.Strategy.Core.STCR001A.STCR001A(), Alaris.Strategy.Core.STCR001A.CalculateLeungSantoliMetrics(), Alaris.Strategy.Core.STCR001A.CalculateSTCR004AMetrics(), Alaris.Strategy.Core.STCR001A.Generate(), and Alaris.Strategy.Core.STCR001A.SafeLog().
_marketData
readonly STDT001A Alaris.Strategy.Core.STCR001A._marketData private
Definition at line 16 of file STCR001A.cs.
Referenced by Alaris.Strategy.Core.STCR001A.STCR001A(), and Alaris.Strategy.Core.STCR001A.FetchMarketData().
_termAnalyzer
readonly STTM001A Alaris.Strategy.Core.STCR001A._termAnalyzer private
Definition at line 18 of file STCR001A.cs.
Referenced by Alaris.Strategy.Core.STCR001A.STCR001A(), and Alaris.Strategy.Core.STCR001A.CalculateSTCR004AMetrics().
_yangZhang
readonly STCR003A Alaris.Strategy.Core.STCR001A._yangZhang private
Definition at line 17 of file STCR001A.cs.
Referenced by Alaris.Strategy.Core.STCR001A.STCR001A(), and Alaris.Strategy.Core.STCR001A.CalculateSTCR004AMetrics().
LogErrorGeneratingSTCR004A
readonly Action<ILogger, string, Exception?> Alaris.Strategy.Core.STCR001A.LogErrorGeneratingSTCR004A static private
Initial value:
=
        LoggerMessage.Define<string>(
            LogLevel.Error,
            new EventId(6, nameof(LogErrorGeneratingSTCR004A)),
            "Error generating signal for {Symbol}")
Definition at line 53 of file STCR001A.cs.
Referenced by Alaris.Strategy.Core.STCR001A.Generate().
LogGeneratingSTCR004A
readonly Action<ILogger, string, DateTime, Exception?> Alaris.Strategy.Core.STCR001A.LogGeneratingSTCR004A static private
Initial value:
=
        LoggerMessage.Define<string, DateTime>(
            LogLevel.Information,
            new EventId(1, nameof(LogGeneratingSTCR004A)),
            "Generating signal for {Symbol} with earnings on {EarningsDate}")
Definition at line 23 of file STCR001A.cs.
Referenced by Alaris.Strategy.Core.STCR001A.Generate().
LogInsufficientPriceHistory
readonly Action<ILogger, string, Exception?> Alaris.Strategy.Core.STCR001A.LogInsufficientPriceHistory static private
Initial value:
=
        LoggerMessage.Define<string>(
            LogLevel.Warning,
            new EventId(2, nameof(LogInsufficientPriceHistory)),
            "Insufficient price history for {Symbol}")
Definition at line 29 of file STCR001A.cs.
Referenced by Alaris.Strategy.Core.STCR001A.Generate().
LogInsufficientSTTM001A
readonly Action<ILogger, string, Exception?> Alaris.Strategy.Core.STCR001A.LogInsufficientSTTM001A static private
Initial value:
=
        LoggerMessage.Define<string>(
            LogLevel.Warning,
            new EventId(4, nameof(LogInsufficientSTTM001A)),
            "Insufficient term structure points for {Symbol}")
Definition at line 41 of file STCR001A.cs.
Referenced by Alaris.Strategy.Core.STCR001A.CalculateSTCR004AMetrics().
LogLeungSantoliMetrics
readonly Action<ILogger, string, double, double, double, Exception?> Alaris.Strategy.Core.STCR001A.LogLeungSantoliMetrics static private
Initial value:
=
        LoggerMessage.Define<string, double, double, double>(
            LogLevel.Information,
            new EventId(7, nameof(LogLeungSantoliMetrics)),
            "L&S model for {Symbol}: sigmaE={SigmaE:P2}, theoreticalIV={TheoreticalIV:P2}, mispricing={Mispricing:P2}")
Definition at line 59 of file STCR001A.cs.
Referenced by Alaris.Strategy.Core.STCR001A.CalculateLeungSantoliMetrics().
LogNoOptionData
readonly Action<ILogger, string, Exception?> Alaris.Strategy.Core.STCR001A.LogNoOptionData static private
Initial value:
=
        LoggerMessage.Define<string>(
            LogLevel.Warning,
            new EventId(3, nameof(LogNoOptionData)),
            "No option data available for {Symbol}")
Definition at line 35 of file STCR001A.cs.
Referenced by Alaris.Strategy.Core.STCR001A.Generate().
LogSTCR004AGenerated
readonly Action<ILogger, string, STCR004AStrength, double, double, long, Exception?> Alaris.Strategy.Core.STCR001A.LogSTCR004AGenerated static private
Initial value:
=
        LoggerMessage.Define<string, STCR004AStrength, double, double, long>(
            LogLevel.Information,
            new EventId(5, nameof(LogSTCR004AGenerated)),
            "STCR004A generated for {Symbol}: {Strength} (IV/RV={IvRv:F2}, Slope={Slope:F5}, Volume={Volume})")
Definition at line 47 of file STCR001A.cs.
Referenced by Alaris.Strategy.Core.STCR001A.Generate().
MaxTermSlope
const double Alaris.Strategy.Core.STCR001A.MaxTermSlope = -0.00406 static private
Definition at line 67 of file STCR001A.cs.
Referenced by Alaris.Strategy.Core.STCR001A.CalculateSTCR004AMetrics().
MinAverageVolume
const long Alaris.Strategy.Core.STCR001A.MinAverageVolume = 1_500_000 static private
Definition at line 68 of file STCR001A.cs.
Referenced by Alaris.Strategy.Core.STCR001A.CalculateSTCR004AMetrics().
MinIvRvRatio
const double Alaris.Strategy.Core.STCR001A.MinIvRvRatio = 1.25 static private
Definition at line 66 of file STCR001A.cs.
Referenced by Alaris.Strategy.Core.STCR001A.CalculateSTCR004AMetrics().
priceHistory
List<PriceBar> Alaris.Strategy.Core.STCR001A.priceHistory private
Fetches market data required for signal generation.
Definition at line 174 of file STCR001A.cs.
Referenced by Alaris.Strategy.Core.STCR001A.CalculateLeungSantoliMetrics(), Alaris.Strategy.Core.STCR001A.CalculateSTCR004AMetrics(), Alaris.Strategy.Core.STCR001A.FetchMarketData(), Alaris.Strategy.Core.STCR001A.Generate(), and Alaris.Strategy.Core.STCR001A.TryCalibrateFromHistory().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Core/STCR001A.cs