Alaris: Alaris.Infrastructure.Events.Infrastructure.EVIF001B Class Reference
Alaris.Infrastructure.Events.Infrastructure.EVIF001B Class Reference sealed
File-based persistent implementation of EVCR002A for production use.
Public Member Functions
EVIF001B (string storagePath)
Initializes a new file-based event store with binary format.
async Task< EVCR003A > AppendAsync< TEvent > (TEvent domainEvent, string? aggregateId=null, string? aggregateType=null, string? initiatedBy=null, IReadOnlyDictionary< string, string >? metadata=null, CancellationToken cancellationToken=default)
Appends an event to the event store.
Parameters
domainEvent The domain event to store.
aggregateId Optional aggregate identifier.
aggregateType Optional aggregate type.
initiatedBy The user or system that initiated this event.
metadata Additional metadata for the event.
cancellationToken Cancellation token.
Returns
The stored event envelope with sequence number.
async Task< IReadOnlyList< EVCR003A > > GetEventsForAggregateAsync (string aggregateId, CancellationToken cancellationToken=default)
Retrieves all events for a specific aggregate.
Parameters
aggregateId The aggregate identifier.
cancellationToken Cancellation token.
Returns
All events for the aggregate in chronological order.
async Task< IReadOnlyList< EVCR003A > > GetEventsFromSequenceAsync (long fromSequenceNumber, int maxCount=1000, CancellationToken cancellationToken=default)
Retrieves events starting from a specific sequence number. Used for event replay and projections.
Parameters
fromSequenceNumber The sequence number to start from (inclusive).
maxCount Maximum number of events to retrieve.
cancellationToken Cancellation token.
Returns
Events in chronological order.
Task< long > GetCurrentSequenceNumberAsync (CancellationToken cancellationToken=default)
Gets the current highest sequence number in the event store.
async Task< IReadOnlyList< EVCR003A > > GetEventsByCorrelationIdAsync (string correlationId, CancellationToken cancellationToken=default)
Retrieves events by correlation ID for tracing.
Parameters
correlationId The correlation identifier.
cancellationToken Cancellation token.
Returns
All events with the given correlation ID.
async Task< IReadOnlyList< EVCR003A > > GetEventsByTimeRangeAsync (DateTime fromUtc, DateTime toUtc, CancellationToken cancellationToken=default)
Retrieves events within a time range.
Parameters
fromUtc Start time (inclusive).
toUtc End time (inclusive).
cancellationToken Cancellation token.
Returns
Events within the time range.
void Dispose ()
Private Member Functions
async IAsyncEnumerable< EVCR003A > ReadEventsAsync ([System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken cancellationToken=default)
long RecoverSequence ()
void PersistSequence (long sequence)
Static Private Member Functions
static byte[] SerializeEnvelope (EVCR003A envelope)
static EVCR003A DeserializeEnvelope (ReadOnlySpan< byte > buffer)
Private Attributes
readonly string _eventsPath
readonly string _sequencePath
readonly SemaphoreSlim _writeSemaphore = new(1, 1)
readonly SemaphoreSlim _readSemaphore = new(1, 1)
long _currentSequence
bool _disposed
Static Private Attributes
const int HeaderSize = 64
const int MaxRecordSize = 1024 * 1024
Detailed Description
File-based persistent implementation of EVCR002A for production use.
Storage format: Binary (SBE-style)
Fixed header: 64 bytes (sequence, eventId, timestamps, lengths)
Variable fields: length-prefixed UTF-8 strings
Append-only (immutable once written)
Binary Layout per record: [0-7] SequenceNumber (long) [8-23] EventId (Guid - 16 bytes) [24-31] StoredAtUtc (long, ticks) [32-35] EventTypeLength (int) [36-39] EventDataLength (int) [40-43] AggregateIdLength (int) [44-47] AggregateTypeLength (int) [48-51] CorrelationIdLength (int) [52-55] InitiatedByLength (int) [56-59] TotalRecordLength (int) [60-63] Reserved/Checksum [64...] Variable-length string data
Definition at line 36 of file EVIF001B.cs.
Constructor & Destructor Documentation
EVIF001B()
Alaris.Infrastructure.Events.Infrastructure.EVIF001B.EVIF001B (string storagePath) inline
Initializes a new file-based event store with binary format.
Parameters
storagePath Directory for event storage files.
Definition at line 52 of file EVIF001B.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF001B._currentSequence, Alaris.Infrastructure.Events.Infrastructure.EVIF001B._eventsPath, Alaris.Infrastructure.Events.Infrastructure.EVIF001B._sequencePath, and Alaris.Infrastructure.Events.Infrastructure.EVIF001B.RecoverSequence().
Member Function Documentation
AppendAsync< TEvent >()
async Task< EVCR003A > Alaris.Infrastructure.Events.Infrastructure.EVIF001B.AppendAsync< TEvent > (TEvent domainEvent, string? aggregateId = null, string? aggregateType = null, string? initiatedBy = null, IReadOnlyDictionary< string, string >? metadata = null, CancellationToken cancellationToken = default) inline
Appends an event to the event store.
Parameters
domainEvent The domain event to store.
aggregateId Optional aggregate identifier.
aggregateType Optional aggregate type.
initiatedBy The user or system that initiated this event.
metadata Additional metadata for the event.
cancellationToken Cancellation token.
Returns
The stored event envelope with sequence number.
Implements Alaris.Infrastructure.Events.Core.EVCR002A.
Type Constraints
TEvent : EVCR001A
Definition at line 65 of file EVIF001B.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF001B._currentSequence, Alaris.Infrastructure.Events.Infrastructure.EVIF001B._disposed, Alaris.Infrastructure.Events.Infrastructure.EVIF001B._eventsPath, Alaris.Infrastructure.Events.Infrastructure.EVIF001B._writeSemaphore, Alaris.Infrastructure.Events.Core.EVCR003A, Alaris.Infrastructure.Events.Infrastructure.EVIF001B.PersistSequence(), and Alaris.Infrastructure.Events.Infrastructure.EVIF001B.SerializeEnvelope().
DeserializeEnvelope()
static EVCR003A Alaris.Infrastructure.Events.Infrastructure.EVIF001B.DeserializeEnvelope (ReadOnlySpan< byte > buffer) inline static private
Definition at line 302 of file EVIF001B.cs.
References Alaris.Infrastructure.Events.Core.EVCR003A.
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF001B.ReadEventsAsync().
Dispose()
void Alaris.Infrastructure.Events.Infrastructure.EVIF001B.Dispose () inline
Definition at line 487 of file EVIF001B.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF001B._disposed, Alaris.Infrastructure.Events.Infrastructure.EVIF001B._readSemaphore, and Alaris.Infrastructure.Events.Infrastructure.EVIF001B._writeSemaphore.
GetCurrentSequenceNumberAsync()
Task< long > Alaris.Infrastructure.Events.Infrastructure.EVIF001B.GetCurrentSequenceNumberAsync (CancellationToken cancellationToken = default) inline
Gets the current highest sequence number in the event store.
Implements Alaris.Infrastructure.Events.Core.EVCR002A.
Definition at line 175 of file EVIF001B.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF001B._currentSequence, and Alaris.Infrastructure.Events.Infrastructure.EVIF001B._disposed.
Referenced by Alaris.Test.Unit.TSUN033A.EVIF001B_RecoverSequence_AfterRestart().
GetEventsByCorrelationIdAsync()
async Task< IReadOnlyList< EVCR003A > > Alaris.Infrastructure.Events.Infrastructure.EVIF001B.GetEventsByCorrelationIdAsync (string correlationId, CancellationToken cancellationToken = default) inline
Retrieves events by correlation ID for tracing.
Parameters
correlationId The correlation identifier.
cancellationToken Cancellation token.
Returns
All events with the given correlation ID.
Implements Alaris.Infrastructure.Events.Core.EVCR002A.
Definition at line 182 of file EVIF001B.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF001B._disposed, Alaris.Infrastructure.Events.Infrastructure.EVIF001B._readSemaphore, Alaris.Infrastructure.Events.Core.EVCR003A, and Alaris.Infrastructure.Events.Infrastructure.EVIF001B.ReadEventsAsync().
GetEventsByTimeRangeAsync()
async Task< IReadOnlyList< EVCR003A > > Alaris.Infrastructure.Events.Infrastructure.EVIF001B.GetEventsByTimeRangeAsync (DateTime fromUtc, DateTime toUtc, CancellationToken cancellationToken = default) inline
Retrieves events within a time range.
Parameters
fromUtc Start time (inclusive).
toUtc End time (inclusive).
cancellationToken Cancellation token.
Returns
Events within the time range.
Implements Alaris.Infrastructure.Events.Core.EVCR002A.
Definition at line 211 of file EVIF001B.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF001B._disposed, Alaris.Infrastructure.Events.Infrastructure.EVIF001B._readSemaphore, Alaris.Infrastructure.Events.Core.EVCR003A, and Alaris.Infrastructure.Events.Infrastructure.EVIF001B.ReadEventsAsync().
GetEventsForAggregateAsync()
async Task< IReadOnlyList< EVCR003A > > Alaris.Infrastructure.Events.Infrastructure.EVIF001B.GetEventsForAggregateAsync (string aggregateId, CancellationToken cancellationToken = default) inline
Retrieves all events for a specific aggregate.
Parameters
aggregateId The aggregate identifier.
cancellationToken Cancellation token.
Returns
All events for the aggregate in chronological order.
Implements Alaris.Infrastructure.Events.Core.EVCR002A.
Definition at line 113 of file EVIF001B.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF001B._disposed, Alaris.Infrastructure.Events.Infrastructure.EVIF001B._readSemaphore, Alaris.Infrastructure.Events.Core.EVCR003A, and Alaris.Infrastructure.Events.Infrastructure.EVIF001B.ReadEventsAsync().
Referenced by Alaris.Test.Unit.TSUN033A.EVIF001B_GetEventsForAggregateAsync_FiltersCorrectly().
GetEventsFromSequenceAsync()
async Task< IReadOnlyList< EVCR003A > > Alaris.Infrastructure.Events.Infrastructure.EVIF001B.GetEventsFromSequenceAsync (long fromSequenceNumber, int maxCount = 1000, CancellationToken cancellationToken = default) inline
Retrieves events starting from a specific sequence number. Used for event replay and projections.
Parameters
fromSequenceNumber The sequence number to start from (inclusive).
maxCount Maximum number of events to retrieve.
cancellationToken Cancellation token.
Returns
Events in chronological order.
Implements Alaris.Infrastructure.Events.Core.EVCR002A.
Definition at line 142 of file EVIF001B.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF001B._disposed, Alaris.Infrastructure.Events.Infrastructure.EVIF001B._readSemaphore, Alaris.Infrastructure.Events.Core.EVCR003A, and Alaris.Infrastructure.Events.Infrastructure.EVIF001B.ReadEventsAsync().
Referenced by Alaris.Test.Unit.TSUN033A.EVIF001B_GetEventsFromSequenceAsync_ReturnsFromSequence().
PersistSequence()
void Alaris.Infrastructure.Events.Infrastructure.EVIF001B.PersistSequence (long sequence) inline private
Definition at line 478 of file EVIF001B.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF001B._sequencePath.
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF001B.AppendAsync< TEvent >().
ReadEventsAsync()
async IAsyncEnumerable< EVCR003A > Alaris.Infrastructure.Events.Infrastructure.EVIF001B.ReadEventsAsync ([System::Runtime::CompilerServices::EnumeratorCancellation] CancellationToken cancellationToken = default) inline private
Definition at line 362 of file EVIF001B.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF001B._eventsPath, Alaris.Infrastructure.Events.Infrastructure.EVIF001B.DeserializeEnvelope(), Alaris.Infrastructure.Events.Core.EVCR003A, Alaris.Infrastructure.Events.Infrastructure.EVIF001B.HeaderSize, and Alaris.Infrastructure.Events.Infrastructure.EVIF001B.MaxRecordSize.
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF001B.GetEventsByCorrelationIdAsync(), Alaris.Infrastructure.Events.Infrastructure.EVIF001B.GetEventsByTimeRangeAsync(), Alaris.Infrastructure.Events.Infrastructure.EVIF001B.GetEventsForAggregateAsync(), and Alaris.Infrastructure.Events.Infrastructure.EVIF001B.GetEventsFromSequenceAsync().
RecoverSequence()
long Alaris.Infrastructure.Events.Infrastructure.EVIF001B.RecoverSequence () inline private
Definition at line 428 of file EVIF001B.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF001B._eventsPath, Alaris.Infrastructure.Events.Infrastructure.EVIF001B._sequencePath, Alaris.Infrastructure.Events.Infrastructure.EVIF001B.HeaderSize, and Alaris.Infrastructure.Events.Infrastructure.EVIF001B.MaxRecordSize.
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF001B.EVIF001B().
SerializeEnvelope()
static byte[] Alaris.Infrastructure.Events.Infrastructure.EVIF001B.SerializeEnvelope (EVCR003A envelope) inline static private
Definition at line 240 of file EVIF001B.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF001B.HeaderSize.
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF001B.AppendAsync< TEvent >().
Member Data Documentation
_currentSequence
long Alaris.Infrastructure.Events.Infrastructure.EVIF001B._currentSequence private
Definition at line 42 of file EVIF001B.cs.
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF001B.EVIF001B(), Alaris.Infrastructure.Events.Infrastructure.EVIF001B.AppendAsync< TEvent >(), and Alaris.Infrastructure.Events.Infrastructure.EVIF001B.GetCurrentSequenceNumberAsync().
_disposed
bool Alaris.Infrastructure.Events.Infrastructure.EVIF001B._disposed private
Definition at line 43 of file EVIF001B.cs.
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF001B.AppendAsync< TEvent >(), Alaris.Infrastructure.Events.Infrastructure.EVIF001B.Dispose(), Alaris.Infrastructure.Events.Infrastructure.EVIF001B.GetCurrentSequenceNumberAsync(), Alaris.Infrastructure.Events.Infrastructure.EVIF001B.GetEventsByCorrelationIdAsync(), Alaris.Infrastructure.Events.Infrastructure.EVIF001B.GetEventsByTimeRangeAsync(), Alaris.Infrastructure.Events.Infrastructure.EVIF001B.GetEventsForAggregateAsync(), and Alaris.Infrastructure.Events.Infrastructure.EVIF001B.GetEventsFromSequenceAsync().
_eventsPath
readonly string Alaris.Infrastructure.Events.Infrastructure.EVIF001B._eventsPath private
Definition at line 38 of file EVIF001B.cs.
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF001B.EVIF001B(), Alaris.Infrastructure.Events.Infrastructure.EVIF001B.AppendAsync< TEvent >(), Alaris.Infrastructure.Events.Infrastructure.EVIF001B.ReadEventsAsync(), and Alaris.Infrastructure.Events.Infrastructure.EVIF001B.RecoverSequence().
_readSemaphore
readonly SemaphoreSlim Alaris.Infrastructure.Events.Infrastructure.EVIF001B._readSemaphore = new(1, 1) private
Definition at line 41 of file EVIF001B.cs.
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF001B.Dispose(), Alaris.Infrastructure.Events.Infrastructure.EVIF001B.GetEventsByCorrelationIdAsync(), Alaris.Infrastructure.Events.Infrastructure.EVIF001B.GetEventsByTimeRangeAsync(), Alaris.Infrastructure.Events.Infrastructure.EVIF001B.GetEventsForAggregateAsync(), and Alaris.Infrastructure.Events.Infrastructure.EVIF001B.GetEventsFromSequenceAsync().
_sequencePath
readonly string Alaris.Infrastructure.Events.Infrastructure.EVIF001B._sequencePath private
Definition at line 39 of file EVIF001B.cs.
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF001B.EVIF001B(), Alaris.Infrastructure.Events.Infrastructure.EVIF001B.PersistSequence(), and Alaris.Infrastructure.Events.Infrastructure.EVIF001B.RecoverSequence().
_writeSemaphore
readonly SemaphoreSlim Alaris.Infrastructure.Events.Infrastructure.EVIF001B._writeSemaphore = new(1, 1) private
Definition at line 40 of file EVIF001B.cs.
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF001B.AppendAsync< TEvent >(), and Alaris.Infrastructure.Events.Infrastructure.EVIF001B.Dispose().
HeaderSize
const int Alaris.Infrastructure.Events.Infrastructure.EVIF001B.HeaderSize = 64 static private
Definition at line 45 of file EVIF001B.cs.
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF001B.ReadEventsAsync(), Alaris.Infrastructure.Events.Infrastructure.EVIF001B.RecoverSequence(), and Alaris.Infrastructure.Events.Infrastructure.EVIF001B.SerializeEnvelope().
MaxRecordSize
const int Alaris.Infrastructure.Events.Infrastructure.EVIF001B.MaxRecordSize = 1024 * 1024 static private
Definition at line 46 of file EVIF001B.cs.
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF001B.ReadEventsAsync(), and Alaris.Infrastructure.Events.Infrastructure.EVIF001B.RecoverSequence().
The documentation for this class was generated from the following file:
src/Alaris.Infrastructure/Events/Infrastructure/EVIF001B.cs