Alaris: Alaris.Core.Pricing.CRAP001A Class Reference
Alaris.Core.Pricing.CRAP001A Class Reference sealed
QD+ approximation using Super Halley's method (third-order). Valid for q < r < 0 regime.
Public Member Functions
CRAP001A (double spot, double strike, double maturity, double rate, double dividendYield, double volatility, bool isCall)
Initializes a new instance of the QD+ approximation engine.
double double Lower CalculateBoundaries ()
Public Attributes
double Upper
Calculates both upper and lower boundaries using QD+ approximation.
Private Member Functions
double double Lower CalculateDoubleBoundariesPut ()
double double Lower CalculateDoubleBoundariesCall ()
double CalculateSingleBoundaryPut ()
double CalculateSingleBoundaryCall ()
double SolveBoundaryEquation (double lambda, double h, bool isUpper)
double double double d2f EvaluateBoundaryFunction (double S, double lambda, double h)
double CalculateC0 (double S, double h, double lambda, double alpha, double beta, double lambdaPrime,(double VE, double Theta, double D1) bs)
double double double D1 CalculateBsComponents (double S)
double GetGeneralizedInitialGuess (bool isUpper)
double InterpolateBenchmark (double T, bool isUpper)
double double Lambda2 CalculateLambdaRoots (double h, double omega, double sigma2)
double ValidateRoot (double S, double initialGuess)
double double Lower ApplyBoundaryConstraints (double upper, double lower)
double double Lower ApproximateForSmallH ()
double CalculateLambdaPrime (double lambda, double h, double sigma2)
double CalculateDc0DS (double S,(double VE, double Theta, double D1) bs)
double EnsureDistanceSteps (double S)
Static Private Member Functions
static double NormalCDF (double x)
static double NormalPDF (double x)
Private Attributes
readonly double _spot
readonly double _strike
readonly double _maturity
readonly double _rate
readonly double _dividendYield
readonly double _volatility
readonly bool _isCall
double f
double double df
double VE
double double Theta
double Lambda1
Static Private Attributes
const double Tolerance = 1e-8
const int MaxIterations = 100
const double NumericalEpsilon = 1e-12
Detailed Description
QD+ approximation using Super Halley's method (third-order). Valid for q < r < 0 regime.
Definition at line 13 of file CRAP001A.cs.
Constructor & Destructor Documentation
CRAP001A()
Alaris.Core.Pricing.CRAP001A.CRAP001A (double spot, double strike, double maturity, double rate, double dividendYield, double volatility, bool isCall) inline
Initializes a new instance of the QD+ approximation engine.
Parameters
spot Current underlying price (must be > 0).
strike Option strike price (must be > 0).
maturity Time to maturity in years (must be > 0).
rate Risk-free interest rate (can be negative).
dividendYield Dividend yield (can be negative).
volatility Annualized volatility (must be > 0).
isCall True for Call options, False for Put options.
Definition at line 37 of file CRAP001A.cs.
References Alaris.Core.Pricing.CRAP001A._dividendYield, Alaris.Core.Pricing.CRAP001A._isCall, Alaris.Core.Pricing.CRAP001A._maturity, Alaris.Core.Pricing.CRAP001A._rate, Alaris.Core.Pricing.CRAP001A._spot, Alaris.Core.Pricing.CRAP001A._strike, Alaris.Core.Pricing.CRAP001A._volatility, and Alaris.Core.Validation.AlgorithmBounds.ValidateDoubleBoundaryInputs().
Member Function Documentation
ApplyBoundaryConstraints()
double double Lower Alaris.Core.Pricing.CRAP001A.ApplyBoundaryConstraints (double upper, double lower) inline private
Definition at line 391 of file CRAP001A.cs.
References Alaris.Core.Pricing.CRAP001A._isCall, and Alaris.Core.Pricing.CRAP001A._strike.
Referenced by Alaris.Core.Pricing.CRAP001A.CalculateDoubleBoundariesCall(), and Alaris.Core.Pricing.CRAP001A.CalculateDoubleBoundariesPut().
ApproximateForSmallH()
double double Lower Alaris.Core.Pricing.CRAP001A.ApproximateForSmallH () inline private
Definition at line 414 of file CRAP001A.cs.
References Alaris.Core.Pricing.CRAP001A._isCall, Alaris.Core.Pricing.CRAP001A._maturity, Alaris.Core.Pricing.CRAP001A._strike, and Alaris.Core.Pricing.CRAP001A._volatility.
Referenced by Alaris.Core.Pricing.CRAP001A.CalculateDoubleBoundariesCall(), and Alaris.Core.Pricing.CRAP001A.CalculateDoubleBoundariesPut().
CalculateBoundaries()
double double Lower Alaris.Core.Pricing.CRAP001A.CalculateBoundaries () inline
Definition at line 62 of file CRAP001A.cs.
References Alaris.Core.Pricing.CRAP001A._dividendYield, Alaris.Core.Pricing.CRAP001A._isCall, Alaris.Core.Pricing.CRAP001A._rate, Alaris.Core.Pricing.CRAP001A._strike, Alaris.Core.Pricing.CRAP001A.CalculateDoubleBoundariesCall(), Alaris.Core.Pricing.CRAP001A.CalculateDoubleBoundariesPut(), Alaris.Core.Pricing.CRAP001A.CalculateSingleBoundaryCall(), and Alaris.Core.Pricing.CRAP001A.CalculateSingleBoundaryPut().
Referenced by Alaris.Core.Pricing.CRSL001A.CalculateInitialBoundaries(), Alaris.Core.Pricing.CRSL002A.FallbackToQdPlusConstant(), Alaris.Core.Pricing.CREN004A.PriceDoubleBoundary(), and Alaris.Core.Pricing.CREN003A.PriceWithDetails().
CalculateBsComponents()
double double double D1 Alaris.Core.Pricing.CRAP001A.CalculateBsComponents (double S) inline private
Definition at line 259 of file CRAP001A.cs.
References Alaris.Core.Pricing.CRAP001A._dividendYield, Alaris.Core.Pricing.CRAP001A._isCall, Alaris.Core.Pricing.CRAP001A._maturity, Alaris.Core.Pricing.CRAP001A._rate, Alaris.Core.Pricing.CRAP001A._strike, Alaris.Core.Pricing.CRAP001A._volatility, Alaris.Core.Pricing.CRAP001A.NormalCDF(), and Alaris.Core.Pricing.CRAP001A.NormalPDF().
CalculateC0()
double Alaris.Core.Pricing.CRAP001A.CalculateC0 (double S, double h, double lambda, double alpha, double beta, double lambdaPrime, (double VE, double Theta, double D1) bs) inline private
Definition at line 233 of file CRAP001A.cs.
References Alaris.Core.Pricing.CRAP001A._isCall, Alaris.Core.Pricing.CRAP001A._rate, Alaris.Core.Pricing.CRAP001A._strike, and Alaris.Core.Pricing.CRAP001A.NumericalEpsilon.
CalculateDc0DS()
double Alaris.Core.Pricing.CRAP001A.CalculateDc0DS (double S, (double VE, double Theta, double D1) bs) inline private
Definition at line 446 of file CRAP001A.cs.
References Alaris.Core.Pricing.CRAP001A._dividendYield, Alaris.Core.Pricing.CRAP001A._maturity, Alaris.Core.Pricing.CRAP001A._rate, Alaris.Core.Pricing.CRAP001A._strike, Alaris.Core.Pricing.CRAP001A.NormalCDF(), Alaris.Core.Pricing.CRAP001A.NormalPDF(), and Alaris.Core.Pricing.CRAP001A.NumericalEpsilon.
CalculateDoubleBoundariesCall()
double double Lower Alaris.Core.Pricing.CRAP001A.CalculateDoubleBoundariesCall () inline private
Definition at line 113 of file CRAP001A.cs.
References Alaris.Core.Pricing.CRAP001A._dividendYield, Alaris.Core.Pricing.CRAP001A._maturity, Alaris.Core.Pricing.CRAP001A._rate, Alaris.Core.Pricing.CRAP001A._volatility, Alaris.Core.Pricing.CRAP001A.ApplyBoundaryConstraints(), Alaris.Core.Pricing.CRAP001A.ApproximateForSmallH(), Alaris.Core.Pricing.CRAP001A.CalculateLambdaRoots(), Alaris.Core.Pricing.CRAP001A.NumericalEpsilon, and Alaris.Core.Pricing.CRAP001A.SolveBoundaryEquation().
Referenced by Alaris.Core.Pricing.CRAP001A.CalculateBoundaries().
CalculateDoubleBoundariesPut()
double double Lower Alaris.Core.Pricing.CRAP001A.CalculateDoubleBoundariesPut () inline private
Definition at line 90 of file CRAP001A.cs.
References Alaris.Core.Pricing.CRAP001A._dividendYield, Alaris.Core.Pricing.CRAP001A._maturity, Alaris.Core.Pricing.CRAP001A._rate, Alaris.Core.Pricing.CRAP001A._volatility, Alaris.Core.Pricing.CRAP001A.ApplyBoundaryConstraints(), Alaris.Core.Pricing.CRAP001A.ApproximateForSmallH(), Alaris.Core.Pricing.CRAP001A.CalculateLambdaRoots(), Alaris.Core.Pricing.CRAP001A.NumericalEpsilon, and Alaris.Core.Pricing.CRAP001A.SolveBoundaryEquation().
Referenced by Alaris.Core.Pricing.CRAP001A.CalculateBoundaries().
CalculateLambdaPrime()
double Alaris.Core.Pricing.CRAP001A.CalculateLambdaPrime (double lambda, double h, double sigma2) inline private
Definition at line 430 of file CRAP001A.cs.
References Alaris.Core.Pricing.CRAP001A._dividendYield, Alaris.Core.Pricing.CRAP001A._rate, and Alaris.Core.Pricing.CRAP001A.NumericalEpsilon.
CalculateLambdaRoots()
double double Lambda2 Alaris.Core.Pricing.CRAP001A.CalculateLambdaRoots (double h, double omega, double sigma2) inline private
Definition at line 354 of file CRAP001A.cs.
References Alaris.Core.Pricing.CRAP001A._rate.
Referenced by Alaris.Core.Pricing.CRAP001A.CalculateDoubleBoundariesCall(), Alaris.Core.Pricing.CRAP001A.CalculateDoubleBoundariesPut(), Alaris.Core.Pricing.CRAP001A.CalculateSingleBoundaryCall(), and Alaris.Core.Pricing.CRAP001A.CalculateSingleBoundaryPut().
CalculateSingleBoundaryCall()
double Alaris.Core.Pricing.CRAP001A.CalculateSingleBoundaryCall () inline private
Definition at line 148 of file CRAP001A.cs.
References Alaris.Core.Pricing.CRAP001A._dividendYield, Alaris.Core.Pricing.CRAP001A._maturity, Alaris.Core.Pricing.CRAP001A._rate, Alaris.Core.Pricing.CRAP001A._volatility, Alaris.Core.Pricing.CRAP001A.CalculateLambdaRoots(), and Alaris.Core.Pricing.CRAP001A.SolveBoundaryEquation().
Referenced by Alaris.Core.Pricing.CRAP001A.CalculateBoundaries().
CalculateSingleBoundaryPut()
double Alaris.Core.Pricing.CRAP001A.CalculateSingleBoundaryPut () inline private
Definition at line 136 of file CRAP001A.cs.
References Alaris.Core.Pricing.CRAP001A._dividendYield, Alaris.Core.Pricing.CRAP001A._maturity, Alaris.Core.Pricing.CRAP001A._rate, Alaris.Core.Pricing.CRAP001A._volatility, Alaris.Core.Pricing.CRAP001A.CalculateLambdaRoots(), and Alaris.Core.Pricing.CRAP001A.SolveBoundaryEquation().
Referenced by Alaris.Core.Pricing.CRAP001A.CalculateBoundaries().
EnsureDistanceSteps()
double Alaris.Core.Pricing.CRAP001A.EnsureDistanceSteps (double S) inline private
Definition at line 463 of file CRAP001A.cs.
References Alaris.Core.Pricing.CRAP001A._isCall, and Alaris.Core.Pricing.CRAP001A._strike.
EvaluateBoundaryFunction()
double double double d2f Alaris.Core.Pricing.CRAP001A.EvaluateBoundaryFunction (double S, double lambda, double h) inline private
Definition at line 205 of file CRAP001A.cs.
Referenced by Alaris.Core.Pricing.CRAP001A.SolveBoundaryEquation().
GetGeneralizedInitialGuess()
double Alaris.Core.Pricing.CRAP001A.GetGeneralizedInitialGuess (bool isUpper) inline private
Definition at line 289 of file CRAP001A.cs.
References Alaris.Core.Pricing.CRAP001A._isCall, Alaris.Core.Pricing.CRAP001A._maturity, Alaris.Core.Pricing.CRAP001A._strike, Alaris.Core.Pricing.CRAP001A._volatility, and Alaris.Core.Pricing.CRAP001A.InterpolateBenchmark().
Referenced by Alaris.Core.Pricing.CRAP001A.SolveBoundaryEquation().
InterpolateBenchmark()
double Alaris.Core.Pricing.CRAP001A.InterpolateBenchmark (double T, bool isUpper) inline private
Definition at line 319 of file CRAP001A.cs.
Referenced by Alaris.Core.Pricing.CRAP001A.GetGeneralizedInitialGuess().
NormalCDF()
static double Alaris.Core.Pricing.CRAP001A.NormalCDF (double x) static private
Referenced by Alaris.Core.Pricing.CRAP001A.CalculateBsComponents(), and Alaris.Core.Pricing.CRAP001A.CalculateDc0DS().
NormalPDF()
static double Alaris.Core.Pricing.CRAP001A.NormalPDF (double x) static private
Referenced by Alaris.Core.Pricing.CRAP001A.CalculateBsComponents(), and Alaris.Core.Pricing.CRAP001A.CalculateDc0DS().
SolveBoundaryEquation()
double Alaris.Core.Pricing.CRAP001A.SolveBoundaryEquation (double lambda, double h, bool isUpper) inline private
Definition at line 160 of file CRAP001A.cs.
References Alaris.Core.Pricing.CRAP001A._strike, Alaris.Core.Pricing.CRAP001A.df, Alaris.Core.Pricing.CRAP001A.EvaluateBoundaryFunction(), Alaris.Core.Pricing.CRAP001A.f, Alaris.Core.Pricing.CRAP001A.GetGeneralizedInitialGuess(), Alaris.Core.Pricing.CRAP001A.MaxIterations, Alaris.Core.Pricing.CRAP001A.NumericalEpsilon, Alaris.Core.Pricing.CRAP001A.Tolerance, and Alaris.Core.Pricing.CRAP001A.ValidateRoot().
Referenced by Alaris.Core.Pricing.CRAP001A.CalculateDoubleBoundariesCall(), Alaris.Core.Pricing.CRAP001A.CalculateDoubleBoundariesPut(), Alaris.Core.Pricing.CRAP001A.CalculateSingleBoundaryCall(), and Alaris.Core.Pricing.CRAP001A.CalculateSingleBoundaryPut().
ValidateRoot()
double Alaris.Core.Pricing.CRAP001A.ValidateRoot (double S, double initialGuess) inline private
Definition at line 369 of file CRAP001A.cs.
References Alaris.Core.Pricing.CRAP001A._maturity, and Alaris.Core.Pricing.CRAP001A._strike.
Referenced by Alaris.Core.Pricing.CRAP001A.SolveBoundaryEquation().
Member Data Documentation
_dividendYield
readonly double Alaris.Core.Pricing.CRAP001A._dividendYield private
Definition at line 19 of file CRAP001A.cs.
Referenced by Alaris.Core.Pricing.CRAP001A.CRAP001A(), Alaris.Core.Pricing.CRAP001A.CalculateBoundaries(), Alaris.Core.Pricing.CRAP001A.CalculateBsComponents(), Alaris.Core.Pricing.CRAP001A.CalculateDc0DS(), Alaris.Core.Pricing.CRAP001A.CalculateDoubleBoundariesCall(), Alaris.Core.Pricing.CRAP001A.CalculateDoubleBoundariesPut(), Alaris.Core.Pricing.CRAP001A.CalculateLambdaPrime(), Alaris.Core.Pricing.CRAP001A.CalculateSingleBoundaryCall(), and Alaris.Core.Pricing.CRAP001A.CalculateSingleBoundaryPut().
_isCall
readonly bool Alaris.Core.Pricing.CRAP001A._isCall private
Definition at line 21 of file CRAP001A.cs.
Referenced by Alaris.Core.Pricing.CRAP001A.CRAP001A(), Alaris.Core.Pricing.CRAP001A.ApplyBoundaryConstraints(), Alaris.Core.Pricing.CRAP001A.ApproximateForSmallH(), Alaris.Core.Pricing.CRAP001A.CalculateBoundaries(), Alaris.Core.Pricing.CRAP001A.CalculateBsComponents(), Alaris.Core.Pricing.CRAP001A.CalculateC0(), Alaris.Core.Pricing.CRAP001A.EnsureDistanceSteps(), and Alaris.Core.Pricing.CRAP001A.GetGeneralizedInitialGuess().
_maturity
readonly double Alaris.Core.Pricing.CRAP001A._maturity private
Definition at line 17 of file CRAP001A.cs.
Referenced by Alaris.Core.Pricing.CRAP001A.CRAP001A(), Alaris.Core.Pricing.CRAP001A.ApproximateForSmallH(), Alaris.Core.Pricing.CRAP001A.CalculateBsComponents(), Alaris.Core.Pricing.CRAP001A.CalculateDc0DS(), Alaris.Core.Pricing.CRAP001A.CalculateDoubleBoundariesCall(), Alaris.Core.Pricing.CRAP001A.CalculateDoubleBoundariesPut(), Alaris.Core.Pricing.CRAP001A.CalculateSingleBoundaryCall(), Alaris.Core.Pricing.CRAP001A.CalculateSingleBoundaryPut(), Alaris.Core.Pricing.CRAP001A.GetGeneralizedInitialGuess(), and Alaris.Core.Pricing.CRAP001A.ValidateRoot().
_rate
readonly double Alaris.Core.Pricing.CRAP001A._rate private
Definition at line 18 of file CRAP001A.cs.
Referenced by Alaris.Core.Pricing.CRAP001A.CRAP001A(), Alaris.Core.Pricing.CRAP001A.CalculateBoundaries(), Alaris.Core.Pricing.CRAP001A.CalculateBsComponents(), Alaris.Core.Pricing.CRAP001A.CalculateC0(), Alaris.Core.Pricing.CRAP001A.CalculateDc0DS(), Alaris.Core.Pricing.CRAP001A.CalculateDoubleBoundariesCall(), Alaris.Core.Pricing.CRAP001A.CalculateDoubleBoundariesPut(), Alaris.Core.Pricing.CRAP001A.CalculateLambdaPrime(), Alaris.Core.Pricing.CRAP001A.CalculateLambdaRoots(), Alaris.Core.Pricing.CRAP001A.CalculateSingleBoundaryCall(), and Alaris.Core.Pricing.CRAP001A.CalculateSingleBoundaryPut().
_spot
readonly double Alaris.Core.Pricing.CRAP001A._spot private
Definition at line 15 of file CRAP001A.cs.
Referenced by Alaris.Core.Pricing.CRAP001A.CRAP001A().
_strike
readonly double Alaris.Core.Pricing.CRAP001A._strike private
Definition at line 16 of file CRAP001A.cs.
Referenced by Alaris.Core.Pricing.CRAP001A.CRAP001A(), Alaris.Core.Pricing.CRAP001A.ApplyBoundaryConstraints(), Alaris.Core.Pricing.CRAP001A.ApproximateForSmallH(), Alaris.Core.Pricing.CRAP001A.CalculateBoundaries(), Alaris.Core.Pricing.CRAP001A.CalculateBsComponents(), Alaris.Core.Pricing.CRAP001A.CalculateC0(), Alaris.Core.Pricing.CRAP001A.CalculateDc0DS(), Alaris.Core.Pricing.CRAP001A.EnsureDistanceSteps(), Alaris.Core.Pricing.CRAP001A.GetGeneralizedInitialGuess(), Alaris.Core.Pricing.CRAP001A.SolveBoundaryEquation(), and Alaris.Core.Pricing.CRAP001A.ValidateRoot().
_volatility
readonly double Alaris.Core.Pricing.CRAP001A._volatility private
Definition at line 20 of file CRAP001A.cs.
Referenced by Alaris.Core.Pricing.CRAP001A.CRAP001A(), Alaris.Core.Pricing.CRAP001A.ApproximateForSmallH(), Alaris.Core.Pricing.CRAP001A.CalculateBsComponents(), Alaris.Core.Pricing.CRAP001A.CalculateDoubleBoundariesCall(), Alaris.Core.Pricing.CRAP001A.CalculateDoubleBoundariesPut(), Alaris.Core.Pricing.CRAP001A.CalculateSingleBoundaryCall(), Alaris.Core.Pricing.CRAP001A.CalculateSingleBoundaryPut(), and Alaris.Core.Pricing.CRAP001A.GetGeneralizedInitialGuess().
df
double double Alaris.Core.Pricing.CRAP001A.df private
Definition at line 205 of file CRAP001A.cs.
Referenced by Alaris.Core.Pricing.CRAP001A.SolveBoundaryEquation().
f
double Alaris.Core.Pricing.CRAP001A.f private
Definition at line 205 of file CRAP001A.cs.
Referenced by Alaris.Core.Pricing.CRAP001A.SolveBoundaryEquation().
Lambda1
double Alaris.Core.Pricing.CRAP001A.Lambda1 private
Definition at line 354 of file CRAP001A.cs.
MaxIterations
const int Alaris.Core.Pricing.CRAP001A.MaxIterations = 100 static private
Definition at line 24 of file CRAP001A.cs.
Referenced by Alaris.Core.Pricing.CRAP001A.SolveBoundaryEquation().
NumericalEpsilon
const double Alaris.Core.Pricing.CRAP001A.NumericalEpsilon = 1e-12 static private
Definition at line 25 of file CRAP001A.cs.
Referenced by Alaris.Core.Pricing.CRAP001A.CalculateC0(), Alaris.Core.Pricing.CRAP001A.CalculateDc0DS(), Alaris.Core.Pricing.CRAP001A.CalculateDoubleBoundariesCall(), Alaris.Core.Pricing.CRAP001A.CalculateDoubleBoundariesPut(), Alaris.Core.Pricing.CRAP001A.CalculateLambdaPrime(), and Alaris.Core.Pricing.CRAP001A.SolveBoundaryEquation().
Theta
double double Alaris.Core.Pricing.CRAP001A.Theta private
Definition at line 259 of file CRAP001A.cs.
Tolerance
const double Alaris.Core.Pricing.CRAP001A.Tolerance = 1e-8 static private
Definition at line 23 of file CRAP001A.cs.
Referenced by Alaris.Core.Pricing.CRAP001A.SolveBoundaryEquation().
Upper
double Alaris.Core.Pricing.CRAP001A.Upper
Calculates both upper and lower boundaries using QD+ approximation.
Returns
Initial (Upper, Lower) boundary estimates for Kim solver refinement.
Definition at line 62 of file CRAP001A.cs.
VE
double Alaris.Core.Pricing.CRAP001A.VE private
Definition at line 259 of file CRAP001A.cs.
The documentation for this class was generated from the following file:
src/Alaris.Core/Pricing/CRAP001A.cs