Alaris: Alaris.Strategy.Core.STIV002A Class Reference
Alaris.Strategy.Core.STIV002A Class Reference sealed
Implements the Kou (2002) double-exponential jump-diffusion model for implied volatility. The model extends Black-Scholes with Poisson jumps where jump sizes follow a double-exponential (asymmetric Laplace) distribution, capturing:
Public Member Functions
STIV002A (KouParameters parameters)
double ComputeTheoreticalIV (double spot, double strike, double timeToExpiry)
Computes the theoretical implied volatility at a given strike and time to expiry. PRODUCTION VERSION: Uses full characteristic function integration and Fourier inversion.
double ComputeTheoreticalIVApproximate (double spot, double strike, double timeToExpiry)
Computes theoretical implied volatility using moment-matching approximation. LEGACY VERSION: Fast approximation for educational/comparison purposes. For production use, prefer ComputeTheoreticalIV() which uses full pricing.
int double TheoreticalIV[] ComputeSTTM001A (double spot, double strike, int[] dtePoints)
double double TheoreticalIV[] ComputeSmile (double spot, double[] strikes, double timeToExpiry)
Static Public Member Functions
static KouParameters Calibrate (double spot, IReadOnlyList<(double Strike, int DTE, double MarketIV)> marketData, double riskFreeRate, double dividendYield)
Calibrates Kou parameters from market IV surface using Differential Evolution. PRODUCTION VERSION: Uses global optimization to handle non-convex parameter space. Differential Evolution is particularly effective for jump-diffusion models due to their multi-modal error surfaces.
Public Attributes
int DTE
Computes the IV term structure for a given moneyness level.
double Strike
Computes the IV smile across strikes at a given expiry.
Private Member Functions
double ComputeJumpVariance (double timeToExpiry)
Computes variance contribution from jumps.
double ComputeSkewAdjustment (double logMoneyness, double timeToExpiry)
Computes skew adjustment based on moneyness. Captures the asymmetric jump distribution's effect on IV smile.
double ComputeJumpSkewness ()
Computes skewness of the jump distribution.
Static Private Member Functions
static KouParameters CalibrateGridSearch (double spot, IReadOnlyList<(double Strike, int DTE, double MarketIV)> marketData, double riskFreeRate, double dividendYield)
Calibrates Kou parameters using grid search. LEGACY VERSION: Used as fallback when Differential Evolution fails. For production, prefer Calibrate() which uses Differential Evolution.
static double ComputeCalibrationError (STIV002A model, double spot, IReadOnlyList<(double Strike, int DTE, double MarketIV)> marketData)
static void ValidateInputs (double spot, double strike, double timeToExpiry)
Private Attributes
readonly KouParameters _params
Detailed Description
Implements the Kou (2002) double-exponential jump-diffusion model for implied volatility. The model extends Black-Scholes with Poisson jumps where jump sizes follow a double-exponential (asymmetric Laplace) distribution, capturing:
Asymmetric jump sizes (upward vs downward moves)
Leptokurtic returns (fat tails)
Implied volatility skew Stock price dynamics under risk-neutral measure Q: dS/S = (r - d - lambda*kappa)dt + sigma*dW + d(sum(V_i - 1)) Where: sigma = diffusion volatility lambda = jump intensity (jumps per year) V_i = jump multiplier with double-exponential distribution kappa = E[V-1] = p*eta1/(eta1-1) + (1-p)*eta2/(eta2+1) - 1 The (r - d - lambda*kappa) drift ensures the martingale condition. Reference: "A Jump-Diffusion Model for Option Pricing" S.G. Kou (2002), Management Science
Definition at line 143 of file STIV002A.cs.
Constructor & Destructor Documentation
STIV002A()
Alaris.Strategy.Core.STIV002A.STIV002A (KouParameters parameters) inline
Definition at line 147 of file STIV002A.cs.
References Alaris.Strategy.Core.STIV002A._params, Alaris.Strategy.Core.ValidationResult.ThrowIfInvalid(), and Alaris.Strategy.Core.KouParameters.Validate().
Member Function Documentation
Calibrate()
static KouParameters Alaris.Strategy.Core.STIV002A.Calibrate (double spot, IReadOnlyList<(double Strike, int DTE, double MarketIV)> marketData, double riskFreeRate, double dividendYield) inline static
Calibrates Kou parameters from market IV surface using Differential Evolution. PRODUCTION VERSION: Uses global optimization to handle non-convex parameter space. Differential Evolution is particularly effective for jump-diffusion models due to their multi-modal error surfaces.
Parameters
spot Current spot price.
marketData Market IV observations (strike, dte, iv).
riskFreeRate Risk-free rate.
dividendYield Dividend yield.
Returns
Calibrated parameters.
Definition at line 338 of file STIV002A.cs.
References Alaris.Strategy.Core.STIV002A.CalibrateGridSearch(), Alaris.Strategy.Core.STIV002A.ComputeTheoreticalIV(), Alaris.Strategy.Core.Numerical.OptimizationResult.Converged, Alaris.Strategy.Calendar.TradingCalendarDefaults.DteToYears(), Alaris.Strategy.Core.ValidationResult.IsValid, Alaris.Strategy.Core.Numerical.OptimizationResult.OptimalParameters, Alaris.Strategy.Core.Numerical.OptimizationResult.OptimalValue, and Alaris.Strategy.Core.KouParameters.Validate().
CalibrateGridSearch()
static KouParameters Alaris.Strategy.Core.STIV002A.CalibrateGridSearch (double spot, IReadOnlyList<(double Strike, int DTE, double MarketIV)> marketData, double riskFreeRate, double dividendYield) inline static private
Calibrates Kou parameters using grid search. LEGACY VERSION: Used as fallback when Differential Evolution fails. For production, prefer Calibrate() which uses Differential Evolution.
Definition at line 442 of file STIV002A.cs.
References Alaris.Strategy.Core.STIV002A.ComputeCalibrationError(), Alaris.Strategy.Core.KouParameters.DefaultEquity, Alaris.Strategy.Core.ValidationResult.IsValid, and Alaris.Strategy.Core.KouParameters.Validate().
Referenced by Alaris.Strategy.Core.STIV002A.Calibrate().
ComputeCalibrationError()
static double Alaris.Strategy.Core.STIV002A.ComputeCalibrationError (STIV002A model, double spot, IReadOnlyList<(double Strike, int DTE, double MarketIV)> marketData) inline static private
Definition at line 501 of file STIV002A.cs.
References Alaris.Strategy.Core.STIV002A.ComputeTheoreticalIV(), and Alaris.Strategy.Calendar.TradingCalendarDefaults.DteToYears().
Referenced by Alaris.Strategy.Core.STIV002A.CalibrateGridSearch().
ComputeJumpSkewness()
double Alaris.Strategy.Core.STIV002A.ComputeJumpSkewness () inline private
Computes skewness of the jump distribution.
Definition at line 253 of file STIV002A.cs.
References Alaris.Strategy.Core.STIV002A._params, Alaris.Strategy.Core.KouParameters.Eta1, Alaris.Strategy.Core.KouParameters.Eta2, and Alaris.Strategy.Core.KouParameters.P.
Referenced by Alaris.Strategy.Core.STIV002A.ComputeSkewAdjustment().
ComputeJumpVariance()
double Alaris.Strategy.Core.STIV002A.ComputeJumpVariance (double timeToExpiry) inline private
Computes variance contribution from jumps.
Definition at line 207 of file STIV002A.cs.
References Alaris.Strategy.Core.STIV002A._params, Alaris.Strategy.Core.KouParameters.Eta1, Alaris.Strategy.Core.KouParameters.Eta2, Alaris.Strategy.Core.KouParameters.Lambda, and Alaris.Strategy.Core.KouParameters.P.
Referenced by Alaris.Strategy.Core.STIV002A.ComputeTheoreticalIVApproximate().
ComputeSkewAdjustment()
double Alaris.Strategy.Core.STIV002A.ComputeSkewAdjustment (double logMoneyness, double timeToExpiry) inline private
Computes skew adjustment based on moneyness. Captures the asymmetric jump distribution's effect on IV smile.
Definition at line 233 of file STIV002A.cs.
References Alaris.Strategy.Core.STIV002A._params, Alaris.Strategy.Core.STIV002A.ComputeJumpSkewness(), and Alaris.Strategy.Core.KouParameters.Lambda.
Referenced by Alaris.Strategy.Core.STIV002A.ComputeTheoreticalIVApproximate().
ComputeSmile()
double double TheoreticalIV[] Alaris.Strategy.Core.STIV002A.ComputeSmile (double spot, double[] strikes, double timeToExpiry) inline
Definition at line 310 of file STIV002A.cs.
References Alaris.Strategy.Core.STIV002A.ComputeTheoreticalIV(), and Alaris.Strategy.Core.STIV002A.Strike.
ComputeSTTM001A()
int double TheoreticalIV[] Alaris.Strategy.Core.STIV002A.ComputeSTTM001A (double spot, double strike, int[] dtePoints) inline
Definition at line 278 of file STIV002A.cs.
References Alaris.Strategy.Core.STIV002A._params, Alaris.Strategy.Core.STIV002A.ComputeTheoreticalIV(), Alaris.Strategy.Core.STIV002A.DTE, Alaris.Strategy.Calendar.TradingCalendarDefaults.DteToYears(), and Alaris.Strategy.Core.KouParameters.Sigma.
ComputeTheoreticalIV()
double Alaris.Strategy.Core.STIV002A.ComputeTheoreticalIV (double spot, double strike, double timeToExpiry) inline
Computes the theoretical implied volatility at a given strike and time to expiry. PRODUCTION VERSION: Uses full characteristic function integration and Fourier inversion.
Parameters
spot Current spot price.
strike Strike price.
timeToExpiry Time to expiry in years.
Returns
Implied volatility from Kou model.
Definition at line 162 of file STIV002A.cs.
References Alaris.Strategy.Core.STIV002A._params, Alaris.Strategy.Core.STPR006A.ComputeImpliedVolatility(), and Alaris.Strategy.Core.STIV002A.ValidateInputs().
Referenced by Alaris.Strategy.Core.STIV002A.Calibrate(), Alaris.Strategy.Core.STIV002A.ComputeCalibrationError(), Alaris.Strategy.Core.STIV003A.ComputeModelIVs(), Alaris.Strategy.Core.STIV002A.ComputeSmile(), and Alaris.Strategy.Core.STIV002A.ComputeSTTM001A().
ComputeTheoreticalIVApproximate()
double Alaris.Strategy.Core.STIV002A.ComputeTheoreticalIVApproximate (double spot, double strike, double timeToExpiry) inline
Computes theoretical implied volatility using moment-matching approximation. LEGACY VERSION: Fast approximation for educational/comparison purposes. For production use, prefer ComputeTheoreticalIV() which uses full pricing.
Parameters
spot Current spot price.
strike Strike price.
timeToExpiry Time to expiry in years.
Returns
Approximate implied volatility.
Definition at line 179 of file STIV002A.cs.
References Alaris.Strategy.Core.STIV002A.ComputeJumpVariance(), Alaris.Strategy.Core.STIV002A.ComputeSkewAdjustment(), and Alaris.Strategy.Core.STIV002A.ValidateInputs().
ValidateInputs()
static void Alaris.Strategy.Core.STIV002A.ValidateInputs (double spot, double strike, double timeToExpiry) inline static private
Definition at line 519 of file STIV002A.cs.
Referenced by Alaris.Strategy.Core.STIV002A.ComputeTheoreticalIV(), and Alaris.Strategy.Core.STIV002A.ComputeTheoreticalIVApproximate().
Member Data Documentation
_params
readonly KouParameters Alaris.Strategy.Core.STIV002A._params private
Definition at line 145 of file STIV002A.cs.
Referenced by Alaris.Strategy.Core.STIV002A.STIV002A(), Alaris.Strategy.Core.STIV002A.ComputeJumpSkewness(), Alaris.Strategy.Core.STIV002A.ComputeJumpVariance(), Alaris.Strategy.Core.STIV002A.ComputeSkewAdjustment(), Alaris.Strategy.Core.STIV002A.ComputeSTTM001A(), and Alaris.Strategy.Core.STIV002A.ComputeTheoreticalIV().
DTE
int Alaris.Strategy.Core.STIV002A.DTE
Computes the IV term structure for a given moneyness level.
Parameters
spot Current spot price.
strike Strike price.
dtePoints Array of days-to-expiry points.
Returns
Array of (DTE, TheoreticalIV) tuples.
Definition at line 278 of file STIV002A.cs.
Referenced by Alaris.Strategy.Core.STIV002A.ComputeSTTM001A().
Strike
double Alaris.Strategy.Core.STIV002A.Strike
Computes the IV smile across strikes at a given expiry.
Parameters
spot Current spot price.
strikes Array of strike prices.
timeToExpiry Time to expiry in years.
Returns
Array of (Strike, TheoreticalIV) tuples.
Definition at line 310 of file STIV002A.cs.
Referenced by Alaris.Strategy.Core.STIV002A.ComputeSmile().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Core/STIV002A.cs