Alaris: Alaris.Strategy.Core.STTM001A Class Reference
Alaris.Strategy.Core.STTM001A Class Reference sealed
Analyzes the term structure of implied volatility. Used to identify inverted term structures that signal trading opportunities.
Public Member Functions
STTM001AAnalysis Analyze (IReadOnlyList< STTM001APoint > points)
Analyzes a set of term structure points and calculates slope/intercept.
Static Private Member Functions
static double CalculateRSquaredOptimized (ReadOnlySpan< double > x, ReadOnlySpan< double > y, double intercept, double slope)
Calculates R-squared for the linear fit using Span (zero allocation).
Detailed Description
Analyzes the term structure of implied volatility. Used to identify inverted term structures that signal trading opportunities.
Definition at line 14 of file STTM001A.cs.
Member Function Documentation
Analyze()
STTM001AAnalysis Alaris.Strategy.Core.STTM001A.Analyze (IReadOnlyList< STTM001APoint > points) inline
Analyzes a set of term structure points and calculates slope/intercept.
Definition at line 19 of file STTM001A.cs.
References Alaris.Strategy.Core.STTM001A.CalculateRSquaredOptimized(), and Alaris.Strategy.Core.STTM001AAnalysis.Points.
Referenced by Alaris.Strategy.Core.STCR001A.CalculateSTCR004AMetrics(), and Alaris.Algorithm.STLN001A.EvaluateSnapshot().
CalculateRSquaredOptimized()
static double Alaris.Strategy.Core.STTM001A.CalculateRSquaredOptimized (ReadOnlySpan< double > x, ReadOnlySpan< double > y, double intercept, double slope) inline static private
Calculates R-squared for the linear fit using Span (zero allocation).
Definition at line 89 of file STTM001A.cs.
Referenced by Alaris.Strategy.Core.STTM001A.Analyze().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Core/STTM001A.cs