Alaris: Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient Class Reference
Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient Class Reference sealed
Polygon.io REST API client for market data retrieval. Component ID: DTpr001A.
Public Member Functions
PolygonApiClient (IPolygonApi api, IConfiguration configuration, ILogger< PolygonApiClient > logger)
async Task< IReadOnlyList< PriceBar > > GetHistoricalBarsAsync (string symbol, DateTime startDate, DateTime endDate, CancellationToken cancellationToken=default)
Gets historical OHLCV bars for a symbol.
Task< OptionChainSnapshot > GetOptionChainAsync (string symbol, DateTime? asOfDate=null, CancellationToken cancellationToken=default)
Gets the current options chain for a symbol.
async Task< OptionChainSnapshot > GetHistoricalOptionChainAsync (string symbol, DateTime asOfDate, CancellationToken cancellationToken=default)
Gets historical option chain for backtesting. NOTE: Polygon does NOT provide historical Greeks/IV via API. This method calculates IV from historical option prices using Black-Scholes, which is the industry-standard approach for backtesting.
async Task< decimal > GetSpotPriceAsync (string symbol, CancellationToken cancellationToken=default)
Gets the current spot price for a symbol.
async Task< decimal > GetAverageVolume30DayAsync (string symbol, DateTime? evaluationDate=null, CancellationToken cancellationToken=default)
Gets 30-day average volume for a symbol.
Parameters
symbol The symbol to query.
evaluationDate Optional evaluation date (use LEAN's Time for backtests, null for live trading).
cancellationToken Cancellation token.
Static Private Member Functions
static string decimal DateTime OptionRight right ParseOptionTicker (string ticker)
Private Attributes
readonly IPolygonApi _api
readonly ILogger< PolygonApiClient > _logger
readonly string _apiKey
Static Private Attributes
static string underlying
static string decimal strike
static string decimal DateTime expiration
Detailed Description
Polygon.io REST API client for market data retrieval. Component ID: DTpr001A.
Implements DTpr003A (Market Data Provider interface) using Polygon.io API via Refit declarative interface (IPolygonApi).
Note: Polygon does NOT provide historical Greeks/IV via API. This provider calculates IV from historical option prices using Black-Scholes, which is the industry-standard approach for backtesting.
Resilience provided by Microsoft.Extensions.Http.Resilience standard handler.
Definition at line 36 of file DTpr001A.cs.
Constructor & Destructor Documentation
PolygonApiClient()
Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.PolygonApiClient (IPolygonApi api, IConfiguration configuration, ILogger< PolygonApiClient > logger) inline
Definition at line 42 of file DTpr001A.cs.
References Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient._api, Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient._apiKey, and Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient._logger.
Member Function Documentation
GetAverageVolume30DayAsync()
async Task< decimal > Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetAverageVolume30DayAsync (string symbol, DateTime? evaluationDate = null, CancellationToken cancellationToken = default) inline
Gets 30-day average volume for a symbol.
Parameters
symbol The symbol to query.
evaluationDate Optional evaluation date (use LEAN's Time for backtests, null for live trading).
cancellationToken Cancellation token.
Implements Alaris.Infrastructure.Data.Provider.DTpr003A.
Definition at line 326 of file DTpr001A.cs.
References Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetHistoricalBarsAsync().
GetHistoricalBarsAsync()
async Task< IReadOnlyList< PriceBar > > Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetHistoricalBarsAsync (string symbol, DateTime startDate, DateTime endDate, CancellationToken cancellationToken = default) inline
Gets historical OHLCV bars for a symbol.
Implements Alaris.Infrastructure.Data.Provider.DTpr003A.
Definition at line 58 of file DTpr001A.cs.
References Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient._api, Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient._apiKey, Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient._logger, Alaris.Infrastructure.Data.Http.Contracts.IPolygonApi.GetDailyBarsAsync(), and Alaris.Infrastructure.Data.Http.Contracts.PolygonAggregatesResponse.Results.
Referenced by Alaris.Host.Application.Service.APsv002A.DownloadEquityDataAsync(), Alaris.Host.Application.Service.APsv002A.DownloadPriceDataWithBenchmarkAsync(), Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetAverageVolume30DayAsync(), and Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetHistoricalOptionChainAsync().
GetHistoricalOptionChainAsync()
async Task< OptionChainSnapshot > Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetHistoricalOptionChainAsync (string symbol, DateTime asOfDate, CancellationToken cancellationToken = default) inline
Gets historical option chain for backtesting. NOTE: Polygon does NOT provide historical Greeks/IV via API. This method calculates IV from historical option prices using Black-Scholes, which is the industry-standard approach for backtesting.
Definition at line 134 of file DTpr001A.cs.
References Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient._api, Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient._apiKey, Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient._logger, Alaris.Core.Math.CRMF001A.BSImpliedVolatility(), Alaris.Infrastructure.Data.Http.Contracts.PolygonBar.Close, Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.expiration, Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetHistoricalBarsAsync(), Alaris.Infrastructure.Data.Http.Contracts.IPolygonApi.GetOptionsContractsAsync(), Alaris.Infrastructure.Data.Http.Contracts.IPolygonApi.GetTickerAggregatesAsync(), Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.ParseOptionTicker(), Alaris.Infrastructure.Data.Http.Contracts.PolygonAggregatesResponse.Results, Alaris.Infrastructure.Data.Http.Contracts.PolygonOptionsContractsResponse.Results, Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.strike, Alaris.Infrastructure.Data.Http.Contracts.PolygonBar.Timestamp, Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.underlying, and Alaris.Infrastructure.Data.Http.Contracts.PolygonBar.Volume.
Referenced by Alaris.Host.Application.Service.APsv002A.BootstrapOptionsDataAsync(), Alaris.Host.Application.Service.APsv002A.DownloadEquityDataAsync(), and Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetOptionChainAsync().
GetOptionChainAsync()
Task< OptionChainSnapshot > Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetOptionChainAsync (string symbol, DateTime? asOfDate = null, CancellationToken cancellationToken = default) inline
Gets the current options chain for a symbol.
Implements Alaris.Infrastructure.Data.Provider.DTpr003A.
Definition at line 120 of file DTpr001A.cs.
References Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetHistoricalOptionChainAsync().
GetSpotPriceAsync()
async Task< decimal > Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetSpotPriceAsync (string symbol, CancellationToken cancellationToken = default) inline
Gets the current spot price for a symbol.
Implements Alaris.Infrastructure.Data.Provider.DTpr003A.
Definition at line 295 of file DTpr001A.cs.
References Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient._api, Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient._apiKey, Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient._logger, Alaris.Infrastructure.Data.Http.Contracts.PolygonBar.Close, Alaris.Infrastructure.Data.Http.Contracts.IPolygonApi.GetPreviousDayAsync(), and Alaris.Infrastructure.Data.Http.Contracts.PolygonAggregatesResponse.Results.
ParseOptionTicker()
static string decimal DateTime OptionRight right Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.ParseOptionTicker (string ticker) inline static private
Definition at line 348 of file DTpr001A.cs.
References Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.expiration, Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.strike, and Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.underlying.
Referenced by Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetHistoricalOptionChainAsync().
Member Data Documentation
_api
readonly IPolygonApi Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient._api private
Definition at line 38 of file DTpr001A.cs.
Referenced by Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.PolygonApiClient(), Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetHistoricalBarsAsync(), Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetHistoricalOptionChainAsync(), and Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetSpotPriceAsync().
_apiKey
readonly string Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient._apiKey private
Definition at line 40 of file DTpr001A.cs.
Referenced by Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.PolygonApiClient(), Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetHistoricalBarsAsync(), Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetHistoricalOptionChainAsync(), and Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetSpotPriceAsync().
_logger
readonly ILogger<PolygonApiClient> Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient._logger private
Definition at line 39 of file DTpr001A.cs.
Referenced by Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.PolygonApiClient(), Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetHistoricalBarsAsync(), Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetHistoricalOptionChainAsync(), and Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetSpotPriceAsync().
expiration
string decimal DateTime Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.expiration static private
Definition at line 347 of file DTpr001A.cs.
Referenced by Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetHistoricalOptionChainAsync(), and Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.ParseOptionTicker().
strike
string decimal Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.strike static private
Definition at line 347 of file DTpr001A.cs.
Referenced by Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetHistoricalOptionChainAsync(), and Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.ParseOptionTicker().
underlying
string Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.underlying static private
Definition at line 347 of file DTpr001A.cs.
Referenced by Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetHistoricalOptionChainAsync(), and Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.ParseOptionTicker().
The documentation for this class was generated from the following file:
src/Alaris.Infrastructure/Data/Provider/DTpr001A.cs