Alaris: Alaris.Strategy.Hedge.STHD009A Class Reference
Alaris.Strategy.Hedge.STHD009A Class Reference sealed
Monitors pin risk for options near expiry when underlying is close to strike.
Public Member Functions
STHD009A (ILogger< STHD009A >? logger=null)
Initialises a new instance of the pin risk monitor.
STHD010A Evaluate (double spotPrice, double strike, int daysToExpiry, double? gamma, int contracts)
Evaluates pin risk for a position.
Static Public Member Functions
static double CalculateMoneynessDeviation (double spotPrice, double strike)
Calculates how far the underlying is from the strike (moneyness deviation).
static bool IsInPinZone (double spotPrice, double strike)
Determines if the position is in the pin zone.
Static Public Attributes
const double PinZoneThreshold = 0.01
Pin zone threshold (fraction of strike). Position is "pinned" if |S - K| / K < this value.
const int MinDaysForPinRisk = 3
Days to expiry below which pin risk becomes significant.
Private Member Functions
void SafeLog (Action logAction)
Safely executes logging operation with fault isolation.
Static Private Member Functions
static double EstimateAtmGamma (double spotPrice, int daysToExpiry)
Estimates ATM gamma near expiry (simplified approximation).
static string GenerateRationale (STHD011A riskLevel, double deviation, int dte)
Generates human-readable rationale.
Private Attributes
readonly? ILogger< STHD009A > _logger
Static Private Attributes
static readonly Action< ILogger, double, int, string, Exception?> LogPinRiskDetected
Detailed Description
Monitors pin risk for options near expiry when underlying is close to strike.
Definition at line 12 of file STHD009A.cs.
Constructor & Destructor Documentation
STHD009A()
Alaris.Strategy.Hedge.STHD009A.STHD009A (ILogger< STHD009A >? logger = null) inline
Initialises a new instance of the pin risk monitor.
Parameters
logger Optional logger instance.
Definition at line 38 of file STHD009A.cs.
References Alaris.Strategy.Hedge.STHD009A._logger.
Member Function Documentation
CalculateMoneynessDeviation()
static double Alaris.Strategy.Hedge.STHD009A.CalculateMoneynessDeviation (double spotPrice, double strike) inline static
Calculates how far the underlying is from the strike (moneyness deviation).
Parameters
spotPrice Current spot price.
strike Strike price.
Returns
Absolute deviation as fraction of strike.
Definition at line 49 of file STHD009A.cs.
Referenced by Alaris.Strategy.Hedge.STHD009A.Evaluate(), and Alaris.Strategy.Hedge.STHD009A.IsInPinZone().
EstimateAtmGamma()
static double Alaris.Strategy.Hedge.STHD009A.EstimateAtmGamma (double spotPrice, int daysToExpiry) inline static private
Estimates ATM gamma near expiry (simplified approximation).
Definition at line 163 of file STHD009A.cs.
References Alaris.Strategy.Calendar.TradingCalendarDefaults.DteToYears().
Referenced by Alaris.Strategy.Hedge.STHD009A.Evaluate().
Evaluate()
STHD010A Alaris.Strategy.Hedge.STHD009A.Evaluate (double spotPrice, double strike, int daysToExpiry, double? gamma, int contracts) inline
Evaluates pin risk for a position.
Parameters
spotPrice Current spot price.
strike Strike price.
daysToExpiry Days until expiration.
gamma Position gamma (optional, estimated if not provided).
contracts Number of contracts.
Returns
Pin risk evaluation result.
Definition at line 77 of file STHD009A.cs.
References Alaris.Strategy.Hedge.STHD009A._logger, Alaris.Strategy.Hedge.STHD009A.CalculateMoneynessDeviation(), Alaris.Strategy.Hedge.STHD009A.EstimateAtmGamma(), Alaris.Strategy.Hedge.STHD009A.GenerateRationale(), Alaris.Strategy.Hedge.STHD009A.IsInPinZone(), Alaris.Strategy.Hedge.STHD009A.LogPinRiskDetected, Alaris.Strategy.Hedge.STHD009A.MinDaysForPinRisk, Alaris.Strategy.Hedge.STHD009A.PinZoneThreshold, Alaris.Strategy.Hedge.STHD009A.SafeLog(), and Alaris.Strategy.Hedge.STHD010A.
Referenced by Alaris.Test.Unit.Phase2MediumPriorityTests.STHD009A_Evaluate_FarFromExpiry_ReturnsLowRisk(), and Alaris.Test.Unit.Phase2MediumPriorityTests.STHD009A_Evaluate_HighPinRisk_RecommendsAction().
GenerateRationale()
static string Alaris.Strategy.Hedge.STHD009A.GenerateRationale (STHD011A riskLevel, double deviation, int dte) inline static private
Generates human-readable rationale.
Definition at line 181 of file STHD009A.cs.
Referenced by Alaris.Strategy.Hedge.STHD009A.Evaluate().
IsInPinZone()
static bool Alaris.Strategy.Hedge.STHD009A.IsInPinZone (double spotPrice, double strike) inline static
Determines if the position is in the pin zone.
Parameters
spotPrice Current spot price.
strike Strike price.
Returns
True if within pin zone threshold.
Definition at line 63 of file STHD009A.cs.
References Alaris.Strategy.Hedge.STHD009A.CalculateMoneynessDeviation(), and Alaris.Strategy.Hedge.STHD009A.PinZoneThreshold.
Referenced by Alaris.Strategy.Hedge.STHD009A.Evaluate(), Alaris.Test.Unit.Phase2MediumPriorityTests.STHD009A_IsInPinZone_AtStrike_ReturnsTrue(), and Alaris.Test.Unit.Phase2MediumPriorityTests.STHD009A_IsInPinZone_FarFromStrike_ReturnsFalse().
SafeLog()
void Alaris.Strategy.Hedge.STHD009A.SafeLog (Action logAction) inline private
Safely executes logging operation with fault isolation.
Definition at line 197 of file STHD009A.cs.
References Alaris.Strategy.Hedge.STHD009A._logger.
Referenced by Alaris.Strategy.Hedge.STHD009A.Evaluate().
Member Data Documentation
_logger
readonly? ILogger<STHD009A> Alaris.Strategy.Hedge.STHD009A._logger private
Definition at line 14 of file STHD009A.cs.
Referenced by Alaris.Strategy.Hedge.STHD009A.STHD009A(), Alaris.Strategy.Hedge.STHD009A.Evaluate(), and Alaris.Strategy.Hedge.STHD009A.SafeLog().
LogPinRiskDetected
readonly Action<ILogger, double, int, string, Exception?> Alaris.Strategy.Hedge.STHD009A.LogPinRiskDetected static private
Initial value:
=
        LoggerMessage.Define<double, int, string>(
            LogLevel.Warning,
            new EventId(1, nameof(LogPinRiskDetected)),
            "Pin risk detected: moneyness={Moneyness:P2}, DTE={DaysToExpiry}, action={Action}")
Definition at line 28 of file STHD009A.cs.
Referenced by Alaris.Strategy.Hedge.STHD009A.Evaluate().
MinDaysForPinRisk
const int Alaris.Strategy.Hedge.STHD009A.MinDaysForPinRisk = 3 static
Days to expiry below which pin risk becomes significant.
Definition at line 25 of file STHD009A.cs.
Referenced by Alaris.Strategy.Hedge.STHD009A.Evaluate().
PinZoneThreshold
const double Alaris.Strategy.Hedge.STHD009A.PinZoneThreshold = 0.01 static
Pin zone threshold (fraction of strike). Position is "pinned" if |S - K| / K < this value.
Definition at line 20 of file STHD009A.cs.
Referenced by Alaris.Strategy.Hedge.STHD009A.Evaluate(), and Alaris.Strategy.Hedge.STHD009A.IsInPinZone().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Hedge/STHD009A.cs