Alaris: Alaris.Test.Unit.Phase2MediumPriorityTests Class Reference
Alaris.Test.Unit.Phase2MediumPriorityTests Class Reference sealed
Unit tests for Phase 2 Medium/Lower priority components.
Public Member Functions
void STDD001A_FindExDatesInWindow_ReturnsMatchingDates ()
void STDD001A_CalculateEarlyExerciseRisk_HighDividend_ReturnsHighRisk ()
void STDD001A_CalculateEarlyExerciseRisk_NoDividend_ReturnsZero ()
void STHD009A_IsInPinZone_AtStrike_ReturnsTrue ()
void STHD009A_IsInPinZone_FarFromStrike_ReturnsFalse ()
void STHD009A_Evaluate_HighPinRisk_RecommendsAction ()
void STHD009A_Evaluate_FarFromExpiry_ReturnsLowRisk ()
void STCR005A_CalculateFreshness_JustGenerated_ReturnsOne ()
void STCR005A_CalculateFreshness_AtHalfLife_ReturnsHalf ()
void STCR005A_RequiresRevalidation_StaleSignal_ReturnsTrue ()
void STHD001A_GetConditionalCorrelationThreshold_LowVIX_ReturnsBase ()
void STHD001A_GetConditionalCorrelationThreshold_HighVIX_ReturnsHigher ()
void STRK001A_CalculateNetOfCostKelly_NoCost_ReturnsStandardKelly ()
void STRK001A_CalculateNetOfCostKelly_HighCost_ReturnsReduced ()
void STRK001A_CalculateNetOfCostKelly_CostsExceedEdge_ReturnsZero ()
Detailed Description
Unit tests for Phase 2 Medium/Lower priority components.
Definition at line 14 of file TSUN017A.cs.
Member Function Documentation
STCR005A_CalculateFreshness_AtHalfLife_ReturnsHalf()
void Alaris.Test.Unit.Phase2MediumPriorityTests.STCR005A_CalculateFreshness_AtHalfLife_ReturnsHalf () inline
Definition at line 143 of file TSUN017A.cs.
References Alaris.Strategy.Core.STCR005A.CalculateFreshness().
STCR005A_CalculateFreshness_JustGenerated_ReturnsOne()
void Alaris.Test.Unit.Phase2MediumPriorityTests.STCR005A_CalculateFreshness_JustGenerated_ReturnsOne () inline
Definition at line 129 of file TSUN017A.cs.
References Alaris.Strategy.Core.STCR005A.CalculateFreshness().
STCR005A_RequiresRevalidation_StaleSignal_ReturnsTrue()
void Alaris.Test.Unit.Phase2MediumPriorityTests.STCR005A_RequiresRevalidation_StaleSignal_ReturnsTrue () inline
Definition at line 157 of file TSUN017A.cs.
References Alaris.Strategy.Core.STCR005A.RequiresRevalidation().
STDD001A_CalculateEarlyExerciseRisk_HighDividend_ReturnsHighRisk()
void Alaris.Test.Unit.Phase2MediumPriorityTests.STDD001A_CalculateEarlyExerciseRisk_HighDividend_ReturnsHighRisk () inline
Definition at line 42 of file TSUN017A.cs.
References Alaris.Strategy.Core.STDD001A.CalculateEarlyExerciseRisk().
STDD001A_CalculateEarlyExerciseRisk_NoDividend_ReturnsZero()
void Alaris.Test.Unit.Phase2MediumPriorityTests.STDD001A_CalculateEarlyExerciseRisk_NoDividend_ReturnsZero () inline
Definition at line 59 of file TSUN017A.cs.
References Alaris.Strategy.Core.STDD001A.CalculateEarlyExerciseRisk().
STDD001A_FindExDatesInWindow_ReturnsMatchingDates()
void Alaris.Test.Unit.Phase2MediumPriorityTests.STDD001A_FindExDatesInWindow_ReturnsMatchingDates () inline
Definition at line 19 of file TSUN017A.cs.
References Alaris.Strategy.Core.STDD001A.FindExDatesInWindow(), and Alaris.Strategy.Core.STDD002A.
STHD001A_GetConditionalCorrelationThreshold_HighVIX_ReturnsHigher()
void Alaris.Test.Unit.Phase2MediumPriorityTests.STHD001A_GetConditionalCorrelationThreshold_HighVIX_ReturnsHigher () inline
Definition at line 183 of file TSUN017A.cs.
References Alaris.Strategy.Hedge.STHD001A.GetConditionalCorrelationThreshold().
STHD001A_GetConditionalCorrelationThreshold_LowVIX_ReturnsBase()
void Alaris.Test.Unit.Phase2MediumPriorityTests.STHD001A_GetConditionalCorrelationThreshold_LowVIX_ReturnsBase () inline
Definition at line 173 of file TSUN017A.cs.
References Alaris.Strategy.Hedge.STHD001A.GetConditionalCorrelationThreshold().
STHD009A_Evaluate_FarFromExpiry_ReturnsLowRisk()
void Alaris.Test.Unit.Phase2MediumPriorityTests.STHD009A_Evaluate_FarFromExpiry_ReturnsLowRisk () inline
Definition at line 112 of file TSUN017A.cs.
References Alaris.Strategy.Hedge.STHD009A.Evaluate(), and Alaris.Strategy.Hedge.STHD010A.
STHD009A_Evaluate_HighPinRisk_RecommendsAction()
void Alaris.Test.Unit.Phase2MediumPriorityTests.STHD009A_Evaluate_HighPinRisk_RecommendsAction () inline
Definition at line 96 of file TSUN017A.cs.
References Alaris.Strategy.Hedge.STHD009A.Evaluate(), and Alaris.Strategy.Hedge.STHD010A.
STHD009A_IsInPinZone_AtStrike_ReturnsTrue()
void Alaris.Test.Unit.Phase2MediumPriorityTests.STHD009A_IsInPinZone_AtStrike_ReturnsTrue () inline
Definition at line 76 of file TSUN017A.cs.
References Alaris.Strategy.Hedge.STHD009A.IsInPinZone().
STHD009A_IsInPinZone_FarFromStrike_ReturnsFalse()
void Alaris.Test.Unit.Phase2MediumPriorityTests.STHD009A_IsInPinZone_FarFromStrike_ReturnsFalse () inline
Definition at line 86 of file TSUN017A.cs.
References Alaris.Strategy.Hedge.STHD009A.IsInPinZone().
STRK001A_CalculateNetOfCostKelly_CostsExceedEdge_ReturnsZero()
void Alaris.Test.Unit.Phase2MediumPriorityTests.STRK001A_CalculateNetOfCostKelly_CostsExceedEdge_ReturnsZero () inline
Definition at line 229 of file TSUN017A.cs.
References Alaris.Strategy.Risk.STRK001A.CalculateNetOfCostKelly().
STRK001A_CalculateNetOfCostKelly_HighCost_ReturnsReduced()
void Alaris.Test.Unit.Phase2MediumPriorityTests.STRK001A_CalculateNetOfCostKelly_HighCost_ReturnsReduced () inline
Definition at line 213 of file TSUN017A.cs.
References Alaris.Strategy.Risk.STRK001A.CalculateNetOfCostKelly().
STRK001A_CalculateNetOfCostKelly_NoCost_ReturnsStandardKelly()
void Alaris.Test.Unit.Phase2MediumPriorityTests.STRK001A_CalculateNetOfCostKelly_NoCost_ReturnsStandardKelly () inline
Definition at line 195 of file TSUN017A.cs.
References Alaris.Strategy.Risk.STRK001A.CalculateNetOfCostKelly().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN017A.cs