Alaris: Alaris.Test.Unit.TSUN051A Class Reference
Alaris.Test.Unit.TSUN051A Class Reference
Unit tests for FSM workflow engine. Component ID: TSUN051A.
Public Member Functions
void Constructor_SetsInitialState ()
void AddTransition_ValidTransition_Succeeds ()
void AddTransition_Duplicate_ThrowsInvalidOperationException ()
void Fire_ValidTransition_ChangesState ()
void Fire_InvalidTransition_ReturnsFailure ()
void Fire_GuardPasses_TransitionsSuccessfully ()
void Fire_GuardFails_TransitionBlocked ()
void CanFire_GuardFails_ReturnsFalse ()
void CanFire_NoGuard_ReturnsTrue ()
void Fire_WithAction_ExecutesAction ()
void Fire_ActionThrows_ReturnsFailure ()
void IsTerminal_InTerminalState_ReturnsTrue ()
void IsTerminal_NotInTerminalState_ReturnsFalse ()
void Fire_RecordsHistory ()
void Fire_FailedTransition_RecordedInHistory ()
void OnTransition_EventRaised ()
void History_CircularBuffer_BoundsMemory ()
void Fire_FreezesDefinition ()
void AddTransition_AfterFire_ThrowsInvalidOperationException ()
void Freeze_ExplicitlyFreezesDefinition ()
void OnEntry_ExecutesWhenEnteringState ()
void OnExit_ExecutesWhenLeavingState ()
void MooreActions_ExecuteInOrder ()
void GetStatistics_ReturnsCorrectCounts ()
void Validate_DetectsDeadStates ()
void GetAvailableEvents_ReturnsValidEvents ()
void GetPossibleTransitions_ReturnsAllDefinedTransitions ()
void Reset_ReturnsToInitialState ()
void Reset_ClearsHistory ()
void Validate_NoTransitionsFromInitial_ReportsIssue ()
void Validate_ValidFSM_ReturnsEmpty ()
void BacktestWorkflow_HappyPath_ReachesCompleted ()
void BacktestWorkflow_DataMissing_BootstrapsAndRetries ()
void BacktestWorkflow_BootstrapFails_ReachesFailed ()
void BacktestWorkflow_Reset_ReturnsToIdle ()
void TradingWorkflow_Connect_Evaluate_Execute ()
void TradingWorkflow_NoSignal_ReturnsToReady ()
void TradingWorkflow_FatalError_ReachesErrorState ()
Detailed Description
Unit tests for FSM workflow engine. Component ID: TSUN051A.
Tests validate:
Determinism: Each (state, event) → exactly one transition
Guard enforcement: Transitions blocked when guards fail
Action execution: Side-effects run on successful transitions
Terminal states: FSM correctly identifies terminal states
Validation: FSM detects structural issues
Definition at line 20 of file TSUN051A.cs.
Member Function Documentation
AddTransition_AfterFire_ThrowsInvalidOperationException()
void Alaris.Test.Unit.TSUN051A.AddTransition_AfterFire_ThrowsInvalidOperationException () inline
Definition at line 294 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition().
AddTransition_Duplicate_ThrowsInvalidOperationException()
void Alaris.Test.Unit.TSUN051A.AddTransition_Duplicate_ThrowsInvalidOperationException () inline
Definition at line 47 of file TSUN051A.cs.
AddTransition_ValidTransition_Succeeds()
void Alaris.Test.Unit.TSUN051A.AddTransition_ValidTransition_Succeeds () inline
Definition at line 34 of file TSUN051A.cs.
BacktestWorkflow_BootstrapFails_ReachesFailed()
void Alaris.Test.Unit.TSUN051A.BacktestWorkflow_BootstrapFails_ReachesFailed () inline
Definition at line 530 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF002A.Create().
BacktestWorkflow_DataMissing_BootstrapsAndRetries()
void Alaris.Test.Unit.TSUN051A.BacktestWorkflow_DataMissing_BootstrapsAndRetries () inline
Definition at line 514 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF002A.Create().
BacktestWorkflow_HappyPath_ReachesCompleted()
void Alaris.Test.Unit.TSUN051A.BacktestWorkflow_HappyPath_ReachesCompleted () inline
Definition at line 492 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF002A.Create().
BacktestWorkflow_Reset_ReturnsToIdle()
void Alaris.Test.Unit.TSUN051A.BacktestWorkflow_Reset_ReturnsToIdle () inline
Definition at line 544 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF002A.Create().
CanFire_GuardFails_ReturnsFalse()
void Alaris.Test.Unit.TSUN051A.CanFire_GuardFails_ReturnsFalse () inline
Definition at line 128 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition().
CanFire_NoGuard_ReturnsTrue()
void Alaris.Test.Unit.TSUN051A.CanFire_NoGuard_ReturnsTrue () inline
Definition at line 141 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition().
Constructor_SetsInitialState()
void Alaris.Test.Unit.TSUN051A.Constructor_SetsInitialState () inline
Definition at line 25 of file TSUN051A.cs.
Fire_ActionThrows_ReturnsFailure()
void Alaris.Test.Unit.TSUN051A.Fire_ActionThrows_ReturnsFailure () inline
Definition at line 170 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition().
Fire_FailedTransition_RecordedInHistory()
void Alaris.Test.Unit.TSUN051A.Fire_FailedTransition_RecordedInHistory () inline
Definition at line 233 of file TSUN051A.cs.
Fire_FreezesDefinition()
void Alaris.Test.Unit.TSUN051A.Fire_FreezesDefinition () inline
Definition at line 281 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition().
Fire_GuardFails_TransitionBlocked()
void Alaris.Test.Unit.TSUN051A.Fire_GuardFails_TransitionBlocked () inline
Definition at line 110 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition().
Fire_GuardPasses_TransitionsSuccessfully()
void Alaris.Test.Unit.TSUN051A.Fire_GuardPasses_TransitionsSuccessfully () inline
Definition at line 93 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition().
Fire_InvalidTransition_ReturnsFailure()
void Alaris.Test.Unit.TSUN051A.Fire_InvalidTransition_ReturnsFailure () inline
Definition at line 76 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition().
Fire_RecordsHistory()
void Alaris.Test.Unit.TSUN051A.Fire_RecordsHistory () inline
Definition at line 216 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition().
Fire_ValidTransition_ChangesState()
void Alaris.Test.Unit.TSUN051A.Fire_ValidTransition_ChangesState () inline
Definition at line 61 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition().
Fire_WithAction_ExecutesAction()
void Alaris.Test.Unit.TSUN051A.Fire_WithAction_ExecutesAction () inline
Definition at line 154 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition().
Freeze_ExplicitlyFreezesDefinition()
void Alaris.Test.Unit.TSUN051A.Freeze_ExplicitlyFreezesDefinition () inline
Definition at line 308 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition().
GetAvailableEvents_ReturnsValidEvents()
void Alaris.Test.Unit.TSUN051A.GetAvailableEvents_ReturnsValidEvents () inline
Definition at line 403 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition().
GetPossibleTransitions_ReturnsAllDefinedTransitions()
void Alaris.Test.Unit.TSUN051A.GetPossibleTransitions_ReturnsAllDefinedTransitions () inline
Definition at line 418 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition().
GetStatistics_ReturnsCorrectCounts()
void Alaris.Test.Unit.TSUN051A.GetStatistics_ReturnsCorrectCounts () inline
Definition at line 373 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF002A.Create().
History_CircularBuffer_BoundsMemory()
void Alaris.Test.Unit.TSUN051A.History_CircularBuffer_BoundsMemory () inline
Definition at line 257 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition().
IsTerminal_InTerminalState_ReturnsTrue()
void Alaris.Test.Unit.TSUN051A.IsTerminal_InTerminalState_ReturnsTrue () inline
Definition at line 192 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.SetTerminal().
IsTerminal_NotInTerminalState_ReturnsFalse()
void Alaris.Test.Unit.TSUN051A.IsTerminal_NotInTerminalState_ReturnsFalse () inline
Definition at line 202 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.SetTerminal().
MooreActions_ExecuteInOrder()
void Alaris.Test.Unit.TSUN051A.MooreActions_ExecuteInOrder () inline
Definition at line 348 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition().
OnEntry_ExecutesWhenEnteringState()
void Alaris.Test.Unit.TSUN051A.OnEntry_ExecutesWhenEnteringState () inline
Definition at line 322 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition().
OnExit_ExecutesWhenLeavingState()
void Alaris.Test.Unit.TSUN051A.OnExit_ExecutesWhenLeavingState () inline
Definition at line 335 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition().
OnTransition_EventRaised()
void Alaris.Test.Unit.TSUN051A.OnTransition_EventRaised () inline
Definition at line 244 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition().
Reset_ClearsHistory()
void Alaris.Test.Unit.TSUN051A.Reset_ClearsHistory () inline
Definition at line 448 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition().
Reset_ReturnsToInitialState()
void Alaris.Test.Unit.TSUN051A.Reset_ReturnsToInitialState () inline
Definition at line 434 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition().
TradingWorkflow_Connect_Evaluate_Execute()
void Alaris.Test.Unit.TSUN051A.TradingWorkflow_Connect_Evaluate_Execute () inline
Definition at line 566 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF003A.Create().
TradingWorkflow_FatalError_ReachesErrorState()
void Alaris.Test.Unit.TSUN051A.TradingWorkflow_FatalError_ReachesErrorState () inline
Definition at line 602 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF003A.Create().
TradingWorkflow_NoSignal_ReturnsToReady()
void Alaris.Test.Unit.TSUN051A.TradingWorkflow_NoSignal_ReturnsToReady () inline
Definition at line 589 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF003A.Create().
Validate_DetectsDeadStates()
void Alaris.Test.Unit.TSUN051A.Validate_DetectsDeadStates () inline
Definition at line 387 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition().
Validate_NoTransitionsFromInitial_ReportsIssue()
void Alaris.Test.Unit.TSUN051A.Validate_NoTransitionsFromInitial_ReportsIssue () inline
Definition at line 466 of file TSUN051A.cs.
Validate_ValidFSM_ReturnsEmpty()
void Alaris.Test.Unit.TSUN051A.Validate_ValidFSM_ReturnsEmpty () inline
Definition at line 478 of file TSUN051A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF002A.Create().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN051A.cs