Alaris: Alaris.Strategy.Core.STEJ001A Class Reference
Alaris.Strategy.Core.STEJ001A Class Reference sealed
Calibrates and evaluates earnings jump risk from historical announcement data.
Public Member Functions
STEJ001A (ILogger< STEJ001A >? logger=null)
Initialises a new instance of the earnings jump risk calibrator.
STEJ002A CalibrateFromMoves (IReadOnlyList< double > historicalMoves)
Calibrates the jump distribution from historical earnings moves.
double CalculateJumpRiskScore (STEJ002A parameters, double impliedMove, double thresholdMultiple=2.0)
Calculates the jump risk score (probability of exceeding threshold).
STEJ003A EvaluateJumpRisk (STEJ002A parameters, double impliedMove, double currentAllocation)
Evaluates jump risk for a position and recommends adjustments.
Private Member Functions
void SafeLog (Action logAction)
Safely executes logging operation with fault isolation.
Static Private Member Functions
static double NormalCdfComplement (double z)
Complement of standard normal CDF: P(Z > z).
static double Erfc (double x)
Complementary error function approximation.
Private Attributes
readonly? ILogger< STEJ001A > _logger
Static Private Attributes
const int MinDataPoints = 8
Minimum number of historical earnings events for calibration.
const double DefaultLaplaceScale = 0.40
Default Laplace scale parameter if insufficient data.
static readonly Action< ILogger, int, double, double, Exception?> LogCalibration
Detailed Description
Calibrates and evaluates earnings jump risk from historical announcement data.
Definition at line 11 of file STEJ001A.cs.
Constructor & Destructor Documentation
STEJ001A()
Alaris.Strategy.Core.STEJ001A.STEJ001A (ILogger< STEJ001A >? logger = null) inline
Initialises a new instance of the earnings jump risk calibrator.
Parameters
logger Optional logger instance.
Definition at line 36 of file STEJ001A.cs.
References Alaris.Strategy.Core.STEJ001A._logger.
Member Function Documentation
CalculateJumpRiskScore()
double Alaris.Strategy.Core.STEJ001A.CalculateJumpRiskScore (STEJ002A parameters, double impliedMove, double thresholdMultiple = 2::0) inline
Calculates the jump risk score (probability of exceeding threshold).
Parameters
parameters Calibrated distribution parameters.
impliedMove Expected move from options (σ√T).
thresholdMultiple Multiple of implied move to test (default 2.0).
Returns
Probability of move exceeding threshold.
Definition at line 106 of file STEJ001A.cs.
References Alaris.Strategy.Core.STEJ001A.NormalCdfComplement().
Referenced by Alaris.Test.Unit.STEJ001ATests.CalculateJumpRiskScore_HigherThreshold_ReturnsSmallerProb(), Alaris.Test.Unit.STEJ001ATests.CalculateJumpRiskScore_WithFatTailParams_ReturnsLargerTail(), Alaris.Test.Unit.STEJ001ATests.CalculateJumpRiskScore_WithNormalParams_ReturnsSmallTail(), and Alaris.Strategy.Core.STEJ001A.EvaluateJumpRisk().
CalibrateFromMoves()
STEJ002A Alaris.Strategy.Core.STEJ001A.CalibrateFromMoves (IReadOnlyList< double > historicalMoves) inline
Calibrates the jump distribution from historical earnings moves.
Parameters
historicalMoves Standardised earnings moves (actual / implied).
Returns
Calibrated jump distribution parameters.
Exceptions
ArgumentNullException Thrown when historicalMoves is null.
Definition at line 47 of file STEJ001A.cs.
References Alaris.Strategy.Core.STEJ001A._logger, Alaris.Strategy.Core.STEJ001A.DefaultLaplaceScale, Alaris.Strategy.Core.STEJ001A.LogCalibration, Alaris.Strategy.Core.STEJ001A.MinDataPoints, Alaris.Strategy.Core.STEJ001A.SafeLog(), and Alaris.Strategy.Core.STEJ002A.
Referenced by Alaris.Test.Unit.STEJ001ATests.CalibrateFromMoves_WithFatTails_ReturnsLowerLambda(), Alaris.Test.Unit.STEJ001ATests.CalibrateFromMoves_WithInsufficientData_ReturnsDefault(), and Alaris.Test.Unit.STEJ001ATests.CalibrateFromMoves_WithNormalData_ReturnsHighLambda().
Erfc()
static double Alaris.Strategy.Core.STEJ001A.Erfc (double x) inline static private
Complementary error function approximation.
Definition at line 201 of file STEJ001A.cs.
Referenced by Alaris.Strategy.Core.STEJ001A.NormalCdfComplement().
EvaluateJumpRisk()
STEJ003A Alaris.Strategy.Core.STEJ001A.EvaluateJumpRisk (STEJ002A parameters, double impliedMove, double currentAllocation) inline
Evaluates jump risk for a position and recommends adjustments.
Parameters
parameters Calibrated distribution parameters.
impliedMove Expected move from options.
currentAllocation Current portfolio allocation.
Returns
Jump risk evaluation result.
Definition at line 130 of file STEJ001A.cs.
References Alaris.Strategy.Core.STEJ001A.CalculateJumpRiskScore(), and Alaris.Strategy.Core.STEJ003A.
Referenced by Alaris.Test.Unit.STEJ001ATests.EvaluateJumpRisk_ElevatedRisk_ReturnsModerateCut(), Alaris.Test.Unit.STEJ001ATests.EvaluateJumpRisk_HighRisk_ReturnsReducedAllocation(), and Alaris.Test.Unit.STEJ001ATests.EvaluateJumpRisk_LowRisk_ReturnsNoAdjustment().
NormalCdfComplement()
static double Alaris.Strategy.Core.STEJ001A.NormalCdfComplement (double z) inline static private
Complement of standard normal CDF: P(Z > z).
Definition at line 190 of file STEJ001A.cs.
References Alaris.Strategy.Core.STEJ001A.Erfc().
Referenced by Alaris.Strategy.Core.STEJ001A.CalculateJumpRiskScore().
SafeLog()
void Alaris.Strategy.Core.STEJ001A.SafeLog (Action logAction) inline private
Safely executes logging operation with fault isolation.
Definition at line 223 of file STEJ001A.cs.
References Alaris.Strategy.Core.STEJ001A._logger.
Referenced by Alaris.Strategy.Core.STEJ001A.CalibrateFromMoves().
Member Data Documentation
_logger
readonly? ILogger<STEJ001A> Alaris.Strategy.Core.STEJ001A._logger private
Definition at line 13 of file STEJ001A.cs.
Referenced by Alaris.Strategy.Core.STEJ001A.STEJ001A(), Alaris.Strategy.Core.STEJ001A.CalibrateFromMoves(), and Alaris.Strategy.Core.STEJ001A.SafeLog().
DefaultLaplaceScale
const double Alaris.Strategy.Core.STEJ001A.DefaultLaplaceScale = 0.40 static private
Default Laplace scale parameter if insufficient data.
Definition at line 23 of file STEJ001A.cs.
Referenced by Alaris.Strategy.Core.STEJ001A.CalibrateFromMoves().
LogCalibration
readonly Action<ILogger, int, double, double, Exception?> Alaris.Strategy.Core.STEJ001A.LogCalibration static private
Initial value:
=
        LoggerMessage.Define<int, double, double>(
            LogLevel.Information,
            new EventId(1, nameof(LogCalibration)),
            "Jump risk calibration: N={DataPoints}, Lambda={Lambda:F3}, LaplaceB={LaplaceB:F4}")
Definition at line 26 of file STEJ001A.cs.
Referenced by Alaris.Strategy.Core.STEJ001A.CalibrateFromMoves().
MinDataPoints
const int Alaris.Strategy.Core.STEJ001A.MinDataPoints = 8 static private
Minimum number of historical earnings events for calibration.
Definition at line 18 of file STEJ001A.cs.
Referenced by Alaris.Strategy.Core.STEJ001A.CalibrateFromMoves().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Core/STEJ001A.cs