Alaris: Alaris.Host.Application.Cli.Monitor.CLmn002A Class Reference
Alaris.Host.Application.Cli.Monitor.CLmn002A Class Reference sealed
Monitors a LEAN backtest in progress and publishes events. Component ID: CLmn002A.
Public Member Functions
CLmn002A (string sessionId, string resultsPath)
Task StartAsync (CancellationToken cancellationToken=default)
Starts monitoring the algorithm.
async Task StopAsync ()
Stops monitoring.
void Dispose ()
Properties
bool IsRunning [get, private set]
Gets whether the algorithm is currently running.
AlgorithmMode Mode [get]
Gets the current algorithm mode.
Properties inherited from Alaris.Host.Application.Cli.Monitor.CLmn001A
Events
EventHandler< EquityUpdate >? EquityChanged
EventHandler< TradeUpdate >? TradeExecuted
EventHandler< StatusUpdate >? StatusChanged
Events inherited from Alaris.Host.Application.Cli.Monitor.CLmn001A
EventHandler< EquityUpdate >? EquityChanged
Raised when equity value changes.
EventHandler< TradeUpdate >? TradeExecuted
Raised when a trade is executed.
EventHandler< StatusUpdate >? StatusChanged
Raised when algorithm status changes.
Private Member Functions
async Task MonitorLoopAsync (CancellationToken ct)
async Task PollResultsAsync (CancellationToken ct)
void ParsePerformanceLine (string line)
void ParseTradeLine (string line)
Private Attributes
readonly string _sessionId
readonly string _resultsPath
CancellationTokenSource? _cts
Task? _monitorTask
decimal _lastEquity
Detailed Description
Monitors a LEAN backtest in progress and publishes events. Component ID: CLmn002A.
Definition at line 12 of file CLmn002A.cs.
Constructor & Destructor Documentation
CLmn002A()
Alaris.Host.Application.Cli.Monitor.CLmn002A.CLmn002A (string sessionId, string resultsPath) inline
Definition at line 27 of file CLmn002A.cs.
References Alaris.Host.Application.Cli.Monitor.CLmn002A._resultsPath, and Alaris.Host.Application.Cli.Monitor.CLmn002A._sessionId.
Member Function Documentation
Dispose()
void Alaris.Host.Application.Cli.Monitor.CLmn002A.Dispose () inline
Definition at line 183 of file CLmn002A.cs.
References Alaris.Host.Application.Cli.Monitor.CLmn002A._cts, and Alaris.Host.Application.Cli.Monitor.CLmn002A.StopAsync().
MonitorLoopAsync()
async Task Alaris.Host.Application.Cli.Monitor.CLmn002A.MonitorLoopAsync (CancellationToken ct) inline private
Definition at line 61 of file CLmn002A.cs.
References Alaris.Host.Application.Cli.Monitor.CLmn002A.PollResultsAsync().
Referenced by Alaris.Host.Application.Cli.Monitor.CLmn002A.StartAsync().
ParsePerformanceLine()
void Alaris.Host.Application.Cli.Monitor.CLmn002A.ParsePerformanceLine (string line) inline private
Definition at line 123 of file CLmn002A.cs.
References Alaris.Host.Application.Cli.Monitor.CLmn002A._lastEquity, and Alaris.Host.Application.Cli.Monitor.CLmn002A.EquityChanged.
Referenced by Alaris.Host.Application.Cli.Monitor.CLmn002A.PollResultsAsync().
ParseTradeLine()
void Alaris.Host.Application.Cli.Monitor.CLmn002A.ParseTradeLine (string line) inline private
Definition at line 153 of file CLmn002A.cs.
References Alaris.Host.Application.Cli.Monitor.CLmn002A.TradeExecuted.
Referenced by Alaris.Host.Application.Cli.Monitor.CLmn002A.PollResultsAsync().
PollResultsAsync()
async Task Alaris.Host.Application.Cli.Monitor.CLmn002A.PollResultsAsync (CancellationToken ct) inline private
Definition at line 83 of file CLmn002A.cs.
References Alaris.Host.Application.Cli.Monitor.CLmn002A._resultsPath, Alaris.Host.Application.Cli.Monitor.CLmn002A.ParsePerformanceLine(), Alaris.Host.Application.Cli.Monitor.CLmn002A.ParseTradeLine(), and Alaris.Host.Application.Cli.Monitor.CLmn002A.StatusChanged.
Referenced by Alaris.Host.Application.Cli.Monitor.CLmn002A.MonitorLoopAsync().
StartAsync()
Task Alaris.Host.Application.Cli.Monitor.CLmn002A.StartAsync (CancellationToken cancellationToken = default) inline
Starts monitoring the algorithm.
Implements Alaris.Host.Application.Cli.Monitor.CLmn001A.
Definition at line 33 of file CLmn002A.cs.
References Alaris.Host.Application.Cli.Monitor.CLmn002A._cts, Alaris.Host.Application.Cli.Monitor.CLmn002A._monitorTask, Alaris.Host.Application.Cli.Monitor.CLmn002A.IsRunning, and Alaris.Host.Application.Cli.Monitor.CLmn002A.MonitorLoopAsync().
StopAsync()
async Task Alaris.Host.Application.Cli.Monitor.CLmn002A.StopAsync () inline
Stops monitoring.
Implements Alaris.Host.Application.Cli.Monitor.CLmn001A.
Definition at line 45 of file CLmn002A.cs.
References Alaris.Host.Application.Cli.Monitor.CLmn002A._cts, Alaris.Host.Application.Cli.Monitor.CLmn002A._monitorTask, and Alaris.Host.Application.Cli.Monitor.CLmn002A.IsRunning.
Referenced by Alaris.Host.Application.Cli.Monitor.CLmn002A.Dispose().
Member Data Documentation
_cts
CancellationTokenSource? Alaris.Host.Application.Cli.Monitor.CLmn002A._cts private
Definition at line 16 of file CLmn002A.cs.
Referenced by Alaris.Host.Application.Cli.Monitor.CLmn002A.Dispose(), Alaris.Host.Application.Cli.Monitor.CLmn002A.StartAsync(), and Alaris.Host.Application.Cli.Monitor.CLmn002A.StopAsync().
_lastEquity
decimal Alaris.Host.Application.Cli.Monitor.CLmn002A._lastEquity private
Definition at line 18 of file CLmn002A.cs.
Referenced by Alaris.Host.Application.Cli.Monitor.CLmn002A.ParsePerformanceLine().
_monitorTask
Task? Alaris.Host.Application.Cli.Monitor.CLmn002A._monitorTask private
Definition at line 17 of file CLmn002A.cs.
Referenced by Alaris.Host.Application.Cli.Monitor.CLmn002A.StartAsync(), and Alaris.Host.Application.Cli.Monitor.CLmn002A.StopAsync().
_resultsPath
readonly string Alaris.Host.Application.Cli.Monitor.CLmn002A._resultsPath private
Definition at line 15 of file CLmn002A.cs.
Referenced by Alaris.Host.Application.Cli.Monitor.CLmn002A.CLmn002A(), and Alaris.Host.Application.Cli.Monitor.CLmn002A.PollResultsAsync().
_sessionId
readonly string Alaris.Host.Application.Cli.Monitor.CLmn002A._sessionId private
Definition at line 14 of file CLmn002A.cs.
Referenced by Alaris.Host.Application.Cli.Monitor.CLmn002A.CLmn002A().
Property Documentation
IsRunning
bool Alaris.Host.Application.Cli.Monitor.CLmn002A.IsRunning get private set
Gets whether the algorithm is currently running.
Implements Alaris.Host.Application.Cli.Monitor.CLmn001A.
Definition at line 20 of file CLmn002A.cs.
Referenced by Alaris.Host.Application.Cli.Monitor.CLmn002A.StartAsync(), and Alaris.Host.Application.Cli.Monitor.CLmn002A.StopAsync().
Mode
AlgorithmMode Alaris.Host.Application.Cli.Monitor.CLmn002A.Mode get
Gets the current algorithm mode.
Implements Alaris.Host.Application.Cli.Monitor.CLmn001A.
Definition at line 21 of file CLmn002A.cs.
Event Documentation
EquityChanged
EventHandler<EquityUpdate>? Alaris.Host.Application.Cli.Monitor.CLmn002A.EquityChanged
Definition at line 23 of file CLmn002A.cs.
Referenced by Alaris.Host.Application.Cli.Monitor.CLmn002A.ParsePerformanceLine().
StatusChanged
EventHandler<StatusUpdate>? Alaris.Host.Application.Cli.Monitor.CLmn002A.StatusChanged
Definition at line 25 of file CLmn002A.cs.
Referenced by Alaris.Host.Application.Cli.Monitor.CLmn002A.PollResultsAsync().
TradeExecuted
EventHandler<TradeUpdate>? Alaris.Host.Application.Cli.Monitor.CLmn002A.TradeExecuted
Definition at line 24 of file CLmn002A.cs.
Referenced by Alaris.Host.Application.Cli.Monitor.CLmn002A.ParseTradeLine().
The documentation for this class was generated from the following file:
src/Alaris.Host/Application/Cli/Monitor/CLmn002A.cs