Alaris: Alaris.Strategy.Core.STCR005A Class Reference
Alaris.Strategy.Core.STCR005A Class Reference sealed
Monitors signal freshness and detects staleness requiring revalidation.
Public Member Functions
STCR005A (double halfLifeMinutes=DefaultHalfLifeMinutes, ILogger< STCR005A >? logger=null)
Initialises a new instance of the signal freshness monitor.
double CalculateFreshness (DateTime signalTime, DateTime currentTime)
Calculates the freshness score of a signal.
bool RequiresRevalidation (DateTime signalTime, DateTime currentTime, double freshnessThreshold=DefaultFreshnessThreshold)
Checks if a signal requires revalidation due to staleness.
TimeSpan TimeUntilStale (DateTime signalTime, DateTime currentTime, double freshnessThreshold=DefaultFreshnessThreshold)
Calculates the time remaining until a signal becomes stale.
STCR006A Evaluate (DateTime signalTime, DateTime currentTime, double freshnessThreshold=DefaultFreshnessThreshold)
Evaluates signal freshness and provides detailed result.
Static Public Attributes
const double DefaultHalfLifeMinutes = 60.0
Default half-life in minutes (60 = 1 hour).
const double DefaultFreshnessThreshold = 0.5
Default freshness threshold for revalidation.
Private Member Functions
void SafeLog (Action logAction)
Safely executes logging operation with fault isolation.
Private Attributes
readonly? ILogger< STCR005A > _logger
readonly double _halfLifeMinutes
readonly double _decayRate
Static Private Attributes
static readonly Action< ILogger, double, double, Exception?> LogStaleSignal
Detailed Description
Monitors signal freshness and detects staleness requiring revalidation.
Definition at line 11 of file STCR005A.cs.
Constructor & Destructor Documentation
STCR005A()
Alaris.Strategy.Core.STCR005A.STCR005A (double halfLifeMinutes = DefaultHalfLifeMinutes, ILogger< STCR005A >? logger = null) inline
Initialises a new instance of the signal freshness monitor.
Parameters
halfLifeMinutes Signal half-life in minutes.
logger Optional logger instance.
Definition at line 39 of file STCR005A.cs.
References Alaris.Strategy.Core.STCR005A._decayRate, Alaris.Strategy.Core.STCR005A._halfLifeMinutes, and Alaris.Strategy.Core.STCR005A._logger.
Member Function Documentation
CalculateFreshness()
double Alaris.Strategy.Core.STCR005A.CalculateFreshness (DateTime signalTime, DateTime currentTime) inline
Calculates the freshness score of a signal.
Parameters
signalTime Time when signal was generated.
currentTime Current time.
Returns
Freshness score in [0, 1].
Definition at line 57 of file STCR005A.cs.
References Alaris.Strategy.Core.STCR005A._decayRate.
Referenced by Alaris.Strategy.Core.STCR005A.Evaluate(), Alaris.Strategy.Core.STCR005A.RequiresRevalidation(), Alaris.Test.Unit.Phase2MediumPriorityTests.STCR005A_CalculateFreshness_AtHalfLife_ReturnsHalf(), and Alaris.Test.Unit.Phase2MediumPriorityTests.STCR005A_CalculateFreshness_JustGenerated_ReturnsOne().
Evaluate()
STCR006A Alaris.Strategy.Core.STCR005A.Evaluate (DateTime signalTime, DateTime currentTime, double freshnessThreshold = DefaultFreshnessThreshold) inline
Evaluates signal freshness and provides detailed result.
Parameters
signalTime Time when signal was generated.
currentTime Current time.
freshnessThreshold Threshold for revalidation.
Returns
Freshness evaluation result.
Definition at line 119 of file STCR005A.cs.
References Alaris.Strategy.Core.STCR005A._halfLifeMinutes, Alaris.Strategy.Core.STCR005A.CalculateFreshness(), Alaris.Strategy.Core.STCR005A.RequiresRevalidation(), Alaris.Strategy.Core.STCR006A, and Alaris.Strategy.Core.STCR005A.TimeUntilStale().
RequiresRevalidation()
bool Alaris.Strategy.Core.STCR005A.RequiresRevalidation (DateTime signalTime, DateTime currentTime, double freshnessThreshold = DefaultFreshnessThreshold) inline
Checks if a signal requires revalidation due to staleness.
Parameters
signalTime Time when signal was generated.
currentTime Current time.
freshnessThreshold Threshold below which revalidation is needed.
Returns
True if signal should be revalidated.
Definition at line 75 of file STCR005A.cs.
References Alaris.Strategy.Core.STCR005A._logger, Alaris.Strategy.Core.STCR005A.CalculateFreshness(), Alaris.Strategy.Core.STCR005A.LogStaleSignal, and Alaris.Strategy.Core.STCR005A.SafeLog().
Referenced by Alaris.Strategy.Core.STCR005A.Evaluate(), and Alaris.Test.Unit.Phase2MediumPriorityTests.STCR005A_RequiresRevalidation_StaleSignal_ReturnsTrue().
SafeLog()
void Alaris.Strategy.Core.STCR005A.SafeLog (Action logAction) inline private
Safely executes logging operation with fault isolation.
Definition at line 168 of file STCR005A.cs.
References Alaris.Strategy.Core.STCR005A._logger.
Referenced by Alaris.Strategy.Core.STCR005A.RequiresRevalidation().
TimeUntilStale()
TimeSpan Alaris.Strategy.Core.STCR005A.TimeUntilStale (DateTime signalTime, DateTime currentTime, double freshnessThreshold = DefaultFreshnessThreshold) inline
Calculates the time remaining until a signal becomes stale.
Parameters
signalTime Time when signal was generated.
currentTime Current time.
freshnessThreshold Threshold for staleness.
Returns
Time until stale (negative if already stale).
Definition at line 99 of file STCR005A.cs.
References Alaris.Strategy.Core.STCR005A._decayRate.
Referenced by Alaris.Strategy.Core.STCR005A.Evaluate().
Member Data Documentation
_decayRate
readonly double Alaris.Strategy.Core.STCR005A._decayRate private
Definition at line 15 of file STCR005A.cs.
Referenced by Alaris.Strategy.Core.STCR005A.STCR005A(), Alaris.Strategy.Core.STCR005A.CalculateFreshness(), and Alaris.Strategy.Core.STCR005A.TimeUntilStale().
_halfLifeMinutes
readonly double Alaris.Strategy.Core.STCR005A._halfLifeMinutes private
Definition at line 14 of file STCR005A.cs.
Referenced by Alaris.Strategy.Core.STCR005A.STCR005A(), and Alaris.Strategy.Core.STCR005A.Evaluate().
_logger
readonly? ILogger<STCR005A> Alaris.Strategy.Core.STCR005A._logger private
Definition at line 13 of file STCR005A.cs.
Referenced by Alaris.Strategy.Core.STCR005A.STCR005A(), Alaris.Strategy.Core.STCR005A.RequiresRevalidation(), and Alaris.Strategy.Core.STCR005A.SafeLog().
DefaultFreshnessThreshold
const double Alaris.Strategy.Core.STCR005A.DefaultFreshnessThreshold = 0.5 static
Default freshness threshold for revalidation.
Definition at line 25 of file STCR005A.cs.
DefaultHalfLifeMinutes
const double Alaris.Strategy.Core.STCR005A.DefaultHalfLifeMinutes = 60.0 static
Default half-life in minutes (60 = 1 hour).
Definition at line 20 of file STCR005A.cs.
LogStaleSignal
readonly Action<ILogger, double, double, Exception?> Alaris.Strategy.Core.STCR005A.LogStaleSignal static private
Initial value:
=
        LoggerMessage.Define<double, double>(
            LogLevel.Warning,
            new EventId(1, nameof(LogStaleSignal)),
            "Signal stale: freshness={Freshness:F3}, age={AgeMinutes:F1}min")
Definition at line 28 of file STCR005A.cs.
Referenced by Alaris.Strategy.Core.STCR005A.RequiresRevalidation().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Core/STCR005A.cs