Alaris: Alaris.Test.Unit.STIV005ATests Class Reference
Alaris.Test.Unit.STIV005ATests Class Reference
Unit tests for STIV005A. Tests calibration of sigma_e from historical earnings data.
Public Member Functions
STIV005ATests ()
void CalibrateFromMoves_WithValidData_ReturnsCorrectSigmaE ()
void CalibrateFromMoves_WithInsufficientData_ReturnsNull ()
void CalibrateFromMoves_WithNullArray_ReturnsNull ()
void CalibrateFromMoves_WithConstantMoves_ReturnsMinSigmaE ()
void CalibrateFromMoves_WithLargeMoves_ClampsToMax ()
void Calibrate_WithValidPricesAndDates_ReturnsValidCalibration ()
void Calibrate_WithInsufficientEarningsData_ReturnsInvalidCalibration ()
void Calibrate_ThrowsOnNullSymbol ()
void Calibrate_ThrowsOnNullPrices ()
void STTM001AEstimator_WithValidInvertedSTTM001A_ReturnsSigmaE ()
void STTM001AEstimator_WithFlatSTTM001A_ReturnsNull ()
void STTM001AEstimator_WithInvalidDTE_ReturnsNull ()
void STTM001AEstimator_WithZeroDTE_ReturnsNull ()
void BaseVolatilityEstimator_WithValidInputs_ReturnsBaseVolatility ()
void BaseVolatilityEstimator_WithSameDTE_ReturnsNull ()
void BaseVolatilityEstimator_WithZeroDTE_ReturnsNull ()
Static Private Member Functions
static List< PriceBar > CreateSamplePriceData ()
static List< DateTime > CreateSampleEarningsDates ()
Private Attributes
readonly STIV005A _calibrator
Detailed Description
Unit tests for STIV005A. Tests calibration of sigma_e from historical earnings data.
Reference: "Accounting for Earnings Announcements in the Pricing of Equity Options" Tim Leung & Marco Santoli (2014), Section 5.2
Definition at line 16 of file TSUN010A.cs.
Constructor & Destructor Documentation
STIV005ATests()
Alaris.Test.Unit.STIV005ATests.STIV005ATests () inline
Definition at line 20 of file TSUN010A.cs.
References Alaris.Test.Unit.STIV005ATests._calibrator.
Member Function Documentation
BaseVolatilityEstimator_WithSameDTE_ReturnsNull()
void Alaris.Test.Unit.STIV005ATests.BaseVolatilityEstimator_WithSameDTE_ReturnsNull () inline
Definition at line 242 of file TSUN010A.cs.
References Alaris.Strategy.Core.STIV005A.BaseVolatilityEstimator().
BaseVolatilityEstimator_WithValidInputs_ReturnsBaseVolatility()
void Alaris.Test.Unit.STIV005ATests.BaseVolatilityEstimator_WithValidInputs_ReturnsBaseVolatility () inline
Definition at line 224 of file TSUN010A.cs.
References Alaris.Strategy.Core.STIV005A.BaseVolatilityEstimator().
BaseVolatilityEstimator_WithZeroDTE_ReturnsNull()
void Alaris.Test.Unit.STIV005ATests.BaseVolatilityEstimator_WithZeroDTE_ReturnsNull () inline
Definition at line 258 of file TSUN010A.cs.
References Alaris.Strategy.Core.STIV005A.BaseVolatilityEstimator().
Calibrate_ThrowsOnNullPrices()
void Alaris.Test.Unit.STIV005ATests.Calibrate_ThrowsOnNullPrices () inline
Definition at line 144 of file TSUN010A.cs.
References Alaris.Test.Unit.STIV005ATests._calibrator, Alaris.Strategy.Core.STIV005A.Calibrate(), and Alaris.Test.Unit.STIV005ATests.CreateSampleEarningsDates().
Calibrate_ThrowsOnNullSymbol()
void Alaris.Test.Unit.STIV005ATests.Calibrate_ThrowsOnNullSymbol () inline
Definition at line 132 of file TSUN010A.cs.
References Alaris.Test.Unit.STIV005ATests._calibrator, Alaris.Strategy.Core.STIV005A.Calibrate(), Alaris.Test.Unit.STIV005ATests.CreateSampleEarningsDates(), and Alaris.Test.Unit.STIV005ATests.CreateSamplePriceData().
Calibrate_WithInsufficientEarningsData_ReturnsInvalidCalibration()
void Alaris.Test.Unit.STIV005ATests.Calibrate_WithInsufficientEarningsData_ReturnsInvalidCalibration () inline
Definition at line 115 of file TSUN010A.cs.
References Alaris.Test.Unit.STIV005ATests._calibrator, Alaris.Strategy.Core.STIV005A.Calibrate(), Alaris.Test.Unit.STIV005ATests.CreateSamplePriceData(), and Alaris.Strategy.Core.EarningsJumpCalibration.IsValid.
Calibrate_WithValidPricesAndDates_ReturnsValidCalibration()
void Alaris.Test.Unit.STIV005ATests.Calibrate_WithValidPricesAndDates_ReturnsValidCalibration () inline
Definition at line 96 of file TSUN010A.cs.
References Alaris.Test.Unit.STIV005ATests._calibrator, Alaris.Strategy.Core.STIV005A.Calibrate(), Alaris.Test.Unit.STIV005ATests.CreateSampleEarningsDates(), Alaris.Test.Unit.STIV005ATests.CreateSamplePriceData(), and Alaris.Strategy.Core.EarningsJumpCalibration.Symbol.
CalibrateFromMoves_WithConstantMoves_ReturnsMinSigmaE()
void Alaris.Test.Unit.STIV005ATests.CalibrateFromMoves_WithConstantMoves_ReturnsMinSigmaE () inline
Definition at line 66 of file TSUN010A.cs.
References Alaris.Test.Unit.STIV005ATests._calibrator, and Alaris.Strategy.Core.STIV005A.CalibrateFromMoves().
CalibrateFromMoves_WithInsufficientData_ReturnsNull()
void Alaris.Test.Unit.STIV005ATests.CalibrateFromMoves_WithInsufficientData_ReturnsNull () inline
Definition at line 43 of file TSUN010A.cs.
References Alaris.Test.Unit.STIV005ATests._calibrator, and Alaris.Strategy.Core.STIV005A.CalibrateFromMoves().
CalibrateFromMoves_WithLargeMoves_ClampsToMax()
void Alaris.Test.Unit.STIV005ATests.CalibrateFromMoves_WithLargeMoves_ClampsToMax () inline
Definition at line 80 of file TSUN010A.cs.
References Alaris.Test.Unit.STIV005ATests._calibrator, and Alaris.Strategy.Core.STIV005A.CalibrateFromMoves().
CalibrateFromMoves_WithNullArray_ReturnsNull()
void Alaris.Test.Unit.STIV005ATests.CalibrateFromMoves_WithNullArray_ReturnsNull () inline
Definition at line 56 of file TSUN010A.cs.
References Alaris.Test.Unit.STIV005ATests._calibrator, and Alaris.Strategy.Core.STIV005A.CalibrateFromMoves().
CalibrateFromMoves_WithValidData_ReturnsCorrectSigmaE()
void Alaris.Test.Unit.STIV005ATests.CalibrateFromMoves_WithValidData_ReturnsCorrectSigmaE () inline
Definition at line 28 of file TSUN010A.cs.
References Alaris.Test.Unit.STIV005ATests._calibrator, and Alaris.Strategy.Core.STIV005A.CalibrateFromMoves().
CreateSampleEarningsDates()
static List< DateTime > Alaris.Test.Unit.STIV005ATests.CreateSampleEarningsDates () inline static private
Definition at line 310 of file TSUN010A.cs.
Referenced by Alaris.Test.Unit.STIV005ATests.Calibrate_ThrowsOnNullPrices(), Alaris.Test.Unit.STIV005ATests.Calibrate_ThrowsOnNullSymbol(), and Alaris.Test.Unit.STIV005ATests.Calibrate_WithValidPricesAndDates_ReturnsValidCalibration().
CreateSamplePriceData()
static List< PriceBar > Alaris.Test.Unit.STIV005ATests.CreateSamplePriceData () inline static private
Definition at line 275 of file TSUN010A.cs.
References Alaris.Strategy.Core.High, and Alaris.Strategy.Core.Low.
Referenced by Alaris.Test.Unit.STIV005ATests.Calibrate_ThrowsOnNullSymbol(), Alaris.Test.Unit.STIV005ATests.Calibrate_WithInsufficientEarningsData_ReturnsInvalidCalibration(), and Alaris.Test.Unit.STIV005ATests.Calibrate_WithValidPricesAndDates_ReturnsValidCalibration().
STTM001AEstimator_WithFlatSTTM001A_ReturnsNull()
void Alaris.Test.Unit.STIV005ATests.STTM001AEstimator_WithFlatSTTM001A_ReturnsNull () inline
Definition at line 174 of file TSUN010A.cs.
References Alaris.Strategy.Core.STIV005A.STTM001AEstimator().
STTM001AEstimator_WithInvalidDTE_ReturnsNull()
void Alaris.Test.Unit.STIV005ATests.STTM001AEstimator_WithInvalidDTE_ReturnsNull () inline
Definition at line 190 of file TSUN010A.cs.
References Alaris.Strategy.Core.STIV005A.STTM001AEstimator().
STTM001AEstimator_WithValidInvertedSTTM001A_ReturnsSigmaE()
void Alaris.Test.Unit.STIV005ATests.STTM001AEstimator_WithValidInvertedSTTM001A_ReturnsSigmaE () inline
Definition at line 157 of file TSUN010A.cs.
References Alaris.Strategy.Core.STIV005A.STTM001AEstimator().
STTM001AEstimator_WithZeroDTE_ReturnsNull()
void Alaris.Test.Unit.STIV005ATests.STTM001AEstimator_WithZeroDTE_ReturnsNull () inline
Definition at line 206 of file TSUN010A.cs.
References Alaris.Strategy.Core.STIV005A.STTM001AEstimator().
Member Data Documentation
_calibrator
readonly STIV005A Alaris.Test.Unit.STIV005ATests._calibrator private
Definition at line 18 of file TSUN010A.cs.
Referenced by Alaris.Test.Unit.STIV005ATests.STIV005ATests(), Alaris.Test.Unit.STIV005ATests.Calibrate_ThrowsOnNullPrices(), Alaris.Test.Unit.STIV005ATests.Calibrate_ThrowsOnNullSymbol(), Alaris.Test.Unit.STIV005ATests.Calibrate_WithInsufficientEarningsData_ReturnsInvalidCalibration(), Alaris.Test.Unit.STIV005ATests.Calibrate_WithValidPricesAndDates_ReturnsValidCalibration(), Alaris.Test.Unit.STIV005ATests.CalibrateFromMoves_WithConstantMoves_ReturnsMinSigmaE(), Alaris.Test.Unit.STIV005ATests.CalibrateFromMoves_WithInsufficientData_ReturnsNull(), Alaris.Test.Unit.STIV005ATests.CalibrateFromMoves_WithLargeMoves_ClampsToMax(), Alaris.Test.Unit.STIV005ATests.CalibrateFromMoves_WithNullArray_ReturnsNull(), and Alaris.Test.Unit.STIV005ATests.CalibrateFromMoves_WithValidData_ReturnsCorrectSigmaE().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN010A.cs