Alaris: Alaris.Strategy.Risk.STRK004A Class Reference
Alaris.Strategy.Risk.STRK004A Class Reference sealed
Implements priority queue capital allocation for heterogeneous opportunities.
Public Member Functions
STRK004A (STRK001A baseKelly, ILogger< STRK004A >? logger=null)
Initialises a new instance of the priority queue allocator.
QueueAllocationResult Allocate (double portfolioValue, STCR004A candidate, double candidateSpreadCost, IReadOnlyList< OpenPosition > openPositions, IReadOnlyList< Trade > historicalTrades)
Evaluates a candidate opportunity against the current portfolio queue.
double CalculatePriority (STCR004A signal, IReadOnlyList< Trade > historicalTrades)
Calculates the priority score for an opportunity.
IReadOnlyList< RebalanceRecommendation > RebalancePortfolio (double portfolioValue, IReadOnlyList< OpenPosition > openPositions, IReadOnlyList< Trade > historicalTrades)
Rebalances the entire portfolio to optimal queue allocation.
Private Member Functions
QueueAllocationResult CalculateQueueBasedAllocation (double portfolioValue, STCR004A candidate, double spreadCost, double candidatePriority, int candidateRank, List< QueueEntry > queue, double currentAllocation, STRK002A basePosition)
Calculates allocation based on queue position and available capital.
QueueAllocationResult EvaluateDisplacement (STCR004A candidate, double candidatePriority, List< QueueEntry > queue, double currentAllocation, double portfolioValue, double spreadCost, STRK002A basePosition)
Evaluates whether the candidate should displace a lower-priority position.
void SafeLog (Action logAction)
Safely executes logging operation with fault isolation (Rule 15).
Static Private Member Functions
static double CalculateVariancePenalty (double winRate)
Calculates variance penalty based on historical win rate uncertainty.
static List< QueueEntry > BuildPriorityQueue (IReadOnlyList< OpenPosition > openPositions, STCR004A candidate, double candidatePriority, double candidateAllocation)
Builds the priority queue including open positions and candidate.
Private Attributes
readonly STRK001A _baseKelly
readonly? ILogger< STRK004A > _logger
Static Private Attributes
const double MaxTotalAllocation = 0.60
Maximum total portfolio allocation across all positions.
const double MinPriorityImprovementRatio = 1.20
Minimum priority improvement required to displace existing position. Prevents excessive rebalancing from marginal improvements.
const double FractionalKellyMultiplier = 0.25
Fractional Kelly multiplier for safety (25% of full Kelly).
static readonly Action< ILogger, string, double, int, Exception?> LogAllocationDecision
static readonly Action< ILogger, string, string, double, double, Exception?> LogDisplacementDecision
static readonly Action< ILogger, int, double, Exception?> LogQueueState
Detailed Description
Implements priority queue capital allocation for heterogeneous opportunities.
Definition at line 13 of file STRK004A.cs.
Constructor & Destructor Documentation
STRK004A()
Alaris.Strategy.Risk.STRK004A.STRK004A (STRK001A baseKelly, ILogger< STRK004A >? logger = null) inline
Initialises a new instance of the priority queue allocator.
Parameters
baseKelly Base Kelly calculator for individual position sizing.
logger Optional logger instance.
Exceptions
ArgumentNullException Thrown when baseKelly is null.
Definition at line 59 of file STRK004A.cs.
References Alaris.Strategy.Risk.STRK004A._baseKelly, and Alaris.Strategy.Risk.STRK004A._logger.
Member Function Documentation
Allocate()
QueueAllocationResult Alaris.Strategy.Risk.STRK004A.Allocate (double portfolioValue, STCR004A candidate, double candidateSpreadCost, IReadOnlyList< OpenPosition > openPositions, IReadOnlyList< Trade > historicalTrades) inline
Evaluates a candidate opportunity against the current portfolio queue.
Parameters
portfolioValue Total portfolio value.
candidate Candidate trading signal to evaluate.
candidateSpreadCost Cost of the candidate calendar spread.
openPositions Currently open positions with their priorities.
historicalTrades Historical trades for Kelly calculation.
Returns
Allocation decision with sizing and any displacement recommendations.
Exceptions
ArgumentNullException Thrown when required parameters are null.
ArgumentOutOfRangeException Thrown when portfolioValue is non-positive.
Definition at line 76 of file STRK004A.cs.
References Alaris.Strategy.Risk.STRK004A._baseKelly, Alaris.Strategy.Risk.STRK004A._logger, Alaris.Strategy.Risk.STRK002A.AllocationPercent, Alaris.Strategy.Risk.STRK004A.BuildPriorityQueue(), Alaris.Strategy.Risk.STRK001A.CalculateFromHistory(), Alaris.Strategy.Risk.STRK004A.CalculatePriority(), Alaris.Strategy.Risk.STRK004A.CalculateQueueBasedAllocation(), Alaris.Strategy.Risk.STRK002A.Contracts, Alaris.Strategy.Risk.STRK004A.LogAllocationDecision, Alaris.Strategy.Risk.STRK004A.LogQueueState, Alaris.Strategy.Risk.QueueAllocationResult, Alaris.Strategy.Risk.STRK004A.SafeLog(), and Alaris.Strategy.Core.STCR004A.Symbol.
Referenced by Alaris.Test.Unit.STRK004ATests.Allocate_WhenCandidateCanDisplace_ReturnsDisplaceExisting(), Alaris.Test.Unit.STRK004ATests.Allocate_WhenCandidateIsHigherPriority_RanksFirst(), Alaris.Test.Unit.STRK004ATests.Allocate_WhenCapacityExhausted_EvaluatesDisplacement(), Alaris.Test.Unit.STRK004ATests.Allocate_WhenQueueEmpty_AcceptsNewOpportunity(), Alaris.Test.Unit.STRK004ATests.Allocate_WithAvoidSignal_RejectsOpportunity(), Alaris.Test.Unit.STRK004ATests.Allocate_WithInvalidPortfolioValue_ThrowsArgumentOutOfRangeException(), and Alaris.Test.Unit.STRK004ATests.Allocate_WithNullCandidate_ThrowsArgumentNullException().
BuildPriorityQueue()
static List< QueueEntry > Alaris.Strategy.Risk.STRK004A.BuildPriorityQueue (IReadOnlyList< OpenPosition > openPositions, STCR004A candidate, double candidatePriority, double candidateAllocation) inline static private
Builds the priority queue including open positions and candidate.
Definition at line 201 of file STRK004A.cs.
References Alaris.Strategy.Risk.OpenPosition.
Referenced by Alaris.Strategy.Risk.STRK004A.Allocate().
CalculatePriority()
double Alaris.Strategy.Risk.STRK004A.CalculatePriority (STCR004A signal, IReadOnlyList< Trade > historicalTrades) inline
Calculates the priority score for an opportunity.
Parameters
signal Trading signal containing opportunity metrics.
historicalTrades Historical trades for win rate estimation.
Returns
Priority score (higher is better).
Definition at line 144 of file STRK004A.cs.
References Alaris.Strategy.Risk.STRK004A.CalculateVariancePenalty(), Alaris.Strategy.Core.STCR004A.IVCrushRatio, Alaris.Strategy.Core.STCR004A.IVRVRatio, and Alaris.Strategy.Core.STCR004A.STTM001ASlope.
Referenced by Alaris.Strategy.Risk.STRK004A.Allocate(), Alaris.Test.Unit.STRK004ATests.CalculatePriority_WithAvoidSignal_ReturnsZero(), Alaris.Test.Unit.STRK004ATests.CalculatePriority_WithHighEdgeRecommendedSignal_ReturnsHighPriority(), and Alaris.Test.Unit.STRK004ATests.CalculatePriority_WithLowEdgeConsiderSignal_ReturnsLowerPriority().
CalculateQueueBasedAllocation()
QueueAllocationResult Alaris.Strategy.Risk.STRK004A.CalculateQueueBasedAllocation (double portfolioValue, STCR004A candidate, double spreadCost, double candidatePriority, int candidateRank, List< QueueEntry > queue, double currentAllocation, STRK002A basePosition) inline private
Calculates allocation based on queue position and available capital.
Definition at line 235 of file STRK004A.cs.
References Alaris.Strategy.Risk.STRK002A.AllocationPercent, Alaris.Strategy.Risk.STRK004A.EvaluateDisplacement(), Alaris.Strategy.Risk.STRK002A.ExpectedProfitPerContract, Alaris.Strategy.Risk.STRK004A.FractionalKellyMultiplier, Alaris.Strategy.Risk.STRK002A.MaxLossPerContract, Alaris.Strategy.Risk.STRK004A.MaxTotalAllocation, Alaris.Strategy.Risk.QueueAllocationResult, and Alaris.Strategy.Core.STCR004A.Symbol.
Referenced by Alaris.Strategy.Risk.STRK004A.Allocate().
CalculateVariancePenalty()
static double Alaris.Strategy.Risk.STRK004A.CalculateVariancePenalty (double winRate) inline static private
Calculates variance penalty based on historical win rate uncertainty.
Definition at line 190 of file STRK004A.cs.
Referenced by Alaris.Strategy.Risk.STRK004A.CalculatePriority().
EvaluateDisplacement()
QueueAllocationResult Alaris.Strategy.Risk.STRK004A.EvaluateDisplacement (STCR004A candidate, double candidatePriority, List< QueueEntry > queue, double currentAllocation, double portfolioValue, double spreadCost, STRK002A basePosition) inline private
Evaluates whether the candidate should displace a lower-priority position.
Definition at line 303 of file STRK004A.cs.
References Alaris.Strategy.Risk.STRK004A._logger, Alaris.Strategy.Risk.STRK002A.AllocationPercent, Alaris.Strategy.Risk.STRK002A.ExpectedProfitPerContract, Alaris.Strategy.Risk.STRK004A.FractionalKellyMultiplier, Alaris.Strategy.Risk.STRK004A.LogDisplacementDecision, Alaris.Strategy.Risk.STRK002A.MaxLossPerContract, Alaris.Strategy.Risk.STRK004A.MinPriorityImprovementRatio, Alaris.Strategy.Risk.QueueAllocationResult, Alaris.Strategy.Risk.STRK004A.SafeLog(), and Alaris.Strategy.Core.STCR004A.Symbol.
Referenced by Alaris.Strategy.Risk.STRK004A.CalculateQueueBasedAllocation().
RebalancePortfolio()
IReadOnlyList< RebalanceRecommendation > Alaris.Strategy.Risk.STRK004A.RebalancePortfolio (double portfolioValue, IReadOnlyList< OpenPosition > openPositions, IReadOnlyList< Trade > historicalTrades) inline
Rebalances the entire portfolio to optimal queue allocation.
Parameters
portfolioValue Total portfolio value.
openPositions Currently open positions.
historicalTrades Historical trades for priority calculation.
Returns
List of rebalancing recommendations.
Definition at line 390 of file STRK004A.cs.
References Alaris.Strategy.Risk.STRK004A.FractionalKellyMultiplier, Alaris.Strategy.Risk.STRK004A.MaxTotalAllocation, Alaris.Strategy.Risk.OpenPosition, and Alaris.Strategy.Risk.RebalanceRecommendation.
Referenced by Alaris.Test.Unit.STRK004ATests.RebalancePortfolio_WithMisallocatedPositions_ReturnsRecommendations().
SafeLog()
void Alaris.Strategy.Risk.STRK004A.SafeLog (Action logAction) inline private
Safely executes logging operation with fault isolation (Rule 15).
Definition at line 440 of file STRK004A.cs.
References Alaris.Strategy.Risk.STRK004A._logger.
Referenced by Alaris.Strategy.Risk.STRK004A.Allocate(), and Alaris.Strategy.Risk.STRK004A.EvaluateDisplacement().
Member Data Documentation
_baseKelly
readonly STRK001A Alaris.Strategy.Risk.STRK004A._baseKelly private
Definition at line 15 of file STRK004A.cs.
Referenced by Alaris.Strategy.Risk.STRK004A.STRK004A(), and Alaris.Strategy.Risk.STRK004A.Allocate().
_logger
readonly? ILogger<STRK004A> Alaris.Strategy.Risk.STRK004A._logger private
Definition at line 16 of file STRK004A.cs.
Referenced by Alaris.Strategy.Risk.STRK004A.STRK004A(), Alaris.Strategy.Risk.STRK004A.Allocate(), Alaris.Strategy.Risk.STRK004A.EvaluateDisplacement(), and Alaris.Strategy.Risk.STRK004A.SafeLog().
FractionalKellyMultiplier
const double Alaris.Strategy.Risk.STRK004A.FractionalKellyMultiplier = 0.25 static private
Fractional Kelly multiplier for safety (25% of full Kelly).
Definition at line 32 of file STRK004A.cs.
Referenced by Alaris.Strategy.Risk.STRK004A.CalculateQueueBasedAllocation(), Alaris.Strategy.Risk.STRK004A.EvaluateDisplacement(), and Alaris.Strategy.Risk.STRK004A.RebalancePortfolio().
LogAllocationDecision
readonly Action<ILogger, string, double, int, Exception?> Alaris.Strategy.Risk.STRK004A.LogAllocationDecision static private
Initial value:
=
        LoggerMessage.Define<string, double, int>(
            LogLevel.Information,
            new EventId(1, nameof(LogAllocationDecision)),
            "Queue allocation for {Symbol}: priority={Priority:F4}, rank={Rank}")
Definition at line 35 of file STRK004A.cs.
Referenced by Alaris.Strategy.Risk.STRK004A.Allocate().
LogDisplacementDecision
readonly Action<ILogger, string, string, double, double, Exception?> Alaris.Strategy.Risk.STRK004A.LogDisplacementDecision static private
Initial value:
=
        LoggerMessage.Define<string, string, double, double>(
            LogLevel.Information,
            new EventId(2, nameof(LogDisplacementDecision)),
            "Displacement analysis: {Candidate} (priority={CandidatePriority:F4}) vs {Incumbent} (priority={IncumbentPriority:F4})")
Definition at line 41 of file STRK004A.cs.
Referenced by Alaris.Strategy.Risk.STRK004A.EvaluateDisplacement().
LogQueueState
readonly Action<ILogger, int, double, Exception?> Alaris.Strategy.Risk.STRK004A.LogQueueState static private
Initial value:
=
        LoggerMessage.Define<int, double>(
            LogLevel.Debug,
            new EventId(3, nameof(LogQueueState)),
            "Queue state: {PositionCount} positions, {TotalAllocation:P2} allocated")
Definition at line 47 of file STRK004A.cs.
Referenced by Alaris.Strategy.Risk.STRK004A.Allocate().
MaxTotalAllocation
const double Alaris.Strategy.Risk.STRK004A.MaxTotalAllocation = 0.60 static private
Maximum total portfolio allocation across all positions.
Definition at line 21 of file STRK004A.cs.
Referenced by Alaris.Strategy.Risk.STRK004A.CalculateQueueBasedAllocation(), and Alaris.Strategy.Risk.STRK004A.RebalancePortfolio().
MinPriorityImprovementRatio
const double Alaris.Strategy.Risk.STRK004A.MinPriorityImprovementRatio = 1.20 static private
Minimum priority improvement required to displace existing position. Prevents excessive rebalancing from marginal improvements.
Definition at line 27 of file STRK004A.cs.
Referenced by Alaris.Strategy.Risk.STRK004A.EvaluateDisplacement().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Risk/STRK004A.cs