Alaris: Alaris.Test.Benchmark.TSBM002A Class Reference
Alaris.Test.Benchmark.TSBM002A Class Reference
Benchmark tests comparing spectral vs finite difference American option pricing.
Public Member Functions
TSBM002A (ITestOutputHelper output)
void Accuracy_SpectralVsFD_StandardRegime (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType)
void Accuracy_SpectralVsFD_NegativeRateSingleBoundary (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType)
void Performance_SpectralFastVsFD_100Options ()
void RegimeCoverage_AllRegimesProduceValidPrice (double r, double q, bool isCall, string regimeDescription)
void Greeks_SpectralProducesReasonableValues (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType)
void RMSE_SpectralVsFD_Portfolio ()
Private Attributes
readonly ITestOutputHelper _output
readonly CREN004A _spectralFast
readonly CREN004A _spectralAccurate
readonly CREN002A _fdEngine
Detailed Description
Benchmark tests comparing spectral vs finite difference American option pricing.
Definition at line 19 of file TSBM002A.cs.
Constructor & Destructor Documentation
TSBM002A()
Alaris.Test.Benchmark.TSBM002A.TSBM002A (ITestOutputHelper output) inline
Definition at line 26 of file TSBM002A.cs.
References Alaris.Test.Benchmark.TSBM002A._fdEngine, Alaris.Test.Benchmark.TSBM002A._output, Alaris.Test.Benchmark.TSBM002A._spectralAccurate, and Alaris.Test.Benchmark.TSBM002A._spectralFast.
Member Function Documentation
Accuracy_SpectralVsFD_NegativeRateSingleBoundary()
void Alaris.Test.Benchmark.TSBM002A.Accuracy_SpectralVsFD_NegativeRateSingleBoundary (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType) inline
Definition at line 64 of file TSBM002A.cs.
References Alaris.Test.Benchmark.TSBM002A._fdEngine, Alaris.Test.Benchmark.TSBM002A._output, Alaris.Test.Benchmark.TSBM002A._spectralAccurate, Alaris.Core.Pricing.CREN004A.Price(), and Alaris.Core.Pricing.CREN002A.Price().
Accuracy_SpectralVsFD_StandardRegime()
void Alaris.Test.Benchmark.TSBM002A.Accuracy_SpectralVsFD_StandardRegime (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType) inline
Definition at line 42 of file TSBM002A.cs.
References Alaris.Test.Benchmark.TSBM002A._fdEngine, Alaris.Test.Benchmark.TSBM002A._output, Alaris.Test.Benchmark.TSBM002A._spectralAccurate, Alaris.Core.Pricing.CREN004A.Price(), and Alaris.Core.Pricing.CREN002A.Price().
Greeks_SpectralProducesReasonableValues()
void Alaris.Test.Benchmark.TSBM002A.Greeks_SpectralProducesReasonableValues (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType) inline
Definition at line 176 of file TSBM002A.cs.
References Alaris.Test.Benchmark.TSBM002A._output, Alaris.Test.Benchmark.TSBM002A._spectralAccurate, Alaris.Core.Pricing.CREN004A.Delta(), Alaris.Core.Pricing.CREN004A.Gamma(), and Alaris.Core.Pricing.CREN004A.Vega().
Performance_SpectralFastVsFD_100Options()
void Alaris.Test.Benchmark.TSBM002A.Performance_SpectralFastVsFD_100Options () inline
Definition at line 85 of file TSBM002A.cs.
References Alaris.Test.Benchmark.TSBM002A._fdEngine, Alaris.Test.Benchmark.TSBM002A._output, Alaris.Test.Benchmark.TSBM002A._spectralFast, Alaris.Core.Pricing.CREN004A.Price(), Alaris.Core.Pricing.CREN002A.Price(), and Alaris.Core.Options.Spot.
RegimeCoverage_AllRegimesProduceValidPrice()
void Alaris.Test.Benchmark.TSBM002A.RegimeCoverage_AllRegimesProduceValidPrice (double r, double q, bool isCall, string regimeDescription) inline
Definition at line 148 of file TSBM002A.cs.
References Alaris.Test.Benchmark.TSBM002A._output, Alaris.Test.Benchmark.TSBM002A._spectralAccurate, and Alaris.Core.Pricing.CREN004A.Price().
RMSE_SpectralVsFD_Portfolio()
void Alaris.Test.Benchmark.TSBM002A.RMSE_SpectralVsFD_Portfolio () inline
Definition at line 204 of file TSBM002A.cs.
References Alaris.Test.Benchmark.TSBM002A._fdEngine, Alaris.Test.Benchmark.TSBM002A._output, Alaris.Test.Benchmark.TSBM002A._spectralAccurate, Alaris.Core.Pricing.CREN004A.Price(), Alaris.Core.Pricing.CREN002A.Price(), and Alaris.Core.Options.Spot.
Member Data Documentation
_fdEngine
readonly CREN002A Alaris.Test.Benchmark.TSBM002A._fdEngine private
Definition at line 24 of file TSBM002A.cs.
Referenced by Alaris.Test.Benchmark.TSBM002A.TSBM002A(), Alaris.Test.Benchmark.TSBM002A.Accuracy_SpectralVsFD_NegativeRateSingleBoundary(), Alaris.Test.Benchmark.TSBM002A.Accuracy_SpectralVsFD_StandardRegime(), Alaris.Test.Benchmark.TSBM002A.Performance_SpectralFastVsFD_100Options(), and Alaris.Test.Benchmark.TSBM002A.RMSE_SpectralVsFD_Portfolio().
_output
readonly ITestOutputHelper Alaris.Test.Benchmark.TSBM002A._output private
Definition at line 21 of file TSBM002A.cs.
Referenced by Alaris.Test.Benchmark.TSBM002A.TSBM002A(), Alaris.Test.Benchmark.TSBM002A.Accuracy_SpectralVsFD_NegativeRateSingleBoundary(), Alaris.Test.Benchmark.TSBM002A.Accuracy_SpectralVsFD_StandardRegime(), Alaris.Test.Benchmark.TSBM002A.Greeks_SpectralProducesReasonableValues(), Alaris.Test.Benchmark.TSBM002A.Performance_SpectralFastVsFD_100Options(), Alaris.Test.Benchmark.TSBM002A.RegimeCoverage_AllRegimesProduceValidPrice(), and Alaris.Test.Benchmark.TSBM002A.RMSE_SpectralVsFD_Portfolio().
_spectralAccurate
readonly CREN004A Alaris.Test.Benchmark.TSBM002A._spectralAccurate private
Definition at line 23 of file TSBM002A.cs.
Referenced by Alaris.Test.Benchmark.TSBM002A.TSBM002A(), Alaris.Test.Benchmark.TSBM002A.Accuracy_SpectralVsFD_NegativeRateSingleBoundary(), Alaris.Test.Benchmark.TSBM002A.Accuracy_SpectralVsFD_StandardRegime(), Alaris.Test.Benchmark.TSBM002A.Greeks_SpectralProducesReasonableValues(), Alaris.Test.Benchmark.TSBM002A.RegimeCoverage_AllRegimesProduceValidPrice(), and Alaris.Test.Benchmark.TSBM002A.RMSE_SpectralVsFD_Portfolio().
_spectralFast
readonly CREN004A Alaris.Test.Benchmark.TSBM002A._spectralFast private
Definition at line 22 of file TSBM002A.cs.
Referenced by Alaris.Test.Benchmark.TSBM002A.TSBM002A(), and Alaris.Test.Benchmark.TSBM002A.Performance_SpectralFastVsFD_100Options().
The documentation for this class was generated from the following file:
src/Alaris.Test/Benchmark/TSBM002A.cs