Alaris: Alaris.Host.Application.Serialization.APsr001A Class Reference
Alaris.Host.Application.Serialization.APsr001A Class Reference
Binary serialization adapter for session metadata. Component ID: APsr001A.
Static Public Member Functions
static int EncodeSessionMetadata (APmd001A session, Span< byte > buffer)
Encodes session metadata to binary format.
static int GetEncodedSize (APmd001A session)
Gets the estimated encoded size for session metadata.
static APmd001A DecodeSessionMetadata (ReadOnlySpan< byte > buffer)
Decodes session metadata from binary format.
Static Private Member Functions
static void WriteFixedString (Span< byte > buffer, string? value, int length)
static string ReadFixedString (ReadOnlySpan< byte > buffer, int length)
Static Private Attributes
const byte FormatVersion = 1
Detailed Description
Binary serialization adapter for session metadata. Component ID: APsr001A.
Provides binary encoding/decoding for session metadata and index files. This is optional and sessions continue to use JSON for human-readability in the main session.json file, with binary format available for performance.
Definition at line 18 of file APsr001A.cs.
Member Function Documentation
DecodeSessionMetadata()
static APmd001A Alaris.Host.Application.Serialization.APsr001A.DecodeSessionMetadata (ReadOnlySpan< byte > buffer) inline static
Decodes session metadata from binary format.
Definition at line 94 of file APsr001A.cs.
References Alaris.Host.Application.Model.APmd001A, Alaris.Host.Application.Serialization.APsr001A.FormatVersion, and Alaris.Host.Application.Serialization.APsr001A.ReadFixedString().
Referenced by Alaris.Test.Unit.TSUN030A.SessionMetadata_RoundTrip_PreservesAllFields().
EncodeSessionMetadata()
static int Alaris.Host.Application.Serialization.APsr001A.EncodeSessionMetadata (APmd001A session, Span< byte > buffer) inline static
Encodes session metadata to binary format.
Parameters
session Source session metadata.
buffer Target buffer (minimum 512 bytes).
Returns
Number of bytes written.
Definition at line 28 of file APsr001A.cs.
References Alaris.Host.Application.Serialization.APsr001A.FormatVersion, and Alaris.Host.Application.Serialization.APsr001A.WriteFixedString().
Referenced by Alaris.Test.Unit.TSUN030A.GetEncodedSize_ForSession_ReturnsCorrectSize(), and Alaris.Test.Unit.TSUN030A.SessionMetadata_RoundTrip_PreservesAllFields().
GetEncodedSize()
static int Alaris.Host.Application.Serialization.APsr001A.GetEncodedSize (APmd001A session) inline static
Gets the estimated encoded size for session metadata.
Definition at line 83 of file APsr001A.cs.
Referenced by Alaris.Test.Unit.TSUN030A.GetEncodedSize_ForSession_ReturnsCorrectSize().
ReadFixedString()
static string Alaris.Host.Application.Serialization.APsr001A.ReadFixedString (ReadOnlySpan< byte > buffer, int length) inline static private
Definition at line 161 of file APsr001A.cs.
Referenced by Alaris.Host.Application.Serialization.APsr001A.DecodeSessionMetadata().
WriteFixedString()
static void Alaris.Host.Application.Serialization.APsr001A.WriteFixedString (Span< byte > buffer, string? value, int length) inline static private
Definition at line 151 of file APsr001A.cs.
Referenced by Alaris.Host.Application.Serialization.APsr001A.EncodeSessionMetadata().
Member Data Documentation
FormatVersion
const byte Alaris.Host.Application.Serialization.APsr001A.FormatVersion = 1 static private
Definition at line 20 of file APsr001A.cs.
Referenced by Alaris.Host.Application.Serialization.APsr001A.DecodeSessionMetadata(), and Alaris.Host.Application.Serialization.APsr001A.EncodeSessionMetadata().
The documentation for this class was generated from the following file:
src/Alaris.Host/Application/Serialization/APsr001A.cs