Alaris: Alaris.Test.Unit.RuleBasedExitTests Class Reference
Alaris.Test.Unit.RuleBasedExitTests Class Reference sealed
Public Member Functions
void Evaluate_TargetCapture_ExitsImmediately ()
void Evaluate_SignificantCaptureButStalled_Exits ()
void Evaluate_TracksUpdateCount ()
void Evaluate_ApproachingExpiry_TimeDecayExit ()
void Evaluate_GoodProgress_Holds ()
void ComputeCrushCaptured_CorrectCalculation ()
void SmoothedRate_TracksRateChange ()
Detailed Description
Definition at line 205 of file TSUN013A.cs.
Member Function Documentation
ComputeCrushCaptured_CorrectCalculation()
void Alaris.Test.Unit.RuleBasedExitTests.ComputeCrushCaptured_CorrectCalculation () inline
Definition at line 288 of file TSUN013A.cs.
References Alaris.Strategy.Hedge.STHD007B.ComputeCrushCaptured().
Evaluate_ApproachingExpiry_TimeDecayExit()
void Alaris.Test.Unit.RuleBasedExitTests.Evaluate_ApproachingExpiry_TimeDecayExit () inline
Definition at line 257 of file TSUN013A.cs.
References Alaris.Strategy.Hedge.STHD007B.Evaluate().
Evaluate_GoodProgress_Holds()
void Alaris.Test.Unit.RuleBasedExitTests.Evaluate_GoodProgress_Holds () inline
Definition at line 271 of file TSUN013A.cs.
References Alaris.Strategy.Hedge.STHD007B.Evaluate().
Evaluate_SignificantCaptureButStalled_Exits()
void Alaris.Test.Unit.RuleBasedExitTests.Evaluate_SignificantCaptureButStalled_Exits () inline
Definition at line 222 of file TSUN013A.cs.
References Alaris.Strategy.Hedge.STHD007B.Evaluate().
Evaluate_TargetCapture_ExitsImmediately()
void Alaris.Test.Unit.RuleBasedExitTests.Evaluate_TargetCapture_ExitsImmediately () inline
Definition at line 208 of file TSUN013A.cs.
References Alaris.Strategy.Hedge.STHD007B.Evaluate().
Evaluate_TracksUpdateCount()
void Alaris.Test.Unit.RuleBasedExitTests.Evaluate_TracksUpdateCount () inline
Definition at line 241 of file TSUN013A.cs.
References Alaris.Strategy.Hedge.STHD007B.Evaluate().
SmoothedRate_TracksRateChange()
void Alaris.Test.Unit.RuleBasedExitTests.SmoothedRate_TracksRateChange () inline
Definition at line 304 of file TSUN013A.cs.
References Alaris.Strategy.Hedge.STHD007B.Evaluate().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN013A.cs