Alaris: Alaris.Strategy.Core.STPR003A Class Reference
Alaris.Strategy.Core.STPR003A Class Reference
Production-grade Heston model pricing using characteristic function integration. Implements the semi-analytical pricing formula from Heston (1993). Uses Carr-Madan Fourier inversion or Lewis (2001) approach for option pricing, then backs out implied volatility using Newton-Raphson iteration.
Static Public Member Functions
static double ComputePrice (double spot, double strike, double timeToExpiry, HestonParameters @params, bool isCall=true)
Computes call option price using Heston semi-analytical formula. Uses the characteristic function approach with numerical integration.
static double ComputeImpliedVolatility (double spot, double strike, double timeToExpiry, HestonParameters @params)
Computes implied volatility from Heston model using Brent's method. Replaces Newton-Bisection cascade with unified Brent algorithm.
Static Private Member Functions
static double ComputeProbability (double spot, double strike, double timeToExpiry, HestonParameters @params, int j)
Computes P_j probability using characteristic function integration.
static Complex CharacteristicFunction (double phi, double timeToExpiry, HestonParameters @params, int j)
Standard Heston characteristic function for probability P_j. This is the core of the semi-analytical pricing formula. Based on Heston (1993) equations (17) and (18).
static double BlackScholesPrice (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, bool isCall)
Black-Scholes option price for IV solving.
static double BlackScholesVega (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility)
Black-Scholes vega for gradient-based methods (retained for reference).
static double NormalCDF (double x)
Cumulative distribution function for standard normal. Delegates to unified CRMF001A implementation.
static double NormalPDF (double x)
Probability density function for standard normal. Delegates to unified CRMF001A implementation.
Static Private Attributes
const double MinIV = 0.001
const double MaxIV = 5.0
const double IVTolerance = 1e-6
Detailed Description
Production-grade Heston model pricing using characteristic function integration. Implements the semi-analytical pricing formula from Heston (1993). Uses Carr-Madan Fourier inversion or Lewis (2001) approach for option pricing, then backs out implied volatility using Newton-Raphson iteration.
Definition at line 14 of file STPR003A.cs.
Member Function Documentation
BlackScholesPrice()
static double Alaris.Strategy.Core.STPR003A.BlackScholesPrice (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, bool isCall) inline static private
Black-Scholes option price for IV solving.
Definition at line 208 of file STPR003A.cs.
References Alaris.Strategy.Core.STPR003A.NormalCDF().
Referenced by Alaris.Strategy.Core.STPR003A.ComputeImpliedVolatility().
BlackScholesVega()
static double Alaris.Strategy.Core.STPR003A.BlackScholesVega (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility) inline static private
Black-Scholes vega for gradient-based methods (retained for reference).
Definition at line 239 of file STPR003A.cs.
References Alaris.Strategy.Core.STPR003A.NormalPDF().
CharacteristicFunction()
static Complex Alaris.Strategy.Core.STPR003A.CharacteristicFunction (double phi, double timeToExpiry, HestonParameters @ params, int j) inline static private
Standard Heston characteristic function for probability P_j. This is the core of the semi-analytical pricing formula. Based on Heston (1993) equations (17) and (18).
Definition at line 148 of file STPR003A.cs.
References Alaris.Strategy.Core.HestonParameters.DividendYield, Alaris.Strategy.Core.HestonParameters.Kappa, Alaris.Strategy.Core.HestonParameters.Rho, Alaris.Strategy.Core.HestonParameters.RiskFreeRate, Alaris.Strategy.Core.HestonParameters.SigmaV, Alaris.Strategy.Core.HestonParameters.Theta, and Alaris.Strategy.Core.HestonParameters.V0.
Referenced by Alaris.Strategy.Core.STPR003A.ComputeProbability().
ComputeImpliedVolatility()
static double Alaris.Strategy.Core.STPR003A.ComputeImpliedVolatility (double spot, double strike, double timeToExpiry, HestonParameters @ params) inline static
Computes implied volatility from Heston model using Brent's method. Replaces Newton-Bisection cascade with unified Brent algorithm.
Parameters
spot Current spot price.
strike Strike price.
timeToExpiry Time to expiry in years.
params Heston model parameters.
Returns
Implied volatility.
Definition at line 77 of file STPR003A.cs.
References Alaris.Strategy.Core.STPR003A.BlackScholesPrice(), Alaris.Strategy.Core.STPR003A.ComputePrice(), Alaris.Strategy.Core.HestonParameters.DividendYield, Alaris.Strategy.Core.STPR003A.IVTolerance, Alaris.Strategy.Core.STPR003A.MaxIV, Alaris.Strategy.Core.STPR003A.MinIV, Alaris.Strategy.Core.HestonParameters.RiskFreeRate, and Alaris.Strategy.Core.Numerical.STPR007A.SolveImpliedVolatility().
Referenced by Alaris.Strategy.Core.STIV001A.ComputeTheoreticalIV().
ComputePrice()
static double Alaris.Strategy.Core.STPR003A.ComputePrice (double spot, double strike, double timeToExpiry, HestonParameters @ params, bool isCall = true) inline static
Computes call option price using Heston semi-analytical formula. Uses the characteristic function approach with numerical integration.
Parameters
spot Current spot price.
strike Strike price.
timeToExpiry Time to expiry in years.
params Heston model parameters.
isCall True for call, false for put.
Returns
Option price.
Definition at line 30 of file STPR003A.cs.
References Alaris.Strategy.Core.STPR003A.ComputeProbability(), Alaris.Strategy.Core.HestonParameters.DividendYield, and Alaris.Strategy.Core.HestonParameters.RiskFreeRate.
Referenced by Alaris.Strategy.Core.STPR003A.ComputeImpliedVolatility().
ComputeProbability()
static double Alaris.Strategy.Core.STPR003A.ComputeProbability (double spot, double strike, double timeToExpiry, HestonParameters @ params, int j) inline static private
Computes P_j probability using characteristic function integration.
Parameters
spot Current spot price.
strike Strike price.
timeToExpiry Time to expiration in years.
params Heston model parameters.
j Probability index (1 or 2).
Definition at line 105 of file STPR003A.cs.
References Alaris.Strategy.Core.STPR003A.CharacteristicFunction(), and Alaris.Strategy.Core.Numerical.STPR002C.IntegrateToInfinity().
Referenced by Alaris.Strategy.Core.STPR003A.ComputePrice().
NormalCDF()
static double Alaris.Strategy.Core.STPR003A.NormalCDF (double x) static private
Cumulative distribution function for standard normal. Delegates to unified CRMF001A implementation.
Referenced by Alaris.Strategy.Core.STPR003A.BlackScholesPrice().
NormalPDF()
static double Alaris.Strategy.Core.STPR003A.NormalPDF (double x) static private
Probability density function for standard normal. Delegates to unified CRMF001A implementation.
Referenced by Alaris.Strategy.Core.STPR003A.BlackScholesVega().
Member Data Documentation
IVTolerance
const double Alaris.Strategy.Core.STPR003A.IVTolerance = 1e-6 static private
Definition at line 18 of file STPR003A.cs.
Referenced by Alaris.Strategy.Core.STPR003A.ComputeImpliedVolatility().
MaxIV
const double Alaris.Strategy.Core.STPR003A.MaxIV = 5.0 static private
Definition at line 17 of file STPR003A.cs.
Referenced by Alaris.Strategy.Core.STPR003A.ComputeImpliedVolatility().
MinIV
const double Alaris.Strategy.Core.STPR003A.MinIV = 0.001 static private
Definition at line 16 of file STPR003A.cs.
Referenced by Alaris.Strategy.Core.STPR003A.ComputeImpliedVolatility().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Core/STPR003A.cs