Alaris: Alaris.Test.Integration.TSEE001A Class Reference
Alaris.Test.Integration.TSEE001A Class Reference sealed
TSEE001A: End-to-end workflow tests for complete signal-to-execution pipeline.
Public Member Functions
void HappyPath_SingleSymbol_CompletePipeline ()
Complete pipeline with single equity: Signal → Validation → Sizing.
void EarningsEvent_ElevatedIV_GeneratesSignal ()
Signal generation around earnings events with elevated IV.
void HighVolatility_AdjustsPositionSize (double vixLevel, double expectedScaling)
Position sizing under VIX > 30 regime.
void NearExpiry_BoundaryValidation (double timeToExpiry)
Near-expiry (T < 3 DTE) edge case handling.
void DataGap_MissingBars_HandledGracefully ()
Missing data handling - system gracefully handles gaps.
void MultiSymbol_BatchProcess_Efficient ()
Processing multiple symbols efficiently.
void BoundsValidation_IntegrationWithDoubleSolver ()
Validates bounds are enforced across pipeline.
void BoundsValidation_InvalidVolatility_Rejected (double volatility)
Invalid parameters rejected at pipeline entry.
Static Private Member Functions
static STCR004A CreateTestSignal (string symbol, double impliedVol30, double realizedVol30, double termSlope, long volume=1_000_000)
Creates a test signal with specified parameters.
Detailed Description
TSEE001A: End-to-end workflow tests for complete signal-to-execution pipeline.
Definition at line 26 of file TSEE001A.cs.
Member Function Documentation
BoundsValidation_IntegrationWithDoubleSolver()
void Alaris.Test.Integration.TSEE001A.BoundsValidation_IntegrationWithDoubleSolver () inline
Validates bounds are enforced across pipeline.
Definition at line 251 of file TSEE001A.cs.
References Alaris.Core.Validation.AlgorithmBounds.ValidateDoubleBoundaryInputs().
BoundsValidation_InvalidVolatility_Rejected()
void Alaris.Test.Integration.TSEE001A.BoundsValidation_InvalidVolatility_Rejected (double volatility) inline
Invalid parameters rejected at pipeline entry.
Definition at line 279 of file TSEE001A.cs.
References Alaris.Core.Validation.AlgorithmBounds.ValidateDoubleBoundaryInputs().
CreateTestSignal()
static STCR004A Alaris.Test.Integration.TSEE001A.CreateTestSignal (string symbol, double impliedVol30, double realizedVol30, double termSlope, long volume = 1_000_000) inline static private
Creates a test signal with specified parameters.
Definition at line 32 of file TSEE001A.cs.
Referenced by Alaris.Test.Integration.TSEE001A.EarningsEvent_ElevatedIV_GeneratesSignal(), Alaris.Test.Integration.TSEE001A.HappyPath_SingleSymbol_CompletePipeline(), and Alaris.Test.Integration.TSEE001A.MultiSymbol_BatchProcess_Efficient().
DataGap_MissingBars_HandledGracefully()
void Alaris.Test.Integration.TSEE001A.DataGap_MissingBars_HandledGracefully () inline
Missing data handling - system gracefully handles gaps.
Definition at line 183 of file TSEE001A.cs.
EarningsEvent_ElevatedIV_GeneratesSignal()
void Alaris.Test.Integration.TSEE001A.EarningsEvent_ElevatedIV_GeneratesSignal () inline
Signal generation around earnings events with elevated IV.
Definition at line 89 of file TSEE001A.cs.
References Alaris.Test.Integration.TSEE001A.CreateTestSignal(), and Alaris.Strategy.Core.STCR004A.IVRVRatio.
HappyPath_SingleSymbol_CompletePipeline()
void Alaris.Test.Integration.TSEE001A.HappyPath_SingleSymbol_CompletePipeline () inline
Complete pipeline with single equity: Signal → Validation → Sizing.
Definition at line 57 of file TSEE001A.cs.
References Alaris.Test.Integration.TSEE001A.CreateTestSignal().
HighVolatility_AdjustsPositionSize()
void Alaris.Test.Integration.TSEE001A.HighVolatility_AdjustsPositionSize (double vixLevel, double expectedScaling) inline
Position sizing under VIX > 30 regime.
Definition at line 122 of file TSEE001A.cs.
MultiSymbol_BatchProcess_Efficient()
void Alaris.Test.Integration.TSEE001A.MultiSymbol_BatchProcess_Efficient () inline
Processing multiple symbols efficiently.
Definition at line 218 of file TSEE001A.cs.
References Alaris.Test.Integration.TSEE001A.CreateTestSignal().
NearExpiry_BoundaryValidation()
void Alaris.Test.Integration.TSEE001A.NearExpiry_BoundaryValidation (double timeToExpiry) inline
Near-expiry (T < 3 DTE) edge case handling.
Definition at line 153 of file TSEE001A.cs.
The documentation for this class was generated from the following file:
src/Alaris.Test/Integration/TSEE001A.cs