Alaris: Alaris.Algorithm.STLN001A Class Reference
Alaris.Algorithm.STLN001A Class Reference sealed
Alaris Earnings Volatility Trading Algorithm.
Classes
class EvaluationResult
Result of symbol evaluation.
class OrderExecutionResult
Result of order execution attempt.
Public Member Functions
override void Initialize ()
Initialises the algorithm at start. Called once by LEAN engine.
override void OnEndOfAlgorithm ()
Called when the algorithm ends.
override void OnOrderEvent (OrderEvent orderEvent)
Handles order events from LEAN.
Private Member Functions
void InitialiseLogging ()
Initialises logging infrastructure. Bridges LEAN logging to Microsoft.Extensions.Logging.
void InitialiseDataProviders ()
Initialises data providers from Alaris.Data.
void InitialiseStrategyComponents ()
Initialises strategy analysis components from Alaris.Strategy.
void InitialiseProductionValidation ()
Initialises production validation pipeline.
void InitialiseUniverseSelection ()
Initialises universe selection. Uses STUN001B (Polygon-based) which reads pre-generated universe files.
void InitialiseAuditTrail ()
Initialises audit trail and event sourcing.
void ScheduleDailyEvaluation ()
Schedules daily strategy evaluation at market open + 1 minute.
IConfiguration BuildConfiguration ()
Builds configuration from appsettings files. Loads appsettings.jsonc (base) then appsettings.local.jsonc (secrets).
void LoadSettings (IConfiguration configuration)
Loads configuration-backed settings with validation.
void EvaluatePositions ()
Main strategy evaluation logic. Called daily at 9:31 AM ET.
EvaluationResult EvaluateSymbol (Symbol symbol)
Evaluates a single symbol for trading opportunity. Implements complete Alaris strategy workflow.
EvaluationResult EvaluateSnapshot (Symbol symbol, MarketDataSnapshot snapshot, bool useExecutionQuoteProvider)
bool AreComponentsInitialised ()
Checks if all components are properly initialised.
decimal GetCurrentAllocation ()
Gets current portfolio allocation to strategy positions.
STHD006A ValidateForProduction (STCR004A signal, MarketDataSnapshot snapshot, CalendarSpreadSelection selection, int proposedContracts)
Validates a signal for production using STHD005A.
bool TrySelectCalendarSpread (MarketDataSnapshot snapshot, DateTime earningsDate, AlarisOptionRight right, out CalendarSpreadSelection selection, out string detail)
void PopulateSignalLegs (STCR004A signal, CalendarSpreadSelection selection)
DTmd002A? GetSpreadQuote (CalendarSpreadSelection selection, bool useExecutionQuoteProvider)
IReadOnlyList< double > IReadOnlyList< double > BackIVHistory BuildIvHistory (CalendarSpreadSelection selection, MarketDataSnapshot snapshot)
SpreadGreeks ComputeSpreadGreeks (CalendarSpreadSelection selection, MarketDataSnapshot snapshot)
Alaris.Strategy.Model.STDT003A BuildPricingParameters (MarketDataSnapshot snapshot, OptionContract contract, AlarisOptionRight right, double impliedVolatility)
bool TryResolveImpliedVolatility (OptionContract contract, double spotPrice, double riskFreeRate, double dividendYield, DateTime valuationDate, AlarisOptionRight right, out double impliedVolatility, out bool usedSynthetic)
IReadOnlyList< Alaris.Strategy.Bridge.PriceBar > ConvertToPriceBars (IReadOnlyList< Alaris.Infrastructure.Data.Model.PriceBar > dataBars)
Converts Alaris.Infrastructure.Data.Model.PriceBar to Alaris.Strategy.Bridge.PriceBar for volatility calculation.
IReadOnlyList< STTM001APoint > ConvertToTermStructurePoints (OptionChainSnapshot optionChain, DateTime? evaluationDate=null)
Converts option chain snapshot to term structure points for analysis.
OrderExecutionResult ExecuteCalendarSpread (Symbol underlyingSymbol, CalendarSpreadSelection selection, DTmd002A quote, int contracts)
Executes a calendar spread order using LEAN's combo order functionality.
Symbol CreateOptionSymbol (Symbol underlying, decimal strike, DateTime expiry, QCOptionRight right)
Creates an option symbol from components.
record CalendarSpreadSelection (string Symbol, OptionContract FrontLeg, OptionContract BackLeg, decimal Strike, DateTime FrontExpiry, DateTime BackExpiry, AlarisOptionRight Right, bool UsesSyntheticIv, double FrontIV, double BackIV)
record StrategySettings (int DaysBeforeEarningsMin, int DaysBeforeEarningsMax, decimal MinimumDollarVolume, decimal MinimumPrice, decimal PortfolioAllocationLimit, decimal MaxPositionAllocation, int MaxConcurrentPositions, int MaxUniverseSymbols, int MaxCoarseSymbols, int EvaluationTimeHour, int EvaluationTimeMinute, AlarisOptionRight OptionRight, int RealisedVolatilityWindowDays, double DefaultImpliedVolatility)
record BacktestSettings (DateTime StartDate, DateTime EndDate, decimal InitialCash, int WarmUpDays, int HistoryLookbackDays, int EarningsLookaheadDays, int EarningsLookbackDays, TimeSpan EarningsQueryTimeout)
record DataProviderSettings (Uri PolygonBaseUri, TimeSpan PolygonTimeout, Uri NasdaqBaseUri, TimeSpan NasdaqTimeout, Uri TreasuryBaseUri, TimeSpan TreasuryTimeout, TimeSpan MarketDataTimeout, TimeSpan ExecutionQuoteTimeout)
record ValidationSettings (double MaxVegaCorrelation, int MinimumVegaObservations, int VegaCorrelationLookbackDays, double MaxPositionToVolumeRatio, double MaxPositionToOpenInterestRatio, double DeltaRehedgeThreshold, double GammaWarningThreshold, double MoneynessAlertThreshold)
record FeeSettings (decimal PerContract, decimal ExchangePerContract, decimal RegulatoryPerContract)
Static Private Member Functions
static string FindLeanDataPath ()
Finds the LEAN data path for universe files.
static string FindRepositoryRoot ()
Finds the repository root directory containing appsettings.jsonc.
static ? DTmd002A BuildSpreadQuote (CalendarSpreadSelection selection)
static STCS002A BuildOptionParams (OptionContract contract, Alaris.Strategy.Cost.OrderDirection direction, string symbol, int contracts)
static bool TryGetContractForStrike (OptionChainSnapshot chain, DateTime expiry, decimal strike, AlarisOptionRight right, out OptionContract contract)
static bool IsQuoteValid (OptionContract contract)
static QCOptionRight ToQcOptionRight (AlarisOptionRight right)
static OptionType ToOptionType (AlarisOptionRight right)
static string GetRequiredValue (IConfiguration configuration, string key)
static int GetRequiredInt (IConfiguration configuration, string key)
static double GetRequiredDouble (IConfiguration configuration, string key)
static decimal GetRequiredDecimal (IConfiguration configuration, string key)
static DateTime GetRequiredDateTime (IConfiguration configuration, string key)
static Uri GetRequiredUri (IConfiguration configuration, string key)
static AlarisOptionRight GetRequiredOptionRight (IConfiguration configuration, string key)
Private Attributes
StrategySettings _strategySettings = StrategySettings.Empty
BacktestSettings _backtestSettings = BacktestSettings.Empty
DataProviderSettings _dataProviderSettings = DataProviderSettings.Empty
ValidationSettings _validationSettings = ValidationSettings.Empty
FeeSettings _feeSettings = FeeSettings.Empty
AlarisDataBridge? _dataBridge
DTpr003A? _marketDataProvider
DTpr004A? _earningsProvider
DTpr005A? _riskFreeRateProvider
DTpr002A? _executionQuoteProvider
STCR003A? _yangZhangEstimator
STTM001A? _termStructureAnalyzer
STCR001A? _signalGenerator
DataBridgeMarketDataAdapter? _marketDataAdapter
STRK001A? _positionSizer
STBR001A? _pricingEngine
STHD005A? _productionValidator
STCS005A? _feeModel
STCS006A? _costValidator
STHD001A? _vegaAnalyser
STCS008A? _liquidityValidator
STHD003A? _gammaRiskManager
EVIF001A? _eventStore
EVIF002A? _auditLogger
ILogger< STLN001A >? _logger
ILoggerFactory? _loggerFactory
IConfiguration? _configuration
AlarisTimeProvider? _timeProvider
readonly HashSet< Symbol > _activePositions = new()
readonly Dictionary< Symbol, DateTime > _positionEntryDates = new()
IReadOnlyList< double > FrontIVHistory
Detailed Description
Alaris Earnings Volatility Trading Algorithm.
Implements Atilgan (2014) earnings calendar spread strategy with:
Yang-Zhang (2000) realised volatility estimation
Leung-Santoli (2014) pre-earnings IV modelling
Healy (2021) American option pricing under negative rates
Production validation (cost survival, vega independence, liquidity, gamma risk)
Strategy workflow (10 phases):
Universe selection: symbols with earnings in target window
Market data acquisition: historical bars, options chains, earnings calendar
Realised volatility: Yang-Zhang OHLC estimator
Term structure analysis: 30/60/90 DTE IV
Signal generation: Atilgan criteria evaluation
Production validation: 4-stage validator pipeline
Position sizing: Kelly criterion
Execution pricing: IBKR snapshot quotes
Order execution: LEAN combo orders
Audit trail: Alaris.Events logging
Definition at line 76 of file STLN001A.cs.
Member Function Documentation
AreComponentsInitialised()
bool Alaris.Algorithm.STLN001A.AreComponentsInitialised () inline private
Checks if all components are properly initialised.
Definition at line 968 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.EvaluatePositions().
BacktestSettings()
record Alaris.Algorithm.STLN001A.BacktestSettings (DateTime StartDate, DateTime EndDate, decimal InitialCash, int WarmUpDays, int HistoryLookbackDays, int EarningsLookaheadDays, int EarningsLookbackDays, TimeSpan EarningsQueryTimeout) inline sealed private
Definition at line 1775 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.LoadSettings().
BuildConfiguration()
IConfiguration Alaris.Algorithm.STLN001A.BuildConfiguration () inline private
Builds configuration from appsettings files. Loads appsettings.jsonc (base) then appsettings.local.jsonc (secrets).
Definition at line 500 of file STLN001A.cs.
References Alaris.Algorithm.STLN001A.FindRepositoryRoot().
Referenced by Alaris.Algorithm.STLN001A.InitialiseDataProviders(), and Alaris.Algorithm.STLN001A.Initialize().
BuildIvHistory()
IReadOnlyList< double > IReadOnlyList< double > BackIVHistory Alaris.Algorithm.STLN001A.BuildIvHistory (CalendarSpreadSelection selection, MarketDataSnapshot snapshot) inline private
Definition at line 1242 of file STLN001A.cs.
References Alaris.Infrastructure.Data.Model.MarketDataSnapshot.DividendYield, Alaris.Infrastructure.Data.Model.MarketDataSnapshot.OptionChain, Alaris.Infrastructure.Data.Model.MarketDataSnapshot.RiskFreeRate, and Alaris.Infrastructure.Data.Model.MarketDataSnapshot.Timestamp.
BuildOptionParams()
static STCS002A Alaris.Algorithm.STLN001A.BuildOptionParams (OptionContract contract, Alaris::Strategy::Cost::OrderDirection direction, string symbol, int contracts) inline static private
Definition at line 1313 of file STLN001A.cs.
References Alaris.Infrastructure.Data.Model.OptionContract.Ask, Alaris.Infrastructure.Data.Model.OptionContract.Bid, Alaris.Infrastructure.Data.Model.OptionContract.Mid, and Alaris.Strategy.Cost.STCS002A.
BuildPricingParameters()
Alaris.Strategy.Model.STDT003A Alaris.Algorithm.STLN001A.BuildPricingParameters (MarketDataSnapshot snapshot, OptionContract contract, AlarisOptionRight right, double impliedVolatility) inline private
Definition at line 1362 of file STLN001A.cs.
References Alaris.Infrastructure.Data.Model.MarketDataSnapshot.DividendYield, Alaris.Infrastructure.Data.Model.OptionContract.Expiration, Alaris.Core.Time.CRTM005A.FromDateTime(), Alaris.Infrastructure.Data.Model.MarketDataSnapshot.RiskFreeRate, Alaris.Infrastructure.Data.Model.MarketDataSnapshot.SpotPrice, Alaris.Infrastructure.Data.Model.OptionContract.Strike, and Alaris.Infrastructure.Data.Model.MarketDataSnapshot.Timestamp.
BuildSpreadQuote()
static ? DTmd002A Alaris.Algorithm.STLN001A.BuildSpreadQuote (CalendarSpreadSelection selection) inline static private
Definition at line 1219 of file STLN001A.cs.
References Alaris.Infrastructure.Data.Model.DTmd002A.
CalendarSpreadSelection()
record Alaris.Algorithm.STLN001A.CalendarSpreadSelection (string Symbol, OptionContract FrontLeg, OptionContract BackLeg, decimal Strike, DateTime FrontExpiry, DateTime BackExpiry, AlarisOptionRight Right, bool UsesSyntheticIv, double FrontIV, double BackIV) sealed private
ComputeSpreadGreeks()
SpreadGreeks Alaris.Algorithm.STLN001A.ComputeSpreadGreeks (CalendarSpreadSelection selection, MarketDataSnapshot snapshot) inline private
Definition at line 1335 of file STLN001A.cs.
References Alaris.Strategy.Hedge.SpreadGreeks.
ConvertToPriceBars()
IReadOnlyList< Alaris.Strategy.Bridge.PriceBar > Alaris.Algorithm.STLN001A.ConvertToPriceBars (IReadOnlyList< Alaris::Infrastructure::Data::Model::PriceBar > dataBars) inline private
Converts Alaris.Infrastructure.Data.Model.PriceBar to Alaris.Strategy.Bridge.PriceBar for volatility calculation.
Definition at line 1494 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.EvaluateSnapshot().
ConvertToTermStructurePoints()
IReadOnlyList< STTM001APoint > Alaris.Algorithm.STLN001A.ConvertToTermStructurePoints (OptionChainSnapshot optionChain, DateTime? evaluationDate = null) inline private
Converts option chain snapshot to term structure points for analysis.
Parameters
optionChain The option chain snapshot.
evaluationDate Optional evaluation date (defaults to snapshot timestamp).
Definition at line 1512 of file STLN001A.cs.
References Alaris.Core.Time.Days, Alaris.Infrastructure.Data.Model.OptionChainSnapshot.SpotPrice, and Alaris.Infrastructure.Data.Model.OptionChainSnapshot.Timestamp.
Referenced by Alaris.Algorithm.STLN001A.EvaluateSnapshot().
CreateOptionSymbol()
Symbol Alaris.Algorithm.STLN001A.CreateOptionSymbol (Symbol underlying, decimal strike, DateTime expiry, QCOptionRight right) inline private
Creates an option symbol from components.
Definition at line 1637 of file STLN001A.cs.
DataProviderSettings()
record Alaris.Algorithm.STLN001A.DataProviderSettings (Uri PolygonBaseUri, TimeSpan PolygonTimeout, Uri NasdaqBaseUri, TimeSpan NasdaqTimeout, Uri TreasuryBaseUri, TimeSpan TreasuryTimeout, TimeSpan MarketDataTimeout, TimeSpan ExecutionQuoteTimeout) inline sealed private
Definition at line 1816 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.LoadSettings().
EvaluatePositions()
void Alaris.Algorithm.STLN001A.EvaluatePositions () inline private
Main strategy evaluation logic. Called daily at 9:31 AM ET.
Definition at line 606 of file STLN001A.cs.
References Alaris.Algorithm.STLN001A._activePositions, Alaris.Algorithm.STLN001A._auditLogger, Alaris.Algorithm.STLN001A._strategySettings, Alaris.Algorithm.STLN001A.AreComponentsInitialised(), Alaris.Algorithm.STLN001A.EvaluateSymbol(), Alaris.Algorithm.STLN001A.GetCurrentAllocation(), and Alaris.Infrastructure.Events.Infrastructure.EVIF002A.LogAsync().
Referenced by Alaris.Algorithm.STLN001A.ScheduleDailyEvaluation().
EvaluateSnapshot()
EvaluationResult Alaris.Algorithm.STLN001A.EvaluateSnapshot (Symbol symbol, MarketDataSnapshot snapshot, bool useExecutionQuoteProvider) inline private
Definition at line 745 of file STLN001A.cs.
References Alaris.Algorithm.STLN001A._activePositions, Alaris.Algorithm.STLN001A._auditLogger, Alaris.Algorithm.STLN001A._positionEntryDates, Alaris.Algorithm.STLN001A._positionSizer, Alaris.Algorithm.STLN001A._signalGenerator, Alaris.Algorithm.STLN001A._strategySettings, Alaris.Algorithm.STLN001A._termStructureAnalyzer, Alaris.Algorithm.STLN001A._yangZhangEstimator, Alaris.Strategy.Core.STTM001A.Analyze(), Alaris.Strategy.Core.STCR003A.Calculate(), Alaris.Strategy.Risk.STRK001A.CalculateFromHistory(), Alaris.Algorithm.STLN001A.ConvertToPriceBars(), Alaris.Algorithm.STLN001A.ConvertToTermStructurePoints(), Alaris.Infrastructure.Data.Model.EarningsEvent.Date, Alaris.Infrastructure.Data.Model.DTmd002A, Alaris.Algorithm.STLN001A.ExecuteCalendarSpread(), Alaris.Strategy.Core.STCR001A.Generate(), Alaris.Algorithm.STLN001A.GetSpreadQuote(), Alaris.Infrastructure.Data.Model.MarketDataSnapshot.HistoricalBars, Alaris.Infrastructure.Events.Infrastructure.EVIF002A.LogAsync(), Alaris.Infrastructure.Data.Model.MarketDataSnapshot.NextEarnings, Alaris.Infrastructure.Data.Model.MarketDataSnapshot.OptionChain, Alaris.Algorithm.STLN001A.PopulateSignalLegs(), Alaris.Strategy.Hedge.STHD006A, Alaris.Infrastructure.Data.Model.MarketDataSnapshot.Timestamp, Alaris.Algorithm.STLN001A.TrySelectCalendarSpread(), and Alaris.Algorithm.STLN001A.ValidateForProduction().
Referenced by Alaris.Algorithm.STLN001A.EvaluateSymbol().
EvaluateSymbol()
EvaluationResult Alaris.Algorithm.STLN001A.EvaluateSymbol (Symbol symbol) inline private
Evaluates a single symbol for trading opportunity. Implements complete Alaris strategy workflow.
Parameters
symbol The symbol to evaluate.
Returns
Evaluation result summary.
Definition at line 708 of file STLN001A.cs.
References Alaris.Algorithm.STLN001A._dataProviderSettings, Alaris.Algorithm.STLN001A._marketDataAdapter, Alaris.Algorithm.STLN001A.EvaluateSnapshot(), and Alaris.Infrastructure.Data.Model.MarketDataSnapshot.NextEarnings.
Referenced by Alaris.Algorithm.STLN001A.EvaluatePositions().
ExecuteCalendarSpread()
OrderExecutionResult Alaris.Algorithm.STLN001A.ExecuteCalendarSpread (Symbol underlyingSymbol, CalendarSpreadSelection selection, DTmd002A quote, int contracts) inline private
Executes a calendar spread order using LEAN's combo order functionality.
Definition at line 1580 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.EvaluateSnapshot().
FeeSettings()
record Alaris.Algorithm.STLN001A.FeeSettings (decimal PerContract, decimal ExchangePerContract, decimal RegulatoryPerContract) inline sealed private
Definition at line 1890 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.LoadSettings().
FindLeanDataPath()
static string Alaris.Algorithm.STLN001A.FindLeanDataPath () inline static private
Finds the LEAN data path for universe files.
Definition at line 443 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.InitialiseUniverseSelection().
FindRepositoryRoot()
static string Alaris.Algorithm.STLN001A.FindRepositoryRoot () inline static private
Finds the repository root directory containing appsettings.jsonc.
Definition at line 516 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.BuildConfiguration().
GetCurrentAllocation()
decimal Alaris.Algorithm.STLN001A.GetCurrentAllocation () inline private
Gets current portfolio allocation to strategy positions.
Definition at line 982 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.EvaluatePositions().
GetRequiredDateTime()
static DateTime Alaris.Algorithm.STLN001A.GetRequiredDateTime (IConfiguration configuration, string key) inline static private
Definition at line 1940 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.LoadSettings().
GetRequiredDecimal()
static decimal Alaris.Algorithm.STLN001A.GetRequiredDecimal (IConfiguration configuration, string key) inline static private
Definition at line 1932 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.LoadSettings().
GetRequiredDouble()
static double Alaris.Algorithm.STLN001A.GetRequiredDouble (IConfiguration configuration, string key) inline static private
Definition at line 1924 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.LoadSettings().
GetRequiredInt()
static int Alaris.Algorithm.STLN001A.GetRequiredInt (IConfiguration configuration, string key) inline static private
Definition at line 1916 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.LoadSettings().
GetRequiredOptionRight()
static AlarisOptionRight Alaris.Algorithm.STLN001A.GetRequiredOptionRight (IConfiguration configuration, string key) inline static private
Definition at line 1956 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.LoadSettings().
GetRequiredUri()
static Uri Alaris.Algorithm.STLN001A.GetRequiredUri (IConfiguration configuration, string key) inline static private
Definition at line 1948 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.LoadSettings().
GetRequiredValue()
static string Alaris.Algorithm.STLN001A.GetRequiredValue (IConfiguration configuration, string key) inline static private
Definition at line 1908 of file STLN001A.cs.
GetSpreadQuote()
DTmd002A? Alaris.Algorithm.STLN001A.GetSpreadQuote (CalendarSpreadSelection selection, bool useExecutionQuoteProvider) inline private
Definition at line 1189 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.EvaluateSnapshot().
InitialiseAuditTrail()
void Alaris.Algorithm.STLN001A.InitialiseAuditTrail () inline private
Initialises audit trail and event sourcing.
Definition at line 475 of file STLN001A.cs.
References Alaris.Algorithm.STLN001A._auditLogger, and Alaris.Algorithm.STLN001A._eventStore.
Referenced by Alaris.Algorithm.STLN001A.Initialize().
InitialiseDataProviders()
void Alaris.Algorithm.STLN001A.InitialiseDataProviders () inline private
Initialises data providers from Alaris.Data.
Definition at line 256 of file STLN001A.cs.
References Alaris.Algorithm.STLN001A._configuration, Alaris.Algorithm.STLN001A._dataBridge, Alaris.Algorithm.STLN001A._dataProviderSettings, Alaris.Algorithm.STLN001A._earningsProvider, Alaris.Algorithm.STLN001A._executionQuoteProvider, Alaris.Algorithm.STLN001A._loggerFactory, Alaris.Algorithm.STLN001A._marketDataProvider, Alaris.Algorithm.STLN001A._riskFreeRateProvider, Alaris.Algorithm.STLN001A._timeProvider, Alaris.Algorithm.STLN001A.BuildConfiguration(), Alaris.Infrastructure.Data.Provider.DTpr004A.EnableCacheOnlyMode(), and Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.SetSessionDataPath().
Referenced by Alaris.Algorithm.STLN001A.Initialize().
InitialiseLogging()
void Alaris.Algorithm.STLN001A.InitialiseLogging () inline private
Initialises logging infrastructure. Bridges LEAN logging to Microsoft.Extensions.Logging.
Definition at line 240 of file STLN001A.cs.
References Alaris.Algorithm.STLN001A._logger, and Alaris.Algorithm.STLN001A._loggerFactory.
Referenced by Alaris.Algorithm.STLN001A.Initialize().
InitialiseProductionValidation()
void Alaris.Algorithm.STLN001A.InitialiseProductionValidation () inline private
Initialises production validation pipeline.
Definition at line 365 of file STLN001A.cs.
References Alaris.Algorithm.STLN001A._costValidator, Alaris.Algorithm.STLN001A._feeModel, Alaris.Algorithm.STLN001A._feeSettings, Alaris.Algorithm.STLN001A._gammaRiskManager, Alaris.Algorithm.STLN001A._liquidityValidator, Alaris.Algorithm.STLN001A._loggerFactory, Alaris.Algorithm.STLN001A._productionValidator, Alaris.Algorithm.STLN001A._validationSettings, and Alaris.Algorithm.STLN001A._vegaAnalyser.
Referenced by Alaris.Algorithm.STLN001A.Initialize().
InitialiseStrategyComponents()
void Alaris.Algorithm.STLN001A.InitialiseStrategyComponents () inline private
Initialises strategy analysis components from Alaris.Strategy.
Definition at line 334 of file STLN001A.cs.
References Alaris.Algorithm.STLN001A._dataBridge, Alaris.Algorithm.STLN001A._loggerFactory, Alaris.Algorithm.STLN001A._marketDataAdapter, Alaris.Algorithm.STLN001A._positionSizer, Alaris.Algorithm.STLN001A._pricingEngine, Alaris.Algorithm.STLN001A._signalGenerator, Alaris.Algorithm.STLN001A._termStructureAnalyzer, and Alaris.Algorithm.STLN001A._yangZhangEstimator.
Referenced by Alaris.Algorithm.STLN001A.Initialize().
InitialiseUniverseSelection()
void Alaris.Algorithm.STLN001A.InitialiseUniverseSelection () inline private
Initialises universe selection. Uses STUN001B (Polygon-based) which reads pre-generated universe files.
Definition at line 413 of file STLN001A.cs.
References Alaris.Algorithm.STLN001A._earningsProvider, Alaris.Algorithm.STLN001A._loggerFactory, Alaris.Algorithm.STLN001A._strategySettings, and Alaris.Algorithm.STLN001A.FindLeanDataPath().
Referenced by Alaris.Algorithm.STLN001A.Initialize().
Initialize()
override void Alaris.Algorithm.STLN001A.Initialize () inline
Initialises the algorithm at start. Called once by LEAN engine.
Definition at line 134 of file STLN001A.cs.
References Alaris.Algorithm.STLN001A._backtestSettings, Alaris.Algorithm.STLN001A._configuration, Alaris.Algorithm.STLN001A.BuildConfiguration(), Alaris.Algorithm.STLN001A.InitialiseAuditTrail(), Alaris.Algorithm.STLN001A.InitialiseDataProviders(), Alaris.Algorithm.STLN001A.InitialiseLogging(), Alaris.Algorithm.STLN001A.InitialiseProductionValidation(), Alaris.Algorithm.STLN001A.InitialiseStrategyComponents(), Alaris.Algorithm.STLN001A.InitialiseUniverseSelection(), Alaris.Algorithm.STLN001A.LoadSettings(), and Alaris.Algorithm.STLN001A.ScheduleDailyEvaluation().
IsQuoteValid()
static bool Alaris.Algorithm.STLN001A.IsQuoteValid (OptionContract contract) inline static private
Definition at line 1476 of file STLN001A.cs.
References Alaris.Infrastructure.Data.Model.OptionContract.Bid.
LoadSettings()
void Alaris.Algorithm.STLN001A.LoadSettings (IConfiguration configuration) inline private
Loads configuration-backed settings with validation.
Definition at line 539 of file STLN001A.cs.
References Alaris.Algorithm.STLN001A._backtestSettings, Alaris.Algorithm.STLN001A._dataProviderSettings, Alaris.Algorithm.STLN001A._feeSettings, Alaris.Algorithm.STLN001A._strategySettings, Alaris.Algorithm.STLN001A._validationSettings, Alaris.Algorithm.STLN001A.BacktestSettings(), Alaris.Algorithm.STLN001A.DataProviderSettings(), Alaris.Algorithm.STLN001A.FeeSettings(), Alaris.Algorithm.STLN001A.GetRequiredDateTime(), Alaris.Algorithm.STLN001A.GetRequiredDecimal(), Alaris.Algorithm.STLN001A.GetRequiredDouble(), Alaris.Algorithm.STLN001A.GetRequiredInt(), Alaris.Algorithm.STLN001A.GetRequiredOptionRight(), Alaris.Algorithm.STLN001A.GetRequiredUri(), Alaris.Algorithm.STLN001A.StrategySettings(), and Alaris.Algorithm.STLN001A.ValidationSettings().
Referenced by Alaris.Algorithm.STLN001A.Initialize().
OnEndOfAlgorithm()
override void Alaris.Algorithm.STLN001A.OnEndOfAlgorithm () inline
Called when the algorithm ends.
Definition at line 221 of file STLN001A.cs.
References Alaris.Algorithm.STLN001A._pricingEngine, and Alaris.Strategy.Bridge.STBR001A.Dispose().
OnOrderEvent()
override void Alaris.Algorithm.STLN001A.OnOrderEvent (OrderEvent orderEvent) inline
Handles order events from LEAN.
Parameters
orderEvent The order event.
Definition at line 1656 of file STLN001A.cs.
PopulateSignalLegs()
void Alaris.Algorithm.STLN001A.PopulateSignalLegs (STCR004A signal, CalendarSpreadSelection selection) inline private
Definition at line 1179 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.EvaluateSnapshot().
ScheduleDailyEvaluation()
void Alaris.Algorithm.STLN001A.ScheduleDailyEvaluation () inline private
Schedules daily strategy evaluation at market open + 1 minute.
Definition at line 486 of file STLN001A.cs.
References Alaris.Algorithm.STLN001A._strategySettings, and Alaris.Algorithm.STLN001A.EvaluatePositions().
Referenced by Alaris.Algorithm.STLN001A.Initialize().
StrategySettings()
record Alaris.Algorithm.STLN001A.StrategySettings (int DaysBeforeEarningsMin, int DaysBeforeEarningsMax, decimal MinimumDollarVolume, decimal MinimumPrice, decimal PortfolioAllocationLimit, decimal MaxPositionAllocation, int MaxConcurrentPositions, int MaxUniverseSymbols, int MaxCoarseSymbols, int EvaluationTimeHour, int EvaluationTimeMinute, AlarisOptionRight OptionRight, int RealisedVolatilityWindowDays, double DefaultImpliedVolatility) inline sealed private
Definition at line 1721 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.LoadSettings().
ToOptionType()
static OptionType Alaris.Algorithm.STLN001A.ToOptionType (AlarisOptionRight right) inline static private
Definition at line 1486 of file STLN001A.cs.
ToQcOptionRight()
static QCOptionRight Alaris.Algorithm.STLN001A.ToQcOptionRight (AlarisOptionRight right) inline static private
Definition at line 1481 of file STLN001A.cs.
TryGetContractForStrike()
static bool Alaris.Algorithm.STLN001A.TryGetContractForStrike (OptionChainSnapshot chain, DateTime expiry, decimal strike, AlarisOptionRight right, out OptionContract contract) inline static private
Definition at line 1450 of file STLN001A.cs.
TryResolveImpliedVolatility()
bool Alaris.Algorithm.STLN001A.TryResolveImpliedVolatility (OptionContract contract, double spotPrice, double riskFreeRate, double dividendYield, DateTime valuationDate, AlarisOptionRight right, out double impliedVolatility, out bool usedSynthetic) inline private
Definition at line 1381 of file STLN001A.cs.
References Alaris.Infrastructure.Data.Model.OptionContract.Expiration, Alaris.Core.Time.CRTM005A.FromDateTime(), Alaris.Infrastructure.Data.Model.OptionContract.ImpliedVolatility, Alaris.Infrastructure.Data.Model.OptionContract.Mid, and Alaris.Infrastructure.Data.Model.OptionContract.Strike.
TrySelectCalendarSpread()
bool Alaris.Algorithm.STLN001A.TrySelectCalendarSpread (MarketDataSnapshot snapshot, DateTime earningsDate, AlarisOptionRight right, out CalendarSpreadSelection selection, out string detail) inline private
Definition at line 1036 of file STLN001A.cs.
References Alaris.Infrastructure.Data.Model.OptionChainSnapshot.Contracts, Alaris.Infrastructure.Data.Model.MarketDataSnapshot.OptionChain, and Alaris.Infrastructure.Data.Model.OptionContract.Timestamp.
Referenced by Alaris.Algorithm.STLN001A.EvaluateSnapshot().
ValidateForProduction()
STHD006A Alaris.Algorithm.STLN001A.ValidateForProduction (STCR004A signal, MarketDataSnapshot snapshot, CalendarSpreadSelection selection, int proposedContracts) inline private
Validates a signal for production using STHD005A.
Definition at line 996 of file STLN001A.cs.
References Alaris.Strategy.Core.STCR004A.EarningsDate, Alaris.Infrastructure.Data.Model.MarketDataSnapshot.SpotPrice, Alaris.Strategy.Core.STCR004A.Symbol, and Alaris.Infrastructure.Data.Model.MarketDataSnapshot.Timestamp.
Referenced by Alaris.Algorithm.STLN001A.EvaluateSnapshot().
ValidationSettings()
record Alaris.Algorithm.STLN001A.ValidationSettings (double MaxVegaCorrelation, int MinimumVegaObservations, int VegaCorrelationLookbackDays, double MaxPositionToVolumeRatio, double MaxPositionToOpenInterestRatio, double DeltaRehedgeThreshold, double GammaWarningThreshold, double MoneynessAlertThreshold) inline sealed private
Definition at line 1857 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.LoadSettings().
Member Data Documentation
_activePositions
readonly HashSet<Symbol> Alaris.Algorithm.STLN001A._activePositions = new() private
Definition at line 125 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.EvaluatePositions(), and Alaris.Algorithm.STLN001A.EvaluateSnapshot().
_auditLogger
EVIF002A? Alaris.Algorithm.STLN001A._auditLogger private
Definition at line 114 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.EvaluatePositions(), Alaris.Algorithm.STLN001A.EvaluateSnapshot(), and Alaris.Algorithm.STLN001A.InitialiseAuditTrail().
_backtestSettings
BacktestSettings Alaris.Algorithm.STLN001A._backtestSettings = BacktestSettings.Empty private
Definition at line 80 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.Initialize(), and Alaris.Algorithm.STLN001A.LoadSettings().
_configuration
IConfiguration? Alaris.Algorithm.STLN001A._configuration private
Definition at line 119 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.InitialiseDataProviders(), and Alaris.Algorithm.STLN001A.Initialize().
_costValidator
STCS006A? Alaris.Algorithm.STLN001A._costValidator private
Definition at line 105 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.InitialiseProductionValidation().
_dataBridge
AlarisDataBridge? Alaris.Algorithm.STLN001A._dataBridge private
Definition at line 88 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.InitialiseDataProviders(), and Alaris.Algorithm.STLN001A.InitialiseStrategyComponents().
_dataProviderSettings
DataProviderSettings Alaris.Algorithm.STLN001A._dataProviderSettings = DataProviderSettings.Empty private
Definition at line 81 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.EvaluateSymbol(), Alaris.Algorithm.STLN001A.InitialiseDataProviders(), and Alaris.Algorithm.STLN001A.LoadSettings().
_earningsProvider
DTpr004A? Alaris.Algorithm.STLN001A._earningsProvider private
Definition at line 90 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.InitialiseDataProviders(), and Alaris.Algorithm.STLN001A.InitialiseUniverseSelection().
_eventStore
EVIF001A? Alaris.Algorithm.STLN001A._eventStore private
Definition at line 113 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.InitialiseAuditTrail().
_executionQuoteProvider
DTpr002A? Alaris.Algorithm.STLN001A._executionQuoteProvider private
Definition at line 92 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.InitialiseDataProviders().
_feeModel
STCS005A? Alaris.Algorithm.STLN001A._feeModel private
Definition at line 104 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.InitialiseProductionValidation().
_feeSettings
FeeSettings Alaris.Algorithm.STLN001A._feeSettings = FeeSettings.Empty private
Definition at line 83 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.InitialiseProductionValidation(), and Alaris.Algorithm.STLN001A.LoadSettings().
_gammaRiskManager
STHD003A? Alaris.Algorithm.STLN001A._gammaRiskManager private
Definition at line 108 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.InitialiseProductionValidation().
_liquidityValidator
STCS008A? Alaris.Algorithm.STLN001A._liquidityValidator private
Definition at line 107 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.InitialiseProductionValidation().
_logger
ILogger<STLN001A>? Alaris.Algorithm.STLN001A._logger private
Definition at line 117 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.InitialiseLogging().
_loggerFactory
ILoggerFactory? Alaris.Algorithm.STLN001A._loggerFactory private
Definition at line 118 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.InitialiseDataProviders(), Alaris.Algorithm.STLN001A.InitialiseLogging(), Alaris.Algorithm.STLN001A.InitialiseProductionValidation(), Alaris.Algorithm.STLN001A.InitialiseStrategyComponents(), and Alaris.Algorithm.STLN001A.InitialiseUniverseSelection().
_marketDataAdapter
DataBridgeMarketDataAdapter? Alaris.Algorithm.STLN001A._marketDataAdapter private
Definition at line 98 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.EvaluateSymbol(), and Alaris.Algorithm.STLN001A.InitialiseStrategyComponents().
_marketDataProvider
DTpr003A? Alaris.Algorithm.STLN001A._marketDataProvider private
Definition at line 89 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.InitialiseDataProviders().
_positionEntryDates
readonly Dictionary<Symbol, DateTime> Alaris.Algorithm.STLN001A._positionEntryDates = new() private
Definition at line 126 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.EvaluateSnapshot().
_positionSizer
STRK001A? Alaris.Algorithm.STLN001A._positionSizer private
Definition at line 99 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.EvaluateSnapshot(), and Alaris.Algorithm.STLN001A.InitialiseStrategyComponents().
_pricingEngine
STBR001A? Alaris.Algorithm.STLN001A._pricingEngine private
Definition at line 100 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.InitialiseStrategyComponents(), and Alaris.Algorithm.STLN001A.OnEndOfAlgorithm().
_productionValidator
STHD005A? Alaris.Algorithm.STLN001A._productionValidator private
Definition at line 103 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.InitialiseProductionValidation().
_riskFreeRateProvider
DTpr005A? Alaris.Algorithm.STLN001A._riskFreeRateProvider private
Definition at line 91 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.InitialiseDataProviders().
_signalGenerator
STCR001A? Alaris.Algorithm.STLN001A._signalGenerator private
Definition at line 97 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.EvaluateSnapshot(), and Alaris.Algorithm.STLN001A.InitialiseStrategyComponents().
_strategySettings
StrategySettings Alaris.Algorithm.STLN001A._strategySettings = StrategySettings.Empty private
Definition at line 79 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.EvaluatePositions(), Alaris.Algorithm.STLN001A.EvaluateSnapshot(), Alaris.Algorithm.STLN001A.InitialiseUniverseSelection(), Alaris.Algorithm.STLN001A.LoadSettings(), and Alaris.Algorithm.STLN001A.ScheduleDailyEvaluation().
_termStructureAnalyzer
STTM001A? Alaris.Algorithm.STLN001A._termStructureAnalyzer private
Definition at line 96 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.EvaluateSnapshot(), and Alaris.Algorithm.STLN001A.InitialiseStrategyComponents().
_timeProvider
AlarisTimeProvider? Alaris.Algorithm.STLN001A._timeProvider private
Definition at line 122 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.InitialiseDataProviders().
_validationSettings
ValidationSettings Alaris.Algorithm.STLN001A._validationSettings = ValidationSettings.Empty private
Definition at line 82 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.InitialiseProductionValidation(), and Alaris.Algorithm.STLN001A.LoadSettings().
_vegaAnalyser
STHD001A? Alaris.Algorithm.STLN001A._vegaAnalyser private
Definition at line 106 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.InitialiseProductionValidation().
_yangZhangEstimator
STCR003A? Alaris.Algorithm.STLN001A._yangZhangEstimator private
Definition at line 95 of file STLN001A.cs.
Referenced by Alaris.Algorithm.STLN001A.EvaluateSnapshot(), and Alaris.Algorithm.STLN001A.InitialiseStrategyComponents().
FrontIVHistory
IReadOnlyList<double> Alaris.Algorithm.STLN001A.FrontIVHistory private
Definition at line 1242 of file STLN001A.cs.
The documentation for this class was generated from the following file:
src/Alaris.Algorithm/STLN001A.cs