Alaris: Alaris.Infrastructure.Events.Serialization.EVsr001A Class Reference
Alaris.Infrastructure.Events.Serialization.EVsr001A Class Reference
Binary serialization adapter for event envelopes. Component ID: EVsr001A.
Static Public Member Functions
static int EncodeEventEnvelope (EVCR003A envelope, Span< byte > buffer)
Encodes an EventEnvelope to binary format.
static EVCR003A DecodeEventEnvelope (ReadOnlySpan< byte > buffer)
Decodes an EventEnvelope from binary format.
static int GetEncodedSize (EVCR003A envelope)
Gets the estimated encoded size for an event envelope.
Static Private Member Functions
static void WriteFixedString (Span< byte > buffer, string? value, int length)
static string ReadFixedString (ReadOnlySpan< byte > buffer, int length)
static ? string ReadNullableFixedString (ReadOnlySpan< byte > buffer, int length)
Static Private Attributes
const byte FormatVersion = 1
Detailed Description
Binary serialization adapter for event envelopes. Component ID: EVsr001A.
Provides dual-mode serialization:
Binary (SBE-style) for hot path storage
JSON for debugging and human-readable audit logs
Rule 17 Compliance: All serialized events remain immutable and traceable.
Definition at line 20 of file EVsr001A.cs.
Member Function Documentation
DecodeEventEnvelope()
static EVCR003A Alaris.Infrastructure.Events.Serialization.EVsr001A.DecodeEventEnvelope (ReadOnlySpan< byte > buffer) inline static
Decodes an EventEnvelope from binary format.
Definition at line 86 of file EVsr001A.cs.
References Alaris.Infrastructure.Events.Core.EVCR003A, Alaris.Infrastructure.Events.Serialization.EVsr001A.FormatVersion, Alaris.Infrastructure.Events.Serialization.EVsr001A.ReadFixedString(), and Alaris.Infrastructure.Events.Serialization.EVsr001A.ReadNullableFixedString().
Referenced by Alaris.Test.Unit.TSUN030A.EventEnvelope_RoundTrip_PreservesAllFields().
EncodeEventEnvelope()
static int Alaris.Infrastructure.Events.Serialization.EVsr001A.EncodeEventEnvelope (EVCR003A envelope, Span< byte > buffer) inline static
Encodes an EventEnvelope to binary format.
Parameters
envelope Source event envelope.
buffer Target buffer (minimum 4KB recommended).
Returns
Number of bytes written.
Definition at line 30 of file EVsr001A.cs.
References Alaris.Infrastructure.Events.Serialization.EVsr001A.FormatVersion, and Alaris.Infrastructure.Events.Serialization.EVsr001A.WriteFixedString().
Referenced by Alaris.Test.Unit.TSUN030A.EventEnvelope_RoundTrip_PreservesAllFields(), and Alaris.Test.Unit.TSUN030A.GetEncodedSize_ReturnsCorrectSize().
GetEncodedSize()
static int Alaris.Infrastructure.Events.Serialization.EVsr001A.GetEncodedSize (EVCR003A envelope) inline static
Gets the estimated encoded size for an event envelope.
Definition at line 151 of file EVsr001A.cs.
Referenced by Alaris.Test.Unit.TSUN030A.GetEncodedSize_ReturnsCorrectSize().
ReadFixedString()
static string Alaris.Infrastructure.Events.Serialization.EVsr001A.ReadFixedString (ReadOnlySpan< byte > buffer, int length) inline static private
Definition at line 171 of file EVsr001A.cs.
Referenced by Alaris.Infrastructure.Events.Serialization.EVsr001A.DecodeEventEnvelope(), and Alaris.Infrastructure.Events.Serialization.EVsr001A.ReadNullableFixedString().
ReadNullableFixedString()
static ? string Alaris.Infrastructure.Events.Serialization.EVsr001A.ReadNullableFixedString (ReadOnlySpan< byte > buffer, int length) inline static private
Definition at line 182 of file EVsr001A.cs.
References Alaris.Infrastructure.Events.Serialization.EVsr001A.ReadFixedString().
Referenced by Alaris.Infrastructure.Events.Serialization.EVsr001A.DecodeEventEnvelope().
WriteFixedString()
static void Alaris.Infrastructure.Events.Serialization.EVsr001A.WriteFixedString (Span< byte > buffer, string? value, int length) inline static private
Definition at line 161 of file EVsr001A.cs.
Referenced by Alaris.Infrastructure.Events.Serialization.EVsr001A.EncodeEventEnvelope().
Member Data Documentation
FormatVersion
const byte Alaris.Infrastructure.Events.Serialization.EVsr001A.FormatVersion = 1 static private
Definition at line 22 of file EVsr001A.cs.
Referenced by Alaris.Infrastructure.Events.Serialization.EVsr001A.DecodeEventEnvelope(), and Alaris.Infrastructure.Events.Serialization.EVsr001A.EncodeEventEnvelope().
The documentation for this class was generated from the following file:
src/Alaris.Infrastructure/Events/Serialization/EVsr001A.cs