Alaris: Alaris.Host.Application.Command.APcm002A Class Reference
Alaris.Host.Application.Command.APcm002A Class Reference sealed
APcm002A: Configuration management command for Alaris.
Public Member Functions
override int Execute (CommandContext context, ConfigSettings settings)
Executes the config command.
Static Private Member Functions
static int ShowConfiguration (bool secretsOnly)
static int SetConfiguration (string? key, string? value)
static int ValidateConfiguration ()
static int ShowHelp ()
static ? string FindConfigFile (string[] paths)
static ? JsonNode LoadJsonc (string path)
static string StripJsonComments (string json)
static void AddConfigRow (Table table, string key, JsonNode? local, JsonNode? baseConfig, bool isSecret)
static ? string GetNestedValue (JsonNode? node, params string[] path)
static string MaskSensitive (string key, string value)
Static Private Attributes
static readonly string[] ConfigPaths
static readonly string[] BasePaths
Detailed Description
APcm002A: Configuration management command for Alaris.
Definition at line 48 of file APcm002A.cs.
Member Function Documentation
AddConfigRow()
static void Alaris.Host.Application.Command.APcm002A.AddConfigRow (Table table, string key, JsonNode? local, JsonNode? baseConfig, bool isSecret) inline static private
Definition at line 395 of file APcm002A.cs.
References Alaris.Host.Application.Command.APcm002A.GetNestedValue(), and Alaris.Host.Application.Command.APcm002A.MaskSensitive().
Referenced by Alaris.Host.Application.Command.APcm002A.ShowConfiguration().
Execute()
override int Alaris.Host.Application.Command.APcm002A.Execute (CommandContext context, ConfigSettings settings) inline
Executes the config command.
Definition at line 69 of file APcm002A.cs.
References Alaris.Host.Application.Command.ConfigSettings.Action, Alaris.Host.Application.Command.ConfigSettings.Key, Alaris.Host.Application.Command.ConfigSettings.SecretsOnly, Alaris.Host.Application.Command.APcm002A.SetConfiguration(), Alaris.Host.Application.Command.APcm002A.ShowConfiguration(), Alaris.Host.Application.Command.APcm002A.ShowHelp(), Alaris.Host.Application.Command.APcm002A.ValidateConfiguration(), and Alaris.Host.Application.Command.ConfigSettings.Value.
FindConfigFile()
static ? string Alaris.Host.Application.Command.APcm002A.FindConfigFile (string[] paths) inline static private
Definition at line 300 of file APcm002A.cs.
Referenced by Alaris.Host.Application.Command.APcm002A.SetConfiguration(), Alaris.Host.Application.Command.APcm002A.ShowConfiguration(), and Alaris.Host.Application.Command.APcm002A.ValidateConfiguration().
GetNestedValue()
static ? string Alaris.Host.Application.Command.APcm002A.GetNestedValue (JsonNode? node, params string[] path) inline static private
Definition at line 412 of file APcm002A.cs.
Referenced by Alaris.Host.Application.Command.APcm002A.AddConfigRow(), and Alaris.Host.Application.Command.APcm002A.ValidateConfiguration().
LoadJsonc()
static ? JsonNode Alaris.Host.Application.Command.APcm002A.LoadJsonc (string path) inline static private
Definition at line 312 of file APcm002A.cs.
References Alaris.Host.Application.Command.APcm002A.StripJsonComments().
Referenced by Alaris.Host.Application.Command.APcm002A.SetConfiguration(), Alaris.Host.Application.Command.APcm002A.ShowConfiguration(), and Alaris.Host.Application.Command.APcm002A.ValidateConfiguration().
MaskSensitive()
static string Alaris.Host.Application.Command.APcm002A.MaskSensitive (string key, string value) inline static private
Definition at line 435 of file APcm002A.cs.
Referenced by Alaris.Host.Application.Command.APcm002A.AddConfigRow().
SetConfiguration()
static int Alaris.Host.Application.Command.APcm002A.SetConfiguration (string? key, string? value) inline static private
Definition at line 147 of file APcm002A.cs.
References Alaris.Host.Application.Command.APcm002A.ConfigPaths, Alaris.Host.Application.Command.APcm002A.FindConfigFile(), and Alaris.Host.Application.Command.APcm002A.LoadJsonc().
Referenced by Alaris.Host.Application.Command.APcm002A.Execute().
ShowConfiguration()
static int Alaris.Host.Application.Command.APcm002A.ShowConfiguration (bool secretsOnly) inline static private
Definition at line 80 of file APcm002A.cs.
References Alaris.Host.Application.Command.APcm002A.AddConfigRow(), Alaris.Host.Application.Command.APcm002A.BasePaths, Alaris.Host.Application.Command.APcm002A.ConfigPaths, Alaris.Host.Application.Command.APcm002A.FindConfigFile(), and Alaris.Host.Application.Command.APcm002A.LoadJsonc().
Referenced by Alaris.Host.Application.Command.APcm002A.Execute().
ShowHelp()
static int Alaris.Host.Application.Command.APcm002A.ShowHelp () inline static private
Definition at line 283 of file APcm002A.cs.
Referenced by Alaris.Host.Application.Command.APcm002A.Execute().
StripJsonComments()
static string Alaris.Host.Application.Command.APcm002A.StripJsonComments (string json) inline static private
Definition at line 327 of file APcm002A.cs.
Referenced by Alaris.Host.Application.Command.APcm002A.LoadJsonc().
ValidateConfiguration()
static int Alaris.Host.Application.Command.APcm002A.ValidateConfiguration () inline static private
Definition at line 219 of file APcm002A.cs.
References Alaris.Host.Application.Command.APcm002A.BasePaths, Alaris.Host.Application.Command.APcm002A.ConfigPaths, Alaris.Host.Application.Command.APcm002A.FindConfigFile(), Alaris.Host.Application.Command.APcm002A.GetNestedValue(), and Alaris.Host.Application.Command.APcm002A.LoadJsonc().
Referenced by Alaris.Host.Application.Command.APcm002A.Execute().
Member Data Documentation
BasePaths
readonly string [] Alaris.Host.Application.Command.APcm002A.BasePaths static private
Initial value:
=
    [
        "appsettings.jsonc",
        "../appsettings.jsonc",
        "../../appsettings.jsonc",
        "../../../appsettings.jsonc"
    ]
Definition at line 58 of file APcm002A.cs.
Referenced by Alaris.Host.Application.Command.APcm002A.ShowConfiguration(), and Alaris.Host.Application.Command.APcm002A.ValidateConfiguration().
ConfigPaths
readonly string [] Alaris.Host.Application.Command.APcm002A.ConfigPaths static private
Initial value:
=
    [
        "appsettings.local.jsonc",
        "../appsettings.local.jsonc",
        "../../appsettings.local.jsonc",
        "../../../appsettings.local.jsonc"
    ]
Definition at line 50 of file APcm002A.cs.
Referenced by Alaris.Host.Application.Command.APcm002A.SetConfiguration(), Alaris.Host.Application.Command.APcm002A.ShowConfiguration(), and Alaris.Host.Application.Command.APcm002A.ValidateConfiguration().
The documentation for this class was generated from the following file:
src/Alaris.Host/Application/Command/APcm002A.cs