Alaris: Alaris.Core.Pricing.CRSL001A Class Reference
Alaris.Core.Pricing.CRSL001A Class Reference sealed
Complete solver for double boundary options. Stage 1: QD+ (fast). Stage 2: FP-B' Kim (accurate).
Public Member Functions
CRSL001A (double spot, double strike, double maturity, double rate, double dividendYield, double volatility, bool isCall, int collocationPoints=50, bool useRefinement=true)
Initializes the double boundary solver.
DoubleBoundaryResult Solve ()
Solves for both boundaries using QD+ approximation and optional Kim refinement.
Private Member Functions
DoubleBoundaryResult CreateNearExpiryResult (NearExpiryValidation validation)
Creates result for near-expiry regime where QD+ is numerically unstable.
double double lowerInitial CalculateInitialBoundaries ()
DoubleBoundaryResult CreateQdOnlyResult (double upperInitial, double lowerInitial)
Creates result using only QD+ approximation without refinement.
DoubleBoundaryResult ApplyKimRefinement (double upperInitial, double lowerInitial)
Applies Kim refinement to initial QD+ boundaries using CRSL002A.
bool DetectDoubleBoundaryRegime ()
Detects if the option is in a double boundary regime.
bool ValidateBoundaries (double upper, double lower)
Validates boundary values for consistency.
Static Private Member Functions
static DoubleBoundaryResult CreateSingleBoundaryResult (double upperInitial, double lowerInitial)
Creates result for single boundary regime.
Private Attributes
readonly double _spot
readonly double _strike
readonly double _maturity
readonly double _rate
readonly double _dividendYield
readonly double _volatility
readonly bool _isCall
readonly int _collocationPoints
readonly bool _useRefinement
double upperInitial
Calculates initial boundary estimates using QD+ approximation (CRAP001A).
Detailed Description
Complete solver for double boundary options. Stage 1: QD+ (fast). Stage 2: FP-B' Kim (accurate).
Definition at line 16 of file CRSL001A.cs.
Constructor & Destructor Documentation
CRSL001A()
Alaris.Core.Pricing.CRSL001A.CRSL001A (double spot, double strike, double maturity, double rate, double dividendYield, double volatility, bool isCall, int collocationPoints = 50, bool useRefinement = true) inline
Initializes the double boundary solver.
Parameters
spot Current asset price
strike Strike price
maturity Time to maturity (years)
rate Risk-free rate (negative for negative rate regime)
dividendYield Dividend yield (negative for negative rate regime)
volatility Volatility
isCall True for call, false for put
collocationPoints Number of time points (default 50)
useRefinement Use FP-B' Kim refinement (default FALSE until CRSL002A migrated)
Exceptions
BoundsViolationException Thrown if inputs violate algorithm bounds.
Definition at line 41 of file CRSL001A.cs.
References Alaris.Core.Pricing.CRSL001A._collocationPoints, Alaris.Core.Pricing.CRSL001A._dividendYield, Alaris.Core.Pricing.CRSL001A._isCall, Alaris.Core.Pricing.CRSL001A._maturity, Alaris.Core.Pricing.CRSL001A._rate, Alaris.Core.Pricing.CRSL001A._spot, Alaris.Core.Pricing.CRSL001A._strike, Alaris.Core.Pricing.CRSL001A._useRefinement, Alaris.Core.Pricing.CRSL001A._volatility, and Alaris.Core.Validation.AlgorithmBounds.ValidateDoubleBoundaryInputs().
Member Function Documentation
ApplyKimRefinement()
DoubleBoundaryResult Alaris.Core.Pricing.CRSL001A.ApplyKimRefinement (double upperInitial, double lowerInitial) inline private
Applies Kim refinement to initial QD+ boundaries using CRSL002A.
Definition at line 201 of file CRSL001A.cs.
References Alaris.Core.Pricing.CRSL001A._collocationPoints, Alaris.Core.Pricing.CRSL001A._dividendYield, Alaris.Core.Pricing.CRSL001A._isCall, Alaris.Core.Pricing.CRSL001A._maturity, Alaris.Core.Pricing.CRSL001A._rate, Alaris.Core.Pricing.CRSL001A._spot, Alaris.Core.Pricing.CRSL001A._strike, Alaris.Core.Pricing.CRSL001A._volatility, Alaris.Core.Pricing.CRSL002A.SolveBoundaries(), Alaris.Core.Pricing.CRSL001A.upperInitial, and Alaris.Core.Pricing.CRSL001A.ValidateBoundaries().
Referenced by Alaris.Core.Pricing.CRSL001A.Solve().
CalculateInitialBoundaries()
double double lowerInitial Alaris.Core.Pricing.CRSL001A.CalculateInitialBoundaries () inline private
Definition at line 151 of file CRSL001A.cs.
References Alaris.Core.Pricing.CRSL001A._dividendYield, Alaris.Core.Pricing.CRSL001A._isCall, Alaris.Core.Pricing.CRSL001A._maturity, Alaris.Core.Pricing.CRSL001A._rate, Alaris.Core.Pricing.CRSL001A._spot, Alaris.Core.Pricing.CRSL001A._strike, Alaris.Core.Pricing.CRSL001A._volatility, and Alaris.Core.Pricing.CRAP001A.CalculateBoundaries().
Referenced by Alaris.Core.Pricing.CRSL001A.Solve().
CreateNearExpiryResult()
DoubleBoundaryResult Alaris.Core.Pricing.CRSL001A.CreateNearExpiryResult (NearExpiryValidation validation) inline private
Creates result for near-expiry regime where QD+ is numerically unstable.
Definition at line 117 of file CRSL001A.cs.
References Alaris.Core.Pricing.CRSL001A._isCall, Alaris.Core.Pricing.CRSL001A._maturity, Alaris.Core.Pricing.CRSL001A._strike, and Alaris.Core.Pricing.CRSL001A._volatility.
Referenced by Alaris.Core.Pricing.CRSL001A.Solve().
CreateQdOnlyResult()
DoubleBoundaryResult Alaris.Core.Pricing.CRSL001A.CreateQdOnlyResult (double upperInitial, double lowerInitial) inline private
Creates result using only QD+ approximation without refinement.
Definition at line 182 of file CRSL001A.cs.
References Alaris.Core.Pricing.CRSL001A.upperInitial, and Alaris.Core.Pricing.CRSL001A.ValidateBoundaries().
Referenced by Alaris.Core.Pricing.CRSL001A.Solve().
CreateSingleBoundaryResult()
static DoubleBoundaryResult Alaris.Core.Pricing.CRSL001A.CreateSingleBoundaryResult (double upperInitial, double lowerInitial) inline static private
Creates result for single boundary regime.
Definition at line 163 of file CRSL001A.cs.
References Alaris.Core.Pricing.CRSL001A.upperInitial.
Referenced by Alaris.Core.Pricing.CRSL001A.Solve().
DetectDoubleBoundaryRegime()
bool Alaris.Core.Pricing.CRSL001A.DetectDoubleBoundaryRegime () inline private
Detects if the option is in a double boundary regime.
Definition at line 235 of file CRSL001A.cs.
References Alaris.Core.Pricing.CRSL001A._dividendYield, Alaris.Core.Pricing.CRSL001A._isCall, and Alaris.Core.Pricing.CRSL001A._rate.
Referenced by Alaris.Core.Pricing.CRSL001A.Solve().
Solve()
DoubleBoundaryResult Alaris.Core.Pricing.CRSL001A.Solve () inline
Solves for both boundaries using QD+ approximation and optional Kim refinement.
For very short maturities (T < 3/252 years ≈ 3 trading days), the method uses the near-expiry handler to avoid numerical singularities in the QD+ asymptotic expansion.
Returns
Solution containing boundaries and metadata
Definition at line 81 of file CRSL001A.cs.
References Alaris.Core.Pricing.CRSL001A._maturity, Alaris.Core.Pricing.CRSL001A._useRefinement, Alaris.Core.Pricing.CRSL001A.ApplyKimRefinement(), Alaris.Core.Pricing.CRSL001A.CalculateInitialBoundaries(), Alaris.Core.Pricing.CRSL001A.CreateNearExpiryResult(), Alaris.Core.Pricing.CRSL001A.CreateQdOnlyResult(), Alaris.Core.Pricing.CRSL001A.CreateSingleBoundaryResult(), Alaris.Core.Pricing.CRSL001A.DetectDoubleBoundaryRegime(), Alaris.Core.Pricing.NearExpiryValidation, Alaris.Core.Pricing.CRSL001A.upperInitial, and Alaris.Core.Pricing.CREX001A.Validate().
ValidateBoundaries()
bool Alaris.Core.Pricing.CRSL001A.ValidateBoundaries (double upper, double lower) inline private
Validates boundary values for consistency.
Definition at line 256 of file CRSL001A.cs.
References Alaris.Core.Pricing.CRSL001A._isCall, and Alaris.Core.Pricing.CRSL001A._strike.
Referenced by Alaris.Core.Pricing.CRSL001A.ApplyKimRefinement(), and Alaris.Core.Pricing.CRSL001A.CreateQdOnlyResult().
Member Data Documentation
_collocationPoints
readonly int Alaris.Core.Pricing.CRSL001A._collocationPoints private
Definition at line 25 of file CRSL001A.cs.
Referenced by Alaris.Core.Pricing.CRSL001A.CRSL001A(), and Alaris.Core.Pricing.CRSL001A.ApplyKimRefinement().
_dividendYield
readonly double Alaris.Core.Pricing.CRSL001A._dividendYield private
Definition at line 22 of file CRSL001A.cs.
Referenced by Alaris.Core.Pricing.CRSL001A.CRSL001A(), Alaris.Core.Pricing.CRSL001A.ApplyKimRefinement(), Alaris.Core.Pricing.CRSL001A.CalculateInitialBoundaries(), and Alaris.Core.Pricing.CRSL001A.DetectDoubleBoundaryRegime().
_isCall
readonly bool Alaris.Core.Pricing.CRSL001A._isCall private
Definition at line 24 of file CRSL001A.cs.
Referenced by Alaris.Core.Pricing.CRSL001A.CRSL001A(), Alaris.Core.Pricing.CRSL001A.ApplyKimRefinement(), Alaris.Core.Pricing.CRSL001A.CalculateInitialBoundaries(), Alaris.Core.Pricing.CRSL001A.CreateNearExpiryResult(), Alaris.Core.Pricing.CRSL001A.DetectDoubleBoundaryRegime(), and Alaris.Core.Pricing.CRSL001A.ValidateBoundaries().
_maturity
readonly double Alaris.Core.Pricing.CRSL001A._maturity private
Definition at line 20 of file CRSL001A.cs.
Referenced by Alaris.Core.Pricing.CRSL001A.CRSL001A(), Alaris.Core.Pricing.CRSL001A.ApplyKimRefinement(), Alaris.Core.Pricing.CRSL001A.CalculateInitialBoundaries(), Alaris.Core.Pricing.CRSL001A.CreateNearExpiryResult(), and Alaris.Core.Pricing.CRSL001A.Solve().
_rate
readonly double Alaris.Core.Pricing.CRSL001A._rate private
Definition at line 21 of file CRSL001A.cs.
Referenced by Alaris.Core.Pricing.CRSL001A.CRSL001A(), Alaris.Core.Pricing.CRSL001A.ApplyKimRefinement(), Alaris.Core.Pricing.CRSL001A.CalculateInitialBoundaries(), and Alaris.Core.Pricing.CRSL001A.DetectDoubleBoundaryRegime().
_spot
readonly double Alaris.Core.Pricing.CRSL001A._spot private
Definition at line 18 of file CRSL001A.cs.
Referenced by Alaris.Core.Pricing.CRSL001A.CRSL001A(), Alaris.Core.Pricing.CRSL001A.ApplyKimRefinement(), and Alaris.Core.Pricing.CRSL001A.CalculateInitialBoundaries().
_strike
readonly double Alaris.Core.Pricing.CRSL001A._strike private
Definition at line 19 of file CRSL001A.cs.
Referenced by Alaris.Core.Pricing.CRSL001A.CRSL001A(), Alaris.Core.Pricing.CRSL001A.ApplyKimRefinement(), Alaris.Core.Pricing.CRSL001A.CalculateInitialBoundaries(), Alaris.Core.Pricing.CRSL001A.CreateNearExpiryResult(), and Alaris.Core.Pricing.CRSL001A.ValidateBoundaries().
_useRefinement
readonly bool Alaris.Core.Pricing.CRSL001A._useRefinement private
Definition at line 26 of file CRSL001A.cs.
Referenced by Alaris.Core.Pricing.CRSL001A.CRSL001A(), and Alaris.Core.Pricing.CRSL001A.Solve().
_volatility
readonly double Alaris.Core.Pricing.CRSL001A._volatility private
Definition at line 23 of file CRSL001A.cs.
Referenced by Alaris.Core.Pricing.CRSL001A.CRSL001A(), Alaris.Core.Pricing.CRSL001A.ApplyKimRefinement(), Alaris.Core.Pricing.CRSL001A.CalculateInitialBoundaries(), and Alaris.Core.Pricing.CRSL001A.CreateNearExpiryResult().
upperInitial
double Alaris.Core.Pricing.CRSL001A.upperInitial private
Calculates initial boundary estimates using QD+ approximation (CRAP001A).
Definition at line 151 of file CRSL001A.cs.
Referenced by Alaris.Core.Pricing.CRSL001A.ApplyKimRefinement(), Alaris.Core.Pricing.CRSL001A.CreateQdOnlyResult(), Alaris.Core.Pricing.CRSL001A.CreateSingleBoundaryResult(), and Alaris.Core.Pricing.CRSL001A.Solve().
The documentation for this class was generated from the following file:
src/Alaris.Core/Pricing/CRSL001A.cs