Alaris: Alaris.Core.Math.CRCH001A Class Reference
Alaris.Core.Math.CRCH001A Class Reference
Chebyshev polynomial infrastructure for spectral collocation methods.
Static Public Member Functions
static double[] ChebyshevNodes (int n, double a=0.0, double b=1.0)
Generates Chebyshev nodes of the first kind on interval [a, b].
static double[] ChebyshevLobattoNodes (int n, double a=0.0, double b=1.0)
Generates Chebyshev-Lobatto nodes (extrema of T_n) including endpoints.
static double ChebyshevT (int n, double x)
Evaluates the Chebyshev polynomial T_n(x) using the recurrence relation.
static double[] BarycentricWeights (int n)
Computes barycentric interpolation weights for Chebyshev nodes.
static double[] BarycentricWeightsLobatto (int n)
Computes barycentric weights for Chebyshev-Lobatto nodes.
static double Interpolate (double[] nodes, double[] values, double[] weights, double x)
Interpolates a function at an arbitrary point using barycentric formula.
static double Interpolate (double[] nodes, double[] values, double x)
Interpolates using pre-computed nodes and weights (convenience overload).
static double ToStandardDomain (double x, double a, double b)
Transforms a point from physical domain [a, b] to standard Chebyshev domain [-1, 1].
static double FromStandardDomain (double t, double a, double b)
Transforms a point from standard Chebyshev domain [-1, 1] to physical domain [a, b].
static double[,] DifferentiationMatrix (double[] nodes)
Computes the Chebyshev differentiation matrix for spectral differentiation.
static double[] ValuesToCoefficients (double[] values)
Computes Chebyshev coefficients from function values (DCT-I on Lobatto nodes).
static double EvaluateSeries (double[] coeffs, double x)
Evaluates a Chebyshev series at a point using Clenshaw's algorithm.
Static Private Attributes
const double NodeMatchTolerance = 1e-14
Detailed Description
Chebyshev polynomial infrastructure for spectral collocation methods.
Definition at line 19 of file CRCH001A.cs.
Member Function Documentation
BarycentricWeights()
static double[] Alaris.Core.Math.CRCH001A.BarycentricWeights (int n) inline static
Computes barycentric interpolation weights for Chebyshev nodes.
Parameters
n Number of nodes.
Returns
Array of barycentric weights.
For Chebyshev nodes, weights are: w_k = (-1)^k * sin((2k+1)π/(2n)) Simplified form: w_k = (-1)^k with scaling (all have same magnitude).
Definition at line 141 of file CRCH001A.cs.
Referenced by Alaris.Core.Math.CRCH001A.Interpolate().
BarycentricWeightsLobatto()
static double[] Alaris.Core.Math.CRCH001A.BarycentricWeightsLobatto (int n) inline static
Computes barycentric weights for Chebyshev-Lobatto nodes.
Parameters
n Number of nodes.
Returns
Array of barycentric weights for Lobatto nodes.
For Chebyshev-Lobatto nodes: w_k = (-1)^k * δ_k where δ_0 = δ_{n-1} = 1/2, δ_k = 1 otherwise.
Definition at line 169 of file CRCH001A.cs.
ChebyshevLobattoNodes()
static double[] Alaris.Core.Math.CRCH001A.ChebyshevLobattoNodes (int n, double a = 0::0, double b = 1::0) inline static
Generates Chebyshev-Lobatto nodes (extrema of T_n) including endpoints.
Parameters
n Number of nodes (must be >= 2).
a Left endpoint of interval.
b Right endpoint of interval.
Returns
Array of n Chebyshev-Lobatto nodes including a and b.
Chebyshev-Lobatto nodes: x_k = (a+b)/2 + (b-a)/2 * cos(kπ/(n-1)) for k = 0,...,n-1 These include the endpoints [a, b] which is useful for boundary value problems.
Definition at line 70 of file CRCH001A.cs.
ChebyshevNodes()
static double[] Alaris.Core.Math.CRCH001A.ChebyshevNodes (int n, double a = 0::0, double b = 1::0) inline static
Generates Chebyshev nodes of the first kind on interval [a, b].
Parameters
n Number of nodes (must be >= 1).
a Left endpoint of interval.
b Right endpoint of interval.
Returns
Array of n Chebyshev nodes in ascending order.
Chebyshev nodes: x_k = (a+b)/2 + (b-a)/2 * cos((2k+1)π/(2n)) for k = 0,...,n-1 These nodes minimize the Lebesgue constant and avoid Runge's phenomenon.
Definition at line 34 of file CRCH001A.cs.
Referenced by Alaris.Core.Pricing.CREN004A.PriceDoubleBoundary(), and Alaris.Core.Pricing.CREN004A.PriceSingleBoundary().
ChebyshevT()
static double Alaris.Core.Math.CRCH001A.ChebyshevT (int n, double x) inline static
Evaluates the Chebyshev polynomial T_n(x) using the recurrence relation.
Parameters
n Polynomial degree.
x Evaluation point in [-1, 1].
Returns
T_n(x).
Recurrence: T_0(x) = 1, T_1(x) = x, T_{n+1}(x) = 2x*T_n(x) - T_{n-1}(x)
Definition at line 105 of file CRCH001A.cs.
DifferentiationMatrix()
static double[,] Alaris.Core.Math.CRCH001A.DifferentiationMatrix (double[] nodes) inline static
Computes the Chebyshev differentiation matrix for spectral differentiation.
Parameters
nodes Chebyshev-Lobatto nodes in [-1, 1].
Returns
n×n differentiation matrix D where (Df)_i ≈ f'(x_i).
The differentiation matrix maps function values to approximate derivative values. This is useful for solving ODEs/PDEs spectrally.
Definition at line 283 of file CRCH001A.cs.
EvaluateSeries()
static double Alaris.Core.Math.CRCH001A.EvaluateSeries (double[] coeffs, double x) inline static
Evaluates a Chebyshev series at a point using Clenshaw's algorithm.
Parameters
coeffs Chebyshev coefficients with half-weighted endpoints.
x Evaluation point in [-1, 1].
Returns
Value of the Chebyshev series at x.
Clenshaw's algorithm is numerically stable and O(n).
Definition at line 373 of file CRCH001A.cs.
FromStandardDomain()
static double Alaris.Core.Math.CRCH001A.FromStandardDomain (double t, double a, double b) inline static
Transforms a point from standard Chebyshev domain [-1, 1] to physical domain [a, b].
Definition at line 263 of file CRCH001A.cs.
Interpolate() [1/2]
static double Alaris.Core.Math.CRCH001A.Interpolate (double[] nodes, double[] values, double x) inline static
Interpolates using pre-computed nodes and weights (convenience overload).
Definition at line 238 of file CRCH001A.cs.
References Alaris.Core.Math.CRCH001A.BarycentricWeights(), and Alaris.Core.Math.CRCH001A.Interpolate().
Interpolate() [2/2]
static double Alaris.Core.Math.CRCH001A.Interpolate (double[] nodes, double[] values, double[] weights, double x) inline static
Interpolates a function at an arbitrary point using barycentric formula.
Parameters
nodes Interpolation nodes (in ascending order).
values Function values at nodes.
weights Barycentric weights.
x Evaluation point.
Returns
Interpolated value at x.
Barycentric formula: p(x) = Σ(w_k * f_k / (x - x_k)) / Σ(w_k / (x - x_k)) This is O(n) per evaluation and numerically stable.
Definition at line 196 of file CRCH001A.cs.
References Alaris.Core.Math.CRCH001A.NodeMatchTolerance.
Referenced by Alaris.Core.Math.CRCH001A.Interpolate(), and Alaris.Core.Pricing.CREN004A.InterpolateBoundary().
ToStandardDomain()
static double Alaris.Core.Math.CRCH001A.ToStandardDomain (double x, double a, double b) inline static
Transforms a point from physical domain [a, b] to standard Chebyshev domain [-1, 1].
Definition at line 249 of file CRCH001A.cs.
ValuesToCoefficients()
static double[] Alaris.Core.Math.CRCH001A.ValuesToCoefficients (double[] values) inline static
Computes Chebyshev coefficients from function values (DCT-I on Lobatto nodes).
Parameters
values Function values at Chebyshev-Lobatto nodes.
Returns
Chebyshev coefficients a_k for f(x) ≈ 0.5a_0 + Σ a_k T_k(x) + 0.5a_n T_n(x).
Definition at line 332 of file CRCH001A.cs.
Member Data Documentation
NodeMatchTolerance
const double Alaris.Core.Math.CRCH001A.NodeMatchTolerance = 1e-14 static private
Definition at line 21 of file CRCH001A.cs.
Referenced by Alaris.Core.Math.CRCH001A.Interpolate().
The documentation for this class was generated from the following file:
src/Alaris.Core/Math/CRCH001A.cs