Alaris: Alaris.Test.Unit.TSUN024A Class Reference
Alaris.Test.Unit.TSUN024A Class Reference sealed
TSUN024A: Mathematical invariant tests for IV calculators. Tests properties that must hold independent of specific numerical values.
Public Member Functions
void Heston_ComputeTheoreticalIV_AllValidInputs_ReturnsPositiveIV ()
For all valid inputs, computed IV must be strictly positive. Mathematical basis: IV is a volatility measure; negative volatility is undefined.
void Kou_ComputeTheoreticalIV_AllValidInputs_ReturnsPositiveIV ()
For all valid inputs, Kou model IV must be strictly positive.
void Heston_ATM_ShortTerm_IVApproximatesInstantaneousVol (double inputVol)
At-the-money, short-term IV should be close to instantaneous volatility. Mathematical basis: For short maturities, smile effects diminish.
void Kou_ATM_LowJumpIntensity_IVApproximatesDiffusiveVol (double sigma)
Kou model ATM IV should be close to diffusive volatility when jump intensity is low.
void Heston_AsVolOfVolApproachesZero_ConvergesToFlatSmile ()
As sigma_v → 0, Heston should converge to Black-Scholes (flat smile). Reference: Gatheral (2006), Chapter 3.
void Kou_AsJumpIntensityApproachesZero_ConvergesToDiffusion ()
As λ → 0, Kou JD should converge to Black-Scholes (diffusion only). Reference: Kou (2002), Proposition 1.
void Heston_ATM_TermStructure_IsWellBehaved ()
ATM IV should generally decrease with time (term structure effect). This tests the typical "volatility term structure" pattern.
void Heston_NegativeCorrelation_ProducesNegativeSkew (double rho)
With ρ < 0, OTM puts should have higher IV than OTM calls (negative skew). Reference: Gatheral (2006), leverage effect and skew.
void Kou_DownwardJumpBias_ProducesNegativeSkew ()
When p < 0.5 (more downward jumps), Kou should exhibit negative skew. Reference: Kou (2002), Section 4.
void HestonParameters_FellerViolation_FailsValidation (double kappa, double theta, double sigmaV)
Heston parameters violating Feller condition should fail validation. Mathematical basis: 2κθ > σ_v² ensures V_t > 0 almost surely.
void KouParameters_InvalidEta1_FailsValidation (double eta1)
Kou parameters with Eta1 <= 1 should fail validation. Mathematical basis: Eta1 > 1 ensures finite expected up-jump size.
void Heston_CharacteristicFunction_AtZero_EqualsOne ()
Characteristic function at u=0 should equal 1. Mathematical basis: φ(0) = E[exp(0)] = 1 for any distribution.
void ModelSelector_PreEarnings_PrefersJumpModels ()
Pre-earnings regime should prefer Leung-Santoli or Kou (jump models).
void Heston_HigherVolOfVol_ProducesWiderSmile ()
Higher vol-of-vol should produce wider smiles. Reference: Gatheral (2006), Chapter 3.
void Kou_HigherJumpIntensity_IncreasesATMIV ()
Higher jump intensity should increase ATM IV (more variance). Reference: Kou (2002), total variance = σ² + λ*E[J²].
void Models_ExtremeValidInputs_DoNotProduceNaNOrInfinity ()
Models should not produce NaN or Infinity for extreme but valid inputs.
void Kou_SymmetricJumps_KappaApproachesZero ()
Symmetric Kou jumps should produce kappa ≈ 0. Mathematical basis: E[V-1] = p*eta1/(eta1-1) + (1-p)*eta2/(eta2+1) - 1.
Static Private Member Functions
static HestonParameters CreateValidHestonParams ()
static KouParameters CreateValidKouParams ()
Static Private Attributes
static readonly double[] s_spots = { 80, 90, 100, 110, 120 }
static readonly double[] s_strikes = { 80, 90, 95, 100, 105, 110, 120 }
static readonly double[] s_timesToExpiry = { 7.0 / 252, 14.0 / 252, 30.0 / 252, 60.0 / 252, 90.0 / 252 }
Detailed Description
TSUN024A: Mathematical invariant tests for IV calculators. Tests properties that must hold independent of specific numerical values.
Definition at line 32 of file TSUN024A.cs.
Member Function Documentation
CreateValidHestonParams()
static HestonParameters Alaris.Test.Unit.TSUN024A.CreateValidHestonParams () static private
Referenced by Alaris.Test.Unit.TSUN024A.Heston_ATM_TermStructure_IsWellBehaved(), Alaris.Test.Unit.TSUN024A.Heston_CharacteristicFunction_AtZero_EqualsOne(), Alaris.Test.Unit.TSUN024A.Heston_ComputeTheoreticalIV_AllValidInputs_ReturnsPositiveIV(), and Alaris.Test.Unit.TSUN024A.Models_ExtremeValidInputs_DoNotProduceNaNOrInfinity().
CreateValidKouParams()
static KouParameters Alaris.Test.Unit.TSUN024A.CreateValidKouParams () static private
Referenced by Alaris.Test.Unit.TSUN024A.Kou_ComputeTheoreticalIV_AllValidInputs_ReturnsPositiveIV(), and Alaris.Test.Unit.TSUN024A.Models_ExtremeValidInputs_DoNotProduceNaNOrInfinity().
Heston_AsVolOfVolApproachesZero_ConvergesToFlatSmile()
void Alaris.Test.Unit.TSUN024A.Heston_AsVolOfVolApproachesZero_ConvergesToFlatSmile () inline
As sigma_v → 0, Heston should converge to Black-Scholes (flat smile). Reference: Gatheral (2006), Chapter 3.
Definition at line 196 of file TSUN024A.cs.
Heston_ATM_ShortTerm_IVApproximatesInstantaneousVol()
void Alaris.Test.Unit.TSUN024A.Heston_ATM_ShortTerm_IVApproximatesInstantaneousVol (double inputVol) inline
At-the-money, short-term IV should be close to instantaneous volatility. Mathematical basis: For short maturities, smile effects diminish.
Definition at line 130 of file TSUN024A.cs.
Heston_ATM_TermStructure_IsWellBehaved()
void Alaris.Test.Unit.TSUN024A.Heston_ATM_TermStructure_IsWellBehaved () inline
ATM IV should generally decrease with time (term structure effect). This tests the typical "volatility term structure" pattern.
Definition at line 291 of file TSUN024A.cs.
References Alaris.Test.Unit.TSUN024A.CreateValidHestonParams().
Heston_CharacteristicFunction_AtZero_EqualsOne()
void Alaris.Test.Unit.TSUN024A.Heston_CharacteristicFunction_AtZero_EqualsOne () inline
Characteristic function at u=0 should equal 1. Mathematical basis: φ(0) = E[exp(0)] = 1 for any distribution.
Definition at line 467 of file TSUN024A.cs.
References Alaris.Test.Unit.TSUN024A.CreateValidHestonParams().
Heston_ComputeTheoreticalIV_AllValidInputs_ReturnsPositiveIV()
void Alaris.Test.Unit.TSUN024A.Heston_ComputeTheoreticalIV_AllValidInputs_ReturnsPositiveIV () inline
For all valid inputs, computed IV must be strictly positive. Mathematical basis: IV is a volatility measure; negative volatility is undefined.
Definition at line 69 of file TSUN024A.cs.
References Alaris.Test.Unit.TSUN024A.CreateValidHestonParams(), Alaris.Test.Unit.TSUN024A.s_spots, Alaris.Test.Unit.TSUN024A.s_strikes, and Alaris.Test.Unit.TSUN024A.s_timesToExpiry.
Heston_HigherVolOfVol_ProducesWiderSmile()
void Alaris.Test.Unit.TSUN024A.Heston_HigherVolOfVol_ProducesWiderSmile () inline
Higher vol-of-vol should produce wider smiles. Reference: Gatheral (2006), Chapter 3.
Definition at line 524 of file TSUN024A.cs.
Heston_NegativeCorrelation_ProducesNegativeSkew()
void Alaris.Test.Unit.TSUN024A.Heston_NegativeCorrelation_ProducesNegativeSkew (double rho) inline
With ρ < 0, OTM puts should have higher IV than OTM calls (negative skew). Reference: Gatheral (2006), leverage effect and skew.
Definition at line 334 of file TSUN024A.cs.
HestonParameters_FellerViolation_FailsValidation()
void Alaris.Test.Unit.TSUN024A.HestonParameters_FellerViolation_FailsValidation (double kappa, double theta, double sigmaV) inline
Heston parameters violating Feller condition should fail validation. Mathematical basis: 2κθ > σ_v² ensures V_t > 0 almost surely.
Definition at line 408 of file TSUN024A.cs.
Kou_AsJumpIntensityApproachesZero_ConvergesToDiffusion()
void Alaris.Test.Unit.TSUN024A.Kou_AsJumpIntensityApproachesZero_ConvergesToDiffusion () inline
As λ → 0, Kou JD should converge to Black-Scholes (diffusion only). Reference: Kou (2002), Proposition 1.
Definition at line 249 of file TSUN024A.cs.
Kou_ATM_LowJumpIntensity_IVApproximatesDiffusiveVol()
void Alaris.Test.Unit.TSUN024A.Kou_ATM_LowJumpIntensity_IVApproximatesDiffusiveVol (double sigma) inline
Kou model ATM IV should be close to diffusive volatility when jump intensity is low.
Definition at line 163 of file TSUN024A.cs.
Kou_ComputeTheoreticalIV_AllValidInputs_ReturnsPositiveIV()
void Alaris.Test.Unit.TSUN024A.Kou_ComputeTheoreticalIV_AllValidInputs_ReturnsPositiveIV () inline
For all valid inputs, Kou model IV must be strictly positive.
Definition at line 96 of file TSUN024A.cs.
References Alaris.Test.Unit.TSUN024A.CreateValidKouParams(), Alaris.Test.Unit.TSUN024A.s_spots, Alaris.Test.Unit.TSUN024A.s_strikes, and Alaris.Test.Unit.TSUN024A.s_timesToExpiry.
Kou_DownwardJumpBias_ProducesNegativeSkew()
void Alaris.Test.Unit.TSUN024A.Kou_DownwardJumpBias_ProducesNegativeSkew () inline
When p < 0.5 (more downward jumps), Kou should exhibit negative skew. Reference: Kou (2002), Section 4.
Definition at line 373 of file TSUN024A.cs.
Kou_HigherJumpIntensity_IncreasesATMIV()
void Alaris.Test.Unit.TSUN024A.Kou_HigherJumpIntensity_IncreasesATMIV () inline
Higher jump intensity should increase ATM IV (more variance). Reference: Kou (2002), total variance = σ² + λ*E[J²].
Definition at line 577 of file TSUN024A.cs.
Kou_SymmetricJumps_KappaApproachesZero()
void Alaris.Test.Unit.TSUN024A.Kou_SymmetricJumps_KappaApproachesZero () inline
Symmetric Kou jumps should produce kappa ≈ 0. Mathematical basis: E[V-1] = p*eta1/(eta1-1) + (1-p)*eta2/(eta2+1) - 1.
Definition at line 663 of file TSUN024A.cs.
References Alaris.Strategy.Core.KouParameters.ComputeKappa().
KouParameters_InvalidEta1_FailsValidation()
void Alaris.Test.Unit.TSUN024A.KouParameters_InvalidEta1_FailsValidation (double eta1) inline
Kou parameters with Eta1 <= 1 should fail validation. Mathematical basis: Eta1 > 1 ensures finite expected up-jump size.
Definition at line 439 of file TSUN024A.cs.
References Alaris.Strategy.Core.ValidationResult.IsValid, and Alaris.Strategy.Core.KouParameters.Validate().
Models_ExtremeValidInputs_DoNotProduceNaNOrInfinity()
void Alaris.Test.Unit.TSUN024A.Models_ExtremeValidInputs_DoNotProduceNaNOrInfinity () inline
Models should not produce NaN or Infinity for extreme but valid inputs.
Definition at line 622 of file TSUN024A.cs.
References Alaris.Test.Unit.TSUN024A.CreateValidHestonParams(), and Alaris.Test.Unit.TSUN024A.CreateValidKouParams().
ModelSelector_PreEarnings_PrefersJumpModels()
void Alaris.Test.Unit.TSUN024A.ModelSelector_PreEarnings_PrefersJumpModels () inline
Pre-earnings regime should prefer Leung-Santoli or Kou (jump models).
Definition at line 487 of file TSUN024A.cs.
References Alaris.Strategy.Core.STTM004A.Create().
Member Data Documentation
s_spots
readonly double [] Alaris.Test.Unit.TSUN024A.s_spots = { 80, 90, 100, 110, 120 } static private
Definition at line 35 of file TSUN024A.cs.
Referenced by Alaris.Test.Unit.TSUN024A.Heston_ComputeTheoreticalIV_AllValidInputs_ReturnsPositiveIV(), and Alaris.Test.Unit.TSUN024A.Kou_ComputeTheoreticalIV_AllValidInputs_ReturnsPositiveIV().
s_strikes
readonly double [] Alaris.Test.Unit.TSUN024A.s_strikes = { 80, 90, 95, 100, 105, 110, 120 } static private
Definition at line 36 of file TSUN024A.cs.
Referenced by Alaris.Test.Unit.TSUN024A.Heston_ComputeTheoreticalIV_AllValidInputs_ReturnsPositiveIV(), and Alaris.Test.Unit.TSUN024A.Kou_ComputeTheoreticalIV_AllValidInputs_ReturnsPositiveIV().
s_timesToExpiry
readonly double [] Alaris.Test.Unit.TSUN024A.s_timesToExpiry = { 7.0 / 252, 14.0 / 252, 30.0 / 252, 60.0 / 252, 90.0 / 252 } static private
Definition at line 37 of file TSUN024A.cs.
Referenced by Alaris.Test.Unit.TSUN024A.Heston_ComputeTheoreticalIV_AllValidInputs_ReturnsPositiveIV(), and Alaris.Test.Unit.TSUN024A.Kou_ComputeTheoreticalIV_AllValidInputs_ReturnsPositiveIV().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN024A.cs