// =============================================================================
// IntegrationTypes.cs - Integration Interfaces and Types for Alaris.Algorithm
// =============================================================================
// Purpose: Defines interfaces and types required for STLN001A integration
// These should be implemented or moved to appropriate Alaris projects
// =============================================================================

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Alaris.Algorithm;

// =============================================================================
// SECTION 1: Execution Quote Types (Alaris.Data.Provider.Execution)
// =============================================================================

/// <summary>
/// Interface for execution quote providers (IBKR snapshots).
/// Should be implemented in Alaris.Data.Provider.Execution namespace.
/// </summary>
public interface IExecutionQuoteProvider
{
    /// <summary>
    /// Gets a single option quote.
    /// </summary>
    Task<OptionQuote?> GetOptionQuoteAsync(
        string underlyingSymbol,
        decimal strike,
        DateTime expiration,
        OptionRight right,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets a calendar spread quote (front and back months).
    /// </summary>
    Task<CalendarSpreadQuote?> GetCalendarSpreadQuoteAsync(
        string underlyingSymbol,
        decimal strike,
        DateTime frontExpiration,
        DateTime backExpiration,
        OptionRight right,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Single option quote from execution provider.
/// </summary>
public sealed record OptionQuote
{
    /// <summary>Gets the option symbol.</summary>
    public required string OptionSymbol { get; init; }
    
    /// <summary>Gets the bid price.</summary>
    public required decimal Bid { get; init; }
    
    /// <summary>Gets the ask price.</summary>
    public required decimal Ask { get; init; }
    
    /// <summary>Gets the mid price.</summary>
    public decimal Mid => (Bid + Ask) / 2m;
    
    /// <summary>Gets the bid size.</summary>
    public int BidSize { get; init; }
    
    /// <summary>Gets the ask size.</summary>
    public int AskSize { get; init; }
    
    /// <summary>Gets the last trade price.</summary>
    public decimal? LastPrice { get; init; }
    
    /// <summary>Gets the quote timestamp.</summary>
    public DateTime Timestamp { get; init; } = DateTime.UtcNow;
}

/// <summary>
/// Calendar spread quote (combined front and back month).
/// </summary>
public sealed record CalendarSpreadQuote
{
    /// <summary>Gets the front month quote.</summary>
    public required OptionQuote FrontMonth { get; init; }
    
    /// <summary>Gets the back month quote.</summary>
    public required OptionQuote BackMonth { get; init; }
    
    /// <summary>Gets the spread bid (buy back at ask, sell front at bid).</summary>
    public decimal SpreadBid => BackMonth.Bid - FrontMonth.Ask;
    
    /// <summary>Gets the spread ask (buy back at ask, sell front at bid).</summary>
    public decimal SpreadAsk => BackMonth.Ask - FrontMonth.Bid;
    
    /// <summary>Gets the spread mid price.</summary>
    public decimal SpreadMid => (SpreadBid + SpreadAsk) / 2m;
    
    /// <summary>Gets the spread width.</summary>
    public decimal SpreadWidth => SpreadAsk - SpreadBid;
    
    /// <summary>Gets the quote timestamp.</summary>
    public DateTime Timestamp { get; init; } = DateTime.UtcNow;
}

/// <summary>
/// Option right (call or put).
/// </summary>
public enum OptionRight
{
    /// <summary>Call option.</summary>
    Call,
    
    /// <summary>Put option.</summary>
    Put
}

// =============================================================================
// SECTION 2: Strategy Signal Types (Alaris.Strategy.Core)
// =============================================================================

/// <summary>
/// Trading signal generated by STCR001A.
/// This type should exist in Alaris.Strategy.Core namespace.
/// </summary>
public sealed record STCR004A
{
    /// <summary>Gets the symbol.</summary>
    public required string Symbol { get; init; }
    
    /// <summary>Gets the signal strength.</summary>
    public required STCR004AStrength Strength { get; init; }
    
    /// <summary>Gets the IV/RV ratio.</summary>
    public double IVRVRatio { get; init; }
    
    /// <summary>Gets the term structure slope.</summary>
    public double TermStructureSlope { get; init; }
    
    /// <summary>Gets the strike price for the spread.</summary>
    public decimal Strike { get; init; }
    
    /// <summary>Gets the front month expiration.</summary>
    public DateTime FrontExpiry { get; init; }
    
    /// <summary>Gets the back month expiration.</summary>
    public DateTime BackExpiry { get; init; }
    
    /// <summary>Gets the earnings date.</summary>
    public DateTime EarningsDate { get; init; }
    
    /// <summary>Gets the front month IV.</summary>
    public double FrontIV { get; init; }
    
    /// <summary>Gets the back month IV.</summary>
    public double BackIV { get; init; }
    
    /// <summary>Gets the realised volatility.</summary>
    public double RealisedVolatility { get; init; }
    
    /// <summary>Gets the 30-day average volume.</summary>
    public long AverageVolume { get; init; }
}

/// <summary>
/// Signal strength enumeration.
/// </summary>
public enum STCR004AStrength
{
    /// <summary>Avoid - criteria not met.</summary>
    Avoid,
    
    /// <summary>Consider - partial criteria met.</summary>
    Consider,
    
    /// <summary>Recommended - all criteria met.</summary>
    Recommended
}

// =============================================================================
// SECTION 3: Production Validation Types (Alaris.Strategy.Hedge)
// =============================================================================

/// <summary>
/// Production validation result from STHD005A.
/// </summary>
public sealed record STHD006A
{
    /// <summary>Gets the base signal.</summary>
    public required STCR004A BaseSignal { get; init; }
    
    /// <summary>Gets the validation checks.</summary>
    public required IReadOnlyList<ValidationCheck> Checks { get; init; }
    
    /// <summary>Gets whether overall validation passed.</summary>
    public required bool OverallPass { get; init; }
    
    /// <summary>Gets the adjusted spread debit after costs.</summary>
    public required double AdjustedDebit { get; init; }
    
    /// <summary>Gets the recommended number of contracts.</summary>
    public required int RecommendedContracts { get; init; }
    
    /// <summary>Gets whether signal is production ready.</summary>
    public required bool ProductionReady { get; init; }
}

/// <summary>
/// Single validation check result.
/// </summary>
public sealed record ValidationCheck
{
    /// <summary>Gets the check name.</summary>
    public required string Name { get; init; }
    
    /// <summary>Gets whether the check passed.</summary>
    public required bool Passed { get; init; }
    
    /// <summary>Gets the reason for pass/fail.</summary>
    public string Reason { get; init; } = string.Empty;
}

/// <summary>
/// Option parameters for validation.
/// </summary>
public sealed record OptionParameters
{
    /// <summary>Gets the strike price.</summary>
    public double Strike { get; init; }
    
    /// <summary>Gets the days to expiry.</summary>
    public int DTE { get; init; }
    
    /// <summary>Gets the implied volatility.</summary>
    public double ImpliedVolatility { get; init; }
    
    /// <summary>Gets whether this is a call option.</summary>
    public bool IsCall { get; init; }
}

/// <summary>
/// Greeks for a calendar spread.
/// </summary>
public sealed record SpreadGreeks
{
    /// <summary>Gets the delta.</summary>
    public double Delta { get; init; }
    
    /// <summary>Gets the gamma.</summary>
    public double Gamma { get; init; }
    
    /// <summary>Gets the vega.</summary>
    public double Vega { get; init; }
    
    /// <summary>Gets the theta.</summary>
    public double Theta { get; init; }
}

// =============================================================================
// SECTION 4: Position Sizing Types (Alaris.Strategy.Risk)
// =============================================================================

/// <summary>
/// Position sizing result from STRK001A (Kelly criterion).
/// </summary>
public sealed record PositionSizingResult
{
    /// <summary>Gets the recommended number of contracts.</summary>
    public int Contracts { get; init; }
    
    /// <summary>Gets the allocation as percentage of portfolio.</summary>
    public double AllocationPercent { get; init; }
    
    /// <summary>Gets the total position cost.</summary>
    public decimal TotalCost { get; init; }
    
    /// <summary>Gets the total risk amount.</summary>
    public decimal TotalRisk { get; init; }
    
    /// <summary>Gets the Kelly fraction used.</summary>
    public double KellyFraction { get; init; }
}

// =============================================================================
// SECTION 5: Audit Trail Types (Alaris.Events)
// =============================================================================

/// <summary>
/// Trade event for audit logging.
/// </summary>
public sealed record TradeEvent
{
    /// <summary>Gets the symbol.</summary>
    public required string Symbol { get; init; }
    
    /// <summary>Gets the action (OPEN/CLOSE).</summary>
    public required string Action { get; init; }
    
    /// <summary>Gets the number of contracts.</summary>
    public int Contracts { get; init; }
    
    /// <summary>Gets the execution price.</summary>
    public decimal Price { get; init; }
    
    /// <summary>Gets the associated signal.</summary>
    public STCR004A? Signal { get; init; }
    
    /// <summary>Gets the timestamp.</summary>
    public DateTime Timestamp { get; init; }
}

/// <summary>
/// Order fill event for audit logging.
/// </summary>
public sealed record OrderFillEvent
{
    /// <summary>Gets the order ID.</summary>
    public int OrderId { get; init; }
    
    /// <summary>Gets the symbol.</summary>
    public required string Symbol { get; init; }
    
    /// <summary>Gets the fill quantity.</summary>
    public decimal Quantity { get; init; }
    
    /// <summary>Gets the fill price.</summary>
    public decimal FillPrice { get; init; }
    
    /// <summary>Gets the timestamp.</summary>
    public DateTime Timestamp { get; init; }
}

/// <summary>
/// In-memory audit logger interface.
/// Should be implemented in Alaris.Events.
/// </summary>
public interface IAuditLogger
{
    void LogTrade(TradeEvent tradeEvent);
    void LogOrderFill(OrderFillEvent fillEvent);
    void LogWarning(string message, object? context = null);
    void LogError(string message, Exception? exception = null);
}

/// <summary>
/// In-memory audit logger implementation.
/// Placeholder - should be in Alaris.Events.
/// </summary>
public sealed class InMemoryAuditLogger : IAuditLogger
{
    private readonly InMemoryEventStore _store;
    private readonly Microsoft.Extensions.Logging.ILogger _logger;

    public InMemoryAuditLogger(
        InMemoryEventStore store,
        Microsoft.Extensions.Logging.ILogger logger)
    {
        _store = store;
        _logger = logger;
    }

    public void LogTrade(TradeEvent tradeEvent) { }
    public void LogOrderFill(OrderFillEvent fillEvent) { }
    public void LogWarning(string message, object? context = null) { }
    public void LogError(string message, Exception? exception = null) { }
}

/// <summary>
/// In-memory event store.
/// Placeholder - should be in Alaris.Events.
/// </summary>
public sealed class InMemoryEventStore
{
    private readonly List<object> _events = new();

    public void Append(object @event) => _events.Add(@event);
    public IReadOnlyList<object> GetAll() => _events.AsReadOnly();
}

// =============================================================================
// SECTION 6: Term Structure Types (Alaris.Strategy.Core)
// =============================================================================

/// <summary>
/// Term structure analysis result.
/// </summary>
public sealed record TermStructureAnalysis
{
    /// <summary>Gets the 30-day IV.</summary>
    public double ThirtyDayIV { get; init; }
    
    /// <summary>Gets the 60-day IV.</summary>
    public double SixtyDayIV { get; init; }
    
    /// <summary>Gets the 90-day IV.</summary>
    public double NinetyDayIV { get; init; }
    
    /// <summary>Gets the slope of the term structure.</summary>
    public double Slope { get; init; }
    
    /// <summary>Gets whether term structure is inverted.</summary>
    public bool IsInverted => Slope < 0;
    
    /// <summary>Gets whether trading criterion is met (slope &lt; -0.00406).</summary>
    public bool MeetsTradingCriterion => Slope < -0.00406;
}

// =============================================================================
// SECTION 7: Market Data Adapter Interface
// =============================================================================

/// <summary>
/// Market data provider interface for strategy components.
/// This is referenced as STDT001A in Alaris.Strategy.
/// </summary>
public abstract class STDT001A
{
    // Abstract base class for market data providers
    // Actual implementation depends on strategy requirements
}