Alaris: Alaris.Core.Math.CRMF001A Class Reference
Alaris.Core.Math.CRMF001A Class Reference
Core mathematical functions. Thread-safe, zero-allocation, bounded error (Erf max 1.5e-7).
Static Public Member Functions
static double Erf (double x)
Error function erf(x) using Abramowitz and Stegun formula 7.1.26.
static double NormalCDF (double x)
Standard normal cumulative distribution function Φ(x).
static double NormalPDF (double x)
Standard normal probability density function φ(x).
static double BSd1 (double S, double K, double tau, double sigma, double r, double q)
Black-Scholes d1 parameter.
static double BSd2 (double d1, double sigma, double tau)
Black-Scholes d2 parameter.
static double BSPrice (double S, double K, double tau, double sigma, double r, double q, bool isCall)
Black-Scholes European option price.
static double BSVega (double S, double K, double tau, double sigma, double r, double q)
Black-Scholes Vega (∂V/∂σ).
static double BSVolga (double S, double K, double tau, double sigma, double r, double q)
Black-Scholes Volga (Vomma): ∂²V/∂σ² = ∂Vega/∂σ.
static double BSDelta (double S, double K, double tau, double sigma, double r, double q, bool isCall)
Black-Scholes Delta (∂V/∂S).
static double BSGamma (double S, double K, double tau, double sigma, double r, double q)
Black-Scholes Gamma (∂²V/∂S²).
static double BSTheta (double S, double K, double tau, double sigma, double r, double q, bool isCall)
Black-Scholes Theta (∂V/∂τ).
static double BSImpliedVolatility (double S, double K, double tau, double r, double q, double marketPrice, bool isCall, double tolerance=1e-7, int maxIterations=10)
Computes Black-Scholes implied volatility using 3rd-order Householder with Brent fallback.
static bool IsValidVolatility (double sigma)
Validates that a volatility value is within bounds.
static double ClampVolatility (double sigma)
Clamps volatility to valid bounds.
static double DteToYears (int dte)
Converts days to expiry to years.
static int YearsToDte (double tau)
Converts years to days to expiry.
Static Public Attributes
const double MachineEpsilon = 2.220446049250313e-16
Machine epsilon for double precision (2.22e-16).
const double SqrtTwoPi = 2.5066282746310005
√(2π) for normal distribution calculations.
const double InvSqrtTwoPi = 0.3989422804014327
1/√(2π) for PDF calculations.
const double Sqrt2 = 1.4142135623730951
√2 for erf to CDF conversion.
const double DefaultTolerance = 1e-10
Default tolerance for root-finding algorithms.
const double MaxVolatility = 5.0
Maximum IV bound (500% annualized).
const double MinVolatility = 0.001
Minimum IV bound (0.1% annualized).
const double MinTimeToExpiry = 1.0 / 252.0
Minimum time to expiry (1 trading day).
const int TradingDaysPerYear = 252
Trading days per year.
Static Private Member Functions
static double CorradoMillerGuess (double S, double K, double tau, double r, double q, double marketPrice, bool isCall)
Corrado-Miller (1996) closed-form IV approximation.
static double BSImpliedVolatilityBrent (double S, double K, double tau, double r, double q, double marketPrice, bool isCall, double tolerance=1e-7, int maxIterations=100)
Brent's method for IV calculation - guaranteed convergence.
Detailed Description
Core mathematical functions. Thread-safe, zero-allocation, bounded error (Erf max 1.5e-7).
Definition at line 8 of file CRMF001A.cs.
Member Function Documentation
BSd1()
static double Alaris.Core.Math.CRMF001A.BSd1 (double S, double K, double tau, double sigma, double r, double q) inline static
Black-Scholes d1 parameter.
Parameters
S Spot price (must be > 0).
K Strike price (must be > 0).
tau Time to expiry in years (must be > 0).
sigma Volatility (must be > 0).
r Risk-free rate.
q Dividend yield.
Returns
d1 = (ln(S/K) + (r - q + σ²/2)τ) / (σ√τ)
Definition at line 136 of file CRMF001A.cs.
Referenced by Alaris.Core.Math.CRMF001A.BSDelta(), Alaris.Core.Math.CRMF001A.BSGamma(), Alaris.Core.Math.CRMF001A.BSPrice(), Alaris.Core.Math.CRMF001A.BSTheta(), Alaris.Core.Math.CRMF001A.BSVega(), and Alaris.Core.Math.CRMF001A.BSVolga().
BSd2()
static double Alaris.Core.Math.CRMF001A.BSd2 (double d1, double sigma, double tau) inline static
Black-Scholes d2 parameter.
Parameters
d1 The d1 parameter.
sigma Volatility.
tau Time to expiry in years.
Returns
d2 = d1 - σ√τ
Definition at line 149 of file CRMF001A.cs.
Referenced by Alaris.Core.Math.CRMF001A.BSPrice(), Alaris.Core.Math.CRMF001A.BSTheta(), and Alaris.Core.Math.CRMF001A.BSVolga().
BSDelta()
static double Alaris.Core.Math.CRMF001A.BSDelta (double S, double K, double tau, double sigma, double r, double q, bool isCall) inline static
Black-Scholes Delta (∂V/∂S).
Parameters
S Spot price.
K Strike price.
tau Time to expiry in years.
sigma Volatility.
r Risk-free rate.
q Dividend yield.
isCall True for call, false for put.
Returns
Delta: Call = e^(-qτ)*Φ(d1), Put = -e^(-qτ)*Φ(-d1)
Definition at line 247 of file CRMF001A.cs.
References Alaris.Core.Math.CRMF001A.BSd1(), and Alaris.Core.Math.CRMF001A.NormalCDF().
BSGamma()
static double Alaris.Core.Math.CRMF001A.BSGamma (double S, double K, double tau, double sigma, double r, double q) inline static
Black-Scholes Gamma (∂²V/∂S²).
Parameters
S Spot price.
K Strike price.
tau Time to expiry in years.
sigma Volatility.
r Risk-free rate.
q Dividend yield.
Returns
Gamma = e^(-qτ)*φ(d1)/(S*σ*√τ)
Gamma is identical for calls and puts.
Definition at line 275 of file CRMF001A.cs.
References Alaris.Core.Math.CRMF001A.BSd1(), and Alaris.Core.Math.CRMF001A.NormalPDF().
BSImpliedVolatility()
static double Alaris.Core.Math.CRMF001A.BSImpliedVolatility (double S, double K, double tau, double r, double q, double marketPrice, bool isCall, double tolerance = 1e-7, int maxIterations = 10) inline static
Computes Black-Scholes implied volatility using 3rd-order Householder with Brent fallback.
Parameters
S Spot price.
K Strike price.
tau Time to expiry in years.
r Risk-free rate.
q Dividend yield.
marketPrice Market price of the option.
isCall True for call, false for put.
tolerance Convergence tolerance (default 1e-7).
maxIterations Maximum Householder iterations before Brent fallback (default 10).
Returns
Implied volatility, or NaN if not converged.
Algorithm:
Corrado-Miller (1996) closed-form initial guess
Householder(3) refinement: σ_{n+1} = σ_n - f/f' × (1 + f×f''/(2×f'²))
Cubic convergence (typically 2 iterations vs 3-5 for Newton)
Brent's method fallback for guaranteed convergence
References:
Corrado CJ, Miller TW. A note on a simple, accurate formula to compute implied standard deviations. Journal of Banking & Finance. 1996;20(3):595-603.
Householder AS. The Numerical Treatment of a Single Nonlinear Equation. 1970.
Brent RP. Algorithms for Minimization without Derivatives. 1973.
Definition at line 343 of file CRMF001A.cs.
References Alaris.Core.Math.CRMF001A.BSImpliedVolatilityBrent(), Alaris.Core.Math.CRMF001A.BSPrice(), Alaris.Core.Math.CRMF001A.BSVega(), Alaris.Core.Math.CRMF001A.BSVolga(), Alaris.Core.Math.CRMF001A.ClampVolatility(), Alaris.Core.Math.CRMF001A.CorradoMillerGuess(), Alaris.Core.Math.CRMF001A.MachineEpsilon, and Alaris.Core.Math.CRMF001A.MaxVolatility.
Referenced by Alaris.Strategy.Bridge.STBR001A.CalculateImpliedVolatility(), and Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetHistoricalOptionChainAsync().
BSImpliedVolatilityBrent()
static double Alaris.Core.Math.CRMF001A.BSImpliedVolatilityBrent (double S, double K, double tau, double r, double q, double marketPrice, bool isCall, double tolerance = 1e-7, int maxIterations = 100) inline static private
Brent's method for IV calculation - guaranteed convergence.
Combines bisection, secant, and inverse quadratic interpolation. Superlinear convergence with guaranteed bracketing.
Definition at line 480 of file CRMF001A.cs.
References Alaris.Core.Math.CRMF001A.BSPrice(), Alaris.Core.Math.CRMF001A.MachineEpsilon, Alaris.Core.Math.CRMF001A.MaxVolatility, and Alaris.Core.Math.CRMF001A.MinVolatility.
Referenced by Alaris.Core.Math.CRMF001A.BSImpliedVolatility().
BSPrice()
static double Alaris.Core.Math.CRMF001A.BSPrice (double S, double K, double tau, double sigma, double r, double q, bool isCall) inline static
Black-Scholes European option price.
Parameters
S Spot price (must be > 0).
K Strike price (must be > 0).
tau Time to expiry in years (must be > 0).
sigma Volatility (must be > 0).
r Risk-free rate.
q Dividend yield.
isCall True for call, false for put.
Returns
Option price.
Uses put-call parity for puts: P = C - S*e^(-qτ) + K*e^(-rτ)
Definition at line 168 of file CRMF001A.cs.
References Alaris.Core.Math.CRMF001A.BSd1(), Alaris.Core.Math.CRMF001A.BSd2(), and Alaris.Core.Math.CRMF001A.NormalCDF().
Referenced by Alaris.Core.Math.CRMF001A.BSImpliedVolatility(), Alaris.Core.Math.CRMF001A.BSImpliedVolatilityBrent(), Alaris.Test.Unit.Core.Pricing.CREN003ATests.Price_AmericanGreaterThanOrEqualEuropean(), and Alaris.Core.Pricing.CREN003A.PriceWithDetails().
BSTheta()
static double Alaris.Core.Math.CRMF001A.BSTheta (double S, double K, double tau, double sigma, double r, double q, bool isCall) inline static
Black-Scholes Theta (∂V/∂τ).
Parameters
S Spot price.
K Strike price.
tau Time to expiry in years.
sigma Volatility.
r Risk-free rate.
q Dividend yield.
isCall True for call, false for put.
Returns
Theta (per year, divide by 252 for daily).
Definition at line 295 of file CRMF001A.cs.
References Alaris.Core.Math.CRMF001A.BSd1(), Alaris.Core.Math.CRMF001A.BSd2(), Alaris.Core.Math.CRMF001A.NormalCDF(), and Alaris.Core.Math.CRMF001A.NormalPDF().
BSVega()
static double Alaris.Core.Math.CRMF001A.BSVega (double S, double K, double tau, double sigma, double r, double q) inline static
Black-Scholes Vega (∂V/∂σ).
Parameters
S Spot price.
K Strike price.
tau Time to expiry in years.
sigma Volatility.
r Risk-free rate.
q Dividend yield.
Returns
Vega = S*e^(-qτ)*φ(d1)*√τ
Vega is identical for calls and puts.
Definition at line 199 of file CRMF001A.cs.
References Alaris.Core.Math.CRMF001A.BSd1(), and Alaris.Core.Math.CRMF001A.NormalPDF().
Referenced by Alaris.Core.Math.CRMF001A.BSImpliedVolatility(), and Alaris.Core.Math.CRMF001A.BSVolga().
BSVolga()
static double Alaris.Core.Math.CRMF001A.BSVolga (double S, double K, double tau, double sigma, double r, double q) inline static
Black-Scholes Volga (Vomma): ∂²V/∂σ² = ∂Vega/∂σ.
Parameters
S Spot price.
K Strike price.
tau Time to expiry in years.
sigma Volatility.
r Risk-free rate.
q Dividend yield.
Returns
Volga = Vega × d1 × d2 / σ
Volga is identical for calls and puts. Used in 3rd-order Householder iteration for IV calculation.
Definition at line 222 of file CRMF001A.cs.
References Alaris.Core.Math.CRMF001A.BSd1(), Alaris.Core.Math.CRMF001A.BSd2(), Alaris.Core.Math.CRMF001A.BSVega(), and Alaris.Core.Math.CRMF001A.MachineEpsilon.
Referenced by Alaris.Core.Math.CRMF001A.BSImpliedVolatility().
ClampVolatility()
static double Alaris.Core.Math.CRMF001A.ClampVolatility (double sigma) inline static
Clamps volatility to valid bounds.
Parameters
sigma Volatility to clamp.
Returns
Clamped volatility.
Definition at line 598 of file CRMF001A.cs.
References Alaris.Core.Math.CRMF001A.MaxVolatility, and Alaris.Core.Math.CRMF001A.MinVolatility.
Referenced by Alaris.Core.Math.CRMF001A.BSImpliedVolatility().
CorradoMillerGuess()
static double Alaris.Core.Math.CRMF001A.CorradoMillerGuess (double S, double K, double tau, double r, double q, double marketPrice, bool isCall) inline static private
Corrado-Miller (1996) closed-form IV approximation.
Formula for calls (puts via put-call parity normalization): σ ≈ √(2π/τ) × (C - (F-K)/2) / (F+K)/2
With correction for moneyness.
Definition at line 433 of file CRMF001A.cs.
References Alaris.Core.Math.CRMF001A.MachineEpsilon, Alaris.Core.Math.CRMF001A.MinVolatility, and Alaris.Core.Math.CRMF001A.SqrtTwoPi.
Referenced by Alaris.Core.Math.CRMF001A.BSImpliedVolatility().
DteToYears()
static double Alaris.Core.Math.CRMF001A.DteToYears (int dte) inline static
Converts days to expiry to years.
Parameters
dte Days to expiry.
Returns
Time in years.
Definition at line 608 of file CRMF001A.cs.
References Alaris.Core.Math.CRMF001A.TradingDaysPerYear.
Erf()
static double Alaris.Core.Math.CRMF001A.Erf (double x) inline static
Error function erf(x) using Abramowitz and Stegun formula 7.1.26.
Parameters
x Input value.
Returns
erf(x) ∈ [-1, 1]
Maximum error: 1.5e-7 (Abramowitz & Stegun 7.1.26)
Coefficients: a₁ = 0.254829592, a₂ = -0.284496736, a₃ = 1.421413741 a₄ = -1.453152027, a₅ = 1.061405429, p = 0.3275911
Definition at line 67 of file CRMF001A.cs.
Referenced by Alaris.Core.Math.CRMF001A.NormalCDF().
IsValidVolatility()
static bool Alaris.Core.Math.CRMF001A.IsValidVolatility (double sigma) inline static
Validates that a volatility value is within bounds.
Parameters
sigma Volatility to validate.
Returns
True if valid.
Definition at line 585 of file CRMF001A.cs.
References Alaris.Core.Math.CRMF001A.MaxVolatility, and Alaris.Core.Math.CRMF001A.MinVolatility.
NormalCDF()
static double Alaris.Core.Math.CRMF001A.NormalCDF (double x) inline static
Standard normal cumulative distribution function Φ(x).
Parameters
x Input value.
Returns
Φ(x) = P(Z ≤ x) ∈ [0, 1]
Computes Φ(x) = (1 + erf(x/√2))/2 Accuracy: inherits from Erf (max error 1.5e-7)
Definition at line 103 of file CRMF001A.cs.
References Alaris.Core.Math.CRMF001A.Erf(), and Alaris.Core.Math.CRMF001A.Sqrt2.
Referenced by Alaris.Core.Pricing.CREN004A.BlackScholesEuropean(), Alaris.Core.Math.CRMF001A.BSDelta(), Alaris.Core.Math.CRMF001A.BSPrice(), Alaris.Core.Math.CRMF001A.BSTheta(), Alaris.Core.Pricing.CREN004A.ComputeIntegralD(), Alaris.Core.Pricing.CREN004A.ComputeIntegralN(), Alaris.Core.Pricing.CREN004A.FixedPointUpdate(), Alaris.Core.Pricing.CREN004A.FixedPointUpdateLower(), Alaris.Core.Pricing.CREN004A.IntegrateDoubleBoundaryPremium(), and Alaris.Core.Pricing.CREN004A.IntegrateEarlyExercisePremium().
NormalPDF()
static double Alaris.Core.Math.CRMF001A.NormalPDF (double x) inline static
Standard normal probability density function φ(x).
Parameters
x Input value.
Returns
φ(x) = exp(-x²/2)/√(2π)
Full double precision. For |x| > 38, returns 0 (underflow).
Definition at line 116 of file CRMF001A.cs.
References Alaris.Core.Math.CRMF001A.InvSqrtTwoPi.
Referenced by Alaris.Core.Math.CRMF001A.BSGamma(), Alaris.Core.Math.CRMF001A.BSTheta(), and Alaris.Core.Math.CRMF001A.BSVega().
YearsToDte()
static int Alaris.Core.Math.CRMF001A.YearsToDte (double tau) inline static
Converts years to days to expiry.
Parameters
tau Time in years.
Returns
Days to expiry (rounded).
Definition at line 618 of file CRMF001A.cs.
References Alaris.Core.Math.CRMF001A.TradingDaysPerYear.
Member Data Documentation
DefaultTolerance
const double Alaris.Core.Math.CRMF001A.DefaultTolerance = 1e-10 static
Default tolerance for root-finding algorithms.
Definition at line 33 of file CRMF001A.cs.
InvSqrtTwoPi
const double Alaris.Core.Math.CRMF001A.InvSqrtTwoPi = 0.3989422804014327 static
1/√(2π) for PDF calculations.
Definition at line 23 of file CRMF001A.cs.
Referenced by Alaris.Core.Math.CRMF001A.NormalPDF().
MachineEpsilon
const double Alaris.Core.Math.CRMF001A.MachineEpsilon = 2.220446049250313e-16 static
Machine epsilon for double precision (2.22e-16).
Definition at line 13 of file CRMF001A.cs.
Referenced by Alaris.Core.Math.CRMF001A.BSImpliedVolatility(), Alaris.Core.Math.CRMF001A.BSImpliedVolatilityBrent(), Alaris.Core.Math.CRMF001A.BSVolga(), and Alaris.Core.Math.CRMF001A.CorradoMillerGuess().
MaxVolatility
const double Alaris.Core.Math.CRMF001A.MaxVolatility = 5.0 static
Maximum IV bound (500% annualized).
Definition at line 38 of file CRMF001A.cs.
Referenced by Alaris.Core.Math.CRMF001A.BSImpliedVolatility(), Alaris.Core.Math.CRMF001A.BSImpliedVolatilityBrent(), Alaris.Core.Math.CRMF001A.ClampVolatility(), and Alaris.Core.Math.CRMF001A.IsValidVolatility().
MinTimeToExpiry
const double Alaris.Core.Math.CRMF001A.MinTimeToExpiry = 1.0 / 252.0 static
Minimum time to expiry (1 trading day).
Definition at line 48 of file CRMF001A.cs.
MinVolatility
const double Alaris.Core.Math.CRMF001A.MinVolatility = 0.001 static
Minimum IV bound (0.1% annualized).
Definition at line 43 of file CRMF001A.cs.
Referenced by Alaris.Core.Math.CRMF001A.BSImpliedVolatilityBrent(), Alaris.Core.Math.CRMF001A.ClampVolatility(), Alaris.Core.Math.CRMF001A.CorradoMillerGuess(), and Alaris.Core.Math.CRMF001A.IsValidVolatility().
Sqrt2
const double Alaris.Core.Math.CRMF001A.Sqrt2 = 1.4142135623730951 static
√2 for erf to CDF conversion.
Definition at line 28 of file CRMF001A.cs.
Referenced by Alaris.Core.Math.CRMF001A.NormalCDF().
SqrtTwoPi
const double Alaris.Core.Math.CRMF001A.SqrtTwoPi = 2.5066282746310005 static
√(2π) for normal distribution calculations.
Definition at line 18 of file CRMF001A.cs.
Referenced by Alaris.Core.Math.CRMF001A.CorradoMillerGuess().
TradingDaysPerYear
const int Alaris.Core.Math.CRMF001A.TradingDaysPerYear = 252 static
Trading days per year.
Definition at line 53 of file CRMF001A.cs.
Referenced by Alaris.Core.Math.CRMF001A.DteToYears(), and Alaris.Core.Math.CRMF001A.YearsToDte().
The documentation for this class was generated from the following file:
src/Alaris.Core/Math/CRMF001A.cs