Alaris: Alaris.Infrastructure.Events.Infrastructure.EVIF002B Class Reference
Alaris.Infrastructure.Events.Infrastructure.EVIF002B Class Reference sealed
File-based persistent implementation of EVCR004A for production use.
Public Member Functions
EVIF002B (string storagePath)
Initializes a new file-based audit logger with binary format.
async Task LogAsync (AuditEntry entry, CancellationToken cancellationToken=default)
Logs an audit entry for a system action.
Parameters
entry The audit entry to log.
cancellationToken Cancellation token.
async Task< IReadOnlyList< AuditEntry > > GetEntriesForEntityAsync (string entityType, string entityId, CancellationToken cancellationToken=default)
Retrieves audit entries for a specific entity.
Parameters
entityType The type of entity.
entityId The entity identifier.
cancellationToken Cancellation token.
Returns
All audit entries for the entity.
async Task< IReadOnlyList< AuditEntry > > GetEntriesByInitiatorAsync (string initiatedBy, CancellationToken cancellationToken=default)
Retrieves audit entries initiated by a specific user or system.
Parameters
initiatedBy The user or system identifier.
cancellationToken Cancellation token.
Returns
All audit entries initiated by the specified actor.
async Task< IReadOnlyList< AuditEntry > > GetEntriesByTimeRangeAsync (DateTime fromUtc, DateTime toUtc, CancellationToken cancellationToken=default)
Retrieves audit entries within a time range.
Parameters
fromUtc Start time (inclusive).
toUtc End time (inclusive).
cancellationToken Cancellation token.
Returns
Audit entries within the time range.
void Dispose ()
Private Member Functions
string GetLogPathForDate (DateTime date)
string[] GetLogFilesInRange (DateTime fromUtc, DateTime toUtc)
async IAsyncEnumerable< AuditEntry > ReadAllEntriesAsync ([System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken cancellationToken=default)
Static Private Member Functions
static byte[] SerializeAuditEntry (AuditEntry entry)
static AuditEntry DeserializeAuditEntry (ReadOnlySpan< byte > buffer)
static async IAsyncEnumerable< AuditEntry > ReadEntriesFromFileAsync (string logPath, [System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken cancellationToken=default)
Private Attributes
readonly string _storagePath
readonly SemaphoreSlim _writeSemaphore = new(1, 1)
readonly SemaphoreSlim _readSemaphore = new(1, 1)
bool _disposed
Static Private Attributes
const int HeaderSize = 48
const int MaxRecordSize = 1024 * 1024
Detailed Description
File-based persistent implementation of EVCR004A for production use.
Storage format: Binary (SBE-style)
Fixed header: 48 bytes
Variable fields: length-prefixed UTF-8 strings
Date-based file rotation for manageability
Binary Layout per record: [0-15] AuditId (Guid - 16 bytes) [16-23] OccurredAtUtc (long, ticks) [24-27] ActionLength (int) [28-31] EntityTypeLength (int) [32-35] EntityIdLength (int) [36-39] InitiatedByLength (int) [40-43] DetailsLength (int) [44-47] TotalRecordLength (int) [48...] Variable-length string data
Definition at line 32 of file EVIF002B.cs.
Constructor & Destructor Documentation
EVIF002B()
Alaris.Infrastructure.Events.Infrastructure.EVIF002B.EVIF002B (string storagePath) inline
Initializes a new file-based audit logger with binary format.
Parameters
storagePath Directory for audit log files.
Definition at line 46 of file EVIF002B.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF002B._storagePath.
Member Function Documentation
DeserializeAuditEntry()
static AuditEntry Alaris.Infrastructure.Events.Infrastructure.EVIF002B.DeserializeAuditEntry (ReadOnlySpan< byte > buffer) inline static private
Definition at line 230 of file EVIF002B.cs.
References Alaris.Infrastructure.Events.Core.AuditEntry.
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF002B.ReadEntriesFromFileAsync().
Dispose()
void Alaris.Infrastructure.Events.Infrastructure.EVIF002B.Dispose () inline
Definition at line 403 of file EVIF002B.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF002B._disposed, Alaris.Infrastructure.Events.Infrastructure.EVIF002B._readSemaphore, and Alaris.Infrastructure.Events.Infrastructure.EVIF002B._writeSemaphore.
GetEntriesByInitiatorAsync()
async Task< IReadOnlyList< AuditEntry > > Alaris.Infrastructure.Events.Infrastructure.EVIF002B.GetEntriesByInitiatorAsync (string initiatedBy, CancellationToken cancellationToken = default) inline
Retrieves audit entries initiated by a specific user or system.
Parameters
initiatedBy The user or system identifier.
cancellationToken Cancellation token.
Returns
All audit entries initiated by the specified actor.
Implements Alaris.Infrastructure.Events.Core.EVCR004A.
Definition at line 115 of file EVIF002B.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF002B._disposed, Alaris.Infrastructure.Events.Infrastructure.EVIF002B._readSemaphore, Alaris.Infrastructure.Events.Core.AuditEntry, and Alaris.Infrastructure.Events.Infrastructure.EVIF002B.ReadAllEntriesAsync().
GetEntriesByTimeRangeAsync()
async Task< IReadOnlyList< AuditEntry > > Alaris.Infrastructure.Events.Infrastructure.EVIF002B.GetEntriesByTimeRangeAsync (DateTime fromUtc, DateTime toUtc, CancellationToken cancellationToken = default) inline
Retrieves audit entries within a time range.
Parameters
fromUtc Start time (inclusive).
toUtc End time (inclusive).
cancellationToken Cancellation token.
Returns
Audit entries within the time range.
Implements Alaris.Infrastructure.Events.Core.EVCR004A.
Definition at line 144 of file EVIF002B.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF002B._disposed, Alaris.Infrastructure.Events.Infrastructure.EVIF002B._readSemaphore, Alaris.Infrastructure.Events.Core.AuditEntry, Alaris.Infrastructure.Events.Infrastructure.EVIF002B.GetLogFilesInRange(), and Alaris.Infrastructure.Events.Infrastructure.EVIF002B.ReadEntriesFromFileAsync().
GetEntriesForEntityAsync()
async Task< IReadOnlyList< AuditEntry > > Alaris.Infrastructure.Events.Infrastructure.EVIF002B.GetEntriesForEntityAsync (string entityType, string entityId, CancellationToken cancellationToken = default) inline
Retrieves audit entries for a specific entity.
Parameters
entityType The type of entity.
entityId The entity identifier.
cancellationToken Cancellation token.
Returns
All audit entries for the entity.
Implements Alaris.Infrastructure.Events.Core.EVCR004A.
Definition at line 84 of file EVIF002B.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF002B._disposed, Alaris.Infrastructure.Events.Infrastructure.EVIF002B._readSemaphore, Alaris.Infrastructure.Events.Core.AuditEntry, and Alaris.Infrastructure.Events.Infrastructure.EVIF002B.ReadAllEntriesAsync().
GetLogFilesInRange()
string[] Alaris.Infrastructure.Events.Infrastructure.EVIF002B.GetLogFilesInRange (DateTime fromUtc, DateTime toUtc) inline private
Definition at line 282 of file EVIF002B.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF002B._storagePath.
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF002B.GetEntriesByTimeRangeAsync().
GetLogPathForDate()
string Alaris.Infrastructure.Events.Infrastructure.EVIF002B.GetLogPathForDate (DateTime date) inline private
Definition at line 277 of file EVIF002B.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF002B._storagePath.
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF002B.LogAsync().
LogAsync()
async Task Alaris.Infrastructure.Events.Infrastructure.EVIF002B.LogAsync (AuditEntry entry, CancellationToken cancellationToken = default) inline
Logs an audit entry for a system action.
Parameters
entry The audit entry to log.
cancellationToken Cancellation token.
Implements Alaris.Infrastructure.Events.Core.EVCR004A.
Definition at line 55 of file EVIF002B.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF002B._disposed, Alaris.Infrastructure.Events.Infrastructure.EVIF002B._writeSemaphore, Alaris.Infrastructure.Events.Infrastructure.EVIF002B.GetLogPathForDate(), and Alaris.Infrastructure.Events.Infrastructure.EVIF002B.SerializeAuditEntry().
Referenced by Alaris.Test.Unit.TSUN033A.EVIF002B_GetEntriesByInitiatorAsync_FiltersCorrectly(), and Alaris.Test.Unit.TSUN033A.EVIF002B_GetEntriesByTimeRangeAsync_FiltersCorrectly().
ReadAllEntriesAsync()
async IAsyncEnumerable< AuditEntry > Alaris.Infrastructure.Events.Infrastructure.EVIF002B.ReadAllEntriesAsync ([System::Runtime::CompilerServices::EnumeratorCancellation] CancellationToken cancellationToken = default) inline private
Definition at line 316 of file EVIF002B.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF002B._storagePath, Alaris.Infrastructure.Events.Core.AuditEntry, and Alaris.Infrastructure.Events.Infrastructure.EVIF002B.ReadEntriesFromFileAsync().
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF002B.GetEntriesByInitiatorAsync(), and Alaris.Infrastructure.Events.Infrastructure.EVIF002B.GetEntriesForEntityAsync().
ReadEntriesFromFileAsync()
static async IAsyncEnumerable< AuditEntry > Alaris.Infrastructure.Events.Infrastructure.EVIF002B.ReadEntriesFromFileAsync (string logPath, [System::Runtime::CompilerServices::EnumeratorCancellation] CancellationToken cancellationToken = default) inline static private
Definition at line 335 of file EVIF002B.cs.
References Alaris.Infrastructure.Events.Core.AuditEntry, Alaris.Infrastructure.Events.Infrastructure.EVIF002B.DeserializeAuditEntry(), Alaris.Infrastructure.Events.Infrastructure.EVIF002B.HeaderSize, and Alaris.Infrastructure.Events.Infrastructure.EVIF002B.MaxRecordSize.
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF002B.GetEntriesByTimeRangeAsync(), and Alaris.Infrastructure.Events.Infrastructure.EVIF002B.ReadAllEntriesAsync().
SerializeAuditEntry()
static byte[] Alaris.Infrastructure.Events.Infrastructure.EVIF002B.SerializeAuditEntry (AuditEntry entry) inline static private
Definition at line 179 of file EVIF002B.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF002B.HeaderSize.
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF002B.LogAsync().
Member Data Documentation
_disposed
bool Alaris.Infrastructure.Events.Infrastructure.EVIF002B._disposed private
Definition at line 37 of file EVIF002B.cs.
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF002B.Dispose(), Alaris.Infrastructure.Events.Infrastructure.EVIF002B.GetEntriesByInitiatorAsync(), Alaris.Infrastructure.Events.Infrastructure.EVIF002B.GetEntriesByTimeRangeAsync(), Alaris.Infrastructure.Events.Infrastructure.EVIF002B.GetEntriesForEntityAsync(), and Alaris.Infrastructure.Events.Infrastructure.EVIF002B.LogAsync().
_readSemaphore
readonly SemaphoreSlim Alaris.Infrastructure.Events.Infrastructure.EVIF002B._readSemaphore = new(1, 1) private
Definition at line 36 of file EVIF002B.cs.
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF002B.Dispose(), Alaris.Infrastructure.Events.Infrastructure.EVIF002B.GetEntriesByInitiatorAsync(), Alaris.Infrastructure.Events.Infrastructure.EVIF002B.GetEntriesByTimeRangeAsync(), and Alaris.Infrastructure.Events.Infrastructure.EVIF002B.GetEntriesForEntityAsync().
_storagePath
readonly string Alaris.Infrastructure.Events.Infrastructure.EVIF002B._storagePath private
Definition at line 34 of file EVIF002B.cs.
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF002B.EVIF002B(), Alaris.Infrastructure.Events.Infrastructure.EVIF002B.GetLogFilesInRange(), Alaris.Infrastructure.Events.Infrastructure.EVIF002B.GetLogPathForDate(), and Alaris.Infrastructure.Events.Infrastructure.EVIF002B.ReadAllEntriesAsync().
_writeSemaphore
readonly SemaphoreSlim Alaris.Infrastructure.Events.Infrastructure.EVIF002B._writeSemaphore = new(1, 1) private
Definition at line 35 of file EVIF002B.cs.
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF002B.Dispose(), and Alaris.Infrastructure.Events.Infrastructure.EVIF002B.LogAsync().
HeaderSize
const int Alaris.Infrastructure.Events.Infrastructure.EVIF002B.HeaderSize = 48 static private
Definition at line 39 of file EVIF002B.cs.
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF002B.ReadEntriesFromFileAsync(), and Alaris.Infrastructure.Events.Infrastructure.EVIF002B.SerializeAuditEntry().
MaxRecordSize
const int Alaris.Infrastructure.Events.Infrastructure.EVIF002B.MaxRecordSize = 1024 * 1024 static private
Definition at line 40 of file EVIF002B.cs.
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF002B.ReadEntriesFromFileAsync().
The documentation for this class was generated from the following file:
src/Alaris.Infrastructure/Events/Infrastructure/EVIF002B.cs