Alaris: Alaris.Strategy.Hedge.STHD007B Class Reference
Alaris.Strategy.Hedge.STHD007B Class Reference sealed
Rule-based exit monitor with stall detection for calendar spreads.
Public Member Functions
STHD007B (ExitParameters? parameters=null, ILogger< STHD007B >? logger=null)
Initialises a new rule-based exit monitor.
void Reset (DateTime? entryTime=null)
Resets the monitor state for a new position.
ExitSignal Evaluate (double crushCaptured, double daysElapsed, double daysRemaining)
Evaluates exit conditions and returns recommendation.
Static Public Member Functions
static double ComputeCrushCaptured (double ivObserved, double ivExpected, double expectedCrush)
Computes crush captured from IV values.
static double ComputeExpectedCrush (double baseVolatility, double earningsJumpVolatility, double timeToExpiryAtEntry)
Computes expected crush from Leung-Santoli parameters.
Properties
bool IsInitialised [get]
Gets whether the monitor has been initialised.
double SmoothedRate [get]
Gets the current smoothed crush rate.
int UpdateCount [get]
Gets the number of updates performed.
Private Member Functions
ExitSignal CreateExitSignal (ExitReason reason, string message, double crushCaptured, double rate, double daysRemaining)
double ComputeHoldConfidence (double crushCaptured, double rate, double daysRemaining)
void SafeLog (Action logAction)
Static Private Member Functions
static double ComputeExitConfidence (ExitReason reason, double crushCaptured, double rate)
Private Attributes
readonly? ILogger< STHD007B > _logger
readonly ExitParameters _params
double _previousCrushCaptured
double _smoothedRate
bool _isInitialised
int _updateCount
DateTime _entryTime
Static Private Attributes
static readonly Action< ILogger, string, double, double, Exception?> LogExitSignal
static readonly Action< ILogger, double, double, Exception?> LogHoldSignal
Detailed Description
Rule-based exit monitor with stall detection for calendar spreads.
Definition at line 20 of file STHD007B.cs.
Constructor & Destructor Documentation
STHD007B()
Alaris.Strategy.Hedge.STHD007B.STHD007B (ExitParameters? parameters = null, ILogger< STHD007B >? logger = null) inline
Initialises a new rule-based exit monitor.
Definition at line 48 of file STHD007B.cs.
References Alaris.Strategy.Hedge.STHD007B._logger, Alaris.Strategy.Hedge.STHD007B._params, Alaris.Strategy.Hedge.ExitParameters(), and Alaris.Strategy.Hedge.STHD007B.Reset().
Member Function Documentation
ComputeCrushCaptured()
static double Alaris.Strategy.Hedge.STHD007B.ComputeCrushCaptured (double ivObserved, double ivExpected, double expectedCrush) inline static
Computes crush captured from IV values.
Parameters
ivObserved Current observed implied volatility.
ivExpected Leung-Santoli theoretical IV for this time.
expectedCrush Total expected IV crush magnitude.
Returns
Fraction of expected crush captured.
Definition at line 193 of file STHD007B.cs.
Referenced by Alaris.Test.Unit.RuleBasedExitTests.ComputeCrushCaptured_CorrectCalculation().
ComputeExitConfidence()
static double Alaris.Strategy.Hedge.STHD007B.ComputeExitConfidence (ExitReason reason, double crushCaptured, double rate) inline static private
Definition at line 250 of file STHD007B.cs.
Referenced by Alaris.Strategy.Hedge.STHD007B.CreateExitSignal().
ComputeExpectedCrush()
static double Alaris.Strategy.Hedge.STHD007B.ComputeExpectedCrush (double baseVolatility, double earningsJumpVolatility, double timeToExpiryAtEntry) inline static
Computes expected crush from Leung-Santoli parameters.
Parameters
baseVolatility Base (diffusion) volatility σ.
earningsJumpVolatility Earnings jump volatility σ_e.
timeToExpiryAtEntry Time to expiry at position entry (years).
Returns
Expected IV crush in volatility points.
Definition at line 212 of file STHD007B.cs.
ComputeHoldConfidence()
double Alaris.Strategy.Hedge.STHD007B.ComputeHoldConfidence (double crushCaptured, double rate, double daysRemaining) inline private
Definition at line 263 of file STHD007B.cs.
References Alaris.Strategy.Hedge.STHD007B._params.
Referenced by Alaris.Strategy.Hedge.STHD007B.Evaluate().
CreateExitSignal()
ExitSignal Alaris.Strategy.Hedge.STHD007B.CreateExitSignal (ExitReason reason, string message, double crushCaptured, double rate, double daysRemaining) inline private
Definition at line 231 of file STHD007B.cs.
References Alaris.Strategy.Hedge.STHD007B._logger, Alaris.Strategy.Hedge.STHD007B.ComputeExitConfidence(), Alaris.Strategy.Hedge.ExitSignal(), Alaris.Strategy.Hedge.STHD007B.LogExitSignal, Alaris.Strategy.Hedge.STHD007B.SafeLog(), and Alaris.Strategy.Hedge.STHD007B.SmoothedRate.
Referenced by Alaris.Strategy.Hedge.STHD007B.Evaluate().
Evaluate()
ExitSignal Alaris.Strategy.Hedge.STHD007B.Evaluate (double crushCaptured, double daysElapsed, double daysRemaining) inline
Evaluates exit conditions and returns recommendation.
Parameters
crushCaptured Fraction of expected crush captured: (IV_expected - IV_observed) / ExpectedCrush.
daysElapsed Trading days since entry.
daysRemaining Trading days until expiry.
Returns
Exit signal with reason and diagnostics.
Definition at line 90 of file STHD007B.cs.
References Alaris.Strategy.Hedge.STHD007B._isInitialised, Alaris.Strategy.Hedge.STHD007B._logger, Alaris.Strategy.Hedge.STHD007B._params, Alaris.Strategy.Hedge.STHD007B._previousCrushCaptured, Alaris.Strategy.Hedge.STHD007B._smoothedRate, Alaris.Strategy.Hedge.STHD007B._updateCount, Alaris.Strategy.Hedge.STHD007B.ComputeHoldConfidence(), Alaris.Strategy.Hedge.STHD007B.CreateExitSignal(), Alaris.Strategy.Hedge.ExitSignal(), Alaris.Strategy.Hedge.STHD007B.LogHoldSignal, Alaris.Strategy.Hedge.STHD007B.SafeLog(), and Alaris.Strategy.Hedge.STHD007B.SmoothedRate.
Referenced by Alaris.Test.Unit.RuleBasedExitTests.Evaluate_ApproachingExpiry_TimeDecayExit(), Alaris.Test.Unit.RuleBasedExitTests.Evaluate_GoodProgress_Holds(), Alaris.Test.Unit.RuleBasedExitTests.Evaluate_SignificantCaptureButStalled_Exits(), Alaris.Test.Unit.RuleBasedExitTests.Evaluate_TargetCapture_ExitsImmediately(), Alaris.Test.Unit.RuleBasedExitTests.Evaluate_TracksUpdateCount(), and Alaris.Test.Unit.RuleBasedExitTests.SmoothedRate_TracksRateChange().
Reset()
void Alaris.Strategy.Hedge.STHD007B.Reset (DateTime? entryTime = null) inline
Resets the monitor state for a new position.
Parameters
entryTime Position entry timestamp.
Definition at line 74 of file STHD007B.cs.
References Alaris.Strategy.Hedge.STHD007B._entryTime, Alaris.Strategy.Hedge.STHD007B._isInitialised, Alaris.Strategy.Hedge.STHD007B._previousCrushCaptured, Alaris.Strategy.Hedge.STHD007B._smoothedRate, and Alaris.Strategy.Hedge.STHD007B._updateCount.
Referenced by Alaris.Strategy.Hedge.STHD007B.STHD007B().
SafeLog()
void Alaris.Strategy.Hedge.STHD007B.SafeLog (Action logAction) inline private
Definition at line 277 of file STHD007B.cs.
References Alaris.Strategy.Hedge.STHD007B._logger.
Referenced by Alaris.Strategy.Hedge.STHD007B.CreateExitSignal(), and Alaris.Strategy.Hedge.STHD007B.Evaluate().
Member Data Documentation
_entryTime
DateTime Alaris.Strategy.Hedge.STHD007B._entryTime private
Definition at line 30 of file STHD007B.cs.
Referenced by Alaris.Strategy.Hedge.STHD007B.Reset().
_isInitialised
bool Alaris.Strategy.Hedge.STHD007B._isInitialised private
Definition at line 28 of file STHD007B.cs.
Referenced by Alaris.Strategy.Hedge.STHD007B.Evaluate(), and Alaris.Strategy.Hedge.STHD007B.Reset().
_logger
readonly? ILogger<STHD007B> Alaris.Strategy.Hedge.STHD007B._logger private
Definition at line 22 of file STHD007B.cs.
Referenced by Alaris.Strategy.Hedge.STHD007B.STHD007B(), Alaris.Strategy.Hedge.STHD007B.CreateExitSignal(), Alaris.Strategy.Hedge.STHD007B.Evaluate(), and Alaris.Strategy.Hedge.STHD007B.SafeLog().
_params
readonly ExitParameters Alaris.Strategy.Hedge.STHD007B._params private
Definition at line 23 of file STHD007B.cs.
Referenced by Alaris.Strategy.Hedge.STHD007B.STHD007B(), Alaris.Strategy.Hedge.STHD007B.ComputeHoldConfidence(), and Alaris.Strategy.Hedge.STHD007B.Evaluate().
_previousCrushCaptured
double Alaris.Strategy.Hedge.STHD007B._previousCrushCaptured private
Definition at line 26 of file STHD007B.cs.
Referenced by Alaris.Strategy.Hedge.STHD007B.Evaluate(), and Alaris.Strategy.Hedge.STHD007B.Reset().
_smoothedRate
double Alaris.Strategy.Hedge.STHD007B._smoothedRate private
Definition at line 27 of file STHD007B.cs.
Referenced by Alaris.Strategy.Hedge.STHD007B.Evaluate(), and Alaris.Strategy.Hedge.STHD007B.Reset().
_updateCount
int Alaris.Strategy.Hedge.STHD007B._updateCount private
Definition at line 29 of file STHD007B.cs.
Referenced by Alaris.Strategy.Hedge.STHD007B.Evaluate(), and Alaris.Strategy.Hedge.STHD007B.Reset().
LogExitSignal
readonly Action<ILogger, string, double, double, Exception?> Alaris.Strategy.Hedge.STHD007B.LogExitSignal static private
Initial value:
=
        LoggerMessage.Define<string, double, double>(
            LogLevel.Information,
            new EventId(1, nameof(LogExitSignal)),
            "Exit signal: {Reason} (crush={Crush:P1}, rate={Rate:F4})")
Definition at line 33 of file STHD007B.cs.
Referenced by Alaris.Strategy.Hedge.STHD007B.CreateExitSignal().
LogHoldSignal
readonly Action<ILogger, double, double, Exception?> Alaris.Strategy.Hedge.STHD007B.LogHoldSignal static private
Initial value:
=
        LoggerMessage.Define<double, double>(
            LogLevel.Debug,
            new EventId(2, nameof(LogHoldSignal)),
            "Hold signal: crush={Crush:P1}, rate={Rate:F4}")
Definition at line 39 of file STHD007B.cs.
Referenced by Alaris.Strategy.Hedge.STHD007B.Evaluate().
Property Documentation
IsInitialised
bool Alaris.Strategy.Hedge.STHD007B.IsInitialised get
Gets whether the monitor has been initialised.
Definition at line 58 of file STHD007B.cs.
SmoothedRate
double Alaris.Strategy.Hedge.STHD007B.SmoothedRate get
Gets the current smoothed crush rate.
Definition at line 63 of file STHD007B.cs.
Referenced by Alaris.Strategy.Hedge.STHD007B.CreateExitSignal(), and Alaris.Strategy.Hedge.STHD007B.Evaluate().
UpdateCount
int Alaris.Strategy.Hedge.STHD007B.UpdateCount get
Gets the number of updates performed.
Definition at line 68 of file STHD007B.cs.
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Hedge/STHD007B.cs