Alaris: Alaris.Strategy.Serialization.STsr001A Class Reference
Alaris.Strategy.Serialization.STsr001A Class Reference
Binary serialization adapter for strategy hot path structures. Component ID: STsr001A.
Classes
struct PricingParamsData
Struct for binary-encoded pricing parameters (STDT003A equivalent).
struct TermStructurePointData
Struct for binary-encoded term structure point.
Static Public Member Functions
static int EncodePricingParams (double underlyingPrice, double strike, int expiryDays, int valuationDays, double impliedVol, double riskFreeRate, double dividendYield, bool isCall, Span< byte > buffer)
Encodes pricing parameters to binary format.
static PricingParamsData DecodePricingParams (ReadOnlySpan< byte > buffer)
Decodes pricing parameters from binary format.
static int EncodeTermPoint (int daysToExpiry, double impliedVol, long openInterestWeight, Span< byte > buffer)
Encodes a term structure point to binary format.
static TermStructurePointData DecodeTermPoint (ReadOnlySpan< byte > buffer)
Decodes a term structure point from binary format.
static int EncodeTermCurve (ReadOnlySpan<(int DaysToExpiry, double IV, long OIWeight)> points, Span< byte > buffer)
Encodes a term structure curve (multiple points) to binary format.
Static Public Attributes
const int PricingParamsEncodedSize = 68
Fixed size of encoded pricing parameters. Layout: 7*8 (mantissas) + 2*4 (days) + 1 (type) + 3 (padding) = 68 bytes.
const int TermPointEncodedSize = 20
Fixed size of encoded term structure point. Layout: 4 (days) + 8 (IV) + 8 (OI weight) = 20 bytes.
Static Private Attributes
const byte FormatVersion = 1
Detailed Description
Binary serialization adapter for strategy hot path structures. Component ID: STsr001A.
Definition at line 13 of file STsr001A.cs.
Member Function Documentation
DecodePricingParams()
static PricingParamsData Alaris.Strategy.Serialization.STsr001A.DecodePricingParams (ReadOnlySpan< byte > buffer) inline static
Decodes pricing parameters from binary format.
Definition at line 107 of file STsr001A.cs.
DecodeTermPoint()
static TermStructurePointData Alaris.Strategy.Serialization.STsr001A.DecodeTermPoint (ReadOnlySpan< byte > buffer) inline static
Decodes a term structure point from binary format.
Definition at line 183 of file STsr001A.cs.
EncodePricingParams()
static int Alaris.Strategy.Serialization.STsr001A.EncodePricingParams (double underlyingPrice, double strike, int expiryDays, int valuationDays, double impliedVol, double riskFreeRate, double dividendYield, bool isCall, Span< byte > buffer) inline static
Encodes pricing parameters to binary format.
Definition at line 68 of file STsr001A.cs.
References Alaris.Infrastructure.Protocol.Serialization.PLSR001A.ToMantissa().
EncodeTermCurve()
static int Alaris.Strategy.Serialization.STsr001A.EncodeTermCurve (ReadOnlySpan<(int DaysToExpiry, double IV, long OIWeight)> points, Span< byte > buffer) inline static
Encodes a term structure curve (multiple points) to binary format.
Definition at line 199 of file STsr001A.cs.
References Alaris.Strategy.Serialization.STsr001A.EncodeTermPoint(), and Alaris.Strategy.Serialization.STsr001A.FormatVersion.
EncodeTermPoint()
static int Alaris.Strategy.Serialization.STsr001A.EncodeTermPoint (int daysToExpiry, double impliedVol, long openInterestWeight, Span< byte > buffer) inline static
Encodes a term structure point to binary format.
Definition at line 166 of file STsr001A.cs.
References Alaris.Infrastructure.Protocol.Serialization.PLSR001A.ToMantissa().
Referenced by Alaris.Strategy.Serialization.STsr001A.EncodeTermCurve().
Member Data Documentation
FormatVersion
const byte Alaris.Strategy.Serialization.STsr001A.FormatVersion = 1 static private
Definition at line 15 of file STsr001A.cs.
Referenced by Alaris.Strategy.Serialization.STsr001A.EncodeTermCurve().
PricingParamsEncodedSize
const int Alaris.Strategy.Serialization.STsr001A.PricingParamsEncodedSize = 68 static
Fixed size of encoded pricing parameters. Layout: 7*8 (mantissas) + 2*4 (days) + 1 (type) + 3 (padding) = 68 bytes.
Definition at line 63 of file STsr001A.cs.
TermPointEncodedSize
const int Alaris.Strategy.Serialization.STsr001A.TermPointEncodedSize = 20 static
Fixed size of encoded term structure point. Layout: 4 (days) + 8 (IV) + 8 (OI weight) = 20 bytes.
Definition at line 161 of file STsr001A.cs.
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Serialization/STsr001A.cs