Alaris: Alaris.Test.Unit.TSUN029A Class Reference
Alaris.Test.Unit.TSUN029A Class Reference sealed
TSUN029A: Unit tests for data models and provider interfaces.
Public Member Functions
void OptionContract_Mid_IsAverageOfBidAsk (decimal bid, decimal ask, decimal expectedMid)
Option contract Mid price is average of Bid and Ask.
void OptionContract_Spread_IsAskMinusBid (decimal bid, decimal ask, decimal expectedSpread)
Option contract Spread is Ask minus Bid.
void OptionContract_SpreadNonNegative_WhenValidBidAsk ()
Option contract bid should not exceed ask.
void OptionChainSnapshot_Calls_ReturnsOnlyCalls ()
Option chain Calls filter returns only calls.
void OptionChainSnapshot_Puts_ReturnsOnlyPuts ()
Option chain Puts filter returns only puts.
void OptionChainSnapshot_CallsPlusPuts_EqualsTotal ()
Option chain Calls + Puts equals total contracts.
void OptionChainSnapshot_ByExpiration_GroupsCorrectly ()
Option chain ByExpiration groups correctly.
void PriceBar_OHLCRelationship_IsValid ()
Price bar OHLC relationship: Low ≤ O,C ≤ High.
void PriceBar_Volume_NonNegative (long volume)
Price bar volume should be non-negative.
void EarningsEvent_Timing_IsValid (EarningsTiming timing)
Earnings event has valid timing values.
void EarningsEvent_FiscalQuarter_IsValid (string quarter)
Earnings event fiscal quarter format.
void MarketDataSnapshot_ContainsAllRequiredData ()
Market data snapshot aggregates data correctly.
void MarketDataSnapshot_HistoricalBars_AreOrdered ()
Market data snapshot historical bars are ordered by date.
void DataQualityResult_Status_IsValid (ValidationStatus status)
Validation status enum values.
void DataQualityResult_Warnings_CanBeProvided ()
Data quality result can have warnings.
async Task DTpr003A_GetHistoricalBarsAsync_ReturnsBars ()
Market data provider returns historical bars.
async Task DTpr003A_GetOptionChainAsync_ReturnsChain ()
Market data provider returns option chain.
async Task DTpr003A_GetSpotPriceAsync_ReturnsValidPrice ()
Market data provider returns valid spot price.
async Task DTpr004A_GetUpcomingEarningsAsync_ReturnsEvents ()
Earnings provider returns upcoming earnings.
async Task DTpr004A_GetHistoricalEarningsAsync_ReturnsEvents ()
Earnings provider returns historical earnings.
async Task DTpr005A_GetCurrentRateAsync_ReturnsValidRate ()
Risk-free rate provider returns valid rate.
async Task DTpr005A_GetHistoricalRatesAsync_ReturnsRates ()
Risk-free rate provider returns historical rates.
async Task DTpr003A_GetSpotPriceAsync_RespectsCancel ()
Provider cancellation token is respected.
Static Private Member Functions
static OptionContract CreateTestOptionContract (decimal bid=5.00m, decimal ask=5.20m)
static OptionChainSnapshot CreateTestOptionChain (int numStrikes=5, int numExpiries=2)
static MarketDataSnapshot CreateTestMarketDataSnapshot ()
Detailed Description
TSUN029A: Unit tests for data models and provider interfaces.
Definition at line 34 of file TSUN029A.cs.
Member Function Documentation
CreateTestMarketDataSnapshot()
static MarketDataSnapshot Alaris.Test.Unit.TSUN029A.CreateTestMarketDataSnapshot () inline static private
Definition at line 566 of file TSUN029A.cs.
References Alaris.Test.Unit.TSUN029A.CreateTestOptionChain().
Referenced by Alaris.Test.Unit.TSUN029A.MarketDataSnapshot_ContainsAllRequiredData(), and Alaris.Test.Unit.TSUN029A.MarketDataSnapshot_HistoricalBars_AreOrdered().
CreateTestOptionChain()
static OptionChainSnapshot Alaris.Test.Unit.TSUN029A.CreateTestOptionChain (int numStrikes = 5, int numExpiries = 2) inline static private
Definition at line 514 of file TSUN029A.cs.
Referenced by Alaris.Test.Unit.TSUN029A.CreateTestMarketDataSnapshot(), Alaris.Test.Unit.TSUN029A.OptionChainSnapshot_ByExpiration_GroupsCorrectly(), Alaris.Test.Unit.TSUN029A.OptionChainSnapshot_Calls_ReturnsOnlyCalls(), Alaris.Test.Unit.TSUN029A.OptionChainSnapshot_CallsPlusPuts_EqualsTotal(), and Alaris.Test.Unit.TSUN029A.OptionChainSnapshot_Puts_ReturnsOnlyPuts().
CreateTestOptionContract()
static OptionContract Alaris.Test.Unit.TSUN029A.CreateTestOptionContract (decimal bid = 5::00m, decimal ask = 5::20m) inline static private
Definition at line 495 of file TSUN029A.cs.
Referenced by Alaris.Test.Unit.TSUN029A.OptionContract_Mid_IsAverageOfBidAsk(), Alaris.Test.Unit.TSUN029A.OptionContract_Spread_IsAskMinusBid(), and Alaris.Test.Unit.TSUN029A.OptionContract_SpreadNonNegative_WhenValidBidAsk().
DataQualityResult_Status_IsValid()
void Alaris.Test.Unit.TSUN029A.DataQualityResult_Status_IsValid (ValidationStatus status) inline
Validation status enum values.
Definition at line 315 of file TSUN029A.cs.
DataQualityResult_Warnings_CanBeProvided()
void Alaris.Test.Unit.TSUN029A.DataQualityResult_Warnings_CanBeProvided () inline
Data quality result can have warnings.
Definition at line 334 of file TSUN029A.cs.
DTpr003A_GetHistoricalBarsAsync_ReturnsBars()
async Task Alaris.Test.Unit.TSUN029A.DTpr003A_GetHistoricalBarsAsync_ReturnsBars () inline
Market data provider returns historical bars.
Definition at line 358 of file TSUN029A.cs.
References Alaris.Infrastructure.Data.Provider.DTpr003A.GetHistoricalBarsAsync().
DTpr003A_GetOptionChainAsync_ReturnsChain()
async Task Alaris.Test.Unit.TSUN029A.DTpr003A_GetOptionChainAsync_ReturnsChain () inline
Market data provider returns option chain.
Definition at line 378 of file TSUN029A.cs.
References Alaris.Infrastructure.Data.Provider.DTpr003A.GetOptionChainAsync().
DTpr003A_GetSpotPriceAsync_RespectsCancel()
async Task Alaris.Test.Unit.TSUN029A.DTpr003A_GetSpotPriceAsync_RespectsCancel () inline
Provider cancellation token is respected.
Definition at line 481 of file TSUN029A.cs.
References Alaris.Infrastructure.Data.Provider.DTpr003A.GetSpotPriceAsync().
DTpr003A_GetSpotPriceAsync_ReturnsValidPrice()
async Task Alaris.Test.Unit.TSUN029A.DTpr003A_GetSpotPriceAsync_ReturnsValidPrice () inline
Market data provider returns valid spot price.
Definition at line 396 of file TSUN029A.cs.
References Alaris.Infrastructure.Data.Provider.DTpr003A.GetSpotPriceAsync().
DTpr004A_GetHistoricalEarningsAsync_ReturnsEvents()
async Task Alaris.Test.Unit.TSUN029A.DTpr004A_GetHistoricalEarningsAsync_ReturnsEvents () inline
Earnings provider returns historical earnings.
Definition at line 429 of file TSUN029A.cs.
References Alaris.Infrastructure.Data.Provider.DTpr004A.GetHistoricalEarningsAsync().
DTpr004A_GetUpcomingEarningsAsync_ReturnsEvents()
async Task Alaris.Test.Unit.TSUN029A.DTpr004A_GetUpcomingEarningsAsync_ReturnsEvents () inline
Earnings provider returns upcoming earnings.
Definition at line 412 of file TSUN029A.cs.
References Alaris.Infrastructure.Data.Provider.DTpr004A.GetUpcomingEarningsAsync().
DTpr005A_GetCurrentRateAsync_ReturnsValidRate()
async Task Alaris.Test.Unit.TSUN029A.DTpr005A_GetCurrentRateAsync_ReturnsValidRate () inline
Risk-free rate provider returns valid rate.
Definition at line 446 of file TSUN029A.cs.
References Alaris.Infrastructure.Data.Provider.DTpr005A.GetCurrentRateAsync().
DTpr005A_GetHistoricalRatesAsync_ReturnsRates()
async Task Alaris.Test.Unit.TSUN029A.DTpr005A_GetHistoricalRatesAsync_ReturnsRates () inline
Risk-free rate provider returns historical rates.
Definition at line 462 of file TSUN029A.cs.
References Alaris.Infrastructure.Data.Provider.DTpr005A.GetHistoricalRatesAsync().
EarningsEvent_FiscalQuarter_IsValid()
void Alaris.Test.Unit.TSUN029A.EarningsEvent_FiscalQuarter_IsValid (string quarter) inline
Earnings event fiscal quarter format.
Definition at line 251 of file TSUN029A.cs.
EarningsEvent_Timing_IsValid()
void Alaris.Test.Unit.TSUN029A.EarningsEvent_Timing_IsValid (EarningsTiming timing) inline
Earnings event has valid timing values.
Definition at line 227 of file TSUN029A.cs.
MarketDataSnapshot_ContainsAllRequiredData()
void Alaris.Test.Unit.TSUN029A.MarketDataSnapshot_ContainsAllRequiredData () inline
Market data snapshot aggregates data correctly.
Definition at line 274 of file TSUN029A.cs.
References Alaris.Test.Unit.TSUN029A.CreateTestMarketDataSnapshot().
MarketDataSnapshot_HistoricalBars_AreOrdered()
void Alaris.Test.Unit.TSUN029A.MarketDataSnapshot_HistoricalBars_AreOrdered () inline
Market data snapshot historical bars are ordered by date.
Definition at line 293 of file TSUN029A.cs.
References Alaris.Test.Unit.TSUN029A.CreateTestMarketDataSnapshot().
OptionChainSnapshot_ByExpiration_GroupsCorrectly()
void Alaris.Test.Unit.TSUN029A.OptionChainSnapshot_ByExpiration_GroupsCorrectly () inline
Option chain ByExpiration groups correctly.
Definition at line 149 of file TSUN029A.cs.
References Alaris.Infrastructure.Data.Model.OptionChainSnapshot.ByExpiration, and Alaris.Test.Unit.TSUN029A.CreateTestOptionChain().
OptionChainSnapshot_Calls_ReturnsOnlyCalls()
void Alaris.Test.Unit.TSUN029A.OptionChainSnapshot_Calls_ReturnsOnlyCalls () inline
Option chain Calls filter returns only calls.
Definition at line 97 of file TSUN029A.cs.
References Alaris.Infrastructure.Data.Model.OptionChainSnapshot.Calls, and Alaris.Test.Unit.TSUN029A.CreateTestOptionChain().
OptionChainSnapshot_CallsPlusPuts_EqualsTotal()
void Alaris.Test.Unit.TSUN029A.OptionChainSnapshot_CallsPlusPuts_EqualsTotal () inline
Option chain Calls + Puts equals total contracts.
Definition at line 131 of file TSUN029A.cs.
References Alaris.Infrastructure.Data.Model.OptionChainSnapshot.Calls, and Alaris.Test.Unit.TSUN029A.CreateTestOptionChain().
OptionChainSnapshot_Puts_ReturnsOnlyPuts()
void Alaris.Test.Unit.TSUN029A.OptionChainSnapshot_Puts_ReturnsOnlyPuts () inline
Option chain Puts filter returns only puts.
Definition at line 114 of file TSUN029A.cs.
References Alaris.Test.Unit.TSUN029A.CreateTestOptionChain(), and Alaris.Infrastructure.Data.Model.OptionChainSnapshot.Puts.
OptionContract_Mid_IsAverageOfBidAsk()
void Alaris.Test.Unit.TSUN029A.OptionContract_Mid_IsAverageOfBidAsk (decimal bid, decimal ask, decimal expectedMid) inline
Option contract Mid price is average of Bid and Ask.
Definition at line 46 of file TSUN029A.cs.
References Alaris.Test.Unit.TSUN029A.CreateTestOptionContract(), and Alaris.Infrastructure.Data.Model.OptionContract.Mid.
OptionContract_Spread_IsAskMinusBid()
void Alaris.Test.Unit.TSUN029A.OptionContract_Spread_IsAskMinusBid (decimal bid, decimal ask, decimal expectedSpread) inline
Option contract Spread is Ask minus Bid.
Definition at line 66 of file TSUN029A.cs.
References Alaris.Test.Unit.TSUN029A.CreateTestOptionContract(), and Alaris.Infrastructure.Data.Model.OptionContract.Spread.
OptionContract_SpreadNonNegative_WhenValidBidAsk()
void Alaris.Test.Unit.TSUN029A.OptionContract_SpreadNonNegative_WhenValidBidAsk () inline
Option contract bid should not exceed ask.
Definition at line 82 of file TSUN029A.cs.
References Alaris.Test.Unit.TSUN029A.CreateTestOptionContract(), and Alaris.Infrastructure.Data.Model.OptionContract.Spread.
PriceBar_OHLCRelationship_IsValid()
void Alaris.Test.Unit.TSUN029A.PriceBar_OHLCRelationship_IsValid () inline
Price bar OHLC relationship: Low ≤ O,C ≤ High.
Definition at line 171 of file TSUN029A.cs.
PriceBar_Volume_NonNegative()
void Alaris.Test.Unit.TSUN029A.PriceBar_Volume_NonNegative (long volume) inline
Price bar volume should be non-negative.
Definition at line 199 of file TSUN029A.cs.
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN029A.cs