Alaris: Alaris.Test.Unit.STRK004ATests Class Reference
Alaris.Test.Unit.STRK004ATests Class Reference sealed
Unit tests for STRK004A - Priority Queue Capital Allocator. Tests queue-based allocation with heterogeneous opportunity ranking.
Public Member Functions
STRK004ATests ()
void CalculatePriority_WithHighEdgeRecommendedSignal_ReturnsHighPriority ()
void CalculatePriority_WithLowEdgeConsiderSignal_ReturnsLowerPriority ()
void CalculatePriority_WithAvoidSignal_ReturnsZero ()
void Allocate_WhenQueueEmpty_AcceptsNewOpportunity ()
void Allocate_WhenCandidateIsHigherPriority_RanksFirst ()
void Allocate_WhenCapacityExhausted_EvaluatesDisplacement ()
void Allocate_WhenCandidateCanDisplace_ReturnsDisplaceExisting ()
void Allocate_WithAvoidSignal_RejectsOpportunity ()
void RebalancePortfolio_WithMisallocatedPositions_ReturnsRecommendations ()
void Allocate_WithNullCandidate_ThrowsArgumentNullException ()
void Allocate_WithInvalidPortfolioValue_ThrowsArgumentOutOfRangeException (double portfolioValue)
Static Private Member Functions
static STCR004A CreateSignal (string symbol, STCR004AStrength strength, double ivRvRatio=1.30, double tsSlope=-0.004)
static OpenPosition CreateOpenPosition (string symbol, double priority, double allocation, double kellyFraction=0.10)
static List< Trade > GenerateHistoricalTrades (int count)
Private Attributes
readonly STRK001A _baseKelly
readonly STRK004A _queueAllocator
Detailed Description
Unit tests for STRK004A - Priority Queue Capital Allocator. Tests queue-based allocation with heterogeneous opportunity ranking.
Definition at line 14 of file TSUN016A.cs.
Constructor & Destructor Documentation
STRK004ATests()
Alaris.Test.Unit.STRK004ATests.STRK004ATests () inline
Definition at line 19 of file TSUN016A.cs.
References Alaris.Test.Unit.STRK004ATests._baseKelly, and Alaris.Test.Unit.STRK004ATests._queueAllocator.
Member Function Documentation
Allocate_WhenCandidateCanDisplace_ReturnsDisplaceExisting()
void Alaris.Test.Unit.STRK004ATests.Allocate_WhenCandidateCanDisplace_ReturnsDisplaceExisting () inline
Definition at line 145 of file TSUN016A.cs.
References Alaris.Test.Unit.STRK004ATests._queueAllocator, Alaris.Strategy.Risk.STRK004A.Allocate(), Alaris.Test.Unit.STRK004ATests.CreateOpenPosition(), Alaris.Test.Unit.STRK004ATests.CreateSignal(), Alaris.Test.Unit.STRK004ATests.GenerateHistoricalTrades(), and Alaris.Strategy.Risk.QueueAllocationResult.
Allocate_WhenCandidateIsHigherPriority_RanksFirst()
void Alaris.Test.Unit.STRK004ATests.Allocate_WhenCandidateIsHigherPriority_RanksFirst () inline
Definition at line 93 of file TSUN016A.cs.
References Alaris.Test.Unit.STRK004ATests._queueAllocator, Alaris.Strategy.Risk.STRK004A.Allocate(), Alaris.Test.Unit.STRK004ATests.CreateOpenPosition(), Alaris.Test.Unit.STRK004ATests.CreateSignal(), Alaris.Test.Unit.STRK004ATests.GenerateHistoricalTrades(), and Alaris.Strategy.Risk.QueueAllocationResult.
Allocate_WhenCapacityExhausted_EvaluatesDisplacement()
void Alaris.Test.Unit.STRK004ATests.Allocate_WhenCapacityExhausted_EvaluatesDisplacement () inline
Definition at line 119 of file TSUN016A.cs.
References Alaris.Test.Unit.STRK004ATests._queueAllocator, Alaris.Strategy.Risk.STRK004A.Allocate(), Alaris.Test.Unit.STRK004ATests.CreateOpenPosition(), Alaris.Test.Unit.STRK004ATests.CreateSignal(), Alaris.Test.Unit.STRK004ATests.GenerateHistoricalTrades(), and Alaris.Strategy.Risk.QueueAllocationResult.
Allocate_WhenQueueEmpty_AcceptsNewOpportunity()
void Alaris.Test.Unit.STRK004ATests.Allocate_WhenQueueEmpty_AcceptsNewOpportunity () inline
Definition at line 70 of file TSUN016A.cs.
References Alaris.Test.Unit.STRK004ATests._queueAllocator, Alaris.Strategy.Risk.STRK004A.Allocate(), Alaris.Test.Unit.STRK004ATests.CreateSignal(), Alaris.Test.Unit.STRK004ATests.GenerateHistoricalTrades(), and Alaris.Strategy.Risk.QueueAllocationResult.
Allocate_WithAvoidSignal_RejectsOpportunity()
void Alaris.Test.Unit.STRK004ATests.Allocate_WithAvoidSignal_RejectsOpportunity () inline
Definition at line 174 of file TSUN016A.cs.
References Alaris.Test.Unit.STRK004ATests._queueAllocator, Alaris.Strategy.Risk.STRK004A.Allocate(), Alaris.Test.Unit.STRK004ATests.CreateSignal(), Alaris.Test.Unit.STRK004ATests.GenerateHistoricalTrades(), and Alaris.Strategy.Risk.QueueAllocationResult.
Allocate_WithInvalidPortfolioValue_ThrowsArgumentOutOfRangeException()
void Alaris.Test.Unit.STRK004ATests.Allocate_WithInvalidPortfolioValue_ThrowsArgumentOutOfRangeException (double portfolioValue) inline
Definition at line 232 of file TSUN016A.cs.
References Alaris.Test.Unit.STRK004ATests._queueAllocator, Alaris.Strategy.Risk.STRK004A.Allocate(), Alaris.Test.Unit.STRK004ATests.CreateSignal(), and Alaris.Test.Unit.STRK004ATests.GenerateHistoricalTrades().
Allocate_WithNullCandidate_ThrowsArgumentNullException()
void Alaris.Test.Unit.STRK004ATests.Allocate_WithNullCandidate_ThrowsArgumentNullException () inline
Definition at line 216 of file TSUN016A.cs.
References Alaris.Test.Unit.STRK004ATests._queueAllocator, Alaris.Strategy.Risk.STRK004A.Allocate(), and Alaris.Test.Unit.STRK004ATests.GenerateHistoricalTrades().
CalculatePriority_WithAvoidSignal_ReturnsZero()
void Alaris.Test.Unit.STRK004ATests.CalculatePriority_WithAvoidSignal_ReturnsZero () inline
Definition at line 56 of file TSUN016A.cs.
References Alaris.Test.Unit.STRK004ATests._queueAllocator, Alaris.Strategy.Risk.STRK004A.CalculatePriority(), Alaris.Test.Unit.STRK004ATests.CreateSignal(), and Alaris.Test.Unit.STRK004ATests.GenerateHistoricalTrades().
CalculatePriority_WithHighEdgeRecommendedSignal_ReturnsHighPriority()
void Alaris.Test.Unit.STRK004ATests.CalculatePriority_WithHighEdgeRecommendedSignal_ReturnsHighPriority () inline
Definition at line 26 of file TSUN016A.cs.
References Alaris.Test.Unit.STRK004ATests._queueAllocator, Alaris.Strategy.Risk.STRK004A.CalculatePriority(), Alaris.Test.Unit.STRK004ATests.CreateSignal(), and Alaris.Test.Unit.STRK004ATests.GenerateHistoricalTrades().
CalculatePriority_WithLowEdgeConsiderSignal_ReturnsLowerPriority()
void Alaris.Test.Unit.STRK004ATests.CalculatePriority_WithLowEdgeConsiderSignal_ReturnsLowerPriority () inline
Definition at line 40 of file TSUN016A.cs.
References Alaris.Test.Unit.STRK004ATests._queueAllocator, Alaris.Strategy.Risk.STRK004A.CalculatePriority(), Alaris.Test.Unit.STRK004ATests.CreateSignal(), and Alaris.Test.Unit.STRK004ATests.GenerateHistoricalTrades().
CreateOpenPosition()
static OpenPosition Alaris.Test.Unit.STRK004ATests.CreateOpenPosition (string symbol, double priority, double allocation, double kellyFraction = 0::10) inline static private
Definition at line 266 of file TSUN016A.cs.
References Alaris.Strategy.Risk.OpenPosition.
Referenced by Alaris.Test.Unit.STRK004ATests.Allocate_WhenCandidateCanDisplace_ReturnsDisplaceExisting(), Alaris.Test.Unit.STRK004ATests.Allocate_WhenCandidateIsHigherPriority_RanksFirst(), Alaris.Test.Unit.STRK004ATests.Allocate_WhenCapacityExhausted_EvaluatesDisplacement(), and Alaris.Test.Unit.STRK004ATests.RebalancePortfolio_WithMisallocatedPositions_ReturnsRecommendations().
CreateSignal()
static STCR004A Alaris.Test.Unit.STRK004ATests.CreateSignal (string symbol, STCR004AStrength strength, double ivRvRatio = 1::30, double tsSlope = -0::004) inline static private
Definition at line 246 of file TSUN016A.cs.
Referenced by Alaris.Test.Unit.STRK004ATests.Allocate_WhenCandidateCanDisplace_ReturnsDisplaceExisting(), Alaris.Test.Unit.STRK004ATests.Allocate_WhenCandidateIsHigherPriority_RanksFirst(), Alaris.Test.Unit.STRK004ATests.Allocate_WhenCapacityExhausted_EvaluatesDisplacement(), Alaris.Test.Unit.STRK004ATests.Allocate_WhenQueueEmpty_AcceptsNewOpportunity(), Alaris.Test.Unit.STRK004ATests.Allocate_WithAvoidSignal_RejectsOpportunity(), Alaris.Test.Unit.STRK004ATests.Allocate_WithInvalidPortfolioValue_ThrowsArgumentOutOfRangeException(), Alaris.Test.Unit.STRK004ATests.CalculatePriority_WithAvoidSignal_ReturnsZero(), Alaris.Test.Unit.STRK004ATests.CalculatePriority_WithHighEdgeRecommendedSignal_ReturnsHighPriority(), and Alaris.Test.Unit.STRK004ATests.CalculatePriority_WithLowEdgeConsiderSignal_ReturnsLowerPriority().
GenerateHistoricalTrades()
static List< Trade > Alaris.Test.Unit.STRK004ATests.GenerateHistoricalTrades (int count) inline static private
Definition at line 283 of file TSUN016A.cs.
Referenced by Alaris.Test.Unit.STRK004ATests.Allocate_WhenCandidateCanDisplace_ReturnsDisplaceExisting(), Alaris.Test.Unit.STRK004ATests.Allocate_WhenCandidateIsHigherPriority_RanksFirst(), Alaris.Test.Unit.STRK004ATests.Allocate_WhenCapacityExhausted_EvaluatesDisplacement(), Alaris.Test.Unit.STRK004ATests.Allocate_WhenQueueEmpty_AcceptsNewOpportunity(), Alaris.Test.Unit.STRK004ATests.Allocate_WithAvoidSignal_RejectsOpportunity(), Alaris.Test.Unit.STRK004ATests.Allocate_WithInvalidPortfolioValue_ThrowsArgumentOutOfRangeException(), Alaris.Test.Unit.STRK004ATests.Allocate_WithNullCandidate_ThrowsArgumentNullException(), Alaris.Test.Unit.STRK004ATests.CalculatePriority_WithAvoidSignal_ReturnsZero(), Alaris.Test.Unit.STRK004ATests.CalculatePriority_WithHighEdgeRecommendedSignal_ReturnsHighPriority(), Alaris.Test.Unit.STRK004ATests.CalculatePriority_WithLowEdgeConsiderSignal_ReturnsLowerPriority(), and Alaris.Test.Unit.STRK004ATests.RebalancePortfolio_WithMisallocatedPositions_ReturnsRecommendations().
RebalancePortfolio_WithMisallocatedPositions_ReturnsRecommendations()
void Alaris.Test.Unit.STRK004ATests.RebalancePortfolio_WithMisallocatedPositions_ReturnsRecommendations () inline
Definition at line 194 of file TSUN016A.cs.
References Alaris.Test.Unit.STRK004ATests._queueAllocator, Alaris.Test.Unit.STRK004ATests.CreateOpenPosition(), Alaris.Test.Unit.STRK004ATests.GenerateHistoricalTrades(), and Alaris.Strategy.Risk.STRK004A.RebalancePortfolio().
Member Data Documentation
_baseKelly
readonly STRK001A Alaris.Test.Unit.STRK004ATests._baseKelly private
Definition at line 16 of file TSUN016A.cs.
Referenced by Alaris.Test.Unit.STRK004ATests.STRK004ATests().
_queueAllocator
readonly STRK004A Alaris.Test.Unit.STRK004ATests._queueAllocator private
Definition at line 17 of file TSUN016A.cs.
Referenced by Alaris.Test.Unit.STRK004ATests.STRK004ATests(), Alaris.Test.Unit.STRK004ATests.Allocate_WhenCandidateCanDisplace_ReturnsDisplaceExisting(), Alaris.Test.Unit.STRK004ATests.Allocate_WhenCandidateIsHigherPriority_RanksFirst(), Alaris.Test.Unit.STRK004ATests.Allocate_WhenCapacityExhausted_EvaluatesDisplacement(), Alaris.Test.Unit.STRK004ATests.Allocate_WhenQueueEmpty_AcceptsNewOpportunity(), Alaris.Test.Unit.STRK004ATests.Allocate_WithAvoidSignal_RejectsOpportunity(), Alaris.Test.Unit.STRK004ATests.Allocate_WithInvalidPortfolioValue_ThrowsArgumentOutOfRangeException(), Alaris.Test.Unit.STRK004ATests.Allocate_WithNullCandidate_ThrowsArgumentNullException(), Alaris.Test.Unit.STRK004ATests.CalculatePriority_WithAvoidSignal_ReturnsZero(), Alaris.Test.Unit.STRK004ATests.CalculatePriority_WithHighEdgeRecommendedSignal_ReturnsHighPriority(), Alaris.Test.Unit.STRK004ATests.CalculatePriority_WithLowEdgeConsiderSignal_ReturnsLowerPriority(), and Alaris.Test.Unit.STRK004ATests.RebalancePortfolio_WithMisallocatedPositions_ReturnsRecommendations().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN016A.cs