Alaris: Alaris.Strategy.Detection.STSD001A Class Reference
Alaris.Strategy.Detection.STSD001A Class Reference sealed
Implements the Neyman-Pearson optimal signal detection framework.
Public Member Functions
STSD001A (ILogger< STSD001A >? logger=null)
Initialises a new instance of the signal detector with default parameters.
void ResetToDefaults ()
Resets distribution parameters to empirical defaults.
void Calibrate (IReadOnlyList< TradeOutcome > outcomes)
Calibrates the detector from historical trade outcomes.
double ComputeOptimalThreshold (double costRatio=2.0)
Computes the optimal threshold for the given cost ratio.
SignalDetectionResult Evaluate (double observedValue, double? threshold=null)
Evaluates a signal observation and returns detection result.
double ComputeLikelihoodRatio (double x)
Computes the likelihood ratio L(H₁)/L(H₀) for an observation.
double ComputePosteriorProbability (double x)
Computes the posterior probability P(H₁|x) using Bayes' theorem.
double ComputeTypeIError (double threshold)
Computes the Type I error rate (false positive rate) for a given threshold.
double ComputeTypeIIError (double threshold)
Computes the Type II error rate (false negative rate) for a given threshold.
double ComputePower (double threshold)
Computes the power (1 - β) of the test for a given threshold.
DistributionParameters GetParameters ()
Gets the current distribution parameters.
Static Public Attributes
const double DefaultMu0 = 1.10
Mean IV/RV ratio for unprofitable trades.
const double DefaultSigma0 = 0.15
Std dev of IV/RV ratio for unprofitable trades.
const double DefaultMu1 = 1.35
Mean IV/RV ratio for profitable trades.
const double DefaultSigma1 = 0.20
Std dev of IV/RV ratio for profitable trades.
const double DefaultPi0 = 0.55
Prior probability of unprofitable trade.
const double DefaultPi1 = 0.45
Prior probability of profitable trade.
const double DefaultCostRatio = 2.0
Default cost ratio (Type I / Type II error costs).
Properties
bool IsCalibrated [get]
Gets whether the detector has been calibrated from historical data.
int CalibrationSampleSize [get]
Gets the calibration sample size.
Private Member Functions
double ComputeThresholdUnequelVariances (double costRatio)
void SafeLog (Action logAction)
Static Private Member Functions
static double ComputeStandardDeviation (List< double > values, double mean)
static double LogNormalPdf (double x, double mu, double sigma)
static double NormalCdf (double z)
Private Attributes
readonly? ILogger< STSD001A > _logger
double _mu0
double _sigma0
double _mu1
double _sigma1
double _pi0
double _pi1
bool _isCalibrated
int _calibrationSampleSize
Static Private Attributes
static readonly Action< ILogger, int, int, Exception?> LogCalibrationComplete
static readonly Action< ILogger, double, double, double, double, Exception?> LogDistributionParameters
static readonly Action< ILogger, double, double, Exception?> LogThresholdComputed
Detailed Description
Implements the Neyman-Pearson optimal signal detection framework.
Definition at line 11 of file STSD001A.cs.
Constructor & Destructor Documentation
STSD001A()
Alaris.Strategy.Detection.STSD001A.STSD001A (ILogger< STSD001A >? logger = null) inline
Initialises a new instance of the signal detector with default parameters.
Definition at line 74 of file STSD001A.cs.
References Alaris.Strategy.Detection.STSD001A._logger, and Alaris.Strategy.Detection.STSD001A.ResetToDefaults().
Member Function Documentation
Calibrate()
void Alaris.Strategy.Detection.STSD001A.Calibrate (IReadOnlyList< TradeOutcome > outcomes) inline
Calibrates the detector from historical trade outcomes.
Parameters
outcomes Historical trade outcomes with IV/RV ratio and profitability.
Exceptions
ArgumentException Thrown when insufficient data for calibration.
Definition at line 110 of file STSD001A.cs.
References Alaris.Strategy.Detection.STSD001A._calibrationSampleSize, Alaris.Strategy.Detection.STSD001A._isCalibrated, Alaris.Strategy.Detection.STSD001A._logger, Alaris.Strategy.Detection.STSD001A._mu0, Alaris.Strategy.Detection.STSD001A._mu1, Alaris.Strategy.Detection.STSD001A._pi0, Alaris.Strategy.Detection.STSD001A._pi1, Alaris.Strategy.Detection.STSD001A._sigma0, Alaris.Strategy.Detection.STSD001A._sigma1, Alaris.Strategy.Detection.STSD001A.ComputeStandardDeviation(), Alaris.Strategy.Detection.STSD001A.LogCalibrationComplete, Alaris.Strategy.Detection.STSD001A.LogDistributionParameters, and Alaris.Strategy.Detection.STSD001A.SafeLog().
ComputeLikelihoodRatio()
double Alaris.Strategy.Detection.STSD001A.ComputeLikelihoodRatio (double x) inline
Computes the likelihood ratio L(H₁)/L(H₀) for an observation.
Definition at line 209 of file STSD001A.cs.
References Alaris.Strategy.Detection.STSD001A._mu0, Alaris.Strategy.Detection.STSD001A._mu1, Alaris.Strategy.Detection.STSD001A._sigma0, Alaris.Strategy.Detection.STSD001A._sigma1, and Alaris.Strategy.Detection.STSD001A.LogNormalPdf().
Referenced by Alaris.Strategy.Detection.STSD001A.Evaluate().
ComputeOptimalThreshold()
double Alaris.Strategy.Detection.STSD001A.ComputeOptimalThreshold (double costRatio = 2::0) inline
Computes the optimal threshold for the given cost ratio.
Parameters
costRatio Ratio of Type I error cost to Type II error cost (c_I / c_II).
Returns
The optimal IV/RV threshold.
Definition at line 150 of file STSD001A.cs.
References Alaris.Strategy.Detection.STSD001A._logger, Alaris.Strategy.Detection.STSD001A._mu0, Alaris.Strategy.Detection.STSD001A._mu1, Alaris.Strategy.Detection.STSD001A._pi0, Alaris.Strategy.Detection.STSD001A._pi1, Alaris.Strategy.Detection.STSD001A._sigma0, Alaris.Strategy.Detection.STSD001A._sigma1, Alaris.Strategy.Detection.STSD001A.ComputeThresholdUnequelVariances(), Alaris.Strategy.Detection.STSD001A.LogThresholdComputed, and Alaris.Strategy.Detection.STSD001A.SafeLog().
Referenced by Alaris.Strategy.Detection.STSD001A.Evaluate(), and Alaris.Test.Unit.SignalDetectionTests.OptimalThreshold_CostRatio2_HigherThanMidpoint().
ComputePosteriorProbability()
double Alaris.Strategy.Detection.STSD001A.ComputePosteriorProbability (double x) inline
Computes the posterior probability P(H₁|x) using Bayes' theorem.
Definition at line 219 of file STSD001A.cs.
References Alaris.Strategy.Detection.STSD001A._mu0, Alaris.Strategy.Detection.STSD001A._mu1, Alaris.Strategy.Detection.STSD001A._pi0, Alaris.Strategy.Detection.STSD001A._pi1, Alaris.Strategy.Detection.STSD001A._sigma0, Alaris.Strategy.Detection.STSD001A._sigma1, and Alaris.Strategy.Detection.STSD001A.LogNormalPdf().
Referenced by Alaris.Strategy.Detection.STSD001A.Evaluate(), and Alaris.Test.Unit.SignalDetectionTests.PosteriorProbability_SumsToOne().
ComputePower()
double Alaris.Strategy.Detection.STSD001A.ComputePower (double threshold) inline
Computes the power (1 - β) of the test for a given threshold.
Definition at line 254 of file STSD001A.cs.
References Alaris.Strategy.Detection.STSD001A.ComputeTypeIIError().
ComputeStandardDeviation()
static double Alaris.Strategy.Detection.STSD001A.ComputeStandardDeviation (List< double > values, double mean) inline static private
Definition at line 316 of file STSD001A.cs.
Referenced by Alaris.Strategy.Detection.STSD001A.Calibrate().
ComputeThresholdUnequelVariances()
double Alaris.Strategy.Detection.STSD001A.ComputeThresholdUnequelVariances (double costRatio) inline private
Definition at line 273 of file STSD001A.cs.
References Alaris.Strategy.Detection.STSD001A._mu0, Alaris.Strategy.Detection.STSD001A._mu1, Alaris.Strategy.Detection.STSD001A._pi0, Alaris.Strategy.Detection.STSD001A._pi1, Alaris.Strategy.Detection.STSD001A._sigma0, and Alaris.Strategy.Detection.STSD001A._sigma1.
Referenced by Alaris.Strategy.Detection.STSD001A.ComputeOptimalThreshold().
ComputeTypeIError()
double Alaris.Strategy.Detection.STSD001A.ComputeTypeIError (double threshold) inline
Computes the Type I error rate (false positive rate) for a given threshold.
Definition at line 234 of file STSD001A.cs.
References Alaris.Strategy.Detection.STSD001A._mu0, Alaris.Strategy.Detection.STSD001A._sigma0, and Alaris.Strategy.Detection.STSD001A.NormalCdf().
Referenced by Alaris.Test.Unit.SignalDetectionTests.TypeIError_IncreasesWithLowerThreshold().
ComputeTypeIIError()
double Alaris.Strategy.Detection.STSD001A.ComputeTypeIIError (double threshold) inline
Computes the Type II error rate (false negative rate) for a given threshold.
Definition at line 244 of file STSD001A.cs.
References Alaris.Strategy.Detection.STSD001A._mu1, Alaris.Strategy.Detection.STSD001A._sigma1, and Alaris.Strategy.Detection.STSD001A.NormalCdf().
Referenced by Alaris.Strategy.Detection.STSD001A.ComputePower().
Evaluate()
SignalDetectionResult Alaris.Strategy.Detection.STSD001A.Evaluate (double observedValue, double? threshold = null) inline
Evaluates a signal observation and returns detection result.
Parameters
observedValue The observed IV/RV ratio.
threshold Optional explicit threshold; uses cost ratio 2.0 if not specified.
Returns
Signal detection result with likelihood ratio and posterior probability.
Definition at line 185 of file STSD001A.cs.
References Alaris.Strategy.Detection.STSD001A.ComputeLikelihoodRatio(), Alaris.Strategy.Detection.STSD001A.ComputeOptimalThreshold(), Alaris.Strategy.Detection.STSD001A.ComputePosteriorProbability(), Alaris.Strategy.Detection.STSD001A.DefaultCostRatio, and Alaris.Strategy.Detection.SignalDetectionResult().
GetParameters()
DistributionParameters Alaris.Strategy.Detection.STSD001A.GetParameters () inline
Gets the current distribution parameters.
Definition at line 262 of file STSD001A.cs.
References Alaris.Strategy.Detection.STSD001A._mu0, Alaris.Strategy.Detection.STSD001A._mu1, Alaris.Strategy.Detection.STSD001A._pi0, Alaris.Strategy.Detection.STSD001A._pi1, Alaris.Strategy.Detection.STSD001A._sigma0, Alaris.Strategy.Detection.STSD001A._sigma1, and Alaris.Strategy.Detection.DistributionParameters().
LogNormalPdf()
static double Alaris.Strategy.Detection.STSD001A.LogNormalPdf (double x, double mu, double sigma) inline static private
Definition at line 322 of file STSD001A.cs.
Referenced by Alaris.Strategy.Detection.STSD001A.ComputeLikelihoodRatio(), and Alaris.Strategy.Detection.STSD001A.ComputePosteriorProbability().
NormalCdf()
static double Alaris.Strategy.Detection.STSD001A.NormalCdf (double z) inline static private
Definition at line 328 of file STSD001A.cs.
Referenced by Alaris.Strategy.Detection.STSD001A.ComputeTypeIError(), and Alaris.Strategy.Detection.STSD001A.ComputeTypeIIError().
ResetToDefaults()
void Alaris.Strategy.Detection.STSD001A.ResetToDefaults () inline
Resets distribution parameters to empirical defaults.
Definition at line 93 of file STSD001A.cs.
References Alaris.Strategy.Detection.STSD001A._calibrationSampleSize, Alaris.Strategy.Detection.STSD001A._isCalibrated, Alaris.Strategy.Detection.STSD001A._mu0, Alaris.Strategy.Detection.STSD001A._mu1, Alaris.Strategy.Detection.STSD001A._pi0, Alaris.Strategy.Detection.STSD001A._pi1, Alaris.Strategy.Detection.STSD001A._sigma0, Alaris.Strategy.Detection.STSD001A._sigma1, Alaris.Strategy.Detection.STSD001A.DefaultMu0, Alaris.Strategy.Detection.STSD001A.DefaultMu1, Alaris.Strategy.Detection.STSD001A.DefaultPi0, Alaris.Strategy.Detection.STSD001A.DefaultPi1, Alaris.Strategy.Detection.STSD001A.DefaultSigma0, and Alaris.Strategy.Detection.STSD001A.DefaultSigma1.
Referenced by Alaris.Strategy.Detection.STSD001A.STSD001A().
SafeLog()
void Alaris.Strategy.Detection.STSD001A.SafeLog (Action logAction) inline private
Definition at line 348 of file STSD001A.cs.
References Alaris.Strategy.Detection.STSD001A._logger.
Referenced by Alaris.Strategy.Detection.STSD001A.Calibrate(), and Alaris.Strategy.Detection.STSD001A.ComputeOptimalThreshold().
Member Data Documentation
_calibrationSampleSize
int Alaris.Strategy.Detection.STSD001A._calibrationSampleSize private
Definition at line 29 of file STSD001A.cs.
Referenced by Alaris.Strategy.Detection.STSD001A.Calibrate(), and Alaris.Strategy.Detection.STSD001A.ResetToDefaults().
_isCalibrated
bool Alaris.Strategy.Detection.STSD001A._isCalibrated private
Definition at line 28 of file STSD001A.cs.
Referenced by Alaris.Strategy.Detection.STSD001A.Calibrate(), and Alaris.Strategy.Detection.STSD001A.ResetToDefaults().
_logger
readonly? ILogger<STSD001A> Alaris.Strategy.Detection.STSD001A._logger private
Definition at line 13 of file STSD001A.cs.
Referenced by Alaris.Strategy.Detection.STSD001A.STSD001A(), Alaris.Strategy.Detection.STSD001A.Calibrate(), Alaris.Strategy.Detection.STSD001A.ComputeOptimalThreshold(), and Alaris.Strategy.Detection.STSD001A.SafeLog().
_mu0
double Alaris.Strategy.Detection.STSD001A._mu0 private
Definition at line 16 of file STSD001A.cs.
Referenced by Alaris.Strategy.Detection.STSD001A.Calibrate(), Alaris.Strategy.Detection.STSD001A.ComputeLikelihoodRatio(), Alaris.Strategy.Detection.STSD001A.ComputeOptimalThreshold(), Alaris.Strategy.Detection.STSD001A.ComputePosteriorProbability(), Alaris.Strategy.Detection.STSD001A.ComputeThresholdUnequelVariances(), Alaris.Strategy.Detection.STSD001A.ComputeTypeIError(), Alaris.Strategy.Detection.STSD001A.GetParameters(), and Alaris.Strategy.Detection.STSD001A.ResetToDefaults().
_mu1
double Alaris.Strategy.Detection.STSD001A._mu1 private
Definition at line 20 of file STSD001A.cs.
Referenced by Alaris.Strategy.Detection.STSD001A.Calibrate(), Alaris.Strategy.Detection.STSD001A.ComputeLikelihoodRatio(), Alaris.Strategy.Detection.STSD001A.ComputeOptimalThreshold(), Alaris.Strategy.Detection.STSD001A.ComputePosteriorProbability(), Alaris.Strategy.Detection.STSD001A.ComputeThresholdUnequelVariances(), Alaris.Strategy.Detection.STSD001A.ComputeTypeIIError(), Alaris.Strategy.Detection.STSD001A.GetParameters(), and Alaris.Strategy.Detection.STSD001A.ResetToDefaults().
_pi0
double Alaris.Strategy.Detection.STSD001A._pi0 private
Definition at line 24 of file STSD001A.cs.
Referenced by Alaris.Strategy.Detection.STSD001A.Calibrate(), Alaris.Strategy.Detection.STSD001A.ComputeOptimalThreshold(), Alaris.Strategy.Detection.STSD001A.ComputePosteriorProbability(), Alaris.Strategy.Detection.STSD001A.ComputeThresholdUnequelVariances(), Alaris.Strategy.Detection.STSD001A.GetParameters(), and Alaris.Strategy.Detection.STSD001A.ResetToDefaults().
_pi1
double Alaris.Strategy.Detection.STSD001A._pi1 private
Definition at line 25 of file STSD001A.cs.
Referenced by Alaris.Strategy.Detection.STSD001A.Calibrate(), Alaris.Strategy.Detection.STSD001A.ComputeOptimalThreshold(), Alaris.Strategy.Detection.STSD001A.ComputePosteriorProbability(), Alaris.Strategy.Detection.STSD001A.ComputeThresholdUnequelVariances(), Alaris.Strategy.Detection.STSD001A.GetParameters(), and Alaris.Strategy.Detection.STSD001A.ResetToDefaults().
_sigma0
double Alaris.Strategy.Detection.STSD001A._sigma0 private
Definition at line 17 of file STSD001A.cs.
Referenced by Alaris.Strategy.Detection.STSD001A.Calibrate(), Alaris.Strategy.Detection.STSD001A.ComputeLikelihoodRatio(), Alaris.Strategy.Detection.STSD001A.ComputeOptimalThreshold(), Alaris.Strategy.Detection.STSD001A.ComputePosteriorProbability(), Alaris.Strategy.Detection.STSD001A.ComputeThresholdUnequelVariances(), Alaris.Strategy.Detection.STSD001A.ComputeTypeIError(), Alaris.Strategy.Detection.STSD001A.GetParameters(), and Alaris.Strategy.Detection.STSD001A.ResetToDefaults().
_sigma1
double Alaris.Strategy.Detection.STSD001A._sigma1 private
Definition at line 21 of file STSD001A.cs.
Referenced by Alaris.Strategy.Detection.STSD001A.Calibrate(), Alaris.Strategy.Detection.STSD001A.ComputeLikelihoodRatio(), Alaris.Strategy.Detection.STSD001A.ComputeOptimalThreshold(), Alaris.Strategy.Detection.STSD001A.ComputePosteriorProbability(), Alaris.Strategy.Detection.STSD001A.ComputeThresholdUnequelVariances(), Alaris.Strategy.Detection.STSD001A.ComputeTypeIIError(), Alaris.Strategy.Detection.STSD001A.GetParameters(), and Alaris.Strategy.Detection.STSD001A.ResetToDefaults().
DefaultCostRatio
const double Alaris.Strategy.Detection.STSD001A.DefaultCostRatio = 2.0 static
Default cost ratio (Type I / Type II error costs).
Definition at line 69 of file STSD001A.cs.
Referenced by Alaris.Strategy.Detection.STSD001A.Evaluate().
DefaultMu0
const double Alaris.Strategy.Detection.STSD001A.DefaultMu0 = 1.10 static
Mean IV/RV ratio for unprofitable trades.
Definition at line 51 of file STSD001A.cs.
Referenced by Alaris.Strategy.Detection.STSD001A.ResetToDefaults().
DefaultMu1
const double Alaris.Strategy.Detection.STSD001A.DefaultMu1 = 1.35 static
Mean IV/RV ratio for profitable trades.
Definition at line 57 of file STSD001A.cs.
Referenced by Alaris.Strategy.Detection.STSD001A.ResetToDefaults().
DefaultPi0
const double Alaris.Strategy.Detection.STSD001A.DefaultPi0 = 0.55 static
Prior probability of unprofitable trade.
Definition at line 63 of file STSD001A.cs.
Referenced by Alaris.Strategy.Detection.STSD001A.ResetToDefaults().
DefaultPi1
const double Alaris.Strategy.Detection.STSD001A.DefaultPi1 = 0.45 static
Prior probability of profitable trade.
Definition at line 66 of file STSD001A.cs.
Referenced by Alaris.Strategy.Detection.STSD001A.ResetToDefaults().
DefaultSigma0
const double Alaris.Strategy.Detection.STSD001A.DefaultSigma0 = 0.15 static
Std dev of IV/RV ratio for unprofitable trades.
Definition at line 54 of file STSD001A.cs.
Referenced by Alaris.Strategy.Detection.STSD001A.ResetToDefaults().
DefaultSigma1
const double Alaris.Strategy.Detection.STSD001A.DefaultSigma1 = 0.20 static
Std dev of IV/RV ratio for profitable trades.
Definition at line 60 of file STSD001A.cs.
Referenced by Alaris.Strategy.Detection.STSD001A.ResetToDefaults().
LogCalibrationComplete
readonly Action<ILogger, int, int, Exception?> Alaris.Strategy.Detection.STSD001A.LogCalibrationComplete static private
Initial value:
=
        LoggerMessage.Define<int, int>(
            LogLevel.Information,
            new EventId(1, nameof(LogCalibrationComplete)),
            "Signal detection calibration complete: {ProfitableCount} profitable, {UnprofitableCount} unprofitable trades")
Definition at line 32 of file STSD001A.cs.
Referenced by Alaris.Strategy.Detection.STSD001A.Calibrate().
LogDistributionParameters
readonly Action<ILogger, double, double, double, double, Exception?> Alaris.Strategy.Detection.STSD001A.LogDistributionParameters static private
Initial value:
=
        LoggerMessage.Define<double, double, double, double>(
            LogLevel.Debug,
            new EventId(2, nameof(LogDistributionParameters)),
            "Distribution parameters: H₀(μ={Mu0:F4}, σ={Sigma0:F4}), H₁(μ={Mu1:F4}, σ={Sigma1:F4})")
Definition at line 38 of file STSD001A.cs.
Referenced by Alaris.Strategy.Detection.STSD001A.Calibrate().
LogThresholdComputed
readonly Action<ILogger, double, double, Exception?> Alaris.Strategy.Detection.STSD001A.LogThresholdComputed static private
Initial value:
=
        LoggerMessage.Define<double, double>(
            LogLevel.Information,
            new EventId(3, nameof(LogThresholdComputed)),
            "Optimal threshold computed: {Threshold:F4} (cost ratio={CostRatio:F2})")
Definition at line 44 of file STSD001A.cs.
Referenced by Alaris.Strategy.Detection.STSD001A.ComputeOptimalThreshold().
Property Documentation
CalibrationSampleSize
int Alaris.Strategy.Detection.STSD001A.CalibrationSampleSize get
Gets the calibration sample size.
Definition at line 88 of file STSD001A.cs.
IsCalibrated
bool Alaris.Strategy.Detection.STSD001A.IsCalibrated get
Gets whether the detector has been calibrated from historical data.
Definition at line 83 of file STSD001A.cs.
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Detection/STSD001A.cs