Alaris: Alaris.Strategy.Core.Numerical.STPR002B Class Reference
Alaris.Strategy.Core.Numerical.STPR002B Class Reference
AVX2-accelerated Gauss-Legendre integration for characteristic function pricing. Component ID: STPR002B.
Static Public Member Functions
static double Integrate (Func< double, double > f, double a, double b)
Integrates a real function over [a, b] using batch-vectorized Gauss-Legendre.
static double double Error IntegrateToInfinity (Func< double, double > f, double a, double absoluteTolerance=1e-8)
static Complex double Error IntegrateComplexToInfinity (Func< double, Complex > f, double a, double absoluteTolerance=1e-8)
Static Public Attributes
static double Value
Integrates from a to infinity using chunked Gauss-Legendre with adaptive step sizing.
static Complex Value
Integrates a complex function from a to infinity.
Properties
static bool IsAvx2Supported [get]
Indicates if AVX2 acceleration is available.
Static Private Member Functions
static double[] GenerateGLNodes32 ()
static double[] GenerateGLWeights32 ()
Static Private Attributes
static readonly double[] GLNodes32 = GenerateGLNodes32()
static readonly double[] GLWeights32 = GenerateGLWeights32()
const double IntegrationStepSize = 50.0
const int MaxChunks = 200
Detailed Description
AVX2-accelerated Gauss-Legendre integration for characteristic function pricing. Component ID: STPR002B.
Provides batch-vectorized numerical integration optimized for:
Heston characteristic function integration
Kou jump-diffusion pricing
General semi-infinite integrals with exponential decay
Uses 32-point Gauss-Legendre quadrature with batch evaluation of 4 points at a time. For smooth characteristic functions, this provides ~3x speedup over scalar integration.
Definition at line 31 of file STPR002B.cs.
Member Function Documentation
GenerateGLNodes32()
static double[] Alaris.Strategy.Core.Numerical.STPR002B.GenerateGLNodes32 () inline static private
Definition at line 206 of file STPR002B.cs.
GenerateGLWeights32()
static double[] Alaris.Strategy.Core.Numerical.STPR002B.GenerateGLWeights32 () inline static private
Definition at line 221 of file STPR002B.cs.
Integrate()
static double Alaris.Strategy.Core.Numerical.STPR002B.Integrate (Func< double, double > f, double a, double b) inline static
Integrates a real function over [a, b] using batch-vectorized Gauss-Legendre.
Parameters
f Function to integrate.
a Lower bound.
b Upper bound.
Returns
Approximate integral value.
Definition at line 53 of file STPR002B.cs.
References Alaris.Strategy.Core.Numerical.STPR002B.GLNodes32, and Alaris.Strategy.Core.Numerical.STPR002B.GLWeights32.
Referenced by Alaris.Strategy.Core.Numerical.STPR002C.Integrate(), Alaris.Strategy.Core.Numerical.STPR002B.IntegrateComplexToInfinity(), and Alaris.Strategy.Core.Numerical.STPR002B.IntegrateToInfinity().
IntegrateComplexToInfinity()
static Complex double Error Alaris.Strategy.Core.Numerical.STPR002B.IntegrateComplexToInfinity (Func< double, Complex > f, double a, double absoluteTolerance = 1e-8) inline static
Definition at line 158 of file STPR002B.cs.
References Alaris.Strategy.Core.Numerical.STPR002B.Integrate(), Alaris.Strategy.Core.Numerical.STPR002B.IntegrationStepSize, and Alaris.Strategy.Core.Numerical.STPR002B.MaxChunks.
Referenced by Alaris.Strategy.Core.Numerical.STPR002C.IntegrateComplexToInfinity().
IntegrateToInfinity()
static double double Error Alaris.Strategy.Core.Numerical.STPR002B.IntegrateToInfinity (Func< double, double > f, double a, double absoluteTolerance = 1e-8) inline static
Definition at line 116 of file STPR002B.cs.
References Alaris.Strategy.Core.Numerical.STPR002B.Integrate(), Alaris.Strategy.Core.Numerical.STPR002B.IntegrationStepSize, and Alaris.Strategy.Core.Numerical.STPR002B.MaxChunks.
Referenced by Alaris.Strategy.Core.Numerical.STPR002C.IntegrateToInfinity().
Member Data Documentation
GLNodes32
readonly double [] Alaris.Strategy.Core.Numerical.STPR002B.GLNodes32 = GenerateGLNodes32() static private
Definition at line 34 of file STPR002B.cs.
Referenced by Alaris.Strategy.Core.Numerical.STPR002B.Integrate().
GLWeights32
readonly double [] Alaris.Strategy.Core.Numerical.STPR002B.GLWeights32 = GenerateGLWeights32() static private
Definition at line 35 of file STPR002B.cs.
Referenced by Alaris.Strategy.Core.Numerical.STPR002B.Integrate().
IntegrationStepSize
const double Alaris.Strategy.Core.Numerical.STPR002B.IntegrationStepSize = 50.0 static private
Definition at line 37 of file STPR002B.cs.
Referenced by Alaris.Strategy.Core.Numerical.STPR002B.IntegrateComplexToInfinity(), and Alaris.Strategy.Core.Numerical.STPR002B.IntegrateToInfinity().
MaxChunks
const int Alaris.Strategy.Core.Numerical.STPR002B.MaxChunks = 200 static private
Definition at line 38 of file STPR002B.cs.
Referenced by Alaris.Strategy.Core.Numerical.STPR002B.IntegrateComplexToInfinity(), and Alaris.Strategy.Core.Numerical.STPR002B.IntegrateToInfinity().
Value [1/2]
double Alaris.Strategy.Core.Numerical.STPR002B.Value static
Integrates from a to infinity using chunked Gauss-Legendre with adaptive step sizing.
Definition at line 116 of file STPR002B.cs.
Value [2/2]
Complex Alaris.Strategy.Core.Numerical.STPR002B.Value static
Integrates a complex function from a to infinity.
Definition at line 158 of file STPR002B.cs.
Property Documentation
IsAvx2Supported
bool Alaris.Strategy.Core.Numerical.STPR002B.IsAvx2Supported static get
Indicates if AVX2 acceleration is available.
Definition at line 43 of file STPR002B.cs.
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Core/Numerical/STPR002B.cs