Alaris: Alaris.Strategy.Core.STTM002A Class Reference
Alaris.Strategy.Core.STTM002A Class Reference sealed
Handles regime detection and switching around earnings announcements. Determines appropriate model behavior based on proximity to earnings.
Public Member Functions
double ComputeAdjustedIV (double baseIV, double earningsIV)
Computes regime-adjusted implied volatility.
Static Public Member Functions
static STTM002A Detect (STTM004A timeParams)
Detects the current earnings regime from time parameters.
Static Public Attributes
const int TransitionDays = 5
Days after earnings for transition period.
const int MaxPreEarningsDays = 60
Maximum days before earnings to consider pre-EA regime.
Properties
STTM002AType RegimeType [get]
Current regime type.
STTM004A TimeParams [get]
Time parameters for this regime.
int? DaysSinceEarnings [get]
Days since earnings (negative if before, positive if after).
double TransitionWeight [get]
Blending weight for transition period [0, 1]. 0 = full post-EA crush, 1 = normalized volatility.
RecommendedModel ModelRecommendation [get]
Recommended model type for this regime.
Private Member Functions
STTM002A (STTM002AType regimeType, STTM004A timeParams, int? daysSinceEarnings, double transitionWeight, RecommendedModel modelRecommendation)
double BlendIV (double baseIV, double earningsIV)
Blends IV during transition period. Immediately after EA: IV drops sharply (crush). Over transition period: IV normalizes to base level.
Detailed Description
Handles regime detection and switching around earnings announcements. Determines appropriate model behavior based on proximity to earnings.
Definition at line 41 of file STTM002A.cs.
Constructor & Destructor Documentation
STTM002A()
Alaris.Strategy.Core.STTM002A.STTM002A (STTM002AType regimeType, STTM004A timeParams, int? daysSinceEarnings, double transitionWeight, RecommendedModel modelRecommendation) inline private
Definition at line 79 of file STTM002A.cs.
References Alaris.Strategy.Core.STTM002A.DaysSinceEarnings, Alaris.Strategy.Core.STTM002A.ModelRecommendation, Alaris.Strategy.Core.STTM002A.RegimeType, Alaris.Strategy.Core.STTM002A.TimeParams, and Alaris.Strategy.Core.STTM002A.TransitionWeight.
Member Function Documentation
BlendIV()
double Alaris.Strategy.Core.STTM002A.BlendIV (double baseIV, double earningsIV) inline private
Blends IV during transition period. Immediately after EA: IV drops sharply (crush). Over transition period: IV normalizes to base level.
Definition at line 184 of file STTM002A.cs.
References Alaris.Strategy.Core.STTM002A.TransitionWeight.
Referenced by Alaris.Strategy.Core.STTM002A.ComputeAdjustedIV().
ComputeAdjustedIV()
double Alaris.Strategy.Core.STTM002A.ComputeAdjustedIV (double baseIV, double earningsIV) inline
Computes regime-adjusted implied volatility.
Parameters
baseIV Base IV from continuous model (Heston/BSM).
earningsIV IV with earnings component (L&S).
Returns
Regime-adjusted IV.
Definition at line 167 of file STTM002A.cs.
References Alaris.Strategy.Core.STTM002A.BlendIV(), and Alaris.Strategy.Core.STTM002A.RegimeType.
Referenced by Alaris.Strategy.Core.LeungSantoliExtensions.ComputePostEarningsIV().
Detect()
static STTM002A Alaris.Strategy.Core.STTM002A.Detect (STTM004A timeParams) inline static
Detects the current earnings regime from time parameters.
Definition at line 96 of file STTM002A.cs.
References Alaris.Strategy.Core.STTM004A.EarningsDate, Alaris.Strategy.Core.STTM004A.HasEarningsBeforeExpiry, Alaris.Strategy.Core.STTM004A.IsPreEarnings, Alaris.Strategy.Core.STTM002A.MaxPreEarningsDays, and Alaris.Strategy.Core.STTM002A.TransitionDays.
Referenced by Alaris.Strategy.Core.STIV003A.SelectBestModel(), Alaris.Test.Unit.IVModelTests.STTM002A_ComputeAdjustedIV_NoEarnings_ReturnsBaseIV(), Alaris.Test.Unit.IVModelTests.STTM002A_ComputeAdjustedIV_PreEarnings_ReturnsEarningsIV(), Alaris.Test.Unit.IVModelTests.STTM002A_Detect_NoEarnings_ReturnsNoSTTM002A(), and Alaris.Test.Unit.IVModelTests.STTM002A_Detect_PreEarnings_ReturnsPreSTTM002A().
Member Data Documentation
MaxPreEarningsDays
const int Alaris.Strategy.Core.STTM002A.MaxPreEarningsDays = 60 static
Maximum days before earnings to consider pre-EA regime.
Definition at line 51 of file STTM002A.cs.
Referenced by Alaris.Strategy.Core.STTM002A.Detect().
TransitionDays
const int Alaris.Strategy.Core.STTM002A.TransitionDays = 5 static
Days after earnings for transition period.
Definition at line 46 of file STTM002A.cs.
Referenced by Alaris.Strategy.Core.STTM002A.Detect().
Property Documentation
DaysSinceEarnings
int? Alaris.Strategy.Core.STTM002A.DaysSinceEarnings get
Days since earnings (negative if before, positive if after).
Definition at line 66 of file STTM002A.cs.
Referenced by Alaris.Strategy.Core.STTM002A.STTM002A().
ModelRecommendation
RecommendedModel Alaris.Strategy.Core.STTM002A.ModelRecommendation get
Recommended model type for this regime.
Definition at line 77 of file STTM002A.cs.
Referenced by Alaris.Strategy.Core.STTM002A.STTM002A().
RegimeType
STTM002AType Alaris.Strategy.Core.STTM002A.RegimeType get
Current regime type.
Definition at line 56 of file STTM002A.cs.
Referenced by Alaris.Strategy.Core.STTM002A.STTM002A(), Alaris.Strategy.Core.STTM002A.ComputeAdjustedIV(), Alaris.Strategy.Core.LeungSantoliExtensions.ComputePreEarningsIV(), Alaris.Test.Unit.IVModelTests.STTM002A_Detect_NoEarnings_ReturnsNoSTTM002A(), and Alaris.Test.Unit.IVModelTests.STTM002A_Detect_PreEarnings_ReturnsPreSTTM002A().
TimeParams
STTM004A Alaris.Strategy.Core.STTM002A.TimeParams get
Time parameters for this regime.
Definition at line 61 of file STTM002A.cs.
Referenced by Alaris.Strategy.Core.STTM002A.STTM002A(), and Alaris.Strategy.Core.LeungSantoliExtensions.ComputePreEarningsIV().
TransitionWeight
double Alaris.Strategy.Core.STTM002A.TransitionWeight get
Blending weight for transition period [0, 1]. 0 = full post-EA crush, 1 = normalized volatility.
Definition at line 72 of file STTM002A.cs.
Referenced by Alaris.Strategy.Core.STTM002A.STTM002A(), and Alaris.Strategy.Core.STTM002A.BlendIV().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Core/STTM002A.cs