Alaris: Alaris.Infrastructure.Data.Provider.DTpr003A Interface Reference
Alaris.Infrastructure.Data.Provider.DTpr003A Interface Reference
Interface for market data providers (Polygon, IBKR, etc.).
Public Member Functions
Task< IReadOnlyList< PriceBar > > GetHistoricalBarsAsync (string symbol, DateTime startDate, DateTime endDate, CancellationToken cancellationToken=default)
Gets historical OHLCV bars for a symbol.
Task< OptionChainSnapshot > GetOptionChainAsync (string symbol, DateTime? asOfDate=null, CancellationToken cancellationToken=default)
Gets the current options chain for a symbol.
Task< decimal > GetSpotPriceAsync (string symbol, CancellationToken cancellationToken=default)
Gets the current spot price for a symbol.
Task< decimal > GetAverageVolume30DayAsync (string symbol, DateTime? evaluationDate=null, CancellationToken cancellationToken=default)
Gets 30-day average volume for a symbol.
Detailed Description
Interface for market data providers (Polygon, IBKR, etc.).
Component ID: DTpr003A
Implementations provide historical OHLCV bars, options chains, spot prices, and volume data from various market data vendors.
Definition at line 23 of file DTpr003A.cs.
Member Function Documentation
GetAverageVolume30DayAsync()
Task< decimal > Alaris.Infrastructure.Data.Provider.DTpr003A.GetAverageVolume30DayAsync (string symbol, DateTime? evaluationDate = null, CancellationToken cancellationToken = default)
Gets 30-day average volume for a symbol.
Parameters
symbol The symbol to query.
evaluationDate Optional evaluation date (use LEAN's Time for backtests, null for live trading).
cancellationToken Cancellation token.
Implemented in Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.
Referenced by Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetMarketDataSnapshotAsync(), and Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.MeetsBasicCriteriaAsync().
GetHistoricalBarsAsync()
Task< IReadOnlyList< PriceBar > > Alaris.Infrastructure.Data.Provider.DTpr003A.GetHistoricalBarsAsync (string symbol, DateTime startDate, DateTime endDate, CancellationToken cancellationToken = default)
Gets historical OHLCV bars for a symbol.
Implemented in Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.
Referenced by Alaris.Test.Unit.TSUN029A.DTpr003A_GetHistoricalBarsAsync_ReturnsBars(), and Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetHistoricalBarsForRvCalculationAsync().
GetOptionChainAsync()
Task< OptionChainSnapshot > Alaris.Infrastructure.Data.Provider.DTpr003A.GetOptionChainAsync (string symbol, DateTime? asOfDate = null, CancellationToken cancellationToken = default)
Gets the current options chain for a symbol.
Implemented in Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.
Referenced by Alaris.Test.Unit.TSUN029A.DTpr003A_GetOptionChainAsync_ReturnsChain(), and Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetOptionChainWithCacheFallbackAsync().
GetSpotPriceAsync()
Task< decimal > Alaris.Infrastructure.Data.Provider.DTpr003A.GetSpotPriceAsync (string symbol, CancellationToken cancellationToken = default)
Gets the current spot price for a symbol.
Implemented in Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.
Referenced by Alaris.Test.Unit.TSUN029A.DTpr003A_GetSpotPriceAsync_RespectsCancel(), Alaris.Test.Unit.TSUN029A.DTpr003A_GetSpotPriceAsync_ReturnsValidPrice(), and Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetMarketDataSnapshotAsync().
The documentation for this interface was generated from the following file:
src/Alaris.Infrastructure/Data/Provider/DTpr003A.cs