Alaris: Alaris.Core.Time.CRTM005A Struct Reference
Alaris.Core.Time.CRTM005A Struct Reference
High-performance date type with serial number representation. Matches QuantLib Date semantics for binary compatibility.
Public Member Functions
CRTM005A (int serialNumber)
Initialises a new date from a serial number.
CRTM005A (int day, int month, int year)
Initialises a new date from day, month, year components.
CRTM005A (int day, CRTM005AMonth month, int year)
Initialises a new date from day, month enum, year components. Provides compatibility with QuantLib Month enum pattern.
DateTime ToDateTime ()
Converts this date to a .NET DateTime (UTC midnight).
CRTM005A AddDays (int days)
Adds the specified number of days to this date.
CRTM005A AddMonths (int months)
Adds the specified number of months to this date. Preserves day-of-month, capping at end-of-month if necessary.
CRTM005A AddYears (int years)
Adds the specified number of years to this date.
bool Equals (CRTM005A other)
override bool Equals (object? obj)
override int GetHashCode ()
int CompareTo (CRTM005A other)
override string ToString ()
string ToIsoString ()
Returns an ISO 8601 formatted string.
Static Public Member Functions
static CRTM005A FromDateTime (DateTime dateTime)
Creates an Alaris date from a .NET DateTime.
static int operator- (CRTM005A left, CRTM005A right)
Calculates the number of days between two dates.
static CRTM005A operator+ (CRTM005A date, CRTM006A period)
Adds a period to a date.
static CRTM005A Add (CRTM005A date, CRTM006A period)
Adds a period to a date (friendly alternate for + operator).
static int Subtract (CRTM005A left, CRTM005A right)
Calculates the difference between two dates in days (friendly alternate for - operator).
static bool operator== (CRTM005A left, CRTM005A right)
Compares two dates for equality.
static bool operator!= (CRTM005A left, CRTM005A right)
Compares two dates for inequality.
static bool operator< (CRTM005A left, CRTM005A right)
Determines if the left date is before the right date.
static bool operator<= (CRTM005A left, CRTM005A right)
Determines if the left date is before or equal to the right date.
static bool operator> (CRTM005A left, CRTM005A right)
Determines if the left date is after the right date.
static bool operator>= (CRTM005A left, CRTM005A right)
Determines if the left date is after or equal to the right date.
Properties
int SerialNumber [get]
Gets the serial number (days since December 31, 1899).
int Day [get]
Gets the day of the month (1-31).
int Month [get]
Gets the month (1-12).
int Year [get]
Gets the year.
DayOfWeek DayOfWeek [get]
Gets the day of the week.
int DayOfYear [get]
Gets the day of the year (1-366).
Static Private Attributes
static readonly DateTime Epoch = new(1899, 12, 31, 0, 0, 0, DateTimeKind.Utc)
Detailed Description
High-performance date type with serial number representation. Matches QuantLib Date semantics for binary compatibility.
This struct replaces QuantLib.Date with a native implementation that:
Uses the same serial number epoch (Dec 31, 1899 = 0)
Provides identical date arithmetic behaviour
Is a value type for zero-allocation operations
Definition at line 29 of file CRTM005A.cs.
Constructor & Destructor Documentation
CRTM005A() [1/3]
Alaris.Core.Time.CRTM005A.CRTM005A (int serialNumber) inline
Initialises a new date from a serial number.
Parameters
serialNumber Days since December 31, 1899.
Definition at line 69 of file CRTM005A.cs.
References Alaris.Core.Time.CRTM005A.SerialNumber.
CRTM005A() [2/3]
Alaris.Core.Time.CRTM005A.CRTM005A (int day, int month, int year) inline
Initialises a new date from day, month, year components.
Parameters
day Day of the month (1-31).
month Month (1-12).
year Year.
Definition at line 80 of file CRTM005A.cs.
References Alaris.Core.Time.CRTM005A.Epoch, and Alaris.Core.Time.CRTM005A.SerialNumber.
CRTM005A() [3/3]
Alaris.Core.Time.CRTM005A.CRTM005A (int day, CRTM005AMonth month, int year) inline
Initialises a new date from day, month enum, year components. Provides compatibility with QuantLib Month enum pattern.
Parameters
day Day of the month (1-31).
month Month enum value.
year Year.
Definition at line 93 of file CRTM005A.cs.
Member Function Documentation
Add()
static CRTM005A Alaris.Core.Time.CRTM005A.Add (CRTM005A date, CRTM006A period) inline static
Adds a period to a date (friendly alternate for + operator).
Parameters
date The base date.
period The period to add.
Returns
A new date offset by the period.
Definition at line 208 of file CRTM005A.cs.
References Alaris.Core.Time.CRTM005A.AddDays(), Alaris.Core.Time.CRTM005A.AddMonths(), Alaris.Core.Time.CRTM005A.AddYears(), and Alaris.Core.Time.CRTM006A.Length.
Referenced by Alaris.Core.Time.CRTM005A.operator+().
AddDays()
CRTM005A Alaris.Core.Time.CRTM005A.AddDays (int days) inline
Adds the specified number of days to this date.
Parameters
days Number of days to add (can be negative).
Returns
A new date offset by the specified days.
Definition at line 123 of file CRTM005A.cs.
References Alaris.Core.Time.CRTM005A.SerialNumber.
Referenced by Alaris.Core.Time.CRTM005A.Add(), Alaris.Test.Unit.Core.Time.CRTM005ATests.AddDays_30Days_ReturnsCorrectDate(), Alaris.Test.Unit.Core.Time.CRTM005ATests.AddDays_CrossingYearBoundary_Works(), Alaris.Test.Unit.Core.Time.CRTM005ATests.AddDays_Negative_SubtractsDays(), Alaris.Test.Unit.STBR001ATests.CreateHealyCallParameters(), Alaris.Test.Unit.STBR001ATests.CreateHealyPutParameters(), Alaris.Test.Unit.STBR001ATests.CreateStandardCallParameters(), Alaris.Test.Unit.STBR001ATests.CreateStandardPutParameters(), and Alaris.Test.Unit.STBR001ATests.CreateSTPR001AParameters().
AddMonths()
CRTM005A Alaris.Core.Time.CRTM005A.AddMonths (int months) inline
Adds the specified number of months to this date. Preserves day-of-month, capping at end-of-month if necessary.
Parameters
months Number of months to add (can be negative).
Returns
A new date offset by the specified months.
Definition at line 134 of file CRTM005A.cs.
References Alaris.Core.Time.CRTM005A.ToDateTime().
Referenced by Alaris.Core.Time.CRTM005A.Add().
AddYears()
CRTM005A Alaris.Core.Time.CRTM005A.AddYears (int years) inline
Adds the specified number of years to this date.
Parameters
years Number of years to add (can be negative).
Returns
A new date offset by the specified years.
Definition at line 167 of file CRTM005A.cs.
References Alaris.Core.Time.CRTM005A.ToDateTime().
Referenced by Alaris.Core.Time.CRTM005A.Add().
CompareTo()
int Alaris.Core.Time.CRTM005A.CompareTo (CRTM005A other) inline
Definition at line 298 of file CRTM005A.cs.
References Alaris.Core.Time.CRTM005A.SerialNumber.
Equals() [1/2]
bool Alaris.Core.Time.CRTM005A.Equals (CRTM005A other) inline
Definition at line 280 of file CRTM005A.cs.
References Alaris.Core.Time.CRTM005A.SerialNumber.
Referenced by Alaris.Core.Time.CRTM005A.Equals().
Equals() [2/2]
override bool Alaris.Core.Time.CRTM005A.Equals (object? obj) inline
Definition at line 286 of file CRTM005A.cs.
References Alaris.Core.Time.CRTM005A.Equals().
FromDateTime()
static CRTM005A Alaris.Core.Time.CRTM005A.FromDateTime (DateTime dateTime) inline static
Creates an Alaris date from a .NET DateTime.
Parameters
dateTime The DateTime to convert.
Returns
The corresponding Alaris date.
Definition at line 103 of file CRTM005A.cs.
References Alaris.Core.Time.CRTM005A.Epoch.
Referenced by Alaris.Algorithm.STLN001A.BuildPricingParameters(), Alaris.Strategy.STCT001A.CreateSpreadParameters(), Alaris.Test.Unit.Core.Time.CRTM005ATests.FromDateTime_RoundTrips(), and Alaris.Algorithm.STLN001A.TryResolveImpliedVolatility().
GetHashCode()
override int Alaris.Core.Time.CRTM005A.GetHashCode () inline
Definition at line 292 of file CRTM005A.cs.
References Alaris.Core.Time.CRTM005A.SerialNumber.
operator!=()
static bool Alaris.Core.Time.CRTM005A.operator!= (CRTM005A left, CRTM005A right) inline static
Compares two dates for inequality.
Definition at line 242 of file CRTM005A.cs.
References Alaris.Core.Time.CRTM005A.SerialNumber.
operator+()
static CRTM005A Alaris.Core.Time.CRTM005A.operator+ (CRTM005A date, CRTM006A period) inline static
Adds a period to a date.
Definition at line 197 of file CRTM005A.cs.
References Alaris.Core.Time.CRTM005A.Add().
operator-()
static int Alaris.Core.Time.CRTM005A.operator- (CRTM005A left, CRTM005A right) inline static
Calculates the number of days between two dates.
Parameters
left Start date.
right End date.
Returns
Number of days (left - right).
Definition at line 188 of file CRTM005A.cs.
References Alaris.Core.Time.CRTM005A.SerialNumber.
operator<()
static bool Alaris.Core.Time.CRTM005A.operator< (CRTM005A left, CRTM005A right) inline static
Determines if the left date is before the right date.
Definition at line 250 of file CRTM005A.cs.
References Alaris.Core.Time.CRTM005A.SerialNumber.
operator<=()
static bool Alaris.Core.Time.CRTM005A.operator<= (CRTM005A left, CRTM005A right) inline static
Determines if the left date is before or equal to the right date.
Definition at line 258 of file CRTM005A.cs.
References Alaris.Core.Time.CRTM005A.SerialNumber.
operator==()
static bool Alaris.Core.Time.CRTM005A.operator== (CRTM005A left, CRTM005A right) inline static
Compares two dates for equality.
Definition at line 234 of file CRTM005A.cs.
References Alaris.Core.Time.CRTM005A.SerialNumber.
operator>()
static bool Alaris.Core.Time.CRTM005A.operator> (CRTM005A left, CRTM005A right) inline static
Determines if the left date is after the right date.
Definition at line 266 of file CRTM005A.cs.
References Alaris.Core.Time.CRTM005A.SerialNumber.
operator>=()
static bool Alaris.Core.Time.CRTM005A.operator>= (CRTM005A left, CRTM005A right) inline static
Determines if the left date is after or equal to the right date.
Definition at line 274 of file CRTM005A.cs.
References Alaris.Core.Time.CRTM005A.SerialNumber.
Subtract()
static int Alaris.Core.Time.CRTM005A.Subtract (CRTM005A left, CRTM005A right) inline static
Calculates the difference between two dates in days (friendly alternate for - operator).
Parameters
left The first date.
right The second date.
Returns
Number of days (left - right).
Definition at line 226 of file CRTM005A.cs.
References Alaris.Core.Time.CRTM005A.SerialNumber.
ToDateTime()
DateTime Alaris.Core.Time.CRTM005A.ToDateTime () inline
Converts this date to a .NET DateTime (UTC midnight).
Returns
DateTime representation.
Definition at line 113 of file CRTM005A.cs.
References Alaris.Core.Time.CRTM005A.Epoch, and Alaris.Core.Time.CRTM005A.SerialNumber.
Referenced by Alaris.Core.Time.CRTM005A.AddMonths(), Alaris.Core.Time.CRTM005A.AddYears(), Alaris.Test.Unit.Core.Time.CRTM005ATests.FromDateTime_RoundTrips(), and Alaris.Core.Time.CRTM005A.ToString().
ToIsoString()
string Alaris.Core.Time.CRTM005A.ToIsoString () inline
Returns an ISO 8601 formatted string.
Definition at line 313 of file CRTM005A.cs.
References Alaris.Core.Time.CRTM005A.ToString().
ToString()
override string Alaris.Core.Time.CRTM005A.ToString () inline
Definition at line 304 of file CRTM005A.cs.
References Alaris.Core.Time.CRTM005A.ToDateTime().
Referenced by Alaris.Core.Time.CRTM005A.ToIsoString().
Member Data Documentation
Epoch
readonly DateTime Alaris.Core.Time.CRTM005A.Epoch = new(1899, 12, 31, 0, 0, 0, DateTimeKind.Utc) static private
Definition at line 33 of file CRTM005A.cs.
Referenced by Alaris.Core.Time.CRTM005A.CRTM005A(), Alaris.Core.Time.CRTM005A.FromDateTime(), and Alaris.Core.Time.CRTM005A.ToDateTime().
Property Documentation
Day
int Alaris.Core.Time.CRTM005A.Day get
Gets the day of the month (1-31).
Definition at line 43 of file CRTM005A.cs.
Referenced by Alaris.Test.Unit.Core.Time.CRTM005ATests.AddDays_30Days_ReturnsCorrectDate(), and Alaris.Core.Time.CRTM007AThirty360.DayCount().
DayOfWeek
DayOfWeek Alaris.Core.Time.CRTM005A.DayOfWeek get
Gets the day of the week.
Definition at line 58 of file CRTM005A.cs.
DayOfYear
int Alaris.Core.Time.CRTM005A.DayOfYear get
Gets the day of the year (1-366).
Definition at line 63 of file CRTM005A.cs.
Month
int Alaris.Core.Time.CRTM005A.Month get
Gets the month (1-12).
Definition at line 48 of file CRTM005A.cs.
Referenced by Alaris.Test.Unit.Core.Time.CRTM005ATests.AddDays_30Days_ReturnsCorrectDate(), Alaris.Test.Unit.Core.Time.CRTM005ATests.AddDays_CrossingYearBoundary_Works(), Alaris.Test.Unit.Core.Time.CRTM005ATests.AddDays_Negative_SubtractsDays(), and Alaris.Core.Time.CRTM007AThirty360.DayCount().
SerialNumber
int Alaris.Core.Time.CRTM005A.SerialNumber get
Gets the serial number (days since December 31, 1899).
Definition at line 38 of file CRTM005A.cs.
Referenced by Alaris.Core.Time.CRTM005A.CRTM005A(), Alaris.Core.Time.CRTM005A.CRTM005A(), Alaris.Core.Time.CRTM005A.AddDays(), Alaris.Core.Options.AmericanExercise.CanExercise(), Alaris.Core.Time.CRTM005A.CompareTo(), Alaris.Core.Time.CRTM005A.Equals(), Alaris.Core.Time.CRTM005A.GetHashCode(), Alaris.Core.Time.CRTM005A.operator!=(), Alaris.Core.Time.CRTM005A.operator-(), Alaris.Core.Time.CRTM005A.operator<(), Alaris.Core.Time.CRTM005A.operator<=(), Alaris.Core.Time.CRTM005A.operator==(), Alaris.Core.Time.CRTM005A.operator>(), Alaris.Core.Time.CRTM005A.operator>=(), Alaris.Core.Time.CRTM005A.Subtract(), Alaris.Core.Time.CRTM005A.ToDateTime(), Alaris.Core.Options.AmericanExercise.ToString(), Alaris.Strategy.Bridge.STPR001AParameters.Validate(), and Alaris.Strategy.Model.STDT003A.Validate().
Year
int Alaris.Core.Time.CRTM005A.Year get
Gets the year.
Definition at line 53 of file CRTM005A.cs.
Referenced by Alaris.Test.Unit.Core.Time.CRTM005ATests.AddDays_CrossingYearBoundary_Works(), and Alaris.Core.Time.CRTM007AThirty360.DayCount().
The documentation for this struct was generated from the following file:
src/Alaris.Core/Time/CRTM005A.cs