Alaris: Alaris.Infrastructure.Data.Provider.DTpr004A Interface Reference
Alaris.Infrastructure.Data.Provider.DTpr004A Interface Reference
Interface for earnings calendar providers.
Public Member Functions
Task< IReadOnlyList< EarningsEvent > > GetUpcomingEarningsAsync (string symbol, int daysAhead=90, CancellationToken cancellationToken=default)
Gets upcoming earnings events for a symbol.
Task< IReadOnlyList< EarningsEvent > > GetHistoricalEarningsAsync (string symbol, int lookbackDays=730, CancellationToken cancellationToken=default)
Gets historical earnings events for a symbol.
Task< IReadOnlyList< EarningsEvent > > GetHistoricalEarningsAsync (string symbol, DateTime anchorDate, int lookbackDays=730, CancellationToken cancellationToken=default)
Gets historical earnings events for a symbol, anchored to a specific date. Use in backtest mode with simulation date as anchor.
Task< IReadOnlyList< string > > GetSymbolsWithEarningsAsync (DateTime startDate, DateTime endDate, CancellationToken cancellationToken=default)
Gets all symbols with earnings in date range.
void EnableCacheOnlyMode ()
Enables cache-only mode (disables API calls). Call for backtests.
Detailed Description
Interface for earnings calendar providers.
Component ID: DTpr004A
Implementations provide upcoming and historical earnings events, including announcement dates, EPS estimates, and fiscal period data.
Definition at line 23 of file DTpr004A.cs.
Member Function Documentation
EnableCacheOnlyMode()
void Alaris.Infrastructure.Data.Provider.DTpr004A.EnableCacheOnlyMode ()
Enables cache-only mode (disables API calls). Call for backtests.
Implemented in Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.
Referenced by Alaris.Algorithm.STLN001A.InitialiseDataProviders().
GetHistoricalEarningsAsync() [1/2]
Task< IReadOnlyList< EarningsEvent > > Alaris.Infrastructure.Data.Provider.DTpr004A.GetHistoricalEarningsAsync (string symbol, DateTime anchorDate, int lookbackDays = 730, CancellationToken cancellationToken = default)
Gets historical earnings events for a symbol, anchored to a specific date. Use in backtest mode with simulation date as anchor.
Implemented in Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.
GetHistoricalEarningsAsync() [2/2]
Task< IReadOnlyList< EarningsEvent > > Alaris.Infrastructure.Data.Provider.DTpr004A.GetHistoricalEarningsAsync (string symbol, int lookbackDays = 730, CancellationToken cancellationToken = default)
Gets historical earnings events for a symbol.
Implemented in Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.
Referenced by Alaris.Test.Unit.TSUN029A.DTpr004A_GetHistoricalEarningsAsync_ReturnsEvents(), and Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetEarningsDataAsync().
GetSymbolsWithEarningsAsync()
Task< IReadOnlyList< string > > Alaris.Infrastructure.Data.Provider.DTpr004A.GetSymbolsWithEarningsAsync (DateTime startDate, DateTime endDate, CancellationToken cancellationToken = default)
Gets all symbols with earnings in date range.
Implemented in Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.
Referenced by Alaris.Algorithm.Universe.STUN001A.GetEarningsSymbolsForWindow(), Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetSymbolsWithUpcomingEarningsAsync(), and Alaris.Algorithm.Universe.STUN001B.LoadEarningsSymbols().
GetUpcomingEarningsAsync()
Task< IReadOnlyList< EarningsEvent > > Alaris.Infrastructure.Data.Provider.DTpr004A.GetUpcomingEarningsAsync (string symbol, int daysAhead = 90, CancellationToken cancellationToken = default)
Gets upcoming earnings events for a symbol.
Implemented in Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.
Referenced by Alaris.Test.Unit.TSUN029A.DTpr004A_GetUpcomingEarningsAsync_ReturnsEvents(), Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetEarningsDataAsync(), and Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.MeetsBasicCriteriaAsync().
The documentation for this interface was generated from the following file:
src/Alaris.Infrastructure/Data/Provider/DTpr004A.cs