Alaris: Alaris.Test.Unit.DTqc004ATests Class Reference
Alaris.Test.Unit.DTqc004ATests Class Reference sealed
Unit tests for EarningsDateValidator (DTqc004A). Validates earnings date accuracy rules.
Public Member Functions
DTqc004ATests ()
void Dispose ()
void ComponentId_ShouldBe_DTqc004A ()
void Validate_NoUpcomingEarnings_ShouldPass ()
void Validate_ValidEarningsDate_ShouldPass ()
void Validate_EarningsDateInPast_ShouldFail ()
void Validate_EarningsMoreThan90DaysAhead_ShouldWarn ()
void Validate_StaleEarningsData_ShouldWarn ()
Private Member Functions
void Dispose (bool disposing)
Static Private Member Functions
static MarketDataSnapshot CreateSnapshotWithoutEarnings ()
static MarketDataSnapshot CreateSnapshotWithEarnings (int daysAhead, int fetchedDaysAgo=0)
Private Attributes
readonly EarningsDateValidator _validator
readonly ILoggerFactory _loggerFactory
readonly ILogger< EarningsDateValidator > _logger
readonly ITimeProvider _timeProvider
bool _disposed
Detailed Description
Unit tests for EarningsDateValidator (DTqc004A). Validates earnings date accuracy rules.
Definition at line 494 of file TSUN006A.cs.
Constructor & Destructor Documentation
DTqc004ATests()
Alaris.Test.Unit.DTqc004ATests.DTqc004ATests () inline
Definition at line 502 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc004ATests._logger, Alaris.Test.Unit.DTqc004ATests._loggerFactory, Alaris.Test.Unit.DTqc004ATests._timeProvider, and Alaris.Test.Unit.DTqc004ATests._validator.
Member Function Documentation
ComponentId_ShouldBe_DTqc004A()
void Alaris.Test.Unit.DTqc004ATests.ComponentId_ShouldBe_DTqc004A () inline
Definition at line 532 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc004ATests._validator, and Alaris.Infrastructure.Data.Quality.EarningsDateValidator.ComponentId.
CreateSnapshotWithEarnings()
static MarketDataSnapshot Alaris.Test.Unit.DTqc004ATests.CreateSnapshotWithEarnings (int daysAhead, int fetchedDaysAgo = 0) inline static private
Definition at line 629 of file TSUN006A.cs.
Referenced by Alaris.Test.Unit.DTqc004ATests.Validate_EarningsDateInPast_ShouldFail(), Alaris.Test.Unit.DTqc004ATests.Validate_EarningsMoreThan90DaysAhead_ShouldWarn(), Alaris.Test.Unit.DTqc004ATests.Validate_StaleEarningsData_ShouldWarn(), and Alaris.Test.Unit.DTqc004ATests.Validate_ValidEarningsDate_ShouldPass().
CreateSnapshotWithoutEarnings()
static MarketDataSnapshot Alaris.Test.Unit.DTqc004ATests.CreateSnapshotWithoutEarnings () inline static private
Definition at line 606 of file TSUN006A.cs.
Referenced by Alaris.Test.Unit.DTqc004ATests.Validate_NoUpcomingEarnings_ShouldPass().
Dispose() [1/2]
void Alaris.Test.Unit.DTqc004ATests.Dispose () inline
Definition at line 510 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc004ATests.Dispose().
Referenced by Alaris.Test.Unit.DTqc004ATests.Dispose().
Dispose() [2/2]
void Alaris.Test.Unit.DTqc004ATests.Dispose (bool disposing) inline private
Definition at line 516 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc004ATests._disposed, and Alaris.Test.Unit.DTqc004ATests._loggerFactory.
Validate_EarningsDateInPast_ShouldFail()
void Alaris.Test.Unit.DTqc004ATests.Validate_EarningsDateInPast_ShouldFail () inline
Definition at line 565 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc004ATests._validator, Alaris.Test.Unit.DTqc004ATests.CreateSnapshotWithEarnings(), Alaris.Infrastructure.Data.Model.DataQualityResult.Status, and Alaris.Infrastructure.Data.Quality.EarningsDateValidator.Validate().
Validate_EarningsMoreThan90DaysAhead_ShouldWarn()
void Alaris.Test.Unit.DTqc004ATests.Validate_EarningsMoreThan90DaysAhead_ShouldWarn () inline
Definition at line 579 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc004ATests._validator, Alaris.Test.Unit.DTqc004ATests.CreateSnapshotWithEarnings(), Alaris.Infrastructure.Data.Model.DataQualityResult.Status, and Alaris.Infrastructure.Data.Quality.EarningsDateValidator.Validate().
Validate_NoUpcomingEarnings_ShouldPass()
void Alaris.Test.Unit.DTqc004ATests.Validate_NoUpcomingEarnings_ShouldPass () inline
Definition at line 538 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc004ATests._validator, Alaris.Test.Unit.DTqc004ATests.CreateSnapshotWithoutEarnings(), Alaris.Infrastructure.Data.Model.DataQualityResult.Status, and Alaris.Infrastructure.Data.Quality.EarningsDateValidator.Validate().
Validate_StaleEarningsData_ShouldWarn()
void Alaris.Test.Unit.DTqc004ATests.Validate_StaleEarningsData_ShouldWarn () inline
Definition at line 593 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc004ATests._validator, Alaris.Test.Unit.DTqc004ATests.CreateSnapshotWithEarnings(), Alaris.Infrastructure.Data.Model.DataQualityResult.Status, and Alaris.Infrastructure.Data.Quality.EarningsDateValidator.Validate().
Validate_ValidEarningsDate_ShouldPass()
void Alaris.Test.Unit.DTqc004ATests.Validate_ValidEarningsDate_ShouldPass () inline
Definition at line 552 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc004ATests._validator, Alaris.Test.Unit.DTqc004ATests.CreateSnapshotWithEarnings(), Alaris.Infrastructure.Data.Model.DataQualityResult.Status, and Alaris.Infrastructure.Data.Quality.EarningsDateValidator.Validate().
Member Data Documentation
_disposed
bool Alaris.Test.Unit.DTqc004ATests._disposed private
Definition at line 500 of file TSUN006A.cs.
Referenced by Alaris.Test.Unit.DTqc004ATests.Dispose().
_logger
readonly ILogger<EarningsDateValidator> Alaris.Test.Unit.DTqc004ATests._logger private
Definition at line 498 of file TSUN006A.cs.
Referenced by Alaris.Test.Unit.DTqc004ATests.DTqc004ATests().
_loggerFactory
readonly ILoggerFactory Alaris.Test.Unit.DTqc004ATests._loggerFactory private
Definition at line 497 of file TSUN006A.cs.
Referenced by Alaris.Test.Unit.DTqc004ATests.DTqc004ATests(), and Alaris.Test.Unit.DTqc004ATests.Dispose().
_timeProvider
readonly ITimeProvider Alaris.Test.Unit.DTqc004ATests._timeProvider private
Definition at line 499 of file TSUN006A.cs.
Referenced by Alaris.Test.Unit.DTqc004ATests.DTqc004ATests().
_validator
readonly EarningsDateValidator Alaris.Test.Unit.DTqc004ATests._validator private
Definition at line 496 of file TSUN006A.cs.
Referenced by Alaris.Test.Unit.DTqc004ATests.DTqc004ATests(), Alaris.Test.Unit.DTqc004ATests.ComponentId_ShouldBe_DTqc004A(), Alaris.Test.Unit.DTqc004ATests.Validate_EarningsDateInPast_ShouldFail(), Alaris.Test.Unit.DTqc004ATests.Validate_EarningsMoreThan90DaysAhead_ShouldWarn(), Alaris.Test.Unit.DTqc004ATests.Validate_NoUpcomingEarnings_ShouldPass(), Alaris.Test.Unit.DTqc004ATests.Validate_StaleEarningsData_ShouldWarn(), and Alaris.Test.Unit.DTqc004ATests.Validate_ValidEarningsDate_ShouldPass().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN006A.cs