Alaris: Alaris.Infrastructure.Protocol.Serialization.PLSR001A Class Reference
Alaris.Infrastructure.Protocol.Serialization.PLSR001A Class Reference
Zero-allocation binary serialization for Alaris market data types. Component ID: PLSR001A.
Static Public Member Functions
static int EncodePriceBar (in PriceBarData bar, Span< byte > buffer)
Encodes a PriceBar to binary format.
static PriceBarData DecodePriceBar (ReadOnlySpan< byte > buffer)
Decodes a PriceBar from binary format (zero allocation).
static int EncodeOptionContract (in OptionContractData contract, Span< byte > buffer)
Encodes an OptionContract to binary format.
static OptionContractData DecodeOptionContract (ReadOnlySpan< byte > buffer)
Decodes an OptionContract from binary format.
static long ToMantissa (decimal value)
Converts decimal to fixed-point mantissa (8 decimal places).
static decimal FromMantissa (long mantissa)
Converts fixed-point mantissa to decimal (8 decimal places).
Static Private Member Functions
static void WriteFixedString (Span< byte > buffer, string? value, int length)
Writes a fixed-length string (null-padded).
static string ReadFixedString (ReadOnlySpan< byte > buffer, int length)
Reads a fixed-length string (null-terminated).
Static Private Attributes
const ushort SchemaId = 1
const ushort SchemaVersion = 1
const ushort OptionContractTemplateId = 1
const ushort PriceBarTemplateId = 2
const ushort EarningsEventTemplateId = 3
const ushort OptionChainSnapshotTemplateId = 4
const ushort MarketDataSnapshotTemplateId = 5
const int HeaderSize = 8
Detailed Description
Zero-allocation binary serialization for Alaris market data types. Component ID: PLSR001A.
This class implements SBE-style encoding with fixed layouts and direct memory access. All encode/decode operations work on Span<byte> with no heap allocations.
Binary Format (little-endian):
Header: 8 bytes (blockLength:2, templateId:2, schemaId:2, version:2)
Fixed fields: at known offsets
Variable-length data: at end with length prefix
Definition at line 22 of file PLSR001A.cs.
Member Function Documentation
DecodeOptionContract()
static OptionContractData Alaris.Infrastructure.Protocol.Serialization.PLSR001A.DecodeOptionContract (ReadOnlySpan< byte > buffer) inline static
Decodes an OptionContract from binary format.
Definition at line 162 of file PLSR001A.cs.
References Alaris.Infrastructure.Protocol.Serialization.PLSR001A.HeaderSize, and Alaris.Infrastructure.Protocol.Serialization.PLSR001A.ReadFixedString().
Referenced by Alaris.Test.Unit.TSUN030A.OptionContractData_RoundTrip_PreservesAllFields().
DecodePriceBar()
static PriceBarData Alaris.Infrastructure.Protocol.Serialization.PLSR001A.DecodePriceBar (ReadOnlySpan< byte > buffer) inline static
Decodes a PriceBar from binary format (zero allocation).
Definition at line 82 of file PLSR001A.cs.
References Alaris.Infrastructure.Protocol.Serialization.PLSR001A.HeaderSize.
Referenced by Alaris.Infrastructure.Data.Serialization.DTsr001A.DecodePriceBar(), and Alaris.Test.Unit.TSUN030A.PriceBarData_RoundTrip_PreservesAllFields().
EncodeOptionContract()
static int Alaris.Infrastructure.Protocol.Serialization.PLSR001A.EncodeOptionContract (in OptionContractData contract, Span< byte > buffer) inline static
Encodes an OptionContract to binary format.
Definition at line 103 of file PLSR001A.cs.
References Alaris.Infrastructure.Protocol.Serialization.PLSR001A.OptionContractTemplateId, Alaris.Infrastructure.Protocol.Serialization.PLSR001A.SchemaId, Alaris.Infrastructure.Protocol.Serialization.PLSR001A.SchemaVersion, and Alaris.Infrastructure.Protocol.Serialization.PLSR001A.WriteFixedString().
Referenced by Alaris.Test.Unit.TSUN030A.OptionContractData_RoundTrip_PreservesAllFields().
EncodePriceBar()
static int Alaris.Infrastructure.Protocol.Serialization.PLSR001A.EncodePriceBar (in PriceBarData bar, Span< byte > buffer) inline static
Encodes a PriceBar to binary format.
Parameters
bar Source price bar.
buffer Target buffer (minimum 64 bytes).
Returns
Number of bytes written.
Definition at line 46 of file PLSR001A.cs.
References Alaris.Infrastructure.Protocol.Serialization.PLSR001A.PriceBarTemplateId, Alaris.Infrastructure.Protocol.Serialization.PLSR001A.SchemaId, and Alaris.Infrastructure.Protocol.Serialization.PLSR001A.SchemaVersion.
Referenced by Alaris.Infrastructure.Data.Serialization.DTsr001A.EncodePriceBar(), and Alaris.Test.Unit.TSUN030A.PriceBarData_RoundTrip_PreservesAllFields().
FromMantissa()
static decimal Alaris.Infrastructure.Protocol.Serialization.PLSR001A.FromMantissa (long mantissa) static
Converts fixed-point mantissa to decimal (8 decimal places).
Referenced by Alaris.Infrastructure.Data.Serialization.DTsr001A.DecodeOptionChainSnapshot(), Alaris.Infrastructure.Data.Serialization.DTsr001A.DecodeOptionContract(), and Alaris.Test.Unit.TSUN030A.ToMantissa_FromMantissa_RoundTrip_IsAccurate().
ReadFixedString()
static string Alaris.Infrastructure.Protocol.Serialization.PLSR001A.ReadFixedString (ReadOnlySpan< byte > buffer, int length) inline static private
Reads a fixed-length string (null-terminated).
Definition at line 222 of file PLSR001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Serialization.PLSR001A.DecodeOptionContract().
ToMantissa()
static long Alaris.Infrastructure.Protocol.Serialization.PLSR001A.ToMantissa (decimal value) static
Converts decimal to fixed-point mantissa (8 decimal places).
Referenced by Alaris.Infrastructure.Data.Serialization.DTsr001A.EncodeOptionChainSnapshot(), Alaris.Infrastructure.Data.Serialization.DTsr001A.EncodeOptionContract(), Alaris.Infrastructure.Data.Serialization.DTsr001A.EncodePriceBar(), Alaris.Strategy.Serialization.STsr001A.EncodePricingParams(), Alaris.Strategy.Serialization.STsr001A.EncodeTermPoint(), Alaris.Test.Unit.TSUN030A.OptionContractData_RoundTrip_PreservesAllFields(), Alaris.Test.Unit.TSUN030A.PriceBarData_RoundTrip_PreservesAllFields(), and Alaris.Test.Unit.TSUN030A.ToMantissa_FromMantissa_RoundTrip_IsAccurate().
WriteFixedString()
static void Alaris.Infrastructure.Protocol.Serialization.PLSR001A.WriteFixedString (Span< byte > buffer, string? value, int length) inline static private
Writes a fixed-length string (null-padded).
Definition at line 209 of file PLSR001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Serialization.PLSR001A.EncodeOptionContract().
Member Data Documentation
EarningsEventTemplateId
const ushort Alaris.Infrastructure.Protocol.Serialization.PLSR001A.EarningsEventTemplateId = 3 static private
Definition at line 31 of file PLSR001A.cs.
HeaderSize
const int Alaris.Infrastructure.Protocol.Serialization.PLSR001A.HeaderSize = 8 static private
Definition at line 36 of file PLSR001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Serialization.PLSR001A.DecodeOptionContract(), and Alaris.Infrastructure.Protocol.Serialization.PLSR001A.DecodePriceBar().
MarketDataSnapshotTemplateId
const ushort Alaris.Infrastructure.Protocol.Serialization.PLSR001A.MarketDataSnapshotTemplateId = 5 static private
Definition at line 33 of file PLSR001A.cs.
OptionChainSnapshotTemplateId
const ushort Alaris.Infrastructure.Protocol.Serialization.PLSR001A.OptionChainSnapshotTemplateId = 4 static private
Definition at line 32 of file PLSR001A.cs.
OptionContractTemplateId
const ushort Alaris.Infrastructure.Protocol.Serialization.PLSR001A.OptionContractTemplateId = 1 static private
Definition at line 29 of file PLSR001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Serialization.PLSR001A.EncodeOptionContract().
PriceBarTemplateId
const ushort Alaris.Infrastructure.Protocol.Serialization.PLSR001A.PriceBarTemplateId = 2 static private
Definition at line 30 of file PLSR001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Serialization.PLSR001A.EncodePriceBar().
SchemaId
const ushort Alaris.Infrastructure.Protocol.Serialization.PLSR001A.SchemaId = 1 static private
Definition at line 25 of file PLSR001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Serialization.PLSR001A.EncodeOptionContract(), and Alaris.Infrastructure.Protocol.Serialization.PLSR001A.EncodePriceBar().
SchemaVersion
const ushort Alaris.Infrastructure.Protocol.Serialization.PLSR001A.SchemaVersion = 1 static private
Definition at line 26 of file PLSR001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Serialization.PLSR001A.EncodeOptionContract(), and Alaris.Infrastructure.Protocol.Serialization.PLSR001A.EncodePriceBar().
The documentation for this class was generated from the following file:
src/Alaris.Infrastructure/Protocol/Serialization/PLSR001A.cs