Alaris: Alaris.Strategy.Core.STCR003A Class Reference
Alaris.Strategy.Core.STCR003A Class Reference sealed
Implements the Yang-Zhang (2000) realized volatility estimator. This estimator is an efficient method that uses OHLC data and accounts for opening jumps. Formula: RV² = σ_o² + k·σ_c² + (1-k)·σ_rs²
Public Member Functions
double Calculate (IReadOnlyList< PriceBar > priceBars, int window, bool annualized=true)
Calculates the Yang-Zhang realized volatility estimate.
IReadOnlyList<(DateTime Date, double Volatility)> CalculateRolling (IReadOnlyList< PriceBar > priceBars, int window, bool annualized=true)
Calculates a rolling Yang-Zhang volatility series. Optimized to reuse buffers across rolling window calculations.
Static Private Member Functions
static void CalculateLogReturnsInPlace (IReadOnlyList< PriceBar > priceBars, int startIdx, int window, double[] openReturns, double[] closeReturns, double[] rogersReturns)
Calculates log returns directly into provided arrays (zero allocation).
static double CalculateSTCR003AVarianceFromSpan (ReadOnlySpan< double > openReturns, ReadOnlySpan< double > closeReturns, ReadOnlySpan< double > rogersReturns, int window)
Calculates Yang-Zhang variance from Span return components (zero allocation).
static double VarianceFromSpan (ReadOnlySpan< double > values)
Calculates sample variance using (n-1) denominator from Span.
static double AverageFromSpan (ReadOnlySpan< double > values)
Calculates average from Span (zero allocation).
Static Private Attributes
const int TradingDaysPerYear = 252
Detailed Description
Implements the Yang-Zhang (2000) realized volatility estimator. This estimator is an efficient method that uses OHLC data and accounts for opening jumps. Formula: RV² = σ_o² + k·σ_c² + (1-k)·σ_rs²
Definition at line 15 of file STCR003A.cs.
Member Function Documentation
AverageFromSpan()
static double Alaris.Strategy.Core.STCR003A.AverageFromSpan (ReadOnlySpan< double > values) inline static private
Calculates average from Span (zero allocation).
Definition at line 151 of file STCR003A.cs.
Referenced by Alaris.Strategy.Core.STCR003A.CalculateSTCR003AVarianceFromSpan(), and Alaris.Strategy.Core.STCR003A.VarianceFromSpan().
Calculate()
double Alaris.Strategy.Core.STCR003A.Calculate (IReadOnlyList< PriceBar > priceBars, int window, bool annualized = true) inline
Calculates the Yang-Zhang realized volatility estimate.
Parameters
priceBars Historical OHLC price data.
window The rolling window size (typically 30 days).
annualized Whether to return annualized volatility.
Returns
The Yang-Zhang volatility estimate.
Definition at line 26 of file STCR003A.cs.
References Alaris.Strategy.Core.STCR003A.CalculateLogReturnsInPlace(), Alaris.Strategy.Core.STCR003A.CalculateSTCR003AVarianceFromSpan(), and Alaris.Strategy.Core.STCR003A.TradingDaysPerYear.
Referenced by Alaris.Strategy.Core.STCR001A.CalculateSTCR004AMetrics(), and Alaris.Algorithm.STLN001A.EvaluateSnapshot().
CalculateLogReturnsInPlace()
static void Alaris.Strategy.Core.STCR003A.CalculateLogReturnsInPlace (IReadOnlyList< PriceBar > priceBars, int startIdx, int window, double[] openReturns, double[] closeReturns, double[] rogersReturns) inline static private
Calculates log returns directly into provided arrays (zero allocation).
Definition at line 80 of file STCR003A.cs.
References Alaris.Strategy.Bridge.PriceBar.Close, Alaris.Strategy.Bridge.PriceBar.High, Alaris.Strategy.Bridge.PriceBar.Low, and Alaris.Strategy.Bridge.PriceBar.Open.
Referenced by Alaris.Strategy.Core.STCR003A.Calculate(), and Alaris.Strategy.Core.STCR003A.CalculateRolling().
CalculateRolling()
IReadOnlyList<(DateTime Date, double Volatility)> Alaris.Strategy.Core.STCR003A.CalculateRolling (IReadOnlyList< PriceBar > priceBars, int window, bool annualized = true) inline
Calculates a rolling Yang-Zhang volatility series. Optimized to reuse buffers across rolling window calculations.
Definition at line 170 of file STCR003A.cs.
References Alaris.Strategy.Core.STCR003A.CalculateLogReturnsInPlace(), Alaris.Strategy.Core.STCR003A.CalculateSTCR003AVarianceFromSpan(), and Alaris.Strategy.Core.STCR003A.TradingDaysPerYear.
CalculateSTCR003AVarianceFromSpan()
static double Alaris.Strategy.Core.STCR003A.CalculateSTCR003AVarianceFromSpan (ReadOnlySpan< double > openReturns, ReadOnlySpan< double > closeReturns, ReadOnlySpan< double > rogersReturns, int window) inline static private
Calculates Yang-Zhang variance from Span return components (zero allocation).
Definition at line 110 of file STCR003A.cs.
References Alaris.Strategy.Core.STCR003A.AverageFromSpan(), and Alaris.Strategy.Core.STCR003A.VarianceFromSpan().
Referenced by Alaris.Strategy.Core.STCR003A.Calculate(), and Alaris.Strategy.Core.STCR003A.CalculateRolling().
VarianceFromSpan()
static double Alaris.Strategy.Core.STCR003A.VarianceFromSpan (ReadOnlySpan< double > values) inline static private
Calculates sample variance using (n-1) denominator from Span.
Definition at line 131 of file STCR003A.cs.
References Alaris.Strategy.Core.STCR003A.AverageFromSpan().
Referenced by Alaris.Strategy.Core.STCR003A.CalculateSTCR003AVarianceFromSpan().
Member Data Documentation
TradingDaysPerYear
const int Alaris.Strategy.Core.STCR003A.TradingDaysPerYear = 252 static private
Definition at line 17 of file STCR003A.cs.
Referenced by Alaris.Strategy.Core.STCR003A.Calculate(), and Alaris.Strategy.Core.STCR003A.CalculateRolling().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Core/STCR003A.cs