Alaris: Alaris.Strategy.Core.STIV003A Class Reference
Alaris.Strategy.Core.STIV003A Class Reference sealed
Selects the optimal IV model based on market conditions, fit metrics, and regime. Implements automatic model selection with martingale condition enforcement. Model Selection Criteria:
Public Member Functions
STIV003A (RegimeModelConfig? config=null)
ModelSelectionResult SelectBestModel (ModelSelectionContext context)
Selects the best model for given market conditions.
Private Member Functions
ModelEvaluation EvaluateModel (RecommendedModel modelType, ModelSelectionContext context, STTM002A regime)
Evaluates a model's fit to market data.
Static Private Member Functions
static IReadOnlyList< RecommendedModel > GetCandidateModels (STTM002A regime)
Gets candidate models appropriate for the regime.
static FitMetrics ComputeFitMetrics (RecommendedModel modelType, ModelSelectionContext context)
Computes fit metrics for a model.
static IReadOnlyList< double > ComputeModelIVs (RecommendedModel modelType, ModelSelectionContext context)
Computes model IVs for comparison with market.
static int GetModelComplexity (RecommendedModel model)
Gets model complexity (number of free parameters).
static double ComputeAIC (double mse, int k, int n)
Computes Akaike Information Criterion. AIC = n * ln(MSE) + 2k.
static double ComputeBIC (double mse, int k, int n)
Computes Bayesian Information Criterion. BIC = n * ln(MSE) + k * ln(n)
static double ComputeCompositeScore (FitMetrics fit, double aic, bool martingaleValid)
Computes composite selection score.
static string GenerateSelectionReason (ModelEvaluation best, STTM002A regime)
Private Attributes
readonly MartingaleValidator _martingaleValidator
readonly RegimeModelConfig _config
Detailed Description
Selects the optimal IV model based on market conditions, fit metrics, and regime. Implements automatic model selection with martingale condition enforcement. Model Selection Criteria:
Regime detection (pre/post earnings, normal)
Fit quality (RMSE, MAE on calibration data)
Parsimony (AIC/BIC penalizing complexity)
Martingale constraint satisfaction
Out-of-sample validation Available Models:
Black-Scholes: Baseline, no parameters to calibrate
Leung-Santoli: Pre-earnings with deterministic jump
Heston: Stochastic volatility for smile/skew
Kou: Jump-diffusion for fat tails and asymmetry
Definition at line 23 of file STIV003A.cs.
Constructor & Destructor Documentation
STIV003A()
Alaris.Strategy.Core.STIV003A.STIV003A (RegimeModelConfig? config = null) inline
Definition at line 28 of file STIV003A.cs.
References Alaris.Strategy.Core.STIV003A._config, Alaris.Strategy.Core.STIV003A._martingaleValidator, and Alaris.Strategy.Core.RegimeModelConfig.Default.
Member Function Documentation
ComputeAIC()
static double Alaris.Strategy.Core.STIV003A.ComputeAIC (double mse, int k, int n) inline static private
Computes Akaike Information Criterion. AIC = n * ln(MSE) + 2k.
Definition at line 260 of file STIV003A.cs.
Referenced by Alaris.Strategy.Core.STIV003A.EvaluateModel().
ComputeBIC()
static double Alaris.Strategy.Core.STIV003A.ComputeBIC (double mse, int k, int n) inline static private
Computes Bayesian Information Criterion. BIC = n * ln(MSE) + k * ln(n)
Definition at line 274 of file STIV003A.cs.
Referenced by Alaris.Strategy.Core.STIV003A.EvaluateModel().
ComputeCompositeScore()
static double Alaris.Strategy.Core.STIV003A.ComputeCompositeScore (FitMetrics fit, double aic, bool martingaleValid) inline static private
Computes composite selection score.
Definition at line 287 of file STIV003A.cs.
References Alaris.Strategy.Core.FitMetrics.RSquared.
Referenced by Alaris.Strategy.Core.STIV003A.EvaluateModel().
ComputeFitMetrics()
static FitMetrics Alaris.Strategy.Core.STIV003A.ComputeFitMetrics (RecommendedModel modelType, ModelSelectionContext context) inline static private
Computes fit metrics for a model.
Definition at line 148 of file STIV003A.cs.
References Alaris.Strategy.Core.STIV003A.ComputeModelIVs(), Alaris.Strategy.Core.FitMetrics.Default, and Alaris.Strategy.Core.ModelSelectionContext.MarketIVs.
Referenced by Alaris.Strategy.Core.STIV003A.EvaluateModel().
ComputeModelIVs()
static IReadOnlyList< double > Alaris.Strategy.Core.STIV003A.ComputeModelIVs (RecommendedModel modelType, ModelSelectionContext context) inline static private
Computes model IVs for comparison with market.
Definition at line 200 of file STIV003A.cs.
References Alaris.Strategy.Core.ModelSelectionContext.BaseVolatility, Alaris.Strategy.Core.STIV004A.ComputeTheoreticalIV(), Alaris.Strategy.Core.STIV001A.ComputeTheoreticalIV(), Alaris.Strategy.Core.STIV002A.ComputeTheoreticalIV(), Alaris.Strategy.Calendar.TradingCalendarDefaults.DteToYears(), Alaris.Strategy.Core.ModelSelectionContext.EarningsJumpVolatility, Alaris.Strategy.Core.ModelSelectionContext.HestonParams, Alaris.Strategy.Core.ModelSelectionContext.KouParams, Alaris.Strategy.Core.ModelSelectionContext.MarketIVs, and Alaris.Strategy.Core.ModelSelectionContext.Spot.
Referenced by Alaris.Strategy.Core.STIV003A.ComputeFitMetrics().
EvaluateModel()
ModelEvaluation Alaris.Strategy.Core.STIV003A.EvaluateModel (RecommendedModel modelType, ModelSelectionContext context, STTM002A regime) inline private
Evaluates a model's fit to market data.
Definition at line 111 of file STIV003A.cs.
References Alaris.Strategy.Core.STIV003A._martingaleValidator, Alaris.Strategy.Core.STIV003A.ComputeAIC(), Alaris.Strategy.Core.STIV003A.ComputeBIC(), Alaris.Strategy.Core.STIV003A.ComputeCompositeScore(), Alaris.Strategy.Core.STIV003A.ComputeFitMetrics(), Alaris.Strategy.Core.STIV003A.GetModelComplexity(), Alaris.Strategy.Core.ModelSelectionContext.MarketIVs, Alaris.Strategy.Core.FitMetrics.MSE, and Alaris.Strategy.Core.MartingaleValidator.Validate().
Referenced by Alaris.Strategy.Core.STIV003A.SelectBestModel().
GenerateSelectionReason()
static string Alaris.Strategy.Core.STIV003A.GenerateSelectionReason (ModelEvaluation best, STTM002A regime) inline static private
Definition at line 304 of file STIV003A.cs.
Referenced by Alaris.Strategy.Core.STIV003A.SelectBestModel().
GetCandidateModels()
static IReadOnlyList< RecommendedModel > Alaris.Strategy.Core.STIV003A.GetCandidateModels (STTM002A regime) inline static private
Gets candidate models appropriate for the regime.
Definition at line 83 of file STIV003A.cs.
Referenced by Alaris.Strategy.Core.STIV003A.SelectBestModel().
GetModelComplexity()
static int Alaris.Strategy.Core.STIV003A.GetModelComplexity (RecommendedModel model) static private
Gets model complexity (number of free parameters).
Referenced by Alaris.Strategy.Core.STIV003A.EvaluateModel().
SelectBestModel()
ModelSelectionResult Alaris.Strategy.Core.STIV003A.SelectBestModel (ModelSelectionContext context) inline
Selects the best model for given market conditions.
Parameters
context Market context including spot, IV surface, and regime.
Returns
Model selection result with fit metrics.
Definition at line 39 of file STIV003A.cs.
References Alaris.Strategy.Core.STTM002A.Detect(), Alaris.Strategy.Core.STIV003A.EvaluateModel(), Alaris.Strategy.Core.STIV003A.GenerateSelectionReason(), Alaris.Strategy.Core.STIV003A.GetCandidateModels(), Alaris.Strategy.Core.ModelEvaluation.ModelType, and Alaris.Strategy.Core.ModelSelectionContext.TimeParams.
Member Data Documentation
_config
readonly RegimeModelConfig Alaris.Strategy.Core.STIV003A._config private
Definition at line 26 of file STIV003A.cs.
Referenced by Alaris.Strategy.Core.STIV003A.STIV003A().
_martingaleValidator
readonly MartingaleValidator Alaris.Strategy.Core.STIV003A._martingaleValidator private
Definition at line 25 of file STIV003A.cs.
Referenced by Alaris.Strategy.Core.STIV003A.STIV003A(), and Alaris.Strategy.Core.STIV003A.EvaluateModel().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Core/STIV003A.cs