Alaris: Alaris.Strategy.Hedge.STHD007A Class Reference
Alaris.Strategy.Hedge.STHD007A Class Reference sealed
Monitors implied volatility to trigger early exits when IV crushes faster than expected.
Public Member Functions
STHD007A (ILogger< STHD007A >? logger=null)
Initialises a new instance of the IV early exit monitor.
STHD008A Evaluate (string symbol, double currentFrontIV, double entryFrontIV, double expectedPostEarningsIV, double expectedIVCrush, int daysToExpiry)
Evaluates whether early exit is warranted based on IV behaviour.
Private Member Functions
void SafeLog (Action logAction)
Safely executes logging operation with fault isolation (Rule 15).
Static Private Member Functions
static double EstimateProfitCapture (double crushRatio)
Estimates profit capture percentage based on IV crush realisation.
Private Attributes
readonly? ILogger< STHD007A > _logger
Static Private Attributes
const double FastCrushThreshold = 0.70
Multiplier for fast crush detection (0.7 = exit if IV reaches 70% of expected post-earnings level).
const double CrushCaptureRatio = 0.80
Ratio of actual/expected crush that triggers early exit (0.8 = exit when 80% of expected crush realised).
const int MinDaysForEarlyExit = 2
Minimum trading days remaining before mandatory review.
static readonly Action< ILogger, string, double, double, Exception?> LogEarlyExitTriggered
static readonly Action< ILogger, string, double, double, Exception?> LogCrushRatioTriggered
static readonly Action< ILogger, string, Exception?> LogHoldRecommended
Detailed Description
Monitors implied volatility to trigger early exits when IV crushes faster than expected.
Definition at line 11 of file STHD007A.cs.
Constructor & Destructor Documentation
STHD007A()
Alaris.Strategy.Hedge.STHD007A.STHD007A (ILogger< STHD007A >? logger = null) inline
Initialises a new instance of the IV early exit monitor.
Parameters
logger Optional logger instance.
Definition at line 53 of file STHD007A.cs.
References Alaris.Strategy.Hedge.STHD007A._logger.
Member Function Documentation
EstimateProfitCapture()
static double Alaris.Strategy.Hedge.STHD007A.EstimateProfitCapture (double crushRatio) inline static private
Estimates profit capture percentage based on IV crush realisation.
Parameters
crushRatio Ratio of actual to expected IV crush.
Returns
Estimated profit capture percentage.
Definition at line 202 of file STHD007A.cs.
Referenced by Alaris.Strategy.Hedge.STHD007A.Evaluate().
Evaluate()
STHD008A Alaris.Strategy.Hedge.STHD007A.Evaluate (string symbol, double currentFrontIV, double entryFrontIV, double expectedPostEarningsIV, double expectedIVCrush, int daysToExpiry) inline
Evaluates whether early exit is warranted based on IV behaviour.
Parameters
symbol The underlying symbol.
currentFrontIV Current front-month implied volatility.
entryFrontIV Front-month IV at position entry.
expectedPostEarningsIV Expected IV after earnings (base volatility from L&S model).
expectedIVCrush Expected IV crush magnitude in volatility points.
daysToExpiry Trading days until front-month expiration.
Returns
Early exit decision with recommendation and rationale.
Exceptions
ArgumentException Thrown when symbol is null or empty.
ArgumentOutOfRangeException Thrown when IV values are invalid.
Definition at line 70 of file STHD007A.cs.
References Alaris.Strategy.Hedge.STHD007A._logger, Alaris.Strategy.Hedge.STHD007A.CrushCaptureRatio, Alaris.Strategy.Hedge.STHD007A.EstimateProfitCapture(), Alaris.Strategy.Hedge.STHD007A.FastCrushThreshold, Alaris.Strategy.Hedge.STHD007A.LogCrushRatioTriggered, Alaris.Strategy.Hedge.STHD007A.LogEarlyExitTriggered, Alaris.Strategy.Hedge.STHD007A.LogHoldRecommended, Alaris.Strategy.Hedge.STHD007A.MinDaysForEarlyExit, Alaris.Strategy.Hedge.STHD007A.SafeLog(), and Alaris.Strategy.Hedge.STHD008A.
Referenced by Alaris.Test.Unit.STHD007ATests.Evaluate_CapturedProfitPercent_IsCalculatedCorrectly(), Alaris.Test.Unit.STHD007ATests.Evaluate_ResultSummary_IsHumanReadable(), Alaris.Test.Unit.STHD007ATests.Evaluate_WhenCrushRatioExceedsThreshold_ReturnsExitDecision(), Alaris.Test.Unit.STHD007ATests.Evaluate_WhenIVCrushesFasterThanExpected_ReturnsExitDecision(), Alaris.Test.Unit.STHD007ATests.Evaluate_WhenIVWithinExpectedRange_ReturnsHold(), Alaris.Test.Unit.STHD007ATests.Evaluate_WhenNearExpiryWithPartialCrush_ReturnsExit(), Alaris.Test.Unit.STHD007ATests.Evaluate_WithInvalidIV_ThrowsArgumentOutOfRangeException(), Alaris.Test.Unit.STHD007ATests.Evaluate_WithInvalidSymbol_ThrowsArgumentException(), and Alaris.Test.Unit.STHD007ATests.Evaluate_WithZeroExpectedCrush_HandlesGracefully().
SafeLog()
void Alaris.Strategy.Hedge.STHD007A.SafeLog (Action logAction) inline private
Safely executes logging operation with fault isolation (Rule 15).
Definition at line 214 of file STHD007A.cs.
References Alaris.Strategy.Hedge.STHD007A._logger.
Referenced by Alaris.Strategy.Hedge.STHD007A.Evaluate().
Member Data Documentation
_logger
readonly? ILogger<STHD007A> Alaris.Strategy.Hedge.STHD007A._logger private
Definition at line 13 of file STHD007A.cs.
Referenced by Alaris.Strategy.Hedge.STHD007A.STHD007A(), Alaris.Strategy.Hedge.STHD007A.Evaluate(), and Alaris.Strategy.Hedge.STHD007A.SafeLog().
CrushCaptureRatio
const double Alaris.Strategy.Hedge.STHD007A.CrushCaptureRatio = 0.80 static private
Ratio of actual/expected crush that triggers early exit (0.8 = exit when 80% of expected crush realised).
Definition at line 23 of file STHD007A.cs.
Referenced by Alaris.Strategy.Hedge.STHD007A.Evaluate().
FastCrushThreshold
const double Alaris.Strategy.Hedge.STHD007A.FastCrushThreshold = 0.70 static private
Multiplier for fast crush detection (0.7 = exit if IV reaches 70% of expected post-earnings level).
Definition at line 18 of file STHD007A.cs.
Referenced by Alaris.Strategy.Hedge.STHD007A.Evaluate().
LogCrushRatioTriggered
readonly Action<ILogger, string, double, double, Exception?> Alaris.Strategy.Hedge.STHD007A.LogCrushRatioTriggered static private
Initial value:
=
        LoggerMessage.Define<string, double, double>(
            LogLevel.Information,
            new EventId(2, nameof(LogCrushRatioTriggered)),
            "Crush ratio exit for {Symbol}: actualCrush={ActualCrush:P2}, expectedCrush={ExpectedCrush:P2}")
Definition at line 37 of file STHD007A.cs.
Referenced by Alaris.Strategy.Hedge.STHD007A.Evaluate().
LogEarlyExitTriggered
readonly Action<ILogger, string, double, double, Exception?> Alaris.Strategy.Hedge.STHD007A.LogEarlyExitTriggered static private
Initial value:
=
        LoggerMessage.Define<string, double, double>(
            LogLevel.Information,
            new EventId(1, nameof(LogEarlyExitTriggered)),
            "Early exit triggered for {Symbol}: currentIV={CurrentIV:P2}, expectedPostEarnings={ExpectedIV:P2}")
Definition at line 31 of file STHD007A.cs.
Referenced by Alaris.Strategy.Hedge.STHD007A.Evaluate().
LogHoldRecommended
readonly Action<ILogger, string, Exception?> Alaris.Strategy.Hedge.STHD007A.LogHoldRecommended static private
Initial value:
=
        LoggerMessage.Define<string>(
            LogLevel.Debug,
            new EventId(3, nameof(LogHoldRecommended)),
            "Hold recommended for {Symbol}: IV crush within expected range")
Definition at line 43 of file STHD007A.cs.
Referenced by Alaris.Strategy.Hedge.STHD007A.Evaluate().
MinDaysForEarlyExit
const int Alaris.Strategy.Hedge.STHD007A.MinDaysForEarlyExit = 2 static private
Minimum trading days remaining before mandatory review.
Definition at line 28 of file STHD007A.cs.
Referenced by Alaris.Strategy.Hedge.STHD007A.Evaluate().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Hedge/STHD007A.cs