Alaris: Alaris.Strategy.Cost.STCS005A Class Reference
Alaris.Strategy.Cost.STCS005A Class Reference sealed
Implements a constant per-contract fee model for option execution costs.
Public Member Functions
STCS005A (double feePerContract=DefaultFeePerContract, double exchangeFeePerContract=DefaultExchangeFee, double regulatoryFeePerContract=DefaultRegulatoryFee, ILogger< STCS005A >? logger=null)
Initialises a new instance of the constant fee model.
STCS003A ComputeOptionCost (STCS002A parameters)
Computes the execution cost for an option order.
Parameters
parameters The order parameters.
Returns
The computed execution cost result.
Exceptions
ArgumentNullException Thrown when parameters is null.
STCS004A ComputeSpreadCost (STCS002A frontLegParameters, STCS002A backLegParameters)
Computes the execution cost for a calendar spread order.
Parameters
frontLegParameters Parameters for the front-month leg.
backLegParameters Parameters for the back-month leg.
Returns
The combined execution cost for the spread.
Exceptions
ArgumentNullException Thrown when either parameter is null.
Static Public Attributes
const double DefaultFeePerContract = 0.65
Default commission fee per contract (conservative estimate).
const double DefaultExchangeFee = 0.30
Default exchange fee per contract.
const double DefaultRegulatoryFee = 0.02
Default regulatory fee per contract.
Properties
string ModelName [get]
Gets the name of the cost model for logging and identification.
Properties inherited from Alaris.Strategy.Cost.STCS001A
Private Member Functions
void SafeLog (Action logAction)
Safely executes logging operation with fault isolation (Rule 15).
Private Attributes
readonly? ILogger< STCS005A > _logger
readonly double _feePerContract
readonly double _exchangeFeePerContract
readonly double _regulatoryFeePerContract
Static Private Attributes
static readonly Action< ILogger, string, int, double, Exception?> LogCostComputed
static readonly Action< ILogger, double, double, double, Exception?> LogSpreadCostComputed
Detailed Description
Implements a constant per-contract fee model for option execution costs.
Definition at line 11 of file STCS005A.cs.
Constructor & Destructor Documentation
STCS005A()
Alaris.Strategy.Cost.STCS005A.STCS005A (double feePerContract = DefaultFeePerContract, double exchangeFeePerContract = DefaultExchangeFee, double regulatoryFeePerContract = DefaultRegulatoryFee, ILogger< STCS005A >? logger = null) inline
Initialises a new instance of the constant fee model.
Parameters
feePerContract Commission fee per contract. Default: $0.65.
exchangeFeePerContract Exchange fee per contract. Default: $0.30.
regulatoryFeePerContract Regulatory fee per contract. Default: $0.02.
logger Optional logger instance.
Exceptions
ArgumentOutOfRangeException Thrown when any fee is negative.
Definition at line 65 of file STCS005A.cs.
References Alaris.Strategy.Cost.STCS005A._exchangeFeePerContract, Alaris.Strategy.Cost.STCS005A._feePerContract, Alaris.Strategy.Cost.STCS005A._logger, and Alaris.Strategy.Cost.STCS005A._regulatoryFeePerContract.
Member Function Documentation
ComputeOptionCost()
STCS003A Alaris.Strategy.Cost.STCS005A.ComputeOptionCost (STCS002A parameters) inline
Computes the execution cost for an option order.
Parameters
parameters The order parameters.
Returns
The computed execution cost result.
Exceptions
ArgumentNullException Thrown when parameters is null.
Implements Alaris.Strategy.Cost.STCS001A.
Definition at line 105 of file STCS005A.cs.
References Alaris.Strategy.Cost.STCS005A._exchangeFeePerContract, Alaris.Strategy.Cost.STCS005A._feePerContract, Alaris.Strategy.Cost.STCS005A._logger, Alaris.Strategy.Cost.STCS005A._regulatoryFeePerContract, Alaris.Strategy.Cost.STCS005A.LogCostComputed, Alaris.Strategy.Cost.STCS005A.SafeLog(), and Alaris.Strategy.Cost.STCS003A.
Referenced by Alaris.Strategy.Cost.STCS005A.ComputeSpreadCost().
ComputeSpreadCost()
STCS004A Alaris.Strategy.Cost.STCS005A.ComputeSpreadCost (STCS002A frontLegParameters, STCS002A backLegParameters) inline
Computes the execution cost for a calendar spread order.
Parameters
frontLegParameters Parameters for the front-month leg.
backLegParameters Parameters for the back-month leg.
Returns
The combined execution cost for the spread.
Exceptions
ArgumentNullException Thrown when either parameter is null.
Implements Alaris.Strategy.Cost.STCS001A.
Definition at line 142 of file STCS005A.cs.
References Alaris.Strategy.Cost.STCS005A._logger, Alaris.Strategy.Cost.STCS005A.ComputeOptionCost(), Alaris.Strategy.Cost.STCS005A.LogSpreadCostComputed, Alaris.Strategy.Cost.STCS005A.SafeLog(), Alaris.Strategy.Cost.STCS002A, Alaris.Strategy.Cost.STCS003A, and Alaris.Strategy.Cost.STCS004A.
SafeLog()
void Alaris.Strategy.Cost.STCS005A.SafeLog (Action logAction) inline private
Safely executes logging operation with fault isolation (Rule 15).
Definition at line 191 of file STCS005A.cs.
References Alaris.Strategy.Cost.STCS005A._logger.
Referenced by Alaris.Strategy.Cost.STCS005A.ComputeOptionCost(), and Alaris.Strategy.Cost.STCS005A.ComputeSpreadCost().
Member Data Documentation
_exchangeFeePerContract
readonly double Alaris.Strategy.Cost.STCS005A._exchangeFeePerContract private
Definition at line 15 of file STCS005A.cs.
Referenced by Alaris.Strategy.Cost.STCS005A.STCS005A(), and Alaris.Strategy.Cost.STCS005A.ComputeOptionCost().
_feePerContract
readonly double Alaris.Strategy.Cost.STCS005A._feePerContract private
Definition at line 14 of file STCS005A.cs.
Referenced by Alaris.Strategy.Cost.STCS005A.STCS005A(), and Alaris.Strategy.Cost.STCS005A.ComputeOptionCost().
_logger
readonly? ILogger<STCS005A> Alaris.Strategy.Cost.STCS005A._logger private
Definition at line 13 of file STCS005A.cs.
Referenced by Alaris.Strategy.Cost.STCS005A.STCS005A(), Alaris.Strategy.Cost.STCS005A.ComputeOptionCost(), Alaris.Strategy.Cost.STCS005A.ComputeSpreadCost(), and Alaris.Strategy.Cost.STCS005A.SafeLog().
_regulatoryFeePerContract
readonly double Alaris.Strategy.Cost.STCS005A._regulatoryFeePerContract private
Definition at line 16 of file STCS005A.cs.
Referenced by Alaris.Strategy.Cost.STCS005A.STCS005A(), and Alaris.Strategy.Cost.STCS005A.ComputeOptionCost().
DefaultExchangeFee
const double Alaris.Strategy.Cost.STCS005A.DefaultExchangeFee = 0.30 static
Default exchange fee per contract.
Definition at line 41 of file STCS005A.cs.
DefaultFeePerContract
const double Alaris.Strategy.Cost.STCS005A.DefaultFeePerContract = 0.65 static
Default commission fee per contract (conservative estimate).
Definition at line 35 of file STCS005A.cs.
DefaultRegulatoryFee
const double Alaris.Strategy.Cost.STCS005A.DefaultRegulatoryFee = 0.02 static
Default regulatory fee per contract.
Definition at line 47 of file STCS005A.cs.
LogCostComputed
readonly Action<ILogger, string, int, double, Exception?> Alaris.Strategy.Cost.STCS005A.LogCostComputed static private
Initial value:
=
        LoggerMessage.Define<string, int, double>(
            LogLevel.Debug,
            new EventId(1, nameof(LogCostComputed)),
            "Cost computed for {Symbol}: {Contracts} contracts, total cost ${TotalCost:F4}")
Definition at line 19 of file STCS005A.cs.
Referenced by Alaris.Strategy.Cost.STCS005A.ComputeOptionCost().
LogSpreadCostComputed
readonly Action<ILogger, double, double, double, Exception?> Alaris.Strategy.Cost.STCS005A.LogSpreadCostComputed static private
Initial value:
=
        LoggerMessage.Define<double, double, double>(
            LogLevel.Debug,
            new EventId(2, nameof(LogSpreadCostComputed)),
            "Spread cost: theoretical ${TheoreticalDebit:F4}, execution ${ExecutionDebit:F4}, slippage {SlippagePercent:F2}%")
Definition at line 25 of file STCS005A.cs.
Referenced by Alaris.Strategy.Cost.STCS005A.ComputeSpreadCost().
Property Documentation
ModelName
string Alaris.Strategy.Cost.STCS005A.ModelName get
Gets the name of the cost model for logging and identification.
Implements Alaris.Strategy.Cost.STCS001A.
Definition at line 102 of file STCS005A.cs.
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Cost/STCS005A.cs