Alaris: Alaris.Test.Unit.STBR001ATests Class Reference
Alaris.Test.Unit.STBR001ATests Class Reference sealed
Unit tests for the STBR001A component. Tests regime detection, pricing accuracy, and calendar spread calculations.
Public Member Functions
STBR001ATests ()
void DetermineRegime_ReturnsCorrectRegime (double rate, double dividend, bool isCall, PricingRegime expected)
void DetermineRegime_PositiveRates_Standard ()
void DetermineRegime_NegativeRatesDoubleBoundary ()
async Task PriceOption_PositiveRates_CallOption ()
async Task PriceOption_PositiveRates_PutOption ()
async Task PriceOption_PositiveRates_ATM_HasHighestGamma ()
async Task PriceOption_NegativeRates_DoubleBoundary_Put ()
async Task PriceOption_NegativeRates_DoubleBoundary_Call ()
async Task PriceOption_NegativeRates_ConsistentAcrossRegimes ()
async Task PriceSTPR001A_PositiveRates_ValidSpread ()
async Task PriceSTPR001A_PositiveRates_CorrectGreeks ()
async Task PriceSTPR001A_NegativeRates_ValidSpread ()
async Task PriceSTPR001A_Validation_Works ()
async Task CalculateImpliedVolatility_ConvergesCorrectly ()
async Task CalculateImpliedVolatility_InvalidPrice_Throws ()
async Task CalculateImpliedVolatility_ZeroPrice_Throws ()
async Task PriceOption_NullParameters_Throws ()
async Task PriceOption_InvalidParameters_Throws ()
async Task PriceSTPR001A_NullParameters_Throws ()
async Task PriceSTPR001A_FrontAfterBack_Throws ()
void Dispose ()
Private Member Functions
STDT003A CreateStandardCallParameters ()
STDT003A CreateStandardPutParameters ()
STDT003A CreateHealyPutParameters ()
STDT003A CreateHealyCallParameters ()
STPR001AParameters CreateSTPR001AParameters ()
void Dispose (bool disposing)
Private Attributes
readonly STBR001A _engine
readonly CRTM005A _valuationDate
bool _disposed
Detailed Description
Unit tests for the STBR001A component. Tests regime detection, pricing accuracy, and calendar spread calculations.
Definition at line 15 of file TSUN009A.cs.
Constructor & Destructor Documentation
STBR001ATests()
Alaris.Test.Unit.STBR001ATests.STBR001ATests () inline
Definition at line 21 of file TSUN009A.cs.
References Alaris.Test.Unit.STBR001ATests._engine, and Alaris.Test.Unit.STBR001ATests._valuationDate.
Member Function Documentation
CalculateImpliedVolatility_ConvergesCorrectly()
async Task Alaris.Test.Unit.STBR001ATests.CalculateImpliedVolatility_ConvergesCorrectly () inline
Definition at line 254 of file TSUN009A.cs.
References Alaris.Test.Unit.STBR001ATests._engine, Alaris.Strategy.Bridge.STBR001A.CalculateImpliedVolatility(), Alaris.Test.Unit.STBR001ATests.CreateStandardCallParameters(), and Alaris.Strategy.Bridge.STBR001A.PriceOption().
CalculateImpliedVolatility_InvalidPrice_Throws()
async Task Alaris.Test.Unit.STBR001ATests.CalculateImpliedVolatility_InvalidPrice_Throws () inline
Definition at line 276 of file TSUN009A.cs.
References Alaris.Test.Unit.STBR001ATests._engine, and Alaris.Test.Unit.STBR001ATests.CreateStandardCallParameters().
CalculateImpliedVolatility_ZeroPrice_Throws()
async Task Alaris.Test.Unit.STBR001ATests.CalculateImpliedVolatility_ZeroPrice_Throws () inline
Definition at line 288 of file TSUN009A.cs.
References Alaris.Test.Unit.STBR001ATests._engine, and Alaris.Test.Unit.STBR001ATests.CreateStandardCallParameters().
CreateHealyCallParameters()
STDT003A Alaris.Test.Unit.STBR001ATests.CreateHealyCallParameters () inline private
Definition at line 390 of file TSUN009A.cs.
References Alaris.Test.Unit.STBR001ATests._valuationDate, and Alaris.Core.Time.CRTM005A.AddDays().
Referenced by Alaris.Test.Unit.STBR001ATests.PriceOption_NegativeRates_DoubleBoundary_Call().
CreateHealyPutParameters()
STDT003A Alaris.Test.Unit.STBR001ATests.CreateHealyPutParameters () inline private
Definition at line 374 of file TSUN009A.cs.
References Alaris.Test.Unit.STBR001ATests._valuationDate, and Alaris.Core.Time.CRTM005A.AddDays().
Referenced by Alaris.Test.Unit.STBR001ATests.PriceOption_NegativeRates_DoubleBoundary_Put().
CreateStandardCallParameters()
STDT003A Alaris.Test.Unit.STBR001ATests.CreateStandardCallParameters () inline private
Definition at line 344 of file TSUN009A.cs.
References Alaris.Test.Unit.STBR001ATests._valuationDate, and Alaris.Core.Time.CRTM005A.AddDays().
Referenced by Alaris.Test.Unit.STBR001ATests.CalculateImpliedVolatility_ConvergesCorrectly(), Alaris.Test.Unit.STBR001ATests.CalculateImpliedVolatility_InvalidPrice_Throws(), Alaris.Test.Unit.STBR001ATests.CalculateImpliedVolatility_ZeroPrice_Throws(), Alaris.Test.Unit.STBR001ATests.PriceOption_InvalidParameters_Throws(), Alaris.Test.Unit.STBR001ATests.PriceOption_NegativeRates_ConsistentAcrossRegimes(), Alaris.Test.Unit.STBR001ATests.PriceOption_PositiveRates_ATM_HasHighestGamma(), and Alaris.Test.Unit.STBR001ATests.PriceOption_PositiveRates_CallOption().
CreateStandardPutParameters()
STDT003A Alaris.Test.Unit.STBR001ATests.CreateStandardPutParameters () inline private
Definition at line 359 of file TSUN009A.cs.
References Alaris.Test.Unit.STBR001ATests._valuationDate, and Alaris.Core.Time.CRTM005A.AddDays().
Referenced by Alaris.Test.Unit.STBR001ATests.PriceOption_PositiveRates_PutOption().
CreateSTPR001AParameters()
STPR001AParameters Alaris.Test.Unit.STBR001ATests.CreateSTPR001AParameters () inline private
Definition at line 405 of file TSUN009A.cs.
References Alaris.Test.Unit.STBR001ATests._valuationDate, and Alaris.Core.Time.CRTM005A.AddDays().
Referenced by Alaris.Test.Unit.STBR001ATests.PriceSTPR001A_FrontAfterBack_Throws(), Alaris.Test.Unit.STBR001ATests.PriceSTPR001A_NegativeRates_ValidSpread(), Alaris.Test.Unit.STBR001ATests.PriceSTPR001A_PositiveRates_CorrectGreeks(), Alaris.Test.Unit.STBR001ATests.PriceSTPR001A_PositiveRates_ValidSpread(), and Alaris.Test.Unit.STBR001ATests.PriceSTPR001A_Validation_Works().
DetermineRegime_NegativeRatesDoubleBoundary()
void Alaris.Test.Unit.STBR001ATests.DetermineRegime_NegativeRatesDoubleBoundary () inline
Definition at line 63 of file TSUN009A.cs.
References Alaris.Strategy.Bridge.STBR001A.DetermineRegime().
DetermineRegime_PositiveRates_Standard()
void Alaris.Test.Unit.STBR001ATests.DetermineRegime_PositiveRates_Standard () inline
Definition at line 48 of file TSUN009A.cs.
References Alaris.Strategy.Bridge.STBR001A.DetermineRegime().
DetermineRegime_ReturnsCorrectRegime()
void Alaris.Test.Unit.STBR001ATests.DetermineRegime_ReturnsCorrectRegime (double rate, double dividend, bool isCall, PricingRegime expected) inline
Definition at line 38 of file TSUN009A.cs.
References Alaris.Strategy.Bridge.STBR001A.DetermineRegime().
Dispose() [1/2]
void Alaris.Test.Unit.STBR001ATests.Dispose () inline
Definition at line 422 of file TSUN009A.cs.
References Alaris.Test.Unit.STBR001ATests.Dispose().
Referenced by Alaris.Test.Unit.STBR001ATests.Dispose().
Dispose() [2/2]
void Alaris.Test.Unit.STBR001ATests.Dispose (bool disposing) inline private
Definition at line 428 of file TSUN009A.cs.
References Alaris.Test.Unit.STBR001ATests._disposed, Alaris.Test.Unit.STBR001ATests._engine, and Alaris.Strategy.Bridge.STBR001A.Dispose().
PriceOption_InvalidParameters_Throws()
async Task Alaris.Test.Unit.STBR001ATests.PriceOption_InvalidParameters_Throws () inline
Definition at line 310 of file TSUN009A.cs.
References Alaris.Test.Unit.STBR001ATests._engine, and Alaris.Test.Unit.STBR001ATests.CreateStandardCallParameters().
PriceOption_NegativeRates_ConsistentAcrossRegimes()
async Task Alaris.Test.Unit.STBR001ATests.PriceOption_NegativeRates_ConsistentAcrossRegimes () inline
Definition at line 165 of file TSUN009A.cs.
References Alaris.Test.Unit.STBR001ATests._engine, Alaris.Test.Unit.STBR001ATests.CreateStandardCallParameters(), and Alaris.Strategy.Bridge.STBR001A.PriceOption().
PriceOption_NegativeRates_DoubleBoundary_Call()
async Task Alaris.Test.Unit.STBR001ATests.PriceOption_NegativeRates_DoubleBoundary_Call () inline
Definition at line 150 of file TSUN009A.cs.
References Alaris.Test.Unit.STBR001ATests._engine, Alaris.Test.Unit.STBR001ATests.CreateHealyCallParameters(), and Alaris.Strategy.Bridge.STBR001A.PriceOption().
PriceOption_NegativeRates_DoubleBoundary_Put()
async Task Alaris.Test.Unit.STBR001ATests.PriceOption_NegativeRates_DoubleBoundary_Put () inline
Definition at line 133 of file TSUN009A.cs.
References Alaris.Test.Unit.STBR001ATests._engine, Alaris.Test.Unit.STBR001ATests.CreateHealyPutParameters(), and Alaris.Strategy.Bridge.STBR001A.PriceOption().
PriceOption_NullParameters_Throws()
async Task Alaris.Test.Unit.STBR001ATests.PriceOption_NullParameters_Throws () inline
Definition at line 302 of file TSUN009A.cs.
References Alaris.Test.Unit.STBR001ATests._engine.
PriceOption_PositiveRates_ATM_HasHighestGamma()
async Task Alaris.Test.Unit.STBR001ATests.PriceOption_PositiveRates_ATM_HasHighestGamma () inline
Definition at line 117 of file TSUN009A.cs.
References Alaris.Test.Unit.STBR001ATests._engine, Alaris.Test.Unit.STBR001ATests.CreateStandardCallParameters(), and Alaris.Strategy.Bridge.STBR001A.PriceOption().
PriceOption_PositiveRates_CallOption()
async Task Alaris.Test.Unit.STBR001ATests.PriceOption_PositiveRates_CallOption () inline
Definition at line 80 of file TSUN009A.cs.
References Alaris.Test.Unit.STBR001ATests._engine, Alaris.Test.Unit.STBR001ATests.CreateStandardCallParameters(), and Alaris.Strategy.Bridge.STBR001A.PriceOption().
PriceOption_PositiveRates_PutOption()
async Task Alaris.Test.Unit.STBR001ATests.PriceOption_PositiveRates_PutOption () inline
Definition at line 99 of file TSUN009A.cs.
References Alaris.Test.Unit.STBR001ATests._engine, Alaris.Test.Unit.STBR001ATests.CreateStandardPutParameters(), and Alaris.Strategy.Bridge.STBR001A.PriceOption().
PriceSTPR001A_FrontAfterBack_Throws()
async Task Alaris.Test.Unit.STBR001ATests.PriceSTPR001A_FrontAfterBack_Throws () inline
Definition at line 330 of file TSUN009A.cs.
References Alaris.Test.Unit.STBR001ATests._engine, and Alaris.Test.Unit.STBR001ATests.CreateSTPR001AParameters().
PriceSTPR001A_NegativeRates_ValidSpread()
async Task Alaris.Test.Unit.STBR001ATests.PriceSTPR001A_NegativeRates_ValidSpread () inline
Definition at line 221 of file TSUN009A.cs.
References Alaris.Test.Unit.STBR001ATests._engine, Alaris.Test.Unit.STBR001ATests.CreateSTPR001AParameters(), and Alaris.Strategy.Bridge.STBR001A.PriceSTPR001A().
PriceSTPR001A_NullParameters_Throws()
async Task Alaris.Test.Unit.STBR001ATests.PriceSTPR001A_NullParameters_Throws () inline
Definition at line 322 of file TSUN009A.cs.
References Alaris.Test.Unit.STBR001ATests._engine.
PriceSTPR001A_PositiveRates_CorrectGreeks()
async Task Alaris.Test.Unit.STBR001ATests.PriceSTPR001A_PositiveRates_CorrectGreeks () inline
Definition at line 205 of file TSUN009A.cs.
References Alaris.Test.Unit.STBR001ATests._engine, Alaris.Test.Unit.STBR001ATests.CreateSTPR001AParameters(), and Alaris.Strategy.Bridge.STBR001A.PriceSTPR001A().
PriceSTPR001A_PositiveRates_ValidSpread()
async Task Alaris.Test.Unit.STBR001ATests.PriceSTPR001A_PositiveRates_ValidSpread () inline
Definition at line 187 of file TSUN009A.cs.
References Alaris.Test.Unit.STBR001ATests._engine, Alaris.Test.Unit.STBR001ATests.CreateSTPR001AParameters(), and Alaris.Strategy.Bridge.STBR001A.PriceSTPR001A().
PriceSTPR001A_Validation_Works()
async Task Alaris.Test.Unit.STBR001ATests.PriceSTPR001A_Validation_Works () inline
Definition at line 239 of file TSUN009A.cs.
References Alaris.Test.Unit.STBR001ATests._engine, Alaris.Test.Unit.STBR001ATests.CreateSTPR001AParameters(), and Alaris.Strategy.Bridge.STBR001A.PriceSTPR001A().
Member Data Documentation
_disposed
bool Alaris.Test.Unit.STBR001ATests._disposed private
Definition at line 19 of file TSUN009A.cs.
Referenced by Alaris.Test.Unit.STBR001ATests.Dispose().
_engine
readonly STBR001A Alaris.Test.Unit.STBR001ATests._engine private
Definition at line 17 of file TSUN009A.cs.
Referenced by Alaris.Test.Unit.STBR001ATests.STBR001ATests(), Alaris.Test.Unit.STBR001ATests.CalculateImpliedVolatility_ConvergesCorrectly(), Alaris.Test.Unit.STBR001ATests.CalculateImpliedVolatility_InvalidPrice_Throws(), Alaris.Test.Unit.STBR001ATests.CalculateImpliedVolatility_ZeroPrice_Throws(), Alaris.Test.Unit.STBR001ATests.Dispose(), Alaris.Test.Unit.STBR001ATests.PriceOption_InvalidParameters_Throws(), Alaris.Test.Unit.STBR001ATests.PriceOption_NegativeRates_ConsistentAcrossRegimes(), Alaris.Test.Unit.STBR001ATests.PriceOption_NegativeRates_DoubleBoundary_Call(), Alaris.Test.Unit.STBR001ATests.PriceOption_NegativeRates_DoubleBoundary_Put(), Alaris.Test.Unit.STBR001ATests.PriceOption_NullParameters_Throws(), Alaris.Test.Unit.STBR001ATests.PriceOption_PositiveRates_ATM_HasHighestGamma(), Alaris.Test.Unit.STBR001ATests.PriceOption_PositiveRates_CallOption(), Alaris.Test.Unit.STBR001ATests.PriceOption_PositiveRates_PutOption(), Alaris.Test.Unit.STBR001ATests.PriceSTPR001A_FrontAfterBack_Throws(), Alaris.Test.Unit.STBR001ATests.PriceSTPR001A_NegativeRates_ValidSpread(), Alaris.Test.Unit.STBR001ATests.PriceSTPR001A_NullParameters_Throws(), Alaris.Test.Unit.STBR001ATests.PriceSTPR001A_PositiveRates_CorrectGreeks(), Alaris.Test.Unit.STBR001ATests.PriceSTPR001A_PositiveRates_ValidSpread(), and Alaris.Test.Unit.STBR001ATests.PriceSTPR001A_Validation_Works().
_valuationDate
readonly CRTM005A Alaris.Test.Unit.STBR001ATests._valuationDate private
Definition at line 18 of file TSUN009A.cs.
Referenced by Alaris.Test.Unit.STBR001ATests.STBR001ATests(), Alaris.Test.Unit.STBR001ATests.CreateHealyCallParameters(), Alaris.Test.Unit.STBR001ATests.CreateHealyPutParameters(), Alaris.Test.Unit.STBR001ATests.CreateStandardCallParameters(), Alaris.Test.Unit.STBR001ATests.CreateStandardPutParameters(), and Alaris.Test.Unit.STBR001ATests.CreateSTPR001AParameters().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN009A.cs