Alaris: Alaris.Core.Time.CRTM006A Struct Reference
Alaris.Core.Time.CRTM006A Struct Reference
Represents a time period with a length and unit. Matches QuantLib Period semantics.
Public Member Functions
CRTM006A (int length, CRTM006AUnit unit)
Initialises a new period.
bool Equals (CRTM006A other)
override bool Equals (object? obj)
override int GetHashCode ()
override string ToString ()
Static Public Member Functions
static CRTM006A Days (int n)
Creates a period of the specified number of days.
static CRTM006A Weeks (int n)
Creates a period of the specified number of weeks.
static CRTM006A Months (int n)
Creates a period of the specified number of months.
static CRTM006A Years (int n)
Creates a period of the specified number of years.
static CRTM006A operator- (CRTM006A period)
Negates the period.
static CRTM006A Negate (CRTM006A period)
Negates the period (friendly alternate for - operator).
static CRTM006A operator* (CRTM006A period, int multiplier)
Multiplies the period by a scalar.
static CRTM006A operator* (int multiplier, CRTM006A period)
Multiplies the period by a scalar.
static CRTM006A Multiply (CRTM006A period, int multiplier)
Multiplies the period by a scalar (friendly alternate for * operator).
static bool operator== (CRTM006A left, CRTM006A right)
Compares two periods for equality.
static bool operator!= (CRTM006A left, CRTM006A right)
Compares two periods for inequality.
Properties
int Length [get]
Gets the length of the period.
CRTM006AUnit Unit [get]
Gets the unit of the period.
Detailed Description
Represents a time period with a length and unit. Matches QuantLib Period semantics.
Definition at line 18 of file CRTM006A.cs.
Constructor & Destructor Documentation
CRTM006A()
Alaris.Core.Time.CRTM006A.CRTM006A (int length, CRTM006AUnit unit) inline
Initialises a new period.
Parameters
length The length of the period.
unit The unit of the period.
Definition at line 35 of file CRTM006A.cs.
References Alaris.Core.Time.CRTM006A.Length, and Alaris.Core.Time.CRTM006A.Unit.
Member Function Documentation
Days()
static CRTM006A Alaris.Core.Time.CRTM006A.Days (int n) static
Creates a period of the specified number of days.
Equals() [1/2]
bool Alaris.Core.Time.CRTM006A.Equals (CRTM006A other) inline
Definition at line 105 of file CRTM006A.cs.
References Alaris.Core.Time.CRTM006A.Length, and Alaris.Core.Time.CRTM006A.Unit.
Referenced by Alaris.Core.Time.CRTM006A.Equals(), Alaris.Core.Time.CRTM006A.operator!=(), and Alaris.Core.Time.CRTM006A.operator==().
Equals() [2/2]
override bool Alaris.Core.Time.CRTM006A.Equals (object? obj) inline
Definition at line 111 of file CRTM006A.cs.
References Alaris.Core.Time.CRTM006A.Equals().
GetHashCode()
override int Alaris.Core.Time.CRTM006A.GetHashCode () inline
Definition at line 117 of file CRTM006A.cs.
References Alaris.Core.Time.CRTM006A.Length, and Alaris.Core.Time.CRTM006A.Unit.
Months()
static CRTM006A Alaris.Core.Time.CRTM006A.Months (int n) static
Creates a period of the specified number of months.
Multiply()
static CRTM006A Alaris.Core.Time.CRTM006A.Multiply (CRTM006A period, int multiplier) inline static
Multiplies the period by a scalar (friendly alternate for * operator).
Definition at line 99 of file CRTM006A.cs.
References Alaris.Core.Time.CRTM006A.Length, and Alaris.Core.Time.CRTM006A.Unit.
Referenced by Alaris.Core.Time.CRTM006A.operator*(), and Alaris.Core.Time.CRTM006A.operator*().
Negate()
static CRTM006A Alaris.Core.Time.CRTM006A.Negate (CRTM006A period) inline static
Negates the period (friendly alternate for - operator).
Definition at line 73 of file CRTM006A.cs.
References Alaris.Core.Time.CRTM006A.Length, and Alaris.Core.Time.CRTM006A.Unit.
Referenced by Alaris.Core.Time.CRTM006A.operator-().
operator!=()
static bool Alaris.Core.Time.CRTM006A.operator!= (CRTM006A left, CRTM006A right) inline static
Compares two periods for inequality.
Definition at line 133 of file CRTM006A.cs.
References Alaris.Core.Time.CRTM006A.Equals().
operator*() [1/2]
static CRTM006A Alaris.Core.Time.CRTM006A.operator* (CRTM006A period, int multiplier) inline static
Multiplies the period by a scalar.
Definition at line 82 of file CRTM006A.cs.
References Alaris.Core.Time.CRTM006A.Multiply().
operator*() [2/2]
static CRTM006A Alaris.Core.Time.CRTM006A.operator* (int multiplier, CRTM006A period) inline static
Multiplies the period by a scalar.
Definition at line 91 of file CRTM006A.cs.
References Alaris.Core.Time.CRTM006A.Multiply().
operator-()
static CRTM006A Alaris.Core.Time.CRTM006A.operator- (CRTM006A period) inline static
Negates the period.
Definition at line 65 of file CRTM006A.cs.
References Alaris.Core.Time.CRTM006A.Negate().
operator==()
static bool Alaris.Core.Time.CRTM006A.operator== (CRTM006A left, CRTM006A right) inline static
Compares two periods for equality.
Definition at line 125 of file CRTM006A.cs.
References Alaris.Core.Time.CRTM006A.Equals().
ToString()
override string Alaris.Core.Time.CRTM006A.ToString () inline
Definition at line 139 of file CRTM006A.cs.
References Alaris.Core.Time.CRTM006A.Unit.
Weeks()
static CRTM006A Alaris.Core.Time.CRTM006A.Weeks (int n) static
Creates a period of the specified number of weeks.
Years()
static CRTM006A Alaris.Core.Time.CRTM006A.Years (int n) static
Creates a period of the specified number of years.
Property Documentation
Length
int Alaris.Core.Time.CRTM006A.Length get
Gets the length of the period.
Definition at line 23 of file CRTM006A.cs.
Referenced by Alaris.Core.Time.CRTM006A.CRTM006A(), Alaris.Core.Time.CRTM005A.Add(), Alaris.Core.Time.CRTM006A.Equals(), Alaris.Core.Time.CRTM006A.GetHashCode(), Alaris.Core.Time.CRTM006A.Multiply(), and Alaris.Core.Time.CRTM006A.Negate().
Unit
CRTM006AUnit Alaris.Core.Time.CRTM006A.Unit get
Gets the unit of the period.
Definition at line 28 of file CRTM006A.cs.
Referenced by Alaris.Core.Time.CRTM006A.CRTM006A(), Alaris.Core.Time.CRTM006A.Equals(), Alaris.Core.Time.CRTM006A.GetHashCode(), Alaris.Core.Time.CRTM006A.Multiply(), Alaris.Core.Time.CRTM006A.Negate(), and Alaris.Core.Time.CRTM006A.ToString().
The documentation for this struct was generated from the following file:
src/Alaris.Core/Time/CRTM006A.cs