Alaris: Alaris.Strategy.Core.Numerical.STPR010A Class Reference
Alaris.Strategy.Core.Numerical.STPR010A Class Reference
AVX2-accelerated option chain batch pricing for high-throughput Greeks computation. Component ID: STPR010A.
Classes
struct GreeksResult
Greeks results for a batch of options.
Static Public Member Functions
static void ComputeChainGreeks (double spot, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, ReadOnlySpan< bool > isCalls, Span< GreeksResult > results)
Computes all Greeks for an option chain using AVX2 batch processing.
static void ComputeChainPrices (double spot, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, ReadOnlySpan< bool > isCalls, Span< double > prices)
Computes prices only for an option chain (faster than full Greeks).
static void ComputeChainDeltas (double spot, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, ReadOnlySpan< bool > isCalls, Span< double > deltas)
Computes delta hedge ratios for an option chain.
Detailed Description
AVX2-accelerated option chain batch pricing for high-throughput Greeks computation. Component ID: STPR010A.
Provides end-to-end batch pricing for option chains using SIMD acceleration. Processes entire chains of options for a single underlying in one call.
Target use case: Computing Greeks for all strikes/expiries in a chain for delta hedging.
Definition at line 21 of file STPR010A.cs.
Member Function Documentation
ComputeChainDeltas()
static void Alaris.Strategy.Core.Numerical.STPR010A.ComputeChainDeltas (double spot, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, ReadOnlySpan< bool > isCalls, Span< double > deltas) inline static
Computes delta hedge ratios for an option chain.
Definition at line 154 of file STPR010A.cs.
References Alaris.Core.Vectorized.CRVT001A.ComputeDeltasBatch().
ComputeChainGreeks()
static void Alaris.Strategy.Core.Numerical.STPR010A.ComputeChainGreeks (double spot, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, ReadOnlySpan< bool > isCalls, Span< GreeksResult > results) inline static
Computes all Greeks for an option chain using AVX2 batch processing.
Parameters
spot Current spot price of underlying.
strikes Strike prices for each option.
taus Times to expiry (years) for each option.
sigmas Implied volatilities for each option.
r Risk-free rate.
q Dividend yield.
isCalls Call/put flags for each option.
results Output array for Greeks results.
Definition at line 52 of file STPR010A.cs.
References Alaris.Core.Vectorized.CRVT001A.ComputeDeltasBatch(), Alaris.Core.Vectorized.CRVT001A.ComputeGammasBatch(), Alaris.Core.Vectorized.CRVT001A.ComputePricesBatch(), and Alaris.Core.Vectorized.CRVT001A.ComputeVegasBatch().
ComputeChainPrices()
static void Alaris.Strategy.Core.Numerical.STPR010A.ComputeChainPrices (double spot, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, ReadOnlySpan< bool > isCalls, Span< double > prices) inline static
Computes prices only for an option chain (faster than full Greeks).
Definition at line 123 of file STPR010A.cs.
References Alaris.Core.Vectorized.CRVT001A.ComputePricesBatch().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Core/Numerical/STPR010A.cs