Alaris: Alaris.Core.Vectorized.CRVT002A Class Reference
Alaris.Core.Vectorized.CRVT002A Class Reference
AVX2-accelerated transcendental functions for high-performance option pricing. Component ID: CRVT002A.
Static Public Member Functions
static Vector256< double > VectorExp256 (Vector256< double > x)
Computes exp(x) for 4 doubles using AVX2 intrinsics.
static Vector256< double > VectorLog256 (Vector256< double > x)
Computes ln(x) for 4 doubles using AVX2 intrinsics.
static Vector256< double > VectorErf256 (Vector256< double > x)
Computes erf(x) for 4 doubles using AVX2 intrinsics.
static Vector256< double > VectorNormalCDF256 (Vector256< double > x)
Computes Φ(x) = (1 + erf(x/√2))/2 for 4 doubles using AVX2.
static Vector256< double > VectorNormalPDF256 (Vector256< double > x)
Computes φ(x) = exp(-x²/2)/√(2π) for 4 doubles using AVX2.
Properties
static bool IsAvx2Supported [get]
Indicates if AVX2 is supported on this hardware.
static bool IsFmaSupported [get]
Indicates if FMA (Fused Multiply-Add) is supported.
Static Private Member Functions
static Vector256< double > VectorExp256Fallback (Vector256< double > x)
static Vector256< double > VectorLog256Fallback (Vector256< double > x)
static Vector256< double > VectorErf256Fallback (Vector256< double > x)
Static Private Attributes
static readonly Vector256< double > ExpLn2Hi = Vector256.Create(6.93147180369123816490e-01)
static readonly Vector256< double > ExpLn2Lo = Vector256.Create(1.90821492927058770002e-10)
static readonly Vector256< double > ExpInvLn2 = Vector256.Create(1.44269504088896338700e+00)
static readonly Vector256< double > ExpMax = Vector256.Create(709.78271289338397)
static readonly Vector256< double > ExpMin = Vector256.Create(-745.13321910194122)
static readonly Vector256< double > ExpC1 = Vector256.Create(1.0)
static readonly Vector256< double > ExpC2 = Vector256.Create(0.5)
static readonly Vector256< double > ExpC3 = Vector256.Create(1.6666666666666666e-01)
static readonly Vector256< double > ExpC4 = Vector256.Create(4.1666666666666664e-02)
static readonly Vector256< double > ExpC5 = Vector256.Create(8.3333333333333332e-03)
static readonly Vector256< double > ExpC6 = Vector256.Create(1.3888888888888889e-03)
static readonly Vector256< double > LogSqrt2 = Vector256.Create(0.7071067811865476)
static readonly Vector256< double > LogLn2 = Vector256.Create(0.6931471805599453)
static readonly Vector256< double > ErfA1 = Vector256.Create(0.254829592)
static readonly Vector256< double > ErfA2 = Vector256.Create(-0.284496736)
static readonly Vector256< double > ErfA3 = Vector256.Create(1.421413741)
static readonly Vector256< double > ErfA4 = Vector256.Create(-1.453152027)
static readonly Vector256< double > ErfA5 = Vector256.Create(1.061405429)
static readonly Vector256< double > ErfP = Vector256.Create(0.3275911)
static readonly Vector256< double > One = Vector256.Create(1.0)
static readonly Vector256< double > Half = Vector256.Create(0.5)
static readonly Vector256< double > Sqrt2Inv = Vector256.Create(0.7071067811865475244)
static readonly Vector256< double > InvSqrt2Pi = Vector256.Create(0.3989422804014327)
Detailed Description
AVX2-accelerated transcendental functions for high-performance option pricing. Component ID: CRVT002A.
Provides hardware-intrinsic implementations of:
VectorExp256 - Exponential (Cody-Waite reduction + polynomial)
VectorLog256 - Natural logarithm (range reduction + Chebyshev)
VectorErf256 - Error function (Abramowitz-Stegun 7.1.26)
VectorNormalCDF256 - Standard normal CDF
VectorNormalPDF256 - Standard normal PDF
Accuracy: All functions maintain ≤ 2 ULP error for most inputs. Erf maintains ≤ 1.5e-7 max error (same as scalar CRMF001A).
Performance: 4 doubles per operation (256-bit vectors). Falls back to scalar when AVX2 is unavailable.
Definition at line 33 of file CRVT002A.cs.
Member Function Documentation
VectorErf256()
static Vector256< double > Alaris.Core.Vectorized.CRVT002A.VectorErf256 (Vector256< double > x) inline static
Computes erf(x) for 4 doubles using AVX2 intrinsics.
Parameters
x Input vector.
Returns
Vector of erf(x) values in [-1, 1].
Uses Abramowitz-Stegun formula 7.1.26 (same as scalar CRMF001A.Erf). Maximum error: 1.5e-7.
Definition at line 223 of file CRVT002A.cs.
References Alaris.Core.Vectorized.CRVT002A.ErfA1, Alaris.Core.Vectorized.CRVT002A.ErfA2, Alaris.Core.Vectorized.CRVT002A.ErfA3, Alaris.Core.Vectorized.CRVT002A.ErfA4, Alaris.Core.Vectorized.CRVT002A.ErfA5, Alaris.Core.Vectorized.CRVT002A.ErfP, Alaris.Core.Vectorized.CRVT002A.One, Alaris.Core.Vectorized.CRVT002A.VectorErf256Fallback(), and Alaris.Core.Vectorized.CRVT002A.VectorExp256().
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorNormalCDF256().
VectorErf256Fallback()
static Vector256< double > Alaris.Core.Vectorized.CRVT002A.VectorErf256Fallback (Vector256< double > x) inline static private
Definition at line 328 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorErf256().
VectorExp256()
static Vector256< double > Alaris.Core.Vectorized.CRVT002A.VectorExp256 (Vector256< double > x) inline static
Computes exp(x) for 4 doubles using AVX2 intrinsics.
Parameters
x Input vector.
Returns
Vector of exp(x) values.
Uses Cody-Waite range reduction + 6th order polynomial. Handles overflow/underflow correctly.
Definition at line 96 of file CRVT002A.cs.
References Alaris.Core.Vectorized.CRVT002A.ExpC1, Alaris.Core.Vectorized.CRVT002A.ExpC2, Alaris.Core.Vectorized.CRVT002A.ExpC3, Alaris.Core.Vectorized.CRVT002A.ExpC4, Alaris.Core.Vectorized.CRVT002A.ExpC5, Alaris.Core.Vectorized.CRVT002A.ExpC6, Alaris.Core.Vectorized.CRVT002A.ExpInvLn2, Alaris.Core.Vectorized.CRVT002A.ExpLn2Hi, Alaris.Core.Vectorized.CRVT002A.ExpLn2Lo, Alaris.Core.Vectorized.CRVT002A.ExpMax, Alaris.Core.Vectorized.CRVT002A.ExpMin, Alaris.Core.Vectorized.CRVT002A.One, and Alaris.Core.Vectorized.CRVT002A.VectorExp256Fallback().
Referenced by Alaris.Core.Vectorized.CRVT001A.ComputeDeltasVector256(), Alaris.Core.Vectorized.CRVT001A.ComputeGammasVector256(), Alaris.Core.Vectorized.CRVT001A.ComputePricesVector256(), Alaris.Core.Vectorized.CRVT001A.ComputeVegasVector256(), Alaris.Core.Vectorized.CRVT002A.VectorErf256(), Alaris.Core.Vectorized.CRVT001A.VectorExp(), and Alaris.Core.Vectorized.CRVT002A.VectorNormalPDF256().
VectorExp256Fallback()
static Vector256< double > Alaris.Core.Vectorized.CRVT002A.VectorExp256Fallback (Vector256< double > x) inline static private
Definition at line 302 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorExp256().
VectorLog256()
static Vector256< double > Alaris.Core.Vectorized.CRVT002A.VectorLog256 (Vector256< double > x) inline static
Computes ln(x) for 4 doubles using AVX2 intrinsics.
Parameters
x Input vector (must be positive).
Returns
Vector of ln(x) values.
Definition at line 162 of file CRVT002A.cs.
References Alaris.Core.Vectorized.CRVT002A.Half, Alaris.Core.Vectorized.CRVT002A.LogLn2, Alaris.Core.Vectorized.CRVT002A.LogSqrt2, Alaris.Core.Vectorized.CRVT002A.One, and Alaris.Core.Vectorized.CRVT002A.VectorLog256Fallback().
Referenced by Alaris.Core.Vectorized.CRVT001A.ComputeDeltasVector256(), Alaris.Core.Vectorized.CRVT001A.ComputeGammasVector256(), Alaris.Core.Vectorized.CRVT001A.ComputePricesVector256(), Alaris.Core.Vectorized.CRVT001A.ComputeVegasVector256(), and Alaris.Core.Vectorized.CRVT001A.VectorLog().
VectorLog256Fallback()
static Vector256< double > Alaris.Core.Vectorized.CRVT002A.VectorLog256Fallback (Vector256< double > x) inline static private
Definition at line 315 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorLog256().
VectorNormalCDF256()
static Vector256< double > Alaris.Core.Vectorized.CRVT002A.VectorNormalCDF256 (Vector256< double > x) inline static
Computes Φ(x) = (1 + erf(x/√2))/2 for 4 doubles using AVX2.
Definition at line 272 of file CRVT002A.cs.
References Alaris.Core.Vectorized.CRVT002A.Half, Alaris.Core.Vectorized.CRVT002A.One, Alaris.Core.Vectorized.CRVT002A.Sqrt2Inv, and Alaris.Core.Vectorized.CRVT002A.VectorErf256().
Referenced by Alaris.Core.Vectorized.CRVT001A.ComputeDeltasVector256(), and Alaris.Core.Vectorized.CRVT001A.ComputePricesVector256().
VectorNormalPDF256()
static Vector256< double > Alaris.Core.Vectorized.CRVT002A.VectorNormalPDF256 (Vector256< double > x) inline static
Computes φ(x) = exp(-x²/2)/√(2π) for 4 doubles using AVX2.
Definition at line 288 of file CRVT002A.cs.
References Alaris.Core.Vectorized.CRVT002A.InvSqrt2Pi, and Alaris.Core.Vectorized.CRVT002A.VectorExp256().
Referenced by Alaris.Core.Vectorized.CRVT001A.ComputeGammasVector256(), and Alaris.Core.Vectorized.CRVT001A.ComputeVegasVector256().
Member Data Documentation
ErfA1
readonly Vector256<double> Alaris.Core.Vectorized.CRVT002A.ErfA1 = Vector256.Create(0.254829592) static private
Definition at line 69 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorErf256().
ErfA2
readonly Vector256<double> Alaris.Core.Vectorized.CRVT002A.ErfA2 = Vector256.Create(-0.284496736) static private
Definition at line 70 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorErf256().
ErfA3
readonly Vector256<double> Alaris.Core.Vectorized.CRVT002A.ErfA3 = Vector256.Create(1.421413741) static private
Definition at line 71 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorErf256().
ErfA4
readonly Vector256<double> Alaris.Core.Vectorized.CRVT002A.ErfA4 = Vector256.Create(-1.453152027) static private
Definition at line 72 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorErf256().
ErfA5
readonly Vector256<double> Alaris.Core.Vectorized.CRVT002A.ErfA5 = Vector256.Create(1.061405429) static private
Definition at line 73 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorErf256().
ErfP
readonly Vector256<double> Alaris.Core.Vectorized.CRVT002A.ErfP = Vector256.Create(0.3275911) static private
Definition at line 74 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorErf256().
ExpC1
readonly Vector256<double> Alaris.Core.Vectorized.CRVT002A.ExpC1 = Vector256.Create(1.0) static private
Definition at line 57 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorExp256().
ExpC2
readonly Vector256<double> Alaris.Core.Vectorized.CRVT002A.ExpC2 = Vector256.Create(0.5) static private
Definition at line 58 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorExp256().
ExpC3
readonly Vector256<double> Alaris.Core.Vectorized.CRVT002A.ExpC3 = Vector256.Create(1.6666666666666666e-01) static private
Definition at line 59 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorExp256().
ExpC4
readonly Vector256<double> Alaris.Core.Vectorized.CRVT002A.ExpC4 = Vector256.Create(4.1666666666666664e-02) static private
Definition at line 60 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorExp256().
ExpC5
readonly Vector256<double> Alaris.Core.Vectorized.CRVT002A.ExpC5 = Vector256.Create(8.3333333333333332e-03) static private
Definition at line 61 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorExp256().
ExpC6
readonly Vector256<double> Alaris.Core.Vectorized.CRVT002A.ExpC6 = Vector256.Create(1.3888888888888889e-03) static private
Definition at line 62 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorExp256().
ExpInvLn2
readonly Vector256<double> Alaris.Core.Vectorized.CRVT002A.ExpInvLn2 = Vector256.Create(1.44269504088896338700e+00) static private
Definition at line 52 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorExp256().
ExpLn2Hi
readonly Vector256<double> Alaris.Core.Vectorized.CRVT002A.ExpLn2Hi = Vector256.Create(6.93147180369123816490e-01) static private
Definition at line 50 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorExp256().
ExpLn2Lo
readonly Vector256<double> Alaris.Core.Vectorized.CRVT002A.ExpLn2Lo = Vector256.Create(1.90821492927058770002e-10) static private
Definition at line 51 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorExp256().
ExpMax
readonly Vector256<double> Alaris.Core.Vectorized.CRVT002A.ExpMax = Vector256.Create(709.78271289338397) static private
Definition at line 53 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorExp256().
ExpMin
readonly Vector256<double> Alaris.Core.Vectorized.CRVT002A.ExpMin = Vector256.Create(-745.13321910194122) static private
Definition at line 54 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorExp256().
Half
readonly Vector256<double> Alaris.Core.Vectorized.CRVT002A.Half = Vector256.Create(0.5) static private
Definition at line 78 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorLog256(), and Alaris.Core.Vectorized.CRVT002A.VectorNormalCDF256().
InvSqrt2Pi
readonly Vector256<double> Alaris.Core.Vectorized.CRVT002A.InvSqrt2Pi = Vector256.Create(0.3989422804014327) static private
Definition at line 80 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorNormalPDF256().
LogLn2
readonly Vector256<double> Alaris.Core.Vectorized.CRVT002A.LogLn2 = Vector256.Create(0.6931471805599453) static private
Definition at line 66 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorLog256().
LogSqrt2
readonly Vector256<double> Alaris.Core.Vectorized.CRVT002A.LogSqrt2 = Vector256.Create(0.7071067811865476) static private
Definition at line 65 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorLog256().
One
readonly Vector256<double> Alaris.Core.Vectorized.CRVT002A.One = Vector256.Create(1.0) static private
Definition at line 77 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorErf256(), Alaris.Core.Vectorized.CRVT002A.VectorExp256(), Alaris.Core.Vectorized.CRVT002A.VectorLog256(), and Alaris.Core.Vectorized.CRVT002A.VectorNormalCDF256().
Sqrt2Inv
readonly Vector256<double> Alaris.Core.Vectorized.CRVT002A.Sqrt2Inv = Vector256.Create(0.7071067811865475244) static private
Definition at line 79 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT002A.VectorNormalCDF256().
Property Documentation
IsAvx2Supported
bool Alaris.Core.Vectorized.CRVT002A.IsAvx2Supported static get
Indicates if AVX2 is supported on this hardware.
Definition at line 38 of file CRVT002A.cs.
Referenced by Alaris.Core.Vectorized.CRVT001A.ComputeDeltasBatch(), Alaris.Core.Vectorized.CRVT001A.ComputeGammasBatch(), Alaris.Core.Vectorized.CRVT001A.ComputePricesBatch(), Alaris.Core.Vectorized.CRVT001A.ComputeVegasBatch(), Alaris.Core.Vectorized.CRVT001A.VectorExp(), and Alaris.Core.Vectorized.CRVT001A.VectorLog().
IsFmaSupported
bool Alaris.Core.Vectorized.CRVT002A.IsFmaSupported static get
Indicates if FMA (Fused Multiply-Add) is supported.
Definition at line 43 of file CRVT002A.cs.
The documentation for this class was generated from the following file:
src/Alaris.Core/Vectorized/CRVT002A.cs