Alaris: Alaris.Strategy.Core.STIV001A Class Reference
Alaris.Strategy.Core.STIV001A Class Reference sealed
Implements the Heston (1993) stochastic volatility model for implied volatility. Stock price dynamics under risk-neutral measure Q: dS/S = (r - d)dt + sqrt(V)*dW_S dV = kappa*(theta - V)dt + sigma_v*sqrt(V)*dW_V corr(dW_S, dW_V) = rho Where: V = instantaneous variance theta = long-run variance (mean reversion level) kappa = mean reversion speed sigma_v = volatility of volatility (vol-of-vol) rho = correlation between stock and variance The model captures:
Public Member Functions
STIV001A (HestonParameters parameters)
double ComputeTheoreticalIV (double spot, double strike, double timeToExpiry)
Computes theoretical implied volatility using characteristic function approach. PRODUCTION VERSION: Uses full semi-analytical pricing with Fourier inversion and Newton-Raphson IV solving.
double ComputeTheoreticalIVApproximate (double spot, double strike, double timeToExpiry)
Computes theoretical implied volatility using moment-matching approximation. LEGACY VERSION: Fast approximation for educational/comparison purposes. For production use, prefer ComputeTheoreticalIV() which uses full pricing.
Complex CharacteristicFunction (Complex u, double t)
Computes the Heston characteristic function. This is the core of the semi-analytical pricing formula.
int double TheoreticalIV[] ComputeSTTM001A (double spot, double strike, int[] dtePoints)
double double TheoreticalIV[] ComputeSmile (double spot, double[] strikes, double timeToExpiry)
Static Public Member Functions
static HestonParameters Calibrate (double spot, IReadOnlyList<(double Strike, int DTE, double MarketIV)> marketData, double riskFreeRate, double dividendYield)
Calibrates Heston parameters from market IV surface using Levenberg-Marquardt optimization. PRODUCTION VERSION: Uses nonlinear least squares optimization for accurate parameter estimation.
Public Attributes
int DTE
Computes the IV term structure using parallel computation.
double Strike
Computes the IV smile across strikes using parallel computation.
Private Member Functions
double ComputeExpectedIntegratedVariance (double t)
Computes expected integrated variance E[int_0^T V_s ds].
double ComputeSkewAdjustment (double logMoneyness, double timeToExpiry)
Computes skew adjustment based on correlation.
double ComputeSmileAdjustment (double logMoneyness, double timeToExpiry)
Computes smile curvature from vol-of-vol.
Static Private Member Functions
static HestonParameters CalibrateGridSearch (double spot, IReadOnlyList<(double Strike, int DTE, double MarketIV)> marketData, double riskFreeRate, double dividendYield)
Calibrates Heston parameters using parallel grid search. LEGACY VERSION: Used as fallback when LM optimization fails. For production, prefer Calibrate() which uses Levenberg-Marquardt.
static double ComputeCalibrationError (STIV001A model, double spot, IReadOnlyList<(double Strike, int DTE, double MarketIV)> marketData)
static void ValidateInputs (double spot, double strike, double timeToExpiry)
Private Attributes
readonly HestonParameters _params
Detailed Description
Implements the Heston (1993) stochastic volatility model for implied volatility. Stock price dynamics under risk-neutral measure Q: dS/S = (r - d)dt + sqrt(V)*dW_S dV = kappa*(theta - V)dt + sigma_v*sqrt(V)*dW_V corr(dW_S, dW_V) = rho Where: V = instantaneous variance theta = long-run variance (mean reversion level) kappa = mean reversion speed sigma_v = volatility of volatility (vol-of-vol) rho = correlation between stock and variance The model captures:
Volatility clustering (mean reversion)
Leverage effect (negative correlation)
Implied volatility smile/skew Martingale condition: The drift (r-d) ensures discounted stock price is a martingale. Feller condition: 2*kappa*theta > sigma_v^2 ensures variance stays positive. Reference: "A Closed-Form Solution for Options with Stochastic Volatility with Applications to Bond and Currency Options" S.L. Heston (1993), Review of Financial Studies
Definition at line 164 of file STIV001A.cs.
Constructor & Destructor Documentation
STIV001A()
Alaris.Strategy.Core.STIV001A.STIV001A (HestonParameters parameters) inline
Definition at line 168 of file STIV001A.cs.
References Alaris.Strategy.Core.STIV001A._params, Alaris.Strategy.Core.ValidationResult.ThrowIfInvalid(), and Alaris.Strategy.Core.HestonParameters.Validate().
Member Function Documentation
Calibrate()
static HestonParameters Alaris.Strategy.Core.STIV001A.Calibrate (double spot, IReadOnlyList<(double Strike, int DTE, double MarketIV)> marketData, double riskFreeRate, double dividendYield) inline static
Calibrates Heston parameters from market IV surface using Levenberg-Marquardt optimization. PRODUCTION VERSION: Uses nonlinear least squares optimization for accurate parameter estimation.
Definition at line 345 of file STIV001A.cs.
References Alaris.Strategy.Core.STIV001A.ComputeTheoreticalIV(), Alaris.Strategy.Core.Numerical.OptimizationResult.Converged, Alaris.Strategy.Calendar.TradingCalendarDefaults.DteToYears(), Alaris.Strategy.Core.ValidationResult.IsValid, Alaris.Strategy.Core.Numerical.OptimizationResult.OptimalParameters, and Alaris.Strategy.Core.HestonParameters.Validate().
CalibrateGridSearch()
static HestonParameters Alaris.Strategy.Core.STIV001A.CalibrateGridSearch (double spot, IReadOnlyList<(double Strike, int DTE, double MarketIV)> marketData, double riskFreeRate, double dividendYield) inline static private
Calibrates Heston parameters using parallel grid search. LEGACY VERSION: Used as fallback when LM optimization fails. For production, prefer Calibrate() which uses Levenberg-Marquardt.
Definition at line 460 of file STIV001A.cs.
References Alaris.Strategy.Core.HestonParameters.DefaultEquity, Alaris.Strategy.Core.ValidationResult.IsValid, and Alaris.Strategy.Core.HestonParameters.Validate().
CharacteristicFunction()
Complex Alaris.Strategy.Core.STIV001A.CharacteristicFunction (Complex u, double t) inline
Computes the Heston characteristic function. This is the core of the semi-analytical pricing formula.
Parameters
u Complex frequency parameter.
t Time to maturity.
Returns
Characteristic function value.
Definition at line 261 of file STIV001A.cs.
References Alaris.Strategy.Core.STIV001A._params, Alaris.Strategy.Core.HestonParameters.DividendYield, Alaris.Strategy.Core.HestonParameters.Kappa, Alaris.Strategy.Core.HestonParameters.Rho, Alaris.Strategy.Core.HestonParameters.RiskFreeRate, Alaris.Strategy.Core.HestonParameters.SigmaV, Alaris.Strategy.Core.HestonParameters.Theta, and Alaris.Strategy.Core.HestonParameters.V0.
ComputeCalibrationError()
static double Alaris.Strategy.Core.STIV001A.ComputeCalibrationError (STIV001A model, double spot, IReadOnlyList<(double Strike, int DTE, double MarketIV)> marketData) inline static private
Definition at line 521 of file STIV001A.cs.
References Alaris.Strategy.Core.STIV001A.ComputeTheoreticalIV(), and Alaris.Strategy.Calendar.TradingCalendarDefaults.DteToYears().
ComputeExpectedIntegratedVariance()
double Alaris.Strategy.Core.STIV001A.ComputeExpectedIntegratedVariance (double t) inline private
Computes expected integrated variance E[int_0^T V_s ds].
Definition at line 225 of file STIV001A.cs.
References Alaris.Strategy.Core.STIV001A._params, Alaris.Strategy.Core.HestonParameters.Kappa, and Alaris.Strategy.Core.HestonParameters.Theta.
Referenced by Alaris.Strategy.Core.STIV001A.ComputeTheoreticalIVApproximate().
ComputeSkewAdjustment()
double Alaris.Strategy.Core.STIV001A.ComputeSkewAdjustment (double logMoneyness, double timeToExpiry) inline private
Computes skew adjustment based on correlation.
Definition at line 236 of file STIV001A.cs.
References Alaris.Strategy.Core.STIV001A._params, and Alaris.Strategy.Core.HestonParameters.V0.
Referenced by Alaris.Strategy.Core.STIV001A.ComputeTheoreticalIVApproximate().
ComputeSmile()
double double TheoreticalIV[] Alaris.Strategy.Core.STIV001A.ComputeSmile (double spot, double[] strikes, double timeToExpiry) inline
Definition at line 323 of file STIV001A.cs.
ComputeSmileAdjustment()
double Alaris.Strategy.Core.STIV001A.ComputeSmileAdjustment (double logMoneyness, double timeToExpiry) inline private
Computes smile curvature from vol-of-vol.
Definition at line 246 of file STIV001A.cs.
References Alaris.Strategy.Core.STIV001A._params, and Alaris.Strategy.Core.HestonParameters.SigmaV.
Referenced by Alaris.Strategy.Core.STIV001A.ComputeTheoreticalIVApproximate().
ComputeSTTM001A()
int double TheoreticalIV[] Alaris.Strategy.Core.STIV001A.ComputeSTTM001A (double spot, double strike, int[] dtePoints) inline
Definition at line 294 of file STIV001A.cs.
References Alaris.Strategy.Core.STIV001A.ComputeTheoreticalIV(), Alaris.Strategy.Core.STIV001A.DTE, and Alaris.Strategy.Calendar.TradingCalendarDefaults.DteToYears().
ComputeTheoreticalIV()
double Alaris.Strategy.Core.STIV001A.ComputeTheoreticalIV (double spot, double strike, double timeToExpiry) inline
Computes theoretical implied volatility using characteristic function approach. PRODUCTION VERSION: Uses full semi-analytical pricing with Fourier inversion and Newton-Raphson IV solving.
Parameters
spot Current spot price.
strike Strike price.
timeToExpiry Time to expiry in years.
Returns
Implied volatility from Heston model.
Definition at line 184 of file STIV001A.cs.
References Alaris.Strategy.Core.STIV001A._params, Alaris.Strategy.Core.STPR003A.ComputeImpliedVolatility(), and Alaris.Strategy.Core.STIV001A.ValidateInputs().
Referenced by Alaris.Strategy.Core.STIV001A.Calibrate(), Alaris.Strategy.Core.STIV001A.ComputeCalibrationError(), Alaris.Strategy.Core.STIV003A.ComputeModelIVs(), and Alaris.Strategy.Core.STIV001A.ComputeSTTM001A().
ComputeTheoreticalIVApproximate()
double Alaris.Strategy.Core.STIV001A.ComputeTheoreticalIVApproximate (double spot, double strike, double timeToExpiry) inline
Computes theoretical implied volatility using moment-matching approximation. LEGACY VERSION: Fast approximation for educational/comparison purposes. For production use, prefer ComputeTheoreticalIV() which uses full pricing.
Parameters
spot Current spot price.
strike Strike price.
timeToExpiry Time to expiry in years.
Returns
Approximate implied volatility.
Definition at line 201 of file STIV001A.cs.
References Alaris.Strategy.Core.STIV001A.ComputeExpectedIntegratedVariance(), Alaris.Strategy.Core.STIV001A.ComputeSkewAdjustment(), Alaris.Strategy.Core.STIV001A.ComputeSmileAdjustment(), and Alaris.Strategy.Core.STIV001A.ValidateInputs().
ValidateInputs()
static void Alaris.Strategy.Core.STIV001A.ValidateInputs (double spot, double strike, double timeToExpiry) inline static private
Definition at line 539 of file STIV001A.cs.
Referenced by Alaris.Strategy.Core.STIV001A.ComputeTheoreticalIV(), and Alaris.Strategy.Core.STIV001A.ComputeTheoreticalIVApproximate().
Member Data Documentation
_params
readonly HestonParameters Alaris.Strategy.Core.STIV001A._params private
Definition at line 166 of file STIV001A.cs.
Referenced by Alaris.Strategy.Core.STIV001A.STIV001A(), Alaris.Strategy.Core.STIV001A.CharacteristicFunction(), Alaris.Strategy.Core.STIV001A.ComputeExpectedIntegratedVariance(), Alaris.Strategy.Core.STIV001A.ComputeSkewAdjustment(), Alaris.Strategy.Core.STIV001A.ComputeSmileAdjustment(), and Alaris.Strategy.Core.STIV001A.ComputeTheoreticalIV().
DTE
int Alaris.Strategy.Core.STIV001A.DTE
Computes the IV term structure using parallel computation.
Definition at line 294 of file STIV001A.cs.
Referenced by Alaris.Strategy.Core.STIV001A.ComputeSTTM001A().
Strike
double Alaris.Strategy.Core.STIV001A.Strike
Computes the IV smile across strikes using parallel computation.
Definition at line 323 of file STIV001A.cs.
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Core/STIV001A.cs