Alaris: Alaris.Host.Application.Cli.Commands.Data.CLdt002A Class Reference
Alaris.Host.Application.Cli.Commands.Data.CLdt002A Class Reference sealed
Shows data coverage and freshness for sessions. Component ID: CLdt002A.
Public Member Functions
override async Task< int > ExecuteAsync (CommandContext context, DataStatusSettings settings)
Detailed Description
Shows data coverage and freshness for sessions. Component ID: CLdt002A.
Definition at line 15 of file CLdt002A.cs.
Member Function Documentation
ExecuteAsync()
override async Task< int > Alaris.Host.Application.Cli.Commands.Data.CLdt002A.ExecuteAsync (CommandContext context, DataStatusSettings settings) inline
Definition at line 17 of file CLdt002A.cs.
References Alaris.Host.Application.Cli.Infrastructure.CLif003A.Error(), Alaris.Host.Application.Cli.Infrastructure.CLif003A.Info(), Alaris.Host.Application.Cli.Settings.DataStatusSettings.SessionId, and Alaris.Host.Application.Cli.Infrastructure.CLif003A.Warning().
The documentation for this class was generated from the following file:
src/Alaris.Host/Application/Cli/Commands/Data/CLdt002A.cs