Alaris: Alaris.Infrastructure.Data.Bridge.AlarisDataBridge Class Reference
Alaris.Infrastructure.Data.Bridge.AlarisDataBridge Class Reference sealed
Bridges Alaris data providers to Lean engine's data infrastructure. Component ID: DTbr001A.
Public Member Functions
AlarisDataBridge (DTpr003A marketDataProvider, DTpr004A earningsProvider, DTpr005A riskFreeRateProvider, IReadOnlyList< DTqc002A > validators, ILogger< AlarisDataBridge > logger)
Initializes a new instance of the AlarisDataBridge class.
void SetSessionDataPath (string sessionDataPath)
Sets the session data path for loading cached data (options, historical bars, etc.). Call this before using the bridge in backtest mode.
async Task< MarketDataSnapshot > GetMarketDataSnapshotAsync (string symbol, DateTime? evaluationDate=null, CancellationToken cancellationToken=default)
Gets complete market data snapshot for strategy evaluation.
Task< OptionChainSnapshot > GetOptionChainSnapshotAsync (string symbol, DateTime evaluationDate, CancellationToken cancellationToken=default)
Gets an option chain snapshot for a given symbol and evaluation date. Uses session cache when configured.
async Task SaveOptionChainCacheAsync (string symbol, OptionChainSnapshot snapshot, CancellationToken cancellationToken=default)
Saves option chain snapshot to binary cache file.
async Task< IReadOnlyList< string > > GetSymbolsWithUpcomingEarningsAsync (DateTime startDate, DateTime endDate, CancellationToken cancellationToken=default)
Gets all symbols with upcoming earnings in date range. Useful for universe selection in Lean algorithm.
async Task< bool > MeetsBasicCriteriaAsync (string symbol, CancellationToken cancellationToken=default)
Validates if a symbol meets basic criteria for strategy evaluation. Used for pre-filtering universe before expensive data fetches.
Private Member Functions
async Task< OptionChainSnapshot > GetOptionChainWithCacheFallbackAsync (string symbol, DateTime evaluationDate, CancellationToken cancellationToken)
Gets option chain with cache fallback for backtest mode. Loads from session cache if available, otherwise falls back to live API. Supports three cache formats:
async Task< OptionChainSnapshot?> FindNearestCacheAsync (string optionsDir, string symbolLower, DateTime evaluationDate, CancellationToken cancellationToken)
Finds the nearest earlier cached options file for a symbol.
async Task< OptionChainSnapshot?> LoadBinaryCacheAsync (string path, CancellationToken cancellationToken)
Loads option chain snapshot from binary cache file. Uses zero-allocation deserialization via DTsr001A.
async Task< IReadOnlyList< PriceBar > > GetHistoricalBarsForRvCalculationAsync (string symbol, DateTime evaluationDate, CancellationToken cancellationToken)
Gets historical bars for Yang-Zhang RV calculation (minimum 30 days).
async Task<(EarningsEvent? next, IReadOnlyList< EarningsEvent > historical)> GetEarningsDataAsync (string symbol, DateTime evaluationDate, CancellationToken cancellationToken)
Gets earnings data (next event + historical for Leung-Santoli).
IReadOnlyList< DataQualityResult > RunDataQualityValidation (MarketDataSnapshot snapshot)
Runs data quality validation pipeline.
Private Attributes
readonly DTpr003A _marketDataProvider
readonly DTpr004A _earningsProvider
readonly DTpr005A _riskFreeRateProvider
readonly IReadOnlyList< DTqc002A > _validators
readonly ILogger< AlarisDataBridge > _logger
string? _sessionDataPath
Static Private Attributes
static readonly JsonSerializerOptions JsonOptions = new() { PropertyNameCaseInsensitive = true }
Detailed Description
Bridges Alaris data providers to Lean engine's data infrastructure. Component ID: DTbr001A.
Responsibilities:
Aggregates data from multiple providers (Polygon, IBKR)
Runs data quality validation pipeline
Provides unified MarketDataSnapshot for strategy evaluation
Integrates with Lean's SubscriptionDataSource when needed
Usage in Lean algorithm: var bridge = new AlarisDataBridge(providers, validators, logger); var snapshot = await bridge.GetMarketDataSnapshotAsync("AAPL");
Definition at line 31 of file DTbr001A.cs.
Constructor & Destructor Documentation
AlarisDataBridge()
Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.AlarisDataBridge (DTpr003A marketDataProvider, DTpr004A earningsProvider, DTpr005A riskFreeRateProvider, IReadOnlyList< DTqc002A > validators, ILogger< AlarisDataBridge > logger) inline
Initializes a new instance of the AlarisDataBridge class.
Parameters
marketDataProvider Market data provider (Polygon).
earningsProvider Earnings calendar provider.
riskFreeRateProvider Risk-free rate provider.
validators Data quality validators.
logger Logger instance.
Definition at line 51 of file DTbr001A.cs.
References Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._earningsProvider, Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._logger, Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._marketDataProvider, Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._riskFreeRateProvider, and Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._validators.
Member Function Documentation
FindNearestCacheAsync()
async Task< OptionChainSnapshot?> Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.FindNearestCacheAsync (string optionsDir, string symbolLower, DateTime evaluationDate, CancellationToken cancellationToken) inline private
Finds the nearest earlier cached options file for a symbol.
Definition at line 349 of file DTbr001A.cs.
References Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._logger, Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.JsonOptions, and Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.LoadBinaryCacheAsync().
Referenced by Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetOptionChainWithCacheFallbackAsync().
GetEarningsDataAsync()
async Task<(EarningsEvent? next, IReadOnlyList< EarningsEvent > historical)> Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetEarningsDataAsync (string symbol, DateTime evaluationDate, CancellationToken cancellationToken) inline private
Gets earnings data (next event + historical for Leung-Santoli).
Parameters
symbol The symbol to fetch earnings for.
evaluationDate The evaluation date (simulation time for backtests).
cancellationToken Cancellation token.
Definition at line 503 of file DTbr001A.cs.
References Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._earningsProvider, Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._logger, Alaris.Infrastructure.Data.Model.EarningsEvent.Date, Alaris.Infrastructure.Data.Provider.DTpr004A.GetHistoricalEarningsAsync(), and Alaris.Infrastructure.Data.Provider.DTpr004A.GetUpcomingEarningsAsync().
Referenced by Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetMarketDataSnapshotAsync().
GetHistoricalBarsForRvCalculationAsync()
async Task< IReadOnlyList< PriceBar > > Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetHistoricalBarsForRvCalculationAsync (string symbol, DateTime evaluationDate, CancellationToken cancellationToken) inline private
Gets historical bars for Yang-Zhang RV calculation (minimum 30 days).
Definition at line 472 of file DTbr001A.cs.
References Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._logger, Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._marketDataProvider, and Alaris.Infrastructure.Data.Provider.DTpr003A.GetHistoricalBarsAsync().
Referenced by Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetMarketDataSnapshotAsync().
GetMarketDataSnapshotAsync()
async Task< MarketDataSnapshot > Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetMarketDataSnapshotAsync (string symbol, DateTime? evaluationDate = null, CancellationToken cancellationToken = default) inline
Gets complete market data snapshot for strategy evaluation.
Parameters
symbol The symbol to evaluate.
evaluationDate The date for data evaluation (use LEAN's simulation time for backtests).
cancellationToken Cancellation token.
Returns
Validated market data snapshot.
Exceptions
InvalidOperationException If data quality validation fails.
Definition at line 84 of file DTbr001A.cs.
References Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._logger, Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._marketDataProvider, Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._riskFreeRateProvider, Alaris.Infrastructure.Data.Provider.DTpr003A.GetAverageVolume30DayAsync(), Alaris.Infrastructure.Data.Provider.DTpr005A.GetCurrentRateAsync(), Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetEarningsDataAsync(), Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetHistoricalBarsForRvCalculationAsync(), Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetOptionChainWithCacheFallbackAsync(), Alaris.Infrastructure.Data.Provider.DTpr003A.GetSpotPriceAsync(), and Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.RunDataQualityValidation().
GetOptionChainSnapshotAsync()
Task< OptionChainSnapshot > Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetOptionChainSnapshotAsync (string symbol, DateTime evaluationDate, CancellationToken cancellationToken = default) inline
Gets an option chain snapshot for a given symbol and evaluation date. Uses session cache when configured.
Definition at line 217 of file DTbr001A.cs.
References Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetOptionChainWithCacheFallbackAsync().
GetOptionChainWithCacheFallbackAsync()
async Task< OptionChainSnapshot > Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetOptionChainWithCacheFallbackAsync (string symbol, DateTime evaluationDate, CancellationToken cancellationToken) inline private
Gets option chain with cache fallback for backtest mode. Loads from session cache if available, otherwise falls back to live API. Supports three cache formats:
Date-specific: {symbol}_{yyyyMMdd}.sbe/.json (preferred for multi-date backtests)
Single-file binary: {symbol}.sbe
Single-file JSON: {symbol}.json (legacy) When exact date match is not found, uses the nearest earlier cached date.
Definition at line 234 of file DTbr001A.cs.
References Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._logger, Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._marketDataProvider, Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._sessionDataPath, Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.FindNearestCacheAsync(), Alaris.Infrastructure.Data.Provider.DTpr003A.GetOptionChainAsync(), Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.JsonOptions, and Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.LoadBinaryCacheAsync().
Referenced by Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetMarketDataSnapshotAsync(), and Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetOptionChainSnapshotAsync().
GetSymbolsWithUpcomingEarningsAsync()
async Task< IReadOnlyList< string > > Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetSymbolsWithUpcomingEarningsAsync (DateTime startDate, DateTime endDate, CancellationToken cancellationToken = default) inline
Gets all symbols with upcoming earnings in date range. Useful for universe selection in Lean algorithm.
Definition at line 603 of file DTbr001A.cs.
References Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._earningsProvider, Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._logger, and Alaris.Infrastructure.Data.Provider.DTpr004A.GetSymbolsWithEarningsAsync().
LoadBinaryCacheAsync()
async Task< OptionChainSnapshot?> Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.LoadBinaryCacheAsync (string path, CancellationToken cancellationToken) inline private
Loads option chain snapshot from binary cache file. Uses zero-allocation deserialization via DTsr001A.
Definition at line 429 of file DTbr001A.cs.
References Alaris.Infrastructure.Data.Serialization.DTsr001A.DecodeOptionChainSnapshot(), Alaris.Infrastructure.Protocol.Buffers.PLBF001A.LargeBufferSize, and Alaris.Infrastructure.Protocol.Buffers.PLBF001A.RentBuffer().
Referenced by Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.FindNearestCacheAsync(), and Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetOptionChainWithCacheFallbackAsync().
MeetsBasicCriteriaAsync()
async Task< bool > Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.MeetsBasicCriteriaAsync (string symbol, CancellationToken cancellationToken = default) inline
Validates if a symbol meets basic criteria for strategy evaluation. Used for pre-filtering universe before expensive data fetches.
Definition at line 626 of file DTbr001A.cs.
References Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._earningsProvider, Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._logger, Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._marketDataProvider, Alaris.Infrastructure.Data.Provider.DTpr003A.GetAverageVolume30DayAsync(), and Alaris.Infrastructure.Data.Provider.DTpr004A.GetUpcomingEarningsAsync().
RunDataQualityValidation()
IReadOnlyList< DataQualityResult > Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.RunDataQualityValidation (MarketDataSnapshot snapshot) inline private
Runs data quality validation pipeline.
Definition at line 563 of file DTbr001A.cs.
References Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._logger, Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._validators, and Alaris.Infrastructure.Data.Model.MarketDataSnapshot.Symbol.
Referenced by Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetMarketDataSnapshotAsync().
SaveOptionChainCacheAsync()
async Task Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.SaveOptionChainCacheAsync (string symbol, OptionChainSnapshot snapshot, CancellationToken cancellationToken = default) inline
Saves option chain snapshot to binary cache file.
Definition at line 446 of file DTbr001A.cs.
References Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._logger, Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._sessionDataPath, Alaris.Infrastructure.Data.Model.OptionChainSnapshot.Contracts, Alaris.Infrastructure.Data.Serialization.DTsr001A.EncodeOptionChainSnapshot(), Alaris.Infrastructure.Protocol.Buffers.PLBF001A.LargeBufferSize, and Alaris.Infrastructure.Protocol.Buffers.PLBF001A.RentBuffer().
SetSessionDataPath()
void Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.SetSessionDataPath (string sessionDataPath) inline
Sets the session data path for loading cached data (options, historical bars, etc.). Call this before using the bridge in backtest mode.
Parameters
sessionDataPath Path to the session's data folder.
Definition at line 70 of file DTbr001A.cs.
References Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._logger, and Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._sessionDataPath.
Referenced by Alaris.Algorithm.STLN001A.InitialiseDataProviders().
Member Data Documentation
_earningsProvider
readonly DTpr004A Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._earningsProvider private
Definition at line 34 of file DTbr001A.cs.
Referenced by Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.AlarisDataBridge(), Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetEarningsDataAsync(), Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetSymbolsWithUpcomingEarningsAsync(), and Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.MeetsBasicCriteriaAsync().
_logger
readonly ILogger<AlarisDataBridge> Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._logger private
Definition at line 37 of file DTbr001A.cs.
Referenced by Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.AlarisDataBridge(), Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.FindNearestCacheAsync(), Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetEarningsDataAsync(), Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetHistoricalBarsForRvCalculationAsync(), Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetMarketDataSnapshotAsync(), Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetOptionChainWithCacheFallbackAsync(), Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetSymbolsWithUpcomingEarningsAsync(), Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.MeetsBasicCriteriaAsync(), Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.RunDataQualityValidation(), Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.SaveOptionChainCacheAsync(), and Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.SetSessionDataPath().
_marketDataProvider
readonly DTpr003A Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._marketDataProvider private
Definition at line 33 of file DTbr001A.cs.
Referenced by Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.AlarisDataBridge(), Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetHistoricalBarsForRvCalculationAsync(), Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetMarketDataSnapshotAsync(), Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetOptionChainWithCacheFallbackAsync(), and Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.MeetsBasicCriteriaAsync().
_riskFreeRateProvider
readonly DTpr005A Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._riskFreeRateProvider private
Definition at line 35 of file DTbr001A.cs.
Referenced by Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.AlarisDataBridge(), and Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetMarketDataSnapshotAsync().
_sessionDataPath
string? Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._sessionDataPath private
Definition at line 40 of file DTbr001A.cs.
Referenced by Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetOptionChainWithCacheFallbackAsync(), Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.SaveOptionChainCacheAsync(), and Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.SetSessionDataPath().
_validators
readonly IReadOnlyList<DTqc002A> Alaris.Infrastructure.Data.Bridge.AlarisDataBridge._validators private
Definition at line 36 of file DTbr001A.cs.
Referenced by Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.AlarisDataBridge(), and Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.RunDataQualityValidation().
JsonOptions
readonly JsonSerializerOptions Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.JsonOptions = new() { PropertyNameCaseInsensitive = true } static private
Definition at line 41 of file DTbr001A.cs.
Referenced by Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.FindNearestCacheAsync(), and Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetOptionChainWithCacheFallbackAsync().
The documentation for this class was generated from the following file:
src/Alaris.Infrastructure/Data/Bridge/DTbr001A.cs