Alaris: Alaris.Test.Unit.Core.Math.CRMF002ATests Class Reference
Alaris.Test.Unit.Core.Math.CRMF002ATests Class Reference
Unit tests for CRMF002A characteristic equation solver. Validates mathematical invariants and numerical stability.
Public Member Functions
void SolveCharacteristic_PositiveRates_Lambda1GreaterThanOne ()
void SolveCharacteristic_PositiveRates_RootsSatisfyEquation (double r, double q, double σ)
void SolveCharacteristic_NegativeRates_DoubleBoundaryRegime ()
void SolveCharacteristic_NegativeRates_RootsSatisfyEquation (double r, double q, double σ)
void SolveCharacteristic_VietasFormulas_SumOfRoots (double r, double q, double σ)
void SolveCharacteristic_VietasFormulas_ProductOfRoots (double r, double q, double σ)
void SolveCharacteristic_ZeroRate_HandlesCor ()
void SolveCharacteristic_NearZeroRate_NumericalStability ()
void SolveCharacteristic_InvalidVolatility_Throws ()
void SolveCharacteristic_NegativeVolatility_Throws ()
void SuperHalleyRefine_ConvergesToRoot ()
Static Private Attributes
const double Tolerance = 1e-10
Detailed Description
Unit tests for CRMF002A characteristic equation solver. Validates mathematical invariants and numerical stability.
Definition at line 13 of file CRMF002ATests.cs.
Member Function Documentation
SolveCharacteristic_InvalidVolatility_Throws()
void Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_InvalidVolatility_Throws () inline
Definition at line 175 of file CRMF002ATests.cs.
References Alaris.Core.Math.CRMF002A.SolveCharacteristic().
SolveCharacteristic_NearZeroRate_NumericalStability()
void Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_NearZeroRate_NumericalStability () inline
Definition at line 159 of file CRMF002ATests.cs.
References Alaris.Core.Math.CRMF002A.SolveCharacteristic(), and Alaris.Core.Math.CRMF002A.ValidateRoot().
SolveCharacteristic_NegativeRates_DoubleBoundaryRegime()
void Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_NegativeRates_DoubleBoundaryRegime () inline
Definition at line 54 of file CRMF002ATests.cs.
References Alaris.Core.Math.CRMF002A.SolveCharacteristic(), Alaris.Test.Unit.Core.Math.CRMF002ATests.Tolerance, and Alaris.Core.Math.CRMF002A.ValidateRoot().
SolveCharacteristic_NegativeRates_RootsSatisfyEquation()
void Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_NegativeRates_RootsSatisfyEquation (double r, double q, double σ) inline
Definition at line 81 of file CRMF002ATests.cs.
References Alaris.Core.Math.CRMF002A.SolveCharacteristic(), and Alaris.Core.Math.CRMF002A.ValidateRoot().
SolveCharacteristic_NegativeVolatility_Throws()
void Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_NegativeVolatility_Throws () inline
Definition at line 187 of file CRMF002ATests.cs.
References Alaris.Core.Math.CRMF002A.SolveCharacteristic().
SolveCharacteristic_PositiveRates_Lambda1GreaterThanOne()
void Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_PositiveRates_Lambda1GreaterThanOne () inline
Definition at line 20 of file CRMF002ATests.cs.
References Alaris.Core.Math.CRMF002A.SolveCharacteristic().
SolveCharacteristic_PositiveRates_RootsSatisfyEquation()
void Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_PositiveRates_RootsSatisfyEquation (double r, double q, double σ) inline
Definition at line 39 of file CRMF002ATests.cs.
References Alaris.Core.Math.CRMF002A.SolveCharacteristic(), Alaris.Test.Unit.Core.Math.CRMF002ATests.Tolerance, and Alaris.Core.Math.CRMF002A.ValidateRoot().
SolveCharacteristic_VietasFormulas_ProductOfRoots()
void Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_VietasFormulas_ProductOfRoots (double r, double q, double σ) inline
Definition at line 123 of file CRMF002ATests.cs.
References Alaris.Core.Math.CRMF002A.SolveCharacteristic().
SolveCharacteristic_VietasFormulas_SumOfRoots()
void Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_VietasFormulas_SumOfRoots (double r, double q, double σ) inline
Definition at line 103 of file CRMF002ATests.cs.
References Alaris.Core.Math.CRMF002A.SolveCharacteristic().
SolveCharacteristic_ZeroRate_HandlesCor()
void Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_ZeroRate_HandlesCor () inline
Definition at line 143 of file CRMF002ATests.cs.
References Alaris.Core.Math.CRMF002A.SolveCharacteristic(), Alaris.Test.Unit.Core.Math.CRMF002ATests.Tolerance, and Alaris.Core.Math.CRMF002A.ValidateRoot().
SuperHalleyRefine_ConvergesToRoot()
void Alaris.Test.Unit.Core.Math.CRMF002ATests.SuperHalleyRefine_ConvergesToRoot () inline
Definition at line 203 of file CRMF002ATests.cs.
References Alaris.Core.Math.CRMF002A.SuperHalleyRefine().
Member Data Documentation
Tolerance
const double Alaris.Test.Unit.Core.Math.CRMF002ATests.Tolerance = 1e-10 static private
Definition at line 15 of file CRMF002ATests.cs.
Referenced by Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_NegativeRates_DoubleBoundaryRegime(), Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_PositiveRates_RootsSatisfyEquation(), and Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_ZeroRate_HandlesCor().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/Core/Math/CRMF002ATests.cs