Alaris: Alaris.Test.Integration.TSIN005A Class Reference
Alaris.Test.Integration.TSIN005A Class Reference sealed
TSIN005A: Integration tests for Alaris.Application services.
Public Member Functions
Task InitializeAsync ()
Task DisposeAsync ()
async Task APsv001A_CreateAsync_CreatesSessionWithValidId ()
CreateAsync should create a session with valid ID format.
async Task APsv001A_CreateAsync_CreatesFolderStructure ()
CreateAsync should create required folder structure.
async Task APsv001A_CreateAsync_SavesMetadata ()
CreateAsync should save session.json metadata.
async Task APsv001A_CreateAsync_SetsCorrectDates ()
CreateAsync should set correct dates.
async Task APsv001A_CreateAsync_SetsStatusToCreated ()
CreateAsync should set initial status to Created.
async Task APsv001A_CreateAsync_IncludesSymbols ()
CreateAsync should include symbols when provided.
async Task APsv001A_CreateAsync_RejectsInvalidDateRange ()
CreateAsync should reject invalid date range.
async Task APsv001A_CreateAsync_RejectsSameDates ()
CreateAsync should reject same start and end date.
async Task APsv001A_CreateMultiple_SequenceNumbersIncrease ()
Session sequence numbers should be monotonically increasing.
async Task APsv001A_GetAsync_ReturnsSessionById ()
GetAsync should return session by ID.
async Task APsv001A_GetAsync_ReturnsNullForNonExistent ()
GetAsync should return null for non-existent session.
async Task APsv001A_ListAsync_ReturnsEmptyWhenNoSessions ()
ListAsync should return empty list when no sessions exist.
async Task APsv001A_ListAsync_ReturnsAllSessions ()
ListAsync should return all created sessions.
async Task APsv001A_ListAsync_ReturnsOrderedByCreatedAt ()
ListAsync should return sessions ordered by creation date descending.
async Task APsv001A_UpdateAsync_PersistsStatusChange ()
UpdateAsync should persist status changes.
async Task APsv001A_UpdateAsync_UpdatesTimestamp ()
UpdateAsync should update the UpdatedAt timestamp.
async Task APsv001A_DeleteAsync_RemovesSessionFolder ()
DeleteAsync should remove session folder.
async Task APsv001A_DeleteAsync_RemovesFromIndex ()
DeleteAsync should remove session from index.
async Task APsv001A_DeleteAsync_ThrowsForNonExistent ()
DeleteAsync should throw for non-existent session.
async Task APsv001A_GetDataPath_ReturnsCorrectPath ()
GetDataPath should return correct data folder path.
async Task APsv001A_GetResultsPath_ReturnsCorrectPath ()
GetResultsPath should return correct results folder path.
void APmd001A_IsImmutableRecord ()
Session model should be immutable (record type).
void SessionStatistics_ContainsAllFields ()
Session statistics should have all required fields.
void SessionStatus_HasExpectedValue (SessionStatus status)
SessionStatus should have all expected values.
void SessionStatus_HasSixValues ()
SessionStatus should have exactly 6 values.
async Task SessionId_ContainsCorrectDates ()
Session ID should contain correct dates.
async Task SessionId_HasVariantSuffix ()
Session ID should have variant suffix.
async Task APsv001A_ConcurrentCreation_AllSessionsCreated ()
Creating multiple sessions concurrently should work correctly.
Static Private Member Functions
static int ExtractSequence (string sessionId)
Private Attributes
string _tempSessionsRoot = null!
APsv001A _sessionService = null!
Detailed Description
TSIN005A: Integration tests for Alaris.Application services.
Definition at line 38 of file TSIN005A.cs.
Member Function Documentation
APmd001A_IsImmutableRecord()
void Alaris.Test.Integration.TSIN005A.APmd001A_IsImmutableRecord () inline
Session model should be immutable (record type).
Definition at line 475 of file TSIN005A.cs.
References Alaris.Host.Application.Model.APmd001A.
APsv001A_ConcurrentCreation_AllSessionsCreated()
async Task Alaris.Test.Integration.TSIN005A.APsv001A_ConcurrentCreation_AllSessionsCreated () inline
Creating multiple sessions concurrently should work correctly.
Definition at line 593 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._sessionService, and Alaris.Host.Application.Service.APsv001A.CreateAsync().
APsv001A_CreateAsync_CreatesFolderStructure()
async Task Alaris.Test.Integration.TSIN005A.APsv001A_CreateAsync_CreatesFolderStructure () inline
CreateAsync should create required folder structure.
Definition at line 96 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._sessionService, and Alaris.Host.Application.Service.APsv001A.CreateAsync().
APsv001A_CreateAsync_CreatesSessionWithValidId()
async Task Alaris.Test.Integration.TSIN005A.APsv001A_CreateAsync_CreatesSessionWithValidId () inline
CreateAsync should create a session with valid ID format.
Definition at line 77 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._sessionService, and Alaris.Host.Application.Service.APsv001A.CreateAsync().
APsv001A_CreateAsync_IncludesSymbols()
async Task Alaris.Test.Integration.TSIN005A.APsv001A_CreateAsync_IncludesSymbols () inline
CreateAsync should include symbols when provided.
Definition at line 175 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._sessionService, and Alaris.Host.Application.Service.APsv001A.CreateAsync().
APsv001A_CreateAsync_RejectsInvalidDateRange()
async Task Alaris.Test.Integration.TSIN005A.APsv001A_CreateAsync_RejectsInvalidDateRange () inline
CreateAsync should reject invalid date range.
Definition at line 196 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._sessionService, and Alaris.Host.Application.Service.APsv001A.CreateAsync().
APsv001A_CreateAsync_RejectsSameDates()
async Task Alaris.Test.Integration.TSIN005A.APsv001A_CreateAsync_RejectsSameDates () inline
CreateAsync should reject same start and end date.
Definition at line 211 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._sessionService, and Alaris.Host.Application.Service.APsv001A.CreateAsync().
APsv001A_CreateAsync_SavesMetadata()
async Task Alaris.Test.Integration.TSIN005A.APsv001A_CreateAsync_SavesMetadata () inline
CreateAsync should save session.json metadata.
Definition at line 117 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._sessionService, and Alaris.Host.Application.Service.APsv001A.CreateAsync().
APsv001A_CreateAsync_SetsCorrectDates()
async Task Alaris.Test.Integration.TSIN005A.APsv001A_CreateAsync_SetsCorrectDates () inline
CreateAsync should set correct dates.
Definition at line 139 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._sessionService, and Alaris.Host.Application.Service.APsv001A.CreateAsync().
APsv001A_CreateAsync_SetsStatusToCreated()
async Task Alaris.Test.Integration.TSIN005A.APsv001A_CreateAsync_SetsStatusToCreated () inline
CreateAsync should set initial status to Created.
Definition at line 158 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._sessionService, and Alaris.Host.Application.Service.APsv001A.CreateAsync().
APsv001A_CreateMultiple_SequenceNumbersIncrease()
async Task Alaris.Test.Integration.TSIN005A.APsv001A_CreateMultiple_SequenceNumbersIncrease () inline
Session sequence numbers should be monotonically increasing.
Definition at line 228 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._sessionService, Alaris.Host.Application.Service.APsv001A.CreateAsync(), and Alaris.Test.Integration.TSIN005A.ExtractSequence().
APsv001A_DeleteAsync_RemovesFromIndex()
async Task Alaris.Test.Integration.TSIN005A.APsv001A_DeleteAsync_RemovesFromIndex () inline
DeleteAsync should remove session from index.
Definition at line 406 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._sessionService, Alaris.Host.Application.Service.APsv001A.CreateAsync(), Alaris.Host.Application.Service.APsv001A.DeleteAsync(), and Alaris.Host.Application.Service.APsv001A.ListAsync().
APsv001A_DeleteAsync_RemovesSessionFolder()
async Task Alaris.Test.Integration.TSIN005A.APsv001A_DeleteAsync_RemovesSessionFolder () inline
DeleteAsync should remove session folder.
Definition at line 387 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._sessionService, Alaris.Host.Application.Service.APsv001A.CreateAsync(), and Alaris.Host.Application.Service.APsv001A.DeleteAsync().
APsv001A_DeleteAsync_ThrowsForNonExistent()
async Task Alaris.Test.Integration.TSIN005A.APsv001A_DeleteAsync_ThrowsForNonExistent () inline
DeleteAsync should throw for non-existent session.
Definition at line 424 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._sessionService, and Alaris.Host.Application.Service.APsv001A.DeleteAsync().
APsv001A_GetAsync_ReturnsNullForNonExistent()
async Task Alaris.Test.Integration.TSIN005A.APsv001A_GetAsync_ReturnsNullForNonExistent () inline
GetAsync should return null for non-existent session.
Definition at line 275 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._sessionService, and Alaris.Host.Application.Service.APsv001A.GetAsync().
APsv001A_GetAsync_ReturnsSessionById()
async Task Alaris.Test.Integration.TSIN005A.APsv001A_GetAsync_ReturnsSessionById () inline
GetAsync should return session by ID.
Definition at line 254 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._sessionService, Alaris.Host.Application.Service.APsv001A.CreateAsync(), and Alaris.Host.Application.Service.APsv001A.GetAsync().
APsv001A_GetDataPath_ReturnsCorrectPath()
async Task Alaris.Test.Integration.TSIN005A.APsv001A_GetDataPath_ReturnsCorrectPath () inline
GetDataPath should return correct data folder path.
Definition at line 437 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._sessionService, Alaris.Host.Application.Service.APsv001A.CreateAsync(), and Alaris.Host.Application.Service.APsv001A.GetDataPath().
APsv001A_GetResultsPath_ReturnsCorrectPath()
async Task Alaris.Test.Integration.TSIN005A.APsv001A_GetResultsPath_ReturnsCorrectPath () inline
GetResultsPath should return correct results folder path.
Definition at line 455 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._sessionService, Alaris.Host.Application.Service.APsv001A.CreateAsync(), and Alaris.Host.Application.Service.APsv001A.GetResultsPath().
APsv001A_ListAsync_ReturnsAllSessions()
async Task Alaris.Test.Integration.TSIN005A.APsv001A_ListAsync_ReturnsAllSessions () inline
ListAsync should return all created sessions.
Definition at line 303 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._sessionService, Alaris.Host.Application.Service.APsv001A.CreateAsync(), and Alaris.Host.Application.Service.APsv001A.ListAsync().
APsv001A_ListAsync_ReturnsEmptyWhenNoSessions()
async Task Alaris.Test.Integration.TSIN005A.APsv001A_ListAsync_ReturnsEmptyWhenNoSessions () inline
ListAsync should return empty list when no sessions exist.
Definition at line 290 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._sessionService, and Alaris.Host.Application.Service.APsv001A.ListAsync().
APsv001A_ListAsync_ReturnsOrderedByCreatedAt()
async Task Alaris.Test.Integration.TSIN005A.APsv001A_ListAsync_ReturnsOrderedByCreatedAt () inline
ListAsync should return sessions ordered by creation date descending.
Definition at line 321 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._sessionService, Alaris.Host.Application.Service.APsv001A.CreateAsync(), and Alaris.Host.Application.Service.APsv001A.ListAsync().
APsv001A_UpdateAsync_PersistsStatusChange()
async Task Alaris.Test.Integration.TSIN005A.APsv001A_UpdateAsync_PersistsStatusChange () inline
UpdateAsync should persist status changes.
Definition at line 345 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._sessionService, Alaris.Host.Application.Service.APsv001A.CreateAsync(), Alaris.Host.Application.Service.APsv001A.GetAsync(), and Alaris.Host.Application.Service.APsv001A.UpdateAsync().
APsv001A_UpdateAsync_UpdatesTimestamp()
async Task Alaris.Test.Integration.TSIN005A.APsv001A_UpdateAsync_UpdatesTimestamp () inline
UpdateAsync should update the UpdatedAt timestamp.
Definition at line 364 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._sessionService, Alaris.Host.Application.Service.APsv001A.CreateAsync(), Alaris.Host.Application.Service.APsv001A.GetAsync(), and Alaris.Host.Application.Service.APsv001A.UpdateAsync().
DisposeAsync()
Task Alaris.Test.Integration.TSIN005A.DisposeAsync () inline
Definition at line 54 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._tempSessionsRoot.
ExtractSequence()
static int Alaris.Test.Integration.TSIN005A.ExtractSequence (string sessionId) inline static private
Definition at line 616 of file TSIN005A.cs.
Referenced by Alaris.Test.Integration.TSIN005A.APsv001A_CreateMultiple_SequenceNumbersIncrease().
InitializeAsync()
Task Alaris.Test.Integration.TSIN005A.InitializeAsync () inline
Definition at line 45 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._sessionService, and Alaris.Test.Integration.TSIN005A._tempSessionsRoot.
SessionId_ContainsCorrectDates()
async Task Alaris.Test.Integration.TSIN005A.SessionId_ContainsCorrectDates () inline
Session ID should contain correct dates.
Definition at line 559 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._sessionService, and Alaris.Host.Application.Service.APsv001A.CreateAsync().
SessionId_HasVariantSuffix()
async Task Alaris.Test.Integration.TSIN005A.SessionId_HasVariantSuffix () inline
Session ID should have variant suffix.
Definition at line 577 of file TSIN005A.cs.
References Alaris.Test.Integration.TSIN005A._sessionService, and Alaris.Host.Application.Service.APsv001A.CreateAsync().
SessionStatistics_ContainsAllFields()
void Alaris.Test.Integration.TSIN005A.SessionStatistics_ContainsAllFields () inline
Session statistics should have all required fields.
Definition at line 499 of file TSIN005A.cs.
References Alaris.Host.Application.Model.SessionStatistics.
SessionStatus_HasExpectedValue()
void Alaris.Test.Integration.TSIN005A.SessionStatus_HasExpectedValue (SessionStatus status) inline
SessionStatus should have all expected values.
Definition at line 537 of file TSIN005A.cs.
SessionStatus_HasSixValues()
void Alaris.Test.Integration.TSIN005A.SessionStatus_HasSixValues () inline
SessionStatus should have exactly 6 values.
Definition at line 547 of file TSIN005A.cs.
Member Data Documentation
_sessionService
APsv001A Alaris.Test.Integration.TSIN005A._sessionService = null! private
Definition at line 41 of file TSIN005A.cs.
Referenced by Alaris.Test.Integration.TSIN005A.APsv001A_ConcurrentCreation_AllSessionsCreated(), Alaris.Test.Integration.TSIN005A.APsv001A_CreateAsync_CreatesFolderStructure(), Alaris.Test.Integration.TSIN005A.APsv001A_CreateAsync_CreatesSessionWithValidId(), Alaris.Test.Integration.TSIN005A.APsv001A_CreateAsync_IncludesSymbols(), Alaris.Test.Integration.TSIN005A.APsv001A_CreateAsync_RejectsInvalidDateRange(), Alaris.Test.Integration.TSIN005A.APsv001A_CreateAsync_RejectsSameDates(), Alaris.Test.Integration.TSIN005A.APsv001A_CreateAsync_SavesMetadata(), Alaris.Test.Integration.TSIN005A.APsv001A_CreateAsync_SetsCorrectDates(), Alaris.Test.Integration.TSIN005A.APsv001A_CreateAsync_SetsStatusToCreated(), Alaris.Test.Integration.TSIN005A.APsv001A_CreateMultiple_SequenceNumbersIncrease(), Alaris.Test.Integration.TSIN005A.APsv001A_DeleteAsync_RemovesFromIndex(), Alaris.Test.Integration.TSIN005A.APsv001A_DeleteAsync_RemovesSessionFolder(), Alaris.Test.Integration.TSIN005A.APsv001A_DeleteAsync_ThrowsForNonExistent(), Alaris.Test.Integration.TSIN005A.APsv001A_GetAsync_ReturnsNullForNonExistent(), Alaris.Test.Integration.TSIN005A.APsv001A_GetAsync_ReturnsSessionById(), Alaris.Test.Integration.TSIN005A.APsv001A_GetDataPath_ReturnsCorrectPath(), Alaris.Test.Integration.TSIN005A.APsv001A_GetResultsPath_ReturnsCorrectPath(), Alaris.Test.Integration.TSIN005A.APsv001A_ListAsync_ReturnsAllSessions(), Alaris.Test.Integration.TSIN005A.APsv001A_ListAsync_ReturnsEmptyWhenNoSessions(), Alaris.Test.Integration.TSIN005A.APsv001A_ListAsync_ReturnsOrderedByCreatedAt(), Alaris.Test.Integration.TSIN005A.APsv001A_UpdateAsync_PersistsStatusChange(), Alaris.Test.Integration.TSIN005A.APsv001A_UpdateAsync_UpdatesTimestamp(), Alaris.Test.Integration.TSIN005A.InitializeAsync(), Alaris.Test.Integration.TSIN005A.SessionId_ContainsCorrectDates(), and Alaris.Test.Integration.TSIN005A.SessionId_HasVariantSuffix().
_tempSessionsRoot
string Alaris.Test.Integration.TSIN005A._tempSessionsRoot = null! private
Definition at line 40 of file TSIN005A.cs.
Referenced by Alaris.Test.Integration.TSIN005A.DisposeAsync(), and Alaris.Test.Integration.TSIN005A.InitializeAsync().
The documentation for this class was generated from the following file:
src/Alaris.Test/Integration/TSIN005A.cs