Alaris: Alaris.Strategy.Core.STTM004A Class Reference
Alaris.Strategy.Core.STTM004A Class Reference sealed
Comprehensive time parameter specification for IV models. Handles time-to-expiration, earnings dates, and trading calendar conversions.
Static Public Member Functions
static STTM004A Create (DateTime valuationDate, DateTime expirationDate, DateTime? earningsDate=null)
Creates and validates time parameters.
static STTM004A Create (DateTime valuationDate, DateTime expirationDate, DateTime? earningsDate, TimeConstraints constraints)
Creates and validates time parameters with custom constraints.
static double DteToYears (int dte)
Converts days to expiration to annualized time.
static int YearsToDte (double years)
Converts annualized time to days to expiration.
Static Public Attributes
const double TradingDaysPerYear = 252.0
Trading days per year (US equity markets).
const double TradingHoursPerDay = 6.5
Trading hours per day (6.5 hours for US markets).
const double MinTimeToExpiry = 1.0 / (TradingDaysPerYear * TradingHoursPerDay)
Minimum time to expiry in years (~1 hour).
const double MaxTimeToExpiry = 3.0
Maximum reasonable time to expiry (3 years for LEAPS).
Properties
DateTime ValuationDate [get]
Current valuation date.
DateTime ExpirationDate [get]
Option expiration date.
DateTime? EarningsDate [get]
Earnings announcement date (null if no earnings before expiry).
double TimeToExpiry [get]
Time to expiration in years (T - t).
double? TimeToEarnings [get]
Time to earnings in years (T_e - t), null if no earnings.
int DaysToExpiry [get]
Days to expiration.
int? DaysToEarnings [get]
Days to earnings, null if no earnings before expiry.
bool IsPreEarnings [get]
Whether we are in the pre-earnings regime.
bool IsPostEarnings [get]
Whether we are in the post-earnings regime.
bool HasEarningsBeforeExpiry [get]
Whether earnings fall before option expiration.
Private Member Functions
STTM004A ()
Static Private Member Functions
static int CalculateTradingDays (DateTime start, DateTime end)
Calculates trading days between two dates using production-grade trading calendar. Excludes weekends and US market holidays.
Detailed Description
Comprehensive time parameter specification for IV models. Handles time-to-expiration, earnings dates, and trading calendar conversions.
Definition at line 9 of file STTM004A.cs.
Constructor & Destructor Documentation
STTM004A()
Alaris.Strategy.Core.STTM004A.STTM004A () inline private
Definition at line 81 of file STTM004A.cs.
Member Function Documentation
CalculateTradingDays()
static int Alaris.Strategy.Core.STTM004A.CalculateTradingDays (DateTime start, DateTime end) inline static private
Calculates trading days between two dates using production-grade trading calendar. Excludes weekends and US market holidays.
Definition at line 174 of file STTM004A.cs.
References Alaris.Strategy.Core.STTM003A.GetTradingDays().
Referenced by Alaris.Strategy.Core.STTM004A.Create().
Create() [1/2]
static STTM004A Alaris.Strategy.Core.STTM004A.Create (DateTime valuationDate, DateTime expirationDate, DateTime? earningsDate, TimeConstraints constraints) inline static
Creates and validates time parameters with custom constraints.
Definition at line 102 of file STTM004A.cs.
References Alaris.Strategy.Core.STTM004A.CalculateTradingDays(), Alaris.Strategy.Core.STTM004A.DaysToEarnings, Alaris.Strategy.Core.STTM004A.DaysToExpiry, Alaris.Strategy.Core.STTM004A.EarningsDate, Alaris.Strategy.Core.STTM004A.ExpirationDate, Alaris.Strategy.Core.TimeConstraints.MaxTimeToExpiry, Alaris.Strategy.Core.TimeConstraints.MinTimeToExpiry, Alaris.Strategy.Core.STTM004A.TimeToEarnings, Alaris.Strategy.Core.STTM004A.TimeToExpiry, Alaris.Strategy.Core.STTM004A.TradingDaysPerYear, and Alaris.Strategy.Core.STTM004A.ValuationDate.
Create() [2/2]
static STTM004A Alaris.Strategy.Core.STTM004A.Create (DateTime valuationDate, DateTime expirationDate, DateTime? earningsDate = null) inline static
Creates and validates time parameters.
Parameters
valuationDate Current valuation date.
expirationDate Option expiration date.
earningsDate Optional earnings announcement date.
Returns
Validated time parameters.
Definition at line 90 of file STTM004A.cs.
References Alaris.Strategy.Core.STTM004A.Create(), and Alaris.Strategy.Core.TimeConstraints.Default.
Referenced by Alaris.Strategy.Core.STTM004A.Create(), Alaris.Test.Unit.IVModelTests.MartingaleValidator_Validate_BlackScholes_AlwaysValid(), Alaris.Test.Unit.TSUN024A.ModelSelector_PreEarnings_PrefersJumpModels(), Alaris.Test.Unit.IVModelTests.STIV003A_SelectBestModel_NoEarnings_PrefersHeston(), Alaris.Test.Unit.IVModelTests.STIV003A_SelectBestModel_PreEarnings_PrefersLeungSantoli(), Alaris.Test.Unit.IVModelTests.STIV003A_SelectBestModel_WithMarketData_ComputesFitMetrics(), Alaris.Test.Unit.IVModelTests.STTM002A_ComputeAdjustedIV_NoEarnings_ReturnsBaseIV(), Alaris.Test.Unit.IVModelTests.STTM002A_ComputeAdjustedIV_PreEarnings_ReturnsEarningsIV(), Alaris.Test.Unit.IVModelTests.STTM002A_Detect_NoEarnings_ReturnsNoSTTM002A(), Alaris.Test.Unit.IVModelTests.STTM002A_Detect_PreEarnings_ReturnsPreSTTM002A(), Alaris.Test.Unit.IVModelTests.STTM004A_Create_ExpirationBeforeValuation_Throws(), Alaris.Test.Unit.IVModelTests.STTM004A_Create_ValidDates_ReturnsCorrectParameters(), Alaris.Test.Unit.IVModelTests.STTM004A_Create_WithEarningsAfterExpiry_NoEarningsEffect(), Alaris.Test.Unit.IVModelTests.STTM004A_Create_WithEarningsBeforeExpiry_DetectsPreEarnings(), and Alaris.Test.Unit.IVModelTests.TimeConstraints_ValidatePreEarnings_ValidParameters_ReturnsValid().
DteToYears()
static double Alaris.Strategy.Core.STTM004A.DteToYears (int dte) static
Converts days to expiration to annualized time.
YearsToDte()
static int Alaris.Strategy.Core.STTM004A.YearsToDte (double years) static
Converts annualized time to days to expiration.
Member Data Documentation
MaxTimeToExpiry
const double Alaris.Strategy.Core.STTM004A.MaxTimeToExpiry = 3.0 static
Maximum reasonable time to expiry (3 years for LEAPS).
Definition at line 29 of file STTM004A.cs.
MinTimeToExpiry
const double Alaris.Strategy.Core.STTM004A.MinTimeToExpiry = 1.0 / (TradingDaysPerYear * TradingHoursPerDay) static
Minimum time to expiry in years (~1 hour).
Definition at line 24 of file STTM004A.cs.
TradingDaysPerYear
const double Alaris.Strategy.Core.STTM004A.TradingDaysPerYear = 252.0 static
Trading days per year (US equity markets).
Definition at line 14 of file STTM004A.cs.
Referenced by Alaris.Strategy.Core.STTM004A.Create().
TradingHoursPerDay
const double Alaris.Strategy.Core.STTM004A.TradingHoursPerDay = 6.5 static
Trading hours per day (6.5 hours for US markets).
Definition at line 19 of file STTM004A.cs.
Property Documentation
DaysToEarnings
int? Alaris.Strategy.Core.STTM004A.DaysToEarnings get
Days to earnings, null if no earnings before expiry.
Definition at line 64 of file STTM004A.cs.
Referenced by Alaris.Strategy.Core.STTM004A.Create(), and Alaris.Strategy.Core.TimeConstraints.ValidatePreEarnings().
DaysToExpiry
int Alaris.Strategy.Core.STTM004A.DaysToExpiry get
Days to expiration.
Definition at line 59 of file STTM004A.cs.
Referenced by Alaris.Strategy.Core.STTM004A.Create().
EarningsDate
DateTime? Alaris.Strategy.Core.STTM004A.EarningsDate get
Earnings announcement date (null if no earnings before expiry).
Definition at line 44 of file STTM004A.cs.
Referenced by Alaris.Strategy.Core.STTM004A.Create(), and Alaris.Strategy.Core.STTM002A.Detect().
ExpirationDate
DateTime Alaris.Strategy.Core.STTM004A.ExpirationDate get
Option expiration date.
Definition at line 39 of file STTM004A.cs.
Referenced by Alaris.Strategy.Core.STTM004A.Create().
HasEarningsBeforeExpiry
bool Alaris.Strategy.Core.STTM004A.HasEarningsBeforeExpiry get
Whether earnings fall before option expiration.
Definition at line 79 of file STTM004A.cs.
Referenced by Alaris.Strategy.Core.STTM002A.Detect(), and Alaris.Test.Unit.IVModelTests.STTM004A_Create_WithEarningsAfterExpiry_NoEarningsEffect().
IsPostEarnings
bool Alaris.Strategy.Core.STTM004A.IsPostEarnings get
Whether we are in the post-earnings regime.
Definition at line 74 of file STTM004A.cs.
IsPreEarnings
bool Alaris.Strategy.Core.STTM004A.IsPreEarnings get
Whether we are in the pre-earnings regime.
Definition at line 69 of file STTM004A.cs.
Referenced by Alaris.Strategy.Core.STTM002A.Detect(), Alaris.Test.Unit.IVModelTests.STTM004A_Create_WithEarningsBeforeExpiry_DetectsPreEarnings(), and Alaris.Strategy.Core.TimeConstraints.ValidatePreEarnings().
TimeToEarnings
double? Alaris.Strategy.Core.STTM004A.TimeToEarnings get
Time to earnings in years (T_e - t), null if no earnings.
Definition at line 54 of file STTM004A.cs.
Referenced by Alaris.Strategy.Core.STTM004A.Create().
TimeToExpiry
double Alaris.Strategy.Core.STTM004A.TimeToExpiry get
Time to expiration in years (T - t).
Definition at line 49 of file STTM004A.cs.
Referenced by Alaris.Strategy.Core.LeungSantoliExtensions.ComputePreEarningsIV(), Alaris.Strategy.Core.STTM004A.Create(), and Alaris.Strategy.Core.TimeConstraints.ValidatePreEarnings().
ValuationDate
DateTime Alaris.Strategy.Core.STTM004A.ValuationDate get
Current valuation date.
Definition at line 34 of file STTM004A.cs.
Referenced by Alaris.Strategy.Core.STTM004A.Create(), and Alaris.Test.Unit.IVModelTests.STTM004A_Create_ValidDates_ReturnsCorrectParameters().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Core/STTM004A.cs