Alaris: Alaris.Test.Unit.DTqc001ATests Class Reference
Alaris.Test.Unit.DTqc001ATests Class Reference sealed
Unit tests for PriceReasonablenessValidator (DTqc001A). Validates price data quality rules.
Public Member Functions
DTqc001ATests ()
void Dispose ()
void ComponentId_ShouldBe_DTqc001A ()
void Validate_ValidSnapshot_ShouldPass ()
void Validate_SpotPriceChanged_MoreThan10Percent_ShouldWarn ()
void Validate_ZeroBid_ShouldFail ()
void Validate_BidGreaterThanAsk_ShouldFail ()
void Validate_StaleData_ShouldFail ()
void Validate_AskBelowIntrinsic_ShouldFail ()
Private Member Functions
void Dispose (bool disposing)
Static Private Member Functions
static MarketDataSnapshot CreateValidSnapshot (decimal spotPrice=100m, DateTime? timestamp=null, decimal optionBid=2.50m, decimal optionAsk=2.70m, decimal optionStrike=100m, OptionRight optionRight=OptionRight.Call)
Private Attributes
readonly PriceReasonablenessValidator _validator
readonly ILoggerFactory _loggerFactory
readonly ILogger< PriceReasonablenessValidator > _logger
readonly ITimeProvider _timeProvider
bool _disposed
Detailed Description
Unit tests for PriceReasonablenessValidator (DTqc001A). Validates price data quality rules.
Definition at line 20 of file TSUN006A.cs.
Constructor & Destructor Documentation
DTqc001ATests()
Alaris.Test.Unit.DTqc001ATests.DTqc001ATests () inline
Definition at line 28 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc001ATests._logger, Alaris.Test.Unit.DTqc001ATests._loggerFactory, Alaris.Test.Unit.DTqc001ATests._timeProvider, and Alaris.Test.Unit.DTqc001ATests._validator.
Member Function Documentation
ComponentId_ShouldBe_DTqc001A()
void Alaris.Test.Unit.DTqc001ATests.ComponentId_ShouldBe_DTqc001A () inline
Definition at line 58 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc001ATests._validator, and Alaris.Infrastructure.Data.Quality.PriceReasonablenessValidator.ComponentId.
CreateValidSnapshot()
static MarketDataSnapshot Alaris.Test.Unit.DTqc001ATests.CreateValidSnapshot (decimal spotPrice = 100m, DateTime? timestamp = null, decimal optionBid = 2::50m, decimal optionAsk = 2::70m, decimal optionStrike = 100m, OptionRight optionRight = OptionRight::Call) inline static private
Definition at line 155 of file TSUN006A.cs.
Referenced by Alaris.Test.Unit.DTqc001ATests.Validate_AskBelowIntrinsic_ShouldFail(), Alaris.Test.Unit.DTqc001ATests.Validate_BidGreaterThanAsk_ShouldFail(), Alaris.Test.Unit.DTqc001ATests.Validate_SpotPriceChanged_MoreThan10Percent_ShouldWarn(), Alaris.Test.Unit.DTqc001ATests.Validate_StaleData_ShouldFail(), Alaris.Test.Unit.DTqc001ATests.Validate_ValidSnapshot_ShouldPass(), and Alaris.Test.Unit.DTqc001ATests.Validate_ZeroBid_ShouldFail().
Dispose() [1/2]
void Alaris.Test.Unit.DTqc001ATests.Dispose () inline
Definition at line 36 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc001ATests.Dispose().
Referenced by Alaris.Test.Unit.DTqc001ATests.Dispose().
Dispose() [2/2]
void Alaris.Test.Unit.DTqc001ATests.Dispose (bool disposing) inline private
Definition at line 42 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc001ATests._disposed, and Alaris.Test.Unit.DTqc001ATests._loggerFactory.
Validate_AskBelowIntrinsic_ShouldFail()
void Alaris.Test.Unit.DTqc001ATests.Validate_AskBelowIntrinsic_ShouldFail () inline
Definition at line 138 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc001ATests._validator, Alaris.Test.Unit.DTqc001ATests.CreateValidSnapshot(), Alaris.Infrastructure.Data.Model.DataQualityResult.Status, and Alaris.Infrastructure.Data.Quality.PriceReasonablenessValidator.Validate().
Validate_BidGreaterThanAsk_ShouldFail()
void Alaris.Test.Unit.DTqc001ATests.Validate_BidGreaterThanAsk_ShouldFail () inline
Definition at line 110 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc001ATests._validator, Alaris.Test.Unit.DTqc001ATests.CreateValidSnapshot(), Alaris.Infrastructure.Data.Model.DataQualityResult.Status, and Alaris.Infrastructure.Data.Quality.PriceReasonablenessValidator.Validate().
Validate_SpotPriceChanged_MoreThan10Percent_ShouldWarn()
void Alaris.Test.Unit.DTqc001ATests.Validate_SpotPriceChanged_MoreThan10Percent_ShouldWarn () inline
Definition at line 77 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc001ATests._validator, Alaris.Test.Unit.DTqc001ATests.CreateValidSnapshot(), Alaris.Infrastructure.Data.Model.DataQualityResult.Status, and Alaris.Infrastructure.Data.Quality.PriceReasonablenessValidator.Validate().
Validate_StaleData_ShouldFail()
void Alaris.Test.Unit.DTqc001ATests.Validate_StaleData_ShouldFail () inline
Definition at line 124 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc001ATests._validator, Alaris.Test.Unit.DTqc001ATests.CreateValidSnapshot(), Alaris.Infrastructure.Data.Model.DataQualityResult.Status, and Alaris.Infrastructure.Data.Quality.PriceReasonablenessValidator.Validate().
Validate_ValidSnapshot_ShouldPass()
void Alaris.Test.Unit.DTqc001ATests.Validate_ValidSnapshot_ShouldPass () inline
Definition at line 64 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc001ATests._validator, Alaris.Test.Unit.DTqc001ATests.CreateValidSnapshot(), Alaris.Infrastructure.Data.Model.DataQualityResult.Status, and Alaris.Infrastructure.Data.Quality.PriceReasonablenessValidator.Validate().
Validate_ZeroBid_ShouldFail()
void Alaris.Test.Unit.DTqc001ATests.Validate_ZeroBid_ShouldFail () inline
Definition at line 96 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc001ATests._validator, Alaris.Test.Unit.DTqc001ATests.CreateValidSnapshot(), Alaris.Infrastructure.Data.Model.DataQualityResult.Status, and Alaris.Infrastructure.Data.Quality.PriceReasonablenessValidator.Validate().
Member Data Documentation
_disposed
bool Alaris.Test.Unit.DTqc001ATests._disposed private
Definition at line 26 of file TSUN006A.cs.
Referenced by Alaris.Test.Unit.DTqc001ATests.Dispose().
_logger
readonly ILogger<PriceReasonablenessValidator> Alaris.Test.Unit.DTqc001ATests._logger private
Definition at line 24 of file TSUN006A.cs.
Referenced by Alaris.Test.Unit.DTqc001ATests.DTqc001ATests().
_loggerFactory
readonly ILoggerFactory Alaris.Test.Unit.DTqc001ATests._loggerFactory private
Definition at line 23 of file TSUN006A.cs.
Referenced by Alaris.Test.Unit.DTqc001ATests.DTqc001ATests(), and Alaris.Test.Unit.DTqc001ATests.Dispose().
_timeProvider
readonly ITimeProvider Alaris.Test.Unit.DTqc001ATests._timeProvider private
Definition at line 25 of file TSUN006A.cs.
Referenced by Alaris.Test.Unit.DTqc001ATests.DTqc001ATests().
_validator
readonly PriceReasonablenessValidator Alaris.Test.Unit.DTqc001ATests._validator private
Definition at line 22 of file TSUN006A.cs.
Referenced by Alaris.Test.Unit.DTqc001ATests.DTqc001ATests(), Alaris.Test.Unit.DTqc001ATests.ComponentId_ShouldBe_DTqc001A(), Alaris.Test.Unit.DTqc001ATests.Validate_AskBelowIntrinsic_ShouldFail(), Alaris.Test.Unit.DTqc001ATests.Validate_BidGreaterThanAsk_ShouldFail(), Alaris.Test.Unit.DTqc001ATests.Validate_SpotPriceChanged_MoreThan10Percent_ShouldWarn(), Alaris.Test.Unit.DTqc001ATests.Validate_StaleData_ShouldFail(), Alaris.Test.Unit.DTqc001ATests.Validate_ValidSnapshot_ShouldPass(), and Alaris.Test.Unit.DTqc001ATests.Validate_ZeroBid_ShouldFail().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN006A.cs