Alaris: Alaris.Strategy.Core.STIV005A Class Reference
Alaris.Strategy.Core.STIV005A Class Reference sealed
Calibrates earnings jump volatility (sigma_e) from historical earnings announcement data. The earnings jump volatility represents the standard deviation of log-returns on earnings announcement dates, as specified in Leung & Santoli (2014). This parameter is crucial for:
Public Member Functions
STIV005A (ILogger< STIV005A >? logger=null)
double? CalibrateFromMoves (double[] historicalEarningsMoves)
Calibrates earnings jump volatility from historical earnings moves.
EarningsJumpCalibration Calibrate (string symbol, IReadOnlyList< PriceBar > historicalPrices, IReadOnlyList< DateTime > earningsDates)
Calibrates earnings jump volatility from historical price data and earnings dates.
Static Public Member Functions
static ? double STTM001AEstimator (double iv1, int dte1, double iv2, int dte2)
Computes the term structure estimator from two IV observations. From Leung & Santoli (2014) Section 5.2, Equation 5.2: sigma_e^TS = sqrt((IV(T1)^2 - IV(T2)^2) / (1/(T1-t) - 1/(T2-t)))
static ? double BaseVolatilityEstimator (double iv1, int dte1, double iv2, int dte2)
Computes the base volatility (sigma) from term structure observations. From Leung & Santoli (2014) Section 5.2: sigma^TS = sqrt(((T1-t)*IV(T1)^2 - (T2-t)*IV(T2)^2) / (T1 - T2))
Private Member Functions
void ExtractReturns (IReadOnlyList< PriceBar > historicalPrices, IReadOnlyList< DateTime > earningsDates, List< double > earningsLogReturns, List< double > absoluteMoves)
EarningsJumpCalibration ComputeCalibration (string symbol, List< double > returns, List< double > absMoves)
void SafeLog (Action logAction)
Safely executes logging operation with fault isolation.
Static Private Member Functions
static double ComputeMedian (List< double > values)
Computes the median of a list of values.
Private Attributes
readonly? ILogger< STIV005A > _logger
Static Private Attributes
const int MinHistoricalSamples = 4
Minimum number of historical earnings to compute reliable sigma_e.
const int DefaultLookbackQuarters = 12
Default lookback period for historical earnings (quarters).
const double MaxSigmaE = 1.0
Maximum reasonable sigma_e (100% daily move).
const double MinSigmaE = 0.001
Minimum sigma_e to return (avoid zero division issues).
static readonly Action< ILogger, string, int, Exception?> LogCalibrating
static readonly Action< ILogger, string, double, Exception?> LogCalibrationResult
static readonly Action< ILogger, string, Exception?> LogInsufficientData
Detailed Description
Calibrates earnings jump volatility (sigma_e) from historical earnings announcement data. The earnings jump volatility represents the standard deviation of log-returns on earnings announcement dates, as specified in Leung & Santoli (2014). This parameter is crucial for:
Computing theoretical pre-EA implied volatility
Estimating expected IV crush magnitude
Identifying mispricing in market IV vs theoretical IV Calibration approach: sigma_e = sqrt(Var(Z_e)) where Z_e is the log-return on EA date Empirically: sigma_e = StdDev(log(S_t+1 / S_t)) for historical EA dates Reference: "Accounting for Earnings Announcements in the Pricing of Equity Options" Leung & Santoli (2014), Section 5.2 - Analytic Estimators under the Extended BS Model
Definition at line 23 of file STIV005A.cs.
Constructor & Destructor Documentation
STIV005A()
Alaris.Strategy.Core.STIV005A.STIV005A (ILogger< STIV005A >? logger = null) inline
Definition at line 66 of file STIV005A.cs.
References Alaris.Strategy.Core.STIV005A._logger.
Member Function Documentation
BaseVolatilityEstimator()
static ? double Alaris.Strategy.Core.STIV005A.BaseVolatilityEstimator (double iv1, int dte1, double iv2, int dte2) inline static
Computes the base volatility (sigma) from term structure observations. From Leung & Santoli (2014) Section 5.2: sigma^TS = sqrt(((T1-t)*IV(T1)^2 - (T2-t)*IV(T2)^2) / (T1 - T2))
Parameters
iv1 Implied volatility for first maturity.
dte1 Days to expiry for first maturity.
iv2 Implied volatility for second maturity.
dte2 Days to expiry for second maturity.
Returns
Term structure estimator of base volatility sigma, or null if invalid.
Definition at line 294 of file STIV005A.cs.
References Alaris.Strategy.Calendar.TradingCalendarDefaults.DteToYears().
Referenced by Alaris.Test.Unit.STIV005ATests.BaseVolatilityEstimator_WithSameDTE_ReturnsNull(), Alaris.Test.Unit.STIV005ATests.BaseVolatilityEstimator_WithValidInputs_ReturnsBaseVolatility(), Alaris.Test.Unit.STIV005ATests.BaseVolatilityEstimator_WithZeroDTE_ReturnsNull(), and Alaris.Strategy.Core.STCR001A.TryCalibrateFromTermStructure().
Calibrate()
EarningsJumpCalibration Alaris.Strategy.Core.STIV005A.Calibrate (string symbol, IReadOnlyList< PriceBar > historicalPrices, IReadOnlyList< DateTime > earningsDates) inline
Calibrates earnings jump volatility from historical price data and earnings dates.
Parameters
symbol The security symbol.
historicalPrices Historical daily price bars (sorted chronologically).
earningsDates Historical earnings announcement dates.
Returns
Calibration result with sigma_e and statistics.
Definition at line 100 of file STIV005A.cs.
References Alaris.Strategy.Core.STIV005A._logger, Alaris.Strategy.Core.STIV005A.ComputeCalibration(), Alaris.Strategy.Core.STIV005A.ExtractReturns(), Alaris.Strategy.Core.STIV005A.LogCalibrating, Alaris.Strategy.Core.STIV005A.LogInsufficientData, Alaris.Strategy.Core.STIV005A.MinHistoricalSamples, and Alaris.Strategy.Core.STIV005A.SafeLog().
Referenced by Alaris.Test.Unit.STIV005ATests.Calibrate_ThrowsOnNullPrices(), Alaris.Test.Unit.STIV005ATests.Calibrate_ThrowsOnNullSymbol(), Alaris.Test.Unit.STIV005ATests.Calibrate_WithInsufficientEarningsData_ReturnsInvalidCalibration(), Alaris.Test.Unit.STIV005ATests.Calibrate_WithValidPricesAndDates_ReturnsValidCalibration(), and Alaris.Strategy.Core.STCR001A.TryCalibrateFromHistory().
CalibrateFromMoves()
double? Alaris.Strategy.Core.STIV005A.CalibrateFromMoves (double[] historicalEarningsMoves) inline
Calibrates earnings jump volatility from historical earnings moves.
Parameters
historicalEarningsMoves Array of historical earnings log-returns.
Returns
Calibrated sigma_e, or null if insufficient data.
Definition at line 76 of file STIV005A.cs.
References Alaris.Strategy.Core.STIV005A.MaxSigmaE, Alaris.Strategy.Core.STIV005A.MinHistoricalSamples, and Alaris.Strategy.Core.STIV005A.MinSigmaE.
Referenced by Alaris.Test.Unit.STIV005ATests.CalibrateFromMoves_WithConstantMoves_ReturnsMinSigmaE(), Alaris.Test.Unit.STIV005ATests.CalibrateFromMoves_WithInsufficientData_ReturnsNull(), Alaris.Test.Unit.STIV005ATests.CalibrateFromMoves_WithLargeMoves_ClampsToMax(), Alaris.Test.Unit.STIV005ATests.CalibrateFromMoves_WithNullArray_ReturnsNull(), and Alaris.Test.Unit.STIV005ATests.CalibrateFromMoves_WithValidData_ReturnsCorrectSigmaE().
ComputeCalibration()
EarningsJumpCalibration Alaris.Strategy.Core.STIV005A.ComputeCalibration (string symbol, List< double > returns, List< double > absMoves) inline private
Definition at line 188 of file STIV005A.cs.
References Alaris.Strategy.Core.STIV005A._logger, Alaris.Strategy.Core.STIV005A.ComputeMedian(), Alaris.Strategy.Core.STIV005A.LogCalibrationResult, Alaris.Strategy.Core.STIV005A.MaxSigmaE, Alaris.Strategy.Core.STIV005A.MinSigmaE, and Alaris.Strategy.Core.STIV005A.SafeLog().
Referenced by Alaris.Strategy.Core.STIV005A.Calibrate().
ComputeMedian()
static double Alaris.Strategy.Core.STIV005A.ComputeMedian (List< double > values) inline static private
Computes the median of a list of values.
Definition at line 320 of file STIV005A.cs.
Referenced by Alaris.Strategy.Core.STIV005A.ComputeCalibration().
ExtractReturns()
void Alaris.Strategy.Core.STIV005A.ExtractReturns (IReadOnlyList< PriceBar > historicalPrices, IReadOnlyList< DateTime > earningsDates, List< double > earningsLogReturns, List< double > absoluteMoves) inline private
Definition at line 131 of file STIV005A.cs.
References Alaris.Strategy.Bridge.PriceBar.Close, Alaris.Strategy.Bridge.PriceBar.Date, and Alaris.Strategy.Core.STIV005A.DefaultLookbackQuarters.
Referenced by Alaris.Strategy.Core.STIV005A.Calibrate().
SafeLog()
void Alaris.Strategy.Core.STIV005A.SafeLog (Action logAction) inline private
Safely executes logging operation with fault isolation.
Definition at line 341 of file STIV005A.cs.
References Alaris.Strategy.Core.STIV005A._logger.
Referenced by Alaris.Strategy.Core.STIV005A.Calibrate(), and Alaris.Strategy.Core.STIV005A.ComputeCalibration().
STTM001AEstimator()
static ? double Alaris.Strategy.Core.STIV005A.STTM001AEstimator (double iv1, int dte1, double iv2, int dte2) inline static
Computes the term structure estimator from two IV observations. From Leung & Santoli (2014) Section 5.2, Equation 5.2: sigma_e^TS = sqrt((IV(T1)^2 - IV(T2)^2) / (1/(T1-t) - 1/(T2-t)))
Parameters
iv1 Implied volatility for first maturity.
dte1 Days to expiry for first maturity.
iv2 Implied volatility for second maturity (dte2 > dte1).
dte2 Days to expiry for second maturity.
Returns
Term structure estimator of sigma_e, or null if invalid.
Definition at line 248 of file STIV005A.cs.
References Alaris.Strategy.Calendar.TradingCalendarDefaults.DteToYears(), Alaris.Strategy.Core.STIV005A.MaxSigmaE, and Alaris.Strategy.Core.STIV005A.MinSigmaE.
Referenced by Alaris.Test.Unit.STIV005ATests.STTM001AEstimator_WithFlatSTTM001A_ReturnsNull(), Alaris.Test.Unit.STIV005ATests.STTM001AEstimator_WithInvalidDTE_ReturnsNull(), Alaris.Test.Unit.STIV005ATests.STTM001AEstimator_WithValidInvertedSTTM001A_ReturnsSigmaE(), Alaris.Test.Unit.STIV005ATests.STTM001AEstimator_WithZeroDTE_ReturnsNull(), and Alaris.Strategy.Core.STCR001A.TryCalibrateFromTermStructure().
Member Data Documentation
_logger
readonly? ILogger<STIV005A> Alaris.Strategy.Core.STIV005A._logger private
Definition at line 25 of file STIV005A.cs.
Referenced by Alaris.Strategy.Core.STIV005A.STIV005A(), Alaris.Strategy.Core.STIV005A.Calibrate(), Alaris.Strategy.Core.STIV005A.ComputeCalibration(), and Alaris.Strategy.Core.STIV005A.SafeLog().
DefaultLookbackQuarters
const int Alaris.Strategy.Core.STIV005A.DefaultLookbackQuarters = 12 static private
Default lookback period for historical earnings (quarters).
Definition at line 35 of file STIV005A.cs.
Referenced by Alaris.Strategy.Core.STIV005A.ExtractReturns().
LogCalibrating
readonly Action<ILogger, string, int, Exception?> Alaris.Strategy.Core.STIV005A.LogCalibrating static private
Initial value:
=
        LoggerMessage.Define<string, int>(
            LogLevel.Information,
            new EventId(1, nameof(LogCalibrating)),
            "Calibrating sigma_e for {Symbol} using {SampleCount} historical earnings")
Definition at line 48 of file STIV005A.cs.
Referenced by Alaris.Strategy.Core.STIV005A.Calibrate().
LogCalibrationResult
readonly Action<ILogger, string, double, Exception?> Alaris.Strategy.Core.STIV005A.LogCalibrationResult static private
Initial value:
=
        LoggerMessage.Define<string, double>(
            LogLevel.Information,
            new EventId(2, nameof(LogCalibrationResult)),
            "Calibrated sigma_e for {Symbol}: {SigmaE:P2}")
Definition at line 54 of file STIV005A.cs.
Referenced by Alaris.Strategy.Core.STIV005A.ComputeCalibration().
LogInsufficientData
readonly Action<ILogger, string, Exception?> Alaris.Strategy.Core.STIV005A.LogInsufficientData static private
Initial value:
=
        LoggerMessage.Define<string>(
            LogLevel.Warning,
            new EventId(3, nameof(LogInsufficientData)),
            "Insufficient historical earnings data for {Symbol}")
Definition at line 60 of file STIV005A.cs.
Referenced by Alaris.Strategy.Core.STIV005A.Calibrate().
MaxSigmaE
const double Alaris.Strategy.Core.STIV005A.MaxSigmaE = 1.0 static private
Maximum reasonable sigma_e (100% daily move).
Definition at line 40 of file STIV005A.cs.
Referenced by Alaris.Strategy.Core.STIV005A.CalibrateFromMoves(), Alaris.Strategy.Core.STIV005A.ComputeCalibration(), and Alaris.Strategy.Core.STIV005A.STTM001AEstimator().
MinHistoricalSamples
const int Alaris.Strategy.Core.STIV005A.MinHistoricalSamples = 4 static private
Minimum number of historical earnings to compute reliable sigma_e.
Definition at line 30 of file STIV005A.cs.
Referenced by Alaris.Strategy.Core.STIV005A.Calibrate(), and Alaris.Strategy.Core.STIV005A.CalibrateFromMoves().
MinSigmaE
const double Alaris.Strategy.Core.STIV005A.MinSigmaE = 0.001 static private
Minimum sigma_e to return (avoid zero division issues).
Definition at line 45 of file STIV005A.cs.
Referenced by Alaris.Strategy.Core.STIV005A.CalibrateFromMoves(), Alaris.Strategy.Core.STIV005A.ComputeCalibration(), and Alaris.Strategy.Core.STIV005A.STTM001AEstimator().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Core/STIV005A.cs