Alaris: Alaris.Strategy.Core.STIV006A Class Reference
Alaris.Strategy.Core.STIV006A Class Reference sealed
Interpolates implied volatility across strikes using sticky-delta convention.
Public Member Functions
STIV006A (ILogger< STIV006A >? logger=null)
Initialises a new instance of the volatility surface interpolator.
STIV007A CalibrateFromChain (IReadOnlyList< STIV008A > chain, double spotPrice, double timeToExpiry, double riskFreeRate)
Calibrates the volatility surface from an option chain.
double InterpolateIV (STIV007A parameters, double strike)
Interpolates implied volatility at an arbitrary strike.
double CalculateStickyDeltaIVChange (STIV007A parameters, double originalStrike, double originalSpot, double currentSpot)
Calculates the IV change from spot movement (sticky-delta).
STIV009A EvaluateSkewExposure (STIV007A parameters, double currentMoneyness, double entryMoneyness)
Evaluates skew exposure risk for a calendar spread position.
Private Member Functions
void SafeLog (Action logAction)
Safely executes logging operation with fault isolation (Rule 15).
Static Private Member Functions
static double CalculateSkewFromChain (IReadOnlyList< STIV008A > chain, double spotPrice, double atmIV, double timeToExpiry)
Calculates skew coefficient from option chain (25-delta risk reversal).
Private Attributes
readonly? ILogger< STIV006A > _logger
Static Private Attributes
const double DefaultSkewCoefficient = -0.10
Default skew coefficient (25-delta risk reversal). Negative for equity (downside skew).
const double MinTimeToExpiry = 1.0 / 252.0
Minimum time to expiry for smile calculations.
static readonly Action< ILogger, double, double, double, Exception?> LogCalibration
Detailed Description
Interpolates implied volatility across strikes using sticky-delta convention.
Definition at line 11 of file STIV006A.cs.
Constructor & Destructor Documentation
STIV006A()
Alaris.Strategy.Core.STIV006A.STIV006A (ILogger< STIV006A >? logger = null) inline
Initialises a new instance of the volatility surface interpolator.
Parameters
logger Optional logger instance.
Definition at line 37 of file STIV006A.cs.
References Alaris.Strategy.Core.STIV006A._logger.
Member Function Documentation
CalculateSkewFromChain()
static double Alaris.Strategy.Core.STIV006A.CalculateSkewFromChain (IReadOnlyList< STIV008A > chain, double spotPrice, double atmIV, double timeToExpiry) inline static private
Calculates skew coefficient from option chain (25-delta risk reversal).
Definition at line 198 of file STIV006A.cs.
References Alaris.Strategy.Core.STIV006A.DefaultSkewCoefficient.
Referenced by Alaris.Strategy.Core.STIV006A.CalibrateFromChain().
CalculateStickyDeltaIVChange()
double Alaris.Strategy.Core.STIV006A.CalculateStickyDeltaIVChange (STIV007A parameters, double originalStrike, double originalSpot, double currentSpot) inline
Calculates the IV change from spot movement (sticky-delta).
Parameters
parameters Calibrated surface parameters.
originalStrike Original strike price.
originalSpot Spot price at position entry.
currentSpot Current spot price.
Returns
Estimated IV change at the original strike.
Definition at line 131 of file STIV006A.cs.
References Alaris.Strategy.Core.STIV006A.MinTimeToExpiry.
Referenced by Alaris.Test.Unit.STIV006ATests.CalculateStickyDeltaIVChange_SpotDown_ReturnsNegativeChange(), and Alaris.Test.Unit.STIV006ATests.CalculateStickyDeltaIVChange_SpotUp_ReturnsPositiveChange().
CalibrateFromChain()
STIV007A Alaris.Strategy.Core.STIV006A.CalibrateFromChain (IReadOnlyList< STIV008A > chain, double spotPrice, double timeToExpiry, double riskFreeRate) inline
Calibrates the volatility surface from an option chain.
Parameters
chain List of option quotes with strikes and IVs.
spotPrice Current spot price.
timeToExpiry Time to expiration in years.
riskFreeRate Risk-free interest rate.
Returns
Calibrated volatility surface parameters.
Exceptions
ArgumentNullException Thrown when chain is null.
ArgumentException Thrown when chain has insufficient data.
Definition at line 52 of file STIV006A.cs.
References Alaris.Strategy.Core.STIV006A._logger, Alaris.Strategy.Core.STIV006A.CalculateSkewFromChain(), Alaris.Strategy.Core.STIV006A.LogCalibration, Alaris.Strategy.Core.STIV006A.SafeLog(), Alaris.Strategy.Core.STIV007A, and Alaris.Strategy.Core.STIV008A.
Referenced by Alaris.Test.Unit.STIV006ATests.CalibrateFromChain_WithInsufficientData_ThrowsArgumentException(), and Alaris.Test.Unit.STIV006ATests.CalibrateFromChain_WithValidChain_ReturnsParameters().
EvaluateSkewExposure()
STIV009A Alaris.Strategy.Core.STIV006A.EvaluateSkewExposure (STIV007A parameters, double currentMoneyness, double entryMoneyness) inline
Evaluates skew exposure risk for a calendar spread position.
Parameters
parameters Calibrated surface parameters.
currentMoneyness Current moneyness (S/K).
entryMoneyness Entry moneyness (S/K at entry).
Returns
Skew exposure result.
Definition at line 160 of file STIV006A.cs.
References Alaris.Strategy.Core.STIV006A.MinTimeToExpiry, and Alaris.Strategy.Core.STIV009A.
Referenced by Alaris.Test.Unit.STIV006ATests.EvaluateSkewExposure_ElevatedShift_RecommendRecenter(), Alaris.Test.Unit.STIV006ATests.EvaluateSkewExposure_LargeShift_ReturnsHighRisk(), and Alaris.Test.Unit.STIV006ATests.EvaluateSkewExposure_SmallShift_ReturnsLowRisk().
InterpolateIV()
double Alaris.Strategy.Core.STIV006A.InterpolateIV (STIV007A parameters, double strike) inline
Interpolates implied volatility at an arbitrary strike.
Parameters
parameters Calibrated surface parameters.
strike Target strike price.
Returns
Interpolated implied volatility.
Exceptions
ArgumentNullException Thrown when parameters is null.
ArgumentOutOfRangeException Thrown when strike is non-positive.
Definition at line 99 of file STIV006A.cs.
References Alaris.Strategy.Core.STIV006A.MinTimeToExpiry.
Referenced by Alaris.Test.Unit.STIV006ATests.InterpolateIV_AboveATM_ReturnsLowerIV(), Alaris.Test.Unit.STIV006ATests.InterpolateIV_AtATM_ReturnsAtmIV(), Alaris.Test.Unit.STIV006ATests.InterpolateIV_BelowATM_ReturnsHigherIV(), and Alaris.Test.Unit.STIV006ATests.InterpolateIV_ClampsToReasonableRange().
SafeLog()
void Alaris.Strategy.Core.STIV006A.SafeLog (Action logAction) inline private
Safely executes logging operation with fault isolation (Rule 15).
Definition at line 238 of file STIV006A.cs.
References Alaris.Strategy.Core.STIV006A._logger.
Referenced by Alaris.Strategy.Core.STIV006A.CalibrateFromChain().
Member Data Documentation
_logger
readonly? ILogger<STIV006A> Alaris.Strategy.Core.STIV006A._logger private
Definition at line 13 of file STIV006A.cs.
Referenced by Alaris.Strategy.Core.STIV006A.STIV006A(), Alaris.Strategy.Core.STIV006A.CalibrateFromChain(), and Alaris.Strategy.Core.STIV006A.SafeLog().
DefaultSkewCoefficient
const double Alaris.Strategy.Core.STIV006A.DefaultSkewCoefficient = -0.10 static private
Default skew coefficient (25-delta risk reversal). Negative for equity (downside skew).
Definition at line 19 of file STIV006A.cs.
Referenced by Alaris.Strategy.Core.STIV006A.CalculateSkewFromChain().
LogCalibration
readonly Action<ILogger, double, double, double, Exception?> Alaris.Strategy.Core.STIV006A.LogCalibration static private
Initial value:
=
        LoggerMessage.Define<double, double, double>(
            LogLevel.Debug,
            new EventId(1, nameof(LogCalibration)),
            "Vol surface calibration: ATM_IV={AtmIV:F4}, Skew={Skew:F4}, TimeToExpiry={TimeToExpiry:F4}")
Definition at line 27 of file STIV006A.cs.
Referenced by Alaris.Strategy.Core.STIV006A.CalibrateFromChain().
MinTimeToExpiry
const double Alaris.Strategy.Core.STIV006A.MinTimeToExpiry = 1.0 / 252.0 static private
Minimum time to expiry for smile calculations.
Definition at line 24 of file STIV006A.cs.
Referenced by Alaris.Strategy.Core.STIV006A.CalculateStickyDeltaIVChange(), Alaris.Strategy.Core.STIV006A.EvaluateSkewExposure(), and Alaris.Strategy.Core.STIV006A.InterpolateIV().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Core/STIV006A.cs