Alaris: Alaris.Strategy.Calendar.STCL001A Class Reference
Alaris.Strategy.Calendar.STCL001A Class Reference sealed
NYSE trading calendar implementation with native holiday rules. Replaces QuantLib UnitedStates(NYSE) with equivalent functionality.
Public Member Functions
STCL001A ()
Initialises a new NYSE trading calendar.
int GetBusinessDaysBetween (DateTime startDate, DateTime endDate)
Gets the number of business days between two dates.
Parameters
startDate Start date (exclusive by default).
endDate End date (exclusive by default).
Returns
Number of business days.
bool IsBusinessDay (DateTime targetDate)
Determines if a date is a business day.
Parameters
targetDate Date to check.
Returns
True if the date is a business day.
double GetTimeToExpiryInYears (DateTime currentDate, DateTime expiryDate)
Calculates time to expiry in years (trading days / 252).
Parameters
currentDate Current date.
expiryDate Option expiration date.
Returns
Time to expiry in years.
Static Public Attributes
const double TradingDaysPerYear = 252.0
Trading days per year for annualisation.
Private Member Functions
bool IsNYSEHoliday (DateTime date)
Determines if the given date is an NYSE holiday.
HashSet< DateTime > GetHolidaysForYear (int year)
Gets or computes the set of NYSE holidays for a given year.
Static Private Member Functions
static HashSet< DateTime > ComputeNYSEHolidays (int year)
Computes all NYSE holidays for a given year.
static DateTime AdjustWeekendHoliday (DateTime holiday)
Adjusts a weekend holiday to the nearest weekday. Saturday holidays are observed on Friday. Sunday holidays are observed on Monday.
static DateTime GetNthWeekdayOfMonth (int year, int month, DayOfWeek dayOfWeek, int n)
Gets the nth occurrence of a weekday in a month.
static DateTime GetLastWeekdayOfMonth (int year, int month, DayOfWeek dayOfWeek)
Gets the last occurrence of a weekday in a month.
static DateTime ComputeEasterSunday (int year)
Computes Easter Sunday using the Anonymous Gregorian algorithm.
Private Attributes
readonly Dictionary< int, HashSet< DateTime > > _holidayCache = []
readonly object _cacheLock = new()
Detailed Description
NYSE trading calendar implementation with native holiday rules. Replaces QuantLib UnitedStates(NYSE) with equivalent functionality.
Definition at line 50 of file STCL001A.cs.
Constructor & Destructor Documentation
STCL001A()
Alaris.Strategy.Calendar.STCL001A.STCL001A () inline
Initialises a new NYSE trading calendar.
Definition at line 65 of file STCL001A.cs.
Member Function Documentation
AdjustWeekendHoliday()
static DateTime Alaris.Strategy.Calendar.STCL001A.AdjustWeekendHoliday (DateTime holiday) inline static private
Adjusts a weekend holiday to the nearest weekday. Saturday holidays are observed on Friday. Sunday holidays are observed on Monday.
Definition at line 222 of file STCL001A.cs.
Referenced by Alaris.Strategy.Calendar.STCL001A.ComputeNYSEHolidays().
ComputeEasterSunday()
static DateTime Alaris.Strategy.Calendar.STCL001A.ComputeEasterSunday (int year) inline static private
Computes Easter Sunday using the Anonymous Gregorian algorithm.
Algorithm source: Meeus, Jean. "Astronomical Algorithms" (1991)
Definition at line 263 of file STCL001A.cs.
Referenced by Alaris.Strategy.Calendar.STCL001A.ComputeNYSEHolidays().
ComputeNYSEHolidays()
static HashSet< DateTime > Alaris.Strategy.Calendar.STCL001A.ComputeNYSEHolidays (int year) inline static private
Computes all NYSE holidays for a given year.
NYSE Holiday Rules:
New Year's Day (Jan 1, or following Monday if Sunday)
Martin Luther King Jr. Day (3rd Monday of January)
Presidents' Day (3rd Monday of February)
Good Friday (Friday before Easter Sunday)
Memorial Day (Last Monday of May)
Juneteenth (June 19, or nearest weekday) - Added 2021
Independence Day (July 4, or nearest weekday)
Labor Day (1st Monday of September)
Thanksgiving Day (4th Thursday of November)
Christmas Day (Dec 25, or nearest weekday)
Definition at line 166 of file STCL001A.cs.
References Alaris.Strategy.Calendar.STCL001A.AdjustWeekendHoliday(), Alaris.Strategy.Calendar.STCL001A.ComputeEasterSunday(), Alaris.Strategy.Calendar.STCL001A.GetLastWeekdayOfMonth(), and Alaris.Strategy.Calendar.STCL001A.GetNthWeekdayOfMonth().
Referenced by Alaris.Strategy.Calendar.STCL001A.GetHolidaysForYear().
GetBusinessDaysBetween()
int Alaris.Strategy.Calendar.STCL001A.GetBusinessDaysBetween (DateTime startDate, DateTime endDate) inline
Gets the number of business days between two dates.
Parameters
startDate Start date (exclusive by default).
endDate End date (exclusive by default).
Returns
Number of business days.
Implements Alaris.Strategy.Calendar.ITradingCalendar.
Definition at line 70 of file STCL001A.cs.
References Alaris.Strategy.Calendar.STCL001A.IsBusinessDay().
Referenced by Alaris.Test.Unit.TSUN022A.GetBusinessDaysBetween_OneWeek_ReturnsFiveDays(), Alaris.Test.Unit.TSUN022A.GetBusinessDaysBetween_ReversedDates_ReturnsZero(), Alaris.Test.Unit.TSUN022A.GetBusinessDaysBetween_SameDay_ReturnsZero(), and Alaris.Strategy.Calendar.STCL001A.GetTimeToExpiryInYears().
GetHolidaysForYear()
HashSet< DateTime > Alaris.Strategy.Calendar.STCL001A.GetHolidaysForYear (int year) inline private
Gets or computes the set of NYSE holidays for a given year.
Definition at line 135 of file STCL001A.cs.
References Alaris.Strategy.Calendar.STCL001A._cacheLock, Alaris.Strategy.Calendar.STCL001A._holidayCache, and Alaris.Strategy.Calendar.STCL001A.ComputeNYSEHolidays().
Referenced by Alaris.Strategy.Calendar.STCL001A.IsNYSEHoliday().
GetLastWeekdayOfMonth()
static DateTime Alaris.Strategy.Calendar.STCL001A.GetLastWeekdayOfMonth (int year, int month, DayOfWeek dayOfWeek) inline static private
Gets the last occurrence of a weekday in a month.
Definition at line 250 of file STCL001A.cs.
Referenced by Alaris.Strategy.Calendar.STCL001A.ComputeNYSEHolidays().
GetNthWeekdayOfMonth()
static DateTime Alaris.Strategy.Calendar.STCL001A.GetNthWeekdayOfMonth (int year, int month, DayOfWeek dayOfWeek, int n) inline static private
Gets the nth occurrence of a weekday in a month.
Parameters
year Year.
month Month (1-12).
dayOfWeek Target day of week.
n Occurrence number (1-5).
Definition at line 239 of file STCL001A.cs.
Referenced by Alaris.Strategy.Calendar.STCL001A.ComputeNYSEHolidays().
GetTimeToExpiryInYears()
double Alaris.Strategy.Calendar.STCL001A.GetTimeToExpiryInYears (DateTime currentDate, DateTime expiryDate) inline
Calculates time to expiry in years (trading days / 252).
Parameters
currentDate Current date.
expiryDate Option expiration date.
Returns
Time to expiry in years.
Implements Alaris.Strategy.Calendar.ITradingCalendar.
Definition at line 115 of file STCL001A.cs.
References Alaris.Strategy.Calendar.STCL001A.GetBusinessDaysBetween(), and Alaris.Strategy.Calendar.STCL001A.TradingDaysPerYear.
Referenced by Alaris.Test.Unit.TSUN022A.GetTimeToExpiryInYears_TwoWeeks_IsApproximatelyTenDays(), and Alaris.Test.Unit.TSUN022A.GetTimeToExpiryInYears_VsApproximation_DiffersNearHolidays().
IsBusinessDay()
bool Alaris.Strategy.Calendar.STCL001A.IsBusinessDay (DateTime targetDate) inline
Determines if a date is a business day.
Parameters
targetDate Date to check.
Returns
True if the date is a business day.
Implements Alaris.Strategy.Calendar.ITradingCalendar.
Definition at line 100 of file STCL001A.cs.
References Alaris.Strategy.Calendar.STCL001A.IsNYSEHoliday().
Referenced by Alaris.Strategy.Calendar.STCL001A.GetBusinessDaysBetween(), Alaris.Test.Unit.TSUN022A.IsBusinessDay_NyseHoliday_ReturnsFalse(), Alaris.Test.Unit.TSUN022A.IsBusinessDay_Weekday_ReturnsTrue(), and Alaris.Test.Unit.TSUN022A.IsBusinessDay_Weekend_ReturnsFalse().
IsNYSEHoliday()
bool Alaris.Strategy.Calendar.STCL001A.IsNYSEHoliday (DateTime date) inline private
Determines if the given date is an NYSE holiday.
Parameters
date Date to check (must be weekday).
Returns
True if the date is an NYSE holiday.
Definition at line 126 of file STCL001A.cs.
References Alaris.Strategy.Calendar.STCL001A.GetHolidaysForYear().
Referenced by Alaris.Strategy.Calendar.STCL001A.IsBusinessDay().
Member Data Documentation
_cacheLock
readonly object Alaris.Strategy.Calendar.STCL001A._cacheLock = new() private
Definition at line 60 of file STCL001A.cs.
Referenced by Alaris.Strategy.Calendar.STCL001A.GetHolidaysForYear().
_holidayCache
readonly Dictionary<int, HashSet<DateTime> > Alaris.Strategy.Calendar.STCL001A._holidayCache = [] private
Definition at line 59 of file STCL001A.cs.
Referenced by Alaris.Strategy.Calendar.STCL001A.GetHolidaysForYear().
TradingDaysPerYear
const double Alaris.Strategy.Calendar.STCL001A.TradingDaysPerYear = 252.0 static
Trading days per year for annualisation.
Definition at line 55 of file STCL001A.cs.
Referenced by Alaris.Strategy.Calendar.STCL001A.GetTimeToExpiryInYears().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Calendar/STCL001A.cs