Alaris: Alaris.Host.Application.Service.DataVerificationReport Class Reference
Alaris.Host.Application.Service.DataVerificationReport Class Reference sealed
Report of data verification results.
Public Member Functions
string GetSummary ()
Gets a summary of issues for display.
Properties
string SessionDataPath = string.Empty [get]
DateTime VerifiedAt [get]
bool IsComplete [get, set]
Collection< string > MissingPriceData = new() [get]
Collection< string > MissingMapFiles = new() [get]
Collection< string > MissingFactorFiles = new() [get]
Collection< DateTime > MissingEarningsDates = new() [get]
Collection<(string Symbol, DateTime Date)> MissingOptionsData = new() [get]
bool BenchmarkAvailable [get, set]
Detailed Description
Report of data verification results.
Definition at line 192 of file APsv003A.cs.
Member Function Documentation
GetSummary()
string Alaris.Host.Application.Service.DataVerificationReport.GetSummary () inline
Gets a summary of issues for display.
Definition at line 208 of file APsv003A.cs.
References Alaris.Host.Application.Service.DataVerificationReport.BenchmarkAvailable, Alaris.Host.Application.Service.DataVerificationReport.IsComplete, Alaris.Host.Application.Service.DataVerificationReport.MissingEarningsDates, Alaris.Host.Application.Service.DataVerificationReport.MissingFactorFiles, Alaris.Host.Application.Service.DataVerificationReport.MissingMapFiles, Alaris.Host.Application.Service.DataVerificationReport.MissingOptionsData, and Alaris.Host.Application.Service.DataVerificationReport.MissingPriceData.
Referenced by Alaris.Test.Backtest.TSBT001A.DataVerificationReport_GetSummary_ReturnsSuccessWhenComplete().
Property Documentation
BenchmarkAvailable
bool Alaris.Host.Application.Service.DataVerificationReport.BenchmarkAvailable get set
Definition at line 203 of file APsv003A.cs.
Referenced by Alaris.Host.Application.Service.DataVerificationReport.GetSummary(), and Alaris.Host.Application.Service.APsv003A.VerifyBenchmarkData().
IsComplete
bool Alaris.Host.Application.Service.DataVerificationReport.IsComplete get set
Definition at line 196 of file APsv003A.cs.
Referenced by Alaris.Host.Application.Service.DataVerificationReport.GetSummary().
MissingEarningsDates
Collection<DateTime> Alaris.Host.Application.Service.DataVerificationReport.MissingEarningsDates = new() get
Definition at line 201 of file APsv003A.cs.
Referenced by Alaris.Host.Application.Service.DataVerificationReport.GetSummary(), and Alaris.Host.Application.Service.APsv003A.VerifyEarningsCalendar().
MissingFactorFiles
Collection<string> Alaris.Host.Application.Service.DataVerificationReport.MissingFactorFiles = new() get
Definition at line 200 of file APsv003A.cs.
Referenced by Alaris.Host.Application.Service.DataVerificationReport.GetSummary().
MissingMapFiles
Collection<string> Alaris.Host.Application.Service.DataVerificationReport.MissingMapFiles = new() get
Definition at line 199 of file APsv003A.cs.
Referenced by Alaris.Host.Application.Service.DataVerificationReport.GetSummary().
MissingOptionsData
Collection<(string Symbol, DateTime Date)> Alaris.Host.Application.Service.DataVerificationReport.MissingOptionsData = new() get
Definition at line 202 of file APsv003A.cs.
Referenced by Alaris.Host.Application.Service.DataVerificationReport.GetSummary().
MissingPriceData
Collection<string> Alaris.Host.Application.Service.DataVerificationReport.MissingPriceData = new() get
Definition at line 198 of file APsv003A.cs.
Referenced by Alaris.Test.Backtest.TSBT001A.DataVerificationReport_GetSummary_ListsMissingData(), and Alaris.Host.Application.Service.DataVerificationReport.GetSummary().
SessionDataPath
string Alaris.Host.Application.Service.DataVerificationReport.SessionDataPath = string.Empty get
Definition at line 194 of file APsv003A.cs.
VerifiedAt
DateTime Alaris.Host.Application.Service.DataVerificationReport.VerifiedAt get
Definition at line 195 of file APsv003A.cs.
The documentation for this class was generated from the following file:
src/Alaris.Host/Application/Service/APsv003A.cs