Alaris: Alaris.Test.Unit.Core.Pricing.CREN002ATests Class Reference
Alaris.Test.Unit.Core.Pricing.CREN002ATests Class Reference
Unit tests for CREN002A American option pricing engine.
Public Member Functions
CREN002ATests ()
void Price_ATMCall_ReturnsPositiveValue ()
void Price_ATMPut_ReturnsPositiveValue ()
void Price_DeepITMCall_ApproachesIntrinsicValue ()
void Price_DeepOTMCall_ApproachesZero ()
void Price_AmericanPut_AtLeastEqualToEuropean ()
void Price_AmericanCall_NoDividend_EqualsEuropean ()
void Price_Call_MonotonicInSpot ()
void Price_Put_MonotonicDecreasingInSpot ()
void Price_MonotonicIncreasingInVolatility ()
void Price_MonotonicIncreasingInTime ()
void Delta_Call_BoundedZeroToOne ()
void Delta_Put_BoundedMinusOneToZero ()
void Gamma_AlwaysPositive ()
void Vega_AlwaysPositive ()
void Theta_PutTypicallyNegative ()
void Price_ZeroTimeToExpiry_ReturnsIntrinsic ()
void Price_VariousRates_ReturnsValidPrice (double r, double q)
void Price_InvalidSpot_ThrowsException ()
void Price_InvalidVolatility_ThrowsException ()
Static Private Member Functions
static double BlackScholesCall (double S, double K, double T, double r, double q, double sigma)
static double BlackScholesPut (double S, double K, double T, double r, double q, double sigma)
static double NormalCdf (double x)
static double Erf (double x)
Private Attributes
readonly CREN002A _engine
Static Private Attributes
const double Tolerance = 0.05
Detailed Description
Unit tests for CREN002A American option pricing engine.
Definition at line 19 of file CREN002ATests.cs.
Constructor & Destructor Documentation
CREN002ATests()
Alaris.Test.Unit.Core.Pricing.CREN002ATests.CREN002ATests () inline
Definition at line 24 of file CREN002ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN002ATests._engine.
Member Function Documentation
BlackScholesCall()
static double Alaris.Test.Unit.Core.Pricing.CREN002ATests.BlackScholesCall (double S, double K, double T, double r, double q, double sigma) inline static private
Definition at line 366 of file CREN002ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN002ATests.NormalCdf().
Referenced by Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_AmericanCall_NoDividend_EqualsEuropean().
BlackScholesPut()
static double Alaris.Test.Unit.Core.Pricing.CREN002ATests.BlackScholesPut (double S, double K, double T, double r, double q, double sigma) inline static private
Definition at line 373 of file CREN002ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN002ATests.NormalCdf().
Referenced by Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_AmericanPut_AtLeastEqualToEuropean().
Delta_Call_BoundedZeroToOne()
void Alaris.Test.Unit.Core.Pricing.CREN002ATests.Delta_Call_BoundedZeroToOne () inline
Definition at line 233 of file CREN002ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN002ATests._engine, and Alaris.Core.Pricing.CREN002A.Delta().
Delta_Put_BoundedMinusOneToZero()
void Alaris.Test.Unit.Core.Pricing.CREN002ATests.Delta_Put_BoundedMinusOneToZero () inline
Definition at line 249 of file CREN002ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN002ATests._engine, and Alaris.Core.Pricing.CREN002A.Delta().
Erf()
static double Alaris.Test.Unit.Core.Pricing.CREN002ATests.Erf (double x) inline static private
Definition at line 385 of file CREN002ATests.cs.
Referenced by Alaris.Test.Unit.Core.Pricing.CREN002ATests.NormalCdf().
Gamma_AlwaysPositive()
void Alaris.Test.Unit.Core.Pricing.CREN002ATests.Gamma_AlwaysPositive () inline
Definition at line 265 of file CREN002ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN002ATests._engine, and Alaris.Core.Pricing.CREN002A.Gamma().
NormalCdf()
static double Alaris.Test.Unit.Core.Pricing.CREN002ATests.NormalCdf (double x) inline static private
Definition at line 380 of file CREN002ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN002ATests.Erf().
Referenced by Alaris.Test.Unit.Core.Pricing.CREN002ATests.BlackScholesCall(), and Alaris.Test.Unit.Core.Pricing.CREN002ATests.BlackScholesPut().
Price_AmericanCall_NoDividend_EqualsEuropean()
void Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_AmericanCall_NoDividend_EqualsEuropean () inline
Definition at line 133 of file CREN002ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN002ATests._engine, Alaris.Test.Unit.Core.Pricing.CREN002ATests.BlackScholesCall(), Alaris.Core.Pricing.CREN002A.Price(), and Alaris.Test.Unit.Core.Pricing.CREN002ATests.Tolerance.
Price_AmericanPut_AtLeastEqualToEuropean()
void Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_AmericanPut_AtLeastEqualToEuropean () inline
Definition at line 112 of file CREN002ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN002ATests._engine, Alaris.Test.Unit.Core.Pricing.CREN002ATests.BlackScholesPut(), and Alaris.Core.Pricing.CREN002A.Price().
Price_ATMCall_ReturnsPositiveValue()
void Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_ATMCall_ReturnsPositiveValue () inline
Definition at line 32 of file CREN002ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN002ATests._engine, and Alaris.Core.Pricing.CREN002A.Price().
Price_ATMPut_ReturnsPositiveValue()
void Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_ATMPut_ReturnsPositiveValue () inline
Definition at line 51 of file CREN002ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN002ATests._engine, and Alaris.Core.Pricing.CREN002A.Price().
Price_Call_MonotonicInSpot()
void Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_Call_MonotonicInSpot () inline
Definition at line 157 of file CREN002ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN002ATests._engine, and Alaris.Core.Pricing.CREN002A.Price().
Price_DeepITMCall_ApproachesIntrinsicValue()
void Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_DeepITMCall_ApproachesIntrinsicValue () inline
Definition at line 70 of file CREN002ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN002ATests._engine, and Alaris.Core.Pricing.CREN002A.Price().
Price_DeepOTMCall_ApproachesZero()
void Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_DeepOTMCall_ApproachesZero () inline
Definition at line 89 of file CREN002ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN002ATests._engine, and Alaris.Core.Pricing.CREN002A.Price().
Price_InvalidSpot_ThrowsException()
void Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_InvalidSpot_ThrowsException () inline
Definition at line 349 of file CREN002ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN002ATests._engine, and Alaris.Core.Pricing.CREN002A.Price().
Price_InvalidVolatility_ThrowsException()
void Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_InvalidVolatility_ThrowsException () inline
Definition at line 356 of file CREN002ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN002ATests._engine, and Alaris.Core.Pricing.CREN002A.Price().
Price_MonotonicIncreasingInTime()
void Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_MonotonicIncreasingInTime () inline
Definition at line 211 of file CREN002ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN002ATests._engine, and Alaris.Core.Pricing.CREN002A.Price().
Price_MonotonicIncreasingInVolatility()
void Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_MonotonicIncreasingInVolatility () inline
Definition at line 193 of file CREN002ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN002ATests._engine, and Alaris.Core.Pricing.CREN002A.Price().
Price_Put_MonotonicDecreasingInSpot()
void Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_Put_MonotonicDecreasingInSpot () inline
Definition at line 175 of file CREN002ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN002ATests._engine, and Alaris.Core.Pricing.CREN002A.Price().
Price_VariousRates_ReturnsValidPrice()
void Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_VariousRates_ReturnsValidPrice (double r, double q) inline
Definition at line 336 of file CREN002ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN002ATests._engine, and Alaris.Core.Pricing.CREN002A.Price().
Price_ZeroTimeToExpiry_ReturnsIntrinsic()
void Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_ZeroTimeToExpiry_ReturnsIntrinsic () inline
Definition at line 321 of file CREN002ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN002ATests._engine, and Alaris.Core.Pricing.CREN002A.Price().
Theta_PutTypicallyNegative()
void Alaris.Test.Unit.Core.Pricing.CREN002ATests.Theta_PutTypicallyNegative () inline
Definition at line 299 of file CREN002ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN002ATests._engine, and Alaris.Core.Pricing.CREN002A.Theta().
Vega_AlwaysPositive()
void Alaris.Test.Unit.Core.Pricing.CREN002ATests.Vega_AlwaysPositive () inline
Definition at line 283 of file CREN002ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN002ATests._engine, and Alaris.Core.Pricing.CREN002A.Vega().
Member Data Documentation
_engine
readonly CREN002A Alaris.Test.Unit.Core.Pricing.CREN002ATests._engine private
Definition at line 21 of file CREN002ATests.cs.
Referenced by Alaris.Test.Unit.Core.Pricing.CREN002ATests.CREN002ATests(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Delta_Call_BoundedZeroToOne(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Delta_Put_BoundedMinusOneToZero(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Gamma_AlwaysPositive(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_AmericanCall_NoDividend_EqualsEuropean(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_AmericanPut_AtLeastEqualToEuropean(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_ATMCall_ReturnsPositiveValue(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_ATMPut_ReturnsPositiveValue(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_Call_MonotonicInSpot(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_DeepITMCall_ApproachesIntrinsicValue(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_DeepOTMCall_ApproachesZero(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_InvalidSpot_ThrowsException(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_InvalidVolatility_ThrowsException(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_MonotonicIncreasingInTime(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_MonotonicIncreasingInVolatility(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_Put_MonotonicDecreasingInSpot(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_VariousRates_ReturnsValidPrice(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_ZeroTimeToExpiry_ReturnsIntrinsic(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Theta_PutTypicallyNegative(), and Alaris.Test.Unit.Core.Pricing.CREN002ATests.Vega_AlwaysPositive().
Tolerance
const double Alaris.Test.Unit.Core.Pricing.CREN002ATests.Tolerance = 0.05 static private
Definition at line 22 of file CREN002ATests.cs.
Referenced by Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_AmericanCall_NoDividend_EqualsEuropean().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/Core/Pricing/CREN002ATests.cs