Alaris: Alaris.Strategy.Core.Numerical.STPR002C Class Reference
Alaris.Strategy.Core.Numerical.STPR002C Class Reference
Unified numerical integration facade that automatically selects optimal implementation. Component ID: STPR002C.
Static Public Member Functions
static double double Error Integrate (Func< double, double > f, double a, double b, double absoluteTolerance=1e-8, double relativeTolerance=1e-6)
static double double Error IntegrateToInfinity (Func< double, double > f, double a, double absoluteTolerance=1e-8, double relativeTolerance=1e-6)
static Complex double Error IntegrateComplexToInfinity (Func< double, Complex > f, double a, double absoluteTolerance=1e-8, double relativeTolerance=1e-6)
Static Public Attributes
static double Value
Integrates a real function over [a, b] using optimal implementation.
static Complex Value
Integrates a complex function from a to infinity using optimal implementation.
Properties
static bool IsAvx2Supported [get]
Indicates if AVX2-accelerated integration is available.
Detailed Description
Unified numerical integration facade that automatically selects optimal implementation. Component ID: STPR002C.
Dispatches to either:
STPR002B - AVX2-accelerated 32-point Gauss-Legendre (if AVX2 available)
STPR002A - MathNet.Numerics 128-point Gauss-Legendre (fallback)
Use this facade in hot paths for automatic hardware optimization.
Definition at line 25 of file STPR002C.cs.
Member Function Documentation
Integrate()
static double double Error Alaris.Strategy.Core.Numerical.STPR002C.Integrate (Func< double, double > f, double a, double b, double absoluteTolerance = 1e-8, double relativeTolerance = 1e-6) inline static
Definition at line 36 of file STPR002C.cs.
References Alaris.Strategy.Core.Numerical.STPR002B.Integrate(), Alaris.Strategy.Core.Numerical.STPR002A.Integrate(), and Alaris.Strategy.Core.Numerical.STPR002C.IsAvx2Supported.
IntegrateComplexToInfinity()
static Complex double Error Alaris.Strategy.Core.Numerical.STPR002C.IntegrateComplexToInfinity (Func< double, Complex > f, double a, double absoluteTolerance = 1e-8, double relativeTolerance = 1e-6) inline static
Definition at line 80 of file STPR002C.cs.
References Alaris.Strategy.Core.Numerical.STPR002B.IntegrateComplexToInfinity(), Alaris.Strategy.Core.Numerical.STPR002A.IntegrateComplexToInfinity(), and Alaris.Strategy.Core.Numerical.STPR002C.IsAvx2Supported.
IntegrateToInfinity()
static double double Error Alaris.Strategy.Core.Numerical.STPR002C.IntegrateToInfinity (Func< double, double > f, double a, double absoluteTolerance = 1e-8, double relativeTolerance = 1e-6) inline static
Definition at line 60 of file STPR002C.cs.
References Alaris.Strategy.Core.Numerical.STPR002B.IntegrateToInfinity(), Alaris.Strategy.Core.Numerical.STPR002A.IntegrateToInfinity(), and Alaris.Strategy.Core.Numerical.STPR002C.IsAvx2Supported.
Referenced by Alaris.Strategy.Core.STPR006A.ComputePrice(), and Alaris.Strategy.Core.STPR003A.ComputeProbability().
Member Data Documentation
Value [1/2]
static double Alaris.Strategy.Core.Numerical.STPR002C.Value static
Integrates a real function over [a, b] using optimal implementation.
Integrates from a to infinity using optimal implementation.
Definition at line 36 of file STPR002C.cs.
Value [2/2]
Complex Alaris.Strategy.Core.Numerical.STPR002C.Value static
Integrates a complex function from a to infinity using optimal implementation.
Definition at line 80 of file STPR002C.cs.
Property Documentation
IsAvx2Supported
bool Alaris.Strategy.Core.Numerical.STPR002C.IsAvx2Supported static get
Indicates if AVX2-accelerated integration is available.
Definition at line 30 of file STPR002C.cs.
Referenced by Alaris.Strategy.Core.Numerical.STPR002C.Integrate(), Alaris.Strategy.Core.Numerical.STPR002C.IntegrateComplexToInfinity(), and Alaris.Strategy.Core.Numerical.STPR002C.IntegrateToInfinity().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Core/Numerical/STPR002C.cs