Alaris: Alaris.Test.Unit.TSUN032A Class Reference
Alaris.Test.Unit.TSUN032A Class Reference
TSUN032A: Unit tests for AlgorithmBounds validation (CRVL001A).
Public Member Functions
void ValidateDoubleBoundaryInputs_ValidInputs_DoesNotThrow ()
Valid inputs should not throw.
void ValidateDoubleBoundaryInputs_InvalidVolatility_ThrowsBoundsViolation (double volatility)
Negative volatility should throw BoundsViolationException.
void ValidateDoubleBoundaryInputs_InvalidMaturity_ThrowsBoundsViolation (double maturity)
Zero or negative maturity should throw.
void ValidateDoubleBoundaryInputs_InvalidSpot_ThrowsBoundsViolation (double spot)
Non-positive spot price should throw.
void ValidateDoubleBoundaryInputs_ExtremeMoneynessS_ThrowsBoundsViolation (double spot, double strike)
Extreme moneyness (|ln(K/S)| > 3) should throw.
void ValidateDoubleBoundaryInputs_NegativeRates_DoesNotThrow ()
Negative rates should be allowed (double boundary regime).
void ValidateDoubleBoundaryInputs_InvalidRates_ThrowsBoundsViolation (double rate, double dividend)
NaN/Infinity rates should throw.
void TryValidateDoubleBoundaryInputs_ValidInputs_ReturnsTrue ()
TryValidate returns true for valid inputs.
void TryValidateDoubleBoundaryInputs_InvalidInputs_ReturnsFalseWithError ()
TryValidate returns false with error message for invalid inputs.
void ValidateVolatility_BoundsCheck (double sigma, bool shouldPass)
Validates individual volatility bounds.
void ValidateTimeToExpiry_BoundsCheck (double tau, bool shouldPass)
Validates individual time to expiry bounds.
Detailed Description
TSUN032A: Unit tests for AlgorithmBounds validation (CRVL001A).
Definition at line 26 of file TSUN032A.cs.
Member Function Documentation
TryValidateDoubleBoundaryInputs_InvalidInputs_ReturnsFalseWithError()
void Alaris.Test.Unit.TSUN032A.TryValidateDoubleBoundaryInputs_InvalidInputs_ReturnsFalseWithError () inline
TryValidate returns false with error message for invalid inputs.
Definition at line 195 of file TSUN032A.cs.
References Alaris.Core.Validation.AlgorithmBounds.TryValidateDoubleBoundaryInputs().
TryValidateDoubleBoundaryInputs_ValidInputs_ReturnsTrue()
void Alaris.Test.Unit.TSUN032A.TryValidateDoubleBoundaryInputs_ValidInputs_ReturnsTrue () inline
TryValidate returns true for valid inputs.
Definition at line 176 of file TSUN032A.cs.
References Alaris.Core.Validation.AlgorithmBounds.TryValidateDoubleBoundaryInputs().
ValidateDoubleBoundaryInputs_ExtremeMoneynessS_ThrowsBoundsViolation()
void Alaris.Test.Unit.TSUN032A.ValidateDoubleBoundaryInputs_ExtremeMoneynessS_ThrowsBoundsViolation (double spot, double strike) inline
Extreme moneyness (|ln(K/S)| > 3) should throw.
Definition at line 119 of file TSUN032A.cs.
References Alaris.Core.Validation.AlgorithmBounds.ValidateDoubleBoundaryInputs().
ValidateDoubleBoundaryInputs_InvalidMaturity_ThrowsBoundsViolation()
void Alaris.Test.Unit.TSUN032A.ValidateDoubleBoundaryInputs_InvalidMaturity_ThrowsBoundsViolation (double maturity) inline
Zero or negative maturity should throw.
Definition at line 83 of file TSUN032A.cs.
References Alaris.Core.Validation.AlgorithmBounds.ValidateDoubleBoundaryInputs().
ValidateDoubleBoundaryInputs_InvalidRates_ThrowsBoundsViolation()
void Alaris.Test.Unit.TSUN032A.ValidateDoubleBoundaryInputs_InvalidRates_ThrowsBoundsViolation (double rate, double dividend) inline
NaN/Infinity rates should throw.
Definition at line 159 of file TSUN032A.cs.
References Alaris.Core.Validation.AlgorithmBounds.ValidateDoubleBoundaryInputs().
ValidateDoubleBoundaryInputs_InvalidSpot_ThrowsBoundsViolation()
void Alaris.Test.Unit.TSUN032A.ValidateDoubleBoundaryInputs_InvalidSpot_ThrowsBoundsViolation (double spot) inline
Non-positive spot price should throw.
Definition at line 102 of file TSUN032A.cs.
References Alaris.Core.Validation.AlgorithmBounds.ValidateDoubleBoundaryInputs().
ValidateDoubleBoundaryInputs_InvalidVolatility_ThrowsBoundsViolation()
void Alaris.Test.Unit.TSUN032A.ValidateDoubleBoundaryInputs_InvalidVolatility_ThrowsBoundsViolation (double volatility) inline
Negative volatility should throw BoundsViolationException.
Definition at line 63 of file TSUN032A.cs.
References Alaris.Core.Validation.AlgorithmBounds.ValidateDoubleBoundaryInputs().
ValidateDoubleBoundaryInputs_NegativeRates_DoesNotThrow()
void Alaris.Test.Unit.TSUN032A.ValidateDoubleBoundaryInputs_NegativeRates_DoesNotThrow () inline
Negative rates should be allowed (double boundary regime).
Definition at line 134 of file TSUN032A.cs.
References Alaris.Core.Validation.AlgorithmBounds.ValidateDoubleBoundaryInputs().
ValidateDoubleBoundaryInputs_ValidInputs_DoesNotThrow()
void Alaris.Test.Unit.TSUN032A.ValidateDoubleBoundaryInputs_ValidInputs_DoesNotThrow () inline
Valid inputs should not throw.
Definition at line 33 of file TSUN032A.cs.
References Alaris.Core.Validation.AlgorithmBounds.ValidateDoubleBoundaryInputs().
ValidateTimeToExpiry_BoundsCheck()
void Alaris.Test.Unit.TSUN032A.ValidateTimeToExpiry_BoundsCheck (double tau, bool shouldPass) inline
Validates individual time to expiry bounds.
Definition at line 248 of file TSUN032A.cs.
References Alaris.Core.Validation.AlgorithmBounds.ValidateTimeToExpiry().
ValidateVolatility_BoundsCheck()
void Alaris.Test.Unit.TSUN032A.ValidateVolatility_BoundsCheck (double sigma, bool shouldPass) inline
Validates individual volatility bounds.
Definition at line 222 of file TSUN032A.cs.
References Alaris.Core.Validation.AlgorithmBounds.ValidateVolatility().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN032A.cs