Alaris: Alaris.Strategy.Cost.STCS006A Class Reference
Alaris.Strategy.Cost.STCS006A Class Reference sealed
Validates that trading signals survive execution costs.
Public Member Functions
STCS006A (STCS001A costModel, double minimumPostCostRatio=DefaultMinimumPostCostRatio, double maximumSlippagePercent=DefaultMaximumSlippagePercent, double maximumExecutionCostPercent=DefaultMaximumExecutionCostPercent, ILogger< STCS006A >? logger=null)
Initialises a new instance of the signal cost validator.
STCS007A Validate (Signal signal, STCS002A frontLegParams, STCS002A backLegParams)
Validates that a signal survives execution costs.
IReadOnlyList< STCS007A > ValidateBatch (IReadOnlyList<(Signal Signal, STCS002A FrontParams, STCS002A BackParams)> signalsWithParams)
Validates multiple signals in batch.
Static Public Attributes
const double DefaultMinimumPostCostRatio = 1.20
Default minimum IV/RV ratio after costs.
const double DefaultMaximumSlippagePercent = 10.0
Default maximum acceptable slippage percentage.
const double DefaultMaximumExecutionCostPercent = 5.0
Default maximum execution cost as percentage of capital.
Private Member Functions
void SafeLog (Action logAction)
Safely executes logging operation with fault isolation (Rule 15).
Static Private Member Functions
static double ComputePostCostRatio (double preCostRatio, STCS004A spreadCost)
Computes the post-cost IV/RV ratio.
Private Attributes
readonly STCS001A _costModel
readonly? ILogger< STCS006A > _logger
readonly double _minimumPostCostIVRVRatio
readonly double _maximumSlippagePercent
readonly double _maximumExecutionCostPercent
Static Private Attributes
static readonly Action< ILogger, string, double, double, bool, Exception?> LogValidationResult
static readonly Action< ILogger, string, double, double, Exception?> LogSlippageWarning
static readonly Action< ILogger, string, Exception?> LogValidationError
Detailed Description
Validates that trading signals survive execution costs.
Definition at line 17 of file STCS006A.cs.
Constructor & Destructor Documentation
STCS006A()
Alaris.Strategy.Cost.STCS006A.STCS006A (STCS001A costModel, double minimumPostCostRatio = DefaultMinimumPostCostRatio, double maximumSlippagePercent = DefaultMaximumSlippagePercent, double maximumExecutionCostPercent = DefaultMaximumExecutionCostPercent, ILogger< STCS006A >? logger = null) inline
Initialises a new instance of the signal cost validator.
Parameters
costModel The execution cost model to use.
minimumPostCostRatio Minimum IV/RV ratio after costs. Default: 1.20.
maximumSlippagePercent Maximum acceptable slippage percentage. Default: 10%.
maximumExecutionCostPercent Maximum execution cost as percentage of capital. Default: 5%.
logger Optional logger instance.
Exceptions
ArgumentNullException Thrown when costModel is null.
Definition at line 79 of file STCS006A.cs.
References Alaris.Strategy.Cost.STCS006A._costModel, Alaris.Strategy.Cost.STCS006A._logger, Alaris.Strategy.Cost.STCS006A._maximumExecutionCostPercent, Alaris.Strategy.Cost.STCS006A._maximumSlippagePercent, and Alaris.Strategy.Cost.STCS006A._minimumPostCostIVRVRatio.
Member Function Documentation
ComputePostCostRatio()
static double Alaris.Strategy.Cost.STCS006A.ComputePostCostRatio (double preCostRatio, STCS004A spreadCost) inline static private
Computes the post-cost IV/RV ratio.
Parameters
preCostRatio The original IV/RV ratio from signal generation.
spreadCost The computed spread execution cost.
Returns
The adjusted IV/RV ratio accounting for costs.
Definition at line 178 of file STCS006A.cs.
Referenced by Alaris.Strategy.Cost.STCS006A.Validate().
SafeLog()
void Alaris.Strategy.Cost.STCS006A.SafeLog (Action logAction) inline private
Safely executes logging operation with fault isolation (Rule 15).
Definition at line 216 of file STCS006A.cs.
References Alaris.Strategy.Cost.STCS006A._logger.
Referenced by Alaris.Strategy.Cost.STCS006A.Validate().
Validate()
STCS007A Alaris.Strategy.Cost.STCS006A.Validate (Signal signal, STCS002A frontLegParams, STCS002A backLegParams) inline
Validates that a signal survives execution costs.
Parameters
signal The trading signal to validate.
frontLegParams Front-month option parameters.
backLegParams Back-month option parameters.
Returns
Validation result with detailed metrics.
Exceptions
ArgumentNullException Thrown when any parameter is null.
Definition at line 103 of file STCS006A.cs.
References Alaris.Strategy.Cost.STCS006A._costModel, Alaris.Strategy.Cost.STCS006A._logger, Alaris.Strategy.Cost.STCS006A._maximumExecutionCostPercent, Alaris.Strategy.Cost.STCS006A._maximumSlippagePercent, Alaris.Strategy.Cost.STCS006A._minimumPostCostIVRVRatio, Alaris.Strategy.Cost.STCS006A.ComputePostCostRatio(), Alaris.Strategy.Cost.STCS001A.ComputeSpreadCost(), Alaris.Strategy.Cost.STCS006A.LogSlippageWarning, Alaris.Strategy.Cost.STCS006A.LogValidationError, Alaris.Strategy.Cost.STCS006A.LogValidationResult, Alaris.Strategy.Cost.STCS006A.SafeLog(), Alaris.Strategy.Cost.STCS004A, and Alaris.Strategy.Cost.STCS007A.
Referenced by Alaris.Strategy.Hedge.STHD005A.Validate(), and Alaris.Strategy.Cost.STCS006A.ValidateBatch().
ValidateBatch()
IReadOnlyList< STCS007A > Alaris.Strategy.Cost.STCS006A.ValidateBatch (IReadOnlyList<(Signal Signal, STCS002A FrontParams, STCS002A BackParams)> signalsWithParams) inline
Validates multiple signals in batch.
Parameters
signalsWithParams Collection of signals with their corresponding option parameters.
Returns
Validation results for all signals.
Definition at line 197 of file STCS006A.cs.
References Alaris.Strategy.Cost.STCS002A, Alaris.Strategy.Cost.STCS007A, and Alaris.Strategy.Cost.STCS006A.Validate().
Member Data Documentation
_costModel
readonly STCS001A Alaris.Strategy.Cost.STCS006A._costModel private
Definition at line 19 of file STCS006A.cs.
Referenced by Alaris.Strategy.Cost.STCS006A.STCS006A(), and Alaris.Strategy.Cost.STCS006A.Validate().
_logger
readonly? ILogger<STCS006A> Alaris.Strategy.Cost.STCS006A._logger private
Definition at line 20 of file STCS006A.cs.
Referenced by Alaris.Strategy.Cost.STCS006A.STCS006A(), Alaris.Strategy.Cost.STCS006A.SafeLog(), and Alaris.Strategy.Cost.STCS006A.Validate().
_maximumExecutionCostPercent
readonly double Alaris.Strategy.Cost.STCS006A._maximumExecutionCostPercent private
Definition at line 23 of file STCS006A.cs.
Referenced by Alaris.Strategy.Cost.STCS006A.STCS006A(), and Alaris.Strategy.Cost.STCS006A.Validate().
_maximumSlippagePercent
readonly double Alaris.Strategy.Cost.STCS006A._maximumSlippagePercent private
Definition at line 22 of file STCS006A.cs.
Referenced by Alaris.Strategy.Cost.STCS006A.STCS006A(), and Alaris.Strategy.Cost.STCS006A.Validate().
_minimumPostCostIVRVRatio
readonly double Alaris.Strategy.Cost.STCS006A._minimumPostCostIVRVRatio private
Definition at line 21 of file STCS006A.cs.
Referenced by Alaris.Strategy.Cost.STCS006A.STCS006A(), and Alaris.Strategy.Cost.STCS006A.Validate().
DefaultMaximumExecutionCostPercent
const double Alaris.Strategy.Cost.STCS006A.DefaultMaximumExecutionCostPercent = 5.0 static
Default maximum execution cost as percentage of capital.
Definition at line 60 of file STCS006A.cs.
DefaultMaximumSlippagePercent
const double Alaris.Strategy.Cost.STCS006A.DefaultMaximumSlippagePercent = 10.0 static
Default maximum acceptable slippage percentage.
Definition at line 54 of file STCS006A.cs.
DefaultMinimumPostCostRatio
const double Alaris.Strategy.Cost.STCS006A.DefaultMinimumPostCostRatio = 1.20 static
Default minimum IV/RV ratio after costs.
Definition at line 48 of file STCS006A.cs.
LogSlippageWarning
readonly Action<ILogger, string, double, double, Exception?> Alaris.Strategy.Cost.STCS006A.LogSlippageWarning static private
Initial value:
=
        LoggerMessage.Define<string, double, double>(
            LogLevel.Warning,
            new EventId(2, nameof(LogSlippageWarning)),
            "High slippage for {Symbol}: {SlippagePercent:F2}% exceeds threshold {Threshold:F2}%")
Definition at line 32 of file STCS006A.cs.
Referenced by Alaris.Strategy.Cost.STCS006A.Validate().
LogValidationError
readonly Action<ILogger, string, Exception?> Alaris.Strategy.Cost.STCS006A.LogValidationError static private
Initial value:
=
        LoggerMessage.Define<string>(
            LogLevel.Error,
            new EventId(3, nameof(LogValidationError)),
            "Error validating costs for {Symbol}")
Definition at line 38 of file STCS006A.cs.
Referenced by Alaris.Strategy.Cost.STCS006A.Validate().
LogValidationResult
readonly Action<ILogger, string, double, double, bool, Exception?> Alaris.Strategy.Cost.STCS006A.LogValidationResult static private
Initial value:
=
        LoggerMessage.Define<string, double, double, bool>(
            LogLevel.Information,
            new EventId(1, nameof(LogValidationResult)),
            "Cost validation for {Symbol}: pre-cost IV/RV={PreCostRatio:F3}, post-cost={PostCostRatio:F3}, passed={Passed}")
Definition at line 26 of file STCS006A.cs.
Referenced by Alaris.Strategy.Cost.STCS006A.Validate().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Cost/STCS006A.cs