Alaris: Alaris.Test.Unit.TSUN026A Class Reference
Alaris.Test.Unit.TSUN026A Class Reference sealed
TSUN026A: Unit tests for execution cost model components. Tests mathematical properties that must hold for all cost calculations.
Public Member Functions
void STCS002A_Validate_ValidParameters_DoesNotThrow ()
Valid order parameters should pass validation.
void STCS002A_Validate_InvalidContracts_Throws (int contracts)
Zero or negative contract count should fail validation.
void STCS002A_Validate_NegativeMidPrice_Throws ()
Negative mid price should fail validation.
void STCS002A_Validate_AskLessThanBid_Throws ()
Ask price less than bid price should fail validation.
void STCS002A_BidAskSpread_EqualsAskMinusBid ()
BidAskSpread computed property should equal Ask - Bid.
void STCS002A_HalfSpread_EqualsSpreadDividedByTwo ()
HalfSpread should equal BidAskSpread / 2.
void STCS005A_DefaultConstructor_UsesStandardFees ()
Default constructor should use standard fee values.
void STCS005A_Constructor_NegativeFees_Throws (double fee, double exchange, double regulatory)
Negative fees should throw ArgumentOutOfRangeException.
void STCS003A_TotalCost_EqualsSumOfComponents ()
INVARIANT: TotalCost = Commission + ExchangeFees + RegulatoryFees + Slippage.
void STCS003A_AllComponents_AreNonNegative ()
INVARIANT: All cost components must be non-negative.
void STCS003A_Costs_ScaleLinearlyWithContracts (int contracts1, int contracts2)
INVARIANT: Costs scale linearly with contract count.
void STCS003A_BuyOrder_ExecutionPriceIsAsk ()
Buy order should fill at ask price (execution price = ask).
void STCS003A_SellOrder_ExecutionPriceIsBid ()
Sell order should fill at bid price (execution price = bid).
void STCS003A_Slippage_EqualsHalfSpreadTimesContractsTimesMultiplier ()
INVARIANT: Slippage = |ExecutionPrice - MidPrice| × Contracts × Multiplier.
void STCS003A_CostPerContract_EqualsTotalDividedByContracts ()
CostPerContract should equal TotalCost / Contracts.
void STCS004A_TotalExecutionCost_IsSumOfLegs ()
INVARIANT: TotalExecutionCost = FrontLegCost.TotalCost + BackLegCost.TotalCost.
void STCS004A_TotalSlippage_IsSumOfLegSlippages ()
INVARIANT: TotalSlippage = FrontLegSlippage + BackLegSlippage.
void STCS004A_TheoreticalDebit_EqualsBackMidMinusFrontMid ()
INVARIANT: TheoreticalDebit = BackMidPrice - FrontMidPrice.
void STCS004A_ExecutionDebit_EqualsBackAskMinusFrontBid ()
INVARIANT: ExecutionDebit = BackAsk - FrontBid (worst-case fill for debit spread).
void STCS004A_ExecutionDebit_GreaterOrEqualToTheoreticalDebit ()
INVARIANT: ExecutionDebit ≥ TheoreticalDebit (slippage always increases cost).
void STCS004A_TotalCapitalRequired_IncludesDebitAndFees ()
TotalCapitalRequired should include debit and all fees.
void STCS003A_ZeroSpread_ProducesZeroSlippage ()
Zero bid-ask spread should produce zero slippage.
void STCS003A_SingleContract_ComputesCorrectly ()
Single contract should compute correctly.
void STCS003A_ZeroCostModel_OnlyHasSlippage ()
Zero-cost model (all fees = 0) should only have slippage.
void STCS005A_ImplementsInterface ()
STCS005A should implement STCS001A interface.
void STCS005A_ComputeOptionCost_NullParams_Throws ()
Null parameters should throw ArgumentNullException.
void STCS005A_ComputeSpreadCost_NullParams_Throws ()
Null parameters for spread cost should throw ArgumentNullException.
void STCS004A_TypicalCalendarSpread_RealisticCosts ()
Typical AAPL calendar spread cost calculation.
void STCS003A_WideSpread_HigherSlippagePercent ()
Wide spread options (low liquidity) should have higher slippage percentage.
Static Private Member Functions
static STCS002A CreateValidBuyOrderParams ()
static STCS002A CreateValidSellOrderParams ()
static STCS005A CreateDefaultCostModel ()
Detailed Description
TSUN026A: Unit tests for execution cost model components. Tests mathematical properties that must hold for all cost calculations.
Definition at line 33 of file TSUN026A.cs.
Member Function Documentation
CreateDefaultCostModel()
static STCS005A Alaris.Test.Unit.TSUN026A.CreateDefaultCostModel () static private
Referenced by Alaris.Test.Unit.TSUN026A.STCS003A_AllComponents_AreNonNegative(), Alaris.Test.Unit.TSUN026A.STCS003A_BuyOrder_ExecutionPriceIsAsk(), Alaris.Test.Unit.TSUN026A.STCS003A_CostPerContract_EqualsTotalDividedByContracts(), Alaris.Test.Unit.TSUN026A.STCS003A_Costs_ScaleLinearlyWithContracts(), Alaris.Test.Unit.TSUN026A.STCS003A_SellOrder_ExecutionPriceIsBid(), Alaris.Test.Unit.TSUN026A.STCS003A_Slippage_EqualsHalfSpreadTimesContractsTimesMultiplier(), Alaris.Test.Unit.TSUN026A.STCS003A_TotalCost_EqualsSumOfComponents(), Alaris.Test.Unit.TSUN026A.STCS003A_WideSpread_HigherSlippagePercent(), Alaris.Test.Unit.TSUN026A.STCS003A_ZeroSpread_ProducesZeroSlippage(), Alaris.Test.Unit.TSUN026A.STCS004A_ExecutionDebit_EqualsBackAskMinusFrontBid(), Alaris.Test.Unit.TSUN026A.STCS004A_ExecutionDebit_GreaterOrEqualToTheoreticalDebit(), Alaris.Test.Unit.TSUN026A.STCS004A_TheoreticalDebit_EqualsBackMidMinusFrontMid(), Alaris.Test.Unit.TSUN026A.STCS004A_TotalCapitalRequired_IncludesDebitAndFees(), Alaris.Test.Unit.TSUN026A.STCS004A_TotalExecutionCost_IsSumOfLegs(), Alaris.Test.Unit.TSUN026A.STCS004A_TotalSlippage_IsSumOfLegSlippages(), Alaris.Test.Unit.TSUN026A.STCS004A_TypicalCalendarSpread_RealisticCosts(), Alaris.Test.Unit.TSUN026A.STCS005A_ComputeOptionCost_NullParams_Throws(), and Alaris.Test.Unit.TSUN026A.STCS005A_ComputeSpreadCost_NullParams_Throws().
CreateValidBuyOrderParams()
static STCS002A Alaris.Test.Unit.TSUN026A.CreateValidBuyOrderParams () static private
Referenced by Alaris.Test.Unit.TSUN026A.STCS002A_BidAskSpread_EqualsAskMinusBid(), Alaris.Test.Unit.TSUN026A.STCS002A_HalfSpread_EqualsSpreadDividedByTwo(), Alaris.Test.Unit.TSUN026A.STCS002A_Validate_AskLessThanBid_Throws(), Alaris.Test.Unit.TSUN026A.STCS002A_Validate_InvalidContracts_Throws(), Alaris.Test.Unit.TSUN026A.STCS002A_Validate_NegativeMidPrice_Throws(), Alaris.Test.Unit.TSUN026A.STCS002A_Validate_ValidParameters_DoesNotThrow(), Alaris.Test.Unit.TSUN026A.STCS003A_AllComponents_AreNonNegative(), Alaris.Test.Unit.TSUN026A.STCS003A_BuyOrder_ExecutionPriceIsAsk(), Alaris.Test.Unit.TSUN026A.STCS003A_CostPerContract_EqualsTotalDividedByContracts(), Alaris.Test.Unit.TSUN026A.STCS003A_Costs_ScaleLinearlyWithContracts(), Alaris.Test.Unit.TSUN026A.STCS003A_SingleContract_ComputesCorrectly(), Alaris.Test.Unit.TSUN026A.STCS003A_Slippage_EqualsHalfSpreadTimesContractsTimesMultiplier(), Alaris.Test.Unit.TSUN026A.STCS003A_TotalCost_EqualsSumOfComponents(), Alaris.Test.Unit.TSUN026A.STCS003A_WideSpread_HigherSlippagePercent(), Alaris.Test.Unit.TSUN026A.STCS003A_ZeroCostModel_OnlyHasSlippage(), Alaris.Test.Unit.TSUN026A.STCS003A_ZeroSpread_ProducesZeroSlippage(), Alaris.Test.Unit.TSUN026A.STCS004A_ExecutionDebit_EqualsBackAskMinusFrontBid(), Alaris.Test.Unit.TSUN026A.STCS004A_ExecutionDebit_GreaterOrEqualToTheoreticalDebit(), Alaris.Test.Unit.TSUN026A.STCS004A_TheoreticalDebit_EqualsBackMidMinusFrontMid(), Alaris.Test.Unit.TSUN026A.STCS004A_TotalCapitalRequired_IncludesDebitAndFees(), Alaris.Test.Unit.TSUN026A.STCS004A_TotalExecutionCost_IsSumOfLegs(), Alaris.Test.Unit.TSUN026A.STCS004A_TotalSlippage_IsSumOfLegSlippages(), and Alaris.Test.Unit.TSUN026A.STCS005A_ComputeSpreadCost_NullParams_Throws().
CreateValidSellOrderParams()
static STCS002A Alaris.Test.Unit.TSUN026A.CreateValidSellOrderParams () static private
Referenced by Alaris.Test.Unit.TSUN026A.STCS003A_SellOrder_ExecutionPriceIsBid(), Alaris.Test.Unit.TSUN026A.STCS004A_ExecutionDebit_EqualsBackAskMinusFrontBid(), Alaris.Test.Unit.TSUN026A.STCS004A_ExecutionDebit_GreaterOrEqualToTheoreticalDebit(), Alaris.Test.Unit.TSUN026A.STCS004A_TheoreticalDebit_EqualsBackMidMinusFrontMid(), Alaris.Test.Unit.TSUN026A.STCS004A_TotalCapitalRequired_IncludesDebitAndFees(), Alaris.Test.Unit.TSUN026A.STCS004A_TotalExecutionCost_IsSumOfLegs(), and Alaris.Test.Unit.TSUN026A.STCS004A_TotalSlippage_IsSumOfLegSlippages().
STCS002A_BidAskSpread_EqualsAskMinusBid()
void Alaris.Test.Unit.TSUN026A.STCS002A_BidAskSpread_EqualsAskMinusBid () inline
BidAskSpread computed property should equal Ask - Bid.
Definition at line 135 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateValidBuyOrderParams().
STCS002A_HalfSpread_EqualsSpreadDividedByTwo()
void Alaris.Test.Unit.TSUN026A.STCS002A_HalfSpread_EqualsSpreadDividedByTwo () inline
HalfSpread should equal BidAskSpread / 2.
Definition at line 153 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateValidBuyOrderParams().
STCS002A_Validate_AskLessThanBid_Throws()
void Alaris.Test.Unit.TSUN026A.STCS002A_Validate_AskLessThanBid_Throws () inline
Ask price less than bid price should fail validation.
Definition at line 116 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateValidBuyOrderParams().
STCS002A_Validate_InvalidContracts_Throws()
void Alaris.Test.Unit.TSUN026A.STCS002A_Validate_InvalidContracts_Throws (int contracts) inline
Zero or negative contract count should fail validation.
Definition at line 86 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateValidBuyOrderParams().
STCS002A_Validate_NegativeMidPrice_Throws()
void Alaris.Test.Unit.TSUN026A.STCS002A_Validate_NegativeMidPrice_Throws () inline
Negative mid price should fail validation.
Definition at line 101 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateValidBuyOrderParams().
STCS002A_Validate_ValidParameters_DoesNotThrow()
void Alaris.Test.Unit.TSUN026A.STCS002A_Validate_ValidParameters_DoesNotThrow () inline
Valid order parameters should pass validation.
Definition at line 69 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateValidBuyOrderParams().
STCS003A_AllComponents_AreNonNegative()
void Alaris.Test.Unit.TSUN026A.STCS003A_AllComponents_AreNonNegative () inline
INVARIANT: All cost components must be non-negative.
Definition at line 222 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateDefaultCostModel(), Alaris.Test.Unit.TSUN026A.CreateValidBuyOrderParams(), and Alaris.Strategy.Cost.STCS003A.
STCS003A_BuyOrder_ExecutionPriceIsAsk()
void Alaris.Test.Unit.TSUN026A.STCS003A_BuyOrder_ExecutionPriceIsAsk () inline
Buy order should fill at ask price (execution price = ask).
Definition at line 266 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateDefaultCostModel(), Alaris.Test.Unit.TSUN026A.CreateValidBuyOrderParams(), and Alaris.Strategy.Cost.STCS003A.
STCS003A_CostPerContract_EqualsTotalDividedByContracts()
void Alaris.Test.Unit.TSUN026A.STCS003A_CostPerContract_EqualsTotalDividedByContracts () inline
CostPerContract should equal TotalCost / Contracts.
Definition at line 320 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateDefaultCostModel(), Alaris.Test.Unit.TSUN026A.CreateValidBuyOrderParams(), and Alaris.Strategy.Cost.STCS003A.
STCS003A_Costs_ScaleLinearlyWithContracts()
void Alaris.Test.Unit.TSUN026A.STCS003A_Costs_ScaleLinearlyWithContracts (int contracts1, int contracts2) inline
INVARIANT: Costs scale linearly with contract count.
Definition at line 246 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateDefaultCostModel(), Alaris.Test.Unit.TSUN026A.CreateValidBuyOrderParams(), and Alaris.Strategy.Cost.STCS003A.
STCS003A_SellOrder_ExecutionPriceIsBid()
void Alaris.Test.Unit.TSUN026A.STCS003A_SellOrder_ExecutionPriceIsBid () inline
Sell order should fill at bid price (execution price = bid).
Definition at line 283 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateDefaultCostModel(), Alaris.Test.Unit.TSUN026A.CreateValidSellOrderParams(), and Alaris.Strategy.Cost.STCS003A.
STCS003A_SingleContract_ComputesCorrectly()
void Alaris.Test.Unit.TSUN026A.STCS003A_SingleContract_ComputesCorrectly () inline
Single contract should compute correctly.
Definition at line 479 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateValidBuyOrderParams(), and Alaris.Strategy.Cost.STCS003A.
STCS003A_Slippage_EqualsHalfSpreadTimesContractsTimesMultiplier()
void Alaris.Test.Unit.TSUN026A.STCS003A_Slippage_EqualsHalfSpreadTimesContractsTimesMultiplier () inline
INVARIANT: Slippage = |ExecutionPrice - MidPrice| × Contracts × Multiplier.
Definition at line 300 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateDefaultCostModel(), Alaris.Test.Unit.TSUN026A.CreateValidBuyOrderParams(), and Alaris.Strategy.Cost.STCS003A.
STCS003A_TotalCost_EqualsSumOfComponents()
void Alaris.Test.Unit.TSUN026A.STCS003A_TotalCost_EqualsSumOfComponents () inline
INVARIANT: TotalCost = Commission + ExchangeFees + RegulatoryFees + Slippage.
Definition at line 203 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateDefaultCostModel(), Alaris.Test.Unit.TSUN026A.CreateValidBuyOrderParams(), and Alaris.Strategy.Cost.STCS003A.
STCS003A_WideSpread_HigherSlippagePercent()
void Alaris.Test.Unit.TSUN026A.STCS003A_WideSpread_HigherSlippagePercent () inline
Wide spread options (low liquidity) should have higher slippage percentage.
Definition at line 619 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateDefaultCostModel(), and Alaris.Test.Unit.TSUN026A.CreateValidBuyOrderParams().
STCS003A_ZeroCostModel_OnlyHasSlippage()
void Alaris.Test.Unit.TSUN026A.STCS003A_ZeroCostModel_OnlyHasSlippage () inline
Zero-cost model (all fees = 0) should only have slippage.
Definition at line 502 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateValidBuyOrderParams(), and Alaris.Strategy.Cost.STCS003A.
STCS003A_ZeroSpread_ProducesZeroSlippage()
void Alaris.Test.Unit.TSUN026A.STCS003A_ZeroSpread_ProducesZeroSlippage () inline
Zero bid-ask spread should produce zero slippage.
Definition at line 457 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateDefaultCostModel(), Alaris.Test.Unit.TSUN026A.CreateValidBuyOrderParams(), and Alaris.Strategy.Cost.STCS003A.
STCS004A_ExecutionDebit_EqualsBackAskMinusFrontBid()
void Alaris.Test.Unit.TSUN026A.STCS004A_ExecutionDebit_EqualsBackAskMinusFrontBid () inline
INVARIANT: ExecutionDebit = BackAsk - FrontBid (worst-case fill for debit spread).
Definition at line 398 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateDefaultCostModel(), Alaris.Test.Unit.TSUN026A.CreateValidBuyOrderParams(), Alaris.Test.Unit.TSUN026A.CreateValidSellOrderParams(), and Alaris.Strategy.Cost.STCS004A.
STCS004A_ExecutionDebit_GreaterOrEqualToTheoreticalDebit()
void Alaris.Test.Unit.TSUN026A.STCS004A_ExecutionDebit_GreaterOrEqualToTheoreticalDebit () inline
INVARIANT: ExecutionDebit ≥ TheoreticalDebit (slippage always increases cost).
Definition at line 417 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateDefaultCostModel(), Alaris.Test.Unit.TSUN026A.CreateValidBuyOrderParams(), Alaris.Test.Unit.TSUN026A.CreateValidSellOrderParams(), and Alaris.Strategy.Cost.STCS004A.
STCS004A_TheoreticalDebit_EqualsBackMidMinusFrontMid()
void Alaris.Test.Unit.TSUN026A.STCS004A_TheoreticalDebit_EqualsBackMidMinusFrontMid () inline
INVARIANT: TheoreticalDebit = BackMidPrice - FrontMidPrice.
Definition at line 379 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateDefaultCostModel(), Alaris.Test.Unit.TSUN026A.CreateValidBuyOrderParams(), Alaris.Test.Unit.TSUN026A.CreateValidSellOrderParams(), and Alaris.Strategy.Cost.STCS004A.
STCS004A_TotalCapitalRequired_IncludesDebitAndFees()
void Alaris.Test.Unit.TSUN026A.STCS004A_TotalCapitalRequired_IncludesDebitAndFees () inline
TotalCapitalRequired should include debit and all fees.
Definition at line 435 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateDefaultCostModel(), Alaris.Test.Unit.TSUN026A.CreateValidBuyOrderParams(), Alaris.Test.Unit.TSUN026A.CreateValidSellOrderParams(), and Alaris.Strategy.Cost.STCS004A.
STCS004A_TotalExecutionCost_IsSumOfLegs()
void Alaris.Test.Unit.TSUN026A.STCS004A_TotalExecutionCost_IsSumOfLegs () inline
INVARIANT: TotalExecutionCost = FrontLegCost.TotalCost + BackLegCost.TotalCost.
Definition at line 341 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateDefaultCostModel(), Alaris.Test.Unit.TSUN026A.CreateValidBuyOrderParams(), Alaris.Test.Unit.TSUN026A.CreateValidSellOrderParams(), and Alaris.Strategy.Cost.STCS004A.
STCS004A_TotalSlippage_IsSumOfLegSlippages()
void Alaris.Test.Unit.TSUN026A.STCS004A_TotalSlippage_IsSumOfLegSlippages () inline
INVARIANT: TotalSlippage = FrontLegSlippage + BackLegSlippage.
Definition at line 360 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateDefaultCostModel(), Alaris.Test.Unit.TSUN026A.CreateValidBuyOrderParams(), Alaris.Test.Unit.TSUN026A.CreateValidSellOrderParams(), and Alaris.Strategy.Cost.STCS004A.
STCS004A_TypicalCalendarSpread_RealisticCosts()
void Alaris.Test.Unit.TSUN026A.STCS004A_TypicalCalendarSpread_RealisticCosts () inline
Typical AAPL calendar spread cost calculation.
Definition at line 574 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateDefaultCostModel(), Alaris.Strategy.Cost.STCS002A, and Alaris.Strategy.Cost.STCS004A.
STCS005A_ComputeOptionCost_NullParams_Throws()
void Alaris.Test.Unit.TSUN026A.STCS005A_ComputeOptionCost_NullParams_Throws () inline
Null parameters should throw ArgumentNullException.
Definition at line 540 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateDefaultCostModel().
STCS005A_ComputeSpreadCost_NullParams_Throws()
void Alaris.Test.Unit.TSUN026A.STCS005A_ComputeSpreadCost_NullParams_Throws () inline
Null parameters for spread cost should throw ArgumentNullException.
Definition at line 554 of file TSUN026A.cs.
References Alaris.Test.Unit.TSUN026A.CreateDefaultCostModel(), and Alaris.Test.Unit.TSUN026A.CreateValidBuyOrderParams().
STCS005A_Constructor_NegativeFees_Throws()
void Alaris.Test.Unit.TSUN026A.STCS005A_Constructor_NegativeFees_Throws (double fee, double exchange, double regulatory) inline
Negative fees should throw ArgumentOutOfRangeException.
Definition at line 189 of file TSUN026A.cs.
STCS005A_DefaultConstructor_UsesStandardFees()
void Alaris.Test.Unit.TSUN026A.STCS005A_DefaultConstructor_UsesStandardFees () inline
Default constructor should use standard fee values.
Definition at line 173 of file TSUN026A.cs.
STCS005A_ImplementsInterface()
void Alaris.Test.Unit.TSUN026A.STCS005A_ImplementsInterface () inline
STCS005A should implement STCS001A interface.
Definition at line 526 of file TSUN026A.cs.
References Alaris.Strategy.Cost.STCS001A.ModelName.
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN026A.cs