Alaris: Alaris.Test.Integration.StrategyIntegrationTests Class Reference
Alaris.Test.Integration.StrategyIntegrationTests Class Reference
Integration tests for the earnings volatility calendar spread strategy. Tests the complete workflow from signal generation to position sizing.
Public Member Functions
void STCR003A_CalculatesVolatilityCorrectly ()
void STCR003A_CalculatesRollingVolatility ()
void STTM001A_IdentifiesInvertedStructure ()
void STTM001A_IdentifiesNormalStructure ()
void STCR001A_GeneratesSTCR004A ()
void STRK001A_CalculatesPosition ()
void STPR001APricing_ValidatesCorrectly ()
async Task STCT001A_EvaluatesOpportunity ()
async Task STBR001A_IntegrationTest_PositiveRates ()
async Task STBR001A_IntegrationTest_NegativeRates ()
async Task STBR001A_STPR001A_PositiveRates ()
async Task STBR001A_STPR001A_NegativeRates ()
async Task STCT001A_WithSTBR001A_FullWorkflow ()
Static Private Member Functions
static List< PriceBar > GenerateSamplePriceBars (int count)
static List< Trade > GenerateSampleTrades (int count)
Detailed Description
Integration tests for the earnings volatility calendar spread strategy. Tests the complete workflow from signal generation to position sizing.
Definition at line 18 of file TSIN002A.cs.
Member Function Documentation
GenerateSamplePriceBars()
static List< PriceBar > Alaris.Test.Integration.StrategyIntegrationTests.GenerateSamplePriceBars (int count) inline static private
Definition at line 363 of file TSIN002A.cs.
References Alaris.Strategy.Risk.Close, Alaris.Strategy.Core.High, and Alaris.Strategy.Core.Low.
Referenced by Alaris.Test.Integration.StrategyIntegrationTests.STCR003A_CalculatesRollingVolatility(), and Alaris.Test.Integration.StrategyIntegrationTests.STCR003A_CalculatesVolatilityCorrectly().
GenerateSampleTrades()
static List< Trade > Alaris.Test.Integration.StrategyIntegrationTests.GenerateSampleTrades (int count) inline static private
Definition at line 392 of file TSIN002A.cs.
Referenced by Alaris.Test.Integration.StrategyIntegrationTests.STCT001A_EvaluatesOpportunity(), Alaris.Test.Integration.StrategyIntegrationTests.STCT001A_WithSTBR001A_FullWorkflow(), and Alaris.Test.Integration.StrategyIntegrationTests.STRK001A_CalculatesPosition().
STBR001A_IntegrationTest_NegativeRates()
async Task Alaris.Test.Integration.StrategyIntegrationTests.STBR001A_IntegrationTest_NegativeRates () inline
Definition at line 230 of file TSIN002A.cs.
STBR001A_IntegrationTest_PositiveRates()
async Task Alaris.Test.Integration.StrategyIntegrationTests.STBR001A_IntegrationTest_PositiveRates () inline
Definition at line 199 of file TSIN002A.cs.
STBR001A_STPR001A_NegativeRates()
async Task Alaris.Test.Integration.StrategyIntegrationTests.STBR001A_STPR001A_NegativeRates () inline
Definition at line 293 of file TSIN002A.cs.
STBR001A_STPR001A_PositiveRates()
async Task Alaris.Test.Integration.StrategyIntegrationTests.STBR001A_STPR001A_PositiveRates () inline
Definition at line 261 of file TSIN002A.cs.
STCR001A_GeneratesSTCR004A()
void Alaris.Test.Integration.StrategyIntegrationTests.STCR001A_GeneratesSTCR004A () inline
Definition at line 98 of file TSIN002A.cs.
STCR003A_CalculatesRollingVolatility()
void Alaris.Test.Integration.StrategyIntegrationTests.STCR003A_CalculatesRollingVolatility () inline
Definition at line 36 of file TSIN002A.cs.
References Alaris.Test.Integration.StrategyIntegrationTests.GenerateSamplePriceBars().
STCR003A_CalculatesVolatilityCorrectly()
void Alaris.Test.Integration.StrategyIntegrationTests.STCR003A_CalculatesVolatilityCorrectly () inline
Definition at line 21 of file TSIN002A.cs.
References Alaris.Test.Integration.StrategyIntegrationTests.GenerateSamplePriceBars().
STCT001A_EvaluatesOpportunity()
async Task Alaris.Test.Integration.StrategyIntegrationTests.STCT001A_EvaluatesOpportunity () inline
Definition at line 169 of file TSIN002A.cs.
References Alaris.Test.Integration.StrategyIntegrationTests.GenerateSampleTrades().
STCT001A_WithSTBR001A_FullWorkflow()
async Task Alaris.Test.Integration.StrategyIntegrationTests.STCT001A_WithSTBR001A_FullWorkflow () inline
Definition at line 324 of file TSIN002A.cs.
References Alaris.Test.Integration.StrategyIntegrationTests.GenerateSampleTrades().
STPR001APricing_ValidatesCorrectly()
void Alaris.Test.Integration.StrategyIntegrationTests.STPR001APricing_ValidatesCorrectly () inline
Definition at line 151 of file TSIN002A.cs.
STRK001A_CalculatesPosition()
void Alaris.Test.Integration.StrategyIntegrationTests.STRK001A_CalculatesPosition () inline
Definition at line 122 of file TSIN002A.cs.
References Alaris.Test.Integration.StrategyIntegrationTests.GenerateSampleTrades().
STTM001A_IdentifiesInvertedStructure()
void Alaris.Test.Integration.StrategyIntegrationTests.STTM001A_IdentifiesInvertedStructure () inline
Definition at line 52 of file TSIN002A.cs.
STTM001A_IdentifiesNormalStructure()
void Alaris.Test.Integration.StrategyIntegrationTests.STTM001A_IdentifiesNormalStructure () inline
Definition at line 76 of file TSIN002A.cs.
The documentation for this class was generated from the following file:
src/Alaris.Test/Integration/TSIN002A.cs