Alaris: Alaris.Strategy.Risk Namespace Reference
Alaris.Strategy.Risk Namespace Reference
Classes
class STMG001A
Provides maturity-based position filtering to avoid near-expiry regime.
class STQT001A
Implements queue-theoretic analysis for position management.
class STRK001A
Implements Kelly Criterion position sizing for options strategies. Uses fractional Kelly (typically 25% of full Kelly) for safety.
class STRK002A
Represents the sizing information for an options position.
class STRK003A
Implements reserve-adjusted Kelly position sizing for concurrent positions.
class STRK004A
Implements priority queue capital allocation for heterogeneous opportunities.
class Trade
Represents a historical trade for Kelly Criterion calculation.
Enumerations
enum MaturityAction { Allow = 0 , Reject = 1 }
Recommended maturity action.
enum ExitUrgency { None = 0 , Normal = 1 , Immediate = 2 }
Exit urgency levels.
enum AllocationDecision { Reject = 0 , Accept = 1 , DisplaceExisting = 2 }
Allocation decision types.
enum RebalanceAction { Hold = 0 , Increase = 1 , Decrease = 2 , Close = 3 }
Rebalancing actions.
Functions
readonly record struct QueueParameters (double SmoothingAlpha, double DefaultBlockingCost, double DefaultHoldingCost)
Queue management parameters.
readonly record struct QueueEstimates (double ArrivalRate, double ServiceRate, double ServiceCV, double Utilisation, double MeanQueueLength)
Current queue parameter estimates.
readonly record struct PositionPriority (string Symbol, double ExpectedProfit, double RemainingDays, double CurrentPnL, double Priority)
Represents a position with its computed priority.
readonly record struct SignalQueueEntry (string Symbol, int Strength, double CapitalRequired, double VirtualFinishTime, DateTime ArrivalTime)
Signal entry in the scheduling queue.
Enumeration Type Documentation
AllocationDecision
enum Alaris.Strategy.Risk.AllocationDecision
Allocation decision types.
Enumerator
Reject
Reject the opportunity - insufficient priority or capacity.
Accept
Accept the opportunity into the queue.
DisplaceExisting
Accept by displacing a lower-priority position.
Definition at line 534 of file STRK004A.cs.
ExitUrgency
enum Alaris.Strategy.Risk.ExitUrgency
Exit urgency levels.
Enumerator
None
No exit required.
Normal
Normal exit - close at next opportunity.
Immediate
Immediate exit - near-expiry regime imminent.
Definition at line 284 of file STMG001A.cs.
MaturityAction
enum Alaris.Strategy.Risk.MaturityAction
Recommended maturity action.
Enumerator
Allow
Entry allowed.
Reject
Entry rejected due to maturity.
Definition at line 272 of file STMG001A.cs.
RebalanceAction
enum Alaris.Strategy.Risk.RebalanceAction
Rebalancing actions.
Enumerator
Hold
No change needed.
Increase
Increase allocation.
Decrease
Decrease allocation.
Close
Close position entirely.
Definition at line 573 of file STRK004A.cs.
Function Documentation
PositionPriority()
readonly record struct Alaris.Strategy.Risk.PositionPriority (string Symbol, double ExpectedProfit, double RemainingDays, double CurrentPnL, double Priority)
Represents a position with its computed priority.
QueueEstimates()
readonly record struct Alaris.Strategy.Risk.QueueEstimates (double ArrivalRate, double ServiceRate, double ServiceCV, double Utilisation, double MeanQueueLength)
Current queue parameter estimates.
Referenced by Alaris.Strategy.Risk.STQT001A.GetCurrentEstimates().
QueueParameters()
readonly record struct Alaris.Strategy.Risk.QueueParameters (double SmoothingAlpha, double DefaultBlockingCost, double DefaultHoldingCost)
Queue management parameters.
Default parameters.
Definition at line 367 of file STQT001A.cs.
References Alaris.Strategy.Risk.QueueParameters().
Referenced by Alaris.Strategy.Risk.STQT001A.STQT001A(), and Alaris.Strategy.Risk.QueueParameters().
SignalQueueEntry()
readonly record struct Alaris.Strategy.Risk.SignalQueueEntry (string Symbol, int Strength, double CapitalRequired, double VirtualFinishTime, DateTime ArrivalTime)
Signal entry in the scheduling queue.
References Alaris.Strategy.Risk.SignalQueueEntry().
Referenced by Alaris.Strategy.Risk.SignalQueueEntry().