Alaris: Alaris.Core.Pricing.CREN002A Class Reference
Alaris.Core.Pricing.CREN002A Class Reference sealed
Unified American option pricing engine supporting all rate regimes.
Public Member Functions
CREN002A (int timeSteps=DefaultTimeSteps, int spotSteps=DefaultSpotSteps, double theta=0.5, double gridConcentration=DefaultGridConcentration)
Initialises the unified pricing engine.
double Price (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType)
Prices an American option using the appropriate method for the rate regime.
double Delta (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType)
double Gamma (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType)
double Vega (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType)
double Theta (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType)
double Rho (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType)
Static Public Attributes
const int DefaultTimeSteps = 100
Default number of time steps for standard accuracy.
const int DefaultSpotSteps = 200
Default number of spot grid points.
const double DefaultGridConcentration = 0.5
Default grid concentration parameter for ASINH distribution. Higher values concentrate more points near the spot. Typical range: 0.1 to 5.0.
Private Member Functions
double PriceWithCrankNicolson (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType)
Price using Crank-Nicolson with ASINH grid and Neumann boundaries.
void BuildAsinhGrid (double[] x, double[] dx, int n, double spot, double strike, double sigma, double T)
Builds ASINH-distributed grid with higher density near spot.
void BuildTridiagonalSystemVariable (int n, double dt, double sigma2, double r, double q, double[] x, double[] dx, double[] v, double[] aOut, double[] bOut, double[] cOut, double[] dOut)
Builds tridiagonal system with variable grid spacing.
Static Private Member Functions
static void ApplyNeumannBoundaries (int n, double[] a, double[] b, double[] c, double[] d, double[] v)
Applies Neumann boundary conditions (gamma = 0).
static void SolveTridiagonal (int n, double[] a, double[] b, double[] c, double[] d, double[] x)
Solves tridiagonal system using Thomas algorithm O(N).
static double InterpolatePrice (double[] x, double[] v, int n, double logSpot)
static double CalculatePayoff (double spot, double strike, OptionType optionType)
static double Asinh (double x)
Private Attributes
readonly int _timeSteps
readonly int _spotSteps
readonly double _theta
readonly double _gridConcentration
Detailed Description
Unified American option pricing engine supporting all rate regimes.
Key improvements over base CREN001A:
ASINH grid distribution - higher density near ATM, sparser at boundaries
Neumann boundary conditions (gamma = 0) - more stable for extreme prices
Regime detection for positive/negative rate handling
Definition at line 35 of file CREN002A.cs.
Constructor & Destructor Documentation
CREN002A()
Alaris.Core.Pricing.CREN002A.CREN002A (int timeSteps = DefaultTimeSteps, int spotSteps = DefaultSpotSteps, double theta = 0::5, double gridConcentration = DefaultGridConcentration) inline
Initialises the unified pricing engine.
Parameters
timeSteps Number of time steps (default: 100).
spotSteps Number of spot grid points (default: 200).
theta Theta for time stepping (0.5 = Crank-Nicolson).
gridConcentration ASINH concentration parameter (default: 0.5).
Definition at line 62 of file CREN002A.cs.
References Alaris.Core.Pricing.CREN002A._gridConcentration, Alaris.Core.Pricing.CREN002A._spotSteps, Alaris.Core.Pricing.CREN002A._theta, and Alaris.Core.Pricing.CREN002A._timeSteps.
Member Function Documentation
ApplyNeumannBoundaries()
static void Alaris.Core.Pricing.CREN002A.ApplyNeumannBoundaries (int n, double[] a, double[] b, double[] c, double[] d, double[] v) inline static private
Applies Neumann boundary conditions (gamma = 0).
Neumann conditions enforce that the second derivative (gamma) is zero at boundaries. This is more stable than Dirichlet conditions and reflects that option value becomes linear in the far wings.
At left boundary (S→0): V[0] = 2*V[1] - V[2] At right boundary (S→∞): V[N-1] = 2*V[N-2] - V[N-3]
Definition at line 334 of file CREN002A.cs.
Referenced by Alaris.Core.Pricing.CREN002A.PriceWithCrankNicolson().
Asinh()
static double Alaris.Core.Pricing.CREN002A.Asinh (double x) inline static private
Definition at line 433 of file CREN002A.cs.
Referenced by Alaris.Core.Pricing.CREN002A.BuildAsinhGrid().
BuildAsinhGrid()
void Alaris.Core.Pricing.CREN002A.BuildAsinhGrid (double[] x, double[] dx, int n, double spot, double strike, double sigma, double T) inline private
Builds ASINH-distributed grid with higher density near spot.
Uses QuantLib/kwinto-cuda sinh interpolation formula:
Define grid bounds: xMin = xMid - scale*σ*√T, xMax = xMid + scale*σ*√T
Transform to y-space: yMin = asinh((xMin-xMid)/density), yMax = asinh((xMax-xMid)/density)
Linear interpolate in y-space: y = yMin*(1-ξ) + yMax*ξ
Transform back: x = xMid + density * sinh(y)
This concentrates grid points near xMid where option value curves sharply. References: fdmblackscholesmesher.cpp, kwFd1d.cpp
Definition at line 225 of file CREN002A.cs.
References Alaris.Core.Pricing.CREN002A._gridConcentration, and Alaris.Core.Pricing.CREN002A.Asinh().
Referenced by Alaris.Core.Pricing.CREN002A.PriceWithCrankNicolson().
BuildTridiagonalSystemVariable()
void Alaris.Core.Pricing.CREN002A.BuildTridiagonalSystemVariable (int n, double dt, double sigma2, double r, double q, double[] x, double[] dx, double[] v, double[] aOut, double[] bOut, double[] cOut, double[] dOut) inline private
Builds tridiagonal system with variable grid spacing.
Black-Scholes PDE in log-spot space: ∂V/∂t + (r-q-σ²/2)∂V/∂x + (σ²/2)∂²V/∂x² - rV = 0
PDE coefficients matching kwinto-cuda/QuantLib:
a0 = -r (kill/discount term)
ax = r - q - σ²/2 (drift/convection)
axx = σ²/2 (diffusion)
Definition at line 272 of file CREN002A.cs.
References Alaris.Core.Pricing.CREN002A._theta.
Referenced by Alaris.Core.Pricing.CREN002A.PriceWithCrankNicolson().
CalculatePayoff()
static double Alaris.Core.Pricing.CREN002A.CalculatePayoff (double spot, double strike, OptionType optionType) inline static private
Definition at line 422 of file CREN002A.cs.
Referenced by Alaris.Core.Pricing.CREN002A.Price(), and Alaris.Core.Pricing.CREN002A.PriceWithCrankNicolson().
Delta()
double Alaris.Core.Pricing.CREN002A.Delta (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType) inline
Definition at line 440 of file CREN002A.cs.
References Alaris.Core.Pricing.CREN002A.Price().
Referenced by Alaris.Test.Unit.Core.Pricing.CREN002ATests.Delta_Call_BoundedZeroToOne(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Delta_Put_BoundedMinusOneToZero(), Alaris.Test.Benchmark.TSBM003A.Greeks_TimingComparison(), and Alaris.Core.Pricing.CREN003A.PriceWithDetails().
Gamma()
double Alaris.Core.Pricing.CREN002A.Gamma (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType) inline
Definition at line 448 of file CREN002A.cs.
References Alaris.Core.Pricing.CREN002A.Price().
Referenced by Alaris.Test.Unit.Core.Pricing.CREN002ATests.Gamma_AlwaysPositive(), Alaris.Test.Benchmark.TSBM003A.Greeks_TimingComparison(), and Alaris.Core.Pricing.CREN003A.PriceWithDetails().
InterpolatePrice()
static double Alaris.Core.Pricing.CREN002A.InterpolatePrice (double[] x, double[] v, int n, double logSpot) inline static private
Definition at line 400 of file CREN002A.cs.
Referenced by Alaris.Core.Pricing.CREN002A.PriceWithCrankNicolson().
Price()
double Alaris.Core.Pricing.CREN002A.Price (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType) inline
Prices an American option using the appropriate method for the rate regime.
Definition at line 94 of file CREN002A.cs.
References Alaris.Core.Pricing.CREN002A.CalculatePayoff(), and Alaris.Core.Pricing.CREN002A.PriceWithCrankNicolson().
Referenced by Alaris.Test.Benchmark.TSBM002A.Accuracy_SpectralVsFD_NegativeRateSingleBoundary(), Alaris.Test.Benchmark.TSBM002A.Accuracy_SpectralVsFD_StandardRegime(), Alaris.Core.Pricing.CREN002A.Delta(), Alaris.Core.Pricing.CREN002A.Gamma(), Alaris.Test.Benchmark.TSBM003A.MaturityScaling_Performance(), Alaris.Test.Benchmark.TSBM002A.Performance_SpectralFastVsFD_100Options(), Alaris.Test.Benchmark.TSBM003A.Portfolio_ThroughputComparison(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_AmericanCall_NoDividend_EqualsEuropean(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_AmericanPut_AtLeastEqualToEuropean(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_ATMCall_ReturnsPositiveValue(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_ATMPut_ReturnsPositiveValue(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_Call_MonotonicInSpot(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_DeepITMCall_ApproachesIntrinsicValue(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_DeepOTMCall_ApproachesZero(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_InvalidSpot_ThrowsException(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_InvalidVolatility_ThrowsException(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_MonotonicIncreasingInTime(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_MonotonicIncreasingInVolatility(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_Put_MonotonicDecreasingInSpot(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_VariousRates_ReturnsValidPrice(), Alaris.Test.Unit.Core.Pricing.CREN002ATests.Price_ZeroTimeToExpiry_ReturnsIntrinsic(), Alaris.Core.Pricing.CREN003A.PriceWithDetails(), Alaris.Test.Benchmark.TSBM003A.RegimeCoverage_BothEnginesWork(), Alaris.Core.Pricing.CREN002A.Rho(), Alaris.Test.Benchmark.TSBM002A.RMSE_SpectralVsFD_Portfolio(), Alaris.Test.Benchmark.TSBM003A.SingleOption_SpeedComparison(), Alaris.Core.Pricing.CREN002A.Theta(), and Alaris.Core.Pricing.CREN002A.Vega().
PriceWithCrankNicolson()
double Alaris.Core.Pricing.CREN002A.PriceWithCrankNicolson (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType) inline private
Price using Crank-Nicolson with ASINH grid and Neumann boundaries.
Definition at line 131 of file CREN002A.cs.
References Alaris.Core.Pricing.CREN002A._spotSteps, Alaris.Core.Pricing.CREN002A._timeSteps, Alaris.Core.Pricing.CREN002A.ApplyNeumannBoundaries(), Alaris.Core.Pricing.CREN002A.BuildAsinhGrid(), Alaris.Core.Pricing.CREN002A.BuildTridiagonalSystemVariable(), Alaris.Core.Pricing.CREN002A.CalculatePayoff(), Alaris.Core.Pricing.CREN002A.InterpolatePrice(), and Alaris.Core.Pricing.CREN002A.SolveTridiagonal().
Referenced by Alaris.Core.Pricing.CREN002A.Price().
Rho()
double Alaris.Core.Pricing.CREN002A.Rho (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType) inline
Definition at line 474 of file CREN002A.cs.
References Alaris.Core.Pricing.CREN002A.Price().
Referenced by Alaris.Core.Pricing.CREN003A.PriceWithDetails(), and Alaris.Core.Pricing.CREN003A.Rho().
SolveTridiagonal()
static void Alaris.Core.Pricing.CREN002A.SolveTridiagonal (int n, double[] a, double[] b, double[] c, double[] d, double[] x) inline static private
Solves tridiagonal system using Thomas algorithm O(N).
Definition at line 360 of file CREN002A.cs.
Referenced by Alaris.Core.Pricing.CREN002A.PriceWithCrankNicolson().
Theta()
double Alaris.Core.Pricing.CREN002A.Theta (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType) inline
Definition at line 466 of file CREN002A.cs.
References Alaris.Core.Pricing.CREN002A.Price().
Referenced by Alaris.Core.Pricing.CREN003A.PriceWithDetails(), and Alaris.Test.Unit.Core.Pricing.CREN002ATests.Theta_PutTypicallyNegative().
Vega()
double Alaris.Core.Pricing.CREN002A.Vega (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType) inline
Definition at line 458 of file CREN002A.cs.
References Alaris.Core.Pricing.CREN002A.Price().
Referenced by Alaris.Test.Benchmark.TSBM003A.Greeks_TimingComparison(), Alaris.Core.Pricing.CREN003A.PriceWithDetails(), and Alaris.Test.Unit.Core.Pricing.CREN002ATests.Vega_AlwaysPositive().
Member Data Documentation
_gridConcentration
readonly double Alaris.Core.Pricing.CREN002A._gridConcentration private
Definition at line 40 of file CREN002A.cs.
Referenced by Alaris.Core.Pricing.CREN002A.CREN002A(), and Alaris.Core.Pricing.CREN002A.BuildAsinhGrid().
_spotSteps
readonly int Alaris.Core.Pricing.CREN002A._spotSteps private
Definition at line 38 of file CREN002A.cs.
Referenced by Alaris.Core.Pricing.CREN002A.CREN002A(), and Alaris.Core.Pricing.CREN002A.PriceWithCrankNicolson().
_theta
readonly double Alaris.Core.Pricing.CREN002A._theta private
Definition at line 39 of file CREN002A.cs.
Referenced by Alaris.Core.Pricing.CREN002A.CREN002A(), and Alaris.Core.Pricing.CREN002A.BuildTridiagonalSystemVariable().
_timeSteps
readonly int Alaris.Core.Pricing.CREN002A._timeSteps private
Definition at line 37 of file CREN002A.cs.
Referenced by Alaris.Core.Pricing.CREN002A.CREN002A(), and Alaris.Core.Pricing.CREN002A.PriceWithCrankNicolson().
DefaultGridConcentration
const double Alaris.Core.Pricing.CREN002A.DefaultGridConcentration = 0.5 static
Default grid concentration parameter for ASINH distribution. Higher values concentrate more points near the spot. Typical range: 0.1 to 5.0.
Definition at line 53 of file CREN002A.cs.
DefaultSpotSteps
const int Alaris.Core.Pricing.CREN002A.DefaultSpotSteps = 200 static
Default number of spot grid points.
Definition at line 46 of file CREN002A.cs.
DefaultTimeSteps
const int Alaris.Core.Pricing.CREN002A.DefaultTimeSteps = 100 static
Default number of time steps for standard accuracy.
Definition at line 43 of file CREN002A.cs.
The documentation for this class was generated from the following file:
src/Alaris.Core/Pricing/CREN002A.cs