Alaris: Alaris.Test.Unit.TSUN028A Class Reference
Alaris.Test.Unit.TSUN028A Class Reference sealed
TSUN028A: Tests for simulation constants and trading calendar functions.
Public Member Functions
void TradingDaysPerYear_Is252 ()
Trading days per year constant should be 252.
void DteToYears_ConvertsCorrectly (int dte, double expectedYears)
DTE to years conversion should use 252 trading days.
void YearsToDte_IsInverseOfDteToYears (double years, int expectedDte)
Years to DTE conversion is inverse of DTE to years.
void DteToYearsToDte_RoundTrip_IsIdentity (int originalDte)
Round-trip conversion should be identity.
void DeltaBound_IsWithinPhysicalConstraints (double delta, bool expectedValid)
Delta bounds for single options: |Δ| ≤ 1.0 (1.5 with tolerance).
void GammaBound_IsWithinPhysicalConstraints (double gamma, bool expectedValid)
Gamma bounds: |Γ| ≤ 0.5 for stability.
void VegaBound_IsWithinPhysicalConstraints (double vega, bool expectedValid)
Vega bounds: per 1% vol change, |V| ≤ 1.0.
void PositiveRiskFreeRate_IsReasonable ()
Standard risk-free rate for positive regime is ~5.25%.
void NegativeRiskFreeRate_IsValidNegativeRate ()
Negative risk-free rate regime uses small negative rate.
void NegativeRateRegime_DividendLessThanRate ()
For double boundary regime, q < r (dividend < rate).
void EarningsIVPremium_IsReasonable ()
Earnings IV premium is reasonable (5-15%).
void EarningsGapMagnitude_IsRealistic ()
Earnings gap magnitude is calibrated to historical data.
void PriceBar_OHLCRelationship_IsValid ()
PriceBar should have valid OHLC relationship: L ≤ O,C ≤ H.
void PriceBar_Volume_NonNegative ()
PriceBar volume should be non-negative.
void InvertedTermStructure_FrontIVGreaterThanBack ()
Inverted term structure: front IV > back IV.
void TermStructureSlope_IsNegativeForInvertedStructure ()
Term structure slope for inverted term structure is negative.
void DaysBeforeEarnings_IsAtilganOptimal ()
Days before earnings for entry (Atilgan 2014).
void MinimumDollarVolume_IsReasonable ()
Minimum dollar volume filter (liquidity).
void MinimumPrice_FiltersPennyStocks ()
Minimum share price filter.
void MaxPositionAllocation_IsConservative ()
Maximum position allocation respects risk management.
void MaxConcurrentPositions_LimitsConcentration ()
Maximum concurrent positions limits concentration.
void PortfolioAllocationLimit_IsConservative ()
Portfolio allocation limit is conservative.
void IVRVRatio_MeetsSignalThreshold (double iv, double rv, bool expectedRecommended)
IV/RV ratio threshold for Recommended signal.
Detailed Description
TSUN028A: Tests for simulation constants and trading calendar functions.
Definition at line 31 of file TSUN028A.cs.
Member Function Documentation
DaysBeforeEarnings_IsAtilganOptimal()
void Alaris.Test.Unit.TSUN028A.DaysBeforeEarnings_IsAtilganOptimal () inline
Days before earnings for entry (Atilgan 2014).
Definition at line 332 of file TSUN028A.cs.
DeltaBound_IsWithinPhysicalConstraints()
void Alaris.Test.Unit.TSUN028A.DeltaBound_IsWithinPhysicalConstraints (double delta, bool expectedValid) inline
Delta bounds for single options: |Δ| ≤ 1.0 (1.5 with tolerance).
Definition at line 112 of file TSUN028A.cs.
DteToYears_ConvertsCorrectly()
void Alaris.Test.Unit.TSUN028A.DteToYears_ConvertsCorrectly (int dte, double expectedYears) inline
DTE to years conversion should use 252 trading days.
Definition at line 54 of file TSUN028A.cs.
References Alaris.Strategy.Calendar.TradingCalendarDefaults.DteToYears().
DteToYearsToDte_RoundTrip_IsIdentity()
void Alaris.Test.Unit.TSUN028A.DteToYearsToDte_RoundTrip_IsIdentity (int originalDte) inline
Round-trip conversion should be identity.
Definition at line 87 of file TSUN028A.cs.
References Alaris.Strategy.Calendar.TradingCalendarDefaults.DteToYears(), and Alaris.Strategy.Calendar.TradingCalendarDefaults.YearsToDte().
EarningsGapMagnitude_IsRealistic()
void Alaris.Test.Unit.TSUN028A.EarningsGapMagnitude_IsRealistic () inline
Earnings gap magnitude is calibrated to historical data.
Definition at line 228 of file TSUN028A.cs.
EarningsIVPremium_IsReasonable()
void Alaris.Test.Unit.TSUN028A.EarningsIVPremium_IsReasonable () inline
Earnings IV premium is reasonable (5-15%).
Definition at line 214 of file TSUN028A.cs.
GammaBound_IsWithinPhysicalConstraints()
void Alaris.Test.Unit.TSUN028A.GammaBound_IsWithinPhysicalConstraints (double gamma, bool expectedValid) inline
Gamma bounds: |Γ| ≤ 0.5 for stability.
Definition at line 132 of file TSUN028A.cs.
InvertedTermStructure_FrontIVGreaterThanBack()
void Alaris.Test.Unit.TSUN028A.InvertedTermStructure_FrontIVGreaterThanBack () inline
Inverted term structure: front IV > back IV.
Definition at line 291 of file TSUN028A.cs.
IVRVRatio_MeetsSignalThreshold()
void Alaris.Test.Unit.TSUN028A.IVRVRatio_MeetsSignalThreshold (double iv, double rv, bool expectedRecommended) inline
IV/RV ratio threshold for Recommended signal.
Definition at line 422 of file TSUN028A.cs.
MaxConcurrentPositions_LimitsConcentration()
void Alaris.Test.Unit.TSUN028A.MaxConcurrentPositions_LimitsConcentration () inline
Maximum concurrent positions limits concentration.
Definition at line 386 of file TSUN028A.cs.
MaxPositionAllocation_IsConservative()
void Alaris.Test.Unit.TSUN028A.MaxPositionAllocation_IsConservative () inline
Maximum position allocation respects risk management.
Definition at line 373 of file TSUN028A.cs.
MinimumDollarVolume_IsReasonable()
void Alaris.Test.Unit.TSUN028A.MinimumDollarVolume_IsReasonable () inline
Minimum dollar volume filter (liquidity).
Definition at line 345 of file TSUN028A.cs.
MinimumPrice_FiltersPennyStocks()
void Alaris.Test.Unit.TSUN028A.MinimumPrice_FiltersPennyStocks () inline
Minimum share price filter.
Definition at line 359 of file TSUN028A.cs.
NegativeRateRegime_DividendLessThanRate()
void Alaris.Test.Unit.TSUN028A.NegativeRateRegime_DividendLessThanRate () inline
For double boundary regime, q < r (dividend < rate).
Definition at line 199 of file TSUN028A.cs.
NegativeRiskFreeRate_IsValidNegativeRate()
void Alaris.Test.Unit.TSUN028A.NegativeRiskFreeRate_IsValidNegativeRate () inline
Negative risk-free rate regime uses small negative rate.
Definition at line 184 of file TSUN028A.cs.
PortfolioAllocationLimit_IsConservative()
void Alaris.Test.Unit.TSUN028A.PortfolioAllocationLimit_IsConservative () inline
Portfolio allocation limit is conservative.
Definition at line 402 of file TSUN028A.cs.
PositiveRiskFreeRate_IsReasonable()
void Alaris.Test.Unit.TSUN028A.PositiveRiskFreeRate_IsReasonable () inline
Standard risk-free rate for positive regime is ~5.25%.
Definition at line 170 of file TSUN028A.cs.
PriceBar_OHLCRelationship_IsValid()
void Alaris.Test.Unit.TSUN028A.PriceBar_OHLCRelationship_IsValid () inline
PriceBar should have valid OHLC relationship: L ≤ O,C ≤ H.
Definition at line 244 of file TSUN028A.cs.
PriceBar_Volume_NonNegative()
void Alaris.Test.Unit.TSUN028A.PriceBar_Volume_NonNegative () inline
PriceBar volume should be non-negative.
Definition at line 268 of file TSUN028A.cs.
TermStructureSlope_IsNegativeForInvertedStructure()
void Alaris.Test.Unit.TSUN028A.TermStructureSlope_IsNegativeForInvertedStructure () inline
Term structure slope for inverted term structure is negative.
Definition at line 307 of file TSUN028A.cs.
TradingDaysPerYear_Is252()
void Alaris.Test.Unit.TSUN028A.TradingDaysPerYear_Is252 () inline
Trading days per year constant should be 252.
Definition at line 39 of file TSUN028A.cs.
References Alaris.Strategy.Calendar.TradingCalendarDefaults.TradingDaysPerYear.
VegaBound_IsWithinPhysicalConstraints()
void Alaris.Test.Unit.TSUN028A.VegaBound_IsWithinPhysicalConstraints (double vega, bool expectedValid) inline
Vega bounds: per 1% vol change, |V| ≤ 1.0.
Definition at line 152 of file TSUN028A.cs.
YearsToDte_IsInverseOfDteToYears()
void Alaris.Test.Unit.TSUN028A.YearsToDte_IsInverseOfDteToYears (double years, int expectedDte) inline
Years to DTE conversion is inverse of DTE to years.
Definition at line 70 of file TSUN028A.cs.
References Alaris.Strategy.Calendar.TradingCalendarDefaults.YearsToDte().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN028A.cs