Alaris: Alaris.Host.Application.APap001A Class Reference
Alaris.Host.Application.APap001A Class Reference
Alaris Trading System CLI Entry Point. Component ID: APap001A.
Static Public Member Functions
static int Main (string[] args)
Main entry point for Alaris CLI.
Static Private Member Functions
static void ConfigureCommands (IConfigurator config)
static int RunInteractiveMode ()
static void RenderStatusBar ()
static void RenderBanner ()
static void CheckSystemStatus ()
static void WaitForKeyPress ()
static int ShowTradingMenu ()
static int StartTrading (string mode)
static int ShowBacktestMenu ()
static int CreateSessionInteractive ()
static int RunSessionInteractive ()
static int ViewSessionInteractive ()
static int DeleteSessionInteractive ()
static ? string SelectSession (string action)
static int ShowPositionMonitor ()
static int ShowConfigurationMenu ()
static void EditApiKeys ()
static void EditStrategyParams ()
static void EditIbkrSettings ()
static int ShowSystemMenu ()
static void RunHealthCheck ()
static void ViewLogs ()
static void ShowAbout ()
Static Private Attributes
static string _currentMode = "Idle"
static bool _isConnected
const string Version = "2.0.0"
Detailed Description
Alaris Trading System CLI Entry Point. Component ID: APap001A.
Definition at line 18 of file APap001A.cs.
Member Function Documentation
CheckSystemStatus()
static void Alaris.Host.Application.APap001A.CheckSystemStatus () inline static private
Definition at line 231 of file APap001A.cs.
References Alaris.Host.Application.APap001A._isConnected.
Referenced by Alaris.Host.Application.APap001A.RunInteractiveMode().
ConfigureCommands()
static void Alaris.Host.Application.APap001A.ConfigureCommands (IConfigurator config) inline static private
Definition at line 39 of file APap001A.cs.
References Alaris.Host.Application.APap001A.Version.
Referenced by Alaris.Host.Application.APap001A.Main().
CreateSessionInteractive()
static int Alaris.Host.Application.APap001A.CreateSessionInteractive () inline static private
Definition at line 385 of file APap001A.cs.
References Alaris.Host.Application.APap001A.Main().
Referenced by Alaris.Host.Application.APap001A.ShowBacktestMenu().
DeleteSessionInteractive()
static int Alaris.Host.Application.APap001A.DeleteSessionInteractive () inline static private
Definition at line 469 of file APap001A.cs.
References Alaris.Host.Application.APap001A.Main(), and Alaris.Host.Application.APap001A.SelectSession().
Referenced by Alaris.Host.Application.APap001A.ShowBacktestMenu().
EditApiKeys()
static void Alaris.Host.Application.APap001A.EditApiKeys () inline static private
Definition at line 604 of file APap001A.cs.
References Alaris.Host.Application.APap001A.WaitForKeyPress().
Referenced by Alaris.Host.Application.APap001A.ShowConfigurationMenu().
EditIbkrSettings()
static void Alaris.Host.Application.APap001A.EditIbkrSettings () inline static private
Definition at line 645 of file APap001A.cs.
References Alaris.Host.Application.APap001A.WaitForKeyPress().
Referenced by Alaris.Host.Application.APap001A.ShowConfigurationMenu().
EditStrategyParams()
static void Alaris.Host.Application.APap001A.EditStrategyParams () inline static private
Definition at line 628 of file APap001A.cs.
References Alaris.Host.Application.APap001A.WaitForKeyPress().
Referenced by Alaris.Host.Application.APap001A.ShowConfigurationMenu().
Main()
static int Alaris.Host.Application.APap001A.Main (string[] args) inline static
Main entry point for Alaris CLI.
Definition at line 27 of file APap001A.cs.
References Alaris.Host.Application.APap001A.ConfigureCommands(), and Alaris.Host.Application.APap001A.RunInteractiveMode().
Referenced by Alaris.Host.Application.APap001A.CreateSessionInteractive(), Alaris.Host.Application.APap001A.DeleteSessionInteractive(), Alaris.Host.Application.APap001A.RunSessionInteractive(), Alaris.Host.Application.APap001A.ShowBacktestMenu(), Alaris.Host.Application.APap001A.ShowConfigurationMenu(), Alaris.Host.Application.APap001A.StartTrading(), and Alaris.Host.Application.APap001A.ViewSessionInteractive().
RenderBanner()
static void Alaris.Host.Application.APap001A.RenderBanner () inline static private
Definition at line 221 of file APap001A.cs.
References Alaris.Host.Application.APap001A.Version.
Referenced by Alaris.Host.Application.APap001A.RunInteractiveMode().
RenderStatusBar()
static void Alaris.Host.Application.APap001A.RenderStatusBar () inline static private
Definition at line 195 of file APap001A.cs.
References Alaris.Host.Application.APap001A._currentMode, and Alaris.Host.Application.APap001A._isConnected.
Referenced by Alaris.Host.Application.APap001A.RunInteractiveMode(), Alaris.Host.Application.APap001A.ShowBacktestMenu(), Alaris.Host.Application.APap001A.ShowConfigurationMenu(), Alaris.Host.Application.APap001A.ShowPositionMonitor(), Alaris.Host.Application.APap001A.ShowSystemMenu(), and Alaris.Host.Application.APap001A.ShowTradingMenu().
RunHealthCheck()
static void Alaris.Host.Application.APap001A.RunHealthCheck () inline static private
Definition at line 710 of file APap001A.cs.
References Alaris.Host.Application.APap001A._isConnected.
Referenced by Alaris.Host.Application.APap001A.ShowSystemMenu().
RunInteractiveMode()
static int Alaris.Host.Application.APap001A.RunInteractiveMode () inline static private
Definition at line 135 of file APap001A.cs.
References Alaris.Host.Application.APap001A.CheckSystemStatus(), Alaris.Host.Application.APap001A.RenderBanner(), Alaris.Host.Application.APap001A.RenderStatusBar(), Alaris.Host.Application.APap001A.ShowBacktestMenu(), Alaris.Host.Application.APap001A.ShowConfigurationMenu(), Alaris.Host.Application.APap001A.ShowPositionMonitor(), Alaris.Host.Application.APap001A.ShowSystemMenu(), and Alaris.Host.Application.APap001A.ShowTradingMenu().
Referenced by Alaris.Host.Application.APap001A.Main().
RunSessionInteractive()
static int Alaris.Host.Application.APap001A.RunSessionInteractive () inline static private
Definition at line 453 of file APap001A.cs.
References Alaris.Host.Application.APap001A._currentMode, Alaris.Host.Application.APap001A.Main(), and Alaris.Host.Application.APap001A.SelectSession().
Referenced by Alaris.Host.Application.APap001A.ShowBacktestMenu().
SelectSession()
static ? string Alaris.Host.Application.APap001A.SelectSession (string action) inline static private
Definition at line 483 of file APap001A.cs.
Referenced by Alaris.Host.Application.APap001A.DeleteSessionInteractive(), Alaris.Host.Application.APap001A.RunSessionInteractive(), and Alaris.Host.Application.APap001A.ViewSessionInteractive().
ShowAbout()
static void Alaris.Host.Application.APap001A.ShowAbout () inline static private
Definition at line 783 of file APap001A.cs.
Referenced by Alaris.Host.Application.APap001A.ShowSystemMenu().
ShowBacktestMenu()
static int Alaris.Host.Application.APap001A.ShowBacktestMenu () inline static private
Definition at line 327 of file APap001A.cs.
References Alaris.Host.Application.APap001A.CreateSessionInteractive(), Alaris.Host.Application.APap001A.DeleteSessionInteractive(), Alaris.Host.Application.APap001A.Main(), Alaris.Host.Application.APap001A.RenderStatusBar(), Alaris.Host.Application.APap001A.RunSessionInteractive(), Alaris.Host.Application.APap001A.ViewSessionInteractive(), and Alaris.Host.Application.APap001A.WaitForKeyPress().
Referenced by Alaris.Host.Application.APap001A.RunInteractiveMode().
ShowConfigurationMenu()
static int Alaris.Host.Application.APap001A.ShowConfigurationMenu () inline static private
Definition at line 555 of file APap001A.cs.
References Alaris.Host.Application.APap001A.EditApiKeys(), Alaris.Host.Application.APap001A.EditIbkrSettings(), Alaris.Host.Application.APap001A.EditStrategyParams(), Alaris.Host.Application.APap001A.Main(), Alaris.Host.Application.APap001A.RenderStatusBar(), and Alaris.Host.Application.APap001A.WaitForKeyPress().
Referenced by Alaris.Host.Application.APap001A.RunInteractiveMode().
ShowPositionMonitor()
static int Alaris.Host.Application.APap001A.ShowPositionMonitor () inline static private
Definition at line 510 of file APap001A.cs.
References Alaris.Host.Application.APap001A._currentMode, Alaris.Host.Application.APap001A.RenderStatusBar(), and Alaris.Host.Application.APap001A.WaitForKeyPress().
Referenced by Alaris.Host.Application.APap001A.RunInteractiveMode().
ShowSystemMenu()
static int Alaris.Host.Application.APap001A.ShowSystemMenu () inline static private
Definition at line 663 of file APap001A.cs.
References Alaris.Host.Application.APap001A.RenderStatusBar(), Alaris.Host.Application.APap001A.RunHealthCheck(), Alaris.Host.Application.APap001A.ShowAbout(), Alaris.Host.Application.APap001A.ViewLogs(), and Alaris.Host.Application.APap001A.WaitForKeyPress().
Referenced by Alaris.Host.Application.APap001A.RunInteractiveMode().
ShowTradingMenu()
static int Alaris.Host.Application.APap001A.ShowTradingMenu () inline static private
Definition at line 246 of file APap001A.cs.
References Alaris.Host.Application.APap001A.RenderStatusBar(), Alaris.Host.Application.APap001A.StartTrading(), and Alaris.Host.Application.APap001A.WaitForKeyPress().
Referenced by Alaris.Host.Application.APap001A.RunInteractiveMode().
StartTrading()
static int Alaris.Host.Application.APap001A.StartTrading (string mode) inline static private
Definition at line 289 of file APap001A.cs.
References Alaris.Host.Application.APap001A._currentMode, Alaris.Host.Application.APap001A._isConnected, and Alaris.Host.Application.APap001A.Main().
Referenced by Alaris.Host.Application.APap001A.ShowTradingMenu().
ViewLogs()
static void Alaris.Host.Application.APap001A.ViewLogs () inline static private
Definition at line 753 of file APap001A.cs.
Referenced by Alaris.Host.Application.APap001A.ShowSystemMenu().
ViewSessionInteractive()
static int Alaris.Host.Application.APap001A.ViewSessionInteractive () inline static private
Definition at line 462 of file APap001A.cs.
References Alaris.Host.Application.APap001A.Main(), and Alaris.Host.Application.APap001A.SelectSession().
Referenced by Alaris.Host.Application.APap001A.ShowBacktestMenu().
WaitForKeyPress()
static void Alaris.Host.Application.APap001A.WaitForKeyPress () inline static private
Definition at line 237 of file APap001A.cs.
Referenced by Alaris.Host.Application.APap001A.EditApiKeys(), Alaris.Host.Application.APap001A.EditIbkrSettings(), Alaris.Host.Application.APap001A.EditStrategyParams(), Alaris.Host.Application.APap001A.ShowBacktestMenu(), Alaris.Host.Application.APap001A.ShowConfigurationMenu(), Alaris.Host.Application.APap001A.ShowPositionMonitor(), Alaris.Host.Application.APap001A.ShowSystemMenu(), and Alaris.Host.Application.APap001A.ShowTradingMenu().
Member Data Documentation
_currentMode
string Alaris.Host.Application.APap001A._currentMode = "Idle" static private
Definition at line 20 of file APap001A.cs.
Referenced by Alaris.Host.Application.APap001A.RenderStatusBar(), Alaris.Host.Application.APap001A.RunSessionInteractive(), Alaris.Host.Application.APap001A.ShowPositionMonitor(), and Alaris.Host.Application.APap001A.StartTrading().
_isConnected
bool Alaris.Host.Application.APap001A._isConnected static private
Definition at line 21 of file APap001A.cs.
Referenced by Alaris.Host.Application.APap001A.CheckSystemStatus(), Alaris.Host.Application.APap001A.RenderStatusBar(), Alaris.Host.Application.APap001A.RunHealthCheck(), and Alaris.Host.Application.APap001A.StartTrading().
Version
const string Alaris.Host.Application.APap001A.Version = "2.0.0" static private
Definition at line 22 of file APap001A.cs.
Referenced by Alaris.Host.Application.APap001A.ConfigureCommands(), and Alaris.Host.Application.APap001A.RenderBanner().
The documentation for this class was generated from the following file:
src/Alaris.Host/Application/APap001A.cs