Alaris: Alaris.Strategy.Hedge Namespace Reference
Alaris.Strategy.Hedge Namespace Reference
Classes
class STHD001A
Analyses the correlation between front-month and back-month implied volatility changes to assess calendar spread vega independence.
class STHD003A
Monitors and manages gamma risk for calendar spread positions.
class STHD005A
Orchestrates all pre-trade validations for production deployment.
class STHD007A
Monitors implied volatility to trigger early exits when IV crushes faster than expected.
class STHD007B
Rule-based exit monitor with stall detection for calendar spreads.
class STHD009A
Monitors pin risk for options near expiry when underlying is close to strike.
Enumerations
enum RehedgeAction { Hold , MonitorClosely , RecenterRequired , ExitPosition }
Specifies the recommended hedging action.
enum EarlyExitAction { Hold = 0 , ExitNow = 1 , MonitorClosely = 2 }
Early exit action recommendations.
enum ExitAction { Hold , Exit }
Exit action recommendation.
enum ExitReason {
None , TargetCaptured , CrushStalled , TradeNotWorking ,
TimeDecay , RateReversal
}
Reason for exit recommendation.
enum STHD011A {
None = 0 , Low = 1 , Moderate = 2 , Elevated = 3 ,
High = 4 , Critical = 5
}
Pin risk levels.
enum STHD012A { Hold = 0 , ReduceSize = 1 , RollOut = 2 , CloseEarly = 3 }
Recommended actions for pin risk.
Functions
readonly record struct ExitParameters (double TargetCrushRatio, double StallCrushThreshold, double StallRateThreshold, double MinExpectedCrush, double AdverseRateThreshold, double MaxWaitDays, double PartialCaptureThreshold, double MinDaysRemaining, double ReversalRateThreshold, double RateSmoothingAlpha, int MinUpdatesForStall)
Exit monitor parameters with operational meaning.
readonly record struct ExitSignal (ExitAction Action, ExitReason Reason, string Message, double CrushCaptured, double SmoothedRate, double DaysRemaining, double Confidence)
Exit signal result with action, reason, and diagnostics.
Enumeration Type Documentation
EarlyExitAction
enum Alaris.Strategy.Hedge.EarlyExitAction
Early exit action recommendations.
Enumerator
Hold
Hold position - IV crush within expected range.
ExitNow
Exit position immediately - IV crush realised faster than expected.
MonitorClosely
Monitor closely - approaching exit threshold.
Definition at line 308 of file STHD007A.cs.
ExitAction
enum Alaris.Strategy.Hedge.ExitAction
Exit action recommendation.
Enumerator
Hold
Continue holding the position.
Exit
Exit the position.
Definition at line 379 of file STHD007B.cs.
ExitReason
enum Alaris.Strategy.Hedge.ExitReason
Reason for exit recommendation.
Enumerator
None
No exit reason (holding).
TargetCaptured
Captured target crush percentage.
CrushStalled
Significant capture but rate has stalled.
TradeNotWorking
Trade not working - insufficient crush despite time.
TimeDecay
Time decay - approaching expiry with partial profit.
RateReversal
IV reversing after partial capture.
Definition at line 391 of file STHD007B.cs.
RehedgeAction
enum Alaris.Strategy.Hedge.RehedgeAction
Specifies the recommended hedging action.
Enumerator
Hold
No action required; position is within parameters.
MonitorClosely
Position requires close monitoring; risk is elevated but manageable.
RecenterRequired
Position should be closed and re-established at current ATM strike.
ExitPosition
Position should be exited due to elevated gap or directional risk.
Definition at line 269 of file STHD003A.cs.
STHD011A
enum Alaris.Strategy.Hedge.STHD011A
Pin risk levels.
Enumerator
None
Not in pin zone.
Low
In pin zone but far from expiry.
Moderate
Approaching pin risk danger zone.
Elevated
Significant pin risk.
High
High pin risk - action recommended.
Critical
Critical pin risk - immediate action required.
Definition at line 252 of file STHD009A.cs.
STHD012A
enum Alaris.Strategy.Hedge.STHD012A
Recommended actions for pin risk.
Enumerator
Hold
Maintain current position.
ReduceSize
Reduce position size.
RollOut
Roll to later expiry.
CloseEarly
Close position before expiry.
Definition at line 276 of file STHD009A.cs.
Function Documentation
ExitParameters()
readonly record struct Alaris.Strategy.Hedge.ExitParameters (double TargetCrushRatio, double StallCrushThreshold, double StallRateThreshold, double MinExpectedCrush, double AdverseRateThreshold, double MaxWaitDays, double PartialCaptureThreshold, double MinDaysRemaining, double ReversalRateThreshold, double RateSmoothingAlpha, int MinUpdatesForStall)
Exit monitor parameters with operational meaning.
Default parameters based on calendar spread dynamics.
Conservative parameters (longer holds, higher thresholds).
Aggressive parameters (faster exits, lower thresholds).
Definition at line 302 of file STHD007B.cs.
References Alaris.Strategy.Hedge.ExitParameters().
Referenced by Alaris.Strategy.Hedge.STHD007B.STHD007B(), and Alaris.Strategy.Hedge.ExitParameters().
ExitSignal()
readonly record struct Alaris.Strategy.Hedge.ExitSignal (ExitAction Action, ExitReason Reason, string Message, double CrushCaptured, double SmoothedRate, double DaysRemaining, double Confidence)
Exit signal result with action, reason, and diagnostics.
Referenced by Alaris.Strategy.Hedge.STHD007B.CreateExitSignal(), and Alaris.Strategy.Hedge.STHD007B.Evaluate().