Alaris: Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider Class Reference
Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider Class Reference sealed
Treasury Direct API risk-free rate provider. Component ID: DTrf001A.
Public Member Functions
TreasuryDirectRateProvider (ITreasuryDirectApi api, ILogger< TreasuryDirectRateProvider > logger)
Initializes a new instance of the TreasuryDirectRateProvider class.
async Task< decimal > GetCurrentRateAsync (CancellationToken cancellationToken=default)
Gets the current risk-free rate (e.g., 3-month T-bill).
async Task< IReadOnlyDictionary< DateTime, decimal > > GetHistoricalRatesAsync (DateTime startDate, DateTime endDate, CancellationToken cancellationToken=default)
Gets historical risk-free rates.
Static Private Member Functions
static decimal ParseRate (string? rateString)
Parses interest rate string to decimal. Treasury rates are typically given as percentages (e.g., "5.25" for 5.25%).
Private Attributes
readonly ITreasuryDirectApi _api
readonly ILogger< TreasuryDirectRateProvider > _logger
Detailed Description
Treasury Direct API risk-free rate provider. Component ID: DTrf001A.
Provides risk-free rates using official US Treasury data via Refit declarative interface (ITreasuryDirectApi). Implements DTpr005A (Risk-Free Rate Provider interface).
API: https://www.treasurydirect.gov/TA_WS/securities Cost: FREE (official US government API) Data: Daily treasury yields (3-month T-bill recommended for options) No authentication required
Usage:
3-month T-bill rate used as risk-free rate (r parameter)
Updated daily
No rate limits on official API
Resilience provided by Microsoft.Extensions.Http.Resilience standard handler.
Definition at line 41 of file DTrf001A.cs.
Constructor & Destructor Documentation
TreasuryDirectRateProvider()
Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider.TreasuryDirectRateProvider (ITreasuryDirectApi api, ILogger< TreasuryDirectRateProvider > logger) inline
Initializes a new instance of the TreasuryDirectRateProvider class.
Parameters
api Treasury Direct Refit API client.
logger Logger instance.
Definition at line 51 of file DTrf001A.cs.
References Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider._api, and Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider._logger.
Member Function Documentation
GetCurrentRateAsync()
async Task< decimal > Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider.GetCurrentRateAsync (CancellationToken cancellationToken = default) inline
Gets the current risk-free rate (e.g., 3-month T-bill).
Implements Alaris.Infrastructure.Data.Provider.DTpr005A.
Definition at line 60 of file DTrf001A.cs.
References Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider._api, Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider._logger, Alaris.Infrastructure.Data.Http.Contracts.TreasurySecurityDto.InterestRate, Alaris.Infrastructure.Data.Http.Contracts.TreasurySecurityDto.IssueDate, Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider.ParseRate(), Alaris.Infrastructure.Data.Http.Contracts.ITreasuryDirectApi.SearchSecuritiesAsync(), and Alaris.Infrastructure.Data.Http.Contracts.TreasurySecurityDto.Term.
GetHistoricalRatesAsync()
async Task< IReadOnlyDictionary< DateTime, decimal > > Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider.GetHistoricalRatesAsync (DateTime startDate, DateTime endDate, CancellationToken cancellationToken = default) inline
Gets historical risk-free rates.
Implements Alaris.Infrastructure.Data.Provider.DTpr005A.
Definition at line 128 of file DTrf001A.cs.
References Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider._api, Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider._logger, and Alaris.Infrastructure.Data.Http.Contracts.ITreasuryDirectApi.SearchSecuritiesAsync().
Referenced by Alaris.Host.Application.Service.APsv002A.DownloadEquityDataAsync(), and Alaris.Host.Application.Service.APsv002A.DownloadInterestRatesAsync().
ParseRate()
static decimal Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider.ParseRate (string? rateString) inline static private
Parses interest rate string to decimal. Treasury rates are typically given as percentages (e.g., "5.25" for 5.25%).
Definition at line 187 of file DTrf001A.cs.
Referenced by Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider.GetCurrentRateAsync().
Member Data Documentation
_api
readonly ITreasuryDirectApi Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider._api private
Definition at line 43 of file DTrf001A.cs.
Referenced by Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider.TreasuryDirectRateProvider(), Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider.GetCurrentRateAsync(), and Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider.GetHistoricalRatesAsync().
_logger
readonly ILogger<TreasuryDirectRateProvider> Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider._logger private
Definition at line 44 of file DTrf001A.cs.
Referenced by Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider.TreasuryDirectRateProvider(), Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider.GetCurrentRateAsync(), and Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider.GetHistoricalRatesAsync().
The documentation for this class was generated from the following file:
src/Alaris.Infrastructure/Data/Provider/DTrf001A.cs