Alaris: Alaris.Strategy.Risk.STRK001A Class Reference
Alaris.Strategy.Risk.STRK001A Class Reference sealed
Implements Kelly Criterion position sizing for options strategies. Uses fractional Kelly (typically 25% of full Kelly) for safety.
Public Member Functions
STRK001A (ILogger< STRK001A >? logger=null)
STRK002A CalculateFromHistory (double portfolioValue, IReadOnlyList< Trade > historicalTrades, double spreadCost, STCR004A signal)
Calculates position size based on historical trade performance. Kelly Formula: f* = (p*b - q) / b where p = win probability, q = loss probability, b = win/loss ratio.
Static Public Member Functions
static double CalculateNetOfCostKelly (double winProbability, double avgWin, double avgLoss, double roundTripCost)
Calculates Kelly fraction adjusted for transaction costs.
Private Member Functions
void SafeLog (Action logAction)
Safely executes logging operation with fault isolation (Rule 15). Prevents logging failures from crashing critical paths.
Static Private Member Functions
static double AdjustForSTCR004AStrength (double baseAllocation, STCR004A signal)
Adjusts allocation based on signal strength.
static STRK002A GetMinimumPosition (double portfolioValue, double spreadCost)
Returns a minimum safe position size.
Private Attributes
readonly? ILogger< STRK001A > _logger
Static Private Attributes
static readonly Action< ILogger, int, Exception?> LogInsufficientTradeHistory
static readonly Action< ILogger, double, Exception?> LogInvalidWinRate
static readonly Action< ILogger, Exception?> LogInvalidAverageWinLoss
static readonly Action< ILogger, string, int, double, double, Exception?> LogPositionCalculated
static readonly Action< ILogger, string, Exception?> LogErrorCalculatingPosition
const double FractionalKelly = 0.25
const double MaxAllocation = 0.06
const double ContractMultiplier = 100.0
Detailed Description
Implements Kelly Criterion position sizing for options strategies. Uses fractional Kelly (typically 25% of full Kelly) for safety.
Definition at line 10 of file STRK001A.cs.
Constructor & Destructor Documentation
STRK001A()
Alaris.Strategy.Risk.STRK001A.STRK001A (ILogger< STRK001A >? logger = null) inline
Definition at line 49 of file STRK001A.cs.
References Alaris.Strategy.Risk.STRK001A._logger.
Member Function Documentation
AdjustForSTCR004AStrength()
static double Alaris.Strategy.Risk.STRK001A.AdjustForSTCR004AStrength (double baseAllocation, STCR004A signal) inline static private
Adjusts allocation based on signal strength.
Definition at line 207 of file STRK001A.cs.
Referenced by Alaris.Strategy.Risk.STRK001A.CalculateFromHistory().
CalculateFromHistory()
STRK002A Alaris.Strategy.Risk.STRK001A.CalculateFromHistory (double portfolioValue, IReadOnlyList< Trade > historicalTrades, double spreadCost, STCR004A signal) inline
Calculates position size based on historical trade performance. Kelly Formula: f* = (p*b - q) / b where p = win probability, q = loss probability, b = win/loss ratio.
Definition at line 59 of file STRK001A.cs.
References Alaris.Strategy.Risk.STRK001A._logger, Alaris.Strategy.Risk.STRK001A.AdjustForSTCR004AStrength(), Alaris.Strategy.Risk.STRK001A.ContractMultiplier, Alaris.Strategy.Risk.STRK002A.Contracts, Alaris.Strategy.Risk.STRK001A.FractionalKelly, Alaris.Strategy.Risk.STRK001A.GetMinimumPosition(), Alaris.Strategy.Risk.STRK001A.LogErrorCalculatingPosition, Alaris.Strategy.Risk.STRK001A.LogInsufficientTradeHistory, Alaris.Strategy.Risk.STRK001A.LogInvalidAverageWinLoss, Alaris.Strategy.Risk.STRK001A.LogInvalidWinRate, Alaris.Strategy.Risk.STRK001A.LogPositionCalculated, Alaris.Strategy.Risk.STRK001A.MaxAllocation, Alaris.Strategy.Risk.STRK001A.SafeLog(), and Alaris.Strategy.Core.STCR004A.Symbol.
Referenced by Alaris.Strategy.Risk.STRK004A.Allocate(), Alaris.Strategy.Risk.STRK003A.CalculateWithReserve(), Alaris.Strategy.STCT001A.EvaluateOpportunity(), and Alaris.Algorithm.STLN001A.EvaluateSnapshot().
CalculateNetOfCostKelly()
static double Alaris.Strategy.Risk.STRK001A.CalculateNetOfCostKelly (double winProbability, double avgWin, double avgLoss, double roundTripCost) inline static
Calculates Kelly fraction adjusted for transaction costs.
Parameters
winProbability Historical win probability (0-1).
avgWin Average winning trade amount.
avgLoss Average losing trade amount (positive).
roundTripCost Round-trip transaction cost per contract.
Returns
Net-of-cost Kelly fraction.
Definition at line 170 of file STRK001A.cs.
Referenced by Alaris.Test.Unit.TSUN027A.NetOfCostKelly_CostsExceedEdge_ReturnsZero(), Alaris.Test.Unit.TSUN027A.NetOfCostKelly_InvalidWinProbability_ReturnsZero(), Alaris.Test.Unit.TSUN027A.NetOfCostKelly_IsLessOrEqualToStandardKelly(), Alaris.Test.Unit.TSUN027A.NetOfCostKelly_NegativeAvgLoss_Throws(), Alaris.Test.Unit.TSUN027A.NetOfCostKelly_NegativeAvgWin_Throws(), Alaris.Test.Unit.TSUN027A.NetOfCostKelly_NegativeCost_Throws(), Alaris.Test.Unit.TSUN027A.NetOfCostKelly_NegativeExpectancy_ReturnsZeroOrPositive(), Alaris.Test.Unit.TSUN027A.NetOfCostKelly_ZeroCosts_MatchesStandardFormula(), Alaris.Test.Unit.Phase2MediumPriorityTests.STRK001A_CalculateNetOfCostKelly_CostsExceedEdge_ReturnsZero(), Alaris.Test.Unit.Phase2MediumPriorityTests.STRK001A_CalculateNetOfCostKelly_HighCost_ReturnsReduced(), and Alaris.Test.Unit.Phase2MediumPriorityTests.STRK001A_CalculateNetOfCostKelly_NoCost_ReturnsStandardKelly().
GetMinimumPosition()
static STRK002A Alaris.Strategy.Risk.STRK001A.GetMinimumPosition (double portfolioValue, double spreadCost) inline static private
Returns a minimum safe position size.
Definition at line 221 of file STRK001A.cs.
References Alaris.Strategy.Risk.STRK001A.ContractMultiplier.
Referenced by Alaris.Strategy.Risk.STRK001A.CalculateFromHistory().
SafeLog()
void Alaris.Strategy.Risk.STRK001A.SafeLog (Action logAction) inline private
Safely executes logging operation with fault isolation (Rule 15). Prevents logging failures from crashing critical paths.
Definition at line 242 of file STRK001A.cs.
References Alaris.Strategy.Risk.STRK001A._logger.
Referenced by Alaris.Strategy.Risk.STRK001A.CalculateFromHistory().
Member Data Documentation
_logger
readonly? ILogger<STRK001A> Alaris.Strategy.Risk.STRK001A._logger private
Definition at line 12 of file STRK001A.cs.
Referenced by Alaris.Strategy.Risk.STRK001A.STRK001A(), Alaris.Strategy.Risk.STRK001A.CalculateFromHistory(), and Alaris.Strategy.Risk.STRK001A.SafeLog().
ContractMultiplier
const double Alaris.Strategy.Risk.STRK001A.ContractMultiplier = 100.0 static private
Definition at line 47 of file STRK001A.cs.
Referenced by Alaris.Strategy.Risk.STRK001A.CalculateFromHistory(), and Alaris.Strategy.Risk.STRK001A.GetMinimumPosition().
FractionalKelly
const double Alaris.Strategy.Risk.STRK001A.FractionalKelly = 0.25 static private
Definition at line 45 of file STRK001A.cs.
Referenced by Alaris.Strategy.Risk.STRK001A.CalculateFromHistory().
LogErrorCalculatingPosition
readonly Action<ILogger, string, Exception?> Alaris.Strategy.Risk.STRK001A.LogErrorCalculatingPosition static private
Initial value:
=
        LoggerMessage.Define<string>(
            LogLevel.Error,
            new EventId(5, nameof(LogErrorCalculatingPosition)),
            "Error calculating position size for {Symbol}")
Definition at line 39 of file STRK001A.cs.
Referenced by Alaris.Strategy.Risk.STRK001A.CalculateFromHistory().
LogInsufficientTradeHistory
readonly Action<ILogger, int, Exception?> Alaris.Strategy.Risk.STRK001A.LogInsufficientTradeHistory static private
Initial value:
=
        LoggerMessage.Define<int>(
            LogLevel.Warning,
            new EventId(1, nameof(LogInsufficientTradeHistory)),
            "Insufficient trade history ({Count} trades), using minimum position size")
Definition at line 15 of file STRK001A.cs.
Referenced by Alaris.Strategy.Risk.STRK001A.CalculateFromHistory().
LogInvalidAverageWinLoss
readonly Action<ILogger, Exception?> Alaris.Strategy.Risk.STRK001A.LogInvalidAverageWinLoss static private
Initial value:
=
        LoggerMessage.Define(
            LogLevel.Warning,
            new EventId(3, nameof(LogInvalidAverageWinLoss)),
            "Invalid average win/loss, using minimum position size")
Definition at line 27 of file STRK001A.cs.
Referenced by Alaris.Strategy.Risk.STRK001A.CalculateFromHistory().
LogInvalidWinRate
readonly Action<ILogger, double, Exception?> Alaris.Strategy.Risk.STRK001A.LogInvalidWinRate static private
Initial value:
=
        LoggerMessage.Define<double>(
            LogLevel.Warning,
            new EventId(2, nameof(LogInvalidWinRate)),
            "Invalid win rate {WinRate:P2}, using minimum position size")
Definition at line 21 of file STRK001A.cs.
Referenced by Alaris.Strategy.Risk.STRK001A.CalculateFromHistory().
LogPositionCalculated
readonly Action<ILogger, string, int, double, double, Exception?> Alaris.Strategy.Risk.STRK001A.LogPositionCalculated static private
Initial value:
=
        LoggerMessage.Define<string, int, double, double>(
            LogLevel.Information,
            new EventId(4, nameof(LogPositionCalculated)),
            "Position calculated for {Symbol}: {Contracts} contracts, {Allocation:P2} allocation (Kelly={Kelly:P2})")
Definition at line 33 of file STRK001A.cs.
Referenced by Alaris.Strategy.Risk.STRK001A.CalculateFromHistory().
MaxAllocation
const double Alaris.Strategy.Risk.STRK001A.MaxAllocation = 0.06 static private
Definition at line 46 of file STRK001A.cs.
Referenced by Alaris.Strategy.Risk.STRK001A.CalculateFromHistory().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Risk/STRK001A.cs