Alaris: Alaris.Strategy.Core.MartingaleValidator Class Reference
Alaris.Strategy.Core.MartingaleValidator Class Reference sealed
Validates martingale conditions for calibrated models. Ensures risk-neutral pricing consistency.
Public Member Functions
bool Validate (RecommendedModel modelType, ModelSelectionContext context)
Validates martingale condition for a model.
Static Public Member Functions
static double ComputeJumpCompensation (KouParameters kouParams)
Computes the jump compensation term for martingale adjustment.
Static Private Member Functions
static bool ValidateLeungSantoli (ModelSelectionContext context)
Validates Leung and Santoli martingale condition. The model satisfies martingale by using the actual drift r-d.
static bool ValidateHeston (ModelSelectionContext context)
Validates Heston martingale condition. Stock drift must equal r - d.
static bool ValidateKou (ModelSelectionContext context)
Validates Kou martingale condition. Drift must be adjusted: r - d - lambda * kappa.
Static Private Attributes
const double DriftTolerance = 0.001
Tolerance for drift deviation from risk-neutral rate.
Detailed Description
Validates martingale conditions for calibrated models. Ensures risk-neutral pricing consistency.
Definition at line 316 of file STIV003A.cs.
Member Function Documentation
ComputeJumpCompensation()
static double Alaris.Strategy.Core.MartingaleValidator.ComputeJumpCompensation (KouParameters kouParams) inline static
Computes the jump compensation term for martingale adjustment.
Definition at line 398 of file STIV003A.cs.
References Alaris.Strategy.Core.KouParameters.ComputeKappa().
Referenced by Alaris.Test.Unit.IVModelTests.MartingaleValidator_ComputeJumpCompensation_ReturnsCorrectValue().
Validate()
bool Alaris.Strategy.Core.MartingaleValidator.Validate (RecommendedModel modelType, ModelSelectionContext context) inline
Validates martingale condition for a model.
Parameters
modelType The model type to validate.
context The model selection context containing market data.
Returns
True if the martingale condition is satisfied, false otherwise.
Definition at line 329 of file STIV003A.cs.
References Alaris.Strategy.Core.MartingaleValidator.ValidateHeston(), Alaris.Strategy.Core.MartingaleValidator.ValidateKou(), and Alaris.Strategy.Core.MartingaleValidator.ValidateLeungSantoli().
Referenced by Alaris.Strategy.Core.STIV003A.EvaluateModel().
ValidateHeston()
static bool Alaris.Strategy.Core.MartingaleValidator.ValidateHeston (ModelSelectionContext context) inline static private
Validates Heston martingale condition. Stock drift must equal r - d.
Definition at line 358 of file STIV003A.cs.
References Alaris.Strategy.Core.HestonParameters.DividendYield, Alaris.Strategy.Core.ModelSelectionContext.DividendYield, Alaris.Strategy.Core.MartingaleValidator.DriftTolerance, and Alaris.Strategy.Core.ModelSelectionContext.HestonParams.
Referenced by Alaris.Strategy.Core.MartingaleValidator.Validate().
ValidateKou()
static bool Alaris.Strategy.Core.MartingaleValidator.ValidateKou (ModelSelectionContext context) inline static private
Validates Kou martingale condition. Drift must be adjusted: r - d - lambda * kappa.
Definition at line 379 of file STIV003A.cs.
References Alaris.Strategy.Core.KouParameters.ComputeKappa(), Alaris.Strategy.Core.KouParameters.ComputeMartingaleDrift(), Alaris.Strategy.Core.MartingaleValidator.DriftTolerance, and Alaris.Strategy.Core.ModelSelectionContext.KouParams.
Referenced by Alaris.Strategy.Core.MartingaleValidator.Validate().
ValidateLeungSantoli()
static bool Alaris.Strategy.Core.MartingaleValidator.ValidateLeungSantoli (ModelSelectionContext context) inline static private
Validates Leung and Santoli martingale condition. The model satisfies martingale by using the actual drift r-d.
Definition at line 347 of file STIV003A.cs.
Referenced by Alaris.Strategy.Core.MartingaleValidator.Validate().
Member Data Documentation
DriftTolerance
const double Alaris.Strategy.Core.MartingaleValidator.DriftTolerance = 0.001 static private
Tolerance for drift deviation from risk-neutral rate.
Definition at line 321 of file STIV003A.cs.
Referenced by Alaris.Strategy.Core.MartingaleValidator.ValidateHeston(), and Alaris.Strategy.Core.MartingaleValidator.ValidateKou().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Core/STIV003A.cs