Alaris: Alaris.Host.Application.Command.BacktestRunCommand Class Reference
Alaris.Host.Application.Command.BacktestRunCommand Class Reference sealed
Runs a backtest session.
Public Member Functions
override async Task< int > ExecuteAsync (CommandContext context, BacktestRunSettings settings)
Static Private Member Functions
static bool bool bool optionsMissing CheckDataAvailability (string dataPath, APmd001A session)
static async Task BootstrapDataAsync (APmd001A session, APsv001A service, string dataPath)
static List< DateTime > GetEarningsDatesFromCache (string dataPath, DateTime startDate, DateTime endDate)
Parses earnings dates from cached calendar files.
static async Task< int > ExecuteLeanWithMonitoringAsync (APmd001A session, APsv001A service)
static async Task< int > ExecuteLeanForSession (APmd001A session, APsv001A service)
static ? string FindConfigPath ()
static ? string FindLeanLauncher ()
Static Private Attributes
static bool pricesMissing
static bool bool earningsMissing
Detailed Description
Runs a backtest session.
Definition at line 476 of file APcm005A.cs.
Member Function Documentation
BootstrapDataAsync()
static async Task Alaris.Host.Application.Command.BacktestRunCommand.BootstrapDataAsync (APmd001A session, APsv001A service, string dataPath) inline static private
Definition at line 657 of file APcm005A.cs.
References Alaris.Host.Application.Command.BacktestRunCommand.GetEarningsDatesFromCache().
Referenced by Alaris.Host.Application.Command.BacktestRunCommand.ExecuteAsync().
CheckDataAvailability()
static bool bool bool optionsMissing Alaris.Host.Application.Command.BacktestRunCommand.CheckDataAvailability (string dataPath, APmd001A session) inline static private
Definition at line 640 of file APcm005A.cs.
Referenced by Alaris.Host.Application.Command.BacktestRunCommand.ExecuteAsync().
ExecuteAsync()
override async Task< int > Alaris.Host.Application.Command.BacktestRunCommand.ExecuteAsync (CommandContext context, BacktestRunSettings settings) inline
Definition at line 478 of file APcm005A.cs.
References Alaris.Host.Application.Command.BacktestRunSettings.AutoBootstrap, Alaris.Host.Application.Command.BacktestRunCommand.BootstrapDataAsync(), Alaris.Host.Application.Command.BacktestRunCommand.CheckDataAvailability(), Alaris.Infrastructure.Protocol.Workflow.PLWF002A.Create(), Alaris.Host.Application.Command.BacktestRunCommand.earningsMissing, Alaris.Host.Application.Command.BacktestRunCommand.ExecuteLeanForSession(), Alaris.Host.Application.Command.BacktestRunCommand.ExecuteLeanWithMonitoringAsync(), Alaris.Host.Application.Command.BacktestRunSettings.Latest, Alaris.Host.Application.Command.BacktestRunSettings.NoMonitor, Alaris.Host.Application.Command.BacktestRunCommand.pricesMissing, and Alaris.Host.Application.Command.BacktestRunSettings.SessionId.
ExecuteLeanForSession()
static async Task< int > Alaris.Host.Application.Command.BacktestRunCommand.ExecuteLeanForSession (APmd001A session, APsv001A service) inline static private
Definition at line 817 of file APcm005A.cs.
References Alaris.Host.Application.Command.BacktestRunCommand.FindConfigPath(), Alaris.Host.Application.Command.BacktestRunCommand.FindLeanLauncher(), Alaris.Host.Application.Service.APsv001A.GetDataPath(), and Alaris.Host.Application.Service.APsv001A.GetResultsPath().
Referenced by Alaris.Host.Application.Command.BacktestRunCommand.ExecuteAsync(), and Alaris.Host.Application.Command.BacktestRunCommand.ExecuteLeanWithMonitoringAsync().
ExecuteLeanWithMonitoringAsync()
static async Task< int > Alaris.Host.Application.Command.BacktestRunCommand.ExecuteLeanWithMonitoringAsync (APmd001A session, APsv001A service) inline static private
Definition at line 805 of file APcm005A.cs.
References Alaris.Host.Application.Command.BacktestRunCommand.ExecuteLeanForSession().
Referenced by Alaris.Host.Application.Command.BacktestRunCommand.ExecuteAsync().
FindConfigPath()
static ? string Alaris.Host.Application.Command.BacktestRunCommand.FindConfigPath () inline static private
Definition at line 886 of file APcm005A.cs.
Referenced by Alaris.Host.Application.Command.BacktestRunCommand.ExecuteLeanForSession().
FindLeanLauncher()
static ? string Alaris.Host.Application.Command.BacktestRunCommand.FindLeanLauncher () inline static private
Definition at line 892 of file APcm005A.cs.
Referenced by Alaris.Host.Application.Command.BacktestRunCommand.ExecuteLeanForSession().
GetEarningsDatesFromCache()
static List< DateTime > Alaris.Host.Application.Command.BacktestRunCommand.GetEarningsDatesFromCache (string dataPath, DateTime startDate, DateTime endDate) inline static private
Parses earnings dates from cached calendar files.
Definition at line 768 of file APcm005A.cs.
Referenced by Alaris.Host.Application.Command.BacktestRunCommand.BootstrapDataAsync().
Member Data Documentation
earningsMissing
bool bool Alaris.Host.Application.Command.BacktestRunCommand.earningsMissing static private
Definition at line 640 of file APcm005A.cs.
Referenced by Alaris.Host.Application.Command.BacktestRunCommand.ExecuteAsync().
pricesMissing
bool Alaris.Host.Application.Command.BacktestRunCommand.pricesMissing static private
Definition at line 640 of file APcm005A.cs.
Referenced by Alaris.Host.Application.Command.BacktestRunCommand.ExecuteAsync().
The documentation for this class was generated from the following file:
src/Alaris.Host/Application/Command/APcm005A.cs