Alaris: Alaris.Host.Application.Service.APsv001A Class Reference
Alaris.Host.Application.Service.APsv001A Class Reference sealed
Service for managing backtest session lifecycle. Component ID: APsv001A.
Public Member Functions
APsv001A (string? sessionsRoot=null, ILogger< APsv001A >? logger=null)
Initializes the session service.
async Task< APmd001A > CreateAsync (DateTime startDate, DateTime endDate, IEnumerable< string >? symbols=null)
Creates a new backtest session.
async Task< APmd001A?> GetAsync (string sessionId)
Gets a session by ID.
async Task< IReadOnlyList< APmd001A > > ListAsync ()
Lists all sessions.
async Task UpdateAsync (APmd001A session)
Updates a session's status and metadata.
async Task DeleteAsync (string sessionId)
Deletes a session and all its data.
string GetDataPath (string sessionId)
Gets the data folder path for a session (for LEAN integration).
string GetResultsPath (string sessionId)
Gets the results folder path for a session.
Private Member Functions
async Task< int > GetNextSequenceAsync ()
Gets the next available sequence number for session IDs.
async Task< string > GenerateSessionIdAsync (DateTime startDate, DateTime endDate)
Generates a session ID following Alaris naming convention. Format: BT[Sequence][Variant]-[StartDate]-[EndDate].
async Task SaveSessionMetadataAsync (APmd001A session)
Saves session metadata to session.json.
async Task AddToIndexAsync (APmd001A session)
Adds a session to the index.
async Task RemoveFromIndexAsync (string sessionId)
Removes a session from the index.
async Task< SessionIndex > LoadIndexAsync ()
Loads the sessions index.
async Task SaveIndexAsync (SessionIndex index)
Saves the sessions index.
Static Private Member Functions
static int ParseSequenceFromId (string sessionId)
Parses the sequence number from a session ID.
static string FindSessionsRoot ()
Finds the sessions root directory.
Private Attributes
readonly string _sessionsRoot
readonly string _indexPath
readonly? ILogger< APsv001A > _logger
Static Private Attributes
static readonly JsonSerializerOptions JsonOptions
Detailed Description
Service for managing backtest session lifecycle. Component ID: APsv001A.
Definition at line 20 of file APsv001A.cs.
Constructor & Destructor Documentation
APsv001A()
Alaris.Host.Application.Service.APsv001A.APsv001A (string? sessionsRoot = null, ILogger< APsv001A >? logger = null) inline
Initializes the session service.
Parameters
sessionsRoot Root directory for sessions (defaults to Alaris.Sessions/).
logger Logger instance.
Definition at line 38 of file APsv001A.cs.
References Alaris.Host.Application.Service.APsv001A._indexPath, Alaris.Host.Application.Service.APsv001A._logger, Alaris.Host.Application.Service.APsv001A._sessionsRoot, and Alaris.Host.Application.Service.APsv001A.FindSessionsRoot().
Member Function Documentation
AddToIndexAsync()
async Task Alaris.Host.Application.Service.APsv001A.AddToIndexAsync (APmd001A session) inline private
Adds a session to the index.
Definition at line 260 of file APsv001A.cs.
References Alaris.Host.Application.Service.APsv001A.LoadIndexAsync(), and Alaris.Host.Application.Service.APsv001A.SaveIndexAsync().
Referenced by Alaris.Host.Application.Service.APsv001A.CreateAsync().
CreateAsync()
async Task< APmd001A > Alaris.Host.Application.Service.APsv001A.CreateAsync (DateTime startDate, DateTime endDate, IEnumerable< string >? symbols = null) inline
Creates a new backtest session.
Parameters
startDate Backtest start date.
endDate Backtest end date.
symbols Optional list of symbols (null = generate universe).
Returns
Created session.
Definition at line 55 of file APsv001A.cs.
References Alaris.Host.Application.Service.APsv001A._logger, Alaris.Host.Application.Service.APsv001A._sessionsRoot, Alaris.Host.Application.Service.APsv001A.AddToIndexAsync(), Alaris.Host.Application.Model.APmd001A, Alaris.Host.Application.Service.APsv001A.GenerateSessionIdAsync(), and Alaris.Host.Application.Service.APsv001A.SaveSessionMetadataAsync().
Referenced by Alaris.Test.Integration.TSIN005A.APsv001A_ConcurrentCreation_AllSessionsCreated(), Alaris.Test.Integration.TSIN005A.APsv001A_CreateAsync_CreatesFolderStructure(), Alaris.Test.Integration.TSIN005A.APsv001A_CreateAsync_CreatesSessionWithValidId(), Alaris.Test.Integration.TSIN005A.APsv001A_CreateAsync_IncludesSymbols(), Alaris.Test.Integration.TSIN005A.APsv001A_CreateAsync_RejectsInvalidDateRange(), Alaris.Test.Integration.TSIN005A.APsv001A_CreateAsync_RejectsSameDates(), Alaris.Test.Integration.TSIN005A.APsv001A_CreateAsync_SavesMetadata(), Alaris.Test.Integration.TSIN005A.APsv001A_CreateAsync_SetsCorrectDates(), Alaris.Test.Integration.TSIN005A.APsv001A_CreateAsync_SetsStatusToCreated(), Alaris.Test.Integration.TSIN005A.APsv001A_CreateMultiple_SequenceNumbersIncrease(), Alaris.Test.Integration.TSIN005A.APsv001A_DeleteAsync_RemovesFromIndex(), Alaris.Test.Integration.TSIN005A.APsv001A_DeleteAsync_RemovesSessionFolder(), Alaris.Test.Integration.TSIN005A.APsv001A_GetAsync_ReturnsSessionById(), Alaris.Test.Integration.TSIN005A.APsv001A_GetDataPath_ReturnsCorrectPath(), Alaris.Test.Integration.TSIN005A.APsv001A_GetResultsPath_ReturnsCorrectPath(), Alaris.Test.Integration.TSIN005A.APsv001A_ListAsync_ReturnsAllSessions(), Alaris.Test.Integration.TSIN005A.APsv001A_ListAsync_ReturnsOrderedByCreatedAt(), Alaris.Test.Integration.TSIN005A.APsv001A_UpdateAsync_PersistsStatusChange(), Alaris.Test.Integration.TSIN005A.APsv001A_UpdateAsync_UpdatesTimestamp(), Alaris.Test.Integration.TSIN005A.SessionId_ContainsCorrectDates(), and Alaris.Test.Integration.TSIN005A.SessionId_HasVariantSuffix().
DeleteAsync()
async Task Alaris.Host.Application.Service.APsv001A.DeleteAsync (string sessionId) inline
Deletes a session and all its data.
Definition at line 161 of file APsv001A.cs.
References Alaris.Host.Application.Service.APsv001A._logger, Alaris.Host.Application.Service.APsv001A._sessionsRoot, and Alaris.Host.Application.Service.APsv001A.RemoveFromIndexAsync().
Referenced by Alaris.Test.Integration.TSIN005A.APsv001A_DeleteAsync_RemovesFromIndex(), Alaris.Test.Integration.TSIN005A.APsv001A_DeleteAsync_RemovesSessionFolder(), and Alaris.Test.Integration.TSIN005A.APsv001A_DeleteAsync_ThrowsForNonExistent().
FindSessionsRoot()
static string Alaris.Host.Application.Service.APsv001A.FindSessionsRoot () inline static private
Finds the sessions root directory.
Definition at line 307 of file APsv001A.cs.
Referenced by Alaris.Host.Application.Service.APsv001A.APsv001A().
GenerateSessionIdAsync()
async Task< string > Alaris.Host.Application.Service.APsv001A.GenerateSessionIdAsync (DateTime startDate, DateTime endDate) inline private
Generates a session ID following Alaris naming convention. Format: BT[Sequence][Variant]-[StartDate]-[EndDate].
Definition at line 219 of file APsv001A.cs.
References Alaris.Host.Application.Service.APsv001A.GetNextSequenceAsync().
Referenced by Alaris.Host.Application.Service.APsv001A.CreateAsync().
GetAsync()
async Task< APmd001A?> Alaris.Host.Application.Service.APsv001A.GetAsync (string sessionId) inline
Gets a session by ID.
Definition at line 103 of file APsv001A.cs.
References Alaris.Host.Application.Service.APsv001A._sessionsRoot, Alaris.Host.Application.Model.APmd001A, and Alaris.Host.Application.Service.APsv001A.JsonOptions.
Referenced by Alaris.Test.Integration.TSIN005A.APsv001A_GetAsync_ReturnsNullForNonExistent(), Alaris.Test.Integration.TSIN005A.APsv001A_GetAsync_ReturnsSessionById(), Alaris.Test.Integration.TSIN005A.APsv001A_UpdateAsync_PersistsStatusChange(), Alaris.Test.Integration.TSIN005A.APsv001A_UpdateAsync_UpdatesTimestamp(), and Alaris.Host.Application.Service.APsv001A.ListAsync().
GetDataPath()
string Alaris.Host.Application.Service.APsv001A.GetDataPath (string sessionId) inline
Gets the data folder path for a session (for LEAN integration).
Definition at line 184 of file APsv001A.cs.
References Alaris.Host.Application.Service.APsv001A._sessionsRoot.
Referenced by Alaris.Test.Integration.TSIN005A.APsv001A_GetDataPath_ReturnsCorrectPath(), and Alaris.Host.Application.Command.BacktestRunCommand.ExecuteLeanForSession().
GetNextSequenceAsync()
async Task< int > Alaris.Host.Application.Service.APsv001A.GetNextSequenceAsync () inline private
Gets the next available sequence number for session IDs.
Definition at line 200 of file APsv001A.cs.
References Alaris.Host.Application.Service.APsv001A.ListAsync(), and Alaris.Host.Application.Service.APsv001A.ParseSequenceFromId().
Referenced by Alaris.Host.Application.Service.APsv001A.GenerateSessionIdAsync().
GetResultsPath()
string Alaris.Host.Application.Service.APsv001A.GetResultsPath (string sessionId) inline
Gets the results folder path for a session.
Definition at line 192 of file APsv001A.cs.
References Alaris.Host.Application.Service.APsv001A._sessionsRoot.
Referenced by Alaris.Test.Integration.TSIN005A.APsv001A_GetResultsPath_ReturnsCorrectPath(), and Alaris.Host.Application.Command.BacktestRunCommand.ExecuteLeanForSession().
ListAsync()
async Task< IReadOnlyList< APmd001A > > Alaris.Host.Application.Service.APsv001A.ListAsync () inline
Lists all sessions.
Definition at line 120 of file APsv001A.cs.
References Alaris.Host.Application.Service.APsv001A._indexPath, Alaris.Host.Application.Model.APmd001A, Alaris.Host.Application.Service.APsv001A.GetAsync(), and Alaris.Host.Application.Service.APsv001A.JsonOptions.
Referenced by Alaris.Test.Integration.TSIN005A.APsv001A_DeleteAsync_RemovesFromIndex(), Alaris.Test.Integration.TSIN005A.APsv001A_ListAsync_ReturnsAllSessions(), Alaris.Test.Integration.TSIN005A.APsv001A_ListAsync_ReturnsEmptyWhenNoSessions(), Alaris.Test.Integration.TSIN005A.APsv001A_ListAsync_ReturnsOrderedByCreatedAt(), and Alaris.Host.Application.Service.APsv001A.GetNextSequenceAsync().
LoadIndexAsync()
async Task< SessionIndex > Alaris.Host.Application.Service.APsv001A.LoadIndexAsync () inline private
Loads the sessions index.
Definition at line 283 of file APsv001A.cs.
References Alaris.Host.Application.Service.APsv001A._indexPath, and Alaris.Host.Application.Service.APsv001A.JsonOptions.
Referenced by Alaris.Host.Application.Service.APsv001A.AddToIndexAsync(), and Alaris.Host.Application.Service.APsv001A.RemoveFromIndexAsync().
ParseSequenceFromId()
static int Alaris.Host.Application.Service.APsv001A.ParseSequenceFromId (string sessionId) inline static private
Parses the sequence number from a session ID.
Definition at line 233 of file APsv001A.cs.
Referenced by Alaris.Host.Application.Service.APsv001A.GetNextSequenceAsync().
RemoveFromIndexAsync()
async Task Alaris.Host.Application.Service.APsv001A.RemoveFromIndexAsync (string sessionId) inline private
Removes a session from the index.
Definition at line 273 of file APsv001A.cs.
References Alaris.Host.Application.Service.APsv001A.LoadIndexAsync(), and Alaris.Host.Application.Service.APsv001A.SaveIndexAsync().
Referenced by Alaris.Host.Application.Service.APsv001A.DeleteAsync().
SaveIndexAsync()
async Task Alaris.Host.Application.Service.APsv001A.SaveIndexAsync (SessionIndex index) inline private
Saves the sessions index.
Definition at line 298 of file APsv001A.cs.
References Alaris.Host.Application.Service.APsv001A._indexPath, and Alaris.Host.Application.Service.APsv001A.JsonOptions.
Referenced by Alaris.Host.Application.Service.APsv001A.AddToIndexAsync(), and Alaris.Host.Application.Service.APsv001A.RemoveFromIndexAsync().
SaveSessionMetadataAsync()
async Task Alaris.Host.Application.Service.APsv001A.SaveSessionMetadataAsync (APmd001A session) inline private
Saves session metadata to session.json.
Definition at line 250 of file APsv001A.cs.
References Alaris.Host.Application.Service.APsv001A.JsonOptions.
Referenced by Alaris.Host.Application.Service.APsv001A.CreateAsync(), and Alaris.Host.Application.Service.APsv001A.UpdateAsync().
UpdateAsync()
async Task Alaris.Host.Application.Service.APsv001A.UpdateAsync (APmd001A session) inline
Updates a session's status and metadata.
Definition at line 151 of file APsv001A.cs.
References Alaris.Host.Application.Service.APsv001A._logger, and Alaris.Host.Application.Service.APsv001A.SaveSessionMetadataAsync().
Referenced by Alaris.Test.Integration.TSIN005A.APsv001A_UpdateAsync_PersistsStatusChange(), and Alaris.Test.Integration.TSIN005A.APsv001A_UpdateAsync_UpdatesTimestamp().
Member Data Documentation
_indexPath
readonly string Alaris.Host.Application.Service.APsv001A._indexPath private
Definition at line 23 of file APsv001A.cs.
Referenced by Alaris.Host.Application.Service.APsv001A.APsv001A(), Alaris.Host.Application.Service.APsv001A.ListAsync(), Alaris.Host.Application.Service.APsv001A.LoadIndexAsync(), and Alaris.Host.Application.Service.APsv001A.SaveIndexAsync().
_logger
readonly? ILogger<APsv001A> Alaris.Host.Application.Service.APsv001A._logger private
Definition at line 24 of file APsv001A.cs.
Referenced by Alaris.Host.Application.Service.APsv001A.APsv001A(), Alaris.Host.Application.Service.APsv001A.CreateAsync(), Alaris.Host.Application.Service.APsv001A.DeleteAsync(), and Alaris.Host.Application.Service.APsv001A.UpdateAsync().
_sessionsRoot
readonly string Alaris.Host.Application.Service.APsv001A._sessionsRoot private
Definition at line 22 of file APsv001A.cs.
Referenced by Alaris.Host.Application.Service.APsv001A.APsv001A(), Alaris.Host.Application.Service.APsv001A.CreateAsync(), Alaris.Host.Application.Service.APsv001A.DeleteAsync(), Alaris.Host.Application.Service.APsv001A.GetAsync(), Alaris.Host.Application.Service.APsv001A.GetDataPath(), and Alaris.Host.Application.Service.APsv001A.GetResultsPath().
JsonOptions
readonly JsonSerializerOptions Alaris.Host.Application.Service.APsv001A.JsonOptions static private
Initial value:
= new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        Converters = { new JsonStringEnumConverter() }
    }
Definition at line 26 of file APsv001A.cs.
Referenced by Alaris.Host.Application.Service.APsv001A.GetAsync(), Alaris.Host.Application.Service.APsv001A.ListAsync(), Alaris.Host.Application.Service.APsv001A.LoadIndexAsync(), Alaris.Host.Application.Service.APsv001A.SaveIndexAsync(), and Alaris.Host.Application.Service.APsv001A.SaveSessionMetadataAsync().
The documentation for this class was generated from the following file:
src/Alaris.Host/Application/Service/APsv001A.cs