Alaris: Alaris.Strategy.Core.STIV004A Class Reference
Alaris.Strategy.Core.STIV004A Class Reference sealed
Implements the Leung & Santoli (2014) pre-earnings announcement implied volatility model. The model accounts for scheduled earnings jumps in option pricing by incorporating a deterministic-time random jump in the stock price dynamics. The pre-EA implied volatility follows: I(t; K, T) = sqrt(sigma^2 + sigma_e^2 / (T - t)) Where: sigma = base (diffusion) volatility sigma_e = earnings jump volatility (calibrated from historical EA moves) T = option expiration time t = current time (must be before EA date T_e) Reference: "Accounting for Earnings Announcements in the Pricing of Equity Options" Tim Leung & Marco Santoli (2014), Journal of Derivatives.
Static Public Member Functions
static double ComputeTheoreticalIV (double baseVolatility, double earningsJumpVolatility, double timeToExpiry)
Computes the theoretical pre-earnings announcement implied volatility.
static double ComputeMispricingSTCR004A (double marketIV, double baseVolatility, double earningsJumpVolatility, double timeToExpiry)
Computes the IV mispricing signal by comparing market IV to theoretical L&S IV. Positive values indicate market IV is higher than theoretical (potentially overpriced). Negative values indicate market IV is lower than theoretical (potentially underpriced).
static double ComputeExpectedIVCrush (double baseVolatility, double earningsJumpVolatility, double timeToExpiry)
Computes the expected IV crush magnitude after earnings announcement. This represents the drop from pre-EA IV to post-EA IV.
static double ComputeIVCrushRatio (double baseVolatility, double earningsJumpVolatility, double timeToExpiry)
Computes the IV crush ratio (relative magnitude of expected crush).
static double ExtractEarningsJumpVolatility (double marketIV, double baseVolatility, double timeToExpiry)
Extracts the earnings jump volatility (sigma_e) from observed market IV. This is the inverse of the L&S formula, solving for sigma_e given market IV.
static int double TheoreticalIV[] ComputeSTTM001A (double baseVolatility, double earningsJumpVolatility, int[] dtePoints)
Static Public Attributes
static int DTE
Computes the term structure of theoretical IV at different DTEs. Useful for comparing against market term structure.
Static Private Attributes
const double MinTimeToExpiry = 1.0 / (252.0 * 6.5)
Minimum time to expiry to avoid division by zero (1 hour in years).
Detailed Description
Implements the Leung & Santoli (2014) pre-earnings announcement implied volatility model. The model accounts for scheduled earnings jumps in option pricing by incorporating a deterministic-time random jump in the stock price dynamics. The pre-EA implied volatility follows: I(t; K, T) = sqrt(sigma^2 + sigma_e^2 / (T - t)) Where: sigma = base (diffusion) volatility sigma_e = earnings jump volatility (calibrated from historical EA moves) T = option expiration time t = current time (must be before EA date T_e) Reference: "Accounting for Earnings Announcements in the Pricing of Equity Options" Tim Leung & Marco Santoli (2014), Journal of Derivatives.
Definition at line 21 of file STIV004A.cs.
Member Function Documentation
ComputeExpectedIVCrush()
static double Alaris.Strategy.Core.STIV004A.ComputeExpectedIVCrush (double baseVolatility, double earningsJumpVolatility, double timeToExpiry) inline static
Computes the expected IV crush magnitude after earnings announcement. This represents the drop from pre-EA IV to post-EA IV.
Parameters
baseVolatility The base (diffusion) volatility sigma.
earningsJumpVolatility The earnings jump volatility sigma_e.
timeToExpiry Time to option expiration in years (T - t).
Returns
The expected IV crush in volatility points.
Definition at line 94 of file STIV004A.cs.
References Alaris.Strategy.Core.STIV004A.ComputeTheoreticalIV().
Referenced by Alaris.Test.Unit.STIV004ATests.ComputeExpectedIVCrush_IncreasesAsExpiryApproaches(), Alaris.Test.Unit.STIV004ATests.ComputeExpectedIVCrush_IsPositiveWithEarningsJump(), Alaris.Strategy.Core.STIV004A.ComputeIVCrushRatio(), and Alaris.Strategy.Core.STCR001A.ComputeTheoreticalMetrics().
ComputeIVCrushRatio()
static double Alaris.Strategy.Core.STIV004A.ComputeIVCrushRatio (double baseVolatility, double earningsJumpVolatility, double timeToExpiry) inline static
Computes the IV crush ratio (relative magnitude of expected crush).
Parameters
baseVolatility The base (diffusion) volatility sigma.
earningsJumpVolatility The earnings jump volatility sigma_e.
timeToExpiry Time to option expiration in years (T - t).
Returns
The IV crush as a percentage of pre-EA IV.
Definition at line 111 of file STIV004A.cs.
References Alaris.Strategy.Core.STIV004A.ComputeExpectedIVCrush(), and Alaris.Strategy.Core.STIV004A.ComputeTheoreticalIV().
Referenced by Alaris.Test.Unit.STIV004ATests.ComputeIVCrushRatio_IsBetweenZeroAndOne(), and Alaris.Strategy.Core.STCR001A.ComputeTheoreticalMetrics().
ComputeMispricingSTCR004A()
static double Alaris.Strategy.Core.STIV004A.ComputeMispricingSTCR004A (double marketIV, double baseVolatility, double earningsJumpVolatility, double timeToExpiry) inline static
Computes the IV mispricing signal by comparing market IV to theoretical L&S IV. Positive values indicate market IV is higher than theoretical (potentially overpriced). Negative values indicate market IV is lower than theoretical (potentially underpriced).
Parameters
marketIV The observed market implied volatility.
baseVolatility The base (diffusion) volatility sigma.
earningsJumpVolatility The earnings jump volatility sigma_e.
timeToExpiry Time to option expiration in years (T - t).
Returns
The mispricing signal (market IV - theoretical IV).
Definition at line 76 of file STIV004A.cs.
References Alaris.Strategy.Core.STIV004A.ComputeTheoreticalIV().
Referenced by Alaris.Test.Unit.STIV004ATests.ComputeMispricingSTCR004A_NegativeWhenMarketIVLower(), and Alaris.Test.Unit.STIV004ATests.ComputeMispricingSTCR004A_PositiveWhenMarketIVHigher().
ComputeSTTM001A()
static int double TheoreticalIV[] Alaris.Strategy.Core.STIV004A.ComputeSTTM001A (double baseVolatility, double earningsJumpVolatility, int[] dtePoints) inline static
Definition at line 177 of file STIV004A.cs.
References Alaris.Strategy.Core.STIV004A.ComputeTheoreticalIV(), Alaris.Strategy.Core.STIV004A.DTE, and Alaris.Strategy.Calendar.TradingCalendarDefaults.DteToYears().
Referenced by Alaris.Test.Unit.STIV004ATests.ComputeSTTM001A_ConvergesToBaseVolatility(), and Alaris.Test.Unit.STIV004ATests.ComputeSTTM001A_ProducesInvertedStructure().
ComputeTheoreticalIV()
static double Alaris.Strategy.Core.STIV004A.ComputeTheoreticalIV (double baseVolatility, double earningsJumpVolatility, double timeToExpiry) inline static
Computes the theoretical pre-earnings announcement implied volatility.
Parameters
baseVolatility The base (diffusion) volatility sigma.
earningsJumpVolatility The earnings jump volatility sigma_e.
timeToExpiry Time to option expiration in years (T - t).
Returns
The theoretical implied volatility I(t; K, T).
Exceptions
ArgumentException Thrown when parameters are invalid.
Definition at line 36 of file STIV004A.cs.
References Alaris.Strategy.Core.STIV004A.MinTimeToExpiry.
Referenced by Alaris.Strategy.Core.STIV004A.ComputeExpectedIVCrush(), Alaris.Strategy.Core.STIV004A.ComputeIVCrushRatio(), Alaris.Strategy.Core.STIV004A.ComputeMispricingSTCR004A(), Alaris.Test.Unit.STIV004ATests.ComputeMispricingSTCR004A_NegativeWhenMarketIVLower(), Alaris.Strategy.Core.STIV003A.ComputeModelIVs(), Alaris.Strategy.Core.LeungSantoliExtensions.ComputePreEarningsIV(), Alaris.Strategy.Core.STIV004A.ComputeSTTM001A(), Alaris.Test.Unit.STIV004ATests.ComputeTheoreticalIV_DecreasesWithTimeToExpiry(), Alaris.Test.Unit.STIV004ATests.ComputeTheoreticalIV_MatchesLeungSantoliFormula(), Alaris.Test.Unit.STIV004ATests.ComputeTheoreticalIV_ThrowsOnNegativeBaseVolatility(), Alaris.Test.Unit.STIV004ATests.ComputeTheoreticalIV_ThrowsOnNegativeEarningsJump(), Alaris.Test.Unit.STIV004ATests.ComputeTheoreticalIV_ThrowsOnZeroOrNegativeTimeToExpiry(), Alaris.Test.Unit.STIV004ATests.ComputeTheoreticalIV_WhenEarningsJumpPresent_IVIsHigher(), Alaris.Test.Unit.STIV004ATests.ComputeTheoreticalIV_WhenNoEarningsJump_ReturnsBaseVolatility(), Alaris.Strategy.Core.STCR001A.ComputeTheoreticalMetrics(), and Alaris.Test.Unit.STIV004ATests.ExtractEarningsJumpVolatility_RecoversOriginalSigmaE().
ExtractEarningsJumpVolatility()
static double Alaris.Strategy.Core.STIV004A.ExtractEarningsJumpVolatility (double marketIV, double baseVolatility, double timeToExpiry) inline static
Extracts the earnings jump volatility (sigma_e) from observed market IV. This is the inverse of the L&S formula, solving for sigma_e given market IV.
Parameters
marketIV The observed market implied volatility.
baseVolatility The base (diffusion) volatility sigma.
timeToExpiry Time to option expiration in years (T - t).
Returns
The implied earnings jump volatility sigma_e.
Definition at line 134 of file STIV004A.cs.
Referenced by Alaris.Test.Unit.STIV004ATests.ExtractEarningsJumpVolatility_RecoversOriginalSigmaE(), and Alaris.Test.Unit.STIV004ATests.ExtractEarningsJumpVolatility_ReturnsZeroWhenIVBelowBase().
Member Data Documentation
DTE
int Alaris.Strategy.Core.STIV004A.DTE static
Computes the term structure of theoretical IV at different DTEs. Useful for comparing against market term structure.
Parameters
baseVolatility The base (diffusion) volatility sigma.
earningsJumpVolatility The earnings jump volatility sigma_e.
dtePoints Array of days-to-expiry points.
Returns
Array of (DTE, TheoreticalIV) tuples.
Definition at line 177 of file STIV004A.cs.
Referenced by Alaris.Strategy.Core.STIV004A.ComputeSTTM001A().
MinTimeToExpiry
const double Alaris.Strategy.Core.STIV004A.MinTimeToExpiry = 1.0 / (252.0 * 6.5) static private
Minimum time to expiry to avoid division by zero (1 hour in years).
Definition at line 26 of file STIV004A.cs.
Referenced by Alaris.Strategy.Core.STIV004A.ComputeTheoreticalIV().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Core/STIV004A.cs