Alaris: Alaris.Core.Options Namespace Reference
Alaris.Core.Options Namespace Reference
Classes
struct AmericanExercise
American exercise specification. Replaces QuantLib AmericanExercise.
class DividendSchedule
Immutable schedule of discrete cash dividends for option pricing.
class OptionTypeExtensions
Extension methods for OptionType.
struct VanillaPayoff
Plain vanilla option payoff (European/American style). Replaces QuantLib PlainVanillaPayoff.
Enumerations
enum OptionType { Call = 1 , Put = -1 }
Option type enumeration matching QuantLib Option.Type semantics.
enum CashDividendModel { Spot , Escrowed }
Cash dividend model determining how discrete dividends affect pricing.
Functions
readonly record struct CashDividend (DateTime ExDividendDate, double Amount)
Represents a single discrete cash dividend payment.
Enumeration Type Documentation
CashDividendModel
enum Alaris.Core.Options.CashDividendModel
Cash dividend model determining how discrete dividends affect pricing.
Enumerator
Spot
Spot model: Subtract present value of dividends from current spot price. Simple, but less accurate for American options near dividend dates.
S_adjusted = S - Σ [D_i × exp(-r × t_i)] for all dividends D_i at time t_i.
Escrowed
Escrowed model: Handle dividends as jump conditions in the FD grid. More accurate but computationally expensive.
At each dividend date, apply V(S) → V(S - D) transformation in the grid. Requires grid interpolation at dividend times.
Definition at line 22 of file CROP004A.cs.
OptionType
enum Alaris.Core.Options.OptionType
Option type enumeration matching QuantLib Option.Type semantics.
Values are +1 for Call and -1 for Put to enable elegant payoff calculations:
Call payoff = max(S - K, 0) = max((S - K) * 1, 0)
Put payoff = max(K - S, 0) = max((S - K) * -1, 0) * -1
Enumerator
Call
Call option: right to buy at strike.
Put
Put option: right to sell at strike.
Definition at line 28 of file CROP001A.cs.
Function Documentation
CashDividend()
readonly record struct Alaris.Core.Options.CashDividend (DateTime ExDividendDate, double Amount)
Represents a single discrete cash dividend payment.
Parameters
ExDividendDate Ex-dividend date.
Amount Dividend amount per share.
Validates the dividend parameters.
Returns
True if valid.
Definition at line 49 of file CROP004A.cs.
Referenced by Alaris.Core.Options.DividendSchedule.DividendSchedule(), Alaris.Core.Options.DividendSchedule.ComputePresentValue(), Alaris.Core.Options.DividendSchedule.FromContinuousYield(), Alaris.Core.Options.DividendSchedule.GetDividendsBetween(), and Alaris.Core.Options.DividendSchedule.GetDividendTimesForGrid().