Alaris: Alaris.Host.Application.Cli.Infrastructure.CLif003A Class Reference
Alaris.Host.Application.Cli.Infrastructure.CLif003A Class Reference
Rich console output utilities for consistent CLI appearance. Component ID: CLif003A.
Static Public Member Functions
static void WriteBanner ()
Writes the Alaris banner.
static void Success (string message)
Writes a success message.
static void Error (string message)
Writes an error message.
static void Warning (string message)
Writes a warning message.
static void Info (string message)
Writes an info message.
static async Task< T > WithStatusAsync< T > (string message, Func< StatusContext, Task< T > > action)
Creates a status context for long-running operations.
static async Task WithProgressAsync (string description, Func< ProgressContext, Task > action)
Creates a progress context for multi-step operations.
static void WriteKeyValueTable (string title, IEnumerable<(string Key, string Value)> items)
Writes a key-value table.
static void WriteTable< T > (string title, IEnumerable< T > items, params(string Header, Func< T, string > Selector)[] columns)
Writes a data table with custom columns.
static bool Confirm (string prompt, bool defaultValue=false)
Prompts for confirmation.
static void WritePanel (string title, string content, Color? borderColor=null)
Writes a panel with content.
static void WriteRule (string? title=null)
Writes a rule (horizontal line with optional title).
Static Private Attributes
const string Version = "2.0.0"
Detailed Description
Rich console output utilities for consistent CLI appearance. Component ID: CLif003A.
Definition at line 12 of file CLif003A.cs.
Member Function Documentation
Confirm()
static bool Alaris.Host.Application.Cli.Infrastructure.CLif003A.Confirm (string prompt, bool defaultValue = false) inline static
Prompts for confirmation.
Definition at line 142 of file CLif003A.cs.
Error()
static void Alaris.Host.Application.Cli.Infrastructure.CLif003A.Error (string message) inline static
Writes an error message.
Definition at line 41 of file CLif003A.cs.
Referenced by Alaris.Host.Application.Cli.Commands.Strategy.CLst003A.Execute(), Alaris.Host.Application.Cli.Commands.Strategy.CLst002A.Execute(), Alaris.Host.Application.Cli.Commands.Backtest.CLbt002A.ExecuteAsync(), Alaris.Host.Application.Cli.Commands.Data.CLdt001A.ExecuteAsync(), Alaris.Host.Application.Cli.Commands.Data.CLdt002A.ExecuteAsync(), Alaris.Host.Application.Cli.Commands.Data.CLdt003A.ExecuteAsync(), and Alaris.Host.Application.Cli.Commands.Earnings.CLer003A.ExecuteAsync().
Info()
static void Alaris.Host.Application.Cli.Infrastructure.CLif003A.Info (string message) inline static
Writes an info message.
Definition at line 57 of file CLif003A.cs.
Referenced by Alaris.Host.Application.Cli.Commands.Strategy.CLst001A.Execute(), Alaris.Host.Application.Cli.Commands.Strategy.CLst003A.Execute(), Alaris.Host.Application.Cli.Commands.Trade.CLtr003A.Execute(), Alaris.Host.Application.Cli.Commands.Trade.CLtr002A.Execute(), Alaris.Host.Application.Cli.Commands.Backtest.CLbt002A.ExecuteAsync(), Alaris.Host.Application.Cli.Commands.Backtest.CLbt003A.ExecuteAsync(), Alaris.Host.Application.Cli.Commands.Data.CLdt001A.ExecuteAsync(), Alaris.Host.Application.Cli.Commands.Data.CLdt002A.ExecuteAsync(), Alaris.Host.Application.Cli.Commands.Data.CLdt003A.ExecuteAsync(), Alaris.Host.Application.Cli.Commands.Earnings.CLer003A.ExecuteAsync(), and Alaris.Host.Application.Cli.Commands.Earnings.CLer002A.ExecuteAsync().
Success()
static void Alaris.Host.Application.Cli.Infrastructure.CLif003A.Success (string message) inline static
Writes a success message.
Definition at line 33 of file CLif003A.cs.
Referenced by Alaris.Host.Application.Cli.Commands.Strategy.CLst003A.Execute(), Alaris.Host.Application.Cli.Commands.Backtest.CLbt002A.ExecuteAsync(), Alaris.Host.Application.Cli.Commands.Data.CLdt001A.ExecuteAsync(), and Alaris.Host.Application.Cli.Commands.Data.CLdt003A.ExecuteAsync().
Warning()
static void Alaris.Host.Application.Cli.Infrastructure.CLif003A.Warning (string message) inline static
Writes a warning message.
Definition at line 49 of file CLif003A.cs.
Referenced by Alaris.Host.Application.Cli.Commands.Strategy.CLst003A.Execute(), Alaris.Host.Application.Cli.Commands.Backtest.CLbt002A.ExecuteAsync(), Alaris.Host.Application.Cli.Commands.Data.CLdt002A.ExecuteAsync(), Alaris.Host.Application.Cli.Commands.Data.CLdt003A.ExecuteAsync(), Alaris.Host.Application.Cli.Commands.Earnings.CLer003A.ExecuteAsync(), and Alaris.Host.Application.Cli.Commands.Earnings.CLer002A.ExecuteAsync().
WithProgressAsync()
static async Task Alaris.Host.Application.Cli.Infrastructure.CLif003A.WithProgressAsync (string description, Func< ProgressContext, Task > action) inline static
Creates a progress context for multi-step operations.
Definition at line 76 of file CLif003A.cs.
Referenced by Alaris.Host.Application.Cli.Commands.Data.CLdt003A.ExecuteAsync().
WithStatusAsync< T >()
static async Task< T > Alaris.Host.Application.Cli.Infrastructure.CLif003A.WithStatusAsync< T > (string message, Func< StatusContext, Task< T > > action) inline static
Creates a status context for long-running operations.
Definition at line 65 of file CLif003A.cs.
WriteBanner()
static void Alaris.Host.Application.Cli.Infrastructure.CLif003A.WriteBanner () inline static
Writes the Alaris banner.
Definition at line 19 of file CLif003A.cs.
Referenced by Alaris.Host.Application.Cli.Commands.CLvr001A.Execute().
WriteKeyValueTable()
static void Alaris.Host.Application.Cli.Infrastructure.CLif003A.WriteKeyValueTable (string title, IEnumerable<(string Key, string Value)> items) inline static
Writes a key-value table.
Definition at line 95 of file CLif003A.cs.
Referenced by Alaris.Host.Application.Cli.Commands.CLvr001A.Execute(), Alaris.Host.Application.Cli.Commands.Trade.CLtr002A.Execute(), Alaris.Host.Application.Cli.Commands.Backtest.CLbt002A.ExecuteAsync(), Alaris.Host.Application.Cli.Commands.Data.CLdt001A.ExecuteAsync(), Alaris.Host.Application.Cli.Commands.Data.CLdt003A.ExecuteAsync(), and Alaris.Host.Application.Cli.Commands.Earnings.CLer003A.ExecuteAsync().
WritePanel()
static void Alaris.Host.Application.Cli.Infrastructure.CLif003A.WritePanel (string title, string content, Color? borderColor = null) inline static
Writes a panel with content.
Definition at line 150 of file CLif003A.cs.
Referenced by Alaris.Host.Application.Cli.Commands.Strategy.CLst002A.Execute().
WriteRule()
static void Alaris.Host.Application.Cli.Infrastructure.CLif003A.WriteRule (string? title = null) inline static
Writes a rule (horizontal line with optional title).
Definition at line 164 of file CLif003A.cs.
WriteTable< T >()
static void Alaris.Host.Application.Cli.Infrastructure.CLif003A.WriteTable< T > (string title, IEnumerable< T > items, params(string Header, Func< T, string > Selector)[] columns) inline static
Writes a data table with custom columns.
Definition at line 115 of file CLif003A.cs.
Member Data Documentation
Version
const string Alaris.Host.Application.Cli.Infrastructure.CLif003A.Version = "2.0.0" static private
Definition at line 14 of file CLif003A.cs.
The documentation for this class was generated from the following file:
src/Alaris.Host/Application/Cli/Infrastructure/CLif003A.cs