Alaris: Alaris.Test.Unit.TSUN027A Class Reference
Alaris.Test.Unit.TSUN027A Class Reference sealed
TSUN027A: Unit tests for risk management components. Tests Kelly Criterion sizing and maturity guard logic.
Public Member Functions
void NetOfCostKelly_IsLessOrEqualToStandardKelly (double winProb, double avgWin, double avgLoss, double roundTripCost)
INVARIANT: Net-of-cost Kelly ≤ Standard Kelly (costs reduce optimal bet).
void NetOfCostKelly_CostsExceedEdge_ReturnsZero ()
When costs exceed edge, Kelly should be zero (no positive expectancy).
void NetOfCostKelly_InvalidWinProbability_ReturnsZero (double winProb)
INVARIANT: Kelly = 0 when win probability = 0 or 1.
void NetOfCostKelly_ZeroCosts_MatchesStandardFormula ()
Standard Kelly formula: f* = (p*b - q) / b where b = avgWin/avgLoss.
void NetOfCostKelly_NegativeExpectancy_ReturnsZeroOrPositive (double winProb, double avgWin, double avgLoss)
INVARIANT: Kelly ≥ 0 (never bet negative amounts).
void NetOfCostKelly_NegativeAvgWin_Throws ()
Invalid inputs should throw appropriate exceptions.
void NetOfCostKelly_NegativeAvgLoss_Throws ()
void NetOfCostKelly_NegativeCost_Throws ()
void CalculateFromHistory_InsufficientHistory_ReturnsMinimumPosition (int tradeCount)
Insufficient trade history should return minimum position.
void CalculateFromHistory_CapsAtMaxAllocation ()
INVARIANT: Position allocation ≤ MaxAllocation (6%).
void CalculateFromHistory_NeverReturnsNegativeContracts ()
INVARIANT: Contracts ≥ 0 (never negative positions).
void CalculateFromHistory_WeakSignal_ReducesAllocation ()
Signal strength affects allocation.
void CalculateFromHistory_AvoidSignal_ReturnsZeroAllocation ()
Avoid signal should result in zero allocation.
void CalculateFromHistory_InvalidPortfolioValue_Throws (double portfolioValue)
Invalid portfolio value should throw.
void CalculateFromHistory_InvalidSpreadCost_Throws (double spreadCost)
Invalid spread cost should throw.
void STRK002A_Validate_ValidPosition_DoesNotThrow ()
Valid position size should pass validation.
void STRK002A_Validate_NegativeContracts_Throws ()
Negative contracts should fail validation.
void STRK002A_Validate_ExceedsMaxAllocation_Throws ()
Allocation exceeding maximum should fail validation.
void STRK002A_Validate_CustomMaxAllocation_Respected ()
Custom max allocation should be respected.
void STRK002A_Validate_RiskExceedsAllocation_Throws ()
Risk exceeding allocation should fail validation.
void STRK002A_RiskRewardRatio_ComputesCorrectly ()
RiskRewardRatio computed property should work correctly.
void STRK002A_RiskRewardRatio_ZeroMaxLoss_ReturnsZero ()
RiskRewardRatio with zero max loss should be zero.
void STMG001A_EvaluateEntry_AboveMinimum_Allows ()
Entry should be allowed above minimum maturity threshold.
void STMG001A_EvaluateEntry_BelowMinimum_Rejects ()
Entry should be rejected below minimum maturity threshold.
void STMG001A_EvaluateExit_AboveThreshold_NoExit ()
Exit should not be required above force-exit threshold.
void STMG001A_EvaluateExit_BelowThreshold_ImmediateExit ()
Exit should be immediate below force-exit threshold.
void STMG001A_CustomThresholds_Respected ()
Custom thresholds should be respected.
void STMG001A_Constructor_InvalidThresholds_Throws ()
Invalid threshold configuration should throw.
void STMG001A_CalculateTimeToExpiryApproximate_ReturnsReasonableValue ()
Time-to-expiry calculation should be reasonable.
void STMG001A_CalculateTimeToExpiryApproximate_PastExpiry_ReturnsNonPositive ()
Expired options (past expiry) should return zero or negative time.
void Trade_HoldingPeriod_ComputesCorrectly ()
HoldingPeriod computed property should be correct.
void Trade_IsWinner_BasedOnProfitLoss (double pl, bool expectedWinner)
IsWinner should be true for positive P&L.
Static Private Member Functions
static List< Trade > CreateWinningTradeHistory (int count, double avgWin)
static List< Trade > CreateMixedTradeHistory (int wins, int losses, double avgWin, double avgLoss)
static STCR004A CreateSignal (STCR004AStrength strength=STCR004AStrength.Recommended)
Detailed Description
TSUN027A: Unit tests for risk management components. Tests Kelly Criterion sizing and maturity guard logic.
Definition at line 33 of file TSUN027A.cs.
Member Function Documentation
CalculateFromHistory_AvoidSignal_ReturnsZeroAllocation()
void Alaris.Test.Unit.TSUN027A.CalculateFromHistory_AvoidSignal_ReturnsZeroAllocation () inline
Avoid signal should result in zero allocation.
Definition at line 308 of file TSUN027A.cs.
References Alaris.Test.Unit.TSUN027A.CreateMixedTradeHistory(), and Alaris.Test.Unit.TSUN027A.CreateSignal().
CalculateFromHistory_CapsAtMaxAllocation()
void Alaris.Test.Unit.TSUN027A.CalculateFromHistory_CapsAtMaxAllocation () inline
INVARIANT: Position allocation ≤ MaxAllocation (6%).
Definition at line 250 of file TSUN027A.cs.
References Alaris.Test.Unit.TSUN027A.CreateMixedTradeHistory(), and Alaris.Test.Unit.TSUN027A.CreateSignal().
CalculateFromHistory_InsufficientHistory_ReturnsMinimumPosition()
void Alaris.Test.Unit.TSUN027A.CalculateFromHistory_InsufficientHistory_ReturnsMinimumPosition (int tradeCount) inline
Insufficient trade history should return minimum position.
Definition at line 230 of file TSUN027A.cs.
References Alaris.Test.Unit.TSUN027A.CreateSignal(), and Alaris.Test.Unit.TSUN027A.CreateWinningTradeHistory().
CalculateFromHistory_InvalidPortfolioValue_Throws()
void Alaris.Test.Unit.TSUN027A.CalculateFromHistory_InvalidPortfolioValue_Throws (double portfolioValue) inline
Invalid portfolio value should throw.
Definition at line 329 of file TSUN027A.cs.
References Alaris.Test.Unit.TSUN027A.CreateSignal(), and Alaris.Test.Unit.TSUN027A.CreateWinningTradeHistory().
CalculateFromHistory_InvalidSpreadCost_Throws()
void Alaris.Test.Unit.TSUN027A.CalculateFromHistory_InvalidSpreadCost_Throws (double spreadCost) inline
Invalid spread cost should throw.
Definition at line 347 of file TSUN027A.cs.
References Alaris.Test.Unit.TSUN027A.CreateSignal(), and Alaris.Test.Unit.TSUN027A.CreateWinningTradeHistory().
CalculateFromHistory_NeverReturnsNegativeContracts()
void Alaris.Test.Unit.TSUN027A.CalculateFromHistory_NeverReturnsNegativeContracts () inline
INVARIANT: Contracts ≥ 0 (never negative positions).
Definition at line 269 of file TSUN027A.cs.
References Alaris.Test.Unit.TSUN027A.CreateMixedTradeHistory(), and Alaris.Test.Unit.TSUN027A.CreateSignal().
CalculateFromHistory_WeakSignal_ReducesAllocation()
void Alaris.Test.Unit.TSUN027A.CalculateFromHistory_WeakSignal_ReducesAllocation () inline
Signal strength affects allocation.
Definition at line 287 of file TSUN027A.cs.
References Alaris.Test.Unit.TSUN027A.CreateMixedTradeHistory(), and Alaris.Test.Unit.TSUN027A.CreateSignal().
CreateMixedTradeHistory()
static List< Trade > Alaris.Test.Unit.TSUN027A.CreateMixedTradeHistory (int wins, int losses, double avgWin, double avgLoss) inline static private
Definition at line 53 of file TSUN027A.cs.
Referenced by Alaris.Test.Unit.TSUN027A.CalculateFromHistory_AvoidSignal_ReturnsZeroAllocation(), Alaris.Test.Unit.TSUN027A.CalculateFromHistory_CapsAtMaxAllocation(), Alaris.Test.Unit.TSUN027A.CalculateFromHistory_NeverReturnsNegativeContracts(), and Alaris.Test.Unit.TSUN027A.CalculateFromHistory_WeakSignal_ReducesAllocation().
CreateSignal()
static STCR004A Alaris.Test.Unit.TSUN027A.CreateSignal (STCR004AStrength strength = STCR004AStrength::Recommended) inline static private
Definition at line 84 of file TSUN027A.cs.
Referenced by Alaris.Test.Unit.TSUN027A.CalculateFromHistory_AvoidSignal_ReturnsZeroAllocation(), Alaris.Test.Unit.TSUN027A.CalculateFromHistory_CapsAtMaxAllocation(), Alaris.Test.Unit.TSUN027A.CalculateFromHistory_InsufficientHistory_ReturnsMinimumPosition(), Alaris.Test.Unit.TSUN027A.CalculateFromHistory_InvalidPortfolioValue_Throws(), Alaris.Test.Unit.TSUN027A.CalculateFromHistory_InvalidSpreadCost_Throws(), Alaris.Test.Unit.TSUN027A.CalculateFromHistory_NeverReturnsNegativeContracts(), and Alaris.Test.Unit.TSUN027A.CalculateFromHistory_WeakSignal_ReducesAllocation().
CreateWinningTradeHistory()
static List< Trade > Alaris.Test.Unit.TSUN027A.CreateWinningTradeHistory (int count, double avgWin) inline static private
Definition at line 36 of file TSUN027A.cs.
Referenced by Alaris.Test.Unit.TSUN027A.CalculateFromHistory_InsufficientHistory_ReturnsMinimumPosition(), Alaris.Test.Unit.TSUN027A.CalculateFromHistory_InvalidPortfolioValue_Throws(), and Alaris.Test.Unit.TSUN027A.CalculateFromHistory_InvalidSpreadCost_Throws().
NetOfCostKelly_CostsExceedEdge_ReturnsZero()
void Alaris.Test.Unit.TSUN027A.NetOfCostKelly_CostsExceedEdge_ReturnsZero () inline
When costs exceed edge, Kelly should be zero (no positive expectancy).
Definition at line 121 of file TSUN027A.cs.
References Alaris.Strategy.Risk.STRK001A.CalculateNetOfCostKelly().
NetOfCostKelly_InvalidWinProbability_ReturnsZero()
void Alaris.Test.Unit.TSUN027A.NetOfCostKelly_InvalidWinProbability_ReturnsZero (double winProb) inline
INVARIANT: Kelly = 0 when win probability = 0 or 1.
Definition at line 144 of file TSUN027A.cs.
References Alaris.Strategy.Risk.STRK001A.CalculateNetOfCostKelly().
NetOfCostKelly_IsLessOrEqualToStandardKelly()
void Alaris.Test.Unit.TSUN027A.NetOfCostKelly_IsLessOrEqualToStandardKelly (double winProb, double avgWin, double avgLoss, double roundTripCost) inline
INVARIANT: Net-of-cost Kelly ≤ Standard Kelly (costs reduce optimal bet).
Definition at line 103 of file TSUN027A.cs.
References Alaris.Strategy.Risk.STRK001A.CalculateNetOfCostKelly().
NetOfCostKelly_NegativeAvgLoss_Throws()
void Alaris.Test.Unit.TSUN027A.NetOfCostKelly_NegativeAvgLoss_Throws () inline
Definition at line 206 of file TSUN027A.cs.
References Alaris.Strategy.Risk.STRK001A.CalculateNetOfCostKelly().
NetOfCostKelly_NegativeAvgWin_Throws()
void Alaris.Test.Unit.TSUN027A.NetOfCostKelly_NegativeAvgWin_Throws () inline
Invalid inputs should throw appropriate exceptions.
Definition at line 198 of file TSUN027A.cs.
References Alaris.Strategy.Risk.STRK001A.CalculateNetOfCostKelly().
NetOfCostKelly_NegativeCost_Throws()
void Alaris.Test.Unit.TSUN027A.NetOfCostKelly_NegativeCost_Throws () inline
Definition at line 214 of file TSUN027A.cs.
References Alaris.Strategy.Risk.STRK001A.CalculateNetOfCostKelly().
NetOfCostKelly_NegativeExpectancy_ReturnsZeroOrPositive()
void Alaris.Test.Unit.TSUN027A.NetOfCostKelly_NegativeExpectancy_ReturnsZeroOrPositive (double winProb, double avgWin, double avgLoss) inline
INVARIANT: Kelly ≥ 0 (never bet negative amounts).
Definition at line 184 of file TSUN027A.cs.
References Alaris.Strategy.Risk.STRK001A.CalculateNetOfCostKelly().
NetOfCostKelly_ZeroCosts_MatchesStandardFormula()
void Alaris.Test.Unit.TSUN027A.NetOfCostKelly_ZeroCosts_MatchesStandardFormula () inline
Standard Kelly formula: f* = (p*b - q) / b where b = avgWin/avgLoss.
Definition at line 157 of file TSUN027A.cs.
References Alaris.Strategy.Risk.STRK001A.CalculateNetOfCostKelly().
STMG001A_CalculateTimeToExpiryApproximate_PastExpiry_ReturnsNonPositive()
void Alaris.Test.Unit.TSUN027A.STMG001A_CalculateTimeToExpiryApproximate_PastExpiry_ReturnsNonPositive () inline
Expired options (past expiry) should return zero or negative time.
Definition at line 623 of file TSUN027A.cs.
References Alaris.Strategy.Risk.STMG001A.CalculateTimeToExpiryApproximate().
STMG001A_CalculateTimeToExpiryApproximate_ReturnsReasonableValue()
void Alaris.Test.Unit.TSUN027A.STMG001A_CalculateTimeToExpiryApproximate_ReturnsReasonableValue () inline
Time-to-expiry calculation should be reasonable.
Definition at line 604 of file TSUN027A.cs.
References Alaris.Strategy.Risk.STMG001A.CalculateTimeToExpiryApproximate().
STMG001A_Constructor_InvalidThresholds_Throws()
void Alaris.Test.Unit.TSUN027A.STMG001A_Constructor_InvalidThresholds_Throws () inline
Invalid threshold configuration should throw.
Definition at line 589 of file TSUN027A.cs.
STMG001A_CustomThresholds_Respected()
void Alaris.Test.Unit.TSUN027A.STMG001A_CustomThresholds_Respected () inline
Custom thresholds should be respected.
Definition at line 570 of file TSUN027A.cs.
STMG001A_EvaluateEntry_AboveMinimum_Allows()
void Alaris.Test.Unit.TSUN027A.STMG001A_EvaluateEntry_AboveMinimum_Allows () inline
Entry should be allowed above minimum maturity threshold.
Definition at line 498 of file TSUN027A.cs.
STMG001A_EvaluateEntry_BelowMinimum_Rejects()
void Alaris.Test.Unit.TSUN027A.STMG001A_EvaluateEntry_BelowMinimum_Rejects () inline
Entry should be rejected below minimum maturity threshold.
Definition at line 516 of file TSUN027A.cs.
STMG001A_EvaluateExit_AboveThreshold_NoExit()
void Alaris.Test.Unit.TSUN027A.STMG001A_EvaluateExit_AboveThreshold_NoExit () inline
Exit should not be required above force-exit threshold.
Definition at line 534 of file TSUN027A.cs.
STMG001A_EvaluateExit_BelowThreshold_ImmediateExit()
void Alaris.Test.Unit.TSUN027A.STMG001A_EvaluateExit_BelowThreshold_ImmediateExit () inline
Exit should be immediate below force-exit threshold.
Definition at line 552 of file TSUN027A.cs.
STRK002A_RiskRewardRatio_ComputesCorrectly()
void Alaris.Test.Unit.TSUN027A.STRK002A_RiskRewardRatio_ComputesCorrectly () inline
RiskRewardRatio computed property should work correctly.
Definition at line 462 of file TSUN027A.cs.
References Alaris.Strategy.Risk.STRK002A.RiskRewardRatio.
STRK002A_RiskRewardRatio_ZeroMaxLoss_ReturnsZero()
void Alaris.Test.Unit.TSUN027A.STRK002A_RiskRewardRatio_ZeroMaxLoss_ReturnsZero () inline
RiskRewardRatio with zero max loss should be zero.
Definition at line 479 of file TSUN027A.cs.
References Alaris.Strategy.Risk.STRK002A.RiskRewardRatio.
STRK002A_Validate_CustomMaxAllocation_Respected()
void Alaris.Test.Unit.TSUN027A.STRK002A_Validate_CustomMaxAllocation_Respected () inline
Custom max allocation should be respected.
Definition at line 422 of file TSUN027A.cs.
STRK002A_Validate_ExceedsMaxAllocation_Throws()
void Alaris.Test.Unit.TSUN027A.STRK002A_Validate_ExceedsMaxAllocation_Throws () inline
Allocation exceeding maximum should fail validation.
Definition at line 402 of file TSUN027A.cs.
STRK002A_Validate_NegativeContracts_Throws()
void Alaris.Test.Unit.TSUN027A.STRK002A_Validate_NegativeContracts_Throws () inline
Negative contracts should fail validation.
Definition at line 387 of file TSUN027A.cs.
STRK002A_Validate_RiskExceedsAllocation_Throws()
void Alaris.Test.Unit.TSUN027A.STRK002A_Validate_RiskExceedsAllocation_Throws () inline
Risk exceeding allocation should fail validation.
Definition at line 441 of file TSUN027A.cs.
STRK002A_Validate_ValidPosition_DoesNotThrow()
void Alaris.Test.Unit.TSUN027A.STRK002A_Validate_ValidPosition_DoesNotThrow () inline
Valid position size should pass validation.
Definition at line 365 of file TSUN027A.cs.
Trade_HoldingPeriod_ComputesCorrectly()
void Alaris.Test.Unit.TSUN027A.Trade_HoldingPeriod_ComputesCorrectly () inline
HoldingPeriod computed property should be correct.
Definition at line 642 of file TSUN027A.cs.
References Alaris.Strategy.Risk.Trade.HoldingPeriod.
Trade_IsWinner_BasedOnProfitLoss()
void Alaris.Test.Unit.TSUN027A.Trade_IsWinner_BasedOnProfitLoss (double pl, bool expectedWinner) inline
IsWinner should be true for positive P&L.
Definition at line 664 of file TSUN027A.cs.
References Alaris.Strategy.Risk.Trade.IsWinner.
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN027A.cs