Alaris: Alaris.Infrastructure.Data.Provider.DTpr005A Interface Reference
Alaris.Infrastructure.Data.Provider.DTpr005A Interface Reference
Interface for risk-free rate providers.
Public Member Functions
Task< decimal > GetCurrentRateAsync (CancellationToken cancellationToken=default)
Gets the current risk-free rate (e.g., 3-month T-bill).
Task< IReadOnlyDictionary< DateTime, decimal > > GetHistoricalRatesAsync (DateTime startDate, DateTime endDate, CancellationToken cancellationToken=default)
Gets historical risk-free rates.
Detailed Description
Interface for risk-free rate providers.
Component ID: DTpr005A
Implementations provide current and historical risk-free rates (e.g., 3-month Treasury bill rates) for option pricing models.
Definition at line 22 of file DTpr005A.cs.
Member Function Documentation
GetCurrentRateAsync()
Task< decimal > Alaris.Infrastructure.Data.Provider.DTpr005A.GetCurrentRateAsync (CancellationToken cancellationToken = default)
Gets the current risk-free rate (e.g., 3-month T-bill).
Implemented in Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider.
Referenced by Alaris.Test.Unit.TSUN029A.DTpr005A_GetCurrentRateAsync_ReturnsValidRate(), and Alaris.Infrastructure.Data.Bridge.AlarisDataBridge.GetMarketDataSnapshotAsync().
GetHistoricalRatesAsync()
Task< IReadOnlyDictionary< DateTime, decimal > > Alaris.Infrastructure.Data.Provider.DTpr005A.GetHistoricalRatesAsync (DateTime startDate, DateTime endDate, CancellationToken cancellationToken = default)
Gets historical risk-free rates.
Implemented in Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider.
Referenced by Alaris.Test.Unit.TSUN029A.DTpr005A_GetHistoricalRatesAsync_ReturnsRates().
The documentation for this interface was generated from the following file:
src/Alaris.Infrastructure/Data/Provider/DTpr005A.cs