Alaris: Alaris.Test.Unit.DTqc003ATests Class Reference
Alaris.Test.Unit.DTqc003ATests Class Reference sealed
Unit tests for VolumeOpenInterestValidator (DTqc003A). Validates volume and liquidity rules.
Public Member Functions
DTqc003ATests ()
void Dispose ()
void ComponentId_ShouldBe_DTqc003A ()
void Validate_ValidLiquidOption_ShouldPass ()
void Validate_ZeroAverageVolume_ShouldFail ()
void Validate_LiquidOptionWithNoVolume_ShouldWarn ()
void Validate_HighVolumeToOiRatio_ShouldWarn ()
void Validate_VolumeSpike_ShouldWarn ()
Private Member Functions
void Dispose (bool disposing)
Static Private Member Functions
static MarketDataSnapshot CreateLiquidSnapshot (decimal averageVolume=5_000_000m, long underlyingVolume=5_000_000, long optionOpenInterest=1000, long optionVolume=500)
Private Attributes
readonly VolumeOpenInterestValidator _validator
readonly ILoggerFactory _loggerFactory
readonly ILogger< VolumeOpenInterestValidator > _logger
bool _disposed
Detailed Description
Unit tests for VolumeOpenInterestValidator (DTqc003A). Validates volume and liquidity rules.
Definition at line 333 of file TSUN006A.cs.
Constructor & Destructor Documentation
DTqc003ATests()
Alaris.Test.Unit.DTqc003ATests.DTqc003ATests () inline
Definition at line 340 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc003ATests._logger, Alaris.Test.Unit.DTqc003ATests._loggerFactory, and Alaris.Test.Unit.DTqc003ATests._validator.
Member Function Documentation
ComponentId_ShouldBe_DTqc003A()
void Alaris.Test.Unit.DTqc003ATests.ComponentId_ShouldBe_DTqc003A () inline
Definition at line 369 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc003ATests._validator, and Alaris.Infrastructure.Data.Quality.VolumeOpenInterestValidator.ComponentId.
CreateLiquidSnapshot()
static MarketDataSnapshot Alaris.Test.Unit.DTqc003ATests.CreateLiquidSnapshot (decimal averageVolume = 5_000_000m, long underlyingVolume = 5_000_000, long optionOpenInterest = 1000, long optionVolume = 500) inline static private
Definition at line 445 of file TSUN006A.cs.
Referenced by Alaris.Test.Unit.DTqc003ATests.Validate_HighVolumeToOiRatio_ShouldWarn(), Alaris.Test.Unit.DTqc003ATests.Validate_LiquidOptionWithNoVolume_ShouldWarn(), Alaris.Test.Unit.DTqc003ATests.Validate_ValidLiquidOption_ShouldPass(), Alaris.Test.Unit.DTqc003ATests.Validate_VolumeSpike_ShouldWarn(), and Alaris.Test.Unit.DTqc003ATests.Validate_ZeroAverageVolume_ShouldFail().
Dispose() [1/2]
void Alaris.Test.Unit.DTqc003ATests.Dispose () inline
Definition at line 347 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc003ATests.Dispose().
Referenced by Alaris.Test.Unit.DTqc003ATests.Dispose().
Dispose() [2/2]
void Alaris.Test.Unit.DTqc003ATests.Dispose (bool disposing) inline private
Definition at line 353 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc003ATests._disposed, and Alaris.Test.Unit.DTqc003ATests._loggerFactory.
Validate_HighVolumeToOiRatio_ShouldWarn()
void Alaris.Test.Unit.DTqc003ATests.Validate_HighVolumeToOiRatio_ShouldWarn () inline
Definition at line 416 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc003ATests._validator, Alaris.Test.Unit.DTqc003ATests.CreateLiquidSnapshot(), Alaris.Infrastructure.Data.Model.DataQualityResult.Status, and Alaris.Infrastructure.Data.Quality.VolumeOpenInterestValidator.Validate().
Validate_LiquidOptionWithNoVolume_ShouldWarn()
void Alaris.Test.Unit.DTqc003ATests.Validate_LiquidOptionWithNoVolume_ShouldWarn () inline
Definition at line 402 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc003ATests._validator, Alaris.Test.Unit.DTqc003ATests.CreateLiquidSnapshot(), Alaris.Infrastructure.Data.Model.DataQualityResult.Status, and Alaris.Infrastructure.Data.Quality.VolumeOpenInterestValidator.Validate().
Validate_ValidLiquidOption_ShouldPass()
void Alaris.Test.Unit.DTqc003ATests.Validate_ValidLiquidOption_ShouldPass () inline
Definition at line 375 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc003ATests._validator, Alaris.Test.Unit.DTqc003ATests.CreateLiquidSnapshot(), Alaris.Infrastructure.Data.Model.DataQualityResult.Status, and Alaris.Infrastructure.Data.Quality.VolumeOpenInterestValidator.Validate().
Validate_VolumeSpike_ShouldWarn()
void Alaris.Test.Unit.DTqc003ATests.Validate_VolumeSpike_ShouldWarn () inline
Definition at line 430 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc003ATests._validator, Alaris.Test.Unit.DTqc003ATests.CreateLiquidSnapshot(), Alaris.Infrastructure.Data.Model.DataQualityResult.Status, and Alaris.Infrastructure.Data.Quality.VolumeOpenInterestValidator.Validate().
Validate_ZeroAverageVolume_ShouldFail()
void Alaris.Test.Unit.DTqc003ATests.Validate_ZeroAverageVolume_ShouldFail () inline
Definition at line 388 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc003ATests._validator, Alaris.Test.Unit.DTqc003ATests.CreateLiquidSnapshot(), Alaris.Infrastructure.Data.Model.DataQualityResult.Status, and Alaris.Infrastructure.Data.Quality.VolumeOpenInterestValidator.Validate().
Member Data Documentation
_disposed
bool Alaris.Test.Unit.DTqc003ATests._disposed private
Definition at line 338 of file TSUN006A.cs.
Referenced by Alaris.Test.Unit.DTqc003ATests.Dispose().
_logger
readonly ILogger<VolumeOpenInterestValidator> Alaris.Test.Unit.DTqc003ATests._logger private
Definition at line 337 of file TSUN006A.cs.
Referenced by Alaris.Test.Unit.DTqc003ATests.DTqc003ATests().
_loggerFactory
readonly ILoggerFactory Alaris.Test.Unit.DTqc003ATests._loggerFactory private
Definition at line 336 of file TSUN006A.cs.
Referenced by Alaris.Test.Unit.DTqc003ATests.DTqc003ATests(), and Alaris.Test.Unit.DTqc003ATests.Dispose().
_validator
readonly VolumeOpenInterestValidator Alaris.Test.Unit.DTqc003ATests._validator private
Definition at line 335 of file TSUN006A.cs.
Referenced by Alaris.Test.Unit.DTqc003ATests.DTqc003ATests(), Alaris.Test.Unit.DTqc003ATests.ComponentId_ShouldBe_DTqc003A(), Alaris.Test.Unit.DTqc003ATests.Validate_HighVolumeToOiRatio_ShouldWarn(), Alaris.Test.Unit.DTqc003ATests.Validate_LiquidOptionWithNoVolume_ShouldWarn(), Alaris.Test.Unit.DTqc003ATests.Validate_ValidLiquidOption_ShouldPass(), Alaris.Test.Unit.DTqc003ATests.Validate_VolumeSpike_ShouldWarn(), and Alaris.Test.Unit.DTqc003ATests.Validate_ZeroAverageVolume_ShouldFail().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN006A.cs