Alaris: Alaris.Core.Vectorized.CRVT001A Class Reference
Alaris.Core.Vectorized.CRVT001A Class Reference
SIMD-vectorized Greeks. Processes batches of Vector<double>.Width with scalar fallback.
Static Public Member Functions
static void ComputePricesBatch (ReadOnlySpan< double > spots, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, ReadOnlySpan< bool > isCalls, Span< double > results)
Computes Black-Scholes prices for multiple options in vectorized batches. Uses AVX2 intrinsics when available for maximum throughput.
static void ComputeDeltasBatch (ReadOnlySpan< double > spots, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, ReadOnlySpan< bool > isCalls, Span< double > results)
Computes Black-Scholes deltas for multiple options in vectorized batches. Uses AVX2 intrinsics when available.
static void ComputeVegasBatch (ReadOnlySpan< double > spots, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, Span< double > results)
Computes Black-Scholes vegas for multiple options in vectorized batches. Uses AVX2 intrinsics when available.
static void ComputeGammasBatch (ReadOnlySpan< double > spots, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, Span< double > results)
Computes Black-Scholes gammas for multiple options in vectorized batches. Uses AVX2 intrinsics when available.
Static Public Attributes
static readonly int VectorWidth = Vector<double>.Count
Vector width for current hardware.
static readonly bool IsHardwareAccelerated = Vector.IsHardwareAccelerated
Indicates if SIMD is hardware-accelerated on this platform.
Static Private Member Functions
static void ComputePricesVector256 (ReadOnlySpan< double > spots, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, ReadOnlySpan< bool > isCalls, Span< double > results)
AVX2-accelerated price computation for 4 options.
static void ComputeDeltasVector256 (ReadOnlySpan< double > spots, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, ReadOnlySpan< bool > isCalls, Span< double > results)
AVX2-accelerated delta computation for 4 options.
static void ComputeVegasVector256 (ReadOnlySpan< double > spots, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, Span< double > results)
AVX2-accelerated vega computation for 4 options.
static void ComputeGammasVector256 (ReadOnlySpan< double > spots, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, Span< double > results)
AVX2-accelerated gamma computation for 4 options.
static void ComputeDeltasVector (ReadOnlySpan< double > spots, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, ReadOnlySpan< bool > isCalls, Span< double > results)
static void ComputeVegasVector (ReadOnlySpan< double > spots, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, Span< double > results)
static Vector< double > VectorLog (Vector< double > v)
Vectorized natural logarithm (element-wise). Uses AVX2 intrinsics when available, otherwise falls back to scalar.
static Vector< double > VectorExp (Vector< double > v)
Vectorized exponential (element-wise). Uses AVX2 intrinsics when available, otherwise falls back to scalar.
Detailed Description
SIMD-vectorized Greeks. Processes batches of Vector<double>.Width with scalar fallback.
Definition at line 12 of file CRVT001A.cs.
Member Function Documentation
ComputeDeltasBatch()
static void Alaris.Core.Vectorized.CRVT001A.ComputeDeltasBatch (ReadOnlySpan< double > spots, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, ReadOnlySpan< bool > isCalls, Span< double > results) inline static
Computes Black-Scholes deltas for multiple options in vectorized batches. Uses AVX2 intrinsics when available.
Definition at line 172 of file CRVT001A.cs.
References Alaris.Core.Vectorized.CRVT001A.ComputeDeltasVector256(), and Alaris.Core.Vectorized.CRVT002A.IsAvx2Supported.
Referenced by Alaris.Strategy.Core.Numerical.STPR010A.ComputeChainDeltas(), and Alaris.Strategy.Core.Numerical.STPR010A.ComputeChainGreeks().
ComputeDeltasVector()
static void Alaris.Core.Vectorized.CRVT001A.ComputeDeltasVector (ReadOnlySpan< double > spots, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, ReadOnlySpan< bool > isCalls, Span< double > results) inline static private
Definition at line 506 of file CRVT001A.cs.
References Alaris.Core.Vectorized.CRVT001A.VectorExp(), Alaris.Core.Vectorized.CRVT001A.VectorLog(), and Alaris.Core.Vectorized.CRVT001A.VectorWidth.
ComputeDeltasVector256()
static void Alaris.Core.Vectorized.CRVT001A.ComputeDeltasVector256 (ReadOnlySpan< double > spots, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, ReadOnlySpan< bool > isCalls, Span< double > results) inline static private
AVX2-accelerated delta computation for 4 options.
Definition at line 226 of file CRVT001A.cs.
References Alaris.Core.Vectorized.CRVT002A.VectorExp256(), Alaris.Core.Vectorized.CRVT002A.VectorLog256(), and Alaris.Core.Vectorized.CRVT002A.VectorNormalCDF256().
Referenced by Alaris.Core.Vectorized.CRVT001A.ComputeDeltasBatch().
ComputeGammasBatch()
static void Alaris.Core.Vectorized.CRVT001A.ComputeGammasBatch (ReadOnlySpan< double > spots, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, Span< double > results) inline static
Computes Black-Scholes gammas for multiple options in vectorized batches. Uses AVX2 intrinsics when available.
Definition at line 399 of file CRVT001A.cs.
References Alaris.Core.Vectorized.CRVT001A.ComputeGammasVector256(), and Alaris.Core.Vectorized.CRVT002A.IsAvx2Supported.
Referenced by Alaris.Strategy.Core.Numerical.STPR010A.ComputeChainGreeks().
ComputeGammasVector256()
static void Alaris.Core.Vectorized.CRVT001A.ComputeGammasVector256 (ReadOnlySpan< double > spots, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, Span< double > results) inline static private
AVX2-accelerated gamma computation for 4 options.
Definition at line 451 of file CRVT001A.cs.
References Alaris.Core.Vectorized.CRVT002A.VectorExp256(), Alaris.Core.Vectorized.CRVT002A.VectorLog256(), and Alaris.Core.Vectorized.CRVT002A.VectorNormalPDF256().
Referenced by Alaris.Core.Vectorized.CRVT001A.ComputeGammasBatch().
ComputePricesBatch()
static void Alaris.Core.Vectorized.CRVT001A.ComputePricesBatch (ReadOnlySpan< double > spots, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, ReadOnlySpan< bool > isCalls, Span< double > results) inline static
Computes Black-Scholes prices for multiple options in vectorized batches. Uses AVX2 intrinsics when available for maximum throughput.
Parameters
spots Array of spot prices.
strikes Array of strike prices.
taus Array of times to expiry (years).
sigmas Array of volatilities.
r Risk-free rate (scalar for all).
q Dividend yield (scalar for all).
isCalls Array of call/put flags.
results Output array for prices.
Definition at line 37 of file CRVT001A.cs.
References Alaris.Core.Vectorized.CRVT001A.ComputePricesVector256(), and Alaris.Core.Vectorized.CRVT002A.IsAvx2Supported.
Referenced by Alaris.Strategy.Core.Numerical.STPR010A.ComputeChainGreeks(), and Alaris.Strategy.Core.Numerical.STPR010A.ComputeChainPrices().
ComputePricesVector256()
static void Alaris.Core.Vectorized.CRVT001A.ComputePricesVector256 (ReadOnlySpan< double > spots, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, ReadOnlySpan< bool > isCalls, Span< double > results) inline static private
AVX2-accelerated price computation for 4 options.
Definition at line 91 of file CRVT001A.cs.
References Alaris.Core.Vectorized.CRVT002A.VectorExp256(), Alaris.Core.Vectorized.CRVT002A.VectorLog256(), and Alaris.Core.Vectorized.CRVT002A.VectorNormalCDF256().
Referenced by Alaris.Core.Vectorized.CRVT001A.ComputePricesBatch().
ComputeVegasBatch()
static void Alaris.Core.Vectorized.CRVT001A.ComputeVegasBatch (ReadOnlySpan< double > spots, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, Span< double > results) inline static
Computes Black-Scholes vegas for multiple options in vectorized batches. Uses AVX2 intrinsics when available.
Definition at line 289 of file CRVT001A.cs.
References Alaris.Core.Vectorized.CRVT001A.ComputeVegasVector256(), and Alaris.Core.Vectorized.CRVT002A.IsAvx2Supported.
Referenced by Alaris.Strategy.Core.Numerical.STPR010A.ComputeChainGreeks().
ComputeVegasVector()
static void Alaris.Core.Vectorized.CRVT001A.ComputeVegasVector (ReadOnlySpan< double > spots, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, Span< double > results) inline static private
Definition at line 546 of file CRVT001A.cs.
References Alaris.Core.Vectorized.CRVT001A.VectorExp(), Alaris.Core.Vectorized.CRVT001A.VectorLog(), and Alaris.Core.Vectorized.CRVT001A.VectorWidth.
ComputeVegasVector256()
static void Alaris.Core.Vectorized.CRVT001A.ComputeVegasVector256 (ReadOnlySpan< double > spots, ReadOnlySpan< double > strikes, ReadOnlySpan< double > taus, ReadOnlySpan< double > sigmas, double r, double q, Span< double > results) inline static private
AVX2-accelerated vega computation for 4 options.
Definition at line 341 of file CRVT001A.cs.
References Alaris.Core.Vectorized.CRVT002A.VectorExp256(), Alaris.Core.Vectorized.CRVT002A.VectorLog256(), and Alaris.Core.Vectorized.CRVT002A.VectorNormalPDF256().
Referenced by Alaris.Core.Vectorized.CRVT001A.ComputeVegasBatch().
VectorExp()
static Vector< double > Alaris.Core.Vectorized.CRVT001A.VectorExp (Vector< double > v) inline static private
Vectorized exponential (element-wise). Uses AVX2 intrinsics when available, otherwise falls back to scalar.
Definition at line 616 of file CRVT001A.cs.
References Alaris.Core.Vectorized.CRVT002A.IsAvx2Supported, Alaris.Core.Vectorized.CRVT002A.VectorExp256(), and Alaris.Core.Vectorized.CRVT001A.VectorWidth.
Referenced by Alaris.Core.Vectorized.CRVT001A.ComputeDeltasVector(), and Alaris.Core.Vectorized.CRVT001A.ComputeVegasVector().
VectorLog()
static Vector< double > Alaris.Core.Vectorized.CRVT001A.VectorLog (Vector< double > v) inline static private
Vectorized natural logarithm (element-wise). Uses AVX2 intrinsics when available, otherwise falls back to scalar.
Definition at line 583 of file CRVT001A.cs.
References Alaris.Core.Vectorized.CRVT002A.IsAvx2Supported, Alaris.Core.Vectorized.CRVT002A.VectorLog256(), and Alaris.Core.Vectorized.CRVT001A.VectorWidth.
Referenced by Alaris.Core.Vectorized.CRVT001A.ComputeDeltasVector(), and Alaris.Core.Vectorized.CRVT001A.ComputeVegasVector().
Member Data Documentation
IsHardwareAccelerated
readonly bool Alaris.Core.Vectorized.CRVT001A.IsHardwareAccelerated = Vector.IsHardwareAccelerated static
Indicates if SIMD is hardware-accelerated on this platform.
Definition at line 22 of file CRVT001A.cs.
VectorWidth
readonly int Alaris.Core.Vectorized.CRVT001A.VectorWidth = Vector<double>.Count static
Vector width for current hardware.
Definition at line 17 of file CRVT001A.cs.
Referenced by Alaris.Core.Vectorized.CRVT001A.ComputeDeltasVector(), Alaris.Core.Vectorized.CRVT001A.ComputeVegasVector(), Alaris.Core.Vectorized.CRVT001A.VectorExp(), and Alaris.Core.Vectorized.CRVT001A.VectorLog().
The documentation for this class was generated from the following file:
src/Alaris.Core/Vectorized/CRVT001A.cs