Alaris: Alaris.Strategy.Core.Numerical.STPR004A Class Reference
Alaris.Strategy.Core.Numerical.STPR004A Class Reference sealed
Levenberg-Marquardt optimizer implementation using MathNet.Numerics.
Classes
class LeastSquaresObjective
Public Member Functions
OptimizationResult Minimize (Func< double[], double[]> residuals, double[] initialGuess, double[]? lowerBounds=null, double[]? upperBounds=null)
Minimizes the objective function (sum of squared residuals) using MathNet.Numerics LevenbergMarquardtMinimizer.
Properties
int MaxIterations = DefaultMaxIterations [get]
Maximum number of iterations.
double Tolerance = DefaultTolerance [get]
Convergence tolerance.
double ParameterTolerance = DefaultTolerance [get]
Parameter convergence tolerance.
double ObjectiveTolerance = DefaultTolerance [get]
Objective function convergence tolerance.
Private Member Functions
OptimizationResult CreateResult (NonlinearMinimizationResult result, Func< double[], double[]> residuals)
Static Private Member Functions
static OptimizationStatus MapStatus (MathNet.Numerics.Optimization.ExitCondition reason)
Static Private Attributes
const int DefaultMaxIterations = 1000
const double DefaultTolerance = 1e-8
Detailed Description
Levenberg-Marquardt optimizer implementation using MathNet.Numerics.
Definition at line 14 of file STPR004A.cs.
Member Function Documentation
CreateResult()
OptimizationResult Alaris.Strategy.Core.Numerical.STPR004A.CreateResult (NonlinearMinimizationResult result, Func< double[], double[]> residuals) inline private
Definition at line 67 of file STPR004A.cs.
References Alaris.Strategy.Core.Numerical.OptimizationResult.Iterations, and Alaris.Strategy.Core.Numerical.STPR004A.MapStatus().
Referenced by Alaris.Strategy.Core.Numerical.STPR004A.Minimize().
MapStatus()
static OptimizationStatus Alaris.Strategy.Core.Numerical.STPR004A.MapStatus (MathNet::Numerics::Optimization::ExitCondition reason) inline static private
Definition at line 85 of file STPR004A.cs.
Referenced by Alaris.Strategy.Core.Numerical.STPR004A.CreateResult().
Minimize()
OptimizationResult Alaris.Strategy.Core.Numerical.STPR004A.Minimize (Func< double[], double[]> residuals, double[] initialGuess, double?[] lowerBounds = null, double?[] upperBounds = null) inline
Minimizes the objective function (sum of squared residuals) using MathNet.Numerics LevenbergMarquardtMinimizer.
Definition at line 42 of file STPR004A.cs.
References Alaris.Strategy.Core.Numerical.STPR004A.CreateResult(), Alaris.Strategy.Core.Numerical.STPR004A.MaxIterations, Alaris.Strategy.Core.Numerical.STPR004A.ObjectiveTolerance, Alaris.Strategy.Core.Numerical.STPR004A.ParameterTolerance, and Alaris.Strategy.Core.Numerical.STPR004A.Tolerance.
Member Data Documentation
DefaultMaxIterations
const int Alaris.Strategy.Core.Numerical.STPR004A.DefaultMaxIterations = 1000 static private
Definition at line 16 of file STPR004A.cs.
DefaultTolerance
const double Alaris.Strategy.Core.Numerical.STPR004A.DefaultTolerance = 1e-8 static private
Definition at line 17 of file STPR004A.cs.
Property Documentation
MaxIterations
int Alaris.Strategy.Core.Numerical.STPR004A.MaxIterations = DefaultMaxIterations get
Maximum number of iterations.
Definition at line 22 of file STPR004A.cs.
Referenced by Alaris.Strategy.Core.Numerical.STPR004A.Minimize().
ObjectiveTolerance
double Alaris.Strategy.Core.Numerical.STPR004A.ObjectiveTolerance = DefaultTolerance get
Objective function convergence tolerance.
Definition at line 37 of file STPR004A.cs.
Referenced by Alaris.Strategy.Core.Numerical.STPR004A.Minimize().
ParameterTolerance
double Alaris.Strategy.Core.Numerical.STPR004A.ParameterTolerance = DefaultTolerance get
Parameter convergence tolerance.
Definition at line 32 of file STPR004A.cs.
Referenced by Alaris.Strategy.Core.Numerical.STPR004A.Minimize().
Tolerance
double Alaris.Strategy.Core.Numerical.STPR004A.Tolerance = DefaultTolerance get
Convergence tolerance.
Definition at line 27 of file STPR004A.cs.
Referenced by Alaris.Strategy.Core.Numerical.STPR004A.Minimize().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Core/Numerical/STPR004A.cs