Alaris: Alaris.Core.Time.IDayCounter Interface Reference
Alaris.Core.Time.IDayCounter Interface Reference
Interface for day count conventions.
Public Member Functions
double YearFraction (CRTM005A start, CRTM005A end)
Calculates the year fraction between two dates.
int DayCount (CRTM005A start, CRTM005A end)
Calculates the number of days between two dates per convention.
Properties
string Name [get]
Gets the name of the day count convention.
Detailed Description
Interface for day count conventions.
Definition at line 24 of file CRTM007A.cs.
Member Function Documentation
DayCount()
int Alaris.Core.Time.IDayCounter.DayCount (CRTM005A start, CRTM005A end)
Calculates the number of days between two dates per convention.
Parameters
start Start date.
end End date.
Returns
Number of days per the day count convention.
Implemented in Alaris.Core.Time.CRTM007AActual365Fixed, Alaris.Core.Time.CRTM007AActual360, and Alaris.Core.Time.CRTM007AThirty360.
Referenced by Alaris.Test.Unit.Core.Time.CRTM007ATests.Actual365Fixed_DayCount_ReturnsActualDays(), and Alaris.Test.Unit.Core.Time.CRTM007ATests.Thirty360_Feb28ToMar1_HandlesCorrectly().
YearFraction()
double Alaris.Core.Time.IDayCounter.YearFraction (CRTM005A start, CRTM005A end)
Calculates the year fraction between two dates.
Parameters
start Start date.
end End date.
Returns
Year fraction.
Implemented in Alaris.Core.Time.CRTM007AActual365Fixed, Alaris.Core.Time.CRTM007AActual360, and Alaris.Core.Time.CRTM007AThirty360.
Referenced by Alaris.Test.Unit.Core.Time.CRTM007ATests.Actual360_30Days_ReturnsCorrect(), Alaris.Test.Unit.Core.Time.CRTM007ATests.Actual360_OneYear_ReturnsMoreThanOne(), Alaris.Test.Unit.Core.Time.CRTM007ATests.Actual365Fixed_HalfYear_ReturnsHalf(), Alaris.Test.Unit.Core.Time.CRTM007ATests.Actual365Fixed_OneYear_ReturnsOne(), Alaris.Test.Unit.Core.Time.CRTM007ATests.Actual365Fixed_SameDate_ReturnsZero(), Alaris.Core.TermStructure.CRTS002AFlatVol.BlackVol(), Alaris.Strategy.Bridge.STBR001A.CalculateMaxProfit(), Alaris.Core.TermStructure.CRTS001AFlatForward.DiscountFactor(), Alaris.Test.Unit.Core.Time.CRTM007ATests.Thirty360_OneMonth_ReturnsThirtyDays(), Alaris.Test.Unit.Core.Time.CRTM007ATests.Thirty360_OneYear_ReturnsOne(), Alaris.Strategy.Bridge.STPR001AParameters.TimeToBackExpiry(), Alaris.Strategy.Model.STDT003A.TimeToExpiry(), and Alaris.Strategy.Bridge.STPR001AParameters.TimeToFrontExpiry().
Property Documentation
Name
string Alaris.Core.Time.IDayCounter.Name get
Gets the name of the day count convention.
Implemented in Alaris.Core.Time.CRTM007AActual365Fixed, Alaris.Core.Time.CRTM007AActual360, and Alaris.Core.Time.CRTM007AThirty360.
Definition at line 29 of file CRTM007A.cs.
The documentation for this interface was generated from the following file:
src/Alaris.Core/Time/CRTM007A.cs