Alaris: Alaris.Strategy.Risk.STRK003A Class Reference
Alaris.Strategy.Risk.STRK003A Class Reference sealed
Implements reserve-adjusted Kelly position sizing for concurrent positions.
Public Member Functions
STRK003A (STRK001A baseKelly, ILogger< STRK003A >? logger=null)
Initialises a new instance of the concurrent position reserve manager.
double CalculateExpectedConcurrent (double arrivalRate, double averageHoldingPeriod)
Calculates expected concurrent positions using Little's Law.
double CalculateExpectedConcurrentFromHistory (IReadOnlyList< Trade > historicalTrades, int analysisWindowDays=252)
Calculates expected concurrent positions from historical trade data.
STRK002A CalculateWithReserve (double portfolioValue, IReadOnlyList< Trade > historicalTrades, double spreadCost, STCR004A signal, int currentOpenPositions, double expectedConcurrent, double reserveBuffer=DefaultReserveBuffer)
Calculates position size with concurrent position reserve adjustment.
Private Member Functions
void SafeLog (Action logAction)
Safely executes logging operation with fault isolation (Rule 15). Prevents logging failures from crashing critical paths.
Static Private Member Functions
static STRK002A GetZeroPosition ()
Returns a zero-size position (filtered by utilisation threshold).
Private Attributes
readonly STRK001A _baseKelly
readonly? ILogger< STRK003A > _logger
Static Private Attributes
const double DefaultReserveBuffer = 1.30
const double HighUtilisationThreshold = 0.75
const double MaxUtilisationThreshold = 0.90
static readonly Action< ILogger, double, double, double, Exception?> LogReserveCalculation
static readonly Action< ILogger, double, string, Exception?> LogUtilisationFiltered
static readonly Action< ILogger, string, double, double, Exception?> LogAdjustedAllocation
Detailed Description
Implements reserve-adjusted Kelly position sizing for concurrent positions.
Definition at line 12 of file STRK003A.cs.
Constructor & Destructor Documentation
STRK003A()
Alaris.Strategy.Risk.STRK003A.STRK003A (STRK001A baseKelly, ILogger< STRK003A >? logger = null) inline
Initialises a new instance of the concurrent position reserve manager.
Parameters
baseKelly Base Kelly calculator for individual position sizing.
logger Optional logger instance.
Exceptions
ArgumentNullException Thrown when baseKelly is null.
Definition at line 51 of file STRK003A.cs.
References Alaris.Strategy.Risk.STRK003A._baseKelly, and Alaris.Strategy.Risk.STRK003A._logger.
Member Function Documentation
CalculateExpectedConcurrent()
double Alaris.Strategy.Risk.STRK003A.CalculateExpectedConcurrent (double arrivalRate, double averageHoldingPeriod) inline
Calculates expected concurrent positions using Little's Law.
Parameters
arrivalRate Average number of signals per trading day.
averageHoldingPeriod Average holding period in trading days.
Returns
Expected number of concurrent positions.
Exceptions
ArgumentOutOfRangeException Thrown when arrivalRate or averageHoldingPeriod is non-positive.
Definition at line 67 of file STRK003A.cs.
References Alaris.Strategy.Risk.STRK003A._logger, Alaris.Strategy.Risk.STRK003A.LogReserveCalculation, and Alaris.Strategy.Risk.STRK003A.SafeLog().
Referenced by Alaris.Test.Unit.STRK003ATests.CalculateExpectedConcurrent_WithInvalidInputs_ThrowsArgumentOutOfRangeException(), Alaris.Test.Unit.STRK003ATests.CalculateExpectedConcurrent_WithValidInputs_ReturnsLittlesLawResult(), and Alaris.Strategy.Risk.STRK003A.CalculateExpectedConcurrentFromHistory().
CalculateExpectedConcurrentFromHistory()
double Alaris.Strategy.Risk.STRK003A.CalculateExpectedConcurrentFromHistory (IReadOnlyList< Trade > historicalTrades, int analysisWindowDays = 252) inline
Calculates expected concurrent positions from historical trade data.
Parameters
historicalTrades Historical trades to analyse.
analysisWindowDays Number of trading days to analyse.
Returns
Expected number of concurrent positions.
Exceptions
ArgumentNullException Thrown when historicalTrades is null.
ArgumentException Thrown when insufficient trade history.
Definition at line 96 of file STRK003A.cs.
References Alaris.Strategy.Risk.STRK003A.CalculateExpectedConcurrent().
Referenced by Alaris.Test.Unit.STRK003ATests.CalculateExpectedConcurrentFromHistory_WithInsufficientTrades_ThrowsArgumentException(), and Alaris.Test.Unit.STRK003ATests.CalculateExpectedConcurrentFromHistory_WithValidTrades_ReturnsExpectedValue().
CalculateWithReserve()
STRK002A Alaris.Strategy.Risk.STRK003A.CalculateWithReserve (double portfolioValue, IReadOnlyList< Trade > historicalTrades, double spreadCost, STCR004A signal, int currentOpenPositions, double expectedConcurrent, double reserveBuffer = DefaultReserveBuffer) inline
Calculates position size with concurrent position reserve adjustment.
Parameters
portfolioValue Total portfolio value.
historicalTrades Historical trades for Kelly calculation.
spreadCost Cost of the calendar spread.
signal Trading signal.
currentOpenPositions Number of currently open positions.
expectedConcurrent Expected concurrent positions (from Little's Law).
reserveBuffer Buffer multiplier for clustering variance (default: 1.3).
Returns
Reserve-adjusted position size.
Exceptions
ArgumentNullException Thrown when required parameters are null.
ArgumentOutOfRangeException Thrown when numeric parameters are invalid.
Definition at line 133 of file STRK003A.cs.
References Alaris.Strategy.Risk.STRK003A._baseKelly, Alaris.Strategy.Risk.STRK003A._logger, Alaris.Strategy.Risk.STRK002A.AllocationPercent, Alaris.Strategy.Risk.STRK001A.CalculateFromHistory(), Alaris.Strategy.Risk.STRK002A.Contracts, Alaris.Strategy.Risk.STRK002A.ExpectedProfitPerContract, Alaris.Strategy.Risk.STRK003A.GetZeroPosition(), Alaris.Strategy.Risk.STRK003A.HighUtilisationThreshold, Alaris.Strategy.Risk.STRK003A.LogAdjustedAllocation, Alaris.Strategy.Risk.STRK003A.LogUtilisationFiltered, Alaris.Strategy.Risk.STRK002A.MaxLossPerContract, Alaris.Strategy.Risk.STRK003A.MaxUtilisationThreshold, Alaris.Strategy.Risk.STRK003A.SafeLog(), Alaris.Strategy.Core.STCR004A.Strength, and Alaris.Strategy.Core.STCR004A.Symbol.
Referenced by Alaris.Test.Unit.STRK003ATests.CalculateWithReserve_AppliesReserveBufferToAllocation(), Alaris.Test.Unit.STRK003ATests.CalculateWithReserve_WhenUtilisationHigh_RejectsConsiderSignals(), Alaris.Test.Unit.STRK003ATests.CalculateWithReserve_WhenUtilisationLow_AcceptsConsiderSignals(), and Alaris.Test.Unit.STRK003ATests.CalculateWithReserve_WithInvalidPortfolio_ThrowsArgumentOutOfRangeException().
GetZeroPosition()
static STRK002A Alaris.Strategy.Risk.STRK003A.GetZeroPosition () inline static private
Returns a zero-size position (filtered by utilisation threshold).
Definition at line 230 of file STRK003A.cs.
Referenced by Alaris.Strategy.Risk.STRK003A.CalculateWithReserve().
SafeLog()
void Alaris.Strategy.Risk.STRK003A.SafeLog (Action logAction) inline private
Safely executes logging operation with fault isolation (Rule 15). Prevents logging failures from crashing critical paths.
Definition at line 248 of file STRK003A.cs.
References Alaris.Strategy.Risk.STRK003A._logger.
Referenced by Alaris.Strategy.Risk.STRK003A.CalculateExpectedConcurrent(), and Alaris.Strategy.Risk.STRK003A.CalculateWithReserve().
Member Data Documentation
_baseKelly
readonly STRK001A Alaris.Strategy.Risk.STRK003A._baseKelly private
Definition at line 14 of file STRK003A.cs.
Referenced by Alaris.Strategy.Risk.STRK003A.STRK003A(), and Alaris.Strategy.Risk.STRK003A.CalculateWithReserve().
_logger
readonly? ILogger<STRK003A> Alaris.Strategy.Risk.STRK003A._logger private
Definition at line 15 of file STRK003A.cs.
Referenced by Alaris.Strategy.Risk.STRK003A.STRK003A(), Alaris.Strategy.Risk.STRK003A.CalculateExpectedConcurrent(), Alaris.Strategy.Risk.STRK003A.CalculateWithReserve(), and Alaris.Strategy.Risk.STRK003A.SafeLog().
DefaultReserveBuffer
const double Alaris.Strategy.Risk.STRK003A.DefaultReserveBuffer = 1.30 static private
Definition at line 18 of file STRK003A.cs.
HighUtilisationThreshold
const double Alaris.Strategy.Risk.STRK003A.HighUtilisationThreshold = 0.75 static private
Definition at line 21 of file STRK003A.cs.
Referenced by Alaris.Strategy.Risk.STRK003A.CalculateWithReserve().
LogAdjustedAllocation
readonly Action<ILogger, string, double, double, Exception?> Alaris.Strategy.Risk.STRK003A.LogAdjustedAllocation static private
Initial value:
=
        LoggerMessage.Define<string, double, double>(
            LogLevel.Information,
            new EventId(3, nameof(LogAdjustedAllocation)),
            "Reserve-adjusted allocation for {Symbol}: base={BaseAlloc:P2}, adjusted={AdjustedAlloc:P2}")
Definition at line 39 of file STRK003A.cs.
Referenced by Alaris.Strategy.Risk.STRK003A.CalculateWithReserve().
LogReserveCalculation
readonly Action<ILogger, double, double, double, Exception?> Alaris.Strategy.Risk.STRK003A.LogReserveCalculation static private
Initial value:
=
        LoggerMessage.Define<double, double, double>(
            LogLevel.Information,
            new EventId(1, nameof(LogReserveCalculation)),
            "Reserve calculation: arrivalRate={ArrivalRate:F3}/day, holdingPeriod={HoldingPeriod:F1}d, expectedConcurrent={ExpectedConcurrent:F1}")
Definition at line 27 of file STRK003A.cs.
Referenced by Alaris.Strategy.Risk.STRK003A.CalculateExpectedConcurrent().
LogUtilisationFiltered
readonly Action<ILogger, double, string, Exception?> Alaris.Strategy.Risk.STRK003A.LogUtilisationFiltered static private
Initial value:
=
        LoggerMessage.Define<double, string>(
            LogLevel.Information,
            new EventId(2, nameof(LogUtilisationFiltered)),
            "Position filtered: utilisation={Utilisation:P0} exceeds threshold, signalStrength={Strength}")
Definition at line 33 of file STRK003A.cs.
Referenced by Alaris.Strategy.Risk.STRK003A.CalculateWithReserve().
MaxUtilisationThreshold
const double Alaris.Strategy.Risk.STRK003A.MaxUtilisationThreshold = 0.90 static private
Definition at line 24 of file STRK003A.cs.
Referenced by Alaris.Strategy.Risk.STRK003A.CalculateWithReserve().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Risk/STRK003A.cs