Alaris: Alaris.Test.Unit.STEJ001ATests Class Reference
Alaris.Test.Unit.STEJ001ATests Class Reference sealed
Unit tests for STEJ001A - Earnings Jump Risk Calibrator. Tests mixture distribution calibration, tail probability, and risk evaluation.
Public Member Functions
STEJ001ATests ()
void CalibrateFromMoves_WithInsufficientData_ReturnsDefault ()
void CalibrateFromMoves_WithNormalData_ReturnsHighLambda ()
void CalibrateFromMoves_WithFatTails_ReturnsLowerLambda ()
void CalculateJumpRiskScore_WithNormalParams_ReturnsSmallTail ()
void CalculateJumpRiskScore_WithFatTailParams_ReturnsLargerTail ()
void CalculateJumpRiskScore_HigherThreshold_ReturnsSmallerProb ()
void EvaluateJumpRisk_LowRisk_ReturnsNoAdjustment ()
void EvaluateJumpRisk_HighRisk_ReturnsReducedAllocation ()
void EvaluateJumpRisk_ElevatedRisk_ReturnsModerateCut ()
void DefaultParameters_ReturnsValidDefaults ()
Private Attributes
readonly STEJ001A _calibrator
Detailed Description
Unit tests for STEJ001A - Earnings Jump Risk Calibrator. Tests mixture distribution calibration, tail probability, and risk evaluation.
Definition at line 13 of file TSUN011A.cs.
Constructor & Destructor Documentation
STEJ001ATests()
Alaris.Test.Unit.STEJ001ATests.STEJ001ATests () inline
Definition at line 17 of file TSUN011A.cs.
References Alaris.Test.Unit.STEJ001ATests._calibrator.
Member Function Documentation
CalculateJumpRiskScore_HigherThreshold_ReturnsSmallerProb()
void Alaris.Test.Unit.STEJ001ATests.CalculateJumpRiskScore_HigherThreshold_ReturnsSmallerProb () inline
Definition at line 113 of file TSUN011A.cs.
References Alaris.Test.Unit.STEJ001ATests._calibrator, Alaris.Strategy.Core.STEJ001A.CalculateJumpRiskScore(), and Alaris.Strategy.Core.STEJ002A.
CalculateJumpRiskScore_WithFatTailParams_ReturnsLargerTail()
void Alaris.Test.Unit.STEJ001ATests.CalculateJumpRiskScore_WithFatTailParams_ReturnsLargerTail () inline
Definition at line 91 of file TSUN011A.cs.
References Alaris.Test.Unit.STEJ001ATests._calibrator, Alaris.Strategy.Core.STEJ001A.CalculateJumpRiskScore(), and Alaris.Strategy.Core.STEJ002A.
CalculateJumpRiskScore_WithNormalParams_ReturnsSmallTail()
void Alaris.Test.Unit.STEJ001ATests.CalculateJumpRiskScore_WithNormalParams_ReturnsSmallTail () inline
Definition at line 69 of file TSUN011A.cs.
References Alaris.Test.Unit.STEJ001ATests._calibrator, Alaris.Strategy.Core.STEJ001A.CalculateJumpRiskScore(), and Alaris.Strategy.Core.STEJ002A.
CalibrateFromMoves_WithFatTails_ReturnsLowerLambda()
void Alaris.Test.Unit.STEJ001ATests.CalibrateFromMoves_WithFatTails_ReturnsLowerLambda () inline
Definition at line 51 of file TSUN011A.cs.
References Alaris.Test.Unit.STEJ001ATests._calibrator, Alaris.Strategy.Core.STEJ001A.CalibrateFromMoves(), and Alaris.Strategy.Core.STEJ002A.
CalibrateFromMoves_WithInsufficientData_ReturnsDefault()
void Alaris.Test.Unit.STEJ001ATests.CalibrateFromMoves_WithInsufficientData_ReturnsDefault () inline
Definition at line 23 of file TSUN011A.cs.
References Alaris.Test.Unit.STEJ001ATests._calibrator, Alaris.Strategy.Core.STEJ001A.CalibrateFromMoves(), and Alaris.Strategy.Core.STEJ002A.
CalibrateFromMoves_WithNormalData_ReturnsHighLambda()
void Alaris.Test.Unit.STEJ001ATests.CalibrateFromMoves_WithNormalData_ReturnsHighLambda () inline
Definition at line 37 of file TSUN011A.cs.
References Alaris.Test.Unit.STEJ001ATests._calibrator, Alaris.Strategy.Core.STEJ001A.CalibrateFromMoves(), and Alaris.Strategy.Core.STEJ002A.
DefaultParameters_ReturnsValidDefaults()
void Alaris.Test.Unit.STEJ001ATests.DefaultParameters_ReturnsValidDefaults () inline
Definition at line 195 of file TSUN011A.cs.
References Alaris.Strategy.Core.STEJ002A.
EvaluateJumpRisk_ElevatedRisk_ReturnsModerateCut()
void Alaris.Test.Unit.STEJ001ATests.EvaluateJumpRisk_ElevatedRisk_ReturnsModerateCut () inline
Definition at line 173 of file TSUN011A.cs.
References Alaris.Test.Unit.STEJ001ATests._calibrator, Alaris.Strategy.Core.STEJ001A.EvaluateJumpRisk(), Alaris.Strategy.Core.STEJ002A, and Alaris.Strategy.Core.STEJ003A.
EvaluateJumpRisk_HighRisk_ReturnsReducedAllocation()
void Alaris.Test.Unit.STEJ001ATests.EvaluateJumpRisk_HighRisk_ReturnsReducedAllocation () inline
Definition at line 150 of file TSUN011A.cs.
References Alaris.Test.Unit.STEJ001ATests._calibrator, Alaris.Strategy.Core.STEJ001A.EvaluateJumpRisk(), Alaris.Strategy.Core.STEJ002A, and Alaris.Strategy.Core.STEJ003A.
EvaluateJumpRisk_LowRisk_ReturnsNoAdjustment()
void Alaris.Test.Unit.STEJ001ATests.EvaluateJumpRisk_LowRisk_ReturnsNoAdjustment () inline
Definition at line 127 of file TSUN011A.cs.
References Alaris.Test.Unit.STEJ001ATests._calibrator, Alaris.Strategy.Core.STEJ001A.EvaluateJumpRisk(), Alaris.Strategy.Core.STEJ002A, and Alaris.Strategy.Core.STEJ003A.
Member Data Documentation
_calibrator
readonly STEJ001A Alaris.Test.Unit.STEJ001ATests._calibrator private
Definition at line 15 of file TSUN011A.cs.
Referenced by Alaris.Test.Unit.STEJ001ATests.STEJ001ATests(), Alaris.Test.Unit.STEJ001ATests.CalculateJumpRiskScore_HigherThreshold_ReturnsSmallerProb(), Alaris.Test.Unit.STEJ001ATests.CalculateJumpRiskScore_WithFatTailParams_ReturnsLargerTail(), Alaris.Test.Unit.STEJ001ATests.CalculateJumpRiskScore_WithNormalParams_ReturnsSmallTail(), Alaris.Test.Unit.STEJ001ATests.CalibrateFromMoves_WithFatTails_ReturnsLowerLambda(), Alaris.Test.Unit.STEJ001ATests.CalibrateFromMoves_WithInsufficientData_ReturnsDefault(), Alaris.Test.Unit.STEJ001ATests.CalibrateFromMoves_WithNormalData_ReturnsHighLambda(), Alaris.Test.Unit.STEJ001ATests.EvaluateJumpRisk_ElevatedRisk_ReturnsModerateCut(), Alaris.Test.Unit.STEJ001ATests.EvaluateJumpRisk_HighRisk_ReturnsReducedAllocation(), and Alaris.Test.Unit.STEJ001ATests.EvaluateJumpRisk_LowRisk_ReturnsNoAdjustment().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN011A.cs