Alaris: Alaris.Strategy.STCT001A Class Reference
Alaris.Strategy.STCT001A Class Reference sealed
Main control class for the earnings volatility calendar spread strategy. Orchestrates signal generation, position sizing, and trade execution.
Public Member Functions
STCT001A (STCR001A signalGenerator, STBR002A pricingEngine, STRK001A positionSizer, ILogger< STCT001A >? logger=null)
async Task< TradingOpportunity > EvaluateOpportunity (string symbol, DateTime earningsDate, DateTime evaluationDate, double portfolioValue, IReadOnlyList< Trade > historicalTrades)
Evaluates a trading opportunity for a given symbol.
Private Member Functions
STPR001AParameters CreateSpreadParameters (STCR004A signal, DateTime evaluationDate)
Creates calendar spread parameters from a signal.
DateTime FindFrontMonthExpiry (DateTime earningsDate, DateTime evaluationDate)
DateTime FindBackMonthExpiry (DateTime frontExpiry)
void SafeLog (Action logAction)
Safely executes logging operation with fault isolation (Rule 15). Prevents logging failures from crashing critical paths.
Private Attributes
readonly STCR001A _signalGenerator
readonly STBR002A _pricingEngine
readonly STRK001A _positionSizer
readonly? ILogger< STCT001A > _logger
Static Private Attributes
static readonly Action< ILogger, string, DateTime, Exception?> LogEvaluatingOpportunity
static readonly Action< ILogger, string, Exception?> LogSTCR004AAvoid
static readonly Action< ILogger, string, STCR004AStrength, int, double, Exception?> LogOpportunityEvaluated
static readonly Action< ILogger, string, Exception?> LogErrorEvaluatingOpportunity
Detailed Description
Main control class for the earnings volatility calendar spread strategy. Orchestrates signal generation, position sizing, and trade execution.
Definition at line 13 of file STCT001A.cs.
Constructor & Destructor Documentation
STCT001A()
Alaris.Strategy.STCT001A.STCT001A (STCR001A signalGenerator, STBR002A pricingEngine, STRK001A positionSizer, ILogger< STCT001A >? logger = null) inline
Definition at line 45 of file STCT001A.cs.
References Alaris.Strategy.STCT001A._logger, Alaris.Strategy.STCT001A._positionSizer, Alaris.Strategy.STCT001A._pricingEngine, and Alaris.Strategy.STCT001A._signalGenerator.
Member Function Documentation
CreateSpreadParameters()
STPR001AParameters Alaris.Strategy.STCT001A.CreateSpreadParameters (STCR004A signal, DateTime evaluationDate) inline private
Creates calendar spread parameters from a signal.
Definition at line 125 of file STCT001A.cs.
References Alaris.Strategy.Core.STCR004A.EarningsDate, Alaris.Strategy.Core.STCR004A.ExpectedMove, Alaris.Strategy.STCT001A.FindBackMonthExpiry(), Alaris.Strategy.STCT001A.FindFrontMonthExpiry(), Alaris.Core.Time.CRTM005A.FromDateTime(), and Alaris.Strategy.Core.STCR004A.ImpliedVolatility30.
Referenced by Alaris.Strategy.STCT001A.EvaluateOpportunity().
EvaluateOpportunity()
async Task< TradingOpportunity > Alaris.Strategy.STCT001A.EvaluateOpportunity (string symbol, DateTime earningsDate, DateTime evaluationDate, double portfolioValue, IReadOnlyList< Trade > historicalTrades) inline
Evaluates a trading opportunity for a given symbol.
Definition at line 60 of file STCT001A.cs.
References Alaris.Strategy.STCT001A._logger, Alaris.Strategy.STCT001A._positionSizer, Alaris.Strategy.STCT001A._pricingEngine, Alaris.Strategy.STCT001A._signalGenerator, Alaris.Strategy.Risk.STRK001A.CalculateFromHistory(), Alaris.Strategy.Risk.STRK002A.Contracts, Alaris.Strategy.STCT001A.CreateSpreadParameters(), Alaris.Strategy.Core.STCR001A.Generate(), Alaris.Strategy.STCT001A.LogErrorEvaluatingOpportunity, Alaris.Strategy.STCT001A.LogEvaluatingOpportunity, Alaris.Strategy.STCT001A.LogOpportunityEvaluated, Alaris.Strategy.STCT001A.LogSTCR004AAvoid, Alaris.Strategy.Bridge.STBR002A.PriceSTPR001A(), Alaris.Strategy.STCT001A.SafeLog(), Alaris.Strategy.Pricing.STPR001APricing.SpreadCost, and Alaris.Strategy.Core.STCR004A.Strength.
FindBackMonthExpiry()
DateTime Alaris.Strategy.STCT001A.FindBackMonthExpiry (DateTime frontExpiry) inline private
Definition at line 165 of file STCT001A.cs.
Referenced by Alaris.Strategy.STCT001A.CreateSpreadParameters().
FindFrontMonthExpiry()
DateTime Alaris.Strategy.STCT001A.FindFrontMonthExpiry (DateTime earningsDate, DateTime evaluationDate) inline private
Definition at line 145 of file STCT001A.cs.
Referenced by Alaris.Strategy.STCT001A.CreateSpreadParameters().
SafeLog()
void Alaris.Strategy.STCT001A.SafeLog (Action logAction) inline private
Safely executes logging operation with fault isolation (Rule 15). Prevents logging failures from crashing critical paths.
Definition at line 175 of file STCT001A.cs.
References Alaris.Strategy.STCT001A._logger.
Referenced by Alaris.Strategy.STCT001A.EvaluateOpportunity().
Member Data Documentation
_logger
readonly? ILogger<STCT001A> Alaris.Strategy.STCT001A._logger private
Definition at line 18 of file STCT001A.cs.
Referenced by Alaris.Strategy.STCT001A.STCT001A(), Alaris.Strategy.STCT001A.EvaluateOpportunity(), and Alaris.Strategy.STCT001A.SafeLog().
_positionSizer
readonly STRK001A Alaris.Strategy.STCT001A._positionSizer private
Definition at line 17 of file STCT001A.cs.
Referenced by Alaris.Strategy.STCT001A.STCT001A(), and Alaris.Strategy.STCT001A.EvaluateOpportunity().
_pricingEngine
readonly STBR002A Alaris.Strategy.STCT001A._pricingEngine private
Definition at line 16 of file STCT001A.cs.
Referenced by Alaris.Strategy.STCT001A.STCT001A(), and Alaris.Strategy.STCT001A.EvaluateOpportunity().
_signalGenerator
readonly STCR001A Alaris.Strategy.STCT001A._signalGenerator private
Definition at line 15 of file STCT001A.cs.
Referenced by Alaris.Strategy.STCT001A.STCT001A(), and Alaris.Strategy.STCT001A.EvaluateOpportunity().
LogErrorEvaluatingOpportunity
readonly Action<ILogger, string, Exception?> Alaris.Strategy.STCT001A.LogErrorEvaluatingOpportunity static private
Initial value:
=
        LoggerMessage.Define<string>(
            LogLevel.Error,
            new EventId(4, nameof(LogErrorEvaluatingOpportunity)),
            "Error evaluating opportunity for {Symbol}")
Definition at line 39 of file STCT001A.cs.
Referenced by Alaris.Strategy.STCT001A.EvaluateOpportunity().
LogEvaluatingOpportunity
readonly Action<ILogger, string, DateTime, Exception?> Alaris.Strategy.STCT001A.LogEvaluatingOpportunity static private
Initial value:
=
        LoggerMessage.Define<string, DateTime>(
            LogLevel.Information,
            new EventId(1, nameof(LogEvaluatingOpportunity)),
            "Evaluating opportunity for {Symbol} with earnings on {EarningsDate}")
Definition at line 21 of file STCT001A.cs.
Referenced by Alaris.Strategy.STCT001A.EvaluateOpportunity().
LogOpportunityEvaluated
readonly Action<ILogger, string, STCR004AStrength, int, double, Exception?> Alaris.Strategy.STCT001A.LogOpportunityEvaluated static private
Initial value:
=
        LoggerMessage.Define<string, STCR004AStrength, int, double>(
            LogLevel.Information,
            new EventId(3, nameof(LogOpportunityEvaluated)),
            "Opportunity evaluated for {Symbol}: STCR004A={Strength}, Contracts={Contracts}, Cost={Cost:C}")
Definition at line 33 of file STCT001A.cs.
Referenced by Alaris.Strategy.STCT001A.EvaluateOpportunity().
LogSTCR004AAvoid
readonly Action<ILogger, string, Exception?> Alaris.Strategy.STCT001A.LogSTCR004AAvoid static private
Initial value:
=
        LoggerMessage.Define<string>(
            LogLevel.Information,
            new EventId(2, nameof(LogSTCR004AAvoid)),
            "STCR004A strength is Avoid for {Symbol}, skipping")
Definition at line 27 of file STCT001A.cs.
Referenced by Alaris.Strategy.STCT001A.EvaluateOpportunity().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/STCT001A.cs