Alaris: Alaris.Test.Unit.Core.Pricing.CREN004ATests Class Reference
Alaris.Test.Unit.Core.Pricing.CREN004ATests Class Reference
Unit tests for the spectral collocation American option pricing engine.
Public Member Functions
void Price_StandardRegime_ReturnsPositiveValue (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType)
void Price_AmericanPut_AtLeastIntrinsic (double spot, double strike, double tau, double r, double q, double sigma)
void Price_AmericanCall_AtLeastIntrinsic (double spot, double strike, double tau, double r, double q, double sigma)
void Price_AmericanGreaterThanEuropean_Put (double spot, double strike, double tau, double r, double q, double sigma)
void Price_NegativeRateRegime_ReturnsPositiveValue (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType)
void Price_NegativeRate_AtLeastIntrinsic (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType)
void Delta_Put_InValidRange (double spot, double strike, double tau, double r, double q, double sigma)
void Delta_Call_InValidRange (double spot, double strike, double tau, double r, double q, double sigma)
void Gamma_NonNegative (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType)
void Vega_Positive (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType)
void Price_AccurateAndFast_AreClose (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType)
void Price_NearExpiry_ReturnsIntrinsic ()
void Price_DeepITM_Put_CloseToIntrinsic ()
void Price_DeepOTM_Put_SmallValue ()
void Price_InvalidSpot_Throws ()
void Price_InvalidVolatility_Throws ()
Static Private Member Functions
static double NormalCDF (double x)
static double Erf (double x)
Private Attributes
readonly CREN004A _fastEngine = new(SpectralScheme.Fast)
readonly CREN004A _accurateEngine = new(SpectralScheme.Accurate)
Detailed Description
Unit tests for the spectral collocation American option pricing engine.
Definition at line 14 of file CREN004ATests.cs.
Member Function Documentation
Delta_Call_InValidRange()
void Alaris.Test.Unit.Core.Pricing.CREN004ATests.Delta_Call_InValidRange (double spot, double strike, double tau, double r, double q, double sigma) inline
Definition at line 125 of file CREN004ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN004ATests._accurateEngine, and Alaris.Core.Pricing.CREN004A.Delta().
Delta_Put_InValidRange()
void Alaris.Test.Unit.Core.Pricing.CREN004ATests.Delta_Put_InValidRange (double spot, double strike, double tau, double r, double q, double sigma) inline
Definition at line 114 of file CREN004ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN004ATests._accurateEngine, and Alaris.Core.Pricing.CREN004A.Delta().
Erf()
static double Alaris.Test.Unit.Core.Pricing.CREN004ATests.Erf (double x) inline static private
Definition at line 249 of file CREN004ATests.cs.
Referenced by Alaris.Test.Unit.Core.Pricing.CREN004ATests.NormalCDF().
Gamma_NonNegative()
void Alaris.Test.Unit.Core.Pricing.CREN004ATests.Gamma_NonNegative (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType) inline
Definition at line 137 of file CREN004ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN004ATests._accurateEngine, and Alaris.Core.Pricing.CREN004A.Gamma().
NormalCDF()
static double Alaris.Test.Unit.Core.Pricing.CREN004ATests.NormalCDF (double x) inline static private
Definition at line 244 of file CREN004ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN004ATests.Erf().
Referenced by Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_AmericanGreaterThanEuropean_Put().
Price_AccurateAndFast_AreClose()
void Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_AccurateAndFast_AreClose (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType) inline
Definition at line 161 of file CREN004ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN004ATests._accurateEngine, Alaris.Test.Unit.Core.Pricing.CREN004ATests._fastEngine, and Alaris.Core.Pricing.CREN004A.Price().
Price_AmericanCall_AtLeastIntrinsic()
void Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_AmericanCall_AtLeastIntrinsic (double spot, double strike, double tau, double r, double q, double sigma) inline
Definition at line 51 of file CREN004ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN004ATests._accurateEngine, and Alaris.Core.Pricing.CREN004A.Price().
Price_AmericanGreaterThanEuropean_Put()
void Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_AmericanGreaterThanEuropean_Put (double spot, double strike, double tau, double r, double q, double sigma) inline
Definition at line 67 of file CREN004ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN004ATests._accurateEngine, Alaris.Test.Unit.Core.Pricing.CREN004ATests.NormalCDF(), and Alaris.Core.Pricing.CREN004A.Price().
Price_AmericanPut_AtLeastIntrinsic()
void Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_AmericanPut_AtLeastIntrinsic (double spot, double strike, double tau, double r, double q, double sigma) inline
Definition at line 37 of file CREN004ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN004ATests._accurateEngine, and Alaris.Core.Pricing.CREN004A.Price().
Price_DeepITM_Put_CloseToIntrinsic()
void Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_DeepITM_Put_CloseToIntrinsic () inline
Definition at line 192 of file CREN004ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN004ATests._accurateEngine, and Alaris.Core.Pricing.CREN004A.Price().
Price_DeepOTM_Put_SmallValue()
void Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_DeepOTM_Put_SmallValue () inline
Definition at line 210 of file CREN004ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN004ATests._accurateEngine, and Alaris.Core.Pricing.CREN004A.Price().
Price_InvalidSpot_Throws()
void Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_InvalidSpot_Throws () inline
Definition at line 229 of file CREN004ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN004ATests._accurateEngine, and Alaris.Core.Pricing.CREN004A.Price().
Price_InvalidVolatility_Throws()
void Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_InvalidVolatility_Throws () inline
Definition at line 236 of file CREN004ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN004ATests._accurateEngine, and Alaris.Core.Pricing.CREN004A.Price().
Price_NearExpiry_ReturnsIntrinsic()
void Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_NearExpiry_ReturnsIntrinsic () inline
Definition at line 175 of file CREN004ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN004ATests._accurateEngine, and Alaris.Core.Pricing.CREN004A.Price().
Price_NegativeRate_AtLeastIntrinsic()
void Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_NegativeRate_AtLeastIntrinsic (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType) inline
Definition at line 98 of file CREN004ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN004ATests._accurateEngine, and Alaris.Core.Pricing.CREN004A.Price().
Price_NegativeRateRegime_ReturnsPositiveValue()
void Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_NegativeRateRegime_ReturnsPositiveValue (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType) inline
Definition at line 89 of file CREN004ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN004ATests._accurateEngine, and Alaris.Core.Pricing.CREN004A.Price().
Price_StandardRegime_ReturnsPositiveValue()
void Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_StandardRegime_ReturnsPositiveValue (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType) inline
Definition at line 26 of file CREN004ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN004ATests._accurateEngine, and Alaris.Core.Pricing.CREN004A.Price().
Vega_Positive()
void Alaris.Test.Unit.Core.Pricing.CREN004ATests.Vega_Positive (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType) inline
Definition at line 148 of file CREN004ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN004ATests._accurateEngine, and Alaris.Core.Pricing.CREN004A.Vega().
Member Data Documentation
_accurateEngine
readonly CREN004A Alaris.Test.Unit.Core.Pricing.CREN004ATests._accurateEngine = new(SpectralScheme.Accurate) private
Definition at line 17 of file CREN004ATests.cs.
Referenced by Alaris.Test.Unit.Core.Pricing.CREN004ATests.Delta_Call_InValidRange(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Delta_Put_InValidRange(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Gamma_NonNegative(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_AccurateAndFast_AreClose(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_AmericanCall_AtLeastIntrinsic(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_AmericanGreaterThanEuropean_Put(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_AmericanPut_AtLeastIntrinsic(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_DeepITM_Put_CloseToIntrinsic(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_DeepOTM_Put_SmallValue(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_InvalidSpot_Throws(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_InvalidVolatility_Throws(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_NearExpiry_ReturnsIntrinsic(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_NegativeRate_AtLeastIntrinsic(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_NegativeRateRegime_ReturnsPositiveValue(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_StandardRegime_ReturnsPositiveValue(), and Alaris.Test.Unit.Core.Pricing.CREN004ATests.Vega_Positive().
_fastEngine
readonly CREN004A Alaris.Test.Unit.Core.Pricing.CREN004ATests._fastEngine = new(SpectralScheme.Fast) private
Definition at line 16 of file CREN004ATests.cs.
Referenced by Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_AccurateAndFast_AreClose().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/Core/Pricing/CREN004ATests.cs