Alaris: Alaris.Host.Application.Service.APsv002A Class Reference
Alaris.Host.Application.Service.APsv002A Class Reference sealed
Service for downloading and preparing session data. Component ID: APsv002A.
Classes
class CachedEarningsDay
Cached earnings data structure for deserialization.
class CachedEarningsEvent
Public Member Functions
APsv002A (PolygonApiClient polygonClient, NasdaqEarningsProvider? earningsClient, TreasuryDirectRateProvider? treasuryClient, ILogger< APsv002A >? logger=null)
async Task DownloadEquityDataAsync (string sessionDataPath, IEnumerable< string > symbols, DateTime start, DateTime end)
Downloads equity data for a session and saves in LEAN format.
async Task< int > BootstrapEarningsCalendarAsync (DateTime startDate, DateTime endDate, string outputPath, CancellationToken cancellationToken=default)
Bootstrap earnings calendar data from NASDAQ API to local cache files. Rate-limited to 1 request per second to avoid anti-bot blocking.
async Task< int > BootstrapOptionsDataAsync (IEnumerable< string > symbols, IEnumerable< DateTime > dates, string sessionDataPath, CancellationToken cancellationToken=default)
Bootstrap options data for specific dates (typically around earnings events). Downloads historical option chain with IV calculated from market prices via Black-Scholes. Rate-limited to 5 concurrent requests per symbol to respect API limits.
async Task< BootstrapReport > BootstrapSessionDataAsync (Alaris.Core.Model.STDT010A requirements, string sessionDataPath, CancellationToken cancellationToken=default)
Bootstraps ALL data required for a backtest session. This is the SINGLE entry point for data preparation.
void Dispose ()
Private Member Functions
async Task GenerateMapFileAsync (string symbol, string mapFilesPath)
Generates a valid LEAN map file (csv) for the symbol. Format: Date,Ticker,Exchange.
async Task GenerateFactorFileAsync (string symbol, string factorFilesPath)
Generates a valid LEAN factor file (csv) for the symbol. Format: Date,PriceFactor,SplitFactor,ReferencePrice Since we use adjusted data from Polygon (post-split prices), we set factors to 1 (no adjustment).
async Task< int > DownloadPriceDataWithBenchmarkAsync (Alaris.Core.Model.STDT010A requirements, string sessionDataPath, CancellationToken cancellationToken)
Downloads price data for all symbols including benchmark.
async Task< bool > DownloadInterestRatesAsync (Alaris.Core.Model.STDT010A requirements, string sessionDataPath, CancellationToken cancellationToken)
Downloads interest rate data.
IReadOnlyList< DateTime > ComputeOptionsRequiredDates (string sessionDataPath, IReadOnlyList< string > symbols, DateTime startDate, DateTime endDate, int minDays, int maxDays)
Computes all dates where options data is required for signal generation. For each earnings event within the session range, we need options on dates [earnings - maxDays, earnings - minDays].
void CopySystemFiles (string sessionDataPath)
Copies system data folders (market-hours, symbol-properties) to the session data folder. LEAN requires these to function correctly.
Static Private Member Functions
static async Task SaveAsLeanZipAsync (string symbol, IEnumerable< PriceBar > bars, string outputDir)
Saves bars to a LEAN-compatible ZIP file.
static ? string FindLeanDataPath ()
static void CopyDirectory (string sourceDir, string destDir)
Private Attributes
readonly PolygonApiClient _polygonClient
readonly? NasdaqEarningsProvider _earningsClient
readonly? TreasuryDirectRateProvider _treasuryClient
readonly? ILogger< APsv002A > _logger
Static Private Attributes
static readonly JsonSerializerOptions JsonOptions = new() { WriteIndented = true }
Detailed Description
Service for downloading and preparing session data. Component ID: APsv002A.
Definition at line 28 of file APsv002A.cs.
Constructor & Destructor Documentation
APsv002A()
Alaris.Host.Application.Service.APsv002A.APsv002A (PolygonApiClient polygonClient, NasdaqEarningsProvider? earningsClient, TreasuryDirectRateProvider? treasuryClient, ILogger< APsv002A >? logger = null) inline
Definition at line 36 of file APsv002A.cs.
References Alaris.Host.Application.Service.APsv002A._earningsClient, Alaris.Host.Application.Service.APsv002A._logger, Alaris.Host.Application.Service.APsv002A._polygonClient, and Alaris.Host.Application.Service.APsv002A._treasuryClient.
Member Function Documentation
BootstrapEarningsCalendarAsync()
async Task< int > Alaris.Host.Application.Service.APsv002A.BootstrapEarningsCalendarAsync (DateTime startDate, DateTime endDate, string outputPath, CancellationToken cancellationToken = default) inline
Bootstrap earnings calendar data from NASDAQ API to local cache files. Rate-limited to 1 request per second to avoid anti-bot blocking.
Parameters
startDate Start date for calendar data.
endDate End date for calendar data.
outputPath Output directory for cached files.
cancellationToken Cancellation token.
Returns
Number of days downloaded.
Definition at line 228 of file APsv002A.cs.
References Alaris.Host.Application.Service.APsv002A._earningsClient, Alaris.Host.Application.Service.APsv002A._logger, and Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.FetchAndCacheAsync().
Referenced by Alaris.Host.Application.Service.APsv002A.BootstrapSessionDataAsync().
BootstrapOptionsDataAsync()
async Task< int > Alaris.Host.Application.Service.APsv002A.BootstrapOptionsDataAsync (IEnumerable< string > symbols, IEnumerable< DateTime > dates, string sessionDataPath, CancellationToken cancellationToken = default) inline
Bootstrap options data for specific dates (typically around earnings events). Downloads historical option chain with IV calculated from market prices via Black-Scholes. Rate-limited to 5 concurrent requests per symbol to respect API limits.
Parameters
symbols Symbols to download options for.
dates Dates to download options for (evaluation dates around earnings).
sessionDataPath Session data path for caching.
cancellationToken Cancellation token.
Returns
Number of option chains downloaded.
Definition at line 331 of file APsv002A.cs.
References Alaris.Host.Application.Service.APsv002A._logger, Alaris.Host.Application.Service.APsv002A._polygonClient, Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetHistoricalOptionChainAsync(), and Alaris.Host.Application.Service.APsv002A.JsonOptions.
Referenced by Alaris.Host.Application.Service.APsv002A.BootstrapSessionDataAsync().
BootstrapSessionDataAsync()
async Task< BootstrapReport > Alaris.Host.Application.Service.APsv002A.BootstrapSessionDataAsync (Alaris::Core::Model::STDT010A requirements, string sessionDataPath, CancellationToken cancellationToken = default) inline
Bootstraps ALL data required for a backtest session. This is the SINGLE entry point for data preparation.
Parameters
requirements Session data requirements model.
sessionDataPath Path to session data directory.
cancellationToken Cancellation token.
Returns
Detailed bootstrap report.
Definition at line 450 of file APsv002A.cs.
References Alaris.Host.Application.Service.APsv002A._earningsClient, Alaris.Host.Application.Service.APsv002A._logger, Alaris.Host.Application.Service.APsv002A._treasuryClient, Alaris.Host.Application.Service.APsv002A.BootstrapEarningsCalendarAsync(), Alaris.Host.Application.Service.APsv002A.BootstrapOptionsDataAsync(), Alaris.Host.Application.Service.APsv002A.ComputeOptionsRequiredDates(), Alaris.Host.Application.Service.APsv002A.CopySystemFiles(), Alaris.Host.Application.Service.APsv002A.DownloadInterestRatesAsync(), and Alaris.Host.Application.Service.APsv002A.DownloadPriceDataWithBenchmarkAsync().
ComputeOptionsRequiredDates()
IReadOnlyList< DateTime > Alaris.Host.Application.Service.APsv002A.ComputeOptionsRequiredDates (string sessionDataPath, IReadOnlyList< string > symbols, DateTime startDate, DateTime endDate, int minDays, int maxDays) inline private
Computes all dates where options data is required for signal generation. For each earnings event within the session range, we need options on dates [earnings - maxDays, earnings - minDays].
Definition at line 652 of file APsv002A.cs.
References Alaris.Host.Application.Service.APsv002A._logger, and Alaris.Host.Application.Service.APsv002A.CachedEarningsDay.Date.
Referenced by Alaris.Host.Application.Service.APsv002A.BootstrapSessionDataAsync().
CopyDirectory()
static void Alaris.Host.Application.Service.APsv002A.CopyDirectory (string sourceDir, string destDir) inline static private
Definition at line 845 of file APsv002A.cs.
References Alaris.Host.Application.Service.APsv002A.CopyDirectory().
Referenced by Alaris.Host.Application.Service.APsv002A.CopyDirectory(), and Alaris.Host.Application.Service.APsv002A.CopySystemFiles().
CopySystemFiles()
void Alaris.Host.Application.Service.APsv002A.CopySystemFiles (string sessionDataPath) inline private
Copies system data folders (market-hours, symbol-properties) to the session data folder. LEAN requires these to function correctly.
Definition at line 791 of file APsv002A.cs.
References Alaris.Host.Application.Service.APsv002A._logger, Alaris.Host.Application.Service.APsv002A.CopyDirectory(), and Alaris.Host.Application.Service.APsv002A.FindLeanDataPath().
Referenced by Alaris.Host.Application.Service.APsv002A.BootstrapSessionDataAsync(), and Alaris.Host.Application.Service.APsv002A.DownloadEquityDataAsync().
Dispose()
void Alaris.Host.Application.Service.APsv002A.Dispose () inline
Definition at line 730 of file APsv002A.cs.
DownloadEquityDataAsync()
async Task Alaris.Host.Application.Service.APsv002A.DownloadEquityDataAsync (string sessionDataPath, IEnumerable< string > symbols, DateTime start, DateTime end) inline
Downloads equity data for a session and saves in LEAN format.
Definition at line 51 of file APsv002A.cs.
References Alaris.Host.Application.Service.APsv002A._logger, Alaris.Host.Application.Service.APsv002A._polygonClient, Alaris.Host.Application.Service.APsv002A._treasuryClient, Alaris.Host.Application.Service.APsv002A.CopySystemFiles(), Alaris.Host.Application.Service.APsv002A.GenerateFactorFileAsync(), Alaris.Host.Application.Service.APsv002A.GenerateMapFileAsync(), Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetHistoricalBarsAsync(), Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetHistoricalOptionChainAsync(), Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider.GetHistoricalRatesAsync(), Alaris.Host.Application.Service.APsv002A.JsonOptions, and Alaris.Host.Application.Service.APsv002A.SaveAsLeanZipAsync().
DownloadInterestRatesAsync()
async Task< bool > Alaris.Host.Application.Service.APsv002A.DownloadInterestRatesAsync (Alaris::Core::Model::STDT010A requirements, string sessionDataPath, CancellationToken cancellationToken) inline private
Downloads interest rate data.
Definition at line 614 of file APsv002A.cs.
References Alaris.Host.Application.Service.APsv002A._logger, Alaris.Host.Application.Service.APsv002A._treasuryClient, and Alaris.Infrastructure.Data.Provider.Treasury.TreasuryDirectRateProvider.GetHistoricalRatesAsync().
Referenced by Alaris.Host.Application.Service.APsv002A.BootstrapSessionDataAsync().
DownloadPriceDataWithBenchmarkAsync()
async Task< int > Alaris.Host.Application.Service.APsv002A.DownloadPriceDataWithBenchmarkAsync (Alaris::Core::Model::STDT010A requirements, string sessionDataPath, CancellationToken cancellationToken) inline private
Downloads price data for all symbols including benchmark.
Definition at line 549 of file APsv002A.cs.
References Alaris.Host.Application.Service.APsv002A._logger, Alaris.Host.Application.Service.APsv002A._polygonClient, Alaris.Host.Application.Service.APsv002A.GenerateFactorFileAsync(), Alaris.Host.Application.Service.APsv002A.GenerateMapFileAsync(), Alaris.Infrastructure.Data.Provider.Polygon.PolygonApiClient.GetHistoricalBarsAsync(), and Alaris.Host.Application.Service.APsv002A.SaveAsLeanZipAsync().
Referenced by Alaris.Host.Application.Service.APsv002A.BootstrapSessionDataAsync().
FindLeanDataPath()
static ? string Alaris.Host.Application.Service.APsv002A.FindLeanDataPath () inline static private
Definition at line 826 of file APsv002A.cs.
Referenced by Alaris.Host.Application.Service.APsv002A.CopySystemFiles().
GenerateFactorFileAsync()
async Task Alaris.Host.Application.Service.APsv002A.GenerateFactorFileAsync (string symbol, string factorFilesPath) inline private
Generates a valid LEAN factor file (csv) for the symbol. Format: Date,PriceFactor,SplitFactor,ReferencePrice Since we use adjusted data from Polygon (post-split prices), we set factors to 1 (no adjustment).
Definition at line 206 of file APsv002A.cs.
Referenced by Alaris.Host.Application.Service.APsv002A.DownloadEquityDataAsync(), and Alaris.Host.Application.Service.APsv002A.DownloadPriceDataWithBenchmarkAsync().
GenerateMapFileAsync()
async Task Alaris.Host.Application.Service.APsv002A.GenerateMapFileAsync (string symbol, string mapFilesPath) inline private
Generates a valid LEAN map file (csv) for the symbol. Format: Date,Ticker,Exchange.
Definition at line 188 of file APsv002A.cs.
Referenced by Alaris.Host.Application.Service.APsv002A.DownloadEquityDataAsync(), and Alaris.Host.Application.Service.APsv002A.DownloadPriceDataWithBenchmarkAsync().
SaveAsLeanZipAsync()
static async Task Alaris.Host.Application.Service.APsv002A.SaveAsLeanZipAsync (string symbol, IEnumerable< PriceBar > bars, string outputDir) inline static private
Saves bars to a LEAN-compatible ZIP file.
Definition at line 738 of file APsv002A.cs.
Referenced by Alaris.Host.Application.Service.APsv002A.DownloadEquityDataAsync(), and Alaris.Host.Application.Service.APsv002A.DownloadPriceDataWithBenchmarkAsync().
Member Data Documentation
_earningsClient
readonly? NasdaqEarningsProvider Alaris.Host.Application.Service.APsv002A._earningsClient private
Definition at line 31 of file APsv002A.cs.
Referenced by Alaris.Host.Application.Service.APsv002A.APsv002A(), Alaris.Host.Application.Service.APsv002A.BootstrapEarningsCalendarAsync(), and Alaris.Host.Application.Service.APsv002A.BootstrapSessionDataAsync().
_logger
readonly? ILogger<APsv002A> Alaris.Host.Application.Service.APsv002A._logger private
Definition at line 33 of file APsv002A.cs.
Referenced by Alaris.Host.Application.Service.APsv002A.APsv002A(), Alaris.Host.Application.Service.APsv002A.BootstrapEarningsCalendarAsync(), Alaris.Host.Application.Service.APsv002A.BootstrapOptionsDataAsync(), Alaris.Host.Application.Service.APsv002A.BootstrapSessionDataAsync(), Alaris.Host.Application.Service.APsv002A.ComputeOptionsRequiredDates(), Alaris.Host.Application.Service.APsv002A.CopySystemFiles(), Alaris.Host.Application.Service.APsv002A.DownloadEquityDataAsync(), Alaris.Host.Application.Service.APsv002A.DownloadInterestRatesAsync(), and Alaris.Host.Application.Service.APsv002A.DownloadPriceDataWithBenchmarkAsync().
_polygonClient
readonly PolygonApiClient Alaris.Host.Application.Service.APsv002A._polygonClient private
Definition at line 30 of file APsv002A.cs.
Referenced by Alaris.Host.Application.Service.APsv002A.APsv002A(), Alaris.Host.Application.Service.APsv002A.BootstrapOptionsDataAsync(), Alaris.Host.Application.Service.APsv002A.DownloadEquityDataAsync(), and Alaris.Host.Application.Service.APsv002A.DownloadPriceDataWithBenchmarkAsync().
_treasuryClient
readonly? TreasuryDirectRateProvider Alaris.Host.Application.Service.APsv002A._treasuryClient private
Definition at line 32 of file APsv002A.cs.
Referenced by Alaris.Host.Application.Service.APsv002A.APsv002A(), Alaris.Host.Application.Service.APsv002A.BootstrapSessionDataAsync(), Alaris.Host.Application.Service.APsv002A.DownloadEquityDataAsync(), and Alaris.Host.Application.Service.APsv002A.DownloadInterestRatesAsync().
JsonOptions
readonly JsonSerializerOptions Alaris.Host.Application.Service.APsv002A.JsonOptions = new() { WriteIndented = true } static private
Definition at line 34 of file APsv002A.cs.
Referenced by Alaris.Host.Application.Service.APsv002A.BootstrapOptionsDataAsync(), and Alaris.Host.Application.Service.APsv002A.DownloadEquityDataAsync().
The documentation for this class was generated from the following file:
src/Alaris.Host/Application/Service/APsv002A.cs