Alaris: Alaris.Core.Pricing.CREN003A Class Reference
Alaris.Core.Pricing.CREN003A Class Reference sealed
Unified American option pricing engine. Automatically selects the appropriate method based on rate regime.
Public Member Functions
CREN003A (SpectralScheme scheme=SpectralScheme.Accurate, bool enforceInvariants=true)
Initialises the unified pricing engine with spectral as default.
CREN003A (int timeSteps, int spotSteps)
Initialises the unified pricing engine with legacy FD-only mode.
double Price (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType)
double Delta (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType)
double Gamma (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType)
double Theta (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType)
double Vega (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType)
double Rho (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType)
UnifiedPricingResult PriceWithDetails (double spot, double strike, double timeToExpiry, double volatility, double riskFreeRate, double dividendYield, OptionType optionType)
Prices an American option with full result details including regime and method used.
Private Member Functions
double EnforceInvariants (double price, double spot, double strike, double tau, double r, double q, double sigma, bool isCall)
Enforces mathematical invariants: American >= European and American >= Intrinsic.
Static Private Member Functions
static double BlackScholesEuropean (double spot, double strike, double tau, double r, double q, double sigma, bool isCall)
static void ValidateParameters (double spot, double strike, double timeToExpiry, double volatility)
Validates input parameters.
Private Attributes
readonly CREN004A _spectralEngine
readonly CREN002A _fdEngine
readonly CREX001A _nearExpiryHandler
readonly bool _enforceInvariants
Detailed Description
Unified American option pricing engine. Automatically selects the appropriate method based on rate regime.
Rate Regime Classification (Healy 2021)
Regime Condition Method
Standard r ≥ 0 OR r < q < 0 FD (CREN002A)
Double Boundary q < r < 0 (puts) OR 0 < r < q (calls) QD+ (DBAP002A)
Definition at line 122 of file CREN003A.cs.
Constructor & Destructor Documentation
CREN003A() [1/2]
Alaris.Core.Pricing.CREN003A.CREN003A (SpectralScheme scheme = SpectralScheme::Accurate, bool enforceInvariants = true) inline
Initialises the unified pricing engine with spectral as default.
Parameters
scheme Spectral scheme (Fast/Accurate/HighPrecision).
enforceInvariants Whether to enforce American >= European and >= Intrinsic.
Definition at line 134 of file CREN003A.cs.
References Alaris.Core.Pricing.CREN003A._enforceInvariants, Alaris.Core.Pricing.CREN003A._fdEngine, Alaris.Core.Pricing.CREN003A._nearExpiryHandler, and Alaris.Core.Pricing.CREN003A._spectralEngine.
CREN003A() [2/2]
Alaris.Core.Pricing.CREN003A.CREN003A (int timeSteps, int spotSteps) inline
Initialises the unified pricing engine with legacy FD-only mode.
Parameters
timeSteps Number of time steps for FD method.
spotSteps Number of spot steps for FD method.
Definition at line 147 of file CREN003A.cs.
References Alaris.Core.Pricing.CREN003A._enforceInvariants, Alaris.Core.Pricing.CREN003A._fdEngine, Alaris.Core.Pricing.CREN003A._nearExpiryHandler, and Alaris.Core.Pricing.CREN003A._spectralEngine.
Member Function Documentation
BlackScholesEuropean()
static double Alaris.Core.Pricing.CREN003A.BlackScholesEuropean (double spot, double strike, double tau, double r, double q, double sigma, bool isCall) inline static private
Definition at line 203 of file CREN003A.cs.
Referenced by Alaris.Core.Pricing.CREN003A.EnforceInvariants().
Delta()
double Alaris.Core.Pricing.CREN003A.Delta (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType) inline
Implements Alaris.Core.Pricing.IAmericanOptionEngine.
Definition at line 226 of file CREN003A.cs.
References Alaris.Core.Pricing.CREN003A._nearExpiryHandler, Alaris.Core.Pricing.CREN003A._spectralEngine, Alaris.Core.Pricing.CREX001A.CalculateNearExpiryGreeks(), Alaris.Core.Pricing.CREN004A.Delta(), Alaris.Core.Pricing.CREX001A.IsNearExpiry(), and Alaris.Core.Pricing.NearExpiryGreeks.
Referenced by Alaris.Test.Unit.Core.Pricing.CREN003ATests.Delta_InValidRange(), Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_DeltaInValidRange(), Alaris.Strategy.Bridge.STBR001A.PriceOption(), and Alaris.Core.Pricing.CREN003A.PriceWithDetails().
EnforceInvariants()
double Alaris.Core.Pricing.CREN003A.EnforceInvariants (double price, double spot, double strike, double tau, double r, double q, double sigma, bool isCall) inline private
Enforces mathematical invariants: American >= European and American >= Intrinsic.
Definition at line 185 of file CREN003A.cs.
References Alaris.Core.Pricing.CREN003A._enforceInvariants, and Alaris.Core.Pricing.CREN003A.BlackScholesEuropean().
Referenced by Alaris.Core.Pricing.CREN003A.Price().
Gamma()
double Alaris.Core.Pricing.CREN003A.Gamma (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType) inline
Implements Alaris.Core.Pricing.IAmericanOptionEngine.
Definition at line 241 of file CREN003A.cs.
References Alaris.Core.Pricing.CREN003A._nearExpiryHandler, Alaris.Core.Pricing.CREN003A._spectralEngine, Alaris.Core.Pricing.CREX001A.CalculateNearExpiryGreeks(), Alaris.Core.Pricing.CREN004A.Gamma(), Alaris.Core.Pricing.CREX001A.IsNearExpiry(), and Alaris.Core.Pricing.NearExpiryGreeks.
Referenced by Alaris.Test.Unit.Core.Pricing.CREN003ATests.Gamma_NonNegative(), Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_GammaNonNegative(), Alaris.Strategy.Bridge.STBR001A.PriceOption(), and Alaris.Core.Pricing.CREN003A.PriceWithDetails().
Price()
double Alaris.Core.Pricing.CREN003A.Price (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType) inline
Implements Alaris.Core.Pricing.IAmericanOptionEngine.
Definition at line 156 of file CREN003A.cs.
References Alaris.Core.Pricing.CREN003A._nearExpiryHandler, Alaris.Core.Pricing.CREN003A._spectralEngine, Alaris.Core.Pricing.CREX001A.BlendWithIntrinsic(), Alaris.Core.Pricing.CREX001A.CalculateIntrinsic(), Alaris.Core.Pricing.CREN003A.EnforceInvariants(), Alaris.Core.Pricing.CREX001A.IsIntrinsicOnly(), Alaris.Core.Pricing.CREX001A.IsNearExpiry(), and Alaris.Core.Pricing.CREN004A.Price().
Referenced by Alaris.Test.Unit.Core.Pricing.CREN004AExtendedTests.EdgeCase_EqualRateAndDividend_Works(), Alaris.Test.Unit.Core.Pricing.CREN004AExtendedTests.EdgeCase_ZeroDividend_StandardRegime(), Alaris.Test.Unit.Core.Pricing.CREN004AExtendedTests.EdgeCase_ZeroTimeValue_ReturnsIntrinsic(), Alaris.Test.Unit.Core.Pricing.CREN004AExtendedTests.ExternalReference_HealyTable4_DoubleBoundaryPut(), Alaris.Test.Unit.Core.Pricing.CREN004AExtendedTests.ExternalReference_StandardPut_MatchesTextbookCase(), Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_AllRegimesProduceValidPrices(), Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_AmericanPriceGreaterThanOrEqualToEuropean(), Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_AmericanPriceGreaterThanOrEqualToIntrinsic(), Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_DeterministicPricing(), Alaris.Test.Unit.Core.Pricing.CREN004AExtendedTests.NumericalStability_RepeatedCalculations_NoDrift(), Alaris.Test.Unit.Core.Pricing.CREN004AExtendedTests.NumericalStability_ScaledPrices_MaintainsInvariants(), Alaris.Test.Unit.Core.Pricing.CREN004AExtendedTests.NumericalStability_VeryLowVolatility_ReturnsFinitePrice(), Alaris.Test.Unit.Core.Pricing.CREN004AExtendedTests.NumericalStability_VeryNearExpiry_ReturnsIntrinsic(), Alaris.Test.Unit.Core.Pricing.CREN003ATests.Price_AmericanGreaterThanOrEqualEuropean(), Alaris.Test.Unit.Core.Pricing.CREN003ATests.Price_AtLeastIntrinsicValue(), Alaris.Test.Unit.Core.Pricing.CREN003ATests.Price_DeepITM_ConvergesToIntrinsic(), Alaris.Test.Unit.Core.Pricing.CREN003ATests.Price_NearExpiryOption_StillValid(), Alaris.Strategy.Bridge.STBR001A.PriceOption(), Alaris.Core.Pricing.CREN003A.PriceWithDetails(), Alaris.Test.Unit.Core.Pricing.CREN004AExtendedTests.Stress_ExtremeMoneyness_ReturnsFinitePrice(), Alaris.Test.Unit.Core.Pricing.CREN004AExtendedTests.Stress_ExtremeRates_ReturnsFinitePrice(), Alaris.Test.Unit.Core.Pricing.CREN004AExtendedTests.Stress_HighVolatility_ReturnsFinitePrice(), and Alaris.Test.Unit.Core.Pricing.CREN004AExtendedTests.Stress_LongMaturity_ReturnsFinitePrice().
PriceWithDetails()
UnifiedPricingResult Alaris.Core.Pricing.CREN003A.PriceWithDetails (double spot, double strike, double timeToExpiry, double volatility, double riskFreeRate, double dividendYield, OptionType optionType) inline
Prices an American option with full result details including regime and method used.
Parameters
spot Current spot price (must be > 0).
strike Strike price (must be > 0).
timeToExpiry Time to expiry in years (must be > 0).
volatility Volatility σ (must be > 0).
riskFreeRate Risk-free rate r (can be negative).
dividendYield Dividend yield q (can be negative).
optionType Option type (Call or Put).
Returns
Full pricing result with Greeks and regime information.
Definition at line 302 of file CREN003A.cs.
References Alaris.Core.Pricing.CREN003A._fdEngine, Alaris.Core.Math.CRMF001A.BSPrice(), Alaris.Core.Pricing.CRAP001A.CalculateBoundaries(), Alaris.Core.Pricing.CRRE001A.Classify(), Alaris.Core.Pricing.CREN002A.Delta(), Alaris.Core.Pricing.CREN003A.Delta(), Alaris.Core.Pricing.CREN002A.Gamma(), Alaris.Core.Pricing.CREN003A.Gamma(), Alaris.Core.Pricing.CREN002A.Price(), Alaris.Core.Pricing.CREN003A.Price(), Alaris.Core.Pricing.CREN002A.Rho(), Alaris.Core.Pricing.CREN003A.Rho(), Alaris.Core.Pricing.CREN002A.Theta(), Alaris.Core.Pricing.CREN003A.Theta(), Alaris.Core.Pricing.CREN003A.ValidateParameters(), Alaris.Core.Pricing.CREN002A.Vega(), and Alaris.Core.Pricing.CREN003A.Vega().
Referenced by Alaris.Test.Unit.Core.Pricing.CREN003ATests.PriceWithDetails_IncludesAllGreeks(), and Alaris.Test.Unit.Core.Pricing.CREN003ATests.PriceWithDetails_NegativeRateRegime_ClassifiesCorrectly().
Rho()
double Alaris.Core.Pricing.CREN003A.Rho (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType) inline
Implements Alaris.Core.Pricing.IAmericanOptionEngine.
Definition at line 286 of file CREN003A.cs.
References Alaris.Core.Pricing.CREN003A._fdEngine, and Alaris.Core.Pricing.CREN002A.Rho().
Referenced by Alaris.Strategy.Bridge.STBR001A.PriceOption(), and Alaris.Core.Pricing.CREN003A.PriceWithDetails().
Theta()
double Alaris.Core.Pricing.CREN003A.Theta (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType) inline
Implements Alaris.Core.Pricing.IAmericanOptionEngine.
Definition at line 256 of file CREN003A.cs.
References Alaris.Core.Pricing.CREN003A._nearExpiryHandler, Alaris.Core.Pricing.CREN003A._spectralEngine, Alaris.Core.Pricing.CREX001A.CalculateNearExpiryGreeks(), Alaris.Core.Pricing.CREX001A.IsNearExpiry(), Alaris.Core.Pricing.NearExpiryGreeks, and Alaris.Core.Pricing.CREN004A.Theta().
Referenced by Alaris.Strategy.Bridge.STBR001A.PriceOption(), and Alaris.Core.Pricing.CREN003A.PriceWithDetails().
ValidateParameters()
static void Alaris.Core.Pricing.CREN003A.ValidateParameters (double spot, double strike, double timeToExpiry, double volatility) inline static private
Validates input parameters.
Definition at line 378 of file CREN003A.cs.
Referenced by Alaris.Core.Pricing.CREN003A.PriceWithDetails().
Vega()
double Alaris.Core.Pricing.CREN003A.Vega (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType) inline
Implements Alaris.Core.Pricing.IAmericanOptionEngine.
Definition at line 271 of file CREN003A.cs.
References Alaris.Core.Pricing.CREN003A._nearExpiryHandler, Alaris.Core.Pricing.CREN003A._spectralEngine, Alaris.Core.Pricing.CREX001A.CalculateNearExpiryGreeks(), Alaris.Core.Pricing.CREX001A.IsNearExpiry(), Alaris.Core.Pricing.NearExpiryGreeks, and Alaris.Core.Pricing.CREN004A.Vega().
Referenced by Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_VegaNonNegative(), Alaris.Strategy.Bridge.STBR001A.PriceOption(), Alaris.Core.Pricing.CREN003A.PriceWithDetails(), and Alaris.Test.Unit.Core.Pricing.CREN003ATests.Vega_NonNegative().
Member Data Documentation
_enforceInvariants
readonly bool Alaris.Core.Pricing.CREN003A._enforceInvariants private
Definition at line 127 of file CREN003A.cs.
Referenced by Alaris.Core.Pricing.CREN003A.CREN003A(), Alaris.Core.Pricing.CREN003A.CREN003A(), and Alaris.Core.Pricing.CREN003A.EnforceInvariants().
_fdEngine
readonly CREN002A Alaris.Core.Pricing.CREN003A._fdEngine private
Definition at line 125 of file CREN003A.cs.
Referenced by Alaris.Core.Pricing.CREN003A.CREN003A(), Alaris.Core.Pricing.CREN003A.CREN003A(), Alaris.Core.Pricing.CREN003A.PriceWithDetails(), and Alaris.Core.Pricing.CREN003A.Rho().
_nearExpiryHandler
readonly CREX001A Alaris.Core.Pricing.CREN003A._nearExpiryHandler private
Definition at line 126 of file CREN003A.cs.
Referenced by Alaris.Core.Pricing.CREN003A.CREN003A(), Alaris.Core.Pricing.CREN003A.CREN003A(), Alaris.Core.Pricing.CREN003A.Delta(), Alaris.Core.Pricing.CREN003A.Gamma(), Alaris.Core.Pricing.CREN003A.Price(), Alaris.Core.Pricing.CREN003A.Theta(), and Alaris.Core.Pricing.CREN003A.Vega().
_spectralEngine
readonly CREN004A Alaris.Core.Pricing.CREN003A._spectralEngine private
Definition at line 124 of file CREN003A.cs.
Referenced by Alaris.Core.Pricing.CREN003A.CREN003A(), Alaris.Core.Pricing.CREN003A.CREN003A(), Alaris.Core.Pricing.CREN003A.Delta(), Alaris.Core.Pricing.CREN003A.Gamma(), Alaris.Core.Pricing.CREN003A.Price(), Alaris.Core.Pricing.CREN003A.Theta(), and Alaris.Core.Pricing.CREN003A.Vega().
The documentation for this class was generated from the following file:
src/Alaris.Core/Pricing/CREN003A.cs