Alaris: Alaris.Test.Unit.STIV006ATests Class Reference
Alaris.Test.Unit.STIV006ATests Class Reference sealed
Unit tests for STIV006A - Volatility Surface Interpolator. Tests sticky-delta convention, skew calibration, and exposure evaluation.
Public Member Functions
STIV006ATests ()
void CalibrateFromChain_WithValidChain_ReturnsParameters ()
void CalibrateFromChain_WithInsufficientData_ThrowsArgumentException ()
void InterpolateIV_AtATM_ReturnsAtmIV ()
void InterpolateIV_BelowATM_ReturnsHigherIV ()
void InterpolateIV_AboveATM_ReturnsLowerIV ()
void InterpolateIV_ClampsToReasonableRange ()
void CalculateStickyDeltaIVChange_SpotUp_ReturnsPositiveChange ()
void CalculateStickyDeltaIVChange_SpotDown_ReturnsNegativeChange ()
void EvaluateSkewExposure_SmallShift_ReturnsLowRisk ()
void EvaluateSkewExposure_LargeShift_ReturnsHighRisk ()
void EvaluateSkewExposure_ElevatedShift_RecommendRecenter ()
Static Private Member Functions
static List< STIV008A > CreateSampleChain (double spotPrice, double atmIV)
static STIV007A CreateSampleParameters (double atmIV, double skew, double spot)
Private Attributes
readonly STIV006A _interpolator
Detailed Description
Unit tests for STIV006A - Volatility Surface Interpolator. Tests sticky-delta convention, skew calibration, and exposure evaluation.
Definition at line 13 of file TSUN012A.cs.
Constructor & Destructor Documentation
STIV006ATests()
Alaris.Test.Unit.STIV006ATests.STIV006ATests () inline
Definition at line 17 of file TSUN012A.cs.
References Alaris.Test.Unit.STIV006ATests._interpolator.
Member Function Documentation
CalculateStickyDeltaIVChange_SpotDown_ReturnsNegativeChange()
void Alaris.Test.Unit.STIV006ATests.CalculateStickyDeltaIVChange_SpotDown_ReturnsNegativeChange () inline
Definition at line 136 of file TSUN012A.cs.
References Alaris.Test.Unit.STIV006ATests._interpolator, Alaris.Strategy.Core.STIV006A.CalculateStickyDeltaIVChange(), Alaris.Test.Unit.STIV006ATests.CreateSampleParameters(), and Alaris.Strategy.Core.STIV007A.
CalculateStickyDeltaIVChange_SpotUp_ReturnsPositiveChange()
void Alaris.Test.Unit.STIV006ATests.CalculateStickyDeltaIVChange_SpotUp_ReturnsPositiveChange () inline
Definition at line 119 of file TSUN012A.cs.
References Alaris.Test.Unit.STIV006ATests._interpolator, Alaris.Strategy.Core.STIV006A.CalculateStickyDeltaIVChange(), Alaris.Test.Unit.STIV006ATests.CreateSampleParameters(), and Alaris.Strategy.Core.STIV007A.
CalibrateFromChain_WithInsufficientData_ThrowsArgumentException()
void Alaris.Test.Unit.STIV006ATests.CalibrateFromChain_WithInsufficientData_ThrowsArgumentException () inline
Definition at line 39 of file TSUN012A.cs.
References Alaris.Test.Unit.STIV006ATests._interpolator, Alaris.Strategy.Core.STIV006A.CalibrateFromChain(), and Alaris.Strategy.Core.STIV008A.
CalibrateFromChain_WithValidChain_ReturnsParameters()
void Alaris.Test.Unit.STIV006ATests.CalibrateFromChain_WithValidChain_ReturnsParameters () inline
Definition at line 23 of file TSUN012A.cs.
References Alaris.Test.Unit.STIV006ATests._interpolator, Alaris.Strategy.Core.STIV006A.CalibrateFromChain(), Alaris.Test.Unit.STIV006ATests.CreateSampleChain(), and Alaris.Strategy.Core.STIV007A.
CreateSampleChain()
static List< STIV008A > Alaris.Test.Unit.STIV006ATests.CreateSampleChain (double spotPrice, double atmIV) inline static private
Definition at line 198 of file TSUN012A.cs.
References Alaris.Strategy.Core.STIV008A.
Referenced by Alaris.Test.Unit.STIV006ATests.CalibrateFromChain_WithValidChain_ReturnsParameters().
CreateSampleParameters()
static STIV007A Alaris.Test.Unit.STIV006ATests.CreateSampleParameters (double atmIV, double skew, double spot) inline static private
Definition at line 223 of file TSUN012A.cs.
References Alaris.Strategy.Core.STIV007A.
Referenced by Alaris.Test.Unit.STIV006ATests.CalculateStickyDeltaIVChange_SpotDown_ReturnsNegativeChange(), Alaris.Test.Unit.STIV006ATests.CalculateStickyDeltaIVChange_SpotUp_ReturnsPositiveChange(), Alaris.Test.Unit.STIV006ATests.EvaluateSkewExposure_ElevatedShift_RecommendRecenter(), Alaris.Test.Unit.STIV006ATests.EvaluateSkewExposure_LargeShift_ReturnsHighRisk(), Alaris.Test.Unit.STIV006ATests.EvaluateSkewExposure_SmallShift_ReturnsLowRisk(), Alaris.Test.Unit.STIV006ATests.InterpolateIV_AboveATM_ReturnsLowerIV(), Alaris.Test.Unit.STIV006ATests.InterpolateIV_AtATM_ReturnsAtmIV(), and Alaris.Test.Unit.STIV006ATests.InterpolateIV_BelowATM_ReturnsHigherIV().
EvaluateSkewExposure_ElevatedShift_RecommendRecenter()
void Alaris.Test.Unit.STIV006ATests.EvaluateSkewExposure_ElevatedShift_RecommendRecenter () inline
Definition at line 182 of file TSUN012A.cs.
References Alaris.Test.Unit.STIV006ATests._interpolator, Alaris.Test.Unit.STIV006ATests.CreateSampleParameters(), Alaris.Strategy.Core.STIV006A.EvaluateSkewExposure(), Alaris.Strategy.Core.STIV007A, and Alaris.Strategy.Core.STIV009A.
EvaluateSkewExposure_LargeShift_ReturnsHighRisk()
void Alaris.Test.Unit.STIV006ATests.EvaluateSkewExposure_LargeShift_ReturnsHighRisk () inline
Definition at line 167 of file TSUN012A.cs.
References Alaris.Test.Unit.STIV006ATests._interpolator, Alaris.Test.Unit.STIV006ATests.CreateSampleParameters(), Alaris.Strategy.Core.STIV006A.EvaluateSkewExposure(), Alaris.Strategy.Core.STIV007A, and Alaris.Strategy.Core.STIV009A.
EvaluateSkewExposure_SmallShift_ReturnsLowRisk()
void Alaris.Test.Unit.STIV006ATests.EvaluateSkewExposure_SmallShift_ReturnsLowRisk () inline
Definition at line 152 of file TSUN012A.cs.
References Alaris.Test.Unit.STIV006ATests._interpolator, Alaris.Test.Unit.STIV006ATests.CreateSampleParameters(), Alaris.Strategy.Core.STIV006A.EvaluateSkewExposure(), Alaris.Strategy.Core.STIV007A, and Alaris.Strategy.Core.STIV009A.
InterpolateIV_AboveATM_ReturnsLowerIV()
void Alaris.Test.Unit.STIV006ATests.InterpolateIV_AboveATM_ReturnsLowerIV () inline
Definition at line 83 of file TSUN012A.cs.
References Alaris.Test.Unit.STIV006ATests._interpolator, Alaris.Test.Unit.STIV006ATests.CreateSampleParameters(), Alaris.Strategy.Core.STIV006A.InterpolateIV(), and Alaris.Strategy.Core.STIV007A.
InterpolateIV_AtATM_ReturnsAtmIV()
void Alaris.Test.Unit.STIV006ATests.InterpolateIV_AtATM_ReturnsAtmIV () inline
Definition at line 56 of file TSUN012A.cs.
References Alaris.Test.Unit.STIV006ATests._interpolator, Alaris.Test.Unit.STIV006ATests.CreateSampleParameters(), Alaris.Strategy.Core.STIV006A.InterpolateIV(), and Alaris.Strategy.Core.STIV007A.
InterpolateIV_BelowATM_ReturnsHigherIV()
void Alaris.Test.Unit.STIV006ATests.InterpolateIV_BelowATM_ReturnsHigherIV () inline
Definition at line 69 of file TSUN012A.cs.
References Alaris.Test.Unit.STIV006ATests._interpolator, Alaris.Test.Unit.STIV006ATests.CreateSampleParameters(), Alaris.Strategy.Core.STIV006A.InterpolateIV(), and Alaris.Strategy.Core.STIV007A.
InterpolateIV_ClampsToReasonableRange()
void Alaris.Test.Unit.STIV006ATests.InterpolateIV_ClampsToReasonableRange () inline
Definition at line 97 of file TSUN012A.cs.
References Alaris.Test.Unit.STIV006ATests._interpolator, Alaris.Strategy.Core.STIV006A.InterpolateIV(), and Alaris.Strategy.Core.STIV007A.
Member Data Documentation
_interpolator
readonly STIV006A Alaris.Test.Unit.STIV006ATests._interpolator private
Definition at line 15 of file TSUN012A.cs.
Referenced by Alaris.Test.Unit.STIV006ATests.STIV006ATests(), Alaris.Test.Unit.STIV006ATests.CalculateStickyDeltaIVChange_SpotDown_ReturnsNegativeChange(), Alaris.Test.Unit.STIV006ATests.CalculateStickyDeltaIVChange_SpotUp_ReturnsPositiveChange(), Alaris.Test.Unit.STIV006ATests.CalibrateFromChain_WithInsufficientData_ThrowsArgumentException(), Alaris.Test.Unit.STIV006ATests.CalibrateFromChain_WithValidChain_ReturnsParameters(), Alaris.Test.Unit.STIV006ATests.EvaluateSkewExposure_ElevatedShift_RecommendRecenter(), Alaris.Test.Unit.STIV006ATests.EvaluateSkewExposure_LargeShift_ReturnsHighRisk(), Alaris.Test.Unit.STIV006ATests.EvaluateSkewExposure_SmallShift_ReturnsLowRisk(), Alaris.Test.Unit.STIV006ATests.InterpolateIV_AboveATM_ReturnsLowerIV(), Alaris.Test.Unit.STIV006ATests.InterpolateIV_AtATM_ReturnsAtmIV(), Alaris.Test.Unit.STIV006ATests.InterpolateIV_BelowATM_ReturnsHigherIV(), and Alaris.Test.Unit.STIV006ATests.InterpolateIV_ClampsToReasonableRange().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN012A.cs