Alaris: Alaris.Strategy.Bridge.STBR001A Class Reference
Alaris.Strategy.Bridge.STBR001A Class Reference sealed
Unified pricing engine that automatically selects between Alaris native engines based on interest rate regime. Uses spectral collocation as default for performance.
Public Member Functions
STBR001A (ILogger< STBR001A >? logger=null, SpectralScheme scheme=SpectralScheme.Accurate)
Initializes a new instance of the STBR001A with spectral collocation engine.
Task< OptionPricing > PriceOption (STDT003A parameters)
Prices a single American option using the native pricing engine.
async Task< STPR001APricing > PriceSTPR001A (STPR001AParameters parameters)
Prices a calendar spread using the native pricing engine for each leg.
Task< double > CalculateImpliedVolatility (double marketPrice, STDT003A parameters)
Calculates implied volatility from market price using high-order Householder method.
void Dispose ()
Disposes resources.
Static Public Member Functions
static PricingRegime DetermineRegime (double riskFreeRate, double dividendYield, bool isCall)
Determines the appropriate pricing regime based on interest rate, dividend yield, and option type.
Private Member Functions
async Task< double > CalculateMaxProfit (STPR001AParameters parameters, double spreadCost)
Calculates the maximum profit potential of a calendar spread.
Task< double > CalculateBreakEven (STPR001AParameters parameters, double spreadCost)
Calculates the break-even point for the calendar spread.
void SafeLog (Action logAction)
Safely executes logging operation with fault isolation.
Static Private Member Functions
static STDT003A CreateSTDT003A (STPR001AParameters parameters, CRTM005A expiry)
Creates option parameters from calendar spread parameters for a specific expiry.
static STPR001APricing BuildSTPR001APricing (OptionPricing frontPricing, OptionPricing backPricing, double spreadCost, double maxProfit, double breakEven)
Builds STPR001APricing result from option pricings and spread metrics.
static int CalculateDaysToExpiry (CRTM005A valuation, CRTM005A expiry)
Private Attributes
readonly? ILogger< STBR001A > _logger
readonly CREN003A _nativeEngine
bool _disposed
Static Private Attributes
static readonly Action< ILogger, double, double, string, string, PricingRegime, Exception?> LogPricingOption
static readonly Action< ILogger, PricingRegime, string, double, int, int, Exception?> LogPricingSTPR001A
static readonly Action< ILogger, double, Exception?> LogImpliedVolatilityCalculated
static readonly Action< ILogger, Exception?> LogErrorPricing
Detailed Description
Unified pricing engine that automatically selects between Alaris native engines based on interest rate regime. Uses spectral collocation as default for performance.
Definition at line 21 of file STBR001A.cs.
Constructor & Destructor Documentation
STBR001A()
Alaris.Strategy.Bridge.STBR001A.STBR001A (ILogger< STBR001A >? logger = null, SpectralScheme scheme = SpectralScheme::Accurate) inline
Initializes a new instance of the STBR001A with spectral collocation engine.
Parameters
logger Optional logger for diagnostics.
scheme Spectral scheme (Fast/Accurate/HighPrecision). Default: Accurate.
Definition at line 60 of file STBR001A.cs.
References Alaris.Strategy.Bridge.STBR001A._logger, and Alaris.Strategy.Bridge.STBR001A._nativeEngine.
Member Function Documentation
BuildSTPR001APricing()
static STPR001APricing Alaris.Strategy.Bridge.STBR001A.BuildSTPR001APricing (OptionPricing frontPricing, OptionPricing backPricing, double spreadCost, double maxProfit, double breakEven) inline static private
Builds STPR001APricing result from option pricings and spread metrics.
Definition at line 260 of file STBR001A.cs.
References Alaris.Strategy.Pricing.OptionPricing.Delta, Alaris.Strategy.Pricing.OptionPricing.Gamma, Alaris.Strategy.Pricing.OptionPricing.Rho, Alaris.Strategy.Pricing.OptionPricing.Theta, and Alaris.Strategy.Pricing.OptionPricing.Vega.
Referenced by Alaris.Strategy.Bridge.STBR001A.PriceSTPR001A().
CalculateBreakEven()
Task< double > Alaris.Strategy.Bridge.STBR001A.CalculateBreakEven (STPR001AParameters parameters, double spreadCost) inline private
Calculates the break-even point for the calendar spread.
Definition at line 317 of file STBR001A.cs.
References Alaris.Strategy.Bridge.STPR001AParameters.Strike.
Referenced by Alaris.Strategy.Bridge.STBR001A.PriceSTPR001A().
CalculateDaysToExpiry()
static int Alaris.Strategy.Bridge.STBR001A.CalculateDaysToExpiry (CRTM005A valuation, CRTM005A expiry) inline static private
Definition at line 324 of file STBR001A.cs.
Referenced by Alaris.Strategy.Bridge.STBR001A.PriceSTPR001A().
CalculateImpliedVolatility()
Task< double > Alaris.Strategy.Bridge.STBR001A.CalculateImpliedVolatility (double marketPrice, STDT003A parameters) inline
Calculates implied volatility from market price using high-order Householder method.
Implements Alaris.Strategy.Bridge.STBR002A.
Definition at line 214 of file STBR001A.cs.
References Alaris.Strategy.Bridge.STBR001A._logger, Alaris.Core.Math.CRMF001A.BSImpliedVolatility(), Alaris.Strategy.Model.STDT003A.DividendYield, Alaris.Strategy.Bridge.STBR001A.LogImpliedVolatilityCalculated, Alaris.Strategy.Model.STDT003A.OptionType, Alaris.Strategy.Model.STDT003A.RiskFreeRate, Alaris.Strategy.Bridge.STBR001A.SafeLog(), Alaris.Strategy.Model.STDT003A.Strike, Alaris.Strategy.Model.STDT003A.TimeToExpiry(), and Alaris.Strategy.Model.STDT003A.UnderlyingPrice.
Referenced by Alaris.Test.Unit.STBR001ATests.CalculateImpliedVolatility_ConvergesCorrectly().
CalculateMaxProfit()
async Task< double > Alaris.Strategy.Bridge.STBR001A.CalculateMaxProfit (STPR001AParameters parameters, double spreadCost) inline private
Calculates the maximum profit potential of a calendar spread.
Definition at line 287 of file STBR001A.cs.
References Alaris.Core.Time.DayCounters.Actual365Fixed, Alaris.Strategy.Bridge.STPR001AParameters.BackExpiry, Alaris.Strategy.Bridge.STPR001AParameters.DividendYield, Alaris.Strategy.Bridge.STPR001AParameters.FrontExpiry, Alaris.Strategy.Bridge.STPR001AParameters.ImpliedVolatility, Alaris.Strategy.Bridge.STPR001AParameters.OptionType, Alaris.Strategy.Bridge.STBR001A.PriceOption(), Alaris.Strategy.Bridge.STPR001AParameters.RiskFreeRate, Alaris.Strategy.Bridge.STPR001AParameters.Strike, Alaris.Strategy.Bridge.STPR001AParameters.ValuationDate, and Alaris.Core.Time.IDayCounter.YearFraction().
Referenced by Alaris.Strategy.Bridge.STBR001A.PriceSTPR001A().
CreateSTDT003A()
static STDT003A Alaris.Strategy.Bridge.STBR001A.CreateSTDT003A (STPR001AParameters parameters, CRTM005A expiry) inline static private
Creates option parameters from calendar spread parameters for a specific expiry.
Definition at line 242 of file STBR001A.cs.
References Alaris.Strategy.Bridge.STPR001AParameters.DividendYield, Alaris.Strategy.Bridge.STPR001AParameters.ImpliedVolatility, Alaris.Strategy.Bridge.STPR001AParameters.OptionType, Alaris.Strategy.Bridge.STPR001AParameters.RiskFreeRate, Alaris.Strategy.Bridge.STPR001AParameters.Strike, and Alaris.Strategy.Bridge.STPR001AParameters.UnderlyingPrice.
Referenced by Alaris.Strategy.Bridge.STBR001A.PriceSTPR001A().
DetermineRegime()
static PricingRegime Alaris.Strategy.Bridge.STBR001A.DetermineRegime (double riskFreeRate, double dividendYield, bool isCall) inline static
Determines the appropriate pricing regime based on interest rate, dividend yield, and option type.
Definition at line 69 of file STBR001A.cs.
Referenced by Alaris.Test.Unit.STBR001ATests.DetermineRegime_NegativeRatesDoubleBoundary(), Alaris.Test.Unit.STBR001ATests.DetermineRegime_PositiveRates_Standard(), Alaris.Test.Unit.STBR001ATests.DetermineRegime_ReturnsCorrectRegime(), Alaris.Strategy.Bridge.STBR001A.PriceOption(), and Alaris.Strategy.Bridge.STBR001A.PriceSTPR001A().
Dispose()
void Alaris.Strategy.Bridge.STBR001A.Dispose () inline
Disposes resources.
Definition at line 354 of file STBR001A.cs.
References Alaris.Strategy.Bridge.STBR001A._disposed.
Referenced by Alaris.Test.Unit.STBR001ATests.Dispose(), and Alaris.Algorithm.STLN001A.OnEndOfAlgorithm().
PriceOption()
Task< OptionPricing > Alaris.Strategy.Bridge.STBR001A.PriceOption (STDT003A parameters) inline
Prices a single American option using the native pricing engine.
Implements Alaris.Strategy.Bridge.STBR002A.
Definition at line 100 of file STBR001A.cs.
References Alaris.Strategy.Bridge.STBR001A._logger, Alaris.Strategy.Bridge.STBR001A._nativeEngine, Alaris.Core.Pricing.CREN003A.Delta(), Alaris.Strategy.Bridge.STBR001A.DetermineRegime(), Alaris.Strategy.Model.STDT003A.DividendYield, Alaris.Core.Pricing.CREN003A.Gamma(), Alaris.Strategy.Model.STDT003A.ImpliedVolatility, Alaris.Strategy.Bridge.STBR001A.LogErrorPricing, Alaris.Strategy.Bridge.STBR001A.LogPricingOption, Alaris.Strategy.Model.STDT003A.OptionType, Alaris.Core.Pricing.CREN003A.Price(), Alaris.Core.Pricing.CREN003A.Rho(), Alaris.Strategy.Model.STDT003A.RiskFreeRate, Alaris.Strategy.Bridge.STBR001A.SafeLog(), Alaris.Strategy.Model.STDT003A.Strike, Alaris.Core.Pricing.CREN003A.Theta(), Alaris.Strategy.Model.STDT003A.TimeToExpiry(), Alaris.Strategy.Model.STDT003A.UnderlyingPrice, Alaris.Strategy.Model.STDT003A.Validate(), and Alaris.Core.Pricing.CREN003A.Vega().
Referenced by Alaris.Test.Unit.STBR001ATests.CalculateImpliedVolatility_ConvergesCorrectly(), Alaris.Strategy.Bridge.STBR001A.CalculateMaxProfit(), Alaris.Test.Unit.STBR001ATests.PriceOption_NegativeRates_ConsistentAcrossRegimes(), Alaris.Test.Unit.STBR001ATests.PriceOption_NegativeRates_DoubleBoundary_Call(), Alaris.Test.Unit.STBR001ATests.PriceOption_NegativeRates_DoubleBoundary_Put(), Alaris.Test.Unit.STBR001ATests.PriceOption_PositiveRates_ATM_HasHighestGamma(), Alaris.Test.Unit.STBR001ATests.PriceOption_PositiveRates_CallOption(), Alaris.Test.Unit.STBR001ATests.PriceOption_PositiveRates_PutOption(), and Alaris.Strategy.Bridge.STBR001A.PriceSTPR001A().
PriceSTPR001A()
async Task< STPR001APricing > Alaris.Strategy.Bridge.STBR001A.PriceSTPR001A (STPR001AParameters parameters) inline
Prices a calendar spread using the native pricing engine for each leg.
Implements Alaris.Strategy.Bridge.STBR002A.
Definition at line 187 of file STBR001A.cs.
References Alaris.Strategy.Bridge.STBR001A._logger, Alaris.Strategy.Bridge.STPR001AParameters.BackExpiry, Alaris.Strategy.Bridge.STBR001A.BuildSTPR001APricing(), Alaris.Strategy.Bridge.STBR001A.CalculateBreakEven(), Alaris.Strategy.Bridge.STBR001A.CalculateDaysToExpiry(), Alaris.Strategy.Bridge.STBR001A.CalculateMaxProfit(), Alaris.Strategy.Bridge.STBR001A.CreateSTDT003A(), Alaris.Strategy.Bridge.STBR001A.DetermineRegime(), Alaris.Strategy.Bridge.STPR001AParameters.DividendYield, Alaris.Strategy.Bridge.STPR001AParameters.FrontExpiry, Alaris.Strategy.Bridge.STBR001A.LogPricingSTPR001A, Alaris.Strategy.Pricing.OptionPricing.Price, Alaris.Strategy.Bridge.STBR001A.PriceOption(), Alaris.Strategy.Bridge.STPR001AParameters.RiskFreeRate, Alaris.Strategy.Bridge.STBR001A.SafeLog(), Alaris.Strategy.Bridge.STPR001AParameters.Strike, Alaris.Strategy.Bridge.STPR001AParameters.Validate(), and Alaris.Strategy.Bridge.STPR001AParameters.ValuationDate.
Referenced by Alaris.Test.Unit.STBR001ATests.PriceSTPR001A_NegativeRates_ValidSpread(), Alaris.Test.Unit.STBR001ATests.PriceSTPR001A_PositiveRates_CorrectGreeks(), Alaris.Test.Unit.STBR001ATests.PriceSTPR001A_PositiveRates_ValidSpread(), and Alaris.Test.Unit.STBR001ATests.PriceSTPR001A_Validation_Works().
SafeLog()
void Alaris.Strategy.Bridge.STBR001A.SafeLog (Action logAction) inline private
Safely executes logging operation with fault isolation.
Definition at line 332 of file STBR001A.cs.
References Alaris.Strategy.Bridge.STBR001A._logger.
Referenced by Alaris.Strategy.Bridge.STBR001A.CalculateImpliedVolatility(), Alaris.Strategy.Bridge.STBR001A.PriceOption(), and Alaris.Strategy.Bridge.STBR001A.PriceSTPR001A().
Member Data Documentation
_disposed
bool Alaris.Strategy.Bridge.STBR001A._disposed private
Definition at line 25 of file STBR001A.cs.
Referenced by Alaris.Strategy.Bridge.STBR001A.Dispose().
_logger
readonly? ILogger<STBR001A> Alaris.Strategy.Bridge.STBR001A._logger private
Definition at line 23 of file STBR001A.cs.
Referenced by Alaris.Strategy.Bridge.STBR001A.STBR001A(), Alaris.Strategy.Bridge.STBR001A.CalculateImpliedVolatility(), Alaris.Strategy.Bridge.STBR001A.PriceOption(), Alaris.Strategy.Bridge.STBR001A.PriceSTPR001A(), and Alaris.Strategy.Bridge.STBR001A.SafeLog().
_nativeEngine
readonly CREN003A Alaris.Strategy.Bridge.STBR001A._nativeEngine private
Definition at line 24 of file STBR001A.cs.
Referenced by Alaris.Strategy.Bridge.STBR001A.STBR001A(), and Alaris.Strategy.Bridge.STBR001A.PriceOption().
LogErrorPricing
readonly Action<ILogger, Exception?> Alaris.Strategy.Bridge.STBR001A.LogErrorPricing static private
Initial value:
=
        LoggerMessage.Define(
            LogLevel.Error,
            new EventId(4, nameof(LogErrorPricing)),
            "Error pricing option")
Definition at line 46 of file STBR001A.cs.
Referenced by Alaris.Strategy.Bridge.STBR001A.PriceOption().
LogImpliedVolatilityCalculated
readonly Action<ILogger, double, Exception?> Alaris.Strategy.Bridge.STBR001A.LogImpliedVolatilityCalculated static private
Initial value:
=
        LoggerMessage.Define<double>(
            LogLevel.Debug,
            new EventId(3, nameof(LogImpliedVolatilityCalculated)),
            "Implied volatility calculation complete: IV={Iv:F4}")
Definition at line 40 of file STBR001A.cs.
Referenced by Alaris.Strategy.Bridge.STBR001A.CalculateImpliedVolatility().
LogPricingOption
readonly Action<ILogger, double, double, string, string, PricingRegime, Exception?> Alaris.Strategy.Bridge.STBR001A.LogPricingOption static private
Initial value:
=
        LoggerMessage.Define<double, double, string, string, PricingRegime>(
            LogLevel.Debug,
            new EventId(1, nameof(LogPricingOption)),
            "Pricing option: S={UnderlyingPrice}, K={Strike}, Params={Parameters}, Type={OptionType}, Regime={Regime}")
Definition at line 28 of file STBR001A.cs.
Referenced by Alaris.Strategy.Bridge.STBR001A.PriceOption().
LogPricingSTPR001A
readonly Action<ILogger, PricingRegime, string, double, int, int, Exception?> Alaris.Strategy.Bridge.STBR001A.LogPricingSTPR001A static private
Initial value:
=
        LoggerMessage.Define<PricingRegime, string, double, int, int>(
            LogLevel.Information,
            new EventId(2, nameof(LogPricingSTPR001A)),
            "Pricing calendar spread: Regime={Regime}, Type={Type}, Strike={Strike}, Front={FrontDte}, Back={BackDte}")
Definition at line 34 of file STBR001A.cs.
Referenced by Alaris.Strategy.Bridge.STBR001A.PriceSTPR001A().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Bridge/STBR001A.cs