Alaris: Alaris.Strategy.Core Namespace Reference
Alaris.Strategy.Core Namespace Reference
Namespaces
namespace Numerical
Classes
class EarningsJumpCalibration
Results of earnings jump volatility calibration.
class FitMetrics
Fit quality metrics.
class HestonParameters
Heston model parameters.
class KouParameters
Kou model parameters.
class LeungSantoliExtensions
Extension to STIV004A for regime-aware computation.
class MartingaleValidator
Validates martingale conditions for calibrated models. Ensures risk-neutral pricing consistency.
class ModelEvaluation
Evaluation metrics for a single model.
class ModelSelectionContext
Context for model selection.
class ModelSelectionResult
Result of model selection.
class RegimeModelConfig
Configuration for regime-based model behavior.
class STCR001A
Generates trading signals for earnings calendar spread opportunities. Implements the strategy from Atilgan (2014) and incorporates term structure analysis. Enhanced with Leung & Santoli (2014) model for theoretical IV and mispricing signals.
class STCR003A
Implements the Yang-Zhang (2000) realized volatility estimator. This estimator is an efficient method that uses OHLC data and accounts for opening jumps. Formula: RV² = σ_o² + k·σ_c² + (1-k)·σ_rs²
class STCR004A
Represents a trading signal for earnings calendar spread strategy. Based on Atilgan (2014) volatility spread research.
class STCR005A
Monitors signal freshness and detects staleness requiring revalidation.
class STDD001A
Detects dividend ex-dates and evaluates early exercise risk for calendar spreads.
class STEJ001A
Calibrates and evaluates earnings jump risk from historical announcement data.
class STIV001A
Implements the Heston (1993) stochastic volatility model for implied volatility. Stock price dynamics under risk-neutral measure Q: dS/S = (r - d)dt + sqrt(V)*dW_S dV = kappa*(theta - V)dt + sigma_v*sqrt(V)*dW_V corr(dW_S, dW_V) = rho Where: V = instantaneous variance theta = long-run variance (mean reversion level) kappa = mean reversion speed sigma_v = volatility of volatility (vol-of-vol) rho = correlation between stock and variance The model captures:
class STIV002A
Implements the Kou (2002) double-exponential jump-diffusion model for implied volatility. The model extends Black-Scholes with Poisson jumps where jump sizes follow a double-exponential (asymmetric Laplace) distribution, capturing:
class STIV003A
Selects the optimal IV model based on market conditions, fit metrics, and regime. Implements automatic model selection with martingale condition enforcement. Model Selection Criteria:
class STIV004A
Implements the Leung & Santoli (2014) pre-earnings announcement implied volatility model. The model accounts for scheduled earnings jumps in option pricing by incorporating a deterministic-time random jump in the stock price dynamics. The pre-EA implied volatility follows: I(t; K, T) = sqrt(sigma^2 + sigma_e^2 / (T - t)) Where: sigma = base (diffusion) volatility sigma_e = earnings jump volatility (calibrated from historical EA moves) T = option expiration time t = current time (must be before EA date T_e) Reference: "Accounting for Earnings Announcements in the Pricing of Equity Options" Tim Leung & Marco Santoli (2014), Journal of Derivatives.
class STIV005A
Calibrates earnings jump volatility (sigma_e) from historical earnings announcement data. The earnings jump volatility represents the standard deviation of log-returns on earnings announcement dates, as specified in Leung & Santoli (2014). This parameter is crucial for:
class STIV006A
Interpolates implied volatility across strikes using sticky-delta convention.
class STKF001A
Implements a Kalman filter for volatility estimation using Yang-Zhang measurements.
class STPR003A
Production-grade Heston model pricing using characteristic function integration. Implements the semi-analytical pricing formula from Heston (1993). Uses Carr-Madan Fourier inversion or Lewis (2001) approach for option pricing, then backs out implied volatility using Newton-Raphson iteration.
class STPR006A
Production-grade Kou model pricing using characteristic function integration. Implements semi-analytical pricing for double-exponential jump-diffusion model. The Kou (2002) model extends Black-Scholes with asymmetric jumps:
class STTM001A
Analyzes the term structure of implied volatility. Used to identify inverted term structures that signal trading opportunities.
class STTM001AAnalysis
Results of term structure analysis including slope and intercept.
class STTM001APoint
Represents a single point in the implied volatility term structure.
class STTM002A
Handles regime detection and switching around earnings announcements. Determines appropriate model behavior based on proximity to earnings.
class STTM003A
Production-grade trading calendar for calculating business days and market holidays. Supports US market holidays and can be extended for international markets. For production systems, this should be integrated with a market data provider's holiday calendar feed to handle unexpected market closures.
class STTM004A
Comprehensive time parameter specification for IV models. Handles time-to-expiration, earnings dates, and trading calendar conversions.
class TimeConstraints
Constraint specifications for time parameters.
class ValidationResult
Result of constraint validation.
Enumerations
enum STCR004AStrength { Avoid = 0 , Consider = 1 , Recommended = 2 }
STCR004A strength classification for trading decisions.
enum STCR007A { Fresh = 0 , Aging = 1 , Stale = 2 , Expired = 3 }
Signal freshness status.
enum STDD004A {
None = 0 , Low = 1 , Moderate = 2 , Elevated = 3 ,
High = 4
}
Dividend-related early exercise risk levels.
enum STEJ004A { Low = 0 , Moderate = 1 , Elevated = 2 , High = 3 }
Jump risk levels based on tail probability.
enum STIV010A { Low = 0 , Moderate = 1 , Elevated = 2 , High = 3 }
Skew risk levels based on moneyness drift.
enum STTM002AType { NoEarnings , PreEarnings , PostEarningsTransition , PostEarningsNormal }
Defines earnings-related regimes for IV modeling.
enum RecommendedModel {
BlackScholes , Heston , Kou , LeungSantoli ,
PostEarningsBlend , HestonWithEarningsJump
}
Recommended model for a given regime.
Functions
readonly record struct KalmanParameters (double DeltaT, double Phi, double QSigma, double QSigmaDot)
Kalman filter parameters for volatility estimation.
readonly record struct KalmanVolatilityEstimate (double Volatility, double VolatilityDrift, double Variance, double StandardError, double YangZhangRaw, double KalmanGain, double Innovation, double MeasurementNoise)
Represents the Kalman-filtered volatility estimate.
Enumeration Type Documentation
RecommendedModel
enum Alaris.Strategy.Core.RecommendedModel
Recommended model for a given regime.
Enumerator
BlackScholes
Black-Scholes-Merton (simple, no stochastic vol or jumps).
Heston
Heston stochastic volatility model. Best for: normal regimes, volatility clustering.
Kou
Kou double-exponential jump-diffusion. Best for: capturing skew, leptokurtic returns.
LeungSantoli
Leung & Santoli pre-earnings model. Best for: pre-EA regime with deterministic jump timing.
PostEarningsBlend
Blended model for post-earnings transition.
HestonWithEarningsJump
Combined Heston + scheduled jump for pre-EA.
Definition at line 201 of file STTM002A.cs.
STCR004AStrength
enum Alaris.Strategy.Core.STCR004AStrength
STCR004A strength classification for trading decisions.
Enumerator
Avoid
Avoid taking a position - criteria not met.
Consider
Consider taking a position - partial criteria met.
Recommended
Recommended to take a position - all criteria met.
Definition at line 182 of file STCR004A.cs.
STCR007A
enum Alaris.Strategy.Core.STCR007A
Signal freshness status.
Enumerator
Fresh
Freshness >= 80%.
Aging
Freshness 50-80% (approaching stale).
Stale
Freshness 25-50% (needs revalidation).
Expired
Freshness < 25% (expired).
Definition at line 220 of file STCR005A.cs.
STDD004A
enum Alaris.Strategy.Core.STDD004A
Dividend-related early exercise risk levels.
Enumerator
None
No ex-dates in window.
Low
Low early exercise probability.
Moderate
Moderate early exercise probability.
Elevated
Elevated early exercise probability.
High
High early exercise probability - avoid trade.
Definition at line 257 of file STDD001A.cs.
STEJ004A
enum Alaris.Strategy.Core.STEJ004A
Jump risk levels based on tail probability.
Enumerator
Low
Low jump risk - normal distribution.
Moderate
Moderate jump risk - some fat tails.
Elevated
Elevated jump risk - significant fat tails.
High
High jump risk - extreme tails observed.
Definition at line 310 of file STEJ001A.cs.
STIV010A
enum Alaris.Strategy.Core.STIV010A
Skew risk levels based on moneyness drift.
Enumerator
Low
Moneyness within 2% of entry.
Moderate
Moneyness 2-5% from entry.
Elevated
Moneyness 5-10% from entry.
High
Moneyness beyond 10% from entry.
Definition at line 329 of file STIV006A.cs.
STTM002AType
enum Alaris.Strategy.Core.STTM002AType
Defines earnings-related regimes for IV modeling.
Enumerator
NoEarnings
No earnings event before option expiration. Use standard models (BSM, Heston, Kou).
PreEarnings
Pre-earnings announcement regime. IV typically elevated due to anticipated jump. Use L&S model or jump-augmented models.
PostEarningsTransition
Post-earnings announcement regime (0-5 days after). IV typically collapses as uncertainty resolves. Transitional period back to normal.
PostEarningsNormal
Normal regime after earnings effects dissipate. Use standard continuous models.
Definition at line 8 of file STTM002A.cs.
Function Documentation
KalmanParameters()
readonly record struct Alaris.Strategy.Core.KalmanParameters (double DeltaT, double Phi, double QSigma, double QSigmaDot)
Kalman filter parameters for volatility estimation.
Parameters
DeltaT Time step in days (typically 1.0).
Phi Mean-reversion parameter for volatility drift (typically 0.95).
QSigma Process noise variance for volatility shocks.
QSigmaDot Process noise variance for drift changes.
Default parameters for daily equity volatility estimation.
High-frequency parameters (intraday).
Earnings-event parameters (higher uncertainty).
Definition at line 290 of file STKF001A.cs.
References Alaris.Strategy.Core.KalmanParameters().
Referenced by Alaris.Strategy.Core.STKF001A.STKF001A(), and Alaris.Strategy.Core.KalmanParameters().
KalmanVolatilityEstimate()
readonly record struct Alaris.Strategy.Core.KalmanVolatilityEstimate (double Volatility, double VolatilityDrift, double Variance, double StandardError, double YangZhangRaw, double KalmanGain, double Innovation, double MeasurementNoise)
Represents the Kalman-filtered volatility estimate.
Parameters
Volatility Filtered volatility estimate.
VolatilityDrift Estimated rate of change dσ/dt.
Variance Estimation variance P[1,1].
StandardError Square root of variance.
YangZhangRaw Raw Yang-Zhang measurement.
KalmanGain Current Kalman gain (diagnostic).
Innovation z - Hx̂ innovation (diagnostic).
MeasurementNoise Estimated measurement noise R.
Gets whether the raw measurement is within 2σ of the filtered estimate.
Gets the z-score of the innovation.
Definition at line 335 of file STKF001A.cs.
Referenced by Alaris.Strategy.Core.STKF001A.SkipMeasurement(), and Alaris.Strategy.Core.STKF001A.Update().