Alaris: Alaris.Strategy.Calendar.TradingCalendarDefaults Class Reference
Alaris.Strategy.Calendar.TradingCalendarDefaults Class Reference
Default trading calendar provider and utilities.
Static Public Member Functions
static double DteToYears (int daysToExpiry)
Converts days-to-expiry (trading days) to time in years.
static double DteToYears (double daysToExpiry)
Converts days-to-expiry (trading days) to time in years.
static int YearsToDte (double years)
Converts time in years back to trading days.
Static Public Attributes
const double TradingDaysPerYear = 252.0
Trading days per year for annualisation (NYSE standard).
Properties
static ITradingCalendar Instance [get]
Gets the default NYSE trading calendar instance.
Static Private Attributes
static readonly Lazy< ITradingCalendar > LazyInstance
Detailed Description
Default trading calendar provider and utilities.
Definition at line 287 of file STCL001A.cs.
Member Function Documentation
DteToYears() [1/2]
static double Alaris.Strategy.Calendar.TradingCalendarDefaults.DteToYears (double daysToExpiry) inline static
Converts days-to-expiry (trading days) to time in years.
Parameters
daysToExpiry Trading days until expiration (double for API compatibility).
Returns
Time to expiry in years (DTE / 252).
Definition at line 318 of file STCL001A.cs.
References Alaris.Strategy.Calendar.TradingCalendarDefaults.TradingDaysPerYear.
DteToYears() [2/2]
static double Alaris.Strategy.Calendar.TradingCalendarDefaults.DteToYears (int daysToExpiry) inline static
Converts days-to-expiry (trading days) to time in years.
Parameters
daysToExpiry Trading days until expiration.
Returns
Time to expiry in years (DTE / 252).
Definition at line 308 of file STCL001A.cs.
References Alaris.Strategy.Calendar.TradingCalendarDefaults.TradingDaysPerYear.
Referenced by Alaris.Strategy.Core.STIV005A.BaseVolatilityEstimator(), Alaris.Strategy.Core.STIV001A.Calibrate(), Alaris.Strategy.Core.STIV002A.Calibrate(), Alaris.Strategy.Core.STIV001A.ComputeCalibrationError(), Alaris.Strategy.Core.STIV002A.ComputeCalibrationError(), Alaris.Strategy.Core.STIV003A.ComputeModelIVs(), Alaris.Strategy.Core.STIV004A.ComputeSTTM001A(), Alaris.Strategy.Core.STIV001A.ComputeSTTM001A(), Alaris.Strategy.Core.STIV002A.ComputeSTTM001A(), Alaris.Strategy.Core.STCR001A.ComputeTheoreticalMetrics(), Alaris.Test.Unit.TSUN028A.DteToYears_ConvertsCorrectly(), Alaris.Test.Unit.TSUN028A.DteToYearsToDte_RoundTrip_IsIdentity(), Alaris.Strategy.Hedge.STHD009A.EstimateAtmGamma(), and Alaris.Strategy.Core.STIV005A.STTM001AEstimator().
YearsToDte()
static int Alaris.Strategy.Calendar.TradingCalendarDefaults.YearsToDte (double years) inline static
Converts time in years back to trading days.
Parameters
years Time in years.
Returns
Trading days.
Definition at line 328 of file STCL001A.cs.
References Alaris.Strategy.Calendar.TradingCalendarDefaults.TradingDaysPerYear.
Referenced by Alaris.Test.Unit.TSUN028A.DteToYearsToDte_RoundTrip_IsIdentity(), and Alaris.Test.Unit.TSUN028A.YearsToDte_IsInverseOfDteToYears().
Member Data Documentation
LazyInstance
readonly Lazy<ITradingCalendar> Alaris.Strategy.Calendar.TradingCalendarDefaults.LazyInstance static private
Initial value:
= new(
        () => new STCL001A(),
        LazyThreadSafetyMode.ExecutionAndPublication)
Definition at line 289 of file STCL001A.cs.
TradingDaysPerYear
const double Alaris.Strategy.Calendar.TradingCalendarDefaults.TradingDaysPerYear = 252.0 static
Trading days per year for annualisation (NYSE standard).
Definition at line 296 of file STCL001A.cs.
Referenced by Alaris.Strategy.Calendar.TradingCalendarDefaults.DteToYears(), Alaris.Strategy.Calendar.TradingCalendarDefaults.DteToYears(), Alaris.Test.Unit.TSUN028A.TradingDaysPerYear_Is252(), and Alaris.Strategy.Calendar.TradingCalendarDefaults.YearsToDte().
Property Documentation
Instance
ITradingCalendar Alaris.Strategy.Calendar.TradingCalendarDefaults.Instance static get
Gets the default NYSE trading calendar instance.
Definition at line 301 of file STCL001A.cs.
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Calendar/STCL001A.cs