Alaris: Alaris.Test.Unit.Core.Pricing.CRRE001ATests Class Reference
Alaris.Test.Unit.Core.Pricing.CRRE001ATests Class Reference
Unit tests for CRRE001A rate regime classifier. Validates correct regime detection for all three Healy (2021) cases.
Public Member Functions
void Classify_PositiveRates_ReturnsStandard (double r, double q, bool isCall)
void Classify_NegativeRates_WellBehaved_ReturnsStandard (double r, double q, bool isCall)
void Classify_NegativeRates_DoubleBoundary_Put (double r, double q, bool isCall)
void Classify_PositiveRates_DoubleBoundary_Call (double r, double q, bool isCall)
void RequiresDoubleBoundary_DoubleBoundaryCase_ReturnsTrue ()
void RequiresDoubleBoundary_StandardCase_ReturnsFalse ()
void ValidateParameters_ValidRates_ReturnsTrue ()
void ValidateParameters_NaN_ReturnsFalse ()
void ValidateParameters_Infinity_ReturnsFalse ()
void ValidateParameters_ExtremeRates_ReturnsFalse ()
void GetDescription_Standard_ReturnsCorrectString ()
void GetDescription_DoubleBoundary_ReturnsCorrectString ()
Detailed Description
Unit tests for CRRE001A rate regime classifier. Validates correct regime detection for all three Healy (2021) cases.
Definition at line 13 of file CRRE001ATests.cs.
Member Function Documentation
Classify_NegativeRates_DoubleBoundary_Put()
void Alaris.Test.Unit.Core.Pricing.CRRE001ATests.Classify_NegativeRates_DoubleBoundary_Put (double r, double q, bool isCall) inline
Definition at line 53 of file CRRE001ATests.cs.
References Alaris.Core.Pricing.CRRE001A.Classify().
Classify_NegativeRates_WellBehaved_ReturnsStandard()
void Alaris.Test.Unit.Core.Pricing.CRRE001ATests.Classify_NegativeRates_WellBehaved_ReturnsStandard (double r, double q, bool isCall) inline
Definition at line 34 of file CRRE001ATests.cs.
References Alaris.Core.Pricing.CRRE001A.Classify().
Classify_PositiveRates_DoubleBoundary_Call()
void Alaris.Test.Unit.Core.Pricing.CRRE001ATests.Classify_PositiveRates_DoubleBoundary_Call (double r, double q, bool isCall) inline
Definition at line 70 of file CRRE001ATests.cs.
References Alaris.Core.Pricing.CRRE001A.Classify().
Classify_PositiveRates_ReturnsStandard()
void Alaris.Test.Unit.Core.Pricing.CRRE001ATests.Classify_PositiveRates_ReturnsStandard (double r, double q, bool isCall) inline
Definition at line 22 of file CRRE001ATests.cs.
References Alaris.Core.Pricing.CRRE001A.Classify().
GetDescription_DoubleBoundary_ReturnsCorrectString()
void Alaris.Test.Unit.Core.Pricing.CRRE001ATests.GetDescription_DoubleBoundary_ReturnsCorrectString () inline
Definition at line 159 of file CRRE001ATests.cs.
References Alaris.Core.Pricing.CRRE001A.GetDescription().
GetDescription_Standard_ReturnsCorrectString()
void Alaris.Test.Unit.Core.Pricing.CRRE001ATests.GetDescription_Standard_ReturnsCorrectString () inline
Definition at line 152 of file CRRE001ATests.cs.
References Alaris.Core.Pricing.CRRE001A.GetDescription().
RequiresDoubleBoundary_DoubleBoundaryCase_ReturnsTrue()
void Alaris.Test.Unit.Core.Pricing.CRRE001ATests.RequiresDoubleBoundary_DoubleBoundaryCase_ReturnsTrue () inline
Definition at line 88 of file CRRE001ATests.cs.
References Alaris.Core.Pricing.CRRE001A.RequiresDoubleBoundary().
RequiresDoubleBoundary_StandardCase_ReturnsFalse()
void Alaris.Test.Unit.Core.Pricing.CRRE001ATests.RequiresDoubleBoundary_StandardCase_ReturnsFalse () inline
Definition at line 103 of file CRRE001ATests.cs.
References Alaris.Core.Pricing.CRRE001A.RequiresDoubleBoundary().
ValidateParameters_ExtremeRates_ReturnsFalse()
void Alaris.Test.Unit.Core.Pricing.CRRE001ATests.ValidateParameters_ExtremeRates_ReturnsFalse () inline
Definition at line 140 of file CRRE001ATests.cs.
References Alaris.Core.Pricing.CRRE001A.ValidateParameters().
ValidateParameters_Infinity_ReturnsFalse()
void Alaris.Test.Unit.Core.Pricing.CRRE001ATests.ValidateParameters_Infinity_ReturnsFalse () inline
Definition at line 133 of file CRRE001ATests.cs.
References Alaris.Core.Pricing.CRRE001A.ValidateParameters().
ValidateParameters_NaN_ReturnsFalse()
void Alaris.Test.Unit.Core.Pricing.CRRE001ATests.ValidateParameters_NaN_ReturnsFalse () inline
Definition at line 126 of file CRRE001ATests.cs.
References Alaris.Core.Pricing.CRRE001A.ValidateParameters().
ValidateParameters_ValidRates_ReturnsTrue()
void Alaris.Test.Unit.Core.Pricing.CRRE001ATests.ValidateParameters_ValidRates_ReturnsTrue () inline
Definition at line 118 of file CRRE001ATests.cs.
References Alaris.Core.Pricing.CRRE001A.ValidateParameters().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/Core/Pricing/CRRE001ATests.cs