Alaris: Alaris.Infrastructure.Protocol.Workflow.PLWF002A Class Reference
Alaris.Infrastructure.Protocol.Workflow.PLWF002A Class Reference
Factory for creating the Backtest workflow FSM. Component ID: PLWF002A.
Static Public Member Functions
static PLWF001A< BacktestState, BacktestEvent > Create ()
Creates a new Backtest workflow FSM with all transitions defined.
static PLWF001A< BacktestState, BacktestEvent > CreateWithActions (Action? onDataMissing=null, Action? onBootstrapComplete=null, Action? onLeanCompleted=null, Action? onLeanFailed=null)
Creates a Backtest FSM with custom actions attached to transitions.
Detailed Description
Factory for creating the Backtest workflow FSM. Component ID: PLWF002A.
This factory creates a fully-configured FSM for the backtest workflow. The FSM enforces valid state transitions and provides guards for precondition validation.
Definition at line 118 of file PLWF002A.cs.
Member Function Documentation
Create()
static PLWF001A< BacktestState, BacktestEvent > Alaris.Infrastructure.Protocol.Workflow.PLWF002A.Create () inline static
Creates a new Backtest workflow FSM with all transitions defined.
Returns
A configured FSM instance starting in Idle state.
Definition at line 124 of file PLWF002A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition().
Referenced by Alaris.Test.Unit.TSUN051A.BacktestWorkflow_BootstrapFails_ReachesFailed(), Alaris.Test.Unit.TSUN051A.BacktestWorkflow_DataMissing_BootstrapsAndRetries(), Alaris.Test.Unit.TSUN051A.BacktestWorkflow_HappyPath_ReachesCompleted(), Alaris.Test.Unit.TSUN051A.BacktestWorkflow_Reset_ReturnsToIdle(), Alaris.Host.Application.Command.BacktestRunCommand.ExecuteAsync(), Alaris.Test.Unit.TSUN051A.GetStatistics_ReturnsCorrectCounts(), and Alaris.Test.Unit.TSUN051A.Validate_ValidFSM_ReturnsEmpty().
CreateWithActions()
static PLWF001A< BacktestState, BacktestEvent > Alaris.Infrastructure.Protocol.Workflow.PLWF002A.CreateWithActions (Action? onDataMissing = null, Action? onBootstrapComplete = null, Action? onLeanCompleted = null, Action? onLeanFailed = null) inline static
Creates a Backtest FSM with custom actions attached to transitions.
Parameters
onDataMissing Action when data is detected as missing.
onBootstrapComplete Action when bootstrap succeeds.
onLeanCompleted Action when LEAN execution completes.
onLeanFailed Action when LEAN execution fails.
Returns
A configured FSM with actions.
Definition at line 200 of file PLWF002A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition().
The documentation for this class was generated from the following file:
src/Alaris.Infrastructure/Protocol/Workflow/PLWF002A.cs