Alaris: Alaris.Test.Unit.TSUN033A Class Reference
Alaris.Test.Unit.TSUN033A Class Reference sealed
TSUN033A: Unit tests for persistent event stores (EVIF001B, EVIF002B).
Public Member Functions
TSUN033A ()
void Dispose ()
async Task EVIF001B_AppendAsync_PersistsEvent ()
Append and retrieve event successfully.
async Task EVIF001B_AppendAsync_IncrementsSequence ()
Sequence numbers increment correctly.
async Task EVIF001B_GetEventsForAggregateAsync_FiltersCorrectly ()
Get events by aggregate ID.
async Task EVIF001B_RecoverSequence_AfterRestart ()
Sequence persists across store instances (crash recovery).
async Task EVIF001B_GetEventsFromSequenceAsync_ReturnsFromSequence ()
Get events from sequence number.
async Task EVIF002B_LogAsync_PersistsEntry ()
Log and retrieve audit entry.
async Task EVIF002B_GetEntriesByInitiatorAsync_FiltersCorrectly ()
Filter by initiator.
async Task EVIF002B_GetEntriesByTimeRangeAsync_FiltersCorrectly ()
Filter by time range.
async Task EVIF002B_LogAsync_NullEntry_Throws ()
Guard clause: null entry throws.
Properties
Guid EventId = Guid.NewGuid() [get]
DateTime OccurredAtUtc = DateTime.UtcNow [get]
string EventType [get]
string? CorrelationId [get]
Private Member Functions
void Dispose (bool disposing)
Static Private Member Functions
static AuditEntry CreateAuditEntry (string entityType, string entityId, string action, string initiatedBy)
Private Attributes
readonly string _testStoragePath
readonly string _eventsStoragePath
readonly string _auditStoragePath
bool _disposed
record TestEvent: EVCR001A { public required string Message { get
Test event for unit tests.
init
Detailed Description
TSUN033A: Unit tests for persistent event stores (EVIF001B, EVIF002B).
Definition at line 21 of file TSUN033A.cs.
Constructor & Destructor Documentation
TSUN033A()
Alaris.Test.Unit.TSUN033A.TSUN033A () inline
Definition at line 28 of file TSUN033A.cs.
References Alaris.Test.Unit.TSUN033A._auditStoragePath, Alaris.Test.Unit.TSUN033A._eventsStoragePath, and Alaris.Test.Unit.TSUN033A._testStoragePath.
Member Function Documentation
CreateAuditEntry()
static AuditEntry Alaris.Test.Unit.TSUN033A.CreateAuditEntry (string entityType, string entityId, string action, string initiatedBy) inline static private
Definition at line 295 of file TSUN033A.cs.
References Alaris.Infrastructure.Events.Core.AuditEntry, and Alaris.Test.Unit.TSUN033A.OccurredAtUtc.
Referenced by Alaris.Test.Unit.TSUN033A.EVIF002B_GetEntriesByInitiatorAsync_FiltersCorrectly(), Alaris.Test.Unit.TSUN033A.EVIF002B_GetEntriesByTimeRangeAsync_FiltersCorrectly(), and Alaris.Test.Unit.TSUN033A.EVIF002B_LogAsync_PersistsEntry().
Dispose() [1/2]
void Alaris.Test.Unit.TSUN033A.Dispose () inline
Definition at line 36 of file TSUN033A.cs.
References Alaris.Test.Unit.TSUN033A.Dispose().
Referenced by Alaris.Test.Unit.TSUN033A.Dispose().
Dispose() [2/2]
void Alaris.Test.Unit.TSUN033A.Dispose (bool disposing) inline private
Definition at line 42 of file TSUN033A.cs.
References Alaris.Test.Unit.TSUN033A._disposed, and Alaris.Test.Unit.TSUN033A._testStoragePath.
EVIF001B_AppendAsync_IncrementsSequence()
async Task Alaris.Test.Unit.TSUN033A.EVIF001B_AppendAsync_IncrementsSequence () inline
Sequence numbers increment correctly.
Definition at line 89 of file TSUN033A.cs.
References Alaris.Test.Unit.TSUN033A._eventsStoragePath, Alaris.Infrastructure.Events.Core.EVCR003A, and Alaris.Test.Unit.TSUN033A.TestEvent.
EVIF001B_AppendAsync_PersistsEvent()
async Task Alaris.Test.Unit.TSUN033A.EVIF001B_AppendAsync_PersistsEvent () inline
Append and retrieve event successfully.
Definition at line 61 of file TSUN033A.cs.
References Alaris.Test.Unit.TSUN033A._eventsStoragePath, Alaris.Infrastructure.Events.Core.EVCR003A, and Alaris.Test.Unit.TSUN033A.TestEvent.
EVIF001B_GetEventsForAggregateAsync_FiltersCorrectly()
async Task Alaris.Test.Unit.TSUN033A.EVIF001B_GetEventsForAggregateAsync_FiltersCorrectly () inline
Get events by aggregate ID.
Definition at line 115 of file TSUN033A.cs.
References Alaris.Test.Unit.TSUN033A._eventsStoragePath, Alaris.Infrastructure.Events.Infrastructure.EVIF001B.GetEventsForAggregateAsync(), and Alaris.Test.Unit.TSUN033A.TestEvent.
EVIF001B_GetEventsFromSequenceAsync_ReturnsFromSequence()
async Task Alaris.Test.Unit.TSUN033A.EVIF001B_GetEventsFromSequenceAsync_ReturnsFromSequence () inline
Get events from sequence number.
Definition at line 171 of file TSUN033A.cs.
References Alaris.Test.Unit.TSUN033A._eventsStoragePath, Alaris.Infrastructure.Events.Infrastructure.EVIF001B.GetEventsFromSequenceAsync(), and Alaris.Test.Unit.TSUN033A.TestEvent.
EVIF001B_RecoverSequence_AfterRestart()
async Task Alaris.Test.Unit.TSUN033A.EVIF001B_RecoverSequence_AfterRestart () inline
Sequence persists across store instances (crash recovery).
Definition at line 141 of file TSUN033A.cs.
References Alaris.Test.Unit.TSUN033A._eventsStoragePath, Alaris.Infrastructure.Events.Core.EVCR003A, Alaris.Infrastructure.Events.Infrastructure.EVIF001B.GetCurrentSequenceNumberAsync(), and Alaris.Test.Unit.TSUN033A.TestEvent.
EVIF002B_GetEntriesByInitiatorAsync_FiltersCorrectly()
async Task Alaris.Test.Unit.TSUN033A.EVIF002B_GetEntriesByInitiatorAsync_FiltersCorrectly () inline
Filter by initiator.
Definition at line 226 of file TSUN033A.cs.
References Alaris.Test.Unit.TSUN033A._auditStoragePath, Alaris.Test.Unit.TSUN033A.CreateAuditEntry(), and Alaris.Infrastructure.Events.Infrastructure.EVIF002B.LogAsync().
EVIF002B_GetEntriesByTimeRangeAsync_FiltersCorrectly()
async Task Alaris.Test.Unit.TSUN033A.EVIF002B_GetEntriesByTimeRangeAsync_FiltersCorrectly () inline
Filter by time range.
Definition at line 252 of file TSUN033A.cs.
References Alaris.Test.Unit.TSUN033A._auditStoragePath, Alaris.Test.Unit.TSUN033A.CreateAuditEntry(), and Alaris.Infrastructure.Events.Infrastructure.EVIF002B.LogAsync().
EVIF002B_LogAsync_NullEntry_Throws()
async Task Alaris.Test.Unit.TSUN033A.EVIF002B_LogAsync_NullEntry_Throws () inline
Guard clause: null entry throws.
Definition at line 279 of file TSUN033A.cs.
References Alaris.Test.Unit.TSUN033A._auditStoragePath.
EVIF002B_LogAsync_PersistsEntry()
async Task Alaris.Test.Unit.TSUN033A.EVIF002B_LogAsync_PersistsEntry () inline
Log and retrieve audit entry.
Definition at line 200 of file TSUN033A.cs.
References Alaris.Test.Unit.TSUN033A._auditStoragePath, Alaris.Infrastructure.Events.Core.AuditEntry, and Alaris.Test.Unit.TSUN033A.CreateAuditEntry().
Member Data Documentation
_auditStoragePath
readonly string Alaris.Test.Unit.TSUN033A._auditStoragePath private
Definition at line 25 of file TSUN033A.cs.
Referenced by Alaris.Test.Unit.TSUN033A.TSUN033A(), Alaris.Test.Unit.TSUN033A.EVIF002B_GetEntriesByInitiatorAsync_FiltersCorrectly(), Alaris.Test.Unit.TSUN033A.EVIF002B_GetEntriesByTimeRangeAsync_FiltersCorrectly(), Alaris.Test.Unit.TSUN033A.EVIF002B_LogAsync_NullEntry_Throws(), and Alaris.Test.Unit.TSUN033A.EVIF002B_LogAsync_PersistsEntry().
_disposed
bool Alaris.Test.Unit.TSUN033A._disposed private
Definition at line 26 of file TSUN033A.cs.
Referenced by Alaris.Test.Unit.TSUN033A.Dispose().
_eventsStoragePath
readonly string Alaris.Test.Unit.TSUN033A._eventsStoragePath private
Definition at line 24 of file TSUN033A.cs.
Referenced by Alaris.Test.Unit.TSUN033A.TSUN033A(), Alaris.Test.Unit.TSUN033A.EVIF001B_AppendAsync_IncrementsSequence(), Alaris.Test.Unit.TSUN033A.EVIF001B_AppendAsync_PersistsEvent(), Alaris.Test.Unit.TSUN033A.EVIF001B_GetEventsForAggregateAsync_FiltersCorrectly(), Alaris.Test.Unit.TSUN033A.EVIF001B_GetEventsFromSequenceAsync_ReturnsFromSequence(), and Alaris.Test.Unit.TSUN033A.EVIF001B_RecoverSequence_AfterRestart().
_testStoragePath
readonly string Alaris.Test.Unit.TSUN033A._testStoragePath private
Definition at line 23 of file TSUN033A.cs.
Referenced by Alaris.Test.Unit.TSUN033A.TSUN033A(), and Alaris.Test.Unit.TSUN033A.Dispose().
init
Alaris.Test.Unit.TSUN033A.init private
Definition at line 317 of file TSUN033A.cs.
TestEvent
record Alaris.Test.Unit.TSUN033A.TestEvent sealed private
Test event for unit tests.
Definition at line 315 of file TSUN033A.cs.
Referenced by Alaris.Test.Unit.TSUN033A.EVIF001B_AppendAsync_IncrementsSequence(), Alaris.Test.Unit.TSUN033A.EVIF001B_AppendAsync_PersistsEvent(), Alaris.Test.Unit.TSUN033A.EVIF001B_GetEventsForAggregateAsync_FiltersCorrectly(), Alaris.Test.Unit.TSUN033A.EVIF001B_GetEventsFromSequenceAsync_ReturnsFromSequence(), and Alaris.Test.Unit.TSUN033A.EVIF001B_RecoverSequence_AfterRestart().
Property Documentation
CorrelationId
string? Alaris.Test.Unit.TSUN033A.CorrelationId get
Definition at line 321 of file TSUN033A.cs.
EventId
Guid Alaris.Test.Unit.TSUN033A.EventId = Guid.NewGuid() get
Definition at line 318 of file TSUN033A.cs.
EventType
string Alaris.Test.Unit.TSUN033A.EventType get
Definition at line 320 of file TSUN033A.cs.
OccurredAtUtc
DateTime Alaris.Test.Unit.TSUN033A.OccurredAtUtc = DateTime.UtcNow get
Definition at line 319 of file TSUN033A.cs.
Referenced by Alaris.Test.Unit.TSUN033A.CreateAuditEntry().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN033A.cs