Alaris: Alaris.Strategy.Core.STDD001A Class Reference
Alaris.Strategy.Core.STDD001A Class Reference sealed
Detects dividend ex-dates and evaluates early exercise risk for calendar spreads.
Public Member Functions
STDD001A (ILogger< STDD001A >? logger=null)
Initialises a new instance of the dividend date detector.
IReadOnlyList< STDD002A > FindExDatesInWindow (IReadOnlyList< STDD002A > dividendSchedule, DateTime windowStart, DateTime windowEnd)
Finds dividend ex-dates within a specified window.
double CalculateEarlyExerciseRisk (double dividendAmount, double strike, double riskFreeRate, double timeFromExToExpiry)
Calculates early exercise probability for American call near ex-date.
STDD003A EvaluateDividendRisk (IReadOnlyList< STDD002A > dividendSchedule, double spotPrice, double strike, DateTime shortLegExpiry, DateTime earningsDate, double riskFreeRate)
Evaluates dividend risk for a calendar spread position.
Private Member Functions
void SafeLog (Action logAction)
Safely executes logging operation with fault isolation.
Private Attributes
readonly? ILogger< STDD001A > _logger
Static Private Attributes
static readonly Action< ILogger, DateTime, double, double, Exception?> LogExDateDetected
Detailed Description
Detects dividend ex-dates and evaluates early exercise risk for calendar spreads.
Definition at line 11 of file STDD001A.cs.
Constructor & Destructor Documentation
STDD001A()
Alaris.Strategy.Core.STDD001A.STDD001A (ILogger< STDD001A >? logger = null) inline
Initialises a new instance of the dividend date detector.
Parameters
logger Optional logger instance.
Definition at line 26 of file STDD001A.cs.
References Alaris.Strategy.Core.STDD001A._logger.
Member Function Documentation
CalculateEarlyExerciseRisk()
double Alaris.Strategy.Core.STDD001A.CalculateEarlyExerciseRisk (double dividendAmount, double strike, double riskFreeRate, double timeFromExToExpiry) inline
Calculates early exercise probability for American call near ex-date.
Parameters
dividendAmount Dividend amount per share.
strike Option strike price.
riskFreeRate Risk-free interest rate (annualised).
timeFromExToExpiry Time from ex-date to option expiry (years).
Returns
Early exercise risk score (0-1).
Definition at line 60 of file STDD001A.cs.
Referenced by Alaris.Strategy.Core.STDD001A.EvaluateDividendRisk(), Alaris.Test.Unit.Phase2MediumPriorityTests.STDD001A_CalculateEarlyExerciseRisk_HighDividend_ReturnsHighRisk(), and Alaris.Test.Unit.Phase2MediumPriorityTests.STDD001A_CalculateEarlyExerciseRisk_NoDividend_ReturnsZero().
EvaluateDividendRisk()
STDD003A Alaris.Strategy.Core.STDD001A.EvaluateDividendRisk (IReadOnlyList< STDD002A > dividendSchedule, double spotPrice, double strike, DateTime shortLegExpiry, DateTime earningsDate, double riskFreeRate) inline
Evaluates dividend risk for a calendar spread position.
Parameters
dividendSchedule Known dividend events.
spotPrice Current spot price.
strike Strike price.
shortLegExpiry Short leg expiration date.
earningsDate Earnings announcement date.
riskFreeRate Risk-free rate.
Returns
Dividend risk evaluation result.
Definition at line 101 of file STDD001A.cs.
References Alaris.Strategy.Core.STDD001A._logger, Alaris.Strategy.Core.STDD001A.CalculateEarlyExerciseRisk(), Alaris.Strategy.Core.STDD001A.FindExDatesInWindow(), Alaris.Strategy.Core.STDD001A.LogExDateDetected, Alaris.Strategy.Core.STDD001A.SafeLog(), Alaris.Strategy.Core.STDD002A, and Alaris.Strategy.Core.STDD003A.
FindExDatesInWindow()
IReadOnlyList< STDD002A > Alaris.Strategy.Core.STDD001A.FindExDatesInWindow (IReadOnlyList< STDD002A > dividendSchedule, DateTime windowStart, DateTime windowEnd) inline
Finds dividend ex-dates within a specified window.
Parameters
dividendSchedule List of known dividend events.
windowStart Start of the earnings window.
windowEnd End of the earnings window.
Returns
List of ex-dates within the window.
Definition at line 38 of file STDD001A.cs.
Referenced by Alaris.Strategy.Core.STDD001A.EvaluateDividendRisk(), and Alaris.Test.Unit.Phase2MediumPriorityTests.STDD001A_FindExDatesInWindow_ReturnsMatchingDates().
SafeLog()
void Alaris.Strategy.Core.STDD001A.SafeLog (Action logAction) inline private
Safely executes logging operation with fault isolation.
Definition at line 190 of file STDD001A.cs.
References Alaris.Strategy.Core.STDD001A._logger.
Referenced by Alaris.Strategy.Core.STDD001A.EvaluateDividendRisk().
Member Data Documentation
_logger
readonly? ILogger<STDD001A> Alaris.Strategy.Core.STDD001A._logger private
Definition at line 13 of file STDD001A.cs.
Referenced by Alaris.Strategy.Core.STDD001A.STDD001A(), Alaris.Strategy.Core.STDD001A.EvaluateDividendRisk(), and Alaris.Strategy.Core.STDD001A.SafeLog().
LogExDateDetected
readonly Action<ILogger, DateTime, double, double, Exception?> Alaris.Strategy.Core.STDD001A.LogExDateDetected static private
Initial value:
=
        LoggerMessage.Define<DateTime, double, double>(
            LogLevel.Warning,
            new EventId(1, nameof(LogExDateDetected)),
            "Ex-date detected: {ExDate}, Dividend={Dividend:F2}, EarlyExerciseRisk={Risk:P1}")
Definition at line 16 of file STDD001A.cs.
Referenced by Alaris.Strategy.Core.STDD001A.EvaluateDividendRisk().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Core/STDD001A.cs