Alaris: Alaris.Test.Unit.STIV004ATests Class Reference
Alaris.Test.Unit.STIV004ATests Class Reference
Unit tests for STIV004A. Tests mathematical correctness of the L&S (2014) pre-EA implied volatility model.
Public Member Functions
void ComputeTheoreticalIV_WhenNoEarningsJump_ReturnsBaseVolatility ()
void ComputeTheoreticalIV_WhenEarningsJumpPresent_IVIsHigher ()
void ComputeTheoreticalIV_DecreasesWithTimeToExpiry (double timeToExpiry)
void ComputeTheoreticalIV_MatchesLeungSantoliFormula ()
void ComputeTheoreticalIV_ThrowsOnNegativeBaseVolatility ()
void ComputeTheoreticalIV_ThrowsOnNegativeEarningsJump ()
void ComputeTheoreticalIV_ThrowsOnZeroOrNegativeTimeToExpiry ()
void ComputeMispricingSTCR004A_PositiveWhenMarketIVHigher ()
void ComputeMispricingSTCR004A_NegativeWhenMarketIVLower ()
void ComputeExpectedIVCrush_IsPositiveWithEarningsJump ()
void ComputeExpectedIVCrush_IncreasesAsExpiryApproaches ()
void ComputeIVCrushRatio_IsBetweenZeroAndOne ()
void ExtractEarningsJumpVolatility_RecoversOriginalSigmaE ()
void ExtractEarningsJumpVolatility_ReturnsZeroWhenIVBelowBase ()
void ComputeSTTM001A_ProducesInvertedStructure ()
void ComputeSTTM001A_ConvergesToBaseVolatility ()
Detailed Description
Unit tests for STIV004A. Tests mathematical correctness of the L&S (2014) pre-EA implied volatility model.
Reference: "Accounting for Earnings Announcements in the Pricing of Equity Options" Tim Leung & Marco Santoli (2014)
Definition at line 15 of file TSUN008A.cs.
Member Function Documentation
ComputeExpectedIVCrush_IncreasesAsExpiryApproaches()
void Alaris.Test.Unit.STIV004ATests.ComputeExpectedIVCrush_IncreasesAsExpiryApproaches () inline
Definition at line 185 of file TSUN008A.cs.
References Alaris.Strategy.Core.STIV004A.ComputeExpectedIVCrush().
ComputeExpectedIVCrush_IsPositiveWithEarningsJump()
void Alaris.Test.Unit.STIV004ATests.ComputeExpectedIVCrush_IsPositiveWithEarningsJump () inline
Definition at line 170 of file TSUN008A.cs.
References Alaris.Strategy.Core.STIV004A.ComputeExpectedIVCrush().
ComputeIVCrushRatio_IsBetweenZeroAndOne()
void Alaris.Test.Unit.STIV004ATests.ComputeIVCrushRatio_IsBetweenZeroAndOne () inline
Definition at line 204 of file TSUN008A.cs.
References Alaris.Strategy.Core.STIV004A.ComputeIVCrushRatio().
ComputeMispricingSTCR004A_NegativeWhenMarketIVLower()
void Alaris.Test.Unit.STIV004ATests.ComputeMispricingSTCR004A_NegativeWhenMarketIVLower () inline
Definition at line 145 of file TSUN008A.cs.
References Alaris.Strategy.Core.STIV004A.ComputeMispricingSTCR004A(), and Alaris.Strategy.Core.STIV004A.ComputeTheoreticalIV().
ComputeMispricingSTCR004A_PositiveWhenMarketIVHigher()
void Alaris.Test.Unit.STIV004ATests.ComputeMispricingSTCR004A_PositiveWhenMarketIVHigher () inline
Definition at line 127 of file TSUN008A.cs.
References Alaris.Strategy.Core.STIV004A.ComputeMispricingSTCR004A().
ComputeSTTM001A_ConvergesToBaseVolatility()
void Alaris.Test.Unit.STIV004ATests.ComputeSTTM001A_ConvergesToBaseVolatility () inline
Definition at line 281 of file TSUN008A.cs.
References Alaris.Strategy.Core.STIV004A.ComputeSTTM001A().
ComputeSTTM001A_ProducesInvertedStructure()
void Alaris.Test.Unit.STIV004ATests.ComputeSTTM001A_ProducesInvertedStructure () inline
Definition at line 259 of file TSUN008A.cs.
References Alaris.Strategy.Core.STIV004A.ComputeSTTM001A().
ComputeTheoreticalIV_DecreasesWithTimeToExpiry()
void Alaris.Test.Unit.STIV004ATests.ComputeTheoreticalIV_DecreasesWithTimeToExpiry (double timeToExpiry) inline
Definition at line 56 of file TSUN008A.cs.
References Alaris.Strategy.Core.STIV004A.ComputeTheoreticalIV().
ComputeTheoreticalIV_MatchesLeungSantoliFormula()
void Alaris.Test.Unit.STIV004ATests.ComputeTheoreticalIV_MatchesLeungSantoliFormula () inline
Definition at line 74 of file TSUN008A.cs.
References Alaris.Strategy.Core.STIV004A.ComputeTheoreticalIV().
ComputeTheoreticalIV_ThrowsOnNegativeBaseVolatility()
void Alaris.Test.Unit.STIV004ATests.ComputeTheoreticalIV_ThrowsOnNegativeBaseVolatility () inline
Definition at line 94 of file TSUN008A.cs.
References Alaris.Strategy.Core.STIV004A.ComputeTheoreticalIV().
ComputeTheoreticalIV_ThrowsOnNegativeEarningsJump()
void Alaris.Test.Unit.STIV004ATests.ComputeTheoreticalIV_ThrowsOnNegativeEarningsJump () inline
Definition at line 103 of file TSUN008A.cs.
References Alaris.Strategy.Core.STIV004A.ComputeTheoreticalIV().
ComputeTheoreticalIV_ThrowsOnZeroOrNegativeTimeToExpiry()
void Alaris.Test.Unit.STIV004ATests.ComputeTheoreticalIV_ThrowsOnZeroOrNegativeTimeToExpiry () inline
Definition at line 112 of file TSUN008A.cs.
References Alaris.Strategy.Core.STIV004A.ComputeTheoreticalIV().
ComputeTheoreticalIV_WhenEarningsJumpPresent_IVIsHigher()
void Alaris.Test.Unit.STIV004ATests.ComputeTheoreticalIV_WhenEarningsJumpPresent_IVIsHigher () inline
Definition at line 36 of file TSUN008A.cs.
References Alaris.Strategy.Core.STIV004A.ComputeTheoreticalIV().
ComputeTheoreticalIV_WhenNoEarningsJump_ReturnsBaseVolatility()
void Alaris.Test.Unit.STIV004ATests.ComputeTheoreticalIV_WhenNoEarningsJump_ReturnsBaseVolatility () inline
Definition at line 20 of file TSUN008A.cs.
References Alaris.Strategy.Core.STIV004A.ComputeTheoreticalIV().
ExtractEarningsJumpVolatility_RecoversOriginalSigmaE()
void Alaris.Test.Unit.STIV004ATests.ExtractEarningsJumpVolatility_RecoversOriginalSigmaE () inline
Definition at line 221 of file TSUN008A.cs.
References Alaris.Strategy.Core.STIV004A.ComputeTheoreticalIV(), and Alaris.Strategy.Core.STIV004A.ExtractEarningsJumpVolatility().
ExtractEarningsJumpVolatility_ReturnsZeroWhenIVBelowBase()
void Alaris.Test.Unit.STIV004ATests.ExtractEarningsJumpVolatility_ReturnsZeroWhenIVBelowBase () inline
Definition at line 241 of file TSUN008A.cs.
References Alaris.Strategy.Core.STIV004A.ExtractEarningsJumpVolatility().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN008A.cs