Alaris: Alaris.Infrastructure.Events.Infrastructure.EVIF002A Class Reference
Alaris.Infrastructure.Events.Infrastructure.EVIF002A Class Reference sealed
In-memory implementation of EVCR004A for development and testing. NOT suitable for production use - audit logs are lost on process restart.
Public Member Functions
Task LogAsync (AuditEntry entry, CancellationToken cancellationToken=default)
Logs an audit entry for a system action.
Task< IReadOnlyList< AuditEntry > > GetEntriesForEntityAsync (string entityType, string entityId, CancellationToken cancellationToken=default)
Retrieves audit entries for a specific entity.
Task< IReadOnlyList< AuditEntry > > GetEntriesByInitiatorAsync (string initiatedBy, CancellationToken cancellationToken=default)
Retrieves audit entries initiated by a specific user or system.
Task< IReadOnlyList< AuditEntry > > GetEntriesByTimeRangeAsync (DateTime fromUtc, DateTime toUtc, CancellationToken cancellationToken=default)
Retrieves audit entries within a time range.
Private Attributes
readonly ConcurrentBag< AuditEntry > _entries = new()
Detailed Description
In-memory implementation of EVCR004A for development and testing. NOT suitable for production use - audit logs are lost on process restart.
For production, implement a persistent store using:
SQL database with append-only table
Dedicated audit log service
File-based append-only logs with rotation
Definition at line 16 of file EVIF002A.cs.
Member Function Documentation
GetEntriesByInitiatorAsync()
Task< IReadOnlyList< AuditEntry > > Alaris.Infrastructure.Events.Infrastructure.EVIF002A.GetEntriesByInitiatorAsync (string initiatedBy, CancellationToken cancellationToken = default) inline
Retrieves audit entries initiated by a specific user or system.
Parameters
initiatedBy The user or system identifier.
cancellationToken Cancellation token.
Returns
All audit entries initiated by the specified actor.
Implements Alaris.Infrastructure.Events.Core.EVCR004A.
Definition at line 39 of file EVIF002A.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF002A._entries.
GetEntriesByTimeRangeAsync()
Task< IReadOnlyList< AuditEntry > > Alaris.Infrastructure.Events.Infrastructure.EVIF002A.GetEntriesByTimeRangeAsync (DateTime fromUtc, DateTime toUtc, CancellationToken cancellationToken = default) inline
Retrieves audit entries within a time range.
Parameters
fromUtc Start time (inclusive).
toUtc End time (inclusive).
cancellationToken Cancellation token.
Returns
Audit entries within the time range.
Implements Alaris.Infrastructure.Events.Core.EVCR004A.
Definition at line 51 of file EVIF002A.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF002A._entries.
GetEntriesForEntityAsync()
Task< IReadOnlyList< AuditEntry > > Alaris.Infrastructure.Events.Infrastructure.EVIF002A.GetEntriesForEntityAsync (string entityType, string entityId, CancellationToken cancellationToken = default) inline
Retrieves audit entries for a specific entity.
Parameters
entityType The type of entity.
entityId The entity identifier.
cancellationToken Cancellation token.
Returns
All audit entries for the entity.
Implements Alaris.Infrastructure.Events.Core.EVCR004A.
Definition at line 26 of file EVIF002A.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF002A._entries.
LogAsync()
Task Alaris.Infrastructure.Events.Infrastructure.EVIF002A.LogAsync (AuditEntry entry, CancellationToken cancellationToken = default) inline
Logs an audit entry for a system action.
Parameters
entry The audit entry to log.
cancellationToken Cancellation token.
Implements Alaris.Infrastructure.Events.Core.EVCR004A.
Definition at line 20 of file EVIF002A.cs.
References Alaris.Infrastructure.Events.Infrastructure.EVIF002A._entries.
Referenced by Alaris.Algorithm.STLN001A.EvaluatePositions(), and Alaris.Algorithm.STLN001A.EvaluateSnapshot().
Member Data Documentation
_entries
readonly ConcurrentBag<AuditEntry> Alaris.Infrastructure.Events.Infrastructure.EVIF002A._entries = new() private
Definition at line 18 of file EVIF002A.cs.
Referenced by Alaris.Infrastructure.Events.Infrastructure.EVIF002A.GetEntriesByInitiatorAsync(), Alaris.Infrastructure.Events.Infrastructure.EVIF002A.GetEntriesByTimeRangeAsync(), Alaris.Infrastructure.Events.Infrastructure.EVIF002A.GetEntriesForEntityAsync(), and Alaris.Infrastructure.Events.Infrastructure.EVIF002A.LogAsync().
The documentation for this class was generated from the following file:
src/Alaris.Infrastructure/Events/Infrastructure/EVIF002A.cs