Alaris: Alaris.Host.Application.Command.APcm004A Class Reference
Alaris.Host.Application.Command.APcm004A Class Reference sealed
Alaris Universe Command - generate and manage universe files. Component ID: APcm004A.
Public Member Functions
override int Execute (CommandContext context, UniverseSettings settings)
Static Private Member Functions
static int GenerateUniverse (UniverseSettings settings)
static bool int? string error GenerateUniverseForDate (DateTime date, string apiKey, string outputDir, decimal minDollarVolume, decimal minPrice)
static string GetSymbolId (string ticker)
static List< DateTime > GetTradingDays (DateTime start, DateTime end)
static int ListUniverseFiles ()
static int ShowUniverseInfo ()
static int InvalidAction (string action)
static ? string FindDataPath ()
static string FindOrCreateDataPath ()
static ? string GetPolygonApiKey ()
static string FormatSize (long bytes)
Static Private Attributes
static bool success
static bool int stockCount
Detailed Description
Alaris Universe Command - generate and manage universe files. Component ID: APcm004A.
Definition at line 46 of file APcm004A.cs.
Member Function Documentation
Execute()
override int Alaris.Host.Application.Command.APcm004A.Execute (CommandContext context, UniverseSettings settings) inline
Definition at line 48 of file APcm004A.cs.
References Alaris.Host.Application.Command.UniverseSettings.Action, Alaris.Host.Application.Command.APcm004A.GenerateUniverse(), Alaris.Host.Application.Command.APcm004A.InvalidAction(), Alaris.Host.Application.Command.APcm004A.ListUniverseFiles(), and Alaris.Host.Application.Command.APcm004A.ShowUniverseInfo().
FindDataPath()
static ? string Alaris.Host.Application.Command.APcm004A.FindDataPath () inline static private
Definition at line 340 of file APcm004A.cs.
Referenced by Alaris.Host.Application.Command.APcm004A.FindOrCreateDataPath(), Alaris.Host.Application.Command.APcm004A.ListUniverseFiles(), and Alaris.Host.Application.Command.APcm004A.ShowUniverseInfo().
FindOrCreateDataPath()
static string Alaris.Host.Application.Command.APcm004A.FindOrCreateDataPath () inline static private
Definition at line 351 of file APcm004A.cs.
References Alaris.Host.Application.Command.APcm004A.FindDataPath().
Referenced by Alaris.Host.Application.Command.APcm004A.GenerateUniverse().
FormatSize()
static string Alaris.Host.Application.Command.APcm004A.FormatSize (long bytes) inline static private
Definition at line 404 of file APcm004A.cs.
Referenced by Alaris.Host.Application.Command.APcm004A.ListUniverseFiles().
GenerateUniverse()
static int Alaris.Host.Application.Command.APcm004A.GenerateUniverse (UniverseSettings settings) inline static private
Definition at line 59 of file APcm004A.cs.
References Alaris.Host.Application.Command.APcm004A.FindOrCreateDataPath(), Alaris.Host.Application.Command.APcm004A.GenerateUniverseForDate(), Alaris.Host.Application.Command.APcm004A.GetPolygonApiKey(), Alaris.Host.Application.Command.APcm004A.GetTradingDays(), Alaris.Host.Application.Command.UniverseSettings.MinDollarVolume, Alaris.Host.Application.Command.UniverseSettings.MinPrice, Alaris.Host.Application.Command.APcm004A.stockCount, and Alaris.Host.Application.Command.APcm004A.success.
Referenced by Alaris.Host.Application.Command.APcm004A.Execute().
GenerateUniverseForDate()
static bool int? string error Alaris.Host.Application.Command.APcm004A.GenerateUniverseForDate (DateTime date, string apiKey, string outputDir, decimal minDollarVolume, decimal minPrice) inline static private
Definition at line 146 of file APcm004A.cs.
References Alaris.Host.Application.Command.APcm004A.GetSymbolId().
Referenced by Alaris.Host.Application.Command.APcm004A.GenerateUniverse().
GetPolygonApiKey()
static ? string Alaris.Host.Application.Command.APcm004A.GetPolygonApiKey () inline static private
Definition at line 369 of file APcm004A.cs.
Referenced by Alaris.Host.Application.Command.APcm004A.GenerateUniverse(), and Alaris.Host.Application.Command.APcm004A.ShowUniverseInfo().
GetSymbolId()
static string Alaris.Host.Application.Command.APcm004A.GetSymbolId (string ticker) inline static private
Definition at line 222 of file APcm004A.cs.
Referenced by Alaris.Host.Application.Command.APcm004A.GenerateUniverseForDate().
GetTradingDays()
static List< DateTime > Alaris.Host.Application.Command.APcm004A.GetTradingDays (DateTime start, DateTime end) inline static private
Definition at line 230 of file APcm004A.cs.
Referenced by Alaris.Host.Application.Command.APcm004A.GenerateUniverse().
InvalidAction()
static int Alaris.Host.Application.Command.APcm004A.InvalidAction (string action) inline static private
Definition at line 333 of file APcm004A.cs.
Referenced by Alaris.Host.Application.Command.APcm004A.Execute().
ListUniverseFiles()
static int Alaris.Host.Application.Command.APcm004A.ListUniverseFiles () inline static private
Definition at line 248 of file APcm004A.cs.
References Alaris.Host.Application.Command.APcm004A.FindDataPath(), and Alaris.Host.Application.Command.APcm004A.FormatSize().
Referenced by Alaris.Host.Application.Command.APcm004A.Execute().
ShowUniverseInfo()
static int Alaris.Host.Application.Command.APcm004A.ShowUniverseInfo () inline static private
Definition at line 305 of file APcm004A.cs.
References Alaris.Host.Application.Command.APcm004A.FindDataPath(), and Alaris.Host.Application.Command.APcm004A.GetPolygonApiKey().
Referenced by Alaris.Host.Application.Command.APcm004A.Execute().
Member Data Documentation
stockCount
bool int Alaris.Host.Application.Command.APcm004A.stockCount static private
Definition at line 146 of file APcm004A.cs.
Referenced by Alaris.Host.Application.Command.APcm004A.GenerateUniverse().
success
bool Alaris.Host.Application.Command.APcm004A.success static private
Definition at line 146 of file APcm004A.cs.
Referenced by Alaris.Host.Application.Command.APcm004A.GenerateUniverse().
The documentation for this class was generated from the following file:
src/Alaris.Host/Application/Command/APcm004A.cs