Alaris: Alaris.Test.Unit.IVModelTests Class Reference
Alaris.Test.Unit.IVModelTests Class Reference
Unit tests for IV models including STTM004A, Kou, Heston, STTM002A, and STIV003A.
Public Member Functions
void STTM004A_Create_ValidDates_ReturnsCorrectParameters ()
void STTM004A_Create_WithEarningsBeforeExpiry_DetectsPreEarnings ()
void STTM004A_Create_WithEarningsAfterExpiry_NoEarningsEffect ()
void STTM004A_Create_ExpirationBeforeValuation_Throws ()
void TimeConstraints_ValidatePreEarnings_ValidParameters_ReturnsValid ()
void STIV002A_Parameters_Validate_ValidParameters_ReturnsValid ()
void STIV002A_Parameters_Validate_InvalidEta1_ReturnsInvalid ()
void STIV002A_ComputeKappa_ReturnsExpectedValue ()
void STIV002A_ComputeTheoreticalIV_ATM_ReturnsReasonableValue ()
void STIV002A_ComputeSmile_ProducesSkew ()
void STIV002A_ComputeSTTM001A_ReturnsCorrectLength ()
void STIV001A_Parameters_SatisfiesFellerCondition_ValidParams_ReturnsTrue ()
void STIV001A_Parameters_SatisfiesFellerCondition_InvalidParams_ReturnsFalse ()
void STIV001A_Parameters_Validate_FellerViolation_ReturnsInvalid ()
void STIV001A_ExpectedVariance_ConvergesToTheta ()
void STIV001A_ComputeTheoreticalIV_ATM_ReturnsReasonableValue ()
void STIV001A_ComputeSmile_WithNegativeRho_ProducesNegativeSkew ()
void STTM002A_Detect_PreEarnings_ReturnsPreSTTM002A ()
void STTM002A_Detect_NoEarnings_ReturnsNoSTTM002A ()
void STTM002A_ComputeAdjustedIV_PreEarnings_ReturnsEarningsIV ()
void STTM002A_ComputeAdjustedIV_NoEarnings_ReturnsBaseIV ()
void MartingaleValidator_Validate_BlackScholes_AlwaysValid ()
void MartingaleValidator_ComputeJumpCompensation_ReturnsCorrectValue ()
void STIV003A_SelectBestModel_PreEarnings_PrefersLeungSantoli ()
void STIV003A_SelectBestModel_NoEarnings_PrefersHeston ()
void STIV003A_SelectBestModel_WithMarketData_ComputesFitMetrics ()
void FitMetrics_Default_HasReasonableValues ()
void ValidationResult_ThrowIfInvalid_InvalidResult_Throws ()
void ValidationResult_ThrowIfInvalid_ValidResult_DoesNotThrow ()
Static Private Attributes
static readonly double[] s_smileStrikes = { 80, 90, 100, 110, 120 }
static readonly string[] s_validationErrors = { "Error 1", "Error 2" }
Detailed Description
Unit tests for IV models including STTM004A, Kou, Heston, STTM002A, and STIV003A.
Definition at line 13 of file TSUN007A.cs.
Member Function Documentation
FitMetrics_Default_HasReasonableValues()
void Alaris.Test.Unit.IVModelTests.FitMetrics_Default_HasReasonableValues () inline
Definition at line 545 of file TSUN007A.cs.
References Alaris.Strategy.Core.FitMetrics.Default, and Alaris.Strategy.Core.FitMetrics.MSE.
MartingaleValidator_ComputeJumpCompensation_ReturnsCorrectValue()
void Alaris.Test.Unit.IVModelTests.MartingaleValidator_ComputeJumpCompensation_ReturnsCorrectValue () inline
Definition at line 436 of file TSUN007A.cs.
References Alaris.Strategy.Core.MartingaleValidator.ComputeJumpCompensation(), and Alaris.Strategy.Core.KouParameters.DefaultEquity.
MartingaleValidator_Validate_BlackScholes_AlwaysValid()
void Alaris.Test.Unit.IVModelTests.MartingaleValidator_Validate_BlackScholes_AlwaysValid () inline
Definition at line 412 of file TSUN007A.cs.
References Alaris.Strategy.Core.STTM004A.Create().
STIV001A_ComputeSmile_WithNegativeRho_ProducesNegativeSkew()
void Alaris.Test.Unit.IVModelTests.STIV001A_ComputeSmile_WithNegativeRho_ProducesNegativeSkew () inline
Definition at line 310 of file TSUN007A.cs.
References Alaris.Test.Unit.IVModelTests.s_smileStrikes.
STIV001A_ComputeTheoreticalIV_ATM_ReturnsReasonableValue()
void Alaris.Test.Unit.IVModelTests.STIV001A_ComputeTheoreticalIV_ATM_ReturnsReasonableValue () inline
Definition at line 294 of file TSUN007A.cs.
References Alaris.Strategy.Core.HestonParameters.DefaultEquity.
STIV001A_ExpectedVariance_ConvergesToTheta()
void Alaris.Test.Unit.IVModelTests.STIV001A_ExpectedVariance_ConvergesToTheta () inline
Definition at line 279 of file TSUN007A.cs.
References Alaris.Strategy.Core.HestonParameters.DefaultEquity, and Alaris.Strategy.Core.HestonParameters.ExpectedVariance().
STIV001A_Parameters_SatisfiesFellerCondition_InvalidParams_ReturnsFalse()
void Alaris.Test.Unit.IVModelTests.STIV001A_Parameters_SatisfiesFellerCondition_InvalidParams_ReturnsFalse () inline
Definition at line 237 of file TSUN007A.cs.
STIV001A_Parameters_SatisfiesFellerCondition_ValidParams_ReturnsTrue()
void Alaris.Test.Unit.IVModelTests.STIV001A_Parameters_SatisfiesFellerCondition_ValidParams_ReturnsTrue () inline
Definition at line 218 of file TSUN007A.cs.
STIV001A_Parameters_Validate_FellerViolation_ReturnsInvalid()
void Alaris.Test.Unit.IVModelTests.STIV001A_Parameters_Validate_FellerViolation_ReturnsInvalid () inline
Definition at line 256 of file TSUN007A.cs.
STIV002A_ComputeKappa_ReturnsExpectedValue()
void Alaris.Test.Unit.IVModelTests.STIV002A_ComputeKappa_ReturnsExpectedValue () inline
Definition at line 134 of file TSUN007A.cs.
References Alaris.Strategy.Core.KouParameters.ComputeKappa().
STIV002A_ComputeSmile_ProducesSkew()
void Alaris.Test.Unit.IVModelTests.STIV002A_ComputeSmile_ProducesSkew () inline
Definition at line 176 of file TSUN007A.cs.
References Alaris.Test.Unit.IVModelTests.s_smileStrikes.
STIV002A_ComputeSTTM001A_ReturnsCorrectLength()
void Alaris.Test.Unit.IVModelTests.STIV002A_ComputeSTTM001A_ReturnsCorrectLength () inline
Definition at line 202 of file TSUN007A.cs.
References Alaris.Strategy.Core.KouParameters.DefaultEquity.
STIV002A_ComputeTheoreticalIV_ATM_ReturnsReasonableValue()
void Alaris.Test.Unit.IVModelTests.STIV002A_ComputeTheoreticalIV_ATM_ReturnsReasonableValue () inline
Definition at line 157 of file TSUN007A.cs.
References Alaris.Strategy.Core.KouParameters.DefaultEquity.
STIV002A_Parameters_Validate_InvalidEta1_ReturnsInvalid()
void Alaris.Test.Unit.IVModelTests.STIV002A_Parameters_Validate_InvalidEta1_ReturnsInvalid () inline
Definition at line 111 of file TSUN007A.cs.
References Alaris.Strategy.Core.ValidationResult.IsValid, and Alaris.Strategy.Core.KouParameters.Validate().
STIV002A_Parameters_Validate_ValidParameters_ReturnsValid()
void Alaris.Test.Unit.IVModelTests.STIV002A_Parameters_Validate_ValidParameters_ReturnsValid () inline
Definition at line 98 of file TSUN007A.cs.
References Alaris.Strategy.Core.KouParameters.DefaultEquity, Alaris.Strategy.Core.ValidationResult.IsValid, and Alaris.Strategy.Core.KouParameters.Validate().
STIV003A_SelectBestModel_NoEarnings_PrefersHeston()
void Alaris.Test.Unit.IVModelTests.STIV003A_SelectBestModel_NoEarnings_PrefersHeston () inline
Definition at line 480 of file TSUN007A.cs.
References Alaris.Strategy.Core.STTM004A.Create().
STIV003A_SelectBestModel_PreEarnings_PrefersLeungSantoli()
void Alaris.Test.Unit.IVModelTests.STIV003A_SelectBestModel_PreEarnings_PrefersLeungSantoli () inline
Definition at line 452 of file TSUN007A.cs.
References Alaris.Strategy.Core.STTM004A.Create().
STIV003A_SelectBestModel_WithMarketData_ComputesFitMetrics()
void Alaris.Test.Unit.IVModelTests.STIV003A_SelectBestModel_WithMarketData_ComputesFitMetrics () inline
Definition at line 506 of file TSUN007A.cs.
References Alaris.Strategy.Core.STTM004A.Create(), and Alaris.Strategy.Core.HestonParameters.DefaultEquity.
STTM002A_ComputeAdjustedIV_NoEarnings_ReturnsBaseIV()
void Alaris.Test.Unit.IVModelTests.STTM002A_ComputeAdjustedIV_NoEarnings_ReturnsBaseIV () inline
Definition at line 391 of file TSUN007A.cs.
References Alaris.Strategy.Core.STTM004A.Create(), and Alaris.Strategy.Core.STTM002A.Detect().
STTM002A_ComputeAdjustedIV_PreEarnings_ReturnsEarningsIV()
void Alaris.Test.Unit.IVModelTests.STTM002A_ComputeAdjustedIV_PreEarnings_ReturnsEarningsIV () inline
Definition at line 371 of file TSUN007A.cs.
References Alaris.Strategy.Core.STTM004A.Create(), and Alaris.Strategy.Core.STTM002A.Detect().
STTM002A_Detect_NoEarnings_ReturnsNoSTTM002A()
void Alaris.Test.Unit.IVModelTests.STTM002A_Detect_NoEarnings_ReturnsNoSTTM002A () inline
Definition at line 355 of file TSUN007A.cs.
References Alaris.Strategy.Core.STTM004A.Create(), Alaris.Strategy.Core.STTM002A.Detect(), and Alaris.Strategy.Core.STTM002A.RegimeType.
STTM002A_Detect_PreEarnings_ReturnsPreSTTM002A()
void Alaris.Test.Unit.IVModelTests.STTM002A_Detect_PreEarnings_ReturnsPreSTTM002A () inline
Definition at line 338 of file TSUN007A.cs.
References Alaris.Strategy.Core.STTM004A.Create(), Alaris.Strategy.Core.STTM002A.Detect(), and Alaris.Strategy.Core.STTM002A.RegimeType.
STTM004A_Create_ExpirationBeforeValuation_Throws()
void Alaris.Test.Unit.IVModelTests.STTM004A_Create_ExpirationBeforeValuation_Throws () inline
Definition at line 67 of file TSUN007A.cs.
References Alaris.Strategy.Core.STTM004A.Create().
STTM004A_Create_ValidDates_ReturnsCorrectParameters()
void Alaris.Test.Unit.IVModelTests.STTM004A_Create_ValidDates_ReturnsCorrectParameters () inline
Definition at line 18 of file TSUN007A.cs.
References Alaris.Strategy.Core.STTM004A.Create(), and Alaris.Strategy.Core.STTM004A.ValuationDate.
STTM004A_Create_WithEarningsAfterExpiry_NoEarningsEffect()
void Alaris.Test.Unit.IVModelTests.STTM004A_Create_WithEarningsAfterExpiry_NoEarningsEffect () inline
Definition at line 52 of file TSUN007A.cs.
References Alaris.Strategy.Core.STTM004A.Create(), and Alaris.Strategy.Core.STTM004A.HasEarningsBeforeExpiry.
STTM004A_Create_WithEarningsBeforeExpiry_DetectsPreEarnings()
void Alaris.Test.Unit.IVModelTests.STTM004A_Create_WithEarningsBeforeExpiry_DetectsPreEarnings () inline
Definition at line 35 of file TSUN007A.cs.
References Alaris.Strategy.Core.STTM004A.Create(), and Alaris.Strategy.Core.STTM004A.IsPreEarnings.
TimeConstraints_ValidatePreEarnings_ValidParameters_ReturnsValid()
void Alaris.Test.Unit.IVModelTests.TimeConstraints_ValidatePreEarnings_ValidParameters_ReturnsValid () inline
Definition at line 79 of file TSUN007A.cs.
References Alaris.Strategy.Core.STTM004A.Create(), and Alaris.Strategy.Core.TimeConstraints.Default.
ValidationResult_ThrowIfInvalid_InvalidResult_Throws()
void Alaris.Test.Unit.IVModelTests.ValidationResult_ThrowIfInvalid_InvalidResult_Throws () inline
Definition at line 561 of file TSUN007A.cs.
References Alaris.Test.Unit.IVModelTests.s_validationErrors.
ValidationResult_ThrowIfInvalid_ValidResult_DoesNotThrow()
void Alaris.Test.Unit.IVModelTests.ValidationResult_ThrowIfInvalid_ValidResult_DoesNotThrow () inline
Definition at line 573 of file TSUN007A.cs.
Member Data Documentation
s_smileStrikes
readonly double [] Alaris.Test.Unit.IVModelTests.s_smileStrikes = { 80, 90, 100, 110, 120 } static private
Definition at line 173 of file TSUN007A.cs.
Referenced by Alaris.Test.Unit.IVModelTests.STIV001A_ComputeSmile_WithNegativeRho_ProducesNegativeSkew(), and Alaris.Test.Unit.IVModelTests.STIV002A_ComputeSmile_ProducesSkew().
s_validationErrors
readonly string [] Alaris.Test.Unit.IVModelTests.s_validationErrors = { "Error 1", "Error 2" } static private
Definition at line 558 of file TSUN007A.cs.
Referenced by Alaris.Test.Unit.IVModelTests.ValidationResult_ThrowIfInvalid_InvalidResult_Throws().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN007A.cs