Alaris: Alaris.Infrastructure.Protocol.Workflow Namespace Reference
Alaris.Infrastructure.Protocol.Workflow Namespace Reference
Classes
class PLWF001A
Finite State Machine engine for deterministic workflow routing. Component ID: PLWF001A.
class PLWF002A
Factory for creating the Backtest workflow FSM. Component ID: PLWF002A.
class PLWF003A
Factory for creating the Trading workflow FSM. Component ID: PLWF003A.
struct TransitionResult
Result of a state transition attempt.
Enumerations
enum BacktestState {
Idle , SessionSelected , DataChecking , DataBootstrapping ,
ExecutingLean , Monitoring , Completed , Failed
}
Backtest workflow states.
enum BacktestEvent {
SelectSession , CreateSession , CheckData , DataMissing ,
DataReady , BootstrapData , BootstrapComplete , BootstrapFailed ,
StartLean , LeanCompleted , LeanFailed , ViewResults ,
Reset
}
Backtest workflow events/actions.
enum TradingState {
Disconnected , Connecting , Ready , Evaluating ,
Executing , Monitoring , Error
}
Trading workflow states.
enum TradingEvent {
Connect , Connected , ConnectionFailed , Disconnect ,
Evaluate , SignalGenerated , NoSignal , TradeExecuted ,
TradeFailed , PositionClosed , FatalError , Reset
}
Trading workflow events.
Functions
readonly record struct TransitionRecord (string FromState, string Event, string ToState, bool Succeeded, DateTime Timestamp, string? Message=null)
Record of a single state transition for audit/debugging.
readonly record struct FsmStatistics (int StateCount, int EventCount, int TransitionCount, int TerminalStateCount, double TransitionDensity, bool HasCycles)
Statistics about FSM structure.
Enumeration Type Documentation
BacktestEvent
enum Alaris.Infrastructure.Protocol.Workflow.BacktestEvent
Backtest workflow events/actions.
Enumerator
SelectSession
User selects an existing session.
CreateSession
User creates a new session.
CheckData
Begin checking data availability.
DataMissing
Data check determined data is missing.
DataReady
Data check determined data is ready.
BootstrapData
Begin bootstrapping missing data.
BootstrapComplete
Data bootstrap completed successfully.
BootstrapFailed
Data bootstrap failed.
StartLean
Start LEAN engine execution.
LeanCompleted
LEAN execution completed successfully.
LeanFailed
LEAN execution failed.
ViewResults
View backtest results.
Reset
Reset workflow to idle state.
Definition at line 67 of file PLWF002A.cs.
BacktestState
enum Alaris.Infrastructure.Protocol.Workflow.BacktestState
Backtest workflow states.
State diagram:
                 ┌──────────────────────────────────┐
                 │               Reset              │
                 ▼                                  │
[Idle] ──SelectSession──▶ [SessionSelected]         │
  │                              │                  │
  │ CreateSession               CheckData           │
  ▼                              ▼                  │
[SessionSelected] ◀── [DataChecking]                │
                        │         │                 │
                 DataMissing   DataReady            │
                        ▼         │                 │
               [DataBootstrapping]│                 │
                 │         │      │                 │
         Complete│    Failed│     │                 │
                 ▼         ▼      ▼                 │
               [DataChecking] ◀───────────────────  │
                        │                           │
                     StartLean                      │
                        ▼                           │
                 [ExecutingLean]                    │
                   │         │                      │
            Completed    Failed                     │
                   ▼         ▼                      │
             [Completed]  [Failed] ─────Reset───────┘
Enumerator
Idle
No session selected, idle state.
SessionSelected
A session has been selected or created.
DataChecking
Checking data availability for the session.
DataBootstrapping
Bootstrapping missing data (prices/earnings).
ExecutingLean
Executing LEAN engine with the session.
Monitoring
Monitoring LEAN execution.
Completed
Backtest completed successfully (terminal).
Failed
Backtest failed (terminal).
Definition at line 37 of file PLWF002A.cs.
TradingEvent
enum Alaris.Infrastructure.Protocol.Workflow.TradingEvent
Trading workflow events.
Enumerator
Connect
Initiate broker connection.
Connected
Connection established successfully.
ConnectionFailed
Connection failed.
Disconnect
Disconnect from broker.
Evaluate
Begin market evaluation.
SignalGenerated
Signal generated, initiate trade.
NoSignal
No signal, return to ready state.
TradeExecuted
Trade execution completed.
TradeFailed
Trade execution failed.
PositionClosed
Position closed (manual or automatic).
FatalError
Unrecoverable error occurred.
Reset
Reset from error state.
Definition at line 35 of file PLWF003A.cs.
TradingState
enum Alaris.Infrastructure.Protocol.Workflow.TradingState
Trading workflow states.
Enumerator
Disconnected
Not connected to broker.
Connecting
Attempting to connect to broker.
Ready
Connected to broker, ready to trade.
Evaluating
Evaluating market conditions and generating signals.
Executing
Executing a trade order.
Monitoring
Trade executed, monitoring position.
Error
Fatal error occurred (terminal).
Definition at line 8 of file PLWF003A.cs.
Function Documentation
FsmStatistics()
readonly record struct Alaris.Infrastructure.Protocol.Workflow.FsmStatistics (int StateCount, int EventCount, int TransitionCount, int TerminalStateCount, double TransitionDensity, bool HasCycles)
Statistics about FSM structure.
Parameters
StateCount Number of unique states.
EventCount Number of unique events.
TransitionCount Number of defined transitions.
TerminalStateCount Number of terminal states.
TransitionDensity Ratio of defined transitions to possible (0-1).
HasCycles Whether the FSM contains cycles.
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.GetStatistics().
TransitionRecord()
readonly record struct Alaris.Infrastructure.Protocol.Workflow.TransitionRecord (string FromState, string Event, string ToState, bool Succeeded, DateTime Timestamp, string? Message = null)
Record of a single state transition for audit/debugging.
Parameters
FromState State before transition.
Event Event that triggered transition.
ToState State after transition.
Succeeded Whether transition succeeded.
Timestamp When the transition occurred.
Message Optional message (e.g., error details).
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.PLWF001A(), and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.RecordTransition().