Alaris: Alaris.Host.Application.Cli.Dashboard.CLdb001A Class Reference
Alaris.Host.Application.Cli.Dashboard.CLdb001A Class Reference sealed
Renders a live dashboard for algorithm monitoring. Uses Spectre.Console Live display for smooth updates. Component ID: CLdb001A.
Public Member Functions
CLdb001A (CLmn001A monitor)
async Task RunAsync (CancellationToken cancellationToken=default)
Runs the dashboard until cancelled or algorithm completes.
void Dispose ()
Private Member Functions
void OnEquityChanged (object? sender, EquityUpdate e)
void OnTradeExecuted (object? sender, TradeUpdate e)
void OnStatusChanged (object? sender, StatusUpdate e)
IRenderable BuildDashboard ()
Panel BuildStatusBar ()
Panel BuildEquityPanel ()
Panel BuildMetricsPanel ()
Panel BuildTradesPanel ()
Private Attributes
readonly CLmn001A _monitor
readonly List< EquityUpdate > _equityHistory = new()
readonly List< TradeUpdate > _trades = new()
StatusUpdate? _lastStatus
readonly object _lock = new()
Detailed Description
Renders a live dashboard for algorithm monitoring. Uses Spectre.Console Live display for smooth updates. Component ID: CLdb001A.
Definition at line 14 of file CLdb001A.cs.
Constructor & Destructor Documentation
CLdb001A()
Alaris.Host.Application.Cli.Dashboard.CLdb001A.CLdb001A (CLmn001A monitor) inline
Definition at line 22 of file CLdb001A.cs.
References Alaris.Host.Application.Cli.Dashboard.CLdb001A._monitor, Alaris.Host.Application.Cli.Dashboard.CLdb001A.OnEquityChanged(), Alaris.Host.Application.Cli.Dashboard.CLdb001A.OnStatusChanged(), and Alaris.Host.Application.Cli.Dashboard.CLdb001A.OnTradeExecuted().
Member Function Documentation
BuildDashboard()
IRenderable Alaris.Host.Application.Cli.Dashboard.CLdb001A.BuildDashboard () inline private
Definition at line 82 of file CLdb001A.cs.
References Alaris.Host.Application.Cli.Dashboard.CLdb001A.BuildEquityPanel(), Alaris.Host.Application.Cli.Dashboard.CLdb001A.BuildMetricsPanel(), Alaris.Host.Application.Cli.Dashboard.CLdb001A.BuildStatusBar(), and Alaris.Host.Application.Cli.Dashboard.CLdb001A.BuildTradesPanel().
Referenced by Alaris.Host.Application.Cli.Dashboard.CLdb001A.RunAsync().
BuildEquityPanel()
Panel Alaris.Host.Application.Cli.Dashboard.CLdb001A.BuildEquityPanel () inline private
Definition at line 127 of file CLdb001A.cs.
References Alaris.Host.Application.Cli.Dashboard.CLdb001A._equityHistory, and Alaris.Host.Application.Cli.Dashboard.CLdb001A._lock.
Referenced by Alaris.Host.Application.Cli.Dashboard.CLdb001A.BuildDashboard().
BuildMetricsPanel()
Panel Alaris.Host.Application.Cli.Dashboard.CLdb001A.BuildMetricsPanel () inline private
Definition at line 182 of file CLdb001A.cs.
References Alaris.Host.Application.Cli.Dashboard.CLdb001A._equityHistory, Alaris.Host.Application.Cli.Dashboard.CLdb001A._lock, and Alaris.Host.Application.Cli.Dashboard.CLdb001A._trades.
Referenced by Alaris.Host.Application.Cli.Dashboard.CLdb001A.BuildDashboard().
BuildStatusBar()
Panel Alaris.Host.Application.Cli.Dashboard.CLdb001A.BuildStatusBar () inline private
Definition at line 105 of file CLdb001A.cs.
References Alaris.Host.Application.Cli.Dashboard.CLdb001A._lastStatus, Alaris.Host.Application.Cli.Dashboard.CLdb001A._lock, Alaris.Host.Application.Cli.Dashboard.CLdb001A._monitor, Alaris.Host.Application.Cli.Monitor.StatusUpdate.EstimatedRemaining, Alaris.Host.Application.Cli.Monitor.CLmn001A.Mode, Alaris.Host.Application.Cli.Monitor.StatusUpdate.ProgressPercent, and Alaris.Host.Application.Cli.Monitor.StatusUpdate.Status.
Referenced by Alaris.Host.Application.Cli.Dashboard.CLdb001A.BuildDashboard().
BuildTradesPanel()
Panel Alaris.Host.Application.Cli.Dashboard.CLdb001A.BuildTradesPanel () inline private
Definition at line 231 of file CLdb001A.cs.
References Alaris.Host.Application.Cli.Dashboard.CLdb001A._lock, and Alaris.Host.Application.Cli.Dashboard.CLdb001A._trades.
Referenced by Alaris.Host.Application.Cli.Dashboard.CLdb001A.BuildDashboard().
Dispose()
void Alaris.Host.Application.Cli.Dashboard.CLdb001A.Dispose () inline
Definition at line 267 of file CLdb001A.cs.
References Alaris.Host.Application.Cli.Dashboard.CLdb001A.OnEquityChanged(), Alaris.Host.Application.Cli.Dashboard.CLdb001A.OnStatusChanged(), and Alaris.Host.Application.Cli.Dashboard.CLdb001A.OnTradeExecuted().
OnEquityChanged()
void Alaris.Host.Application.Cli.Dashboard.CLdb001A.OnEquityChanged (object? sender, EquityUpdate e) inline private
Definition at line 30 of file CLdb001A.cs.
References Alaris.Host.Application.Cli.Dashboard.CLdb001A._equityHistory, and Alaris.Host.Application.Cli.Dashboard.CLdb001A._lock.
Referenced by Alaris.Host.Application.Cli.Dashboard.CLdb001A.CLdb001A(), and Alaris.Host.Application.Cli.Dashboard.CLdb001A.Dispose().
OnStatusChanged()
void Alaris.Host.Application.Cli.Dashboard.CLdb001A.OnStatusChanged (object? sender, StatusUpdate e) inline private
Definition at line 52 of file CLdb001A.cs.
References Alaris.Host.Application.Cli.Dashboard.CLdb001A._lastStatus, and Alaris.Host.Application.Cli.Dashboard.CLdb001A._lock.
Referenced by Alaris.Host.Application.Cli.Dashboard.CLdb001A.CLdb001A(), and Alaris.Host.Application.Cli.Dashboard.CLdb001A.Dispose().
OnTradeExecuted()
void Alaris.Host.Application.Cli.Dashboard.CLdb001A.OnTradeExecuted (object? sender, TradeUpdate e) inline private
Definition at line 41 of file CLdb001A.cs.
References Alaris.Host.Application.Cli.Dashboard.CLdb001A._lock, and Alaris.Host.Application.Cli.Dashboard.CLdb001A._trades.
Referenced by Alaris.Host.Application.Cli.Dashboard.CLdb001A.CLdb001A(), and Alaris.Host.Application.Cli.Dashboard.CLdb001A.Dispose().
RunAsync()
async Task Alaris.Host.Application.Cli.Dashboard.CLdb001A.RunAsync (CancellationToken cancellationToken = default) inline
Runs the dashboard until cancelled or algorithm completes.
Definition at line 63 of file CLdb001A.cs.
References Alaris.Host.Application.Cli.Dashboard.CLdb001A._monitor, Alaris.Host.Application.Cli.Dashboard.CLdb001A.BuildDashboard(), and Alaris.Host.Application.Cli.Monitor.CLmn001A.IsRunning.
Member Data Documentation
_equityHistory
readonly List<EquityUpdate> Alaris.Host.Application.Cli.Dashboard.CLdb001A._equityHistory = new() private
Definition at line 17 of file CLdb001A.cs.
Referenced by Alaris.Host.Application.Cli.Dashboard.CLdb001A.BuildEquityPanel(), Alaris.Host.Application.Cli.Dashboard.CLdb001A.BuildMetricsPanel(), and Alaris.Host.Application.Cli.Dashboard.CLdb001A.OnEquityChanged().
_lastStatus
StatusUpdate? Alaris.Host.Application.Cli.Dashboard.CLdb001A._lastStatus private
Definition at line 19 of file CLdb001A.cs.
Referenced by Alaris.Host.Application.Cli.Dashboard.CLdb001A.BuildStatusBar(), and Alaris.Host.Application.Cli.Dashboard.CLdb001A.OnStatusChanged().
_lock
readonly object Alaris.Host.Application.Cli.Dashboard.CLdb001A._lock = new() private
Definition at line 20 of file CLdb001A.cs.
Referenced by Alaris.Host.Application.Cli.Dashboard.CLdb001A.BuildEquityPanel(), Alaris.Host.Application.Cli.Dashboard.CLdb001A.BuildMetricsPanel(), Alaris.Host.Application.Cli.Dashboard.CLdb001A.BuildStatusBar(), Alaris.Host.Application.Cli.Dashboard.CLdb001A.BuildTradesPanel(), Alaris.Host.Application.Cli.Dashboard.CLdb001A.OnEquityChanged(), Alaris.Host.Application.Cli.Dashboard.CLdb001A.OnStatusChanged(), and Alaris.Host.Application.Cli.Dashboard.CLdb001A.OnTradeExecuted().
_monitor
readonly CLmn001A Alaris.Host.Application.Cli.Dashboard.CLdb001A._monitor private
Definition at line 16 of file CLdb001A.cs.
Referenced by Alaris.Host.Application.Cli.Dashboard.CLdb001A.CLdb001A(), Alaris.Host.Application.Cli.Dashboard.CLdb001A.BuildStatusBar(), and Alaris.Host.Application.Cli.Dashboard.CLdb001A.RunAsync().
_trades
readonly List<TradeUpdate> Alaris.Host.Application.Cli.Dashboard.CLdb001A._trades = new() private
Definition at line 18 of file CLdb001A.cs.
Referenced by Alaris.Host.Application.Cli.Dashboard.CLdb001A.BuildMetricsPanel(), Alaris.Host.Application.Cli.Dashboard.CLdb001A.BuildTradesPanel(), and Alaris.Host.Application.Cli.Dashboard.CLdb001A.OnTradeExecuted().
The documentation for this class was generated from the following file:
src/Alaris.Host/Application/Cli/Dashboard/CLdb001A.cs