Alaris: Alaris.Core.Math.CRGQ001A Class Reference
Alaris.Core.Math.CRGQ001A Class Reference
Gauss quadrature infrastructure for spectral integration methods.
Classes
class Schemes
Pre-computed Gauss-Legendre nodes and weights for common orders.
Static Public Member Functions
static double[] double[] Weights GaussLegendre (int n)
static double[] double[] Weights GaussLegendreAB (int n, double a, double b)
static double GaussLegendreIntegrate (Func< double, double > f, double a, double b, int n=16)
Integrates a function using Gauss-Legendre quadrature.
static double TanhSinhIntegrate (Func< double, double > f, double a, double b, double tolerance=1e-10, int maxLevels=10)
Integrates a function using Tanh-Sinh (doubly exponential) quadrature.
static double AdaptiveIntegrate (Func< double, double > f, double a, double b, double tolerance=1e-10, int maxDepth=15)
Gauss-Kronrod adaptive quadrature for automatic precision control.
static double IntegrateWithScheme (Func< double, double > f,(double[] Nodes, double[] Weights) scheme, double a, double b)
Integrates using pre-computed nodes and weights (fastest method).
static double[] double[] Weights GaussLaguerre (int n)
static double[] double[] Weights GaussHermite (int n)
Static Public Attributes
static double[] Nodes
Computes Gauss-Legendre nodes and weights on [-1, 1].
Static Private Member Functions
static double AdaptiveIntegrateRecursive (Func< double, double > f, double a, double b, double tolerance, int maxDepth, int depth)
Static Private Attributes
const int MaxLegendreOrder = 64
const int MaxLaguerreOrder = 32
const int MaxHermiteOrder = 32
const double LegendreRootTolerance = 1e-15
const int LegendreMaxIterations = 100
const double TanhSinhWeightCutoff = 1e-20
const double TanhSinhOverflowLimit = 350.0
const int TanhSinhMaxSamples = 1000
Detailed Description
Gauss quadrature infrastructure for spectral integration methods.
Definition at line 20 of file CRGQ001A.cs.
Member Function Documentation
AdaptiveIntegrate()
static double Alaris.Core.Math.CRGQ001A.AdaptiveIntegrate (Func< double, double > f, double a, double b, double tolerance = 1e-10, int maxDepth = 15) inline static
Gauss-Kronrod adaptive quadrature for automatic precision control.
Parameters
f Function to integrate.
a Left endpoint.
b Right endpoint.
tolerance Desired relative tolerance.
maxDepth Maximum recursion depth.
Returns
Approximate integral value.
Uses 7-point Gauss and 15-point Kronrod rules for error estimation. Adaptively subdivides intervals where error is large.
Definition at line 282 of file CRGQ001A.cs.
References Alaris.Core.Math.CRGQ001A.AdaptiveIntegrateRecursive().
AdaptiveIntegrateRecursive()
static double Alaris.Core.Math.CRGQ001A.AdaptiveIntegrateRecursive (Func< double, double > f, double a, double b, double tolerance, int maxDepth, int depth) inline static private
Definition at line 304 of file CRGQ001A.cs.
References Alaris.Core.Math.CRGQ001A.AdaptiveIntegrateRecursive(), and Alaris.Core.Math.CRGQ001A.IntegrateWithScheme().
Referenced by Alaris.Core.Math.CRGQ001A.AdaptiveIntegrate(), and Alaris.Core.Math.CRGQ001A.AdaptiveIntegrateRecursive().
GaussHermite()
static double[] double[] Weights Alaris.Core.Math.CRGQ001A.GaussHermite (int n) inline static
Definition at line 453 of file CRGQ001A.cs.
References Alaris.Core.Math.CRGQ001A.MaxHermiteOrder.
GaussLaguerre()
static double[] double[] Weights Alaris.Core.Math.CRGQ001A.GaussLaguerre (int n) inline static
Definition at line 377 of file CRGQ001A.cs.
References Alaris.Core.Math.CRGQ001A.MaxLaguerreOrder.
GaussLegendre()
static double[] double[] Weights Alaris.Core.Math.CRGQ001A.GaussLegendre (int n) inline static
Definition at line 62 of file CRGQ001A.cs.
References Alaris.Core.Math.CRGQ001A.LegendreMaxIterations, Alaris.Core.Math.CRGQ001A.LegendreRootTolerance, and Alaris.Core.Math.CRGQ001A.MaxLegendreOrder.
Referenced by Alaris.Core.Pricing.CREN004A.CREN004A(), and Alaris.Core.Math.CRGQ001A.GaussLegendreAB().
GaussLegendreAB()
static double[] double[] Weights Alaris.Core.Math.CRGQ001A.GaussLegendreAB (int n, double a, double b) inline static
Definition at line 122 of file CRGQ001A.cs.
References Alaris.Core.Math.CRGQ001A.GaussLegendre().
Referenced by Alaris.Core.Math.CRGQ001A.GaussLegendreIntegrate().
GaussLegendreIntegrate()
static double Alaris.Core.Math.CRGQ001A.GaussLegendreIntegrate (Func< double, double > f, double a, double b, int n = 16) inline static
Integrates a function using Gauss-Legendre quadrature.
Parameters
f Function to integrate.
a Left endpoint.
b Right endpoint.
n Number of quadrature points.
Returns
Approximate integral value.
Definition at line 147 of file CRGQ001A.cs.
References Alaris.Core.Math.CRGQ001A.GaussLegendreAB().
IntegrateWithScheme()
static double Alaris.Core.Math.CRGQ001A.IntegrateWithScheme (Func< double, double > f, (double[] Nodes, double[] Weights) scheme, double a, double b) inline static
Integrates using pre-computed nodes and weights (fastest method).
Parameters
f Function to integrate.
scheme Pre-computed (nodes, weights) from Schemes class.
a Left endpoint.
b Right endpoint.
Returns
Approximate integral value.
Definition at line 342 of file CRGQ001A.cs.
Referenced by Alaris.Core.Math.CRGQ001A.AdaptiveIntegrateRecursive(), Alaris.Core.Pricing.CREN004A.ComputeIntegralD(), Alaris.Core.Pricing.CREN004A.ComputeIntegralN(), Alaris.Core.Pricing.CREN004A.IntegrateDoubleBoundaryPremium(), and Alaris.Core.Pricing.CREN004A.IntegrateEarlyExercisePremium().
TanhSinhIntegrate()
static double Alaris.Core.Math.CRGQ001A.TanhSinhIntegrate (Func< double, double > f, double a, double b, double tolerance = 1e-10, int maxLevels = 10) inline static
Integrates a function using Tanh-Sinh (doubly exponential) quadrature.
Parameters
f Function to integrate.
a Left endpoint.
b Right endpoint.
tolerance Desired relative tolerance.
maxLevels Maximum refinement levels (default 10).
Returns
Approximate integral value.
Tanh-Sinh is excellent for integrands with endpoint singularities. Uses the transformation x = tanh(π/2 * sinh(t)) which clusters points near endpoints where singularities typically occur.
Definition at line 180 of file CRGQ001A.cs.
References Alaris.Core.Math.CRGQ001A.TanhSinhMaxSamples, Alaris.Core.Math.CRGQ001A.TanhSinhOverflowLimit, and Alaris.Core.Math.CRGQ001A.TanhSinhWeightCutoff.
Referenced by Alaris.Core.Pricing.CREN004A.ComputeIntegralD(), Alaris.Core.Pricing.CREN004A.ComputeIntegralN(), Alaris.Core.Pricing.CREN004A.IntegrateDoubleBoundaryPremium(), and Alaris.Core.Pricing.CREN004A.IntegrateEarlyExercisePremium().
Member Data Documentation
LegendreMaxIterations
const int Alaris.Core.Math.CRGQ001A.LegendreMaxIterations = 100 static private
Definition at line 26 of file CRGQ001A.cs.
Referenced by Alaris.Core.Math.CRGQ001A.GaussLegendre().
LegendreRootTolerance
const double Alaris.Core.Math.CRGQ001A.LegendreRootTolerance = 1e-15 static private
Definition at line 25 of file CRGQ001A.cs.
Referenced by Alaris.Core.Math.CRGQ001A.GaussLegendre().
MaxHermiteOrder
const int Alaris.Core.Math.CRGQ001A.MaxHermiteOrder = 32 static private
Definition at line 24 of file CRGQ001A.cs.
Referenced by Alaris.Core.Math.CRGQ001A.GaussHermite().
MaxLaguerreOrder
const int Alaris.Core.Math.CRGQ001A.MaxLaguerreOrder = 32 static private
Definition at line 23 of file CRGQ001A.cs.
Referenced by Alaris.Core.Math.CRGQ001A.GaussLaguerre().
MaxLegendreOrder
const int Alaris.Core.Math.CRGQ001A.MaxLegendreOrder = 64 static private
Definition at line 22 of file CRGQ001A.cs.
Referenced by Alaris.Core.Math.CRGQ001A.GaussLegendre().
Nodes
double [] Alaris.Core.Math.CRGQ001A.Nodes static
Computes Gauss-Legendre nodes and weights on [-1, 1].
Computes Gauss-Hermite nodes and weights for infinite integrals.
Computes Gauss-Laguerre nodes and weights for semi-infinite integrals.
Transforms Gauss-Legendre nodes and weights to interval [a, b].
Parameters
n Number of quadrature points (1 to 64).
Returns
Tuple of (nodes, weights) arrays.
Uses Newton-Raphson iteration to find roots of Legendre polynomials. Weights are computed from the derivative formula.
Parameters
n Number of quadrature points.
a Left endpoint.
b Right endpoint.
Returns
Transformed (nodes, weights) for integration over [a, b].
Parameters
n Number of quadrature points.
Returns
Nodes and weights for integrals over [0, ∞) with weight e^(-x).
Useful for integrals of the form ∫₀^∞ f(x) e^(-x) dx.
Parameters
n Number of quadrature points.
Returns
Nodes and weights for integrals over (-∞, ∞) with weight e^(-x²).
Useful for integrals of the form ∫_{-∞}^∞ f(x) e^(-x²) dx.
Definition at line 62 of file CRGQ001A.cs.
TanhSinhMaxSamples
const int Alaris.Core.Math.CRGQ001A.TanhSinhMaxSamples = 1000 static private
Definition at line 29 of file CRGQ001A.cs.
Referenced by Alaris.Core.Math.CRGQ001A.TanhSinhIntegrate().
TanhSinhOverflowLimit
const double Alaris.Core.Math.CRGQ001A.TanhSinhOverflowLimit = 350.0 static private
Definition at line 28 of file CRGQ001A.cs.
Referenced by Alaris.Core.Math.CRGQ001A.TanhSinhIntegrate().
TanhSinhWeightCutoff
const double Alaris.Core.Math.CRGQ001A.TanhSinhWeightCutoff = 1e-20 static private
Definition at line 27 of file CRGQ001A.cs.
Referenced by Alaris.Core.Math.CRGQ001A.TanhSinhIntegrate().
The documentation for this class was generated from the following file:
src/Alaris.Core/Math/CRGQ001A.cs