Alaris: Alaris.Test.Benchmark.TSBM003A Class Reference
Alaris.Test.Benchmark.TSBM003A Class Reference
Performance benchmarks comparing spectral collocation vs finite difference.
Public Member Functions
TSBM003A (ITestOutputHelper output)
void SingleOption_SpeedComparison ()
void Portfolio_ThroughputComparison ()
void AccuracySpeedTradeoff_SchemeComparison ()
void Greeks_TimingComparison ()
void MaturityScaling_Performance (double tau)
void RegimeCoverage_BothEnginesWork (double r, double q, bool isCall, string regime)
Private Attributes
readonly ITestOutputHelper _output
readonly CREN004A _spectralFast
readonly CREN004A _spectralAccurate
readonly CREN004A _spectralHighPrecision
readonly CREN002A _fdEngine
Detailed Description
Performance benchmarks comparing spectral collocation vs finite difference.
Definition at line 21 of file TSBM003A.cs.
Constructor & Destructor Documentation
TSBM003A()
Alaris.Test.Benchmark.TSBM003A.TSBM003A (ITestOutputHelper output) inline
Definition at line 29 of file TSBM003A.cs.
References Alaris.Test.Benchmark.TSBM003A._fdEngine, Alaris.Test.Benchmark.TSBM003A._output, Alaris.Test.Benchmark.TSBM003A._spectralAccurate, Alaris.Test.Benchmark.TSBM003A._spectralFast, and Alaris.Test.Benchmark.TSBM003A._spectralHighPrecision.
Member Function Documentation
AccuracySpeedTradeoff_SchemeComparison()
void Alaris.Test.Benchmark.TSBM003A.AccuracySpeedTradeoff_SchemeComparison () inline
Definition at line 144 of file TSBM003A.cs.
References Alaris.Test.Benchmark.TSBM003A._output, Alaris.Test.Benchmark.TSBM003A._spectralAccurate, Alaris.Test.Benchmark.TSBM003A._spectralFast, Alaris.Test.Benchmark.TSBM003A._spectralHighPrecision, and Alaris.Core.Pricing.CREN004A.Price().
Greeks_TimingComparison()
void Alaris.Test.Benchmark.TSBM003A.Greeks_TimingComparison () inline
Definition at line 184 of file TSBM003A.cs.
References Alaris.Test.Benchmark.TSBM003A._fdEngine, Alaris.Test.Benchmark.TSBM003A._output, Alaris.Test.Benchmark.TSBM003A._spectralAccurate, Alaris.Core.Pricing.CREN004A.Delta(), Alaris.Core.Pricing.CREN002A.Delta(), Alaris.Core.Pricing.CREN004A.Gamma(), Alaris.Core.Pricing.CREN002A.Gamma(), Alaris.Core.Pricing.CREN004A.Vega(), and Alaris.Core.Pricing.CREN002A.Vega().
MaturityScaling_Performance()
void Alaris.Test.Benchmark.TSBM003A.MaturityScaling_Performance (double tau) inline
Definition at line 225 of file TSBM003A.cs.
References Alaris.Test.Benchmark.TSBM003A._fdEngine, Alaris.Test.Benchmark.TSBM003A._output, Alaris.Test.Benchmark.TSBM003A._spectralAccurate, Alaris.Core.Pricing.CREN004A.Price(), and Alaris.Core.Pricing.CREN002A.Price().
Portfolio_ThroughputComparison()
void Alaris.Test.Benchmark.TSBM003A.Portfolio_ThroughputComparison () inline
Definition at line 94 of file TSBM003A.cs.
References Alaris.Test.Benchmark.TSBM003A._fdEngine, Alaris.Test.Benchmark.TSBM003A._output, Alaris.Test.Benchmark.TSBM003A._spectralAccurate, Alaris.Core.Pricing.CREN004A.Price(), Alaris.Core.Pricing.CREN002A.Price(), and Alaris.Core.Options.Spot.
RegimeCoverage_BothEnginesWork()
void Alaris.Test.Benchmark.TSBM003A.RegimeCoverage_BothEnginesWork (double r, double q, bool isCall, string regime) inline
Definition at line 256 of file TSBM003A.cs.
References Alaris.Test.Benchmark.TSBM003A._fdEngine, Alaris.Test.Benchmark.TSBM003A._output, Alaris.Test.Benchmark.TSBM003A._spectralAccurate, Alaris.Core.Pricing.CREN004A.Price(), and Alaris.Core.Pricing.CREN002A.Price().
SingleOption_SpeedComparison()
void Alaris.Test.Benchmark.TSBM003A.SingleOption_SpeedComparison () inline
Definition at line 41 of file TSBM003A.cs.
References Alaris.Test.Benchmark.TSBM003A._fdEngine, Alaris.Test.Benchmark.TSBM003A._output, Alaris.Test.Benchmark.TSBM003A._spectralAccurate, Alaris.Test.Benchmark.TSBM003A._spectralFast, Alaris.Core.Pricing.CREN004A.Price(), and Alaris.Core.Pricing.CREN002A.Price().
Member Data Documentation
_fdEngine
readonly CREN002A Alaris.Test.Benchmark.TSBM003A._fdEngine private
Definition at line 27 of file TSBM003A.cs.
Referenced by Alaris.Test.Benchmark.TSBM003A.TSBM003A(), Alaris.Test.Benchmark.TSBM003A.Greeks_TimingComparison(), Alaris.Test.Benchmark.TSBM003A.MaturityScaling_Performance(), Alaris.Test.Benchmark.TSBM003A.Portfolio_ThroughputComparison(), Alaris.Test.Benchmark.TSBM003A.RegimeCoverage_BothEnginesWork(), and Alaris.Test.Benchmark.TSBM003A.SingleOption_SpeedComparison().
_output
readonly ITestOutputHelper Alaris.Test.Benchmark.TSBM003A._output private
Definition at line 23 of file TSBM003A.cs.
Referenced by Alaris.Test.Benchmark.TSBM003A.TSBM003A(), Alaris.Test.Benchmark.TSBM003A.AccuracySpeedTradeoff_SchemeComparison(), Alaris.Test.Benchmark.TSBM003A.Greeks_TimingComparison(), Alaris.Test.Benchmark.TSBM003A.MaturityScaling_Performance(), Alaris.Test.Benchmark.TSBM003A.Portfolio_ThroughputComparison(), Alaris.Test.Benchmark.TSBM003A.RegimeCoverage_BothEnginesWork(), and Alaris.Test.Benchmark.TSBM003A.SingleOption_SpeedComparison().
_spectralAccurate
readonly CREN004A Alaris.Test.Benchmark.TSBM003A._spectralAccurate private
Definition at line 25 of file TSBM003A.cs.
Referenced by Alaris.Test.Benchmark.TSBM003A.TSBM003A(), Alaris.Test.Benchmark.TSBM003A.AccuracySpeedTradeoff_SchemeComparison(), Alaris.Test.Benchmark.TSBM003A.Greeks_TimingComparison(), Alaris.Test.Benchmark.TSBM003A.MaturityScaling_Performance(), Alaris.Test.Benchmark.TSBM003A.Portfolio_ThroughputComparison(), Alaris.Test.Benchmark.TSBM003A.RegimeCoverage_BothEnginesWork(), and Alaris.Test.Benchmark.TSBM003A.SingleOption_SpeedComparison().
_spectralFast
readonly CREN004A Alaris.Test.Benchmark.TSBM003A._spectralFast private
Definition at line 24 of file TSBM003A.cs.
Referenced by Alaris.Test.Benchmark.TSBM003A.TSBM003A(), Alaris.Test.Benchmark.TSBM003A.AccuracySpeedTradeoff_SchemeComparison(), and Alaris.Test.Benchmark.TSBM003A.SingleOption_SpeedComparison().
_spectralHighPrecision
readonly CREN004A Alaris.Test.Benchmark.TSBM003A._spectralHighPrecision private
Definition at line 26 of file TSBM003A.cs.
Referenced by Alaris.Test.Benchmark.TSBM003A.TSBM003A(), and Alaris.Test.Benchmark.TSBM003A.AccuracySpeedTradeoff_SchemeComparison().
The documentation for this class was generated from the following file:
src/Alaris.Test/Benchmark/TSBM003A.cs