Alaris: Alaris.Strategy.Core.STTM003A Class Reference
Alaris.Strategy.Core.STTM003A Class Reference
Production-grade trading calendar for calculating business days and market holidays. Supports US market holidays and can be extended for international markets. For production systems, this should be integrated with a market data provider's holiday calendar feed to handle unexpected market closures.
Static Public Member Functions
static int GetTradingDays (DateTime start, DateTime end, bool includeEndDate=false)
Calculates the number of trading days between two dates. Excludes weekends and US market holidays.
static bool IsTradingDay (DateTime date)
Checks if a given date is a trading day (not weekend or holiday).
static DateTime GetNextTradingDay (DateTime date)
Gets the next trading day after the given date.
static DateTime GetPreviousTradingDay (DateTime date)
Gets the previous trading day before the given date.
static DateTime AddTradingDays (DateTime date, int tradingDays)
Adds a specified number of trading days to a date.
static bool IsUSMarketHoliday (DateTime date)
Checks if a date is a US market holiday. Includes NYSE/NASDAQ observed holidays.
static double TradingDaysToYears (int tradingDays)
Converts trading days to annualized time.
static int YearsToTradingDays (double years)
Converts years to trading days.
Static Public Attributes
const int TradingDaysPerYear = 252
Standard trading days per year (252 for US markets).
Static Private Member Functions
static bool IsObservedHoliday (DateTime date, DateTime holiday)
Handles observed holidays when they fall on weekends. If Saturday, observed on Friday. If Sunday, observed on Monday.
static DateTime GetNthWeekdayOfMonth (int year, int month, DayOfWeek dayOfWeek, int n)
Gets the nth occurrence of a weekday in a month.
static DateTime GetLastWeekdayOfMonth (int year, int month, DayOfWeek dayOfWeek)
Gets the last occurrence of a weekday in a month.
static DateTime GetGoodFriday (int year)
Computes Good Friday using Meeus's algorithm for Easter.
static bool IsNationalDayOfMourning (DateTime date)
Checks for specific National Days of Mourning when markets were closed.
Detailed Description
Production-grade trading calendar for calculating business days and market holidays. Supports US market holidays and can be extended for international markets. For production systems, this should be integrated with a market data provider's holiday calendar feed to handle unexpected market closures.
Definition at line 11 of file STTM003A.cs.
Member Function Documentation
AddTradingDays()
static DateTime Alaris.Strategy.Core.STTM003A.AddTradingDays (DateTime date, int tradingDays) inline static
Adds a specified number of trading days to a date.
Parameters
date The starting date.
tradingDays Number of trading days to add (can be negative).
Returns
The resulting date.
Definition at line 102 of file STTM003A.cs.
References Alaris.Strategy.Core.STTM003A.IsTradingDay().
GetGoodFriday()
static DateTime Alaris.Strategy.Core.STTM003A.GetGoodFriday (int year) inline static private
Computes Good Friday using Meeus's algorithm for Easter.
Definition at line 264 of file STTM003A.cs.
Referenced by Alaris.Strategy.Core.STTM003A.IsUSMarketHoliday().
GetLastWeekdayOfMonth()
static DateTime Alaris.Strategy.Core.STTM003A.GetLastWeekdayOfMonth (int year, int month, DayOfWeek dayOfWeek) inline static private
Gets the last occurrence of a weekday in a month.
Definition at line 254 of file STTM003A.cs.
Referenced by Alaris.Strategy.Core.STTM003A.IsUSMarketHoliday().
GetNextTradingDay()
static DateTime Alaris.Strategy.Core.STTM003A.GetNextTradingDay (DateTime date) inline static
Gets the next trading day after the given date.
Parameters
date The starting date.
Returns
The next trading day.
Definition at line 71 of file STTM003A.cs.
References Alaris.Strategy.Core.STTM003A.IsTradingDay().
GetNthWeekdayOfMonth()
static DateTime Alaris.Strategy.Core.STTM003A.GetNthWeekdayOfMonth (int year, int month, DayOfWeek dayOfWeek, int n) inline static private
Gets the nth occurrence of a weekday in a month.
Definition at line 243 of file STTM003A.cs.
Referenced by Alaris.Strategy.Core.STTM003A.IsUSMarketHoliday().
GetPreviousTradingDay()
static DateTime Alaris.Strategy.Core.STTM003A.GetPreviousTradingDay (DateTime date) inline static
Gets the previous trading day before the given date.
Parameters
date The starting date.
Returns
The previous trading day.
Definition at line 86 of file STTM003A.cs.
References Alaris.Strategy.Core.STTM003A.IsTradingDay().
GetTradingDays()
static int Alaris.Strategy.Core.STTM003A.GetTradingDays (DateTime start, DateTime end, bool includeEndDate = false) inline static
Calculates the number of trading days between two dates. Excludes weekends and US market holidays.
Parameters
start Start date (inclusive).
end End date (exclusive).
includeEndDate Whether to include the end date in the count.
Returns
Number of trading days.
Definition at line 26 of file STTM003A.cs.
References Alaris.Strategy.Core.STTM003A.IsTradingDay().
Referenced by Alaris.Strategy.Core.STTM004A.CalculateTradingDays().
IsNationalDayOfMourning()
static bool Alaris.Strategy.Core.STTM003A.IsNationalDayOfMourning (DateTime date) inline static private
Checks for specific National Days of Mourning when markets were closed.
Definition at line 290 of file STTM003A.cs.
Referenced by Alaris.Strategy.Core.STTM003A.IsUSMarketHoliday().
IsObservedHoliday()
static bool Alaris.Strategy.Core.STTM003A.IsObservedHoliday (DateTime date, DateTime holiday) inline static private
Handles observed holidays when they fall on weekends. If Saturday, observed on Friday. If Sunday, observed on Monday.
Definition at line 218 of file STTM003A.cs.
Referenced by Alaris.Strategy.Core.STTM003A.IsUSMarketHoliday().
IsTradingDay()
static bool Alaris.Strategy.Core.STTM003A.IsTradingDay (DateTime date) inline static
Checks if a given date is a trading day (not weekend or holiday).
Parameters
date The date to check.
Returns
True if the date is a trading day.
Definition at line 54 of file STTM003A.cs.
References Alaris.Strategy.Core.STTM003A.IsUSMarketHoliday().
Referenced by Alaris.Strategy.Core.STTM003A.AddTradingDays(), Alaris.Strategy.Core.STTM003A.GetNextTradingDay(), Alaris.Strategy.Core.STTM003A.GetPreviousTradingDay(), and Alaris.Strategy.Core.STTM003A.GetTradingDays().
IsUSMarketHoliday()
static bool Alaris.Strategy.Core.STTM003A.IsUSMarketHoliday (DateTime date) inline static
Checks if a date is a US market holiday. Includes NYSE/NASDAQ observed holidays.
Parameters
date The date to check.
Returns
True if the date is a US market holiday.
Definition at line 126 of file STTM003A.cs.
References Alaris.Strategy.Core.STTM003A.GetGoodFriday(), Alaris.Strategy.Core.STTM003A.GetLastWeekdayOfMonth(), Alaris.Strategy.Core.STTM003A.GetNthWeekdayOfMonth(), Alaris.Strategy.Core.STTM003A.IsNationalDayOfMourning(), and Alaris.Strategy.Core.STTM003A.IsObservedHoliday().
Referenced by Alaris.Strategy.Core.STTM003A.IsTradingDay().
TradingDaysToYears()
static double Alaris.Strategy.Core.STTM003A.TradingDaysToYears (int tradingDays) inline static
Converts trading days to annualized time.
Parameters
tradingDays Number of trading days.
Returns
Time in years.
Definition at line 348 of file STTM003A.cs.
References Alaris.Strategy.Core.STTM003A.TradingDaysPerYear.
YearsToTradingDays()
static int Alaris.Strategy.Core.STTM003A.YearsToTradingDays (double years) inline static
Converts years to trading days.
Parameters
years Time in years.
Returns
Number of trading days.
Definition at line 358 of file STTM003A.cs.
References Alaris.Strategy.Core.STTM003A.TradingDaysPerYear.
Member Data Documentation
TradingDaysPerYear
const int Alaris.Strategy.Core.STTM003A.TradingDaysPerYear = 252 static
Standard trading days per year (252 for US markets).
Definition at line 16 of file STTM003A.cs.
Referenced by Alaris.Strategy.Core.STTM003A.TradingDaysToYears(), and Alaris.Strategy.Core.STTM003A.YearsToTradingDays().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Core/STTM003A.cs