Alaris: Alaris.Core.Validation.AlgorithmBounds Class Reference
Alaris.Core.Validation.AlgorithmBounds Class Reference
Algorithm bounds constants for validation.
Static Public Member Functions
static void ValidateVolatility (double sigma, string paramName="sigma")
Validates volatility is within bounds.
static void ValidateTimeToExpiry (double tau, string paramName="tau")
Validates time to expiry is within bounds.
static void ValidatePositivePrice (double price, string paramName="price")
Validates price is positive.
static void ValidateMoneyness (double spot, double strike, string spotParamName="spot")
Validates moneyness is within bounds.
static void ValidateRate (double rate, string paramName="rate")
Validates rate is a finite number (allows negative rates).
static void ValidateDoubleBoundaryInputs (double spot, double strike, double maturity, double rate, double dividendYield, double volatility)
Validates all inputs required for double boundary American option pricing. This is the single entry point for bounds validation before numerical algorithms.
static bool TryValidateDoubleBoundaryInputs (double spot, double strike, double maturity, double rate, double dividendYield, double volatility, out string? validationError)
Returns whether inputs are within bounds without throwing.
Static Public Attributes
const double MinVolatility = 0.001
Minimum volatility: 0.1% annualized.
const double MaxVolatility = 5.0
Maximum volatility: 500% annualized.
const double MinTimeToExpiry = 1.0 / 252.0
Minimum time to expiry: 1 trading day.
const double MaxTimeToExpiry = 30.0
Maximum time to expiry: 30 years.
const double MinPositivePrice = 1e-10
Minimum positive price.
const double MaxLogMoneyness = 3.0
Maximum log-moneyness |ln(K/S)|.
const int NewtonMaxIterations = 50
Newton-Raphson max iterations.
const int LMMaxIterations = 200
Levenberg-Marquardt max iterations.
const int BisectionMaxIterations = 100
Bisection max iterations.
const int SuperHalleyMaxIterations = 25
Super Halley max iterations.
const int IntegrationMaxChunks = 1000
Gauss-Legendre max chunks.
const double IVTolerance = 1e-8
IV solver tolerance.
const double IntegrationTolerance = 1e-8
Integration tolerance.
const double RootFindingTolerance = 1e-10
Root-finding tolerance.
const double MinVegaForNewton = 1e-15
Minimum vega for Newton IV solver.
Detailed Description
Algorithm bounds constants for validation.
Definition at line 151 of file CRVL001A.cs.
Member Function Documentation
TryValidateDoubleBoundaryInputs()
static bool Alaris.Core.Validation.AlgorithmBounds.TryValidateDoubleBoundaryInputs (double spot, double strike, double maturity, double rate, double dividendYield, double volatility, out string? validationError) inline static
Returns whether inputs are within bounds without throwing.
Returns
True if all inputs are valid, false otherwise.
Definition at line 310 of file CRVL001A.cs.
References Alaris.Core.Validation.AlgorithmBounds.ValidateDoubleBoundaryInputs().
Referenced by Alaris.Test.Unit.TSUN032A.TryValidateDoubleBoundaryInputs_InvalidInputs_ReturnsFalseWithError(), and Alaris.Test.Unit.TSUN032A.TryValidateDoubleBoundaryInputs_ValidInputs_ReturnsTrue().
ValidateDoubleBoundaryInputs()
static void Alaris.Core.Validation.AlgorithmBounds.ValidateDoubleBoundaryInputs (double spot, double strike, double maturity, double rate, double dividendYield, double volatility) inline static
Validates all inputs required for double boundary American option pricing. This is the single entry point for bounds validation before numerical algorithms.
Parameters
spot Underlying spot price.
strike Option strike price.
maturity Time to expiry in years.
rate Risk-free rate (can be negative).
dividendYield Continuous dividend yield (can be negative).
volatility Implied volatility.
Exceptions
BoundsViolationException Thrown if any parameter is out of bounds.
Bounds validated:
Spot: S > 0
Strike: K > 0
Moneyness: |ln(K/S)| ≤ 3
Maturity: τ ∈ [1/252, 30] years
Volatility: σ ∈ [0.001, 5.0]
Rate: finite (allows negative)
Dividend: finite (allows negative)
In the double boundary regime (q < r < 0), these bounds ensure the QD+ algorithm and Kim integral converge deterministically.
Definition at line 280 of file CRVL001A.cs.
References Alaris.Core.Validation.AlgorithmBounds.ValidateMoneyness(), Alaris.Core.Validation.AlgorithmBounds.ValidatePositivePrice(), Alaris.Core.Validation.AlgorithmBounds.ValidateRate(), Alaris.Core.Validation.AlgorithmBounds.ValidateTimeToExpiry(), and Alaris.Core.Validation.AlgorithmBounds.ValidateVolatility().
Referenced by Alaris.Core.Pricing.CRAP001A.CRAP001A(), Alaris.Core.Pricing.CRSL001A.CRSL001A(), Alaris.Core.Pricing.CRSL002A.CRSL002A(), Alaris.Test.Integration.TSEE001A.BoundsValidation_IntegrationWithDoubleSolver(), Alaris.Test.Integration.TSEE001A.BoundsValidation_InvalidVolatility_Rejected(), Alaris.Core.Validation.AlgorithmBounds.TryValidateDoubleBoundaryInputs(), Alaris.Test.Unit.TSUN032A.ValidateDoubleBoundaryInputs_ExtremeMoneynessS_ThrowsBoundsViolation(), Alaris.Test.Unit.TSUN032A.ValidateDoubleBoundaryInputs_InvalidMaturity_ThrowsBoundsViolation(), Alaris.Test.Unit.TSUN032A.ValidateDoubleBoundaryInputs_InvalidRates_ThrowsBoundsViolation(), Alaris.Test.Unit.TSUN032A.ValidateDoubleBoundaryInputs_InvalidSpot_ThrowsBoundsViolation(), Alaris.Test.Unit.TSUN032A.ValidateDoubleBoundaryInputs_InvalidVolatility_ThrowsBoundsViolation(), Alaris.Test.Unit.TSUN032A.ValidateDoubleBoundaryInputs_NegativeRates_DoesNotThrow(), and Alaris.Test.Unit.TSUN032A.ValidateDoubleBoundaryInputs_ValidInputs_DoesNotThrow().
ValidateMoneyness()
static void Alaris.Core.Validation.AlgorithmBounds.ValidateMoneyness (double spot, double strike, string spotParamName = "spot") inline static
Validates moneyness is within bounds.
Definition at line 227 of file CRVL001A.cs.
References Alaris.Core.Validation.AlgorithmBounds.MaxLogMoneyness.
Referenced by Alaris.Core.Validation.AlgorithmBounds.ValidateDoubleBoundaryInputs().
ValidatePositivePrice()
static void Alaris.Core.Validation.AlgorithmBounds.ValidatePositivePrice (double price, string paramName = "price") inline static
Validates price is positive.
Definition at line 218 of file CRVL001A.cs.
References Alaris.Core.Validation.AlgorithmBounds.MinPositivePrice.
Referenced by Alaris.Core.Validation.AlgorithmBounds.ValidateDoubleBoundaryInputs().
ValidateRate()
static void Alaris.Core.Validation.AlgorithmBounds.ValidateRate (double rate, string paramName = "rate") inline static
Validates rate is a finite number (allows negative rates).
Definition at line 243 of file CRVL001A.cs.
Referenced by Alaris.Core.Validation.AlgorithmBounds.ValidateDoubleBoundaryInputs().
ValidateTimeToExpiry()
static void Alaris.Core.Validation.AlgorithmBounds.ValidateTimeToExpiry (double tau, string paramName = "tau") inline static
Validates time to expiry is within bounds.
Definition at line 209 of file CRVL001A.cs.
References Alaris.Core.Validation.AlgorithmBounds.MaxTimeToExpiry, and Alaris.Core.Validation.AlgorithmBounds.MinTimeToExpiry.
Referenced by Alaris.Core.Validation.AlgorithmBounds.ValidateDoubleBoundaryInputs(), and Alaris.Test.Unit.TSUN032A.ValidateTimeToExpiry_BoundsCheck().
ValidateVolatility()
static void Alaris.Core.Validation.AlgorithmBounds.ValidateVolatility (double sigma, string paramName = "sigma") inline static
Validates volatility is within bounds.
Definition at line 200 of file CRVL001A.cs.
References Alaris.Core.Validation.AlgorithmBounds.MaxVolatility, and Alaris.Core.Validation.AlgorithmBounds.MinVolatility.
Referenced by Alaris.Core.Validation.AlgorithmBounds.ValidateDoubleBoundaryInputs(), and Alaris.Test.Unit.TSUN032A.ValidateVolatility_BoundsCheck().
Member Data Documentation
BisectionMaxIterations
const int Alaris.Core.Validation.AlgorithmBounds.BisectionMaxIterations = 100 static
Bisection max iterations.
Definition at line 178 of file CRVL001A.cs.
IntegrationMaxChunks
const int Alaris.Core.Validation.AlgorithmBounds.IntegrationMaxChunks = 1000 static
Gauss-Legendre max chunks.
Definition at line 184 of file CRVL001A.cs.
IntegrationTolerance
const double Alaris.Core.Validation.AlgorithmBounds.IntegrationTolerance = 1e-8 static
Integration tolerance.
Definition at line 190 of file CRVL001A.cs.
IVTolerance
const double Alaris.Core.Validation.AlgorithmBounds.IVTolerance = 1e-8 static
IV solver tolerance.
Definition at line 187 of file CRVL001A.cs.
LMMaxIterations
const int Alaris.Core.Validation.AlgorithmBounds.LMMaxIterations = 200 static
Levenberg-Marquardt max iterations.
Definition at line 175 of file CRVL001A.cs.
MaxLogMoneyness
const double Alaris.Core.Validation.AlgorithmBounds.MaxLogMoneyness = 3.0 static
Maximum log-moneyness |ln(K/S)|.
Definition at line 169 of file CRVL001A.cs.
Referenced by Alaris.Core.Validation.AlgorithmBounds.ValidateMoneyness().
MaxTimeToExpiry
const double Alaris.Core.Validation.AlgorithmBounds.MaxTimeToExpiry = 30.0 static
Maximum time to expiry: 30 years.
Definition at line 163 of file CRVL001A.cs.
Referenced by Alaris.Core.Validation.AlgorithmBounds.ValidateTimeToExpiry().
MaxVolatility
const double Alaris.Core.Validation.AlgorithmBounds.MaxVolatility = 5.0 static
Maximum volatility: 500% annualized.
Definition at line 157 of file CRVL001A.cs.
Referenced by Alaris.Core.Validation.AlgorithmBounds.ValidateVolatility().
MinPositivePrice
const double Alaris.Core.Validation.AlgorithmBounds.MinPositivePrice = 1e-10 static
Minimum positive price.
Definition at line 166 of file CRVL001A.cs.
Referenced by Alaris.Core.Validation.AlgorithmBounds.ValidatePositivePrice().
MinTimeToExpiry
const double Alaris.Core.Validation.AlgorithmBounds.MinTimeToExpiry = 1.0 / 252.0 static
Minimum time to expiry: 1 trading day.
Definition at line 160 of file CRVL001A.cs.
Referenced by Alaris.Core.Validation.AlgorithmBounds.ValidateTimeToExpiry().
MinVegaForNewton
const double Alaris.Core.Validation.AlgorithmBounds.MinVegaForNewton = 1e-15 static
Minimum vega for Newton IV solver.
Definition at line 196 of file CRVL001A.cs.
MinVolatility
const double Alaris.Core.Validation.AlgorithmBounds.MinVolatility = 0.001 static
Minimum volatility: 0.1% annualized.
Definition at line 154 of file CRVL001A.cs.
Referenced by Alaris.Core.Validation.AlgorithmBounds.ValidateVolatility().
NewtonMaxIterations
const int Alaris.Core.Validation.AlgorithmBounds.NewtonMaxIterations = 50 static
Newton-Raphson max iterations.
Definition at line 172 of file CRVL001A.cs.
RootFindingTolerance
const double Alaris.Core.Validation.AlgorithmBounds.RootFindingTolerance = 1e-10 static
Root-finding tolerance.
Definition at line 193 of file CRVL001A.cs.
SuperHalleyMaxIterations
const int Alaris.Core.Validation.AlgorithmBounds.SuperHalleyMaxIterations = 25 static
Super Halley max iterations.
Definition at line 181 of file CRVL001A.cs.
The documentation for this class was generated from the following file:
src/Alaris.Core/Validation/CRVL001A.cs