Alaris: Alaris.Strategy.Risk.STMG001A Class Reference
Alaris.Strategy.Risk.STMG001A Class Reference sealed
Provides maturity-based position filtering to avoid near-expiry regime.
Public Member Functions
STMG001A (ITradingCalendar? calendar=null, ILogger< STMG001A >? logger=null)
Initialises a new maturity guard with default thresholds.
STMG001A (double minEntryMaturity, double forceExitMaturity, ITradingCalendar? calendar=null, ILogger< STMG001A >? logger=null)
Initialises a new maturity guard with custom thresholds.
MaturityEntryResult EvaluateEntry (string symbol, double timeToExpiry)
Evaluates whether a position entry should be allowed based on maturity.
MaturityExitResult EvaluateExit (string symbol, double timeToExpiry)
Evaluates whether a position should be force-exited based on maturity.
double CalculateTimeToExpiry (DateTime expiryDate, DateTime currentDate)
Converts dates to time-to-expiry in years using trading calendar.
Static Public Member Functions
static double CalculateTimeToExpiryApproximate (DateTime expiryDate, DateTime currentDate)
Static fallback for calculating time-to-expiry without a calendar instance. Uses 5/7 approximation for calendar-to-trading day conversion.
Static Public Attributes
const double DefaultMinEntryMaturity = 10.0 / 252.0
Minimum time-to-expiry for entering new positions (in years). Default: 10/252 ≈ 2 weeks.
const double DefaultForceExitMaturity = 5.0 / 252.0
Maturity threshold for force exit (in years). Default: 5/252 ≈ 1 week.
const double NearExpiryThreshold = 3.0 / 252.0
Near-expiry handler threshold (DBEX001A). Below this, QD+ is numerically unstable.
Private Member Functions
void SafeLog (LogLevel level, string message, params object[] args)
Safely executes logging operation with fault isolation (Rule 15). Prevents logging failures from crashing critical paths.
Private Attributes
readonly double _minEntryMaturity
readonly double _forceExitMaturity
readonly? ITradingCalendar _calendar
readonly? ILogger< STMG001A > _logger
Detailed Description
Provides maturity-based position filtering to avoid near-expiry regime.
Definition at line 12 of file STMG001A.cs.
Constructor & Destructor Documentation
STMG001A() [1/2]
Alaris.Strategy.Risk.STMG001A.STMG001A (ITradingCalendar? calendar = null, ILogger< STMG001A >? logger = null) inline
Initialises a new maturity guard with default thresholds.
Parameters
calendar Optional trading calendar for accurate business days.
logger Optional logger instance.
Definition at line 42 of file STMG001A.cs.
STMG001A() [2/2]
Alaris.Strategy.Risk.STMG001A.STMG001A (double minEntryMaturity, double forceExitMaturity, ITradingCalendar? calendar = null, ILogger< STMG001A >? logger = null) inline
Initialises a new maturity guard with custom thresholds.
Parameters
minEntryMaturity Minimum maturity for entry.
forceExitMaturity Maturity threshold for force exit.
calendar Optional trading calendar for accurate business days.
logger Optional logger instance.
Definition at line 54 of file STMG001A.cs.
References Alaris.Strategy.Risk.STMG001A._calendar, Alaris.Strategy.Risk.STMG001A._forceExitMaturity, Alaris.Strategy.Risk.STMG001A._logger, and Alaris.Strategy.Risk.STMG001A._minEntryMaturity.
Member Function Documentation
CalculateTimeToExpiry()
double Alaris.Strategy.Risk.STMG001A.CalculateTimeToExpiry (DateTime expiryDate, DateTime currentDate) inline
Converts dates to time-to-expiry in years using trading calendar.
Parameters
expiryDate Option expiration date.
currentDate Current evaluation date.
Returns
Time to expiry in years (trading days / 252).
Definition at line 179 of file STMG001A.cs.
References Alaris.Strategy.Risk.STMG001A._calendar, and Alaris.Strategy.Calendar.ITradingCalendar.GetTimeToExpiryInYears().
CalculateTimeToExpiryApproximate()
static double Alaris.Strategy.Risk.STMG001A.CalculateTimeToExpiryApproximate (DateTime expiryDate, DateTime currentDate) inline static
Static fallback for calculating time-to-expiry without a calendar instance. Uses 5/7 approximation for calendar-to-trading day conversion.
Parameters
expiryDate Option expiration date.
currentDate Current evaluation date.
Returns
Time to expiry in years (approximate).
Definition at line 201 of file STMG001A.cs.
Referenced by Alaris.Test.Unit.TSUN027A.STMG001A_CalculateTimeToExpiryApproximate_PastExpiry_ReturnsNonPositive(), and Alaris.Test.Unit.TSUN027A.STMG001A_CalculateTimeToExpiryApproximate_ReturnsReasonableValue().
EvaluateEntry()
MaturityEntryResult Alaris.Strategy.Risk.STMG001A.EvaluateEntry (string symbol, double timeToExpiry) inline
Evaluates whether a position entry should be allowed based on maturity.
Parameters
symbol Security symbol for logging.
timeToExpiry Time to expiration in years.
Returns
Entry evaluation result.
Definition at line 81 of file STMG001A.cs.
References Alaris.Strategy.Risk.STMG001A._forceExitMaturity, Alaris.Strategy.Risk.STMG001A._minEntryMaturity, Alaris.Strategy.Risk.MaturityEntryResult, and Alaris.Strategy.Risk.STMG001A.SafeLog().
EvaluateExit()
MaturityExitResult Alaris.Strategy.Risk.STMG001A.EvaluateExit (string symbol, double timeToExpiry) inline
Evaluates whether a position should be force-exited based on maturity.
Parameters
symbol Security symbol for logging.
timeToExpiry Time to expiration in years.
Returns
Exit evaluation result.
Definition at line 128 of file STMG001A.cs.
References Alaris.Strategy.Risk.STMG001A._forceExitMaturity, Alaris.Strategy.Risk.STMG001A._minEntryMaturity, Alaris.Strategy.Risk.MaturityExitResult, Alaris.Strategy.Risk.STMG001A.NearExpiryThreshold, and Alaris.Strategy.Risk.STMG001A.SafeLog().
SafeLog()
void Alaris.Strategy.Risk.STMG001A.SafeLog (LogLevel level, string message, params object[] args) inline private
Safely executes logging operation with fault isolation (Rule 15). Prevents logging failures from crashing critical paths.
Definition at line 216 of file STMG001A.cs.
References Alaris.Strategy.Risk.STMG001A._logger.
Referenced by Alaris.Strategy.Risk.STMG001A.EvaluateEntry(), and Alaris.Strategy.Risk.STMG001A.EvaluateExit().
Member Data Documentation
_calendar
readonly? ITradingCalendar Alaris.Strategy.Risk.STMG001A._calendar private
Definition at line 34 of file STMG001A.cs.
Referenced by Alaris.Strategy.Risk.STMG001A.STMG001A(), and Alaris.Strategy.Risk.STMG001A.CalculateTimeToExpiry().
_forceExitMaturity
readonly double Alaris.Strategy.Risk.STMG001A._forceExitMaturity private
Definition at line 33 of file STMG001A.cs.
Referenced by Alaris.Strategy.Risk.STMG001A.STMG001A(), Alaris.Strategy.Risk.STMG001A.EvaluateEntry(), and Alaris.Strategy.Risk.STMG001A.EvaluateExit().
_logger
readonly? ILogger<STMG001A> Alaris.Strategy.Risk.STMG001A._logger private
Definition at line 35 of file STMG001A.cs.
Referenced by Alaris.Strategy.Risk.STMG001A.STMG001A(), and Alaris.Strategy.Risk.STMG001A.SafeLog().
_minEntryMaturity
readonly double Alaris.Strategy.Risk.STMG001A._minEntryMaturity private
Definition at line 32 of file STMG001A.cs.
Referenced by Alaris.Strategy.Risk.STMG001A.STMG001A(), Alaris.Strategy.Risk.STMG001A.EvaluateEntry(), and Alaris.Strategy.Risk.STMG001A.EvaluateExit().
DefaultForceExitMaturity
const double Alaris.Strategy.Risk.STMG001A.DefaultForceExitMaturity = 5.0 / 252.0 static
Maturity threshold for force exit (in years). Default: 5/252 ≈ 1 week.
Definition at line 24 of file STMG001A.cs.
DefaultMinEntryMaturity
const double Alaris.Strategy.Risk.STMG001A.DefaultMinEntryMaturity = 10.0 / 252.0 static
Minimum time-to-expiry for entering new positions (in years). Default: 10/252 ≈ 2 weeks.
Definition at line 18 of file STMG001A.cs.
NearExpiryThreshold
const double Alaris.Strategy.Risk.STMG001A.NearExpiryThreshold = 3.0 / 252.0 static
Near-expiry handler threshold (DBEX001A). Below this, QD+ is numerically unstable.
Definition at line 30 of file STMG001A.cs.
Referenced by Alaris.Strategy.Risk.STMG001A.EvaluateExit().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Risk/STMG001A.cs