Alaris: Alaris.Infrastructure.Protocol.Workflow.TransitionResult< TState, TEvent > Struct Template Reference
Alaris.Infrastructure.Protocol.Workflow.TransitionResult< TState, TEvent > Struct Template Reference
Result of a state transition attempt.
Static Public Member Functions
static TransitionResult< TState, TEvent > Success (TState from, TEvent on, TState to)
Creates a successful transition result.
static TransitionResult< TState, TEvent > InvalidTransition (TState from, TEvent on)
Creates an invalid transition result (no transition defined).
static TransitionResult< TState, TEvent > GuardFailed (TState from, TEvent on, TState to)
Creates a guard-failed result.
static TransitionResult< TState, TEvent > ActionFailed (TState from, TEvent on, Exception ex, string? context=null)
Creates an action-failed result.
Properties
bool Succeeded [get]
Whether the transition succeeded.
TState? FromState [get]
Source state (before transition).
TEvent? Event [get]
Event that triggered the transition.
TState? ToState [get]
Target state (after transition, if successful).
string Message [get]
Human-readable message describing the result.
Exception? Exception [get]
Exception if action failed.
Detailed Description
Result of a state transition attempt.
Template Parameters
TState State type.
TEvent Event type.
Type Constraints
TState : struct
TState : Enum
TEvent : struct
TEvent : Enum
Definition at line 602 of file PLWF001A.cs.
Member Function Documentation
ActionFailed()
static TransitionResult< TState, TEvent > Alaris.Infrastructure.Protocol.Workflow.TransitionResult< TState, TEvent >.ActionFailed (TState from, TEvent on, Exception ex, string? context = null) static
Creates an action-failed result.
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Fire().
GuardFailed()
static TransitionResult< TState, TEvent > Alaris.Infrastructure.Protocol.Workflow.TransitionResult< TState, TEvent >.GuardFailed (TState from, TEvent on, TState to) static
Creates a guard-failed result.
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Fire().
InvalidTransition()
static TransitionResult< TState, TEvent > Alaris.Infrastructure.Protocol.Workflow.TransitionResult< TState, TEvent >.InvalidTransition (TState from, TEvent on) static
Creates an invalid transition result (no transition defined).
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Fire().
Success()
static TransitionResult< TState, TEvent > Alaris.Infrastructure.Protocol.Workflow.TransitionResult< TState, TEvent >.Success (TState from, TEvent on, TState to) static
Creates a successful transition result.
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Fire().
Property Documentation
Event
TEvent? Alaris.Infrastructure.Protocol.Workflow.TransitionResult< TState, TEvent >.Event get
Event that triggered the transition.
Definition at line 613 of file PLWF001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.RecordTransition().
Exception
Exception? Alaris.Infrastructure.Protocol.Workflow.TransitionResult< TState, TEvent >.Exception get
Exception if action failed.
Definition at line 622 of file PLWF001A.cs.
FromState
TState? Alaris.Infrastructure.Protocol.Workflow.TransitionResult< TState, TEvent >.FromState get
Source state (before transition).
Definition at line 610 of file PLWF001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.RecordTransition().
Message
string Alaris.Infrastructure.Protocol.Workflow.TransitionResult< TState, TEvent >.Message get
Human-readable message describing the result.
Definition at line 619 of file PLWF001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.RecordTransition().
Succeeded
bool Alaris.Infrastructure.Protocol.Workflow.TransitionResult< TState, TEvent >.Succeeded get
Whether the transition succeeded.
Definition at line 607 of file PLWF001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.RecordTransition().
ToState
TState? Alaris.Infrastructure.Protocol.Workflow.TransitionResult< TState, TEvent >.ToState get
Target state (after transition, if successful).
Definition at line 616 of file PLWF001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.RecordTransition().
The documentation for this struct was generated from the following file:
src/Alaris.Infrastructure/Protocol/Workflow/PLWF001A.cs