Alaris: Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests Class Reference
Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests Class Reference
Mathematical invariant tests for the unified American option pricing engine.
Public Member Functions
CREN003AInvariantTests (ITestOutputHelper output)
void Invariant_AmericanPriceGreaterThanOrEqualToEuropean (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType)
void Invariant_AmericanPriceGreaterThanOrEqualToIntrinsic (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType)
void Invariant_DeterministicPricing (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType)
void Invariant_DeltaInValidRange (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType)
void Invariant_GammaNonNegative (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType)
void Invariant_VegaNonNegative (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType)
void Invariant_AllRegimesProduceValidPrices (double r, double q, OptionType optionType, string description)
Static Private Member Functions
static double BlackScholesEuropean (double spot, double strike, double tau, double r, double q, double sigma, bool isCall)
static double NormalCDF (double x)
static double Erf (double x)
Private Attributes
readonly ITestOutputHelper _output
readonly CREN003A _engine
Detailed Description
Mathematical invariant tests for the unified American option pricing engine.
Definition at line 21 of file CREN003AInvariantTests.cs.
Constructor & Destructor Documentation
CREN003AInvariantTests()
Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.CREN003AInvariantTests (ITestOutputHelper output) inline
Definition at line 26 of file CREN003AInvariantTests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests._engine, and Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests._output.
Member Function Documentation
BlackScholesEuropean()
static double Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.BlackScholesEuropean (double spot, double strike, double tau, double r, double q, double sigma, bool isCall) inline static private
Definition at line 181 of file CREN003AInvariantTests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.NormalCDF().
Referenced by Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_AmericanPriceGreaterThanOrEqualToEuropean().
Erf()
static double Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Erf (double x) inline static private
Definition at line 208 of file CREN003AInvariantTests.cs.
Referenced by Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.NormalCDF().
Invariant_AllRegimesProduceValidPrices()
void Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_AllRegimesProduceValidPrices (double r, double q, OptionType optionType, string description) inline
Definition at line 168 of file CREN003AInvariantTests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests._engine, Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests._output, and Alaris.Core.Pricing.CREN003A.Price().
Invariant_AmericanPriceGreaterThanOrEqualToEuropean()
void Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_AmericanPriceGreaterThanOrEqualToEuropean (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType) inline
Definition at line 43 of file CREN003AInvariantTests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests._engine, Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests._output, Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.BlackScholesEuropean(), and Alaris.Core.Pricing.CREN003A.Price().
Invariant_AmericanPriceGreaterThanOrEqualToIntrinsic()
void Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_AmericanPriceGreaterThanOrEqualToIntrinsic (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType) inline
Definition at line 68 of file CREN003AInvariantTests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests._engine, Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests._output, and Alaris.Core.Pricing.CREN003A.Price().
Invariant_DeltaInValidRange()
void Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_DeltaInValidRange (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType) inline
Definition at line 114 of file CREN003AInvariantTests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests._engine, Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests._output, and Alaris.Core.Pricing.CREN003A.Delta().
Invariant_DeterministicPricing()
void Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_DeterministicPricing (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType) inline
Definition at line 89 of file CREN003AInvariantTests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests._engine, Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests._output, and Alaris.Core.Pricing.CREN003A.Price().
Invariant_GammaNonNegative()
void Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_GammaNonNegative (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType) inline
Definition at line 136 of file CREN003AInvariantTests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests._engine, Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests._output, and Alaris.Core.Pricing.CREN003A.Gamma().
Invariant_VegaNonNegative()
void Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_VegaNonNegative (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType) inline
Definition at line 150 of file CREN003AInvariantTests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests._engine, Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests._output, and Alaris.Core.Pricing.CREN003A.Vega().
NormalCDF()
static double Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.NormalCDF (double x) inline static private
Definition at line 203 of file CREN003AInvariantTests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Erf().
Referenced by Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.BlackScholesEuropean().
Member Data Documentation
_engine
readonly CREN003A Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests._engine private
Definition at line 24 of file CREN003AInvariantTests.cs.
Referenced by Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.CREN003AInvariantTests(), Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_AllRegimesProduceValidPrices(), Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_AmericanPriceGreaterThanOrEqualToEuropean(), Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_AmericanPriceGreaterThanOrEqualToIntrinsic(), Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_DeltaInValidRange(), Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_DeterministicPricing(), Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_GammaNonNegative(), and Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_VegaNonNegative().
_output
readonly ITestOutputHelper Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests._output private
Definition at line 23 of file CREN003AInvariantTests.cs.
Referenced by Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.CREN003AInvariantTests(), Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_AllRegimesProduceValidPrices(), Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_AmericanPriceGreaterThanOrEqualToEuropean(), Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_AmericanPriceGreaterThanOrEqualToIntrinsic(), Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_DeltaInValidRange(), Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_DeterministicPricing(), Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_GammaNonNegative(), and Alaris.Test.Unit.Core.Pricing.CREN003AInvariantTests.Invariant_VegaNonNegative().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/Core/Pricing/CREN003AInvariantTests.cs