Alaris: Alaris.Test.Unit.STRK003ATests Class Reference
Alaris.Test.Unit.STRK003ATests Class Reference sealed
Unit tests for STRK003A - Concurrent Position Reserve Manager. Tests reserve-adjusted Kelly sizing with Little's Law calculations.
Public Member Functions
STRK003ATests ()
void CalculateExpectedConcurrent_WithValidInputs_ReturnsLittlesLawResult ()
void CalculateExpectedConcurrent_WithInvalidInputs_ThrowsArgumentOutOfRangeException (double arrivalRate, double holdingPeriod)
void CalculateExpectedConcurrentFromHistory_WithValidTrades_ReturnsExpectedValue ()
void CalculateExpectedConcurrentFromHistory_WithInsufficientTrades_ThrowsArgumentException ()
void CalculateWithReserve_WhenUtilisationHigh_RejectsConsiderSignals ()
void CalculateWithReserve_WhenUtilisationLow_AcceptsConsiderSignals ()
void CalculateWithReserve_AppliesReserveBufferToAllocation ()
void CalculateWithReserve_WithInvalidPortfolio_ThrowsArgumentOutOfRangeException (double portfolio)
Static Private Member Functions
static List< Trade > GenerateHistoricalTrades (int count, int avgHoldingDays)
static STCR004A CreateSignal (string symbol, STCR004AStrength strength)
Private Attributes
readonly STRK001A _baseKelly
readonly STRK003A _reserveManager
Detailed Description
Unit tests for STRK003A - Concurrent Position Reserve Manager. Tests reserve-adjusted Kelly sizing with Little's Law calculations.
Definition at line 14 of file TSUN015A.cs.
Constructor & Destructor Documentation
STRK003ATests()
Alaris.Test.Unit.STRK003ATests.STRK003ATests () inline
Definition at line 19 of file TSUN015A.cs.
References Alaris.Test.Unit.STRK003ATests._baseKelly, and Alaris.Test.Unit.STRK003ATests._reserveManager.
Member Function Documentation
CalculateExpectedConcurrent_WithInvalidInputs_ThrowsArgumentOutOfRangeException()
void Alaris.Test.Unit.STRK003ATests.CalculateExpectedConcurrent_WithInvalidInputs_ThrowsArgumentOutOfRangeException (double arrivalRate, double holdingPeriod) inline
Definition at line 44 of file TSUN015A.cs.
References Alaris.Test.Unit.STRK003ATests._reserveManager, and Alaris.Strategy.Risk.STRK003A.CalculateExpectedConcurrent().
CalculateExpectedConcurrent_WithValidInputs_ReturnsLittlesLawResult()
void Alaris.Test.Unit.STRK003ATests.CalculateExpectedConcurrent_WithValidInputs_ReturnsLittlesLawResult () inline
Definition at line 26 of file TSUN015A.cs.
References Alaris.Test.Unit.STRK003ATests._reserveManager, and Alaris.Strategy.Risk.STRK003A.CalculateExpectedConcurrent().
CalculateExpectedConcurrentFromHistory_WithInsufficientTrades_ThrowsArgumentException()
void Alaris.Test.Unit.STRK003ATests.CalculateExpectedConcurrentFromHistory_WithInsufficientTrades_ThrowsArgumentException () inline
Definition at line 66 of file TSUN015A.cs.
References Alaris.Test.Unit.STRK003ATests._reserveManager, Alaris.Strategy.Risk.STRK003A.CalculateExpectedConcurrentFromHistory(), and Alaris.Test.Unit.STRK003ATests.GenerateHistoricalTrades().
CalculateExpectedConcurrentFromHistory_WithValidTrades_ReturnsExpectedValue()
void Alaris.Test.Unit.STRK003ATests.CalculateExpectedConcurrentFromHistory_WithValidTrades_ReturnsExpectedValue () inline
Definition at line 53 of file TSUN015A.cs.
References Alaris.Test.Unit.STRK003ATests._reserveManager, Alaris.Strategy.Risk.STRK003A.CalculateExpectedConcurrentFromHistory(), and Alaris.Test.Unit.STRK003ATests.GenerateHistoricalTrades().
CalculateWithReserve_AppliesReserveBufferToAllocation()
void Alaris.Test.Unit.STRK003ATests.CalculateWithReserve_AppliesReserveBufferToAllocation () inline
Definition at line 122 of file TSUN015A.cs.
References Alaris.Test.Unit.STRK003ATests._reserveManager, Alaris.Strategy.Risk.STRK002A.AllocationPercent, Alaris.Strategy.Risk.STRK003A.CalculateWithReserve(), Alaris.Test.Unit.STRK003ATests.CreateSignal(), and Alaris.Test.Unit.STRK003ATests.GenerateHistoricalTrades().
CalculateWithReserve_WhenUtilisationHigh_RejectsConsiderSignals()
void Alaris.Test.Unit.STRK003ATests.CalculateWithReserve_WhenUtilisationHigh_RejectsConsiderSignals () inline
Definition at line 78 of file TSUN015A.cs.
References Alaris.Test.Unit.STRK003ATests._reserveManager, Alaris.Strategy.Risk.STRK003A.CalculateWithReserve(), Alaris.Strategy.Risk.STRK002A.Contracts, Alaris.Test.Unit.STRK003ATests.CreateSignal(), and Alaris.Test.Unit.STRK003ATests.GenerateHistoricalTrades().
CalculateWithReserve_WhenUtilisationLow_AcceptsConsiderSignals()
void Alaris.Test.Unit.STRK003ATests.CalculateWithReserve_WhenUtilisationLow_AcceptsConsiderSignals () inline
Definition at line 100 of file TSUN015A.cs.
References Alaris.Test.Unit.STRK003ATests._reserveManager, Alaris.Strategy.Risk.STRK002A.AllocationPercent, Alaris.Strategy.Risk.STRK003A.CalculateWithReserve(), Alaris.Test.Unit.STRK003ATests.CreateSignal(), and Alaris.Test.Unit.STRK003ATests.GenerateHistoricalTrades().
CalculateWithReserve_WithInvalidPortfolio_ThrowsArgumentOutOfRangeException()
void Alaris.Test.Unit.STRK003ATests.CalculateWithReserve_WithInvalidPortfolio_ThrowsArgumentOutOfRangeException (double portfolio) inline
Definition at line 156 of file TSUN015A.cs.
References Alaris.Test.Unit.STRK003ATests._reserveManager, Alaris.Strategy.Risk.STRK003A.CalculateWithReserve(), Alaris.Test.Unit.STRK003ATests.CreateSignal(), and Alaris.Test.Unit.STRK003ATests.GenerateHistoricalTrades().
CreateSignal()
static STCR004A Alaris.Test.Unit.STRK003ATests.CreateSignal (string symbol, STCR004AStrength strength) inline static private
Definition at line 197 of file TSUN015A.cs.
Referenced by Alaris.Test.Unit.STRK003ATests.CalculateWithReserve_AppliesReserveBufferToAllocation(), Alaris.Test.Unit.STRK003ATests.CalculateWithReserve_WhenUtilisationHigh_RejectsConsiderSignals(), Alaris.Test.Unit.STRK003ATests.CalculateWithReserve_WhenUtilisationLow_AcceptsConsiderSignals(), and Alaris.Test.Unit.STRK003ATests.CalculateWithReserve_WithInvalidPortfolio_ThrowsArgumentOutOfRangeException().
GenerateHistoricalTrades()
static List< Trade > Alaris.Test.Unit.STRK003ATests.GenerateHistoricalTrades (int count, int avgHoldingDays) inline static private
Definition at line 175 of file TSUN015A.cs.
Referenced by Alaris.Test.Unit.STRK003ATests.CalculateExpectedConcurrentFromHistory_WithInsufficientTrades_ThrowsArgumentException(), Alaris.Test.Unit.STRK003ATests.CalculateExpectedConcurrentFromHistory_WithValidTrades_ReturnsExpectedValue(), Alaris.Test.Unit.STRK003ATests.CalculateWithReserve_AppliesReserveBufferToAllocation(), Alaris.Test.Unit.STRK003ATests.CalculateWithReserve_WhenUtilisationHigh_RejectsConsiderSignals(), Alaris.Test.Unit.STRK003ATests.CalculateWithReserve_WhenUtilisationLow_AcceptsConsiderSignals(), and Alaris.Test.Unit.STRK003ATests.CalculateWithReserve_WithInvalidPortfolio_ThrowsArgumentOutOfRangeException().
Member Data Documentation
_baseKelly
readonly STRK001A Alaris.Test.Unit.STRK003ATests._baseKelly private
Definition at line 16 of file TSUN015A.cs.
Referenced by Alaris.Test.Unit.STRK003ATests.STRK003ATests().
_reserveManager
readonly STRK003A Alaris.Test.Unit.STRK003ATests._reserveManager private
Definition at line 17 of file TSUN015A.cs.
Referenced by Alaris.Test.Unit.STRK003ATests.STRK003ATests(), Alaris.Test.Unit.STRK003ATests.CalculateExpectedConcurrent_WithInvalidInputs_ThrowsArgumentOutOfRangeException(), Alaris.Test.Unit.STRK003ATests.CalculateExpectedConcurrent_WithValidInputs_ReturnsLittlesLawResult(), Alaris.Test.Unit.STRK003ATests.CalculateExpectedConcurrentFromHistory_WithInsufficientTrades_ThrowsArgumentException(), Alaris.Test.Unit.STRK003ATests.CalculateExpectedConcurrentFromHistory_WithValidTrades_ReturnsExpectedValue(), Alaris.Test.Unit.STRK003ATests.CalculateWithReserve_AppliesReserveBufferToAllocation(), Alaris.Test.Unit.STRK003ATests.CalculateWithReserve_WhenUtilisationHigh_RejectsConsiderSignals(), Alaris.Test.Unit.STRK003ATests.CalculateWithReserve_WhenUtilisationLow_AcceptsConsiderSignals(), and Alaris.Test.Unit.STRK003ATests.CalculateWithReserve_WithInvalidPortfolio_ThrowsArgumentOutOfRangeException().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN015A.cs