Alaris: Alaris.Host.Application.Command.APcm003A Class Reference
Alaris.Host.Application.Command.APcm003A Class Reference sealed
Alaris Data Command - download and manage market data. Component ID: APcm003A.
Public Member Functions
override int Execute (CommandContext context, DataSettings settings)
Static Private Member Functions
static int DownloadData (DataSettings settings)
static int DownloadTickerData (string ticker, DateTime startDate, DateTime endDate, string resolution, string apiKey, string dataPath)
static int ListData ()
static int ShowDataStatus ()
static int InvalidAction (string action)
static ? string FindDataPath ()
static string FindOrCreateDataPath ()
static ? string GetPolygonApiKey ()
static string FormatSize (long bytes)
Detailed Description
Alaris Data Command - download and manage market data. Component ID: APcm003A.
Definition at line 59 of file APcm003A.cs.
Member Function Documentation
DownloadData()
static int Alaris.Host.Application.Command.APcm003A.DownloadData (DataSettings settings) inline static private
Definition at line 72 of file APcm003A.cs.
References Alaris.Host.Application.Command.DataSettings.DataType, Alaris.Host.Application.Command.APcm003A.DownloadTickerData(), Alaris.Host.Application.Command.APcm003A.FindOrCreateDataPath(), Alaris.Host.Application.Command.APcm003A.GetPolygonApiKey(), Alaris.Host.Application.Command.DataSettings.Resolution, Alaris.Host.Application.Command.DataSettings.Source, and Alaris.Host.Application.Command.DataSettings.Ticker.
Referenced by Alaris.Host.Application.Command.APcm003A.Execute().
DownloadTickerData()
static int Alaris.Host.Application.Command.APcm003A.DownloadTickerData (string ticker, DateTime startDate, DateTime endDate, string resolution, string apiKey, string dataPath) inline static private
Definition at line 153 of file APcm003A.cs.
References Alaris.Host.Application.Command.PolygonAggregatesResponse.Results.
Referenced by Alaris.Host.Application.Command.APcm003A.DownloadData().
Execute()
override int Alaris.Host.Application.Command.APcm003A.Execute (CommandContext context, DataSettings settings) inline
Definition at line 61 of file APcm003A.cs.
References Alaris.Host.Application.Command.DataSettings.Action, Alaris.Host.Application.Command.APcm003A.DownloadData(), Alaris.Host.Application.Command.APcm003A.InvalidAction(), Alaris.Host.Application.Command.APcm003A.ListData(), and Alaris.Host.Application.Command.APcm003A.ShowDataStatus().
FindDataPath()
static ? string Alaris.Host.Application.Command.APcm003A.FindDataPath () inline static private
Definition at line 315 of file APcm003A.cs.
Referenced by Alaris.Host.Application.Command.APcm003A.FindOrCreateDataPath(), Alaris.Host.Application.Command.APcm003A.ListData(), and Alaris.Host.Application.Command.APcm003A.ShowDataStatus().
FindOrCreateDataPath()
static string Alaris.Host.Application.Command.APcm003A.FindOrCreateDataPath () inline static private
Definition at line 335 of file APcm003A.cs.
References Alaris.Host.Application.Command.APcm003A.FindDataPath().
Referenced by Alaris.Host.Application.Command.APcm003A.DownloadData().
FormatSize()
static string Alaris.Host.Application.Command.APcm003A.FormatSize (long bytes) inline static private
Definition at line 412 of file APcm003A.cs.
Referenced by Alaris.Host.Application.Command.APcm003A.ListData().
GetPolygonApiKey()
static ? string Alaris.Host.Application.Command.APcm003A.GetPolygonApiKey () inline static private
Definition at line 357 of file APcm003A.cs.
Referenced by Alaris.Host.Application.Command.APcm003A.DownloadData(), and Alaris.Host.Application.Command.APcm003A.ShowDataStatus().
InvalidAction()
static int Alaris.Host.Application.Command.APcm003A.InvalidAction (string action) inline static private
Definition at line 308 of file APcm003A.cs.
Referenced by Alaris.Host.Application.Command.APcm003A.Execute().
ListData()
static int Alaris.Host.Application.Command.APcm003A.ListData () inline static private
Definition at line 250 of file APcm003A.cs.
References Alaris.Host.Application.Command.APcm003A.FindDataPath(), and Alaris.Host.Application.Command.APcm003A.FormatSize().
Referenced by Alaris.Host.Application.Command.APcm003A.Execute().
ShowDataStatus()
static int Alaris.Host.Application.Command.APcm003A.ShowDataStatus () inline static private
Definition at line 288 of file APcm003A.cs.
References Alaris.Host.Application.Command.APcm003A.FindDataPath(), and Alaris.Host.Application.Command.APcm003A.GetPolygonApiKey().
Referenced by Alaris.Host.Application.Command.APcm003A.Execute().
The documentation for this class was generated from the following file:
src/Alaris.Host/Application/Command/APcm003A.cs