Alaris: Alaris.Core.Pricing.CREN004A Class Reference
Alaris.Core.Pricing.CREN004A Class Reference sealed
Spectral collocation American option pricing engine.
Public Member Functions
CREN004A (SpectralScheme scheme=SpectralScheme.Accurate)
Initializes a new spectral American pricing engine.
CREN004A (int chebyshevNodes, int fixedPointIterations, FixedPointEquation fpEquation=FixedPointEquation.Auto, bool useTanhSinh=false)
Initializes a spectral engine with custom parameters.
double Price (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType)
Prices an American option using spectral collocation.
double Delta (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType)
Computes Delta (∂V/∂S) using central differencing.
double Gamma (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType)
Computes Gamma (∂²V/∂S²) using central differencing.
double Theta (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType)
Computes Theta (∂V/∂τ) using forward differencing.
double Vega (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType)
Computes Vega (∂V/∂σ) using central differencing.
Private Types
enum RateRegime { Standard , DoubleBoundary }
Private Member Functions
readonly (double[] Nodes, double[] Weights) _quadratureScheme
double PriceSingleBoundary (double spot, double strike, double tau, double r, double q, double sigma, bool isCall)
double PriceDoubleBoundary (double spot, double strike, double tau, double r, double q, double sigma, bool isCall)
double[] FixedPointIteration (double[] boundary, double[] timeNodes, double strike, double tau, double r, double q, double sigma, bool isCall)
double FixedPointUpdate (double[] boundary, double[] timeNodes, int index, double strike, double tau, double r, double q, double sigma, bool isCall)
double[] double[] Lower DoubleBoundaryFixedPointIteration (double[] upper, double[] lower, double[] timeNodes, double strike, double tau, double r, double q, double sigma, bool isCall)
double FixedPointUpdateLower (double[] lower, double[] upper, double[] timeNodes, int index, double strike, double tau, double r, double q, double sigma, bool isCall)
double ComputeIntegralN (double[] boundary, double[] timeNodes, int index, double strike, double r, double q, double sigma, bool isCall)
double ComputeIntegralD (double[] boundary, double[] timeNodes, int index, double strike, double r, double q, double sigma, bool isCall)
double IntegrateEarlyExercisePremium (double spot, double strike, double tau, double r, double q, double sigma, bool isCall, double[] timeNodes, double[] boundary)
double IntegrateDoubleBoundaryPremium (double spot, double strike, double tau, double r, double q, double sigma, bool isCall, double[] timeNodes, double[] upper, double[] lower)
Static Private Member Functions
static double InterpolateBoundary (double[] boundary, double[] timeNodes, double t)
static double ComputeQdPlusInitialGuess (double strike, double tau, double r, double q, double sigma, bool isCall)
static double BlackScholesEuropean (double spot, double strike, double tau, double r, double q, double sigma, bool isCall)
static double CalculateIntrinsicValue (double spot, double strike, OptionType optionType)
static RateRegime ClassifyRegime (double r, double q, bool isCall)
static void ValidateInputs (double spot, double strike, double tau, double sigma)
Private Attributes
readonly int _chebyshevNodes
readonly int _fixedPointIterations
readonly FixedPointEquation _fpEquation
readonly bool _useTanhSinh
double[] Upper
Static Private Attributes
const double Tolerance = 1e-10
const double NumericalEpsilon = 1e-14
Detailed Description
Spectral collocation American option pricing engine.
Implements the Andersen-Lake-Offengenden algorithm which achieves ~10⁻⁸ accuracy with sub-millisecond pricing by interpolating the exercise boundary on Chebyshev nodes and using Gauss quadrature for integration.
Definition at line 56 of file CREN004A.cs.
Member Enumeration Documentation
RateRegime
enum Alaris.Core.Pricing.CREN004A.RateRegime private
Enumerator
Standard
DoubleBoundary
Definition at line 802 of file CREN004A.cs.
Constructor & Destructor Documentation
CREN004A() [1/2]
Alaris.Core.Pricing.CREN004A.CREN004A (SpectralScheme scheme = SpectralScheme::Accurate) inline
Initializes a new spectral American pricing engine.
Parameters
scheme Pre-defined iteration scheme (Fast/Accurate/HighPrecision).
Definition at line 71 of file CREN004A.cs.
References Alaris.Core.Pricing.CREN004A._chebyshevNodes, Alaris.Core.Pricing.CREN004A._fixedPointIterations, Alaris.Core.Pricing.CREN004A._fpEquation, and Alaris.Core.Pricing.CREN004A._useTanhSinh.
CREN004A() [2/2]
Alaris.Core.Pricing.CREN004A.CREN004A (int chebyshevNodes, int fixedPointIterations, FixedPointEquation fpEquation = FixedPointEquation::Auto, bool useTanhSinh = false) inline
Initializes a spectral engine with custom parameters.
Definition at line 87 of file CREN004A.cs.
References Alaris.Core.Pricing.CREN004A._chebyshevNodes, Alaris.Core.Pricing.CREN004A._fixedPointIterations, Alaris.Core.Pricing.CREN004A._fpEquation, Alaris.Core.Pricing.CREN004A._useTanhSinh, and Alaris.Core.Math.CRGQ001A.GaussLegendre().
Member Function Documentation
BlackScholesEuropean()
static double Alaris.Core.Pricing.CREN004A.BlackScholesEuropean (double spot, double strike, double tau, double r, double q, double sigma, bool isCall) inline static private
Definition at line 776 of file CREN004A.cs.
References Alaris.Core.Math.CRMF001A.NormalCDF().
Referenced by Alaris.Core.Pricing.CREN004A.PriceDoubleBoundary(), and Alaris.Core.Pricing.CREN004A.PriceSingleBoundary().
CalculateIntrinsicValue()
static double Alaris.Core.Pricing.CREN004A.CalculateIntrinsicValue (double spot, double strike, OptionType optionType) inline static private
Definition at line 795 of file CREN004A.cs.
Referenced by Alaris.Core.Pricing.CREN004A.Price(), Alaris.Core.Pricing.CREN004A.PriceDoubleBoundary(), and Alaris.Core.Pricing.CREN004A.PriceSingleBoundary().
ClassifyRegime()
static RateRegime Alaris.Core.Pricing.CREN004A.ClassifyRegime (double r, double q, bool isCall) inline static private
Definition at line 804 of file CREN004A.cs.
Referenced by Alaris.Core.Pricing.CREN004A.Price().
ComputeIntegralD()
double Alaris.Core.Pricing.CREN004A.ComputeIntegralD (double[] boundary, double[] timeNodes, int index, double strike, double r, double q, double sigma, bool isCall) inline private
Definition at line 603 of file CREN004A.cs.
References Alaris.Core.Pricing.CREN004A._chebyshevNodes, Alaris.Core.Pricing.CREN004A._useTanhSinh, Alaris.Core.Math.CRGQ001A.IntegrateWithScheme(), Alaris.Core.Pricing.CREN004A.InterpolateBoundary(), Alaris.Core.Math.CRMF001A.NormalCDF(), Alaris.Core.Pricing.CREN004A.NumericalEpsilon, Alaris.Core.Math.CRGQ001A.TanhSinhIntegrate(), and Alaris.Core.Pricing.CREN004A.Tolerance.
Referenced by Alaris.Core.Pricing.CREN004A.FixedPointUpdate().
ComputeIntegralN()
double Alaris.Core.Pricing.CREN004A.ComputeIntegralN (double[] boundary, double[] timeNodes, int index, double strike, double r, double q, double sigma, bool isCall) inline private
Definition at line 566 of file CREN004A.cs.
References Alaris.Core.Pricing.CREN004A._chebyshevNodes, Alaris.Core.Pricing.CREN004A._useTanhSinh, Alaris.Core.Math.CRGQ001A.IntegrateWithScheme(), Alaris.Core.Pricing.CREN004A.InterpolateBoundary(), Alaris.Core.Math.CRMF001A.NormalCDF(), Alaris.Core.Pricing.CREN004A.NumericalEpsilon, Alaris.Core.Math.CRGQ001A.TanhSinhIntegrate(), and Alaris.Core.Pricing.CREN004A.Tolerance.
Referenced by Alaris.Core.Pricing.CREN004A.FixedPointUpdate().
ComputeQdPlusInitialGuess()
static double Alaris.Core.Pricing.CREN004A.ComputeQdPlusInitialGuess (double strike, double tau, double r, double q, double sigma, bool isCall) inline static private
Definition at line 746 of file CREN004A.cs.
Referenced by Alaris.Core.Pricing.CREN004A.PriceSingleBoundary().
Delta()
double Alaris.Core.Pricing.CREN004A.Delta (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType) inline
Computes Delta (∂V/∂S) using central differencing.
Definition at line 141 of file CREN004A.cs.
References Alaris.Core.Pricing.CREN004A.Price().
Referenced by Alaris.Core.Pricing.CREN003A.Delta(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Delta_Call_InValidRange(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Delta_Put_InValidRange(), Alaris.Test.Benchmark.TSBM002A.Greeks_SpectralProducesReasonableValues(), and Alaris.Test.Benchmark.TSBM003A.Greeks_TimingComparison().
DoubleBoundaryFixedPointIteration()
double[] double[] Lower Alaris.Core.Pricing.CREN004A.DoubleBoundaryFixedPointIteration (double[] upper, double[] lower, double[] timeNodes, double strike, double tau, double r, double q, double sigma, bool isCall) inline private
Definition at line 469 of file CREN004A.cs.
References Alaris.Core.Pricing.CREN004A._chebyshevNodes, Alaris.Core.Pricing.CREN004A._fixedPointIterations, Alaris.Core.Pricing.CREN004A.FixedPointUpdate(), Alaris.Core.Pricing.CREN004A.FixedPointUpdateLower(), and Alaris.Core.Pricing.CREN004A.NumericalEpsilon.
Referenced by Alaris.Core.Pricing.CREN004A.PriceDoubleBoundary().
FixedPointIteration()
double[] Alaris.Core.Pricing.CREN004A.FixedPointIteration (double[] boundary, double[] timeNodes, double strike, double tau, double r, double q, double sigma, bool isCall) inline private
Definition at line 367 of file CREN004A.cs.
References Alaris.Core.Pricing.CREN004A._chebyshevNodes, Alaris.Core.Pricing.CREN004A._fixedPointIterations, Alaris.Core.Pricing.CREN004A.FixedPointUpdate(), Alaris.Core.Pricing.CREN004A.NumericalEpsilon, and Alaris.Core.Pricing.CREN004A.Tolerance.
Referenced by Alaris.Core.Pricing.CREN004A.PriceSingleBoundary().
FixedPointUpdate()
double Alaris.Core.Pricing.CREN004A.FixedPointUpdate (double[] boundary, double[] timeNodes, int index, double strike, double tau, double r, double q, double sigma, bool isCall) inline private
Definition at line 416 of file CREN004A.cs.
References Alaris.Core.Pricing.CREN004A.ComputeIntegralD(), Alaris.Core.Pricing.CREN004A.ComputeIntegralN(), Alaris.Core.Math.CRMF001A.NormalCDF(), and Alaris.Core.Pricing.CREN004A.NumericalEpsilon.
Referenced by Alaris.Core.Pricing.CREN004A.DoubleBoundaryFixedPointIteration(), and Alaris.Core.Pricing.CREN004A.FixedPointIteration().
FixedPointUpdateLower()
double Alaris.Core.Pricing.CREN004A.FixedPointUpdateLower (double[] lower, double[] upper, double[] timeNodes, int index, double strike, double tau, double r, double q, double sigma, bool isCall) inline private
Definition at line 514 of file CREN004A.cs.
References Alaris.Core.Math.CRMF001A.NormalCDF(), and Alaris.Core.Pricing.CREN004A.NumericalEpsilon.
Referenced by Alaris.Core.Pricing.CREN004A.DoubleBoundaryFixedPointIteration().
Gamma()
double Alaris.Core.Pricing.CREN004A.Gamma (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType) inline
Computes Gamma (∂²V/∂S²) using central differencing.
Definition at line 159 of file CREN004A.cs.
References Alaris.Core.Pricing.CREN004A.Price().
Referenced by Alaris.Core.Pricing.CREN003A.Gamma(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Gamma_NonNegative(), Alaris.Test.Benchmark.TSBM002A.Greeks_SpectralProducesReasonableValues(), and Alaris.Test.Benchmark.TSBM003A.Greeks_TimingComparison().
IntegrateDoubleBoundaryPremium()
double Alaris.Core.Pricing.CREN004A.IntegrateDoubleBoundaryPremium (double spot, double strike, double tau, double r, double q, double sigma, bool isCall, double[] timeNodes, double[] upper, double[] lower) inline private
Definition at line 701 of file CREN004A.cs.
References Alaris.Core.Pricing.CREN004A._useTanhSinh, Alaris.Core.Math.CRGQ001A.IntegrateWithScheme(), Alaris.Core.Pricing.CREN004A.InterpolateBoundary(), Alaris.Core.Math.CRMF001A.NormalCDF(), Alaris.Core.Pricing.CREN004A.NumericalEpsilon, Alaris.Core.Math.CRGQ001A.TanhSinhIntegrate(), and Alaris.Core.Pricing.CREN004A.Tolerance.
Referenced by Alaris.Core.Pricing.CREN004A.PriceDoubleBoundary().
IntegrateEarlyExercisePremium()
double Alaris.Core.Pricing.CREN004A.IntegrateEarlyExercisePremium (double spot, double strike, double tau, double r, double q, double sigma, bool isCall, double[] timeNodes, double[] boundary) inline private
Definition at line 640 of file CREN004A.cs.
References Alaris.Core.Pricing.CREN004A._useTanhSinh, Alaris.Core.Math.CRGQ001A.IntegrateWithScheme(), Alaris.Core.Pricing.CREN004A.InterpolateBoundary(), Alaris.Core.Math.CRMF001A.NormalCDF(), Alaris.Core.Pricing.CREN004A.NumericalEpsilon, Alaris.Core.Math.CRGQ001A.TanhSinhIntegrate(), and Alaris.Core.Pricing.CREN004A.Tolerance.
Referenced by Alaris.Core.Pricing.CREN004A.PriceSingleBoundary().
InterpolateBoundary()
static double Alaris.Core.Pricing.CREN004A.InterpolateBoundary (double[] boundary, double[] timeNodes, double t) inline static private
Definition at line 741 of file CREN004A.cs.
References Alaris.Core.Math.CRCH001A.Interpolate().
Referenced by Alaris.Core.Pricing.CREN004A.ComputeIntegralD(), Alaris.Core.Pricing.CREN004A.ComputeIntegralN(), Alaris.Core.Pricing.CREN004A.IntegrateDoubleBoundaryPremium(), and Alaris.Core.Pricing.CREN004A.IntegrateEarlyExercisePremium().
Price()
double Alaris.Core.Pricing.CREN004A.Price (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType) inline
Prices an American option using spectral collocation.
Definition at line 108 of file CREN004A.cs.
References Alaris.Core.Pricing.CREN004A.CalculateIntrinsicValue(), Alaris.Core.Pricing.CREN004A.ClassifyRegime(), Alaris.Core.Pricing.CREN004A.PriceDoubleBoundary(), Alaris.Core.Pricing.CREN004A.PriceSingleBoundary(), and Alaris.Core.Pricing.CREN004A.ValidateInputs().
Referenced by Alaris.Test.Benchmark.TSBM002A.Accuracy_SpectralVsFD_NegativeRateSingleBoundary(), Alaris.Test.Benchmark.TSBM002A.Accuracy_SpectralVsFD_StandardRegime(), Alaris.Test.Benchmark.TSBM003A.AccuracySpeedTradeoff_SchemeComparison(), Alaris.Core.Pricing.CREN004A.Delta(), Alaris.Core.Pricing.CREN004A.Gamma(), Alaris.Test.Benchmark.TSBM003A.MaturityScaling_Performance(), Alaris.Test.Benchmark.TSBM002A.Performance_SpectralFastVsFD_100Options(), Alaris.Test.Benchmark.TSBM003A.Portfolio_ThroughputComparison(), Alaris.Core.Pricing.CREN003A.Price(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_AccurateAndFast_AreClose(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_AmericanCall_AtLeastIntrinsic(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_AmericanGreaterThanEuropean_Put(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_AmericanPut_AtLeastIntrinsic(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_DeepITM_Put_CloseToIntrinsic(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_DeepOTM_Put_SmallValue(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_InvalidSpot_Throws(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_InvalidVolatility_Throws(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_NearExpiry_ReturnsIntrinsic(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_NegativeRate_AtLeastIntrinsic(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_NegativeRateRegime_ReturnsPositiveValue(), Alaris.Test.Unit.Core.Pricing.CREN004ATests.Price_StandardRegime_ReturnsPositiveValue(), Alaris.Test.Benchmark.TSBM002A.RegimeCoverage_AllRegimesProduceValidPrice(), Alaris.Test.Benchmark.TSBM003A.RegimeCoverage_BothEnginesWork(), Alaris.Test.Benchmark.TSBM002A.RMSE_SpectralVsFD_Portfolio(), Alaris.Test.Benchmark.TSBM003A.SingleOption_SpeedComparison(), Alaris.Core.Pricing.CREN004A.Theta(), and Alaris.Core.Pricing.CREN004A.Vega().
PriceDoubleBoundary()
double Alaris.Core.Pricing.CREN004A.PriceDoubleBoundary (double spot, double strike, double tau, double r, double q, double sigma, bool isCall) inline private
Definition at line 252 of file CREN004A.cs.
References Alaris.Core.Pricing.CREN004A._chebyshevNodes, Alaris.Core.Pricing.CREN004A._fixedPointIterations, Alaris.Core.Pricing.CREN004A.BlackScholesEuropean(), Alaris.Core.Pricing.CRAP001A.CalculateBoundaries(), Alaris.Core.Pricing.CREN004A.CalculateIntrinsicValue(), Alaris.Core.Math.CRCH001A.ChebyshevNodes(), Alaris.Core.Pricing.CREN004A.DoubleBoundaryFixedPointIteration(), Alaris.Core.Pricing.CREN004A.IntegrateDoubleBoundaryPremium(), and Alaris.Core.Pricing.CRSL002A.SolveBoundaries().
Referenced by Alaris.Core.Pricing.CREN004A.Price().
PriceSingleBoundary()
double Alaris.Core.Pricing.CREN004A.PriceSingleBoundary (double spot, double strike, double tau, double r, double q, double sigma, bool isCall) inline private
Definition at line 218 of file CREN004A.cs.
References Alaris.Core.Pricing.CREN004A._chebyshevNodes, Alaris.Core.Pricing.CREN004A.BlackScholesEuropean(), Alaris.Core.Pricing.CREN004A.CalculateIntrinsicValue(), Alaris.Core.Math.CRCH001A.ChebyshevNodes(), Alaris.Core.Pricing.CREN004A.ComputeQdPlusInitialGuess(), Alaris.Core.Pricing.CREN004A.FixedPointIteration(), and Alaris.Core.Pricing.CREN004A.IntegrateEarlyExercisePremium().
Referenced by Alaris.Core.Pricing.CREN004A.Price().
readonly()
Alaris.Core.Pricing.CREN004A.readonly (double[] Nodes, double[] Weights) private
Theta()
double Alaris.Core.Pricing.CREN004A.Theta (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType) inline
Computes Theta (∂V/∂τ) using forward differencing.
Definition at line 178 of file CREN004A.cs.
References Alaris.Core.Pricing.CREN004A.Price().
Referenced by Alaris.Core.Pricing.CREN003A.Theta().
ValidateInputs()
static void Alaris.Core.Pricing.CREN004A.ValidateInputs (double spot, double strike, double tau, double sigma) inline static private
Definition at line 820 of file CREN004A.cs.
Referenced by Alaris.Core.Pricing.CREN004A.Price().
Vega()
double Alaris.Core.Pricing.CREN004A.Vega (double spot, double strike, double tau, double r, double q, double sigma, OptionType optionType) inline
Computes Vega (∂V/∂σ) using central differencing.
Definition at line 201 of file CREN004A.cs.
References Alaris.Core.Pricing.CREN004A.Price().
Referenced by Alaris.Test.Benchmark.TSBM002A.Greeks_SpectralProducesReasonableValues(), Alaris.Test.Benchmark.TSBM003A.Greeks_TimingComparison(), Alaris.Core.Pricing.CREN003A.Vega(), and Alaris.Test.Unit.Core.Pricing.CREN004ATests.Vega_Positive().
Member Data Documentation
_chebyshevNodes
readonly int Alaris.Core.Pricing.CREN004A._chebyshevNodes private
Definition at line 58 of file CREN004A.cs.
Referenced by Alaris.Core.Pricing.CREN004A.CREN004A(), Alaris.Core.Pricing.CREN004A.CREN004A(), Alaris.Core.Pricing.CREN004A.ComputeIntegralD(), Alaris.Core.Pricing.CREN004A.ComputeIntegralN(), Alaris.Core.Pricing.CREN004A.DoubleBoundaryFixedPointIteration(), Alaris.Core.Pricing.CREN004A.FixedPointIteration(), Alaris.Core.Pricing.CREN004A.PriceDoubleBoundary(), and Alaris.Core.Pricing.CREN004A.PriceSingleBoundary().
_fixedPointIterations
readonly int Alaris.Core.Pricing.CREN004A._fixedPointIterations private
Definition at line 59 of file CREN004A.cs.
Referenced by Alaris.Core.Pricing.CREN004A.CREN004A(), Alaris.Core.Pricing.CREN004A.CREN004A(), Alaris.Core.Pricing.CREN004A.DoubleBoundaryFixedPointIteration(), Alaris.Core.Pricing.CREN004A.FixedPointIteration(), and Alaris.Core.Pricing.CREN004A.PriceDoubleBoundary().
_fpEquation
readonly FixedPointEquation Alaris.Core.Pricing.CREN004A._fpEquation private
Definition at line 60 of file CREN004A.cs.
Referenced by Alaris.Core.Pricing.CREN004A.CREN004A(), and Alaris.Core.Pricing.CREN004A.CREN004A().
_useTanhSinh
readonly bool Alaris.Core.Pricing.CREN004A._useTanhSinh private
Definition at line 61 of file CREN004A.cs.
Referenced by Alaris.Core.Pricing.CREN004A.CREN004A(), Alaris.Core.Pricing.CREN004A.CREN004A(), Alaris.Core.Pricing.CREN004A.ComputeIntegralD(), Alaris.Core.Pricing.CREN004A.ComputeIntegralN(), Alaris.Core.Pricing.CREN004A.IntegrateDoubleBoundaryPremium(), and Alaris.Core.Pricing.CREN004A.IntegrateEarlyExercisePremium().
NumericalEpsilon
const double Alaris.Core.Pricing.CREN004A.NumericalEpsilon = 1e-14 static private
Definition at line 65 of file CREN004A.cs.
Referenced by Alaris.Core.Pricing.CREN004A.ComputeIntegralD(), Alaris.Core.Pricing.CREN004A.ComputeIntegralN(), Alaris.Core.Pricing.CREN004A.DoubleBoundaryFixedPointIteration(), Alaris.Core.Pricing.CREN004A.FixedPointIteration(), Alaris.Core.Pricing.CREN004A.FixedPointUpdate(), Alaris.Core.Pricing.CREN004A.FixedPointUpdateLower(), Alaris.Core.Pricing.CREN004A.IntegrateDoubleBoundaryPremium(), and Alaris.Core.Pricing.CREN004A.IntegrateEarlyExercisePremium().
Tolerance
const double Alaris.Core.Pricing.CREN004A.Tolerance = 1e-10 static private
Definition at line 64 of file CREN004A.cs.
Referenced by Alaris.Core.Pricing.CREN004A.ComputeIntegralD(), Alaris.Core.Pricing.CREN004A.ComputeIntegralN(), Alaris.Core.Pricing.CREN004A.FixedPointIteration(), Alaris.Core.Pricing.CREN004A.IntegrateDoubleBoundaryPremium(), and Alaris.Core.Pricing.CREN004A.IntegrateEarlyExercisePremium().
Upper
double [] Alaris.Core.Pricing.CREN004A.Upper private
Definition at line 469 of file CREN004A.cs.
The documentation for this class was generated from the following file:
src/Alaris.Core/Pricing/CREN004A.cs