Alaris: Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent > Class Template Reference
Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent > Class Template Reference sealed
Finite State Machine engine for deterministic workflow routing. Component ID: PLWF001A.
Public Member Functions
PLWF001A (TState initialState)
Creates a new FSM with the specified initial state and default history capacity.
PLWF001A (TState initialState, int historyCapacity)
Creates a new FSM with specified initial state and history capacity.
PLWF001A< TState, TEvent > AddTransition (TState from, TEvent on, TState to, Func< bool >? guard=null, Action? action=null)
Defines a transition from one state to another on a given event.
PLWF001A< TState, TEvent > OnEntry (TState state, Action entryAction)
Sets Moore-style entry action for a state (executed when entering state).
PLWF001A< TState, TEvent > OnExit (TState state, Action exitAction)
Sets Moore-style exit action for a state (executed when leaving state).
PLWF001A< TState, TEvent > SetTerminal (TState state)
Marks a state as terminal (accepting/final).
PLWF001A< TState, TEvent > Freeze ()
Freezes the FSM definition, preventing further modifications. Called automatically on first Fire(), but can be called explicitly.
TransitionResult< TState, TEvent > Fire (TEvent @event)
Attempts to fire an event, transitioning the FSM if valid. Thread-safe via SpinLock for atomic state transitions.
bool CanFire (TEvent @event)
Checks if a transition is possible without executing it (thread-safe).
IEnumerable< TEvent > GetAvailableEvents ()
Gets all events that can be fired from the current state. Takes guard conditions into account.
IEnumerable<(TEvent Event, TState Target)> GetPossibleTransitions ()
Gets all defined transitions from the current state (ignoring guards).
void Reset ()
Resets the FSM to its initial state (thread-safe). Clears history buffer.
IReadOnlyList< string > Validate ()
Validates the FSM definition for completeness and correctness.
FsmStatistics GetStatistics ()
Gets statistics about the FSM structure.
Static Public Attributes
const int DefaultHistoryCapacity = 1000
Default history buffer capacity.
Properties
TState CurrentState [get]
Current state of the FSM (thread-safe read).
TState InitialState [get]
Initial state of the FSM.
bool IsTerminal [get]
Whether the FSM is in a terminal (final/accepting) state.
bool IsFrozen [get]
Whether the FSM definition is frozen (no more modifications allowed).
int HistoryCount [get]
Number of transitions in history (may be less than total if buffer wrapped).
int HistoryCapacity [get]
Maximum history capacity.
IReadOnlyList< TransitionRecord > History [get]
History of transitions (most recent first, bounded by capacity).
Events
Action< TransitionRecord >? OnTransition
Event raised when a state transition occurs (thread-safe).
Private Member Functions
bool DetectCycles ()
bool DetectCyclesDfs (TState state, HashSet< TState > visited, HashSet< TState > inStack)
void RecordTransition (TransitionResult< TState, TEvent > result)
void ThrowIfFrozen ()
readonly record struct Transition (TState Target, Func< bool >? Guard, Action? Action)
Private Attributes
readonly Dictionary<(TState, TEvent), Transition > _transitions = new()
readonly HashSet< TState > _terminalStates = new()
readonly TState _initialState
readonly Dictionary< TState, Action?> _stateEntryActions = new()
readonly Dictionary< TState, Action?> _stateExitActions = new()
SpinLock _stateLock = new(enableThreadOwnerTracking: false)
TState _currentState
readonly TransitionRecord[] _historyBuffer
int _historyHead
int _historyCount
readonly object _historyLock = new()
volatile bool _frozen
Detailed Description
Finite State Machine engine for deterministic workflow routing. Component ID: PLWF001A.
Implements a DFA M = (Σ, S, s₀, δ, F) where:
Σ = Input alphabet (TEvent enum)
S = Finite set of states (TState enum)
s₀ = Initial state
δ: S × Σ → S = Partial transition function
F ⊆ S = Terminal (accepting) states
Production guarantees:
Determinism: Each (state, event) pair maps to exactly one transition
Totality: Invalid transitions return explicit errors (partial function)
Thread-safety: Transitions are atomic via SpinLock
Memory-bounded: Circular history buffer with configurable capacity
Immutability: FSM definition frozen after first Fire()
Moore actions: State entry/exit actions for clean separation
Reference: Hopcroft, Motwani, Ullman (2006) "Introduction to Automata Theory"
Template Parameters
TState State enumeration type
TEvent Event enumeration type
Type Constraints
TState : struct
TState : Enum
TEvent : struct
TEvent : Enum
Definition at line 44 of file PLWF001A.cs.
Constructor & Destructor Documentation
PLWF001A() [1/2]
Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.PLWF001A (TState initialState) inline
Creates a new FSM with the specified initial state and default history capacity.
Parameters
initialState The starting state of the FSM.
Definition at line 85 of file PLWF001A.cs.
PLWF001A() [2/2]
Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.PLWF001A (TState initialState, int historyCapacity) inline
Creates a new FSM with specified initial state and history capacity.
Parameters
initialState The starting state of the FSM.
historyCapacity Maximum number of transitions to retain in history.
Definition at line 94 of file PLWF001A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._currentState, Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._historyBuffer, Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._initialState, and Alaris.Infrastructure.Protocol.Workflow.TransitionRecord().
Member Function Documentation
AddTransition()
PLWF001A< TState, TEvent > Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition (TState from, TEvent on, TState to, Func< bool >? guard = null, Action? action = null) inline
Defines a transition from one state to another on a given event.
Parameters
from Source state
on Triggering event
to Target state
guard Optional guard condition (must return true for transition to execute)
action Optional action to execute on successful transition (Mealy-style)
Returns
This FSM instance for fluent chaining.
Exceptions
InvalidOperationException If FSM is frozen or transition already exists.
Definition at line 192 of file PLWF001A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._transitions, Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.ThrowIfFrozen(), and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Transition().
Referenced by Alaris.Test.Unit.TSUN051A.AddTransition_AfterFire_ThrowsInvalidOperationException(), Alaris.Test.Unit.TSUN051A.CanFire_GuardFails_ReturnsFalse(), Alaris.Test.Unit.TSUN051A.CanFire_NoGuard_ReturnsTrue(), Alaris.Infrastructure.Protocol.Workflow.PLWF002A.Create(), Alaris.Infrastructure.Protocol.Workflow.PLWF003A.Create(), Alaris.Infrastructure.Protocol.Workflow.PLWF002A.CreateWithActions(), Alaris.Test.Unit.TSUN051A.Fire_ActionThrows_ReturnsFailure(), Alaris.Test.Unit.TSUN051A.Fire_FreezesDefinition(), Alaris.Test.Unit.TSUN051A.Fire_GuardFails_TransitionBlocked(), Alaris.Test.Unit.TSUN051A.Fire_GuardPasses_TransitionsSuccessfully(), Alaris.Test.Unit.TSUN051A.Fire_InvalidTransition_ReturnsFailure(), Alaris.Test.Unit.TSUN051A.Fire_RecordsHistory(), Alaris.Test.Unit.TSUN051A.Fire_ValidTransition_ChangesState(), Alaris.Test.Unit.TSUN051A.Fire_WithAction_ExecutesAction(), Alaris.Test.Unit.TSUN051A.Freeze_ExplicitlyFreezesDefinition(), Alaris.Test.Unit.TSUN051A.GetAvailableEvents_ReturnsValidEvents(), Alaris.Test.Unit.TSUN051A.GetPossibleTransitions_ReturnsAllDefinedTransitions(), Alaris.Test.Unit.TSUN051A.History_CircularBuffer_BoundsMemory(), Alaris.Test.Unit.TSUN051A.MooreActions_ExecuteInOrder(), Alaris.Test.Unit.TSUN051A.OnEntry_ExecutesWhenEnteringState(), Alaris.Test.Unit.TSUN051A.OnExit_ExecutesWhenLeavingState(), Alaris.Test.Unit.TSUN051A.OnTransition_EventRaised(), Alaris.Test.Unit.TSUN051A.Reset_ClearsHistory(), Alaris.Test.Unit.TSUN051A.Reset_ReturnsToInitialState(), and Alaris.Test.Unit.TSUN051A.Validate_DetectsDeadStates().
CanFire()
bool Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.CanFire (TEvent @ event) inline
Checks if a transition is possible without executing it (thread-safe).
Parameters
event The event to check.
Returns
True if the transition can be fired from the current state.
Definition at line 353 of file PLWF001A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._currentState, Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._stateLock, and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._transitions.
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.GetAvailableEvents().
DetectCycles()
bool Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.DetectCycles () inline private
Definition at line 520 of file PLWF001A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._transitions, and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.DetectCyclesDfs().
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.GetStatistics().
DetectCyclesDfs()
bool Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.DetectCyclesDfs (TState state, HashSet< TState > visited, HashSet< TState > inStack) inline private
Definition at line 534 of file PLWF001A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._transitions, and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.DetectCyclesDfs().
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.DetectCycles(), and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.DetectCyclesDfs().
Fire()
TransitionResult< TState, TEvent > Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Fire (TEvent @ event) inline
Attempts to fire an event, transitioning the FSM if valid. Thread-safe via SpinLock for atomic state transitions.
Parameters
event The event to fire
Returns
Transition result indicating success or failure reason
Definition at line 267 of file PLWF001A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._currentState, Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._frozen, Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._stateEntryActions, Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._stateExitActions, Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._stateLock, Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._transitions, Alaris.Infrastructure.Protocol.Workflow.TransitionResult< TState, TEvent >.ActionFailed(), Alaris.Infrastructure.Protocol.Workflow.TransitionResult< TState, TEvent >.GuardFailed(), Alaris.Infrastructure.Protocol.Workflow.TransitionResult< TState, TEvent >.InvalidTransition(), Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.RecordTransition(), and Alaris.Infrastructure.Protocol.Workflow.TransitionResult< TState, TEvent >.Success().
Freeze()
PLWF001A< TState, TEvent > Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Freeze () inline
Freezes the FSM definition, preventing further modifications. Called automatically on first Fire(), but can be called explicitly.
Returns
This FSM instance for fluent chaining.
Definition at line 255 of file PLWF001A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._frozen.
GetAvailableEvents()
IEnumerable< TEvent > Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.GetAvailableEvents () inline
Gets all events that can be fired from the current state. Takes guard conditions into account.
Returns
Enumerable of available events.
Definition at line 378 of file PLWF001A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.CanFire(), and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.CurrentState.
GetPossibleTransitions()
IEnumerable<(TEvent Event, TState Target)> Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.GetPossibleTransitions () inline
Gets all defined transitions from the current state (ignoring guards).
Returns
Enumerable of (event, targetState) pairs.
Definition at line 391 of file PLWF001A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._transitions, and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.CurrentState.
GetStatistics()
FsmStatistics Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.GetStatistics () inline
Gets statistics about the FSM structure.
Definition at line 500 of file PLWF001A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._terminalStates, Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._transitions, Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.DetectCycles(), and Alaris.Infrastructure.Protocol.Workflow.FsmStatistics().
OnEntry()
PLWF001A< TState, TEvent > Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.OnEntry (TState state, Action entryAction) inline
Sets Moore-style entry action for a state (executed when entering state).
Parameters
state The state to attach the action to.
entryAction Action to execute when entering this state.
Returns
This FSM instance for fluent chaining.
Definition at line 218 of file PLWF001A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._stateEntryActions, and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.ThrowIfFrozen().
OnExit()
PLWF001A< TState, TEvent > Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.OnExit (TState state, Action exitAction) inline
Sets Moore-style exit action for a state (executed when leaving state).
Parameters
state The state to attach the action to.
exitAction Action to execute when exiting this state.
Returns
This FSM instance for fluent chaining.
Definition at line 231 of file PLWF001A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._stateExitActions, and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.ThrowIfFrozen().
RecordTransition()
void Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.RecordTransition (TransitionResult< TState, TEvent > result) inline private
Definition at line 559 of file PLWF001A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._historyBuffer, Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._historyCount, Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._historyHead, Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._historyLock, Alaris.Infrastructure.Protocol.Workflow.TransitionResult< TState, TEvent >.Event, Alaris.Infrastructure.Protocol.Workflow.TransitionResult< TState, TEvent >.FromState, Alaris.Infrastructure.Protocol.Workflow.TransitionResult< TState, TEvent >.Message, Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.OnTransition, Alaris.Infrastructure.Protocol.Workflow.TransitionResult< TState, TEvent >.Succeeded, Alaris.Infrastructure.Protocol.Workflow.TransitionResult< TState, TEvent >.ToState, and Alaris.Infrastructure.Protocol.Workflow.TransitionRecord().
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Fire().
Reset()
void Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Reset () inline
Resets the FSM to its initial state (thread-safe). Clears history buffer.
Definition at line 403 of file PLWF001A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._currentState, Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._historyBuffer, Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._historyCount, Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._historyHead, Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._historyLock, Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._initialState, and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._stateLock.
SetTerminal()
PLWF001A< TState, TEvent > Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.SetTerminal (TState state) inline
Marks a state as terminal (accepting/final).
Parameters
state The state to mark as terminal.
Returns
This FSM instance for fluent chaining.
Definition at line 243 of file PLWF001A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._terminalStates, and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.ThrowIfFrozen().
Referenced by Alaris.Test.Unit.TSUN051A.IsTerminal_InTerminalState_ReturnsTrue(), and Alaris.Test.Unit.TSUN051A.IsTerminal_NotInTerminalState_ReturnsFalse().
ThrowIfFrozen()
void Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.ThrowIfFrozen () inline private
Definition at line 581 of file PLWF001A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._frozen.
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition(), Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.OnEntry(), Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.OnExit(), and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.SetTerminal().
Transition()
readonly record struct Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Transition (TState Target, Func< bool >? Guard, Action? Action) private
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition().
Validate()
IReadOnlyList< string > Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Validate () inline
Validates the FSM definition for completeness and correctness.
Returns
List of validation issues (empty if valid).
Definition at line 428 of file PLWF001A.cs.
References Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._initialState, Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._terminalStates, and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._transitions.
Member Data Documentation
_currentState
TState Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._currentState private
Definition at line 59 of file PLWF001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.PLWF001A(), Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.CanFire(), Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Fire(), and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Reset().
_frozen
volatile bool Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._frozen private
Definition at line 68 of file PLWF001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Fire(), Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Freeze(), and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.ThrowIfFrozen().
_historyBuffer
readonly TransitionRecord [] Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._historyBuffer private
Definition at line 62 of file PLWF001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.PLWF001A(), Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.RecordTransition(), and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Reset().
_historyCount
int Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._historyCount private
Definition at line 64 of file PLWF001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.RecordTransition(), and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Reset().
_historyHead
int Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._historyHead private
Definition at line 63 of file PLWF001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.RecordTransition(), and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Reset().
_historyLock
readonly object Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._historyLock = new() private
Definition at line 65 of file PLWF001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.RecordTransition(), and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Reset().
_initialState
readonly TState Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._initialState private
Definition at line 51 of file PLWF001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.PLWF001A(), Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Reset(), and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Validate().
_stateEntryActions
readonly Dictionary<TState, Action?> Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._stateEntryActions = new() private
Definition at line 54 of file PLWF001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Fire(), and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.OnEntry().
_stateExitActions
readonly Dictionary<TState, Action?> Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._stateExitActions = new() private
Definition at line 55 of file PLWF001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Fire(), and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.OnExit().
_stateLock
SpinLock Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._stateLock = new(enableThreadOwnerTracking: false) private
Definition at line 58 of file PLWF001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.CanFire(), Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Fire(), and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Reset().
_terminalStates
readonly HashSet<TState> Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._terminalStates = new() private
Definition at line 50 of file PLWF001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.GetStatistics(), Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.SetTerminal(), and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Validate().
_transitions
readonly Dictionary<(TState, TEvent), Transition> Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >._transitions = new() private
Definition at line 49 of file PLWF001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.AddTransition(), Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.CanFire(), Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.DetectCycles(), Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.DetectCyclesDfs(), Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Fire(), Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.GetPossibleTransitions(), Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.GetStatistics(), and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.Validate().
DefaultHistoryCapacity
const int Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.DefaultHistoryCapacity = 1000 static
Default history buffer capacity.
Definition at line 73 of file PLWF001A.cs.
Property Documentation
CurrentState
TState Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.CurrentState get
Current state of the FSM (thread-safe read).
Definition at line 107 of file PLWF001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.GetAvailableEvents(), and Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.GetPossibleTransitions().
History
IReadOnlyList<TransitionRecord> Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.History get
History of transitions (most recent first, bounded by capacity).
Definition at line 161 of file PLWF001A.cs.
HistoryCapacity
int Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.HistoryCapacity get
Maximum history capacity.
Definition at line 156 of file PLWF001A.cs.
HistoryCount
int Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.HistoryCount get
Number of transitions in history (may be less than total if buffer wrapped).
Definition at line 142 of file PLWF001A.cs.
InitialState
TState Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.InitialState get
Initial state of the FSM.
Definition at line 127 of file PLWF001A.cs.
IsFrozen
bool Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.IsFrozen get
Whether the FSM definition is frozen (no more modifications allowed).
Definition at line 137 of file PLWF001A.cs.
IsTerminal
bool Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.IsTerminal get
Whether the FSM is in a terminal (final/accepting) state.
Definition at line 132 of file PLWF001A.cs.
Event Documentation
OnTransition
Action<TransitionRecord>? Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.OnTransition
Event raised when a state transition occurs (thread-safe).
Definition at line 79 of file PLWF001A.cs.
Referenced by Alaris.Infrastructure.Protocol.Workflow.PLWF001A< TState, TEvent >.RecordTransition().
The documentation for this class was generated from the following file:
src/Alaris.Infrastructure/Protocol/Workflow/PLWF001A.cs