Alaris: Alaris.Core.Pricing.CREN001A Class Reference
Alaris.Core.Pricing.CREN001A Class Reference sealed
Crank-Nicolson finite difference engine for American options. Provides numerical pricing matching QuantLib FdBlackScholesVanillaEngine accuracy.
Public Member Functions
CREN001A (int timeSteps=DefaultTimeSteps, int spotSteps=DefaultSpotSteps, double theta=0.5)
Initialises the finite difference engine.
double Price (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType)
Prices an American option using finite differences.
double Delta (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType)
Calculates delta using central difference.
double Gamma (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType)
Calculates gamma using central difference.
double Vega (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType)
Calculates vega using central difference.
double Theta (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType)
Calculates theta using forward difference.
double Rho (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType)
Calculates rho using central difference.
Static Public Attributes
const int DefaultTimeSteps = 100
Default number of time steps for standard accuracy.
const int DefaultSpotSteps = 200
Default number of spot grid points.
Private Member Functions
void BuildTridiagonalSystem (int n, double alpha, double beta, double gamma, double[] v, double[] aOut, double[] bOut, double[] cOut, double[] dOut)
Builds the tridiagonal system for Crank-Nicolson.
Static Private Member Functions
static void SolveTridiagonal (int n, double[] a, double[] b, double[] c, double[] d, double[] x)
Solves a tridiagonal system using the Thomas algorithm. O(N) complexity, numerically stable for diagonally dominant matrices.
static void ApplyBoundaryConditions (int n, double[] x, double[] v, double strike, double r, double dt, OptionType optionType)
Applies Dirichlet boundary conditions.
static double InterpolatePrice (double[] x, double[] v, int n, double logSpot)
Interpolates the price at the current spot.
static double CalculatePayoff (double spot, double strike, OptionType optionType)
Calculates the option payoff.
Private Attributes
readonly int _timeSteps
readonly int _spotSteps
readonly double _theta
Detailed Description
Crank-Nicolson finite difference engine for American options. Provides numerical pricing matching QuantLib FdBlackScholesVanillaEngine accuracy.
This engine uses:
Log-spot transformation for uniform grid spacing
Crank-Nicolson scheme (θ=0.5) for stability and second-order accuracy
Thomas algorithm for O(N) tridiagonal system solution
Early exercise enforcement at each time step
Definition at line 38 of file CREN001A.cs.
Constructor & Destructor Documentation
CREN001A()
Alaris.Core.Pricing.CREN001A.CREN001A (int timeSteps = DefaultTimeSteps, int spotSteps = DefaultSpotSteps, double theta = 0::5) inline
Initialises the finite difference engine.
Parameters
timeSteps Number of time steps (default: 100).
spotSteps Number of spot grid points (default: 200).
theta Theta for time stepping (0.5 = Crank-Nicolson, 1.0 = Implicit, 0.0 = Explicit).
Definition at line 60 of file CREN001A.cs.
References Alaris.Core.Pricing.CREN001A._spotSteps, Alaris.Core.Pricing.CREN001A._theta, and Alaris.Core.Pricing.CREN001A._timeSteps.
Member Function Documentation
ApplyBoundaryConditions()
static void Alaris.Core.Pricing.CREN001A.ApplyBoundaryConditions (int n, double[] x, double[] v, double strike, double r, double dt, OptionType optionType) inline static private
Applies Dirichlet boundary conditions.
Definition at line 299 of file CREN001A.cs.
Referenced by Alaris.Core.Pricing.CREN001A.Price().
BuildTridiagonalSystem()
void Alaris.Core.Pricing.CREN001A.BuildTridiagonalSystem (int n, double alpha, double beta, double gamma, double[] v, double[] aOut, double[] bOut, double[] cOut, double[] dOut) inline private
Builds the tridiagonal system for Crank-Nicolson.
Definition at line 212 of file CREN001A.cs.
References Alaris.Core.Pricing.CREN001A._theta.
Referenced by Alaris.Core.Pricing.CREN001A.Price().
CalculatePayoff()
static double Alaris.Core.Pricing.CREN001A.CalculatePayoff (double spot, double strike, OptionType optionType) inline static private
Calculates the option payoff.
Definition at line 357 of file CREN001A.cs.
Referenced by Alaris.Core.Pricing.CREN001A.Price().
Delta()
double Alaris.Core.Pricing.CREN001A.Delta (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType) inline
Calculates delta using central difference.
Parameters
spot Current spot price.
strike Strike price.
timeToExpiry Time to expiry in years.
riskFreeRate Risk-free rate.
dividendYield Dividend yield.
volatility Volatility.
optionType Call or Put.
Returns
Delta (∂V/∂S).
Definition at line 378 of file CREN001A.cs.
References Alaris.Core.Pricing.CREN001A.Price().
Gamma()
double Alaris.Core.Pricing.CREN001A.Gamma (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType) inline
Calculates gamma using central difference.
Definition at line 396 of file CREN001A.cs.
References Alaris.Core.Pricing.CREN001A.Price().
InterpolatePrice()
static double Alaris.Core.Pricing.CREN001A.InterpolatePrice (double[] x, double[] v, int n, double logSpot) inline static private
Interpolates the price at the current spot.
Definition at line 331 of file CREN001A.cs.
Referenced by Alaris.Core.Pricing.CREN001A.Price().
Price()
double Alaris.Core.Pricing.CREN001A.Price (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType) inline
Prices an American option using finite differences.
Parameters
spot Current spot price.
strike Strike price.
timeToExpiry Time to expiry in years.
riskFreeRate Risk-free rate (continuously compounded).
dividendYield Continuous dividend yield.
volatility Volatility (annualised).
optionType Call or Put.
Returns
American option price.
Definition at line 91 of file CREN001A.cs.
References Alaris.Core.Pricing.CREN001A._spotSteps, Alaris.Core.Pricing.CREN001A._timeSteps, Alaris.Core.Pricing.CREN001A.ApplyBoundaryConditions(), Alaris.Core.Pricing.CREN001A.BuildTridiagonalSystem(), Alaris.Core.Pricing.CREN001A.CalculatePayoff(), Alaris.Core.Pricing.CREN001A.InterpolatePrice(), and Alaris.Core.Pricing.CREN001A.SolveTridiagonal().
Referenced by Alaris.Core.Pricing.CREN001A.Delta(), Alaris.Core.Pricing.CREN001A.Gamma(), Alaris.Core.Pricing.CREN001A.Rho(), Alaris.Core.Pricing.CREN001A.Theta(), and Alaris.Core.Pricing.CREN001A.Vega().
Rho()
double Alaris.Core.Pricing.CREN001A.Rho (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType) inline
Calculates rho using central difference.
Definition at line 452 of file CREN001A.cs.
References Alaris.Core.Pricing.CREN001A.Price().
SolveTridiagonal()
static void Alaris.Core.Pricing.CREN001A.SolveTridiagonal (int n, double[] a, double[] b, double[] c, double[] d, double[] x) inline static private
Solves a tridiagonal system using the Thomas algorithm. O(N) complexity, numerically stable for diagonally dominant matrices.
Definition at line 254 of file CREN001A.cs.
Referenced by Alaris.Core.Pricing.CREN001A.Price().
Theta()
double Alaris.Core.Pricing.CREN001A.Theta (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType) inline
Calculates theta using forward difference.
Definition at line 434 of file CREN001A.cs.
References Alaris.Core.Pricing.CREN001A.Price().
Vega()
double Alaris.Core.Pricing.CREN001A.Vega (double spot, double strike, double timeToExpiry, double riskFreeRate, double dividendYield, double volatility, OptionType optionType) inline
Calculates vega using central difference.
Definition at line 416 of file CREN001A.cs.
References Alaris.Core.Pricing.CREN001A.Price().
Member Data Documentation
_spotSteps
readonly int Alaris.Core.Pricing.CREN001A._spotSteps private
Definition at line 41 of file CREN001A.cs.
Referenced by Alaris.Core.Pricing.CREN001A.CREN001A(), and Alaris.Core.Pricing.CREN001A.Price().
_theta
readonly double Alaris.Core.Pricing.CREN001A._theta private
Definition at line 42 of file CREN001A.cs.
Referenced by Alaris.Core.Pricing.CREN001A.CREN001A(), and Alaris.Core.Pricing.CREN001A.BuildTridiagonalSystem().
_timeSteps
readonly int Alaris.Core.Pricing.CREN001A._timeSteps private
Definition at line 40 of file CREN001A.cs.
Referenced by Alaris.Core.Pricing.CREN001A.CREN001A(), and Alaris.Core.Pricing.CREN001A.Price().
DefaultSpotSteps
const int Alaris.Core.Pricing.CREN001A.DefaultSpotSteps = 200 static
Default number of spot grid points.
Definition at line 52 of file CREN001A.cs.
DefaultTimeSteps
const int Alaris.Core.Pricing.CREN001A.DefaultTimeSteps = 100 static
Default number of time steps for standard accuracy.
Definition at line 47 of file CREN001A.cs.
The documentation for this class was generated from the following file:
src/Alaris.Core/Pricing/CREN001A.cs