Alaris: Alaris.Infrastructure.Data.Quality.EarningsDateValidator Class Reference
Alaris.Infrastructure.Data.Quality.EarningsDateValidator Class Reference sealed
Validates earnings date accuracy and consistency. Component ID: DTqc004A.
Public Member Functions
EarningsDateValidator (ILogger< EarningsDateValidator > logger, ITimeProvider timeProvider)
Initializes a new instance of the EarningsDateValidator class.
DataQualityResult Validate (MarketDataSnapshot snapshot)
Validates market data snapshot.
Parameters
snapshot The market data to validate.
Returns
Validation result.
Properties
string ComponentId [get]
Gets the validator component ID (e.g., "DTqc001A").
Properties inherited from Alaris.Infrastructure.Data.Quality.DTqc002A
Private Attributes
readonly ILogger< EarningsDateValidator > _logger
readonly ITimeProvider _timeProvider
Detailed Description
Validates earnings date accuracy and consistency. Component ID: DTqc004A.
Validation checks:
Earnings date confirmed from 2+ sources (if possible)
Date within next 90 days
No conflicting dates in recent history
Definition at line 345 of file DTqc001A.cs.
Constructor & Destructor Documentation
EarningsDateValidator()
Alaris.Infrastructure.Data.Quality.EarningsDateValidator.EarningsDateValidator (ILogger< EarningsDateValidator > logger, ITimeProvider timeProvider) inline
Initializes a new instance of the EarningsDateValidator class.
Parameters
logger The logger instance.
timeProvider The time provider for backtest-aware time operations.
Definition at line 358 of file DTqc001A.cs.
References Alaris.Infrastructure.Data.Quality.EarningsDateValidator._logger, and Alaris.Infrastructure.Data.Quality.EarningsDateValidator._timeProvider.
Member Function Documentation
Validate()
DataQualityResult Alaris.Infrastructure.Data.Quality.EarningsDateValidator.Validate (MarketDataSnapshot snapshot) inline
Validates market data snapshot.
Parameters
snapshot The market data to validate.
Returns
Validation result.
Implements Alaris.Infrastructure.Data.Quality.DTqc002A.
Definition at line 367 of file DTqc001A.cs.
References Alaris.Infrastructure.Data.Quality.EarningsDateValidator._timeProvider, Alaris.Infrastructure.Data.Quality.EarningsDateValidator.ComponentId, Alaris.Infrastructure.Data.Model.MarketDataSnapshot.HistoricalEarnings, Alaris.Infrastructure.Data.Model.MarketDataSnapshot.NextEarnings, Alaris.Core.Time.ITimeProvider.Today, and Alaris.Core.Time.ITimeProvider.ToLocalDate().
Referenced by Alaris.Test.Unit.DTqc004ATests.Validate_EarningsDateInPast_ShouldFail(), Alaris.Test.Unit.DTqc004ATests.Validate_EarningsMoreThan90DaysAhead_ShouldWarn(), Alaris.Test.Unit.DTqc004ATests.Validate_NoUpcomingEarnings_ShouldPass(), Alaris.Test.Unit.DTqc004ATests.Validate_StaleEarningsData_ShouldWarn(), and Alaris.Test.Unit.DTqc004ATests.Validate_ValidEarningsDate_ShouldPass().
Member Data Documentation
_logger
readonly ILogger<EarningsDateValidator> Alaris.Infrastructure.Data.Quality.EarningsDateValidator._logger private
Definition at line 347 of file DTqc001A.cs.
Referenced by Alaris.Infrastructure.Data.Quality.EarningsDateValidator.EarningsDateValidator().
_timeProvider
readonly ITimeProvider Alaris.Infrastructure.Data.Quality.EarningsDateValidator._timeProvider private
Definition at line 348 of file DTqc001A.cs.
Referenced by Alaris.Infrastructure.Data.Quality.EarningsDateValidator.EarningsDateValidator(), and Alaris.Infrastructure.Data.Quality.EarningsDateValidator.Validate().
Property Documentation
ComponentId
string Alaris.Infrastructure.Data.Quality.EarningsDateValidator.ComponentId get
Gets the validator component ID (e.g., "DTqc001A").
Implements Alaris.Infrastructure.Data.Quality.DTqc002A.
Definition at line 351 of file DTqc001A.cs.
Referenced by Alaris.Test.Unit.DTqc004ATests.ComponentId_ShouldBe_DTqc004A(), and Alaris.Infrastructure.Data.Quality.EarningsDateValidator.Validate().
The documentation for this class was generated from the following file:
src/Alaris.Infrastructure/Data/Quality/DTqc001A.cs