Alaris: Alaris.Test.Integration.TSIN004A Class Reference
Alaris.Test.Integration.TSIN004A Class Reference sealed
TSIN004A: Integration tests for Alaris.Events infrastructure.
Public Member Functions
async Task EVIF001A_AppendAsync_SequenceNumbersAreMonotonic ()
AppendAsync should create envelope with monotonically increasing sequence.
async Task EVIF001A_AppendAsync_EventIdsAreUnique ()
AppendAsync should assign unique EventId to each envelope.
async Task EVIF001A_GetEventsForAggregate_FiltersCorrectly ()
GetEventsForAggregateAsync should return only events for specified aggregate.
async Task EVIF001A_GetEventsFromSequence_PaginatesCorrectly ()
GetEventsFromSequenceAsync should paginate correctly.
async Task EVIF001A_GetCurrentSequenceNumber_ReturnsHighest ()
GetCurrentSequenceNumberAsync should return highest sequence.
async Task EVIF001A_GetEventsByCorrelationId_ReturnsCorrelated ()
GetEventsByCorrelationIdAsync should return correlated events.
async Task EVIF001A_GetEventsByTimeRange_FiltersCorrectly ()
GetEventsByTimeRangeAsync should filter by time range.
async Task EVIF002A_LogAsync_StoresEntry ()
LogAsync should store audit entries.
async Task EVIF002A_GetEntriesForEntity_ReturnsCorrectEntries ()
GetEntriesForEntityAsync should return all entries for entity.
async Task EVIF002A_GetEntriesByInitiator_FiltersCorrectly ()
GetEntriesByInitiatorAsync should filter by initiator.
async Task EVIF002A_GetEntriesByTimeRange_FiltersCorrectly ()
GetEntriesByTimeRangeAsync should filter by time.
async Task EVIF002A_PreservesSeverity (AuditSeverity severity)
Audit entries should preserve severity levels.
async Task EVIF002A_PreservesOutcome (AuditOutcome outcome)
Audit entries should preserve outcome status.
void EVCR003A_Create_SerializesEventToJson ()
Event envelope should serialize event data to JSON.
void EVCR003A_Create_PreservesEventId ()
Event envelope should preserve event ID.
void EVCR003A_Create_StoresAggregateInfo ()
Event envelope should store aggregate information.
void EVCR003A_Create_IncludesCorrelationId ()
Event envelope should include correlation ID from event.
async Task EVIF001A_ConcurrentAppends_MaintainsSequenceIntegrity ()
Event store should handle concurrent appends correctly.
async Task EVIF002A_ConcurrentLogs_AllEntriesStored ()
Audit logger should handle concurrent logs correctly.
Static Private Member Functions
static AuditEntry CreateTestAuditEntry (string entityType, string entityId, string action, string initiatedBy)
Detailed Description
TSIN004A: Integration tests for Alaris.Events infrastructure.
Definition at line 33 of file TSIN004A.cs.
Member Function Documentation
CreateTestAuditEntry()
static AuditEntry Alaris.Test.Integration.TSIN004A.CreateTestAuditEntry (string entityType, string entityId, string action, string initiatedBy) inline static private
Definition at line 510 of file TSIN004A.cs.
References Alaris.Infrastructure.Events.Core.AuditEntry, and Alaris.Test.Integration.OccurredAtUtc.
Referenced by Alaris.Test.Integration.TSIN004A.EVIF002A_ConcurrentLogs_AllEntriesStored(), Alaris.Test.Integration.TSIN004A.EVIF002A_GetEntriesByInitiator_FiltersCorrectly(), Alaris.Test.Integration.TSIN004A.EVIF002A_GetEntriesByTimeRange_FiltersCorrectly(), Alaris.Test.Integration.TSIN004A.EVIF002A_GetEntriesForEntity_ReturnsCorrectEntries(), and Alaris.Test.Integration.TSIN004A.EVIF002A_LogAsync_StoresEntry().
EVCR003A_Create_IncludesCorrelationId()
void Alaris.Test.Integration.TSIN004A.EVCR003A_Create_IncludesCorrelationId () inline
Event envelope should include correlation ID from event.
Definition at line 427 of file TSIN004A.cs.
References Alaris.Test.Integration.CorrelationId, Alaris.Infrastructure.Events.Core.EVCR003A, and Alaris.Test.Integration.TestDomainEvent.
EVCR003A_Create_PreservesEventId()
void Alaris.Test.Integration.TSIN004A.EVCR003A_Create_PreservesEventId () inline
Event envelope should preserve event ID.
Definition at line 387 of file TSIN004A.cs.
References Alaris.Infrastructure.Events.Core.EVCR003A, and Alaris.Test.Integration.TestDomainEvent.
EVCR003A_Create_SerializesEventToJson()
void Alaris.Test.Integration.TSIN004A.EVCR003A_Create_SerializesEventToJson () inline
Event envelope should serialize event data to JSON.
Definition at line 366 of file TSIN004A.cs.
References Alaris.Infrastructure.Events.Core.EVCR003A, Alaris.Test.Integration.TestDomainEvent, and Alaris.Test.Integration.TestProperty.
EVCR003A_Create_StoresAggregateInfo()
void Alaris.Test.Integration.TSIN004A.EVCR003A_Create_StoresAggregateInfo () inline
Event envelope should store aggregate information.
Definition at line 403 of file TSIN004A.cs.
References Alaris.Infrastructure.Events.Core.EVCR003A, and Alaris.Test.Integration.TestDomainEvent.
EVIF001A_AppendAsync_EventIdsAreUnique()
async Task Alaris.Test.Integration.TSIN004A.EVIF001A_AppendAsync_EventIdsAreUnique () inline
AppendAsync should assign unique EventId to each envelope.
Definition at line 67 of file TSIN004A.cs.
References Alaris.Test.Integration.TestDomainEvent.
EVIF001A_AppendAsync_SequenceNumbersAreMonotonic()
async Task Alaris.Test.Integration.TSIN004A.EVIF001A_AppendAsync_SequenceNumbersAreMonotonic () inline
AppendAsync should create envelope with monotonically increasing sequence.
Definition at line 41 of file TSIN004A.cs.
References Alaris.Test.Integration.TestDomainEvent.
EVIF001A_ConcurrentAppends_MaintainsSequenceIntegrity()
async Task Alaris.Test.Integration.TSIN004A.EVIF001A_ConcurrentAppends_MaintainsSequenceIntegrity () inline
Event store should handle concurrent appends correctly.
Definition at line 449 of file TSIN004A.cs.
References Alaris.Test.Integration.TestDomainEvent.
EVIF001A_GetCurrentSequenceNumber_ReturnsHighest()
async Task Alaris.Test.Integration.TSIN004A.EVIF001A_GetCurrentSequenceNumber_ReturnsHighest () inline
GetCurrentSequenceNumberAsync should return highest sequence.
Definition at line 138 of file TSIN004A.cs.
References Alaris.Test.Integration.TestDomainEvent.
EVIF001A_GetEventsByCorrelationId_ReturnsCorrelated()
async Task Alaris.Test.Integration.TSIN004A.EVIF001A_GetEventsByCorrelationId_ReturnsCorrelated () inline
GetEventsByCorrelationIdAsync should return correlated events.
Definition at line 160 of file TSIN004A.cs.
References Alaris.Test.Integration.CorrelationId, and Alaris.Test.Integration.TestDomainEvent.
EVIF001A_GetEventsByTimeRange_FiltersCorrectly()
async Task Alaris.Test.Integration.TSIN004A.EVIF001A_GetEventsByTimeRange_FiltersCorrectly () inline
GetEventsByTimeRangeAsync should filter by time range.
Definition at line 186 of file TSIN004A.cs.
References Alaris.Test.Integration.TestDomainEvent.
EVIF001A_GetEventsForAggregate_FiltersCorrectly()
async Task Alaris.Test.Integration.TSIN004A.EVIF001A_GetEventsForAggregate_FiltersCorrectly () inline
GetEventsForAggregateAsync should return only events for specified aggregate.
Definition at line 89 of file TSIN004A.cs.
References Alaris.Test.Integration.TestDomainEvent.
EVIF001A_GetEventsFromSequence_PaginatesCorrectly()
async Task Alaris.Test.Integration.TSIN004A.EVIF001A_GetEventsFromSequence_PaginatesCorrectly () inline
GetEventsFromSequenceAsync should paginate correctly.
Definition at line 114 of file TSIN004A.cs.
References Alaris.Test.Integration.TestDomainEvent.
EVIF002A_ConcurrentLogs_AllEntriesStored()
async Task Alaris.Test.Integration.TSIN004A.EVIF002A_ConcurrentLogs_AllEntriesStored () inline
Audit logger should handle concurrent logs correctly.
Definition at line 483 of file TSIN004A.cs.
References Alaris.Test.Integration.TSIN004A.CreateTestAuditEntry().
EVIF002A_GetEntriesByInitiator_FiltersCorrectly()
async Task Alaris.Test.Integration.TSIN004A.EVIF002A_GetEntriesByInitiator_FiltersCorrectly () inline
GetEntriesByInitiatorAsync should filter by initiator.
Definition at line 256 of file TSIN004A.cs.
References Alaris.Test.Integration.TSIN004A.CreateTestAuditEntry().
EVIF002A_GetEntriesByTimeRange_FiltersCorrectly()
async Task Alaris.Test.Integration.TSIN004A.EVIF002A_GetEntriesByTimeRange_FiltersCorrectly () inline
GetEntriesByTimeRangeAsync should filter by time.
Definition at line 276 of file TSIN004A.cs.
References Alaris.Test.Integration.TSIN004A.CreateTestAuditEntry().
EVIF002A_GetEntriesForEntity_ReturnsCorrectEntries()
async Task Alaris.Test.Integration.TSIN004A.EVIF002A_GetEntriesForEntity_ReturnsCorrectEntries () inline
GetEntriesForEntityAsync should return all entries for entity.
Definition at line 234 of file TSIN004A.cs.
References Alaris.Test.Integration.TSIN004A.CreateTestAuditEntry().
EVIF002A_LogAsync_StoresEntry()
async Task Alaris.Test.Integration.TSIN004A.EVIF002A_LogAsync_StoresEntry () inline
LogAsync should store audit entries.
Definition at line 215 of file TSIN004A.cs.
References Alaris.Test.Integration.TSIN004A.CreateTestAuditEntry().
EVIF002A_PreservesOutcome()
async Task Alaris.Test.Integration.TSIN004A.EVIF002A_PreservesOutcome (AuditOutcome outcome) inline
Audit entries should preserve outcome status.
Definition at line 335 of file TSIN004A.cs.
References Alaris.Infrastructure.Events.Core.AuditEntry, and Alaris.Test.Integration.OccurredAtUtc.
EVIF002A_PreservesSeverity()
async Task Alaris.Test.Integration.TSIN004A.EVIF002A_PreservesSeverity (AuditSeverity severity) inline
Audit entries should preserve severity levels.
Definition at line 303 of file TSIN004A.cs.
References Alaris.Infrastructure.Events.Core.AuditEntry, and Alaris.Test.Integration.OccurredAtUtc.
The documentation for this class was generated from the following file:
src/Alaris.Test/Integration/TSIN004A.cs