Alaris: Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider Class Reference
Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider Class Reference sealed
NASDAQ public API earnings calendar provider. Component ID: DTea001C.
Public Member Functions
NasdaqEarningsProvider (INasdaqCalendarApi api, ILogger< NasdaqEarningsProvider > logger, string? cacheDataPath=null)
Initialises a new instance of the NasdaqEarningsProvider class.
void EnableCacheOnlyMode ()
Enables cache-only mode (no API calls). Use for backtests to prevent 403 errors.
async Task< IReadOnlyList< EarningsEvent > > GetUpcomingEarningsAsync (string symbol, int daysAhead=90, CancellationToken cancellationToken=default)
Gets upcoming earnings events for a symbol.
async Task< IReadOnlyList< EarningsEvent > > GetHistoricalEarningsAsync (string symbol, int lookbackDays=730, CancellationToken cancellationToken=default)
Gets historical earnings events for a symbol.
async Task< IReadOnlyList< EarningsEvent > > GetHistoricalEarningsAsync (string symbol, DateTime anchorDate, int lookbackDays=730, CancellationToken cancellationToken=default)
Gets historical earnings for a symbol, anchored to a specific date. Use this overload in backtest mode with simulation date as anchor.
async Task< IReadOnlyList< string > > GetSymbolsWithEarningsAsync (DateTime startDate, DateTime endDate, CancellationToken cancellationToken=default)
Gets all symbols with earnings in date range.
async Task SaveToCacheAsync (DateTime date, IReadOnlyList< EarningsEvent > earnings, string outputPath, CancellationToken cancellationToken)
Saves earnings data to JSON cache file for future backtests.
async Task< IReadOnlyList< EarningsEvent > > FetchAndCacheAsync (DateTime date, string outputPath, CancellationToken cancellationToken)
Fetches and caches earnings for a specific date (bootstrap mode).
Private Member Functions
async Task< IReadOnlyList< EarningsEvent > > GetEarningsInDateRangeAsync (DateTime startDate, DateTime endDate, CancellationToken cancellationToken)
Gets all earnings events in a date range by querying each date.
async Task< IReadOnlyList< EarningsEvent > > GetEarningsForDateAsync (DateTime date, CancellationToken cancellationToken)
Gets earnings events for a specific date, checking cache first.
async Task< IReadOnlyList< EarningsEvent > > LoadFromCacheAsync (string cachePath, CancellationToken cancellationToken)
Loads cached earnings data from JSON file.
Static Private Member Functions
static EarningsEvent MapToEarningsEvent (NasdaqEarningsRow row, DateTime date)
Maps NASDAQ API response to EarningsEvent model.
static ? decimal ParseDecimal (string? value)
Parses a decimal from string, handling various formats.
Private Attributes
readonly INasdaqCalendarApi _api
readonly ILogger< NasdaqEarningsProvider > _logger
readonly? string _cacheDataPath
bool _cacheOnlyMode
Static Private Attributes
static readonly JsonSerializerOptions JsonOptions
Detailed Description
NASDAQ public API earnings calendar provider. Component ID: DTea001C.
Implements DTpr004A (Earnings Calendar Provider interface) using NASDAQ's public API via Refit declarative interface (INasdaqCalendarApi).
API Endpoint: https://api.nasdaq.com/api/calendar/earnings Cost: FREE (no API key required) Rate Limit: Undocumented (appears unlimited for reasonable use)
Fail-fast design: No fallback providers. Errors propagate immediately. Resilience provided by Microsoft.Extensions.Http.Resilience standard handler.
Future Alternative: EODHD Calendar API ($19.99/month) provides 100,000 calls/day with official C# wrapper and SLA if this endpoint becomes unreliable.
Definition at line 41 of file DTea001C.cs.
Constructor & Destructor Documentation
NasdaqEarningsProvider()
Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.NasdaqEarningsProvider (INasdaqCalendarApi api, ILogger< NasdaqEarningsProvider > logger, string? cacheDataPath = null) inline
Initialises a new instance of the NasdaqEarningsProvider class.
Parameters
api NASDAQ Calendar Refit API client.
logger Logger instance.
cacheDataPath Optional cache data path for backtest mode.
Definition at line 61 of file DTea001C.cs.
References Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider._api, Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider._cacheDataPath, and Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider._logger.
Member Function Documentation
EnableCacheOnlyMode()
void Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.EnableCacheOnlyMode () inline
Enables cache-only mode (no API calls). Use for backtests to prevent 403 errors.
Implements Alaris.Infrastructure.Data.Provider.DTpr004A.
Definition at line 74 of file DTea001C.cs.
References Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider._cacheOnlyMode, and Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider._logger.
FetchAndCacheAsync()
async Task< IReadOnlyList< EarningsEvent > > Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.FetchAndCacheAsync (DateTime date, string outputPath, CancellationToken cancellationToken) inline
Fetches and caches earnings for a specific date (bootstrap mode).
Definition at line 360 of file DTea001C.cs.
References Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider._api, Alaris.Infrastructure.Data.Http.Contracts.NasdaqEarningsResponse.Data, Alaris.Infrastructure.Data.Http.Contracts.INasdaqCalendarApi.GetEarningsAsync(), Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.MapToEarningsEvent(), Alaris.Infrastructure.Data.Http.Contracts.NasdaqEarningsData.Rows, and Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.SaveToCacheAsync().
Referenced by Alaris.Host.Application.Service.APsv002A.BootstrapEarningsCalendarAsync().
GetEarningsForDateAsync()
async Task< IReadOnlyList< EarningsEvent > > Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetEarningsForDateAsync (DateTime date, CancellationToken cancellationToken) inline private
Gets earnings events for a specific date, checking cache first.
Cache-first pattern:
Check {session}/earnings/nasdaq/{date}.json
If cached → Load from file (backtest mode)
If live → Call NASDAQ API
Definition at line 254 of file DTea001C.cs.
References Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider._api, Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider._cacheDataPath, Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider._cacheOnlyMode, Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider._logger, Alaris.Infrastructure.Data.Http.Contracts.NasdaqEarningsResponse.Data, Alaris.Infrastructure.Data.Http.Contracts.INasdaqCalendarApi.GetEarningsAsync(), Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.LoadFromCacheAsync(), Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.MapToEarningsEvent(), and Alaris.Infrastructure.Data.Http.Contracts.NasdaqEarningsData.Rows.
Referenced by Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetEarningsInDateRangeAsync().
GetEarningsInDateRangeAsync()
async Task< IReadOnlyList< EarningsEvent > > Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetEarningsInDateRangeAsync (DateTime startDate, DateTime endDate, CancellationToken cancellationToken) inline private
Gets all earnings events in a date range by querying each date.
Definition at line 214 of file DTea001C.cs.
References Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider._logger, and Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetEarningsForDateAsync().
Referenced by Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetHistoricalEarningsAsync(), Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetSymbolsWithEarningsAsync(), and Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetUpcomingEarningsAsync().
GetHistoricalEarningsAsync() [1/2]
async Task< IReadOnlyList< EarningsEvent > > Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetHistoricalEarningsAsync (string symbol, DateTime anchorDate, int lookbackDays = 730, CancellationToken cancellationToken = default) inline
Gets historical earnings for a symbol, anchored to a specific date. Use this overload in backtest mode with simulation date as anchor.
Parameters
symbol The symbol to look up.
anchorDate The anchor date (simulation date in backtest, or today in live).
lookbackDays Number of days to look back from anchor date.
cancellationToken Cancellation token.
Implements Alaris.Infrastructure.Data.Provider.DTpr004A.
Definition at line 131 of file DTea001C.cs.
References Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider._logger, and Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetEarningsInDateRangeAsync().
GetHistoricalEarningsAsync() [2/2]
async Task< IReadOnlyList< EarningsEvent > > Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetHistoricalEarningsAsync (string symbol, int lookbackDays = 730, CancellationToken cancellationToken = default) inline
Gets historical earnings events for a symbol.
Implements Alaris.Infrastructure.Data.Provider.DTpr004A.
Definition at line 114 of file DTea001C.cs.
References Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetHistoricalEarningsAsync().
Referenced by Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetHistoricalEarningsAsync().
GetSymbolsWithEarningsAsync()
async Task< IReadOnlyList< string > > Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetSymbolsWithEarningsAsync (DateTime startDate, DateTime endDate, CancellationToken cancellationToken = default) inline
Gets all symbols with earnings in date range.
Implements Alaris.Infrastructure.Data.Provider.DTpr004A.
Definition at line 189 of file DTea001C.cs.
References Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider._logger, and Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetEarningsInDateRangeAsync().
GetUpcomingEarningsAsync()
async Task< IReadOnlyList< EarningsEvent > > Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetUpcomingEarningsAsync (string symbol, int daysAhead = 90, CancellationToken cancellationToken = default) inline
Gets upcoming earnings events for a symbol.
Implements Alaris.Infrastructure.Data.Provider.DTpr004A.
Definition at line 81 of file DTea001C.cs.
References Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider._logger, and Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetEarningsInDateRangeAsync().
LoadFromCacheAsync()
async Task< IReadOnlyList< EarningsEvent > > Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.LoadFromCacheAsync (string cachePath, CancellationToken cancellationToken) inline private
Loads cached earnings data from JSON file.
Definition at line 309 of file DTea001C.cs.
References Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider._logger, Alaris.Infrastructure.Data.Provider.Nasdaq.CachedEarningsDay.Earnings, and Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.JsonOptions.
Referenced by Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetEarningsForDateAsync().
MapToEarningsEvent()
static EarningsEvent Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.MapToEarningsEvent (NasdaqEarningsRow row, DateTime date) inline static private
Maps NASDAQ API response to EarningsEvent model.
Definition at line 388 of file DTea001C.cs.
References Alaris.Infrastructure.Data.Http.Contracts.NasdaqEarningsRow.EpsActual, Alaris.Infrastructure.Data.Http.Contracts.NasdaqEarningsRow.EpsForecast, Alaris.Infrastructure.Data.Http.Contracts.NasdaqEarningsRow.FiscalQuarterEnding, Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.ParseDecimal(), Alaris.Infrastructure.Data.Http.Contracts.NasdaqEarningsRow.Symbol, and Alaris.Infrastructure.Data.Http.Contracts.NasdaqEarningsRow.Time.
Referenced by Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.FetchAndCacheAsync(), and Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetEarningsForDateAsync().
ParseDecimal()
static ? decimal Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.ParseDecimal (string? value) inline static private
Parses a decimal from string, handling various formats.
Definition at line 430 of file DTea001C.cs.
Referenced by Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.MapToEarningsEvent().
SaveToCacheAsync()
async Task Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.SaveToCacheAsync (DateTime date, IReadOnlyList< EarningsEvent > earnings, string outputPath, CancellationToken cancellationToken) inline
Saves earnings data to JSON cache file for future backtests.
Definition at line 333 of file DTea001C.cs.
References Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider._logger, and Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.JsonOptions.
Referenced by Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.FetchAndCacheAsync().
Member Data Documentation
_api
readonly INasdaqCalendarApi Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider._api private
Definition at line 43 of file DTea001C.cs.
Referenced by Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.NasdaqEarningsProvider(), Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.FetchAndCacheAsync(), and Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetEarningsForDateAsync().
_cacheDataPath
readonly? string Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider._cacheDataPath private
Definition at line 45 of file DTea001C.cs.
Referenced by Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.NasdaqEarningsProvider(), and Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetEarningsForDateAsync().
_cacheOnlyMode
bool Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider._cacheOnlyMode private
Definition at line 46 of file DTea001C.cs.
Referenced by Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.EnableCacheOnlyMode(), and Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetEarningsForDateAsync().
_logger
readonly ILogger<NasdaqEarningsProvider> Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider._logger private
Definition at line 44 of file DTea001C.cs.
Referenced by Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.NasdaqEarningsProvider(), Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.EnableCacheOnlyMode(), Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetEarningsForDateAsync(), Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetEarningsInDateRangeAsync(), Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetHistoricalEarningsAsync(), Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetSymbolsWithEarningsAsync(), Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.GetUpcomingEarningsAsync(), Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.LoadFromCacheAsync(), and Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.SaveToCacheAsync().
JsonOptions
readonly JsonSerializerOptions Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.JsonOptions static private
Initial value:
= new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        WriteIndented = true,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
    }
Definition at line 48 of file DTea001C.cs.
Referenced by Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.LoadFromCacheAsync(), and Alaris.Infrastructure.Data.Provider.Nasdaq.NasdaqEarningsProvider.SaveToCacheAsync().
The documentation for this class was generated from the following file:
src/Alaris.Infrastructure/Data/Provider/Nasdaq/DTea001C.cs