Alaris: Alaris.Test.Unit.QueueTheoryTests Class Reference
Alaris.Test.Unit.QueueTheoryTests Class Reference sealed
Public Member Functions
void MeanQueueLength_IncreasesWithUtilisation ()
void BlockingProbability_AtCapacity_ReturnsOne ()
void GittinsProxy_HigherProfit_HigherPriority ()
void SelectForEjection_NewSignalHigherPriority_ReturnsMinIndex ()
Detailed Description
Definition at line 145 of file TSUN013A.cs.
Member Function Documentation
BlockingProbability_AtCapacity_ReturnsOne()
void Alaris.Test.Unit.QueueTheoryTests.BlockingProbability_AtCapacity_ReturnsOne () inline
Definition at line 161 of file TSUN013A.cs.
References Alaris.Strategy.Risk.STQT001A.ComputeBlockingProbability().
GittinsProxy_HigherProfit_HigherPriority()
void Alaris.Test.Unit.QueueTheoryTests.GittinsProxy_HigherProfit_HigherPriority () inline
Definition at line 174 of file TSUN013A.cs.
References Alaris.Strategy.Risk.STQT001A.ComputeGittinsProxy().
MeanQueueLength_IncreasesWithUtilisation()
void Alaris.Test.Unit.QueueTheoryTests.MeanQueueLength_IncreasesWithUtilisation () inline
Definition at line 148 of file TSUN013A.cs.
References Alaris.Strategy.Risk.STQT001A.ComputeMeanQueueLength().
SelectForEjection_NewSignalHigherPriority_ReturnsMinIndex()
void Alaris.Test.Unit.QueueTheoryTests.SelectForEjection_NewSignalHigherPriority_ReturnsMinIndex () inline
Definition at line 185 of file TSUN013A.cs.
References Alaris.Strategy.Risk.STQT001A.SelectForEjection().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN013A.cs