Alaris: Alaris.Core.Pricing.CRRE001A Class Reference
Alaris.Core.Pricing.CRRE001A Class Reference
Rate regime classifier for American option pricing. Determines whether single-boundary FD or double-boundary QD+ is required.
Static Public Member Functions
static RateRegime Classify (double r, double q, bool isCall)
Classifies the rate regime for pricing.
static bool RequiresDoubleBoundary (double r, double q, bool isCall)
Checks if the parameters require double-boundary treatment.
static string GetDescription (RateRegime regime)
Gets a human-readable description of the rate regime.
static bool ValidateParameters (double r, double q)
Validates that parameters are within reasonable bounds.
Detailed Description
Rate regime classifier for American option pricing. Determines whether single-boundary FD or double-boundary QD+ is required.
Reference: Healy (2021) - American Options Under Negative Rates
Regime classification:
For PUT options:
q < r < 0 → Double boundary (both upper and lower exercise boundaries)
Otherwise → Standard single boundary
For CALL options:
0 < r < q → Double boundary (both upper and lower exercise boundaries)
Otherwise → Standard single boundary
Definition at line 49 of file CRRE001A.cs.
Member Function Documentation
Classify()
static RateRegime Alaris.Core.Pricing.CRRE001A.Classify (double r, double q, bool isCall) inline static
Classifies the rate regime for pricing.
Parameters
r Risk-free rate (can be negative).
q Dividend yield (can be negative).
isCall True for call options, false for puts.
Returns
The applicable rate regime.
Definition at line 58 of file CRRE001A.cs.
Referenced by Alaris.Test.Unit.Core.Pricing.CREN003ATests.Classify_DoubleBoundaryRegime(), Alaris.Test.Unit.Core.Pricing.CRRE001ATests.Classify_NegativeRates_DoubleBoundary_Put(), Alaris.Test.Unit.Core.Pricing.CRRE001ATests.Classify_NegativeRates_WellBehaved_ReturnsStandard(), Alaris.Test.Unit.Core.Pricing.CRRE001ATests.Classify_PositiveRates_DoubleBoundary_Call(), Alaris.Test.Unit.Core.Pricing.CRRE001ATests.Classify_PositiveRates_ReturnsStandard(), Alaris.Test.Unit.Core.Pricing.CREN003ATests.Classify_StandardRegime(), Alaris.Core.Pricing.CREN003A.PriceWithDetails(), and Alaris.Core.Pricing.CRRE001A.RequiresDoubleBoundary().
GetDescription()
static string Alaris.Core.Pricing.CRRE001A.GetDescription (RateRegime regime) inline static
Gets a human-readable description of the rate regime.
Parameters
regime Rate regime to describe.
Returns
Description string.
Definition at line 99 of file CRRE001A.cs.
Referenced by Alaris.Test.Unit.Core.Pricing.CRRE001ATests.GetDescription_DoubleBoundary_ReturnsCorrectString(), and Alaris.Test.Unit.Core.Pricing.CRRE001ATests.GetDescription_Standard_ReturnsCorrectString().
RequiresDoubleBoundary()
static bool Alaris.Core.Pricing.CRRE001A.RequiresDoubleBoundary (double r, double q, bool isCall) inline static
Checks if the parameters require double-boundary treatment.
Parameters
r Risk-free rate.
q Dividend yield.
isCall True for call options.
Returns
True if double-boundary method is required.
Definition at line 89 of file CRRE001A.cs.
References Alaris.Core.Pricing.CRRE001A.Classify().
Referenced by Alaris.Test.Unit.Core.Pricing.CRRE001ATests.RequiresDoubleBoundary_DoubleBoundaryCase_ReturnsTrue(), and Alaris.Test.Unit.Core.Pricing.CRRE001ATests.RequiresDoubleBoundary_StandardCase_ReturnsFalse().
ValidateParameters()
static bool Alaris.Core.Pricing.CRRE001A.ValidateParameters (double r, double q) inline static
Validates that parameters are within reasonable bounds.
Parameters
r Risk-free rate.
q Dividend yield.
Returns
True if parameters are valid.
Definition at line 115 of file CRRE001A.cs.
Referenced by Alaris.Test.Unit.Core.Pricing.CRRE001ATests.ValidateParameters_ExtremeRates_ReturnsFalse(), Alaris.Test.Unit.Core.Pricing.CRRE001ATests.ValidateParameters_Infinity_ReturnsFalse(), Alaris.Test.Unit.Core.Pricing.CRRE001ATests.ValidateParameters_NaN_ReturnsFalse(), and Alaris.Test.Unit.Core.Pricing.CRRE001ATests.ValidateParameters_ValidRates_ReturnsTrue().
The documentation for this class was generated from the following file:
src/Alaris.Core/Pricing/CRRE001A.cs