Alaris: Alaris.Core.Math.CRMF002A Class Reference
Alaris.Core.Math.CRMF002A Class Reference
Characteristic equation solver for American option pricing. Computes λ₁ and λ₂ roots used in boundary calculations.
Static Public Member Functions
static double double λ2 SolveCharacteristic (double r, double q, double σ)
static double SuperHalleyRefine (double λInit, double a, double b, double c, double tolerance=1e-12, int maxIterations=20)
Refines a characteristic root using Super-Halley iteration.
static bool ValidateRoot (double r, double q, double σ, double λ, double tolerance=1e-10)
Validates that the computed roots satisfy the characteristic equation.
Static Public Attributes
static double λ1
Solves the characteristic equation for the given parameters.
Static Private Member Functions
static double BrentBisectionFallback (double λInit, double a, double b, double c, double tolerance=1e-12)
Brent bisection fallback for quadratic root finding - guaranteed convergence.
Detailed Description
Characteristic equation solver for American option pricing. Computes λ₁ and λ₂ roots used in boundary calculations.
Definition at line 23 of file CRMF002A.cs.
Member Function Documentation
BrentBisectionFallback()
static double Alaris.Core.Math.CRMF002A.BrentBisectionFallback (double λInit, double a, double b, double c, double tolerance = 1e-12) inline static private
Brent bisection fallback for quadratic root finding - guaranteed convergence.
Parameters
λInit Initial estimate.
a Quadratic coefficient.
b Linear coefficient.
c Constant coefficient.
tolerance Convergence tolerance.
Returns
Refined root value.
Uses bisection with bracketing. For a quadratic with real roots, we can bracket by expanding around the initial estimate.
Definition at line 169 of file CRMF002A.cs.
Referenced by Alaris.Core.Math.CRMF002A.SuperHalleyRefine().
SolveCharacteristic()
static double double λ2 Alaris.Core.Math.CRMF002A.SolveCharacteristic (double r, double q, double σ) inline static
Definition at line 38 of file CRMF002A.cs.
Referenced by Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_InvalidVolatility_Throws(), Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_NearZeroRate_NumericalStability(), Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_NegativeRates_DoubleBoundaryRegime(), Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_NegativeRates_RootsSatisfyEquation(), Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_NegativeVolatility_Throws(), Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_PositiveRates_Lambda1GreaterThanOne(), Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_PositiveRates_RootsSatisfyEquation(), Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_VietasFormulas_ProductOfRoots(), Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_VietasFormulas_SumOfRoots(), and Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_ZeroRate_HandlesCor().
SuperHalleyRefine()
static double Alaris.Core.Math.CRMF002A.SuperHalleyRefine (double λInit, double a, double b, double c, double tolerance = 1e-12, int maxIterations = 20) inline static
Refines a characteristic root using Super-Halley iteration.
Parameters
λInit Initial root estimate.
a Quadratic coefficient (σ²/2).
b Linear coefficient (r - q - σ²/2).
c Constant coefficient (-r).
tolerance Convergence tolerance.
maxIterations Maximum iterations.
Returns
Refined root value.
Super-Halley iteration formula: λₙ₊₁ = λₙ - (f(λₙ)·f'(λₙ)) / (f'(λₙ)² - ½f(λₙ)·f''(λₙ))
For quadratic: f(λ) = aλ² + bλ + c f'(λ) = 2aλ + b f''(λ) = 2a
Definition at line 97 of file CRMF002A.cs.
References Alaris.Core.Math.CRMF002A.BrentBisectionFallback().
Referenced by Alaris.Test.Unit.Core.Math.CRMF002ATests.SuperHalleyRefine_ConvergesToRoot().
ValidateRoot()
static bool Alaris.Core.Math.CRMF002A.ValidateRoot (double r, double q, double σ, double λ, double tolerance = 1e-10) inline static
Validates that the computed roots satisfy the characteristic equation.
Parameters
r Risk-free rate.
q Dividend yield.
σ Volatility.
λ Root to validate.
tolerance Maximum acceptable residual.
Returns
True if the root satisfies the equation within tolerance.
Definition at line 246 of file CRMF002A.cs.
Referenced by Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_NearZeroRate_NumericalStability(), Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_NegativeRates_DoubleBoundaryRegime(), Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_NegativeRates_RootsSatisfyEquation(), Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_PositiveRates_RootsSatisfyEquation(), and Alaris.Test.Unit.Core.Math.CRMF002ATests.SolveCharacteristic_ZeroRate_HandlesCor().
Member Data Documentation
λ1
double Alaris.Core.Math.CRMF002A.λ1 static
Solves the characteristic equation for the given parameters.
Parameters
r Risk-free rate (can be negative).
q Dividend yield (can be negative).
σ Volatility (must be positive).
Returns
Tuple of (λ₁, λ₂) roots, where λ₁ > λ₂.
Characteristic equation: (1/2)σ²λ² + (r - q - σ²/2)λ - r = 0
Coefficients: a = σ²/2, b = r - q - σ²/2, c = -r
Definition at line 38 of file CRMF002A.cs.
The documentation for this class was generated from the following file:
src/Alaris.Core/Math/CRMF002A.cs