Alaris: Alaris.Infrastructure.Data.Model Namespace Reference
Alaris.Infrastructure.Data.Model Namespace Reference
Classes
class DataQualityResult
Result of a data quality validation check.
class EarningsEvent
Represents an earnings announcement event.
class MarketDataSnapshot
Complete market data snapshot for strategy evaluation.
class OptionChainSnapshot
Represents a complete options chain for a given underlying at a point in time.
class OptionContract
Represents a single option contract with market data.
class PriceBar
Represents an OHLCV bar for historical price data.
Enumerations
enum OptionRight { Call , Put }
Option right (call or put).
enum EarningsTiming { BeforeMarketOpen , AfterMarketClose , DuringMarketHours , Unknown }
Timing of earnings announcement relative to market hours.
enum ValidationStatus { Passed , PassedWithWarnings , Failed }
Validation status enumeration.
enum CorporateActionType {
Split = 0 , ReverseSplit = 1 , CashDividend = 2 , StockDividend = 3 ,
SpinOff = 4 , Merger = 5 , RightsOffering = 6
}
Types of corporate actions that affect price/strike adjustments.
Functions
record DTmd003A (string Symbol, DateTime ExDate, CorporateActionType Type, decimal Factor, string Description, DateTime? PayDate=null, DateTime? RecordDate=null)
Corporate Action Data Model. Component ID: DTmd003A.
Enumeration Type Documentation
CorporateActionType
enum Alaris.Infrastructure.Data.Model.CorporateActionType
Types of corporate actions that affect price/strike adjustments.
Enumerator
Split
Stock split (e.g., 2:1 doubles shares, halves price).
ReverseSplit
Reverse split (e.g., 1:5 reduces shares, increases price).
CashDividend
Cash dividend (affects option pricing near ex-date).
StockDividend
Stock dividend (additional shares issued).
SpinOff
Spin-off (new company shares issued).
Merger
Merger or acquisition.
RightsOffering
Rights offering.
Definition at line 8 of file DTmd003A.cs.
EarningsTiming
enum Alaris.Infrastructure.Data.Model.EarningsTiming
Timing of earnings announcement relative to market hours.
Enumerator
BeforeMarketOpen
Before market open.
AfterMarketClose
After market close.
DuringMarketHours
During market hours (rare).
Unknown
Timing unknown.
Definition at line 173 of file DTmd001A.cs.
OptionRight
enum Alaris.Infrastructure.Data.Model.OptionRight
Option right (call or put).
Enumerator
Call
Call option.
Put
Put option.
Definition at line 69 of file DTmd001A.cs.
ValidationStatus
enum Alaris.Infrastructure.Data.Model.ValidationStatus
Validation status enumeration.
Enumerator
Passed
Validation passed.
PassedWithWarnings
Validation passed with warnings.
Failed
Validation failed.
Definition at line 251 of file DTmd001A.cs.
Function Documentation
DTmd003A()
record Alaris.Infrastructure.Data.Model.DTmd003A (string Symbol, DateTime ExDate, CorporateActionType Type, decimal Factor, string Description, DateTime? PayDate = null, DateTime? RecordDate = null) sealed
Corporate Action Data Model. Component ID: DTmd003A.
Represents a single corporate action event that may require price adjustments in historical backtesting data.
Key Fields:
ExDate: The ex-dividend/split date (price adjusts on this date)
Factor: The adjustment multiplier (e.g., 2.0 for 2:1 split)
PayDate: When the action is paid/effective
Parameters
Symbol Ticker symbol affected by this action.
ExDate Ex-date when the adjustment takes effect.
Type Type of corporate action.
Factor Adjustment factor. For splits: new shares per old share. For dividends: cash amount per share.
Description Human-readable description of the action.
PayDate Optional payment/effective date.
RecordDate Optional record date.
Gets whether this action requires price adjustment.
Gets whether this action requires strike adjustment for options.
Computes the price adjustment multiplier.
Returns
The multiplier to apply to pre-action prices. For a 2:1 split, returns 0.5 (price is halved).
Computes the strike adjustment multiplier for options.
Returns
The multiplier to apply to pre-action strikes. For a 2:1 split, returns 0.5 (strikes are halved).
Definition at line 60 of file DTmd003A.cs.
Referenced by Alaris.Test.Unit.DTmd003ATests.Equals_DifferentSymbol_ReturnsFalse(), Alaris.Test.Unit.DTmd003ATests.Equals_SameValues_ReturnsTrue(), Alaris.Test.Unit.DTmd003ATests.GetPriceMultiplier_CashDividend_ReturnsOne(), Alaris.Test.Unit.DTmd003ATests.GetPriceMultiplier_FivePercentStockDividend_ReturnsAdjustedMultiplier(), Alaris.Test.Unit.DTmd003ATests.GetPriceMultiplier_FourForOneSplit_ReturnsQuarter(), Alaris.Test.Unit.DTmd003ATests.GetPriceMultiplier_OneForTenReverseSplit_ReturnsTen(), Alaris.Test.Unit.DTmd003ATests.GetPriceMultiplier_TwoForOneSplit_ReturnsHalf(), Alaris.Test.Unit.DTmd003ATests.GetStrikeMultiplier_CashDividend_ReturnsOne(), Alaris.Test.Unit.DTmd003ATests.GetStrikeMultiplier_OneForTenReverseSplit_ReturnsTen(), Alaris.Test.Unit.DTmd003ATests.GetStrikeMultiplier_TwoForOneSplit_ReturnsHalf(), Alaris.Test.Unit.DTmd003ATests.RequiresPriceAdjustment_VariousTypes_ReturnsExpected(), and Alaris.Test.Unit.DTmd003ATests.RequiresStrikeAdjustment_VariousTypes_ReturnsExpected().