Alaris: Alaris.Strategy.Detection Namespace Reference
Alaris.Strategy.Detection Namespace Reference
Classes
class STSD001A
Implements the Neyman-Pearson optimal signal detection framework.
Functions
readonly record struct SignalDetectionResult (bool PassesThreshold, double LikelihoodRatio, double PosteriorProbability, double Threshold, double ObservedValue)
Represents the result of signal detection evaluation.
readonly record struct DistributionParameters (double Mu0, double Sigma0, double Mu1, double Sigma1, double Pi0, double Pi1)
Represents the calibrated distribution parameters.
readonly record struct TradeOutcome (string Symbol, DateTime TradeDate, double IVRVRatio, double TermStructureSlope, double ProfitLoss, bool IsProfitable)
Represents a historical trade outcome for calibration.
Function Documentation
DistributionParameters()
readonly record struct Alaris.Strategy.Detection.DistributionParameters (double Mu0, double Sigma0, double Mu1, double Sigma1, double Pi0, double Pi1)
Represents the calibrated distribution parameters.
Referenced by Alaris.Strategy.Detection.STSD001A.GetParameters().
SignalDetectionResult()
readonly record struct Alaris.Strategy.Detection.SignalDetectionResult (bool PassesThreshold, double LikelihoodRatio, double PosteriorProbability, double Threshold, double ObservedValue)
Represents the result of signal detection evaluation.
Parameters
PassesThreshold Whether the observation exceeds the optimal threshold.
LikelihoodRatio The likelihood ratio L(H₁)/L(H₀).
PosteriorProbability Posterior probability P(H₁|observation).
Threshold The threshold used for evaluation.
ObservedValue The observed IV/RV ratio.
Referenced by Alaris.Strategy.Detection.STSD001A.Evaluate().
TradeOutcome()
readonly record struct Alaris.Strategy.Detection.TradeOutcome (string Symbol, DateTime TradeDate, double IVRVRatio, double TermStructureSlope, double ProfitLoss, bool IsProfitable)
Represents a historical trade outcome for calibration.
References Alaris.Strategy.Detection.TradeOutcome().
Referenced by Alaris.Strategy.Detection.TradeOutcome().