Alaris: Alaris.Test.Unit.DTqc002AValidatorTests Class Reference
Alaris.Test.Unit.DTqc002AValidatorTests Class Reference sealed
Unit tests for IvArbitrageValidator (DTqc002A interface test).
Public Member Functions
DTqc002AValidatorTests ()
void Dispose ()
void ComponentId_ShouldBe_DTqc002A ()
void Validate_ValidSnapshot_ShouldPass ()
void Validate_PutCallParityViolation_ShouldWarn ()
Private Member Functions
void Dispose (bool disposing)
Static Private Member Functions
static MarketDataSnapshot CreateSnapshotWithPutCallParity (decimal callBid=5.00m, decimal callAsk=5.20m, decimal putBid=4.80m, decimal putAsk=5.00m)
Private Attributes
readonly IvArbitrageValidator _validator
readonly ILoggerFactory _loggerFactory
readonly ILogger< IvArbitrageValidator > _logger
bool _disposed
Detailed Description
Unit tests for IvArbitrageValidator (DTqc002A interface test).
Definition at line 207 of file TSUN006A.cs.
Constructor & Destructor Documentation
DTqc002AValidatorTests()
Alaris.Test.Unit.DTqc002AValidatorTests.DTqc002AValidatorTests () inline
Definition at line 214 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc002AValidatorTests._logger, Alaris.Test.Unit.DTqc002AValidatorTests._loggerFactory, and Alaris.Test.Unit.DTqc002AValidatorTests._validator.
Member Function Documentation
ComponentId_ShouldBe_DTqc002A()
void Alaris.Test.Unit.DTqc002AValidatorTests.ComponentId_ShouldBe_DTqc002A () inline
Definition at line 243 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc002AValidatorTests._validator, and Alaris.Infrastructure.Data.Quality.IvArbitrageValidator.ComponentId.
CreateSnapshotWithPutCallParity()
static MarketDataSnapshot Alaris.Test.Unit.DTqc002AValidatorTests.CreateSnapshotWithPutCallParity (decimal callBid = 5::00m, decimal callAsk = 5::20m, decimal putBid = 4::80m, decimal putAsk = 5::00m) inline static private
Definition at line 277 of file TSUN006A.cs.
Referenced by Alaris.Test.Unit.DTqc002AValidatorTests.Validate_PutCallParityViolation_ShouldWarn(), and Alaris.Test.Unit.DTqc002AValidatorTests.Validate_ValidSnapshot_ShouldPass().
Dispose() [1/2]
void Alaris.Test.Unit.DTqc002AValidatorTests.Dispose () inline
Definition at line 221 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc002AValidatorTests.Dispose().
Referenced by Alaris.Test.Unit.DTqc002AValidatorTests.Dispose().
Dispose() [2/2]
void Alaris.Test.Unit.DTqc002AValidatorTests.Dispose (bool disposing) inline private
Definition at line 227 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc002AValidatorTests._disposed, and Alaris.Test.Unit.DTqc002AValidatorTests._loggerFactory.
Validate_PutCallParityViolation_ShouldWarn()
void Alaris.Test.Unit.DTqc002AValidatorTests.Validate_PutCallParityViolation_ShouldWarn () inline
Definition at line 262 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc002AValidatorTests._validator, Alaris.Test.Unit.DTqc002AValidatorTests.CreateSnapshotWithPutCallParity(), Alaris.Infrastructure.Data.Model.DataQualityResult.Status, and Alaris.Infrastructure.Data.Quality.IvArbitrageValidator.Validate().
Validate_ValidSnapshot_ShouldPass()
void Alaris.Test.Unit.DTqc002AValidatorTests.Validate_ValidSnapshot_ShouldPass () inline
Definition at line 249 of file TSUN006A.cs.
References Alaris.Test.Unit.DTqc002AValidatorTests._validator, Alaris.Test.Unit.DTqc002AValidatorTests.CreateSnapshotWithPutCallParity(), Alaris.Infrastructure.Data.Model.DataQualityResult.Status, and Alaris.Infrastructure.Data.Quality.IvArbitrageValidator.Validate().
Member Data Documentation
_disposed
bool Alaris.Test.Unit.DTqc002AValidatorTests._disposed private
Definition at line 212 of file TSUN006A.cs.
Referenced by Alaris.Test.Unit.DTqc002AValidatorTests.Dispose().
_logger
readonly ILogger<IvArbitrageValidator> Alaris.Test.Unit.DTqc002AValidatorTests._logger private
Definition at line 211 of file TSUN006A.cs.
Referenced by Alaris.Test.Unit.DTqc002AValidatorTests.DTqc002AValidatorTests().
_loggerFactory
readonly ILoggerFactory Alaris.Test.Unit.DTqc002AValidatorTests._loggerFactory private
Definition at line 210 of file TSUN006A.cs.
Referenced by Alaris.Test.Unit.DTqc002AValidatorTests.DTqc002AValidatorTests(), and Alaris.Test.Unit.DTqc002AValidatorTests.Dispose().
_validator
readonly IvArbitrageValidator Alaris.Test.Unit.DTqc002AValidatorTests._validator private
Definition at line 209 of file TSUN006A.cs.
Referenced by Alaris.Test.Unit.DTqc002AValidatorTests.DTqc002AValidatorTests(), Alaris.Test.Unit.DTqc002AValidatorTests.ComponentId_ShouldBe_DTqc002A(), Alaris.Test.Unit.DTqc002AValidatorTests.Validate_PutCallParityViolation_ShouldWarn(), and Alaris.Test.Unit.DTqc002AValidatorTests.Validate_ValidSnapshot_ShouldPass().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/TSUN006A.cs