Alaris: Alaris.Test.Unit.Core.Time.CRTM007ATests Class Reference
Alaris.Test.Unit.Core.Time.CRTM007ATests Class Reference
Public Member Functions
void Actual365Fixed_OneYear_ReturnsOne ()
void Actual365Fixed_HalfYear_ReturnsHalf ()
void Actual365Fixed_SameDate_ReturnsZero ()
void Actual365Fixed_DayCount_ReturnsActualDays ()
void Actual360_OneYear_ReturnsMoreThanOne ()
void Actual360_30Days_ReturnsCorrect ()
void Thirty360_OneMonth_ReturnsThirtyDays ()
void Thirty360_OneYear_ReturnsOne ()
void Thirty360_Feb28ToMar1_HandlesCorrectly ()
Detailed Description
Definition at line 9 of file CRTM007ATests.cs.
Member Function Documentation
Actual360_30Days_ReturnsCorrect()
void Alaris.Test.Unit.Core.Time.CRTM007ATests.Actual360_30Days_ReturnsCorrect () inline
Definition at line 75 of file CRTM007ATests.cs.
References Alaris.Core.Time.DayCounters.Actual360, and Alaris.Core.Time.IDayCounter.YearFraction().
Actual360_OneYear_ReturnsMoreThanOne()
void Alaris.Test.Unit.Core.Time.CRTM007ATests.Actual360_OneYear_ReturnsMoreThanOne () inline
Definition at line 63 of file CRTM007ATests.cs.
References Alaris.Core.Time.DayCounters.Actual360, and Alaris.Core.Time.IDayCounter.YearFraction().
Actual365Fixed_DayCount_ReturnsActualDays()
void Alaris.Test.Unit.Core.Time.CRTM007ATests.Actual365Fixed_DayCount_ReturnsActualDays () inline
Definition at line 48 of file CRTM007ATests.cs.
References Alaris.Core.Time.DayCounters.Actual365Fixed, and Alaris.Core.Time.IDayCounter.DayCount().
Actual365Fixed_HalfYear_ReturnsHalf()
void Alaris.Test.Unit.Core.Time.CRTM007ATests.Actual365Fixed_HalfYear_ReturnsHalf () inline
Definition at line 26 of file CRTM007ATests.cs.
References Alaris.Core.Time.DayCounters.Actual365Fixed, and Alaris.Core.Time.IDayCounter.YearFraction().
Actual365Fixed_OneYear_ReturnsOne()
void Alaris.Test.Unit.Core.Time.CRTM007ATests.Actual365Fixed_OneYear_ReturnsOne () inline
Definition at line 14 of file CRTM007ATests.cs.
References Alaris.Core.Time.DayCounters.Actual365Fixed, and Alaris.Core.Time.IDayCounter.YearFraction().
Actual365Fixed_SameDate_ReturnsZero()
void Alaris.Test.Unit.Core.Time.CRTM007ATests.Actual365Fixed_SameDate_ReturnsZero () inline
Definition at line 38 of file CRTM007ATests.cs.
References Alaris.Core.Time.DayCounters.Actual365Fixed, and Alaris.Core.Time.IDayCounter.YearFraction().
Thirty360_Feb28ToMar1_HandlesCorrectly()
void Alaris.Test.Unit.Core.Time.CRTM007ATests.Thirty360_Feb28ToMar1_HandlesCorrectly () inline
Definition at line 115 of file CRTM007ATests.cs.
References Alaris.Core.Time.IDayCounter.DayCount(), and Alaris.Core.Time.DayCounters.Thirty360.
Thirty360_OneMonth_ReturnsThirtyDays()
void Alaris.Test.Unit.Core.Time.CRTM007ATests.Thirty360_OneMonth_ReturnsThirtyDays () inline
Definition at line 91 of file CRTM007ATests.cs.
References Alaris.Core.Time.DayCounters.Thirty360, and Alaris.Core.Time.IDayCounter.YearFraction().
Thirty360_OneYear_ReturnsOne()
void Alaris.Test.Unit.Core.Time.CRTM007ATests.Thirty360_OneYear_ReturnsOne () inline
Definition at line 103 of file CRTM007ATests.cs.
References Alaris.Core.Time.DayCounters.Thirty360, and Alaris.Core.Time.IDayCounter.YearFraction().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/Core/Time/CRTM007ATests.cs