Alaris: Alaris.Strategy.Core.Numerical.STPR005A Class Reference
Alaris.Strategy.Core.Numerical.STPR005A Class Reference sealed
Production-grade Differential Evolution optimizer for global optimization. Component ID: STPR005A.
Public Member Functions
OptimizationResult Minimize (Func< double[], double > objective, double[] lowerBounds, double[] upperBounds)
Minimizes an objective function using Differential Evolution.
Properties
int PopulationSize [get, set]
Population size (typically 10 * dimension). 0 means auto-select.
int MaxGenerations = 500 [get, set]
Maximum number of generations.
double DifferentialWeight = 0.8 [get, set]
Differential weight F ∈ [0, 2], typically 0.8. Controls the amplification of differential variation.
double CrossoverProbability = 0.9 [get, set]
Crossover probability CR ∈ [0, 1], typically 0.9. Controls the fraction of parameter values copied from the mutant.
double Tolerance = 1e-6 [get, set]
Tolerance for convergence (standard deviation of population objective values).
int? RandomSeed [get, set]
Random number generator seed (null for random).
Static Private Member Functions
static double EvaluateIndividual (double[][] population, int index, Func< double[], double > objective)
static double[] GetIndividual (double[][] population, int index)
static int FindMinIndex (double[] values)
static int SelectRandomIndex (Random rng, int popSize, params int[] exclude)
static double ComputeStandardDeviation (double[] values)
static OptimizationResult CreateResult (double[] x, double objectiveValue, int iterations, OptimizationStatus status)
Detailed Description
Production-grade Differential Evolution optimizer for global optimization. Component ID: STPR005A.
Particularly effective for non-convex, multi-modal objective functions. DE is a population-based stochastic optimization algorithm that:
Doesn't require gradient information
Handles non-smooth, non-convex objectives
Good at escaping local minima
Robust for calibrating jump-diffusion models (Heston, Kou)
Mutation Strategy: DE/rand/1/bin (standard, most widely used)
Library Status: Custom implementation maintained in-house. Neither MathNet.Numerics nor Accord.Math provide DE optimization.
Definition at line 37 of file STPR005A.cs.
Member Function Documentation
ComputeStandardDeviation()
static double Alaris.Strategy.Core.Numerical.STPR005A.ComputeStandardDeviation (double[] values) inline static private
Definition at line 263 of file STPR005A.cs.
Referenced by Alaris.Strategy.Core.Numerical.STPR005A.Minimize().
CreateResult()
static OptimizationResult Alaris.Strategy.Core.Numerical.STPR005A.CreateResult (double[] x, double objectiveValue, int iterations, OptimizationStatus status) inline static private
Definition at line 270 of file STPR005A.cs.
Referenced by Alaris.Strategy.Core.Numerical.STPR005A.Minimize().
EvaluateIndividual()
static double Alaris.Strategy.Core.Numerical.STPR005A.EvaluateIndividual (double population[][], int index, Func< double[], double > objective) inline static private
Definition at line 224 of file STPR005A.cs.
Referenced by Alaris.Strategy.Core.Numerical.STPR005A.Minimize().
FindMinIndex()
static int Alaris.Strategy.Core.Numerical.STPR005A.FindMinIndex (double[] values) inline static private
Definition at line 234 of file STPR005A.cs.
Referenced by Alaris.Strategy.Core.Numerical.STPR005A.Minimize().
GetIndividual()
static double[] Alaris.Strategy.Core.Numerical.STPR005A.GetIndividual (double population[][], int index) inline static private
Definition at line 229 of file STPR005A.cs.
Referenced by Alaris.Strategy.Core.Numerical.STPR005A.Minimize().
Minimize()
OptimizationResult Alaris.Strategy.Core.Numerical.STPR005A.Minimize (Func< double[], double > objective, double[] lowerBounds, double[] upperBounds) inline
Minimizes an objective function using Differential Evolution.
Parameters
objective Objective function to minimize.
lowerBounds Lower bounds for parameters (required).
upperBounds Upper bounds for parameters (required).
Returns
Optimization result.
Definition at line 78 of file STPR005A.cs.
References Alaris.Strategy.Core.Numerical.STPR005A.ComputeStandardDeviation(), Alaris.Strategy.Core.Numerical.STPR005A.CreateResult(), Alaris.Strategy.Core.Numerical.STPR005A.CrossoverProbability, Alaris.Strategy.Core.Numerical.STPR005A.DifferentialWeight, Alaris.Strategy.Core.Numerical.STPR005A.EvaluateIndividual(), Alaris.Strategy.Core.Numerical.STPR005A.FindMinIndex(), Alaris.Strategy.Core.Numerical.STPR005A.GetIndividual(), Alaris.Strategy.Core.Numerical.STPR005A.MaxGenerations, Alaris.Strategy.Core.Numerical.STPR005A.PopulationSize, Alaris.Strategy.Core.Numerical.STPR005A.RandomSeed, Alaris.Strategy.Core.Numerical.STPR005A.SelectRandomIndex(), and Alaris.Strategy.Core.Numerical.STPR005A.Tolerance.
SelectRandomIndex()
static int Alaris.Strategy.Core.Numerical.STPR005A.SelectRandomIndex (Random rng, int popSize, params int[] exclude) inline static private
Definition at line 249 of file STPR005A.cs.
Referenced by Alaris.Strategy.Core.Numerical.STPR005A.Minimize().
Property Documentation
CrossoverProbability
double Alaris.Strategy.Core.Numerical.STPR005A.CrossoverProbability = 0.9 get set
Crossover probability CR ∈ [0, 1], typically 0.9. Controls the fraction of parameter values copied from the mutant.
Definition at line 59 of file STPR005A.cs.
Referenced by Alaris.Strategy.Core.Numerical.STPR005A.Minimize().
DifferentialWeight
double Alaris.Strategy.Core.Numerical.STPR005A.DifferentialWeight = 0.8 get set
Differential weight F ∈ [0, 2], typically 0.8. Controls the amplification of differential variation.
Definition at line 53 of file STPR005A.cs.
Referenced by Alaris.Strategy.Core.Numerical.STPR005A.Minimize().
MaxGenerations
int Alaris.Strategy.Core.Numerical.STPR005A.MaxGenerations = 500 get set
Maximum number of generations.
Definition at line 47 of file STPR005A.cs.
Referenced by Alaris.Strategy.Core.Numerical.STPR005A.Minimize().
PopulationSize
int Alaris.Strategy.Core.Numerical.STPR005A.PopulationSize get set
Population size (typically 10 * dimension). 0 means auto-select.
Definition at line 42 of file STPR005A.cs.
Referenced by Alaris.Strategy.Core.Numerical.STPR005A.Minimize().
RandomSeed
int? Alaris.Strategy.Core.Numerical.STPR005A.RandomSeed get set
Random number generator seed (null for random).
Definition at line 69 of file STPR005A.cs.
Referenced by Alaris.Strategy.Core.Numerical.STPR005A.Minimize().
Tolerance
double Alaris.Strategy.Core.Numerical.STPR005A.Tolerance = 1e-6 get set
Tolerance for convergence (standard deviation of population objective values).
Definition at line 64 of file STPR005A.cs.
Referenced by Alaris.Strategy.Core.Numerical.STPR005A.Minimize().
The documentation for this class was generated from the following file:
src/Alaris.Strategy/Core/Numerical/STPR005A.cs