Alaris: Alaris.Test.Unit.Core.Pricing.CREN003ATests Class Reference
Alaris.Test.Unit.Core.Pricing.CREN003ATests Class Reference
First-principles tests for unified American option pricing engine.
Public Member Functions
CREN003ATests ()
void Price_AmericanGreaterThanOrEqualEuropean (double spot, double strike, double tau, double sigma, double r, double q)
void Price_AtLeastIntrinsicValue (double spot, double strike, double tau, double sigma, double r, double q)
void Delta_InValidRange (double spot, double strike, double tau, double sigma, double r, double q)
void Gamma_NonNegative (double spot, double strike, double tau, double sigma, double r, double q)
void Vega_NonNegative (double spot, double strike, double tau, double sigma, double r, double q)
void Classify_StandardRegime (double r, double q, bool isCall)
void Classify_DoubleBoundaryRegime (double r, double q, bool isCall)
void PriceWithDetails_IncludesAllGreeks ()
void PriceWithDetails_NegativeRateRegime_ClassifiesCorrectly ()
void Price_NearExpiryOption_StillValid ()
void Price_DeepITM_ConvergesToIntrinsic ()
Private Attributes
readonly CREN003A _engine
Static Private Attributes
const double Tolerance = 1e-6
Detailed Description
First-principles tests for unified American option pricing engine.
Definition at line 20 of file CREN003ATests.cs.
Constructor & Destructor Documentation
CREN003ATests()
Alaris.Test.Unit.Core.Pricing.CREN003ATests.CREN003ATests () inline
Definition at line 25 of file CREN003ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN003ATests._engine.
Member Function Documentation
Classify_DoubleBoundaryRegime()
void Alaris.Test.Unit.Core.Pricing.CREN003ATests.Classify_DoubleBoundaryRegime (double r, double q, bool isCall) inline
Definition at line 153 of file CREN003ATests.cs.
References Alaris.Core.Pricing.CRRE001A.Classify().
Classify_StandardRegime()
void Alaris.Test.Unit.Core.Pricing.CREN003ATests.Classify_StandardRegime (double r, double q, bool isCall) inline
Definition at line 144 of file CREN003ATests.cs.
References Alaris.Core.Pricing.CRRE001A.Classify().
Delta_InValidRange()
void Alaris.Test.Unit.Core.Pricing.CREN003ATests.Delta_InValidRange (double spot, double strike, double tau, double sigma, double r, double q) inline
Definition at line 91 of file CREN003ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN003ATests._engine, Alaris.Core.Pricing.CREN003A.Delta(), and Alaris.Test.Unit.Core.Pricing.CREN003ATests.Tolerance.
Gamma_NonNegative()
void Alaris.Test.Unit.Core.Pricing.CREN003ATests.Gamma_NonNegative (double spot, double strike, double tau, double sigma, double r, double q) inline
Definition at line 110 of file CREN003ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN003ATests._engine, Alaris.Core.Pricing.CREN003A.Gamma(), and Alaris.Test.Unit.Core.Pricing.CREN003ATests.Tolerance.
Price_AmericanGreaterThanOrEqualEuropean()
void Alaris.Test.Unit.Core.Pricing.CREN003ATests.Price_AmericanGreaterThanOrEqualEuropean (double spot, double strike, double tau, double sigma, double r, double q) inline
Definition at line 38 of file CREN003ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN003ATests._engine, Alaris.Core.Math.CRMF001A.BSPrice(), Alaris.Core.Pricing.CREN003A.Price(), and Alaris.Test.Unit.Core.Pricing.CREN003ATests.Tolerance.
Price_AtLeastIntrinsicValue()
void Alaris.Test.Unit.Core.Pricing.CREN003ATests.Price_AtLeastIntrinsicValue (double spot, double strike, double tau, double sigma, double r, double q) inline
Definition at line 63 of file CREN003ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN003ATests._engine, and Alaris.Core.Pricing.CREN003A.Price().
Price_DeepITM_ConvergesToIntrinsic()
void Alaris.Test.Unit.Core.Pricing.CREN003ATests.Price_DeepITM_ConvergesToIntrinsic () inline
Definition at line 220 of file CREN003ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN003ATests._engine, and Alaris.Core.Pricing.CREN003A.Price().
Price_NearExpiryOption_StillValid()
void Alaris.Test.Unit.Core.Pricing.CREN003ATests.Price_NearExpiryOption_StillValid () inline
Definition at line 200 of file CREN003ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN003ATests._engine, and Alaris.Core.Pricing.CREN003A.Price().
PriceWithDetails_IncludesAllGreeks()
void Alaris.Test.Unit.Core.Pricing.CREN003ATests.PriceWithDetails_IncludesAllGreeks () inline
Definition at line 164 of file CREN003ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN003ATests._engine, Alaris.Core.Pricing.UnifiedPricingResult.Delta, Alaris.Core.Pricing.UnifiedPricingResult.EarlyExercisePremium, Alaris.Core.Pricing.UnifiedPricingResult.Gamma, Alaris.Core.Pricing.UnifiedPricingResult.Method, Alaris.Core.Pricing.UnifiedPricingResult.Price, Alaris.Core.Pricing.CREN003A.PriceWithDetails(), Alaris.Core.Pricing.UnifiedPricingResult.Regime, Alaris.Core.Pricing.UnifiedPricingResult.Rho, Alaris.Core.Pricing.UnifiedPricingResult.Theta, and Alaris.Core.Pricing.UnifiedPricingResult.Vega.
PriceWithDetails_NegativeRateRegime_ClassifiesCorrectly()
void Alaris.Test.Unit.Core.Pricing.CREN003ATests.PriceWithDetails_NegativeRateRegime_ClassifiesCorrectly () inline
Definition at line 185 of file CREN003ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN003ATests._engine, Alaris.Core.Pricing.CREN003A.PriceWithDetails(), and Alaris.Core.Pricing.UnifiedPricingResult.Regime.
Vega_NonNegative()
void Alaris.Test.Unit.Core.Pricing.CREN003ATests.Vega_NonNegative (double spot, double strike, double tau, double sigma, double r, double q) inline
Definition at line 125 of file CREN003ATests.cs.
References Alaris.Test.Unit.Core.Pricing.CREN003ATests._engine, Alaris.Test.Unit.Core.Pricing.CREN003ATests.Tolerance, and Alaris.Core.Pricing.CREN003A.Vega().
Member Data Documentation
_engine
readonly CREN003A Alaris.Test.Unit.Core.Pricing.CREN003ATests._engine private
Definition at line 22 of file CREN003ATests.cs.
Referenced by Alaris.Test.Unit.Core.Pricing.CREN003ATests.CREN003ATests(), Alaris.Test.Unit.Core.Pricing.CREN003ATests.Delta_InValidRange(), Alaris.Test.Unit.Core.Pricing.CREN003ATests.Gamma_NonNegative(), Alaris.Test.Unit.Core.Pricing.CREN003ATests.Price_AmericanGreaterThanOrEqualEuropean(), Alaris.Test.Unit.Core.Pricing.CREN003ATests.Price_AtLeastIntrinsicValue(), Alaris.Test.Unit.Core.Pricing.CREN003ATests.Price_DeepITM_ConvergesToIntrinsic(), Alaris.Test.Unit.Core.Pricing.CREN003ATests.Price_NearExpiryOption_StillValid(), Alaris.Test.Unit.Core.Pricing.CREN003ATests.PriceWithDetails_IncludesAllGreeks(), Alaris.Test.Unit.Core.Pricing.CREN003ATests.PriceWithDetails_NegativeRateRegime_ClassifiesCorrectly(), and Alaris.Test.Unit.Core.Pricing.CREN003ATests.Vega_NonNegative().
Tolerance
const double Alaris.Test.Unit.Core.Pricing.CREN003ATests.Tolerance = 1e-6 static private
Definition at line 23 of file CREN003ATests.cs.
Referenced by Alaris.Test.Unit.Core.Pricing.CREN003ATests.Delta_InValidRange(), Alaris.Test.Unit.Core.Pricing.CREN003ATests.Gamma_NonNegative(), Alaris.Test.Unit.Core.Pricing.CREN003ATests.Price_AmericanGreaterThanOrEqualEuropean(), and Alaris.Test.Unit.Core.Pricing.CREN003ATests.Vega_NonNegative().
The documentation for this class was generated from the following file:
src/Alaris.Test/Unit/Core/Pricing/CREN003ATests.cs